-- Create GL Account to Income Statement Item Code Lookup Table
-- This table maps GL accounts to their respective income statement categories and item codes
-- Significantly improves query performance by avoiding repeated CASE statements

-- Create lookup table
CREATE TABLE INCOME_STATEMENT_GL_LOOKUP (
    GL_ACCOUNT VARCHAR(20) NOT NULL,
    CATEGORY VARCHAR(50) NOT NULL,
    ITEM_CODE INTEGER,
    DESCRIPTION VARCHAR(200),
    PRIMARY KEY (GL_ACCOUNT, CATEGORY)
);

-- Create index for fast lookups
CREATE INDEX IDX_IS_GL_CATEGORY ON INCOME_STATEMENT_GL_LOOKUP(CATEGORY, ITEM_CODE);
CREATE INDEX IDX_IS_GL_ACCOUNT ON INCOME_STATEMENT_GL_LOOKUP(GL_ACCOUNT);

-- Insert D46: Interest Income mappings
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400010001', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400010005', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400020001', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400020012', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400030001', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400030002', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400030003', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400030005', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400040001', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400040002', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400040003', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400040006', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400030007', 'INTEREST_INCOME', 1, 'Interest on loans and advances');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400030009', 'INTEREST_INCOME', 1, 'Interest on loans and advances');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('408010001', 'INTEREST_INCOME', 2, 'Interest on interbank loans');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('404020001', 'INTEREST_INCOME', 3, 'Interest on govt debt securities');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400060001', 'INTEREST_INCOME', 6, 'Interest on balance with other banks');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400060002', 'INTEREST_INCOME', 6, 'Interest on balance with other banks');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400060005', 'INTEREST_INCOME', 6, 'Interest on balance with other banks');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400060004', 'INTEREST_INCOME', 6, 'Interest on balance with other banks');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400061001', 'INTEREST_INCOME', 6, 'Interest on balance with other banks');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('400070003', 'INTEREST_INCOME', 6, 'Interest on balance with other banks');

-- Item code 11: Pattern-based (401%, 402%, 403%) - handled in query

-- Insert D47: Interest Expenses mappings
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220001', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220002', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220003', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220004', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220005', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220006', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220009', 'INTEREST_EXPENSE', 1, 'Interest on deposits');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600220010', 'INTEREST_EXPENSE', 1, 'Interest on deposits');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('602010001', 'INTEREST_EXPENSE', 5, 'Interest on govt deposits');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600230001', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600230002', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600230003', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600230004', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600230005', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600230006', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('600240001', 'INTEREST_EXPENSE', 11, 'Other interest expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('601060001', 'INTEREST_EXPENSE', 11, 'Other interest expenses');

-- Insert D48: Non-Interest Income mappings
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505040001', 'NON_INTEREST_INCOME', 1, 'Fees and commissions');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505040002', 'NON_INTEREST_INCOME', 1, 'Fees and commissions');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505040006', 'NON_INTEREST_INCOME', 1, 'Fees and commissions');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505040009', 'NON_INTEREST_INCOME', 1, 'Fees and commissions');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020055', 'NON_INTEREST_INCOME', 4, 'Foreign exchange gains');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020056', 'NON_INTEREST_INCOME', 4, 'Foreign exchange gains');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020058', 'NON_INTEREST_INCOME', 4, 'Foreign exchange gains');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500010009', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500010010', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500010015', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020003', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020010', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020011', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020014', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020015', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020016', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020018', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020019', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020020', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020027', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020030', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020036', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020038', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020062', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020065', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020070', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('502010001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('503010001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('503010011', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('503010012', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504040001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504040002', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504050001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504060001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504080001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504100001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504110001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504120002', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('504130001', 'NON_INTEREST_INCOME', 5, 'Other non-interest income');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('500020017', 'NON_INTEREST_INCOME', 20, 'Miscellaneous income');

-- Insert D49: Non-Interest Expenses mappings
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700010001', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700010004', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700010005', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700020002', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700030001', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700040002', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700050001', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700060001', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090001', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090005', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090009', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090006', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090011', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090013', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090015', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701020001', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701020005', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701020006', 'NON_INTEREST_EXPENSE', 1, 'Staff costs');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010001', 'NON_INTEREST_EXPENSE', 5, 'Directors emoluments');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('703020001', 'NON_INTEREST_EXPENSE', 7, 'Depreciation');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('703020004', 'NON_INTEREST_EXPENSE', 8, 'Amortization');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('703020006', 'NON_INTEREST_EXPENSE', 8, 'Amortization');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('703020008', 'NON_INTEREST_EXPENSE', 8, 'Amortization');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('703020011', 'NON_INTEREST_EXPENSE', 8, 'Amortization');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010009', 'NON_INTEREST_EXPENSE', 9, 'Audit fees');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705020001', 'NON_INTEREST_EXPENSE', 12, 'Rent and rates');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705070001', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705100004', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705110003', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705100003', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705110002', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705110004', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705110005', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705110006', 'NON_INTEREST_EXPENSE', 13, 'Insurance');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705110007', 'NON_INTEREST_EXPENSE', 13, 'Insurance');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705080002', 'NON_INTEREST_EXPENSE', 23, 'IT expenses');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705040001', 'NON_INTEREST_EXPENSE', 24, 'Marketing and advertising');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705040009', 'NON_INTEREST_EXPENSE', 24, 'Marketing and advertising');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705040011', 'NON_INTEREST_EXPENSE', 24, 'Marketing and advertising');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090003', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('700090004', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010002', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010003', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010006', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010008', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010012', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010013', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('701010010', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702010002', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702030001', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702030003', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702030004', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702040002', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702040004', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('702040006', 'NON_INTEREST_EXPENSE', 25, 'Other operating expenses');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705050001', 'NON_INTEREST_EXPENSE', 36, 'Legal and professional fees');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705060002', 'NON_INTEREST_EXPENSE', 36, 'Legal and professional fees');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705060004', 'NON_INTEREST_EXPENSE', 36, 'Legal and professional fees');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705090001', 'NON_INTEREST_EXPENSE', 36, 'Legal and professional fees');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705010001', 'NON_INTEREST_EXPENSE', 37, 'Communication costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705010002', 'NON_INTEREST_EXPENSE', 37, 'Communication costs');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705010003', 'NON_INTEREST_EXPENSE', 37, 'Communication costs');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705120001', 'NON_INTEREST_EXPENSE', 39, 'Training and development');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705120005', 'NON_INTEREST_EXPENSE', 39, 'Training and development');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705120006', 'NON_INTEREST_EXPENSE', 39, 'Training and development');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705160001', 'NON_INTEREST_EXPENSE', 40, 'Other expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705160002', 'NON_INTEREST_EXPENSE', 40, 'Other expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705160003', 'NON_INTEREST_EXPENSE', 40, 'Other expenses');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705170001', 'NON_INTEREST_EXPENSE', 40, 'Other expenses');

-- Insert D50: Non-Core Credits and Charges mappings
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505070001', 'NON_CORE_CREDITS', 1, 'Gain/loss on disposal');

INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505010001', 'NON_CORE_CREDITS', 3, 'Other non-core items');

-- Insert Single Value Fields
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705190003', 'BAD_DEBTS', NULL, 'Bad debts written off not provided');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705190002', 'PROVISION', NULL, 'Provision for bad and doubtful debts');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('705190001', 'IMPAIRMENT', NULL, 'Impairments of investments');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704010001', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704020001', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704020002', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704020004', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704020007', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704020012', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704020013', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('704030004', 'TAX', NULL, 'Income tax provision');
INSERT INTO INCOME_STATEMENT_GL_LOOKUP VALUES ('505000000', 'EXTRAORDINARY', NULL, 'Extraordinary credits/charges');

-- Verify data
SELECT CATEGORY, ITEM_CODE, COUNT(*) as account_count
FROM INCOME_STATEMENT_GL_LOOKUP
GROUP BY CATEGORY, ITEM_CODE
ORDER BY CATEGORY, ITEM_CODE;

-- Show summary
SELECT 
    'Total GL accounts mapped' as metric,
    COUNT(*) as value
FROM INCOME_STATEMENT_GL_LOOKUP
UNION ALL
SELECT 
    'Unique categories' as metric,
    COUNT(DISTINCT CATEGORY) as value
FROM INCOME_STATEMENT_GL_LOOKUP;
