-- DB2 Summary Query for Balance with Other Banks Pipeline
SELECT COUNT(*) as record_count
FROM GLI_TRX_EXTRACT gte
         LEFT JOIN GLG_ACCOUNT gl ON gte.FK_GLG_ACCOUNTACCO = gl.ACCOUNT_ID
         LEFT JOIN CUSTOMER c ON gte.CUST_ID = c.CUST_ID
         LEFT JOIN PROFITS_ACCOUNT pa ON gte.CUST_ID = pa.CUST_ID AND pa.PRFT_SYSTEM = 3
WHERE gl.EXTERNAL_GLACCOUNT IN ('100050001', '100013000', '100050000')
  AND pa.ACCOUNT_NUMBER <> ''