SELECT *
FROM BANKEMPLOYEE
WHERE STAFF_NO IS NOT NULL
  AND STAFF_NO = TRIM(STAFF_NO)
  AND LENGTH(TRIM(STAFF_NO)) = 8
  AND EMPL_STATUS = 1
  AND STAFF_NO NOT LIKE 'ATMUSER%'
  AND STAFF_NO NOT LIKE '993%'
  AND STAFF_NO NOT LIKE '999%'
  AND STAFF_NO NOT LIKE 'I00%'
  AND STAFF_NO NOT LIKE 'IAP%'
  AND STAFF_NO NOT LIKE 'MCB%'
  AND STAFF_NO NOT LIKE 'MIP%'
  AND STAFF_NO NOT LIKE 'MOB%'
  AND STAFF_NO NOT LIKE 'MWL%'
  AND STAFF_NO NOT LIKE 'OWP%'
  AND STAFF_NO NOT LIKE 'PI0%'
  AND STAFF_NO NOT LIKE 'POS%'
  AND STAFF_NO NOT LIKE 'STP%'
  AND STAFF_NO NOT LIKE 'TER%';
