CREATE TABLE COMPLAINT_REGISTER (
    COMPLAINT_ID        INTEGER         NOT NULL GENERATED ALWAYS AS IDENTITY,
    CATEGORY            VARCHAR(50),
    ACCOUNT_NUMBER      VARCHAR(20),
    CUSTOMER_NAME       VARCHAR(100),
    CONTACT_NUMBER      VARCHAR(20),
    REGION              VARCHAR(50),
    LOGGED_BY           VARCHAR(50),
    LOGGED_DATE         DATE,
    RECEIVED_VIA        VARCHAR(30),
    CASE_DESCRIPTION    VARCHAR(2000),
    NATURE_OF_COMPLAINT VARCHAR(100),
    SERVICE_NAME        VARCHAR(100),
    WORKING_AGE         SMALLINT,
    RESOLUTION_INFO     VARCHAR(2000),
    STATUS              VARCHAR(20),
    CLOSING_DATE        DATE,
    TAT_STATUS          VARCHAR(20),
    CUSTOMER_SEGMENT    VARCHAR(50),
    QUERY_OWNER         VARCHAR(50),
    TMSTAMP             TIMESTAMP       NOT NULL DEFAULT CURRENT TIMESTAMP,

    CONSTRAINT PK_COMPLAINT_REGISTER PRIMARY KEY (COMPLAINT_ID)
);

-- Optional: Add a check constraint on STATUS
ALTER TABLE COMPLAINT_REGISTER
    ADD CONSTRAINT CHK_STATUS CHECK (STATUS IN ('OPEN', 'CLOSED', 'PENDING', 'ESCALATED'));

-- Optional: Index on ACCOUNT_NUMBER for faster lookups
CREATE INDEX IDX_COMPLAINT_ACCOUNT ON COMPLAINT_REGISTER (ACCOUNT_NUMBER);

-- Optional: Index on LOGGED_DATE for date range queries
CREATE INDEX IDX_COMPLAINT_DATE ON COMPLAINT_REGISTER (LOGGED_DATE);