SELECT CURRENT_TIMESTAMP        AS reportingDate,
       c.SURNAME                AS companyName,
       c.CUST_ID                AS customerIdentificationNumber,
       NULL                     AS smrCode,
       pa.ACCOUNT_NUMBER        AS accountNumber,
       cu.SHORT_DESCR           AS currency,
       NULL                     AS accountOperationStatus,
       NULL                     AS establishmentDate,
       NULL                     AS legalForm,
       NULL                     AS negativeClientStatus,
       NULL                     AS numberOfEmployeesMale,
       NULL                     AS numberOfEmployeesFemale,
       NULL                     AS registrationCountry,
       NULL                     AS registrationNumber,
       wdc.TAX_REGISTRATION_NO  AS taxIdentificationNumber,
       NULL                     AS tradeName,
       NULL                     AS parentName,
       NULL                     AS parentIncorporationNumber,
       NULL                     AS groupId,
       NULL                     AS sectorClassificationSNA,
       NULL                     AS relatedPerson,
       wdc.TELEPHONE            AS cellPhone,
       wdc.NAME_STANDARD        AS fullName,
       NULL                     AS gender,
       NULL                     AS relationType,
       wdc.ID_NO                AS nationalID,
       wdc.NATIONAL_DESCRIPTION AS nationality,
       NULL                     AS appointmentDate,
       NULL                     AS terminationDate,
       NULL                     AS rateValueOfSharesOwned,
       NULL                     AS amountValueOfSharesOwned,
       NULL                     AS businessAddress,
       NULL                     AS postalCode,
       NULL                     AS region,
       NULL                     AS district,
       NULL                     AS ward,
       NULL                     AS street,
       NULL                     AS houseNumber,
       NULL                     AS primaryRegistrationAddress,
       NULL                     AS primaryPostalCode,
       NULL                     AS primaryRegion,
       NULL                     AS primaryDistrict,
       NULL                     AS primaryWard,
       NULL                     AS primaryStreet,
       NULL                     AS primaryHouseNumber,
       NULL                     AS country,
       NULL                     AS postalOfficeBox,
       NULL                     AS zipCode,
       NULL                     AS secondaryRegistrationAddress,
       NULL                     AS secondaryPostalCode,
       NULL                     AS secondaryRegion,
       NULL                     AS secondaryDistrict,
       NULL                     AS secondaryWard,
       NULL                     AS secondaryStreet,
       NULL                     AS secondaryHouseNumber,
       NULL                     AS structuredAddress,
       NULL                     AS textAddress,
       NULL                     AS companyContacts,
       wdc.TELEPHONE            AS mobileNumber,
       NULL                     AS alternativeMobileNumber,
       NULL                     AS fixedLineNumber,
       NULL                     AS faxNumber,
       NULL                     AS emailAddress,
       NULL                     AS socialMedia,
       NULL                     AS subjectRelationsEntity,
       NULL                     AS entityName,
       NULL                     AS entityType,
       NULL                     AS certificateIncorporation,
       NULL                     AS groupParentCode,
       NULL                     AS shareOwnedPercentage,
       NULL                     AS shareOwnedAmount
FROM (SELECT DISTINCT c.SURNAME,
                      c.CUST_ID,
                      c.FKCURR_THINKS_IN
      FROM CUSTOMER c
               INNER JOIN CUSTOMER_CATEGORY cc ON c.CUST_ID = cc.FK_CUSTOMERCUST_ID
      WHERE cc.FK_CATEGORYCATEGOR IN ('CMPTYPE', 'LAWSHAPE', 'COMTYPE')) c
         LEFT JOIN (SELECT *
                    FROM CURRENCY) cu ON c.FKCURR_THINKS_IN = cu.ID_CURRENCY
         LEFT JOIN (SELECT *
                    FROM PROFITS_ACCOUNT) pa ON pa.CUST_ID = c.CUST_ID AND PRFT_SYSTEM = 3
         INNER JOIN (SELECT CUST_ID,
                            MOBILE_TEL,
                            TAX_REGISTRATION_NO,
                            ID_NO,
                            NATIONAL_DESCRIPTION,
                            TELEPHONE,
                            NAME_STANDARD,
                            ROW_NUMBER() OVER (PARTITION BY CUST_ID ORDER BY CUST_ID) AS rn -- Keeps one row per customer
                     FROM W_DIM_CUSTOMER
                     WHERE CUST_TYPE_IND = 'Corporate') wdc ON wdc.CUST_ID = c.CUST_ID AND wdc.rn = 1
ORDER BY c.CUST_ID;