SELECT TO_CHAR(CURRENT_TIMESTAMP, 'DDMMYYYYHH24MI') as reportingDate,
       sc.CAPITAL_CATEGORY                          AS capitalCategory,
       sc.CAPITAL_SUBCATEGORY                       AS capitalSubCategory,
       VARCHAR_FORMAT(sc.TRANSACTION_DATE,'DDMMYYYYHHMM')                          AS transactionDate,
       sc.TRANSACTION_TYPE                          AS transactionType,
       sc.SHAREHOLDER_NAME                          AS shareholderNames,
       sc.CLIENT_TYPE                               AS clientType,
       sc.SHAREHOLDER_COUNTRY                       AS shareholderCountry,
       sc.NUMBER_OF_SHARES                          AS numberOfShares,
       sc.SHARE_PRICE_BOOK_VALUE                    AS sharePriceBookValue,
       sc.CURRENCY                                  AS currency,
       sc.ORG_AMOUNT                                AS orgAmount,
       sc.TZS_AMOUNT                                AS tzsAmount,
       sc.SECTOR_SNA_CLASSIFICATION                 AS sectorSnaClassification
FROM SHARE_CAPITAL sc;
