create table "0COSTCENTER_ATTR"
(
    "COAr"         VARCHAR(255),
    KOSTL          VARCHAR(255),
    "Valid To"     VARCHAR(255),
    "Valid From"   VARCHAR(255),
    "PersResp"     VARCHAR(255),
    "CoCd"         VARCHAR(255),
    "BusA"         VARCHAR(255),
    "CCtC"         VARCHAR(255),
    "Crcy"         VARCHAR(255),
    "Profit Ctr"   VARCHAR(255),
    "ActPri"       VARCHAR(255),
    "PlnPri"       VARCHAR(255),
    "User Resp."   VARCHAR(255),
    "CostSh"       VARCHAR(255),
    "Tax Jur"      VARCHAR(255),
    "Plnt"         VARCHAR(255),
    "LogSystem"    VARCHAR(255),
    "Created on"   VARCHAR(255),
    "Entered by"   VARCHAR(255),
    "ActSec"       VARCHAR(255),
    "ActRev"       VARCHAR(255),
    "Cmmt"         VARCHAR(255),
    "PlnSec"       VARCHAR(255),
    "PlnRev"       VARCHAR(255),
    AM             VARCHAR(255),
    "Qty"          VARCHAR(255),
    "Department"   VARCHAR(255),
    "SCtr"         VARCHAR(255),
    U              VARCHAR(255),
    "App"          VARCHAR(255),
    "OH key"       VARCHAR(255),
    "Cty"          VARCHAR(255),
    "Title"        VARCHAR(255),
    "Name"         VARCHAR(255),
    "Name 2"       VARCHAR(255),
    "Name 3"       VARCHAR(255),
    "Name 4"       VARCHAR(255),
    "City"         VARCHAR(255),
    "District"     VARCHAR(255),
    "Street"       VARCHAR(255),
    "PO Box"       VARCHAR(255),
    "PostCode"     VARCHAR(255),
    "POBoxpcd"     VARCHAR(255),
    "Rg"           VARCHAR(255),
    "Language"     VARCHAR(255),
    "Telebox"      VARCHAR(255),
    "Telephone1"   VARCHAR(255),
    "Telephone2"   VARCHAR(255),
    "FaxNumber"    VARCHAR(255),
    "Teletex"      VARCHAR(255),
    "Telex"        VARCHAR(255),
    "Data line"    VARCHAR(255),
    "Prin"         VARCHAR(255),
    "Area"         VARCHAR(255),
    "Key"          VARCHAR(255),
    "Complete"     VARCHAR(255),
    S              VARCHAR(255),
    "Objectnumber" VARCHAR(255),
    "Fct"          VARCHAR(255),
    "Afnc"         VARCHAR(255),
    "Template"     VARCHAR(255),
    "Template1"    VARCHAR(255),
    "FuncArea"     VARCHAR(255),
    "TemplAlloc"   VARCHAR(255),
    "TemplAlloc1"  VARCHAR(255),
    JV             VARCHAR(255),
    RI             VARCHAR(255),
    ET             VARCHAR(255),
    "Type"         VARCHAR(255),
    "Class"        VARCHAR(255),
    "SClA"         VARCHAR(255)
);

