create table ACC_REPRESENTIVE
(
    FK_BOUND_RELATION1 INTEGER,
    FK_BOUND_RELATION2 INTEGER,
    FK_BOUND_RELATIONS CHAR(12),
    FK_REPR_BENEFICIA1 INTEGER,
    FK_REPR_BENEFICIAR DECIMAL(11),
    REPRESENTATIVE_SN  SMALLINT,
    EFFECTIVE_FROM     DATE,
    EXPIRE_DATE        DATE,
    RESTRICT0          CHAR(1),
    CODE_NUMBER        CHAR(20),
    ENTRY_COMMENT      CHAR(30),
    ACCOUNT_NUMBER     DECIMAL(11)
);

create unique index IXP_ACC_001
    on ACC_REPRESENTIVE (FK_BOUND_RELATION1, FK_BOUND_RELATION2, FK_BOUND_RELATIONS, FK_REPR_BENEFICIA1,
                         FK_REPR_BENEFICIAR, REPRESENTATIVE_SN);

