create table ACC_TOT_TEMP
(
    ACCOUNT_NUMBER  DECIMAL(11),
    YEAR_ID         SMALLINT,
    MONTH_ID        SMALLINT,
    ID_PRODUCT      INTEGER,
    IN_ID_UNIT      INTEGER,
    IN_ID_CURRENCY  INTEGER,
    IN_TOTAL_DEBIT  DECIMAL(15, 2),
    IN_TOTAL_CREDIT DECIMAL(15, 2),
    INVENTORY       DECIMAL(15, 2),
    GL_ACCOUNT      CHAR(21)
);

create unique index IXP_ACC_002
    on ACC_TOT_TEMP (ACCOUNT_NUMBER, YEAR_ID, MONTH_ID);

