create table ACC_REPRESENTIVE_U
(
    FK_REPR_BENEFICIA1 INTEGER     not null,
    FK_REPR_BENEFICIAR DECIMAL(11) not null,
    FK_BOUND_RELATIONS CHAR(12)    not null,
    FK_BOUND_RELATION1 INTEGER     not null,
    FK_BOUND_RELATION2 INTEGER     not null,
    REPRESENTATIVE_SN  SMALLINT    not null,
    EFFECTIVE_FROM     DATE,
    EXPIRE_DATE        DATE,
    RESTRICT           CHAR(1),
    CODE_NUMBER        CHAR(20),
    ENTRY_COMMENT      CHAR(30),
    constraint IXU_CIU_002
        primary key (REPRESENTATIVE_SN, FK_BOUND_RELATION2, FK_BOUND_RELATION1, FK_BOUND_RELATIONS, FK_REPR_BENEFICIAR,
                     FK_REPR_BENEFICIA1)
);

