CREATE VIEW ACCOUNTING_RULE_VIEW
(
   ID,
   SNUM,
   POSITION,
   SUBSY,
   DESCRIPTION,
   HOME_BRANCH,
   GLACC_ORIGIN,
   AMOUNT_SER_NO,
   ENTRY_TYPE,
   AMOUNT_SIGN,
   FOREIGN_IND,
   LC_CONVERT_RATE,
   GLG_DOC_TYPE,
   GLG_DOC_ID,
   GLG_DOC_SER,
   GLG_JUSTIFY_ID,
   GLG_ACCOUNT_ID,
   BOP_FLAG
)
AS
   -- FORCE
   SELECT *
     FROM (  SELECT ID,                     SNUM,                     position,                     SUBSY,                      DESCRIPTION,                     HOME_BRANCH,                     glacc_origin,                      amount_ser_no,                     entry_type,                     amount_sign,                      foreign_ind,                     lc_convert_rate,                     glg_doc_type,                      glg_doc_id,                     glg_doc_ser,                     glg_justify_id,                      glg_account_id,                     bop_flag
               FROM (SELECT ID,
                            SNUM,
                            '1' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_01 HOME_BRANCH,
                            glacc_origin_01 glacc_origin,
                            amount_ser_no_01 amount_ser_no,
                            entry_type_01 entry_type,
                            amount_sign_01 amount_sign,
                            foreign_ind_01 foreign_ind,
                            lc_convert_rate_01 lc_convert_rate,
                            glg_doc_type_01 glg_doc_type,
                            glg_doc_id_01 glg_doc_id,
                            glg_doc_ser_01 glg_doc_ser,
                            glg_justify_id_01 glg_justify_id,
                            glg_account_01 glg_account_id,
                            bop_flag_01 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '2' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_02 HOME_BRANCH,
                            glacc_origin_02 glacc_origin,
                            amount_ser_no_02 amount_ser_no,
                            entry_type_02 entry_type,
                            amount_sign_02 amount_sign,
                            foreign_ind_02 foreign_ind,
                            lc_convert_rate_02 lc_convert_rate,
                            glg_doc_type_02 glg_doc_type,
                            glg_doc_id_02 glg_doc_id,
                            glg_doc_ser_02 glg_doc_ser,
                            glg_justify_id_02 glg_justify_id,
                            glg_account_02 glg_account_id,
                            bop_flag_02 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '3' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_03 HOME_BRANCH,
                            glacc_origin_03 glacc_origin,
                            amount_ser_no_03 amount_ser_no,
                            entry_type_03 entry_type,
                            amount_sign_03 amount_sign,
                            foreign_ind_03 foreign_ind,
                            lc_convert_rate_03 lc_convert_rate,
                            glg_doc_type_03 glg_doc_type,
                            glg_doc_id_03 glg_doc_id,
                            glg_doc_ser_03 glg_doc_ser,
                            glg_justify_id_03 glg_justify_id,
                            glg_account_03 glg_account_id,
                            bop_flag_03 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '4' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_04 HOME_BRANCH,
                            glacc_origin_04 glacc_origin,
                            amount_ser_no_04 amount_ser_no,
                            entry_type_04 entry_type,
                            amount_sign_04 amount_sign,
                            foreign_ind_04 foreign_ind,
                            lc_convert_rate_04 lc_convert_rate,
                            glg_doc_type_04 glg_doc_type,
                            glg_doc_id_04 glg_doc_id,
                            glg_doc_ser_04 glg_doc_ser,
                            glg_justify_id_04 glg_justify_id,
                            glg_account_04 glg_account_id,
                            bop_flag_04 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '5' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_05 HOME_BRANCH,
                            glacc_origin_05 glacc_origin,
                            amount_ser_no_05 amount_ser_no,
                            entry_type_05 entry_type,
                            amount_sign_05 amount_sign,
                            foreign_ind_05 foreign_ind,
                            lc_convert_rate_05 lc_convert_rate,
                            glg_doc_type_05 glg_doc_type,
                            glg_doc_id_05 glg_doc_id,
                            glg_doc_ser_05 glg_doc_ser,
                            glg_justify_id_05 glg_justify_id,
                            glg_account_05 glg_account_id,
                            bop_flag_05 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '6' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_06 HOME_BRANCH,
                            glacc_origin_06 glacc_origin,
                            amount_ser_no_06 amount_ser_no,
                            entry_type_06 entry_type,
                            amount_sign_06 amount_sign,
                            foreign_ind_06 foreign_ind,
                            lc_convert_rate_06 lc_convert_rate,
                            glg_doc_type_06 glg_doc_type,
                            glg_doc_id_06 glg_doc_id,
                            glg_doc_ser_06 glg_doc_ser,
                            glg_justify_id_06 glg_justify_id,
                            glg_account_06 glg_account_id,
                            bop_flag_06 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '7' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_07 HOME_BRANCH,
                            glacc_origin_07 glacc_origin,
                            amount_ser_no_07 amount_ser_no,
                            entry_type_07 entry_type,
                            amount_sign_07 amount_sign,
                            foreign_ind_07 foreign_ind,
                            lc_convert_rate_07 lc_convert_rate,
                            glg_doc_type_07 glg_doc_type,
                            glg_doc_id_07 glg_doc_id,
                            glg_doc_ser_07 glg_doc_ser,
                            glg_justify_id_07 glg_justify_id,
                            glg_account_07 glg_account_id,
                            bop_flag_07 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '8' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_08 HOME_BRANCH,
                            glacc_origin_08 glacc_origin,
                            amount_ser_no_08 amount_ser_no,
                            entry_type_08 entry_type,
                            amount_sign_08 amount_sign,
                            foreign_ind_08 foreign_ind,
                            lc_convert_rate_08 lc_convert_rate,
                            glg_doc_type_08 glg_doc_type,
                            glg_doc_id_08 glg_doc_id,
                            glg_doc_ser_08 glg_doc_ser,
                            glg_justify_id_08 glg_justify_id,
                            glg_account_08 glg_account_id,
                            bop_flag_08 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '9' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_09 HOME_BRANCH,
                            glacc_origin_09 glacc_origin,
                            amount_ser_no_09 amount_ser_no,
                            entry_type_09 entry_type,
                            amount_sign_09 amount_sign,
                            foreign_ind_09 foreign_ind,
                            lc_convert_rate_09 lc_convert_rate,
                            glg_doc_type_09 glg_doc_type,
                            glg_doc_id_09 glg_doc_id,
                            glg_doc_ser_09 glg_doc_ser,
                            glg_justify_id_09 glg_justify_id,
                            glg_account_09 glg_account_id,
                            bop_flag_09 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '10' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_10 HOME_BRANCH,
                            glacc_origin_10 glacc_origin,
                            amount_ser_no_10 amount_ser_no,
                            entry_type_10 entry_type,
                            amount_sign_10 amount_sign,
                            foreign_ind_10 foreign_ind,
                            lc_convert_rate_10 lc_convert_rate,
                            glg_doc_type_10 glg_doc_type,
                            glg_doc_id_10 glg_doc_id,
                            glg_doc_ser_10 glg_doc_ser,
                            glg_justify_id_10 glg_justify_id,
                            glg_account_10 glg_account_id,
                            bop_flag_10 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '11' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_11 HOME_BRANCH,
                            glacc_origin_11 glacc_origin,
                            amount_ser_no_11 amount_ser_no,
                            entry_type_11 entry_type,
                            amount_sign_11 amount_sign,
                            foreign_ind_11 foreign_ind,
                            lc_convert_rate_11 lc_convert_rate,
                            glg_doc_type_11 glg_doc_type,
                            glg_doc_id_11 glg_doc_id,
                            glg_doc_ser_11 glg_doc_ser,
                            glg_justify_id_11 glg_justify_id,
                            glg_account_11 glg_account_id,
                            bop_flag_11 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '12' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_12 HOME_BRANCH,
                            glacc_origin_12 glacc_origin,
                            amount_ser_no_12 amount_ser_no,
                            entry_type_12 entry_type,
                            amount_sign_12 amount_sign,
                            foreign_ind_12 foreign_ind,
                            lc_convert_rate_12 lc_convert_rate,
                            glg_doc_type_12 glg_doc_type,
                            glg_doc_id_12 glg_doc_id,
                            glg_doc_ser_12 glg_doc_ser,
                            glg_justify_id_12 glg_justify_id,
                            glg_account_12 glg_account_id,
                            bop_flag_12 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '13' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_13 HOME_BRANCH,
                            glacc_origin_13 glacc_origin,
                            amount_ser_no_13 amount_ser_no,
                            entry_type_13 entry_type,
                            amount_sign_13 amount_sign,
                            foreign_ind_13 foreign_ind,
                            lc_convert_rate_13 lc_convert_rate,
                            glg_doc_type_13 glg_doc_type,
                            glg_doc_id_13 glg_doc_id,
                            glg_doc_ser_13 glg_doc_ser,
                            glg_justify_id_13 glg_justify_id,
                            glg_account_13 glg_account_id,
                            bop_flag_13 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '14' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_14 HOME_BRANCH,
                            glacc_origin_14 glacc_origin,
                            amount_ser_no_14 amount_ser_no,
                            entry_type_14 entry_type,
                            amount_sign_14 amount_sign,
                            foreign_ind_14 foreign_ind,
                            lc_convert_rate_14 lc_convert_rate,
                            glg_doc_type_14 glg_doc_type,
                            glg_doc_id_14 glg_doc_id,
                            glg_doc_ser_14 glg_doc_ser,
                            glg_justify_id_14 glg_justify_id,
                            glg_account_14 glg_account_id,
                            bop_flag_14 bop_flag
                       FROM ACCOUNTING_RULE
                     UNION
                     SELECT ID,
                            SNUM,
                            '15' position,
                            SUBSY,
                            DESCRIPTION,
                            HOME_BRANCH_15 HOME_BRANCH,
                            glacc_origin_15 glacc_origin,
                            amount_ser_no_15 amount_ser_no,
                            entry_type_15 entry_type,
                            amount_sign_15 amount_sign,
                            foreign_ind_15 foreign_ind,
                            lc_convert_rate_15 lc_convert_rate,
                            glg_doc_type_15 glg_doc_type,
                            glg_doc_id_15 glg_doc_id,
                            glg_doc_ser_15 glg_doc_ser,
                            glg_justify_id_15 glg_justify_id,
                            glg_account_15 glg_account_id,
                            bop_flag_15 bop_flag
                       FROM ACCOUNTING_RULE)
              WHERE HOME_BRANCH IN ('0', '1', '2')
           ORDER BY ID, SNUM, TO_NUMBER (POSITION));

