create table ACH_HANDLING
(
    FK_REFERS_CLAGENT  INTEGER,
    FK_MAXAMOUNT_CURRE INTEGER,
    AMOUNT             DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    CHEQUE_END_ISSUE_D DATE,
    CHEQUE_END_TRX_DAT DATE,
    AUTO_EURO_CONVERT  CHAR(1)
);

create unique index IXU_ACH_001
    on ACH_HANDLING (FK_REFERS_CLAGENT, FK_MAXAMOUNT_CURRE);

