CREATE VIEW ACTIVE_TERM_DEPOSITS_06_12_VW  (     MONOTORING_UNIT,     UNIT_NAME,     DURATION_DAYS_TO,     ACCOUNT_NUMBER,     ACCOUNT_CD,     CUST_ID,     C_DIGIT,     MOVEMENT_CURRENCY,     PRODUCT_ID,     DAYS_DURATION,     FKGD_CATEGORY,     BOOK_BALANCE,     ACCR_CR_INTEREST,     CR_INT_ACCR_GL_ACC,     GL_ACCOUNT,     CALCULAT_CURRENCY_FIX_RATE$  )  AS       SELECT                                                         --DISTINCT
            --tab_to_string(t_varchar2_tab(
            profits_account.monotoring_unit,              unit.unit_name,              td_duration_gl.duration_days_to,              profits_account.account_number,              profits_account.account_cd,              profits_account.cust_id,              profits_account.c_digit,              profits_account.movement_currency,              profits_account.product_id,              time_depos_renewal.days_duration,              r_deposit_account.fkgd_category,              r_deposit_account.book_balance,              r_deposit_account.accr_cr_interest,              td_duration_gl.cr_int_accr_gl_acc,              td_duration_gl.gl_account,              get_fixing_rate (profits_account.movement_currency)                 calculat_currency_fix_rate$         --))
       FROM r_deposit_account r_deposit_account,              profits_account profits_account,              td_duration_gl td_duration_gl,              time_depos_renewal time_depos_renewal /*          ,td_int_accr_reslts*/                                                   ,              r_time_depos_renew,              bank_parameters,              unit        WHERE     profits_account.dep_acc_number =                     r_deposit_account.account_number              AND profits_account.monotoring_unit = unit.code              AND r_deposit_account.account_number =                     time_depos_renewal.fk_deposit_accoacc              AND r_deposit_account.renewal_number =                     time_depos_renewal.renewal_ser_num              AND time_depos_renewal.entry_status = '1'              AND r_deposit_account.entry_status != '0'              AND r_deposit_account.entry_status != '3'              AND r_deposit_account.entry_status != '4'              /*       AND TO_NUMBER(bank_parameters.prev_trx_date - td_int_accr_reslts.last_int_calc_date) + 1 <
                                   td_duration_gl.duration_days_to
            */              AND   TO_NUMBER (                         bank_parameters.prev_trx_date                       - r_time_depos_renew.last_int_calc_date)                  + 1 < td_duration_gl.duration_days_to              AND time_depos_renewal.days_duration <=                     td_duration_gl.duration_days_to              AND r_deposit_account.fk_depositfk_produ =                     td_duration_gl.fk_depositfk_produ              AND r_deposit_account.fkgd_category =                     td_duration_gl.fk_generic_detaser              AND (    (r_deposit_account.deposit_type = '2')                   AND (profits_account.prft_system = 3))              /*       AND td_int_accr_reslts.account_number = r_deposit_account.account_number*/              AND r_deposit_account.account_number =                     profits_account.dep_acc_number              /*       AND td_int_accr_reslts.trx_date IN (SELECT   MAX(trx_date)
                                                              FROM     td_int_accr_reslts
                                                       WHERE    td_int_accr_reslts.account_number = r_deposit_account.account_number)
            */              AND td_duration_gl.duration_days_to =                     (SELECT MIN (b.duration_days_to)                        FROM td_duration_gl b                       WHERE     b.fk_depositfk_produ =                                    td_duration_gl.fk_depositfk_produ                             AND b.fk_generic_detaser =                                    td_duration_gl.fk_generic_detaser                             AND b.duration_days_to >=                                    time_depos_renewal.days_duration)              AND r_deposit_account.renewal_number =                     r_time_depos_renew.renewal_ser_num              AND r_deposit_account.account_number =                     r_time_depos_renew.fk_deposit_accoacc     GROUP BY profits_account.monotoring_unit,              unit.unit_name,              td_duration_gl.duration_days_to,              profits_account.account_number,              profits_account.account_cd,              profits_account.cust_id,              profits_account.c_digit,              profits_account.movement_currency,              profits_account.product_id,              time_depos_renewal.days_duration,              r_deposit_account.fkgd_category,              r_deposit_account.book_balance,              r_deposit_account.accr_cr_interest,              td_duration_gl.cr_int_accr_gl_acc,              td_duration_gl.gl_account /*          ,TO_NUMBER(bank_parameters.prev_trx_date - td_int_accr_reslts.last_int_calc_date) + 1*/                                       ,                TO_NUMBER (                     bank_parameters.prev_trx_date                   - r_time_depos_renew.last_int_calc_date)              + 1;

