create table ACTUAL_DOCUMENT
(
    PRFT_SYSTEM        SMALLINT,
    ID                 DECIMAL(13),
    SERIAL_NO          SMALLINT,
    FK_DOCUMENT_TEMPRF SMALLINT,
    FKGD_HAS_LANGUAGE  INTEGER,
    FK_PRFT_TRANSACID  INTEGER,
    FK_DOCUMENT_TEMCOD INTEGER,
    CR_DR_AMOUNT       DECIMAL(15, 2),
    LG_AMOUNT          DECIMAL(15, 2),
    FINAL_DATE         DATE,
    CREATION_DATE      DATE,
    DATE_OF_PRINT      DATE,
    DATE_OF_PROCESS    DATE,
    LAST_UPDATE_DT     DATE,
    DOC_STATUS         CHAR(1),
    LOCK_UNLOCK_FLG    CHAR(1),
    FKGH_HAS_LANGUAGE  CHAR(5),
    FK_USRCODE         CHAR(8),
    USR_OF_PROCESS     CHAR(8),
    USR_OF_PRINT       CHAR(8),
    REFERENCE_NUMBER   CHAR(10),
    FILE_NAME          CHAR(24),
    ACCOUNT_NUMBER     CHAR(40)
);

create unique index IXU_ACT_000
    on ACTUAL_DOCUMENT (PRFT_SYSTEM, ID, SERIAL_NO);

