create table ADDITIONAL_TRX_EXTERNAL
(
    DATE_REC              DATE         not null,
    SOURCE_TYPE           INTEGER      not null,
    FILE_NAME             CHAR(20)     not null,
    ENTRY_SERIAL_NUM      INTEGER      not null,
    FK_COMPANY_CODE       INTEGER      not null,
    FK_COMPANY_NAME       CHAR(40),
    FK_COST_CENTER_ID     CHAR(10),
    ENTRY_DATE            DATE,
    EMPLOYEE_NAME         VARCHAR(40),
    EMPLOYEE_STAFF_NUMBER CHAR(8),
    CUST_ID               INTEGER,
    PRFT_SYSTEM           SMALLINT,
    ACCOUNT_NUMBER        CHAR(40),
    ACCOUNT_CD            SMALLINT,
    BENEFICIARY_NAME      CHAR(70),
    BENEFICIARY_BANK_ID   CHAR(11),
    BENEFICIARY_ACCOUNT   CHAR(34),
    ENTRY_STATUS          SMALLINT,
    REJECTION_REASON      VARCHAR(255),
    DR_CR_FLAG            SMALLINT,
    ID_CURRENCY           INTEGER,
    ID_JUSTIFIC           INTEGER,
    TUN_USR_SN            INTEGER,
    RATE                  DECIMAL(12, 6),
    DC_AMOUNT             DECIMAL(15, 2),
    AMOUNT                DECIMAL(15, 2),
    VALEUR_DATE           DATE,
    AVAIL_DATE            DATE,
    TMSTAMP               TIMESTAMP(6),
    ISO_CURRENCY          CHAR(5),
    TRX_TIMESTAMP         TIMESTAMP(6) not null,
    TRX_DATE              DATE         not null,
    TRX_UNIT              INTEGER      not null,
    TRX_USR               CHAR(8)      not null,
    TRX_INTERNAL_SN       INTEGER      not null,
    ORDER_CODE            VARCHAR(20),
    REL_TUN_USER          CHAR(8),
    REL_TRX_DATE          DATE         not null,
    REL_TRX_UNIT          INTEGER      not null,
    REL_TRX_USR           CHAR(8)      not null,
    REL_TRX_INT_SN        INTEGER      not null,
    GLG_ACCOUNT_ID        CHAR(21),
    CHARGE_BEARER         CHAR(4),
    INSTRUM_CODE          CHAR(10),
    PRFT_TRANS_CODE       INTEGER,
    COMMENTS              CHAR(100),
    CLEARING_SYSTEM       VARCHAR(11),
    constraint PK_ADD_TRX_EXT
        primary key (DATE_REC, FILE_NAME, ENTRY_SERIAL_NUM, FK_COMPANY_CODE)
);

