create table AGENT
(
    AGENT_ID            INTEGER not null,
    DISTRI_CHANNEL      INTEGER not null,
    ENTRY_STATUS        CHAR(1),
    TRANSACTION_ACCOUNT CHAR(40),
    COMMISSION_ACCOUNT  CHAR(40),
    INSERTION_BRANCH    INTEGER,
    INSERTION_USER      CHAR(8),
    INSERTION_DATE      DATE,
    INSERTION_TMSTAMP   TIMESTAMP(6),
    INSERTION_AUTH_BY   CHAR(8),
    UPDATE_BRANCH       INTEGER,
    UPDATE_USER         CHAR(8),
    UPDATE_DATE         DATE,
    UPDATE_TMSTAMP      TIMESTAMP(6),
    UPDATE_AUTH_BY      CHAR(8),
    FK_CUSTOMERCUST_ID  INTEGER not null,
    FK_DISTR_CHANNEID   INTEGER not null,
    FK_DEPOSIT_ACCO     INTEGER,
    FK_UNITCODE         INTEGER,
    FK0_DEPOSIT_ACCO    INTEGER
);

