create table AGR_TRXJUST
(
    FK_AGREEMENT_TYFK  INTEGER,
    FK_PRFT_TRANSACID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_PARAMETRIC_RSN2 SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_ACCOUNTING_RID  INTEGER,
    FK_PARAMETRIC_RID  INTEGER,
    FK_PARAMETRIC_RID2 INTEGER,
    TMSTAMP            TIMESTAMP(6),
    VALIDITY_DATE      DATE,
    PROFIT_INDICATOR   CHAR(1),
    HOME_BRANCH        CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_AGR_011
    on AGR_TRXJUST (FK_AGREEMENT_TYFK, FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST);

