create table AGR_ADDITIONAL_ACT
(
    FK_AGREEMENTFK_UNI  INTEGER,
    FK_AGREEMENTAGR_YE  SMALLINT,
    FK_AGREEMENTAGR_SN  INTEGER,
    FK_AGREEMENTAGR_ME  INTEGER,
    AGR_ADDITIONAL_CNT  INTEGER,
    TMSTAMP             TIMESTAMP(6),
    TRX_CODE            INTEGER,
    JUSTIF_ID           INTEGER,
    UNIT_CODE           INTEGER,
    DG_CUST_ID          INTEGER,
    AMMENDMENT_CNT      INTEGER,
    AGR_AMNT            DECIMAL(15, 2),
    TRX_DATE            DATE,
    ADDIT_STATUS        CHAR(1),
    DEPT_GUAR_MAINT_FLG CHAR(1),
    USER_CODE           CHAR(8),
    TRX_DESCRIPTION     CHAR(40),
    COMMENTS            VARCHAR(500)
);

create unique index IXU_AGR_005
    on AGR_ADDITIONAL_ACT (FK_AGREEMENTFK_UNI, FK_AGREEMENTAGR_YE, FK_AGREEMENTAGR_SN, FK_AGREEMENTAGR_ME,
                           AGR_ADDITIONAL_CNT, TMSTAMP);

