create table AGREEMENT_GUARANT
(
    FK_AGREEMENTFK_UNI INTEGER,
    FK_AGREEMENTAGR_YE SMALLINT,
    FK_AGREEMENTAGR_SN INTEGER,
    FK_AGREEMENTAGR_ME INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    TMSTAMP            TIMESTAMP(6),
    GUARANTEE_AMOUNT   DECIMAL(15, 2),
    REMOVAL_DT         DATE,
    GUARANTOR_STATUS   CHAR(1),
    AGR_PERC_AMOUNT    DECIMAL(15, 2),
    GUARANTEE_DT       DATE,
    ADDRESS_SN         INTEGER,
    RECEIPIENT_FLAG    CHAR(1)
);

create unique index IXAGREEMG
    on AGREEMENT_GUARANT (FK_CUSTOMERCUST_ID);

create unique index IXU_AGR_002
    on AGREEMENT_GUARANT (FK_AGREEMENTFK_UNI, FK_AGREEMENTAGR_YE, FK_AGREEMENTAGR_SN, FK_AGREEMENTAGR_ME,
                          FK_CUSTOMERCUST_ID, TMSTAMP);

