create table AGREEMENT_LMT_HIST
(
    FK_AGREEMENTFK_UNI INTEGER,
    FK_AGREEMENTAGR_YE SMALLINT,
    FK_AGREEMENTAGR_SN INTEGER,
    FK_AGREEMENTAGR_ME INTEGER,
    HISTORY_SN         INTEGER,
    TUN_INTERNAL_SN    SMALLINT,
    TRX_UNIT           INTEGER,
    TRANSACTION_CODE   INTEGER,
    TRX_USR_SN         INTEGER,
    HISTORY_AMOUNT     DECIMAL(15, 2),
    TRX_DATE           DATE,
    AMOUNT_IND         CHAR(1),
    HISTORY_STATUS     CHAR(1),
    TRX_USR            CHAR(8),
    HISTORY_COMMENTS   CHAR(40),
    TMSTAMP            TIMESTAMP(6)
);

create unique index IXU_AGR_003
    on AGREEMENT_LMT_HIST (FK_AGREEMENTFK_UNI, FK_AGREEMENTAGR_YE, FK_AGREEMENTAGR_SN, FK_AGREEMENTAGR_ME, HISTORY_SN);

