create table AGREEMENT_BENEF
(
    FK_AGREEMENTFK_UNI INTEGER,
    FK_AGREEMENTAGR_YE SMALLINT,
    FK_AGREEMENTAGR_SN INTEGER,
    FK_AGREEMENTAGR_ME INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    TMSTAMP            TIMESTAMP(6),
    REMOVAL_DT         DATE,
    MAIN_BENEF_FLG     CHAR(1),
    BENEF_STATUS       CHAR(1),
    ICOM_KEEP_TMDATE   DATE,
    ICOM_KEEP_TMSTAMP  TIMESTAMP(6),
    BENEFICIARY_SN     SMALLINT,
    MANDATE_INSTRUCT   VARCHAR(2048),
    ADDRESS_SN         INTEGER,
    RECEIPIENT_FLAG    CHAR(1)
);

create unique index IXAGREEM
    on AGREEMENT_BENEF (FK_CUSTOMERCUST_ID);

create unique index IXU_AGR_001
    on AGREEMENT_BENEF (FK_AGREEMENTFK_UNI, FK_AGREEMENTAGR_YE, FK_AGREEMENTAGR_SN, FK_AGREEMENTAGR_ME,
                        FK_CUSTOMERCUST_ID, TMSTAMP);

