create table AML_CUSTOMER
(
    CUSTNO               INTEGER not null
        constraint IXU_AML_004
            primary key,
    PROP_WEALTH          SMALLINT,
    CUSY                 INTEGER,
    BIRTH_COUN_SER_NU    INTEGER,
    PASS_NO_SERIAL_NO    INTEGER,
    BRANCH_OFFICE        INTEGER,
    NAT_COUNT_SER_NUM    INTEGER,
    BRANCH_SER_NUM       INTEGER,
    PROFES_SER_NUM       INTEGER,
    CUSY_SER_NUM         INTEGER,
    S_COUNT_SER_NUM      INTEGER,
    H_COUNT_SER_NUM      INTEGER,
    EXEMPTIONAMOUNT      DECIMAL(9, 2),
    FK_CSMNO             DECIMAL(12),
    TOT_WEALTH           DECIMAL(15, 2),
    SALARY               DECIMAL(15, 2),
    BIRTHDATE            DATE,
    LAST_UPDATE          DATE,
    CUSTCONTACT          DATE,
    SALARYDATE           DATE,
    GENDER               CHAR(1),
    EXEMPTIONFLAG        CHAR(1),
    DIRECT_DEBITYN       CHAR(1),
    BORROWERYN           CHAR(1),
    CUST_TYPE            CHAR(1),
    ASYLSYN              CHAR(1),
    NAT_COUNTRY          CHAR(3),
    H_COUNTRY            CHAR(3),
    S_COUNTRY            CHAR(3),
    BIRTH_COUNTRY        CHAR(3),
    INSTITUTE            CHAR(4),
    BIRTH_COUN_PAR_TYP   CHAR(5),
    PASS_NO_PAR_TYPE     CHAR(5),
    NAT_COUNT_PAR_TYP    CHAR(5),
    BRANCH_PAR_TYPE      CHAR(5),
    PROFES_PAR_TYPE      CHAR(5),
    CUSY_PAR_TYPE        CHAR(5),
    S_COUNT_PAR_TYPE     CHAR(5),
    H_COUNT_PAR_TYPE     CHAR(5),
    ZIP                  CHAR(10),
    RISK_CLASS           CHAR(10),
    EMPLNO               CHAR(16),
    PASS_NO              CHAR(20),
    CUST_FLAG_01_24      CHAR(24),
    TOWN                 CHAR(30),
    BRANCH               CHAR(32),
    STREET               CHAR(40),
    LASTNAME             CHAR(70),
    FIRSTNAME            CHAR(32),
    BIRTH_PLACE          CHAR(32),
    PROFESSION           CHAR(32),
    C_DIGIT              SMALLINT,
    ADDRESS_TYPE         CHAR(1)     default ' ',
    ADDRESS_TYPE_DES     VARCHAR(25) default ' ',
    MARIT_STATUS         CHAR(32)    default ' ',
    MARIT_STAT_SER_NU    INTEGER     default 0,
    MARIT_STAT_PAR_TYP   CHAR(5)     default 'FALST',
    E_MAIL               CHAR(64)    default ' ',
    MIDDLE_NAME          VARCHAR(15) default ' ',
    TITLE                CHAR(6),
    FAMILY_MEMBERS       SMALLINT,
    PHONE                CHAR(15),
    COMMUNICAT_METHOD    CHAR(6),
    PHYSICAL_ADDRESS     VARCHAR(40),
    BUILDING_NAME        VARCHAR(40),
    BUILDING_UNIT_NO     VARCHAR(40),
    FLOOR                VARCHAR(40),
    APARTMENT            VARCHAR(40),
    ADRESS_REGION        VARCHAR(20),
    ID_TYPE              VARCHAR(40),
    ID_NUMBER            CHAR(20),
    ID_ISSUE_DATE        DATE,
    ID_VALID_TO          DATE,
    ID_COUNTRY           INTEGER,
    ID_COUNTRY_DESC      VARCHAR(40),
    CRM_ID               VARCHAR(25),
    COMP_REG_NUM         CHAR(20),
    COMP_ISS_COUNTRY     INTEGER,
    COMP_ISS_CNRTY_DESC  VARCHAR(40),
    COMP_INC_DATE        DATE,
    PIN                  CHAR(20),
    INCOME_LEVEL         INTEGER,
    INCOME_LEVEL_DESC    VARCHAR(40),
    EDUCAT_LEVEL         INTEGER,
    EDUCAT_LEVEL_DESC    VARCHAR(40),
    LEGAL_FORM           INTEGER,
    LEGAL_FORM_DESC      VARCHAR(40),
    COMMUNICAT_LANG      CHAR(3),
    COMMUNICAT_LANG_SN   INTEGER,
    ID_TYPE_CODE         INTEGER,
    ID_COUNTRY_SHORTCODE CHAR(3),
    NAT_COUNT_SHORT      CHAR(3),
    MOBILE_TEL           CHAR(15),
    MOBILE_TEL2          CHAR(15)
);

