create table APPLICATION
(
    SN                   CHAR(40) not null
        constraint IXU_APL_IDX
            primary key,
    INST_LOAN_PROGRAM_SN INTEGER,
    STATUS               CHAR(1),
    CUST_ID              DECIMAL(7),
    C_DIGIT              DECIMAL(1),
    CUST_ADDRESS_SN      DECIMAL(3),
    OPENING_UNIT         DECIMAL(5),
    MONITORING_UNIT      DECIMAL(5),
    ID_PRODUCT           DECIMAL(5),
    SALES_UNIT           DECIMAL(5),
    SALER                DECIMAL(5),
    APPLICATION_OFFICER  CHAR(8),
    CURRENCY_ID          DECIMAL(5),
    DATE_REQUESTED       DATE,
    DURATION             DECIMAL(5),
    DURATION_UNIT        DECIMAL(1),
    DATE_OFFERED         DATE,
    OFFER_VALID_UNTIL    DATE,
    REGISTRY_SN          DECIMAL(12),
    REGISTRY_TYPE        CHAR(2),
    OFFER_AMOUNT         DECIMAL(18, 2),
    FIXING_RATE          DECIMAL(12, 6),
    VAT_IND              DECIMAL(1),
    PAY_FREQUENCE        DECIMAL(2),
    ADVANCE_DEPOSIT      DECIMAL(18, 2),
    TOTAL_AMOUNT         DECIMAL(18, 2),
    LOAN_ACCOUNT         CHAR(40),
    LOAN_CD              DECIMAL(2),
    AGREEMENT_ACCOUNT    CHAR(40),
    AGREEMENT_CD         DECIMAL(2),
    DEPOSIT_ACCOUNT      CHAR(40),
    DEPOSIT_CD           DECIMAL(2),
    COMMENTS             VARCHAR(200),
    TRX_UPDATE_UNIT      DECIMAL(5),
    TRX_UNIT             DECIMAL(5),
    TRX_UPDATE_DATE      DATE,
    TRX_DATE             DATE,
    TRX_UPDATE_USR       CHAR(8),
    TRX_USR              CHAR(8),
    TIMESTMP             TIMESTAMP(6),
    STARTING_CAPITAL_AMN DECIMAL(18, 2),
    BANK_DEPOSIT_ACCOUNT CHAR(40),
    BANK_DEPOSIT_CD      DECIMAL(2),
    EXPIRY_DATE          DATE,
    MULTI_APPLICATION_ID CHAR(15)
);

