create table APPROV_INTER_RATE
(
    FK_USRCODE         CHAR(8),
    DEALER_REF_NO      CHAR(20),
    C_DIGIT            SMALLINT,
    TRX_UNIT           INTEGER,
    ID_CURRENCY        INTEGER,
    DB_INTEREST_RATE   DECIMAL(8, 4),
    CR_INTEREST_RATE   DECIMAL(8, 4),
    TRX_USR_SN         INTEGER,
    ACCOUNT_NUMBER     DECIMAL(11),
    RATE_AMOUNT        DECIMAL(15, 2),
    TRX_DATE           DATE,
    START_DATE         DATE,
    TIMESTMP           TIMESTAMP(6),
    STATUS_FLAG        CHAR(1),
    RENEWAL_FLAG       CHAR(1),
    TRX_USR            CHAR(8),
    FK0USRCODE         CHAR(8),
    END_DATE           DATE,
    TIME_DEP_TRANS_FLG CHAR(1),
    INTER_PAY_OPTIONS  CHAR(1),
    DAYS_DURATION      SMALLINT,
    LOAN_ACC_CD        SMALLINT,
    LOAN_ACC_NUMBER    VARCHAR(40),
    PRFT_SYSTEM        SMALLINT
);

create unique index IXU_APP_000
    on APPROV_INTER_RATE (FK_USRCODE, DEALER_REF_NO);

