create table ART_PHYSICAL_ENTITIES
(
    SN                                    INTEGER generated always as identity,
    CURRENT_DATE                          DATE        not null,
    ENTITY_KEY                            VARCHAR(40) not null,
    COUNTRY_CODE                          CHAR(2),
    ID_TYPE                               CHAR(1),
    ID_NUMBER                             VARCHAR(40),
    TITLE                                 CHAR(4),
    LAST_NAME_LATIN                       VARCHAR(40),
    FIRST_NAME_LATIN                      VARCHAR(40),
    FATHERS_NAME_LATIN                    VARCHAR(40),
    LAST_NAME_GREEK                       VARCHAR(30),
    FIRST_NAME_GREEK                      VARCHAR(30),
    FATHERS_NAME_GREEK                    VARCHAR(30),
    DATE_OF_BIRTH                         DATE,
    COUNTRY_OF_BIRTH                      CHAR(2),
    MARITAL_STATUS                        VARCHAR(2),
    EDUCATION_LEVEL                       VARCHAR(2),
    NUMBER_OF_DEPENDENTS                  INTEGER,
    ADDRESS_LINE_1                        VARCHAR(100),
    ADDRESS_LINE_2                        VARCHAR(100),
    POSTAL_CODE                           VARCHAR(10),
    MUNICIPALITY_COMMUNITY                VARCHAR(30),
    DISTRICT                              VARCHAR(21),
    COUNTRY                               CHAR(2),
    PROFESSION                            CHAR(4),
    EMPLOYMENT_POSITION                   CHAR(4),
    NACE_CODE                             CHAR(4),
    ANNUAL_NET_INCOME_FOR_EMPLOYMENT      DECIMAL(13, 2),
    OTHER_ANNUAL_INCOME                   DECIMAL(13, 2),
    TOT_ANNUAL_INC_AFTER_EXPEN_BEF_LOAN_P DECIMAL(13, 2),
    FINANCIAL_YEAR                        CHAR(4),
    CUSTOMER_INTERNAL_RATING_SCORING      VARCHAR(14),
    RATING_SCORING_DATE                   DATE,
    COOPERTAION_START_DATE                DATE,
    IS_ACCOUNT_OWNER                      CHAR(1),
    FILE_ACTION                           CHAR(1) default 'F',
    primary key (SN, CURRENT_DATE, ENTITY_KEY)
);

