create table ASSET_MASTER
(
    ASSET_ID                 VARCHAR(10) not null
        constraint IXU_GL_013
            primary key,
    TRX_LUNIT                INTEGER,
    TRX_UNIT                 INTEGER,
    ASSET_COUNTRY            INTEGER,
    MANUFACTURER             INTEGER,
    TAX_PERCENT              INTEGER,
    MEASURING_UNIT           INTEGER,
    VENDOR_ID                INTEGER,
    OWNED_UNIT               INTEGER,
    TAX_AMOUNT               DECIMAL(15, 2),
    UNTAX_AMOUNT             DECIMAL(15, 2),
    AMOUNT                   DECIMAL(15, 2),
    QUANTITY                 DECIMAL(15, 2),
    DEPRECIAT_VAL_REM        DECIMAL(15, 2),
    DEPRECIATED_VALUE        DECIMAL(15, 2),
    CURR_VALUE               DECIMAL(15, 2),
    OBJ_VALUE                DECIMAL(15, 2),
    REVAL_START_DT           DATE,
    LAST_SCHEDULED_DT        DATE,
    DEPR_START_DT            DATE,
    AQUISITION_DATE          DATE,
    TRX_LDATE                DATE,
    TRX_DATE                 DATE,
    LAST_UNSCHEDLED_DT       DATE,
    LAST_DVLP_LAW_DATE       DATE,
    ASSET_FULL_DEPR          CHAR(1),
    ASSET_AUTO_DEPR          CHAR(1),
    ASSET_STATUS             CHAR(1),
    ASSET_ADDITION           CHAR(1),
    TRX_LUSR                 CHAR(8),
    TRX_USR                  CHAR(8),
    OPPOSED_GL_ACCOUNT       CHAR(21),
    GL_ACCOUNT               CHAR(21),
    CATEGORY_CODE            VARCHAR(2),
    STATUS_CODE              VARCHAR(4),
    DEVELOPMENTAL_LAW        VARCHAR(4),
    ASSET_CODE_ADDED         VARCHAR(10),
    SERIAL_NUMBER            VARCHAR(13),
    SHORT_DESCRIPTION        VARCHAR(40),
    DESCRIPTION              VARCHAR(100),
    INVOICE_NO               VARCHAR(100),
    ADDITIONAL_INFO          VARCHAR(2000),
    ASSET_BARCODE            VARCHAR(200),
    UNDEPRECIATE_ASSET_VALUE DECIMAL(15, 2) default 0,
    CURRENCY_ID              DECIMAL(5)     default 22,
    FIRST_PROF_DEPR          DATE,
    REGISTRY_SN              DECIMAL(12),
    REVAL_PROFIT             DECIMAL(15, 2)
);

