create table ASSET_TRX_RECORDING
(
    TRX_DATE           DATE                 not null,
    TRX_UNIT           INTEGER              not null,
    TRX_USER           CHAR(8)              not null,
    TRX_USR_SN         INTEGER              not null,
    PRFT_SYSTEM        SMALLINT,
    TRX_CODE           INTEGER,
    CURRENCY_ID        INTEGER,
    ID_PRODUCT         INTEGER,
    GL_RULE_ID         INTEGER,
    UNIT_CODE          INTEGER,
    ID_JUSTIFIC        INTEGER,
    CUST_ID            INTEGER,
    DOC_NUM            INTEGER,
    FIXING_RATE        DECIMAL(12, 6),
    FC_AMOUNT          DECIMAL(15, 2),
    DC_AMOUNT_NET      DECIMAL(15, 2),
    FC_AMOUNT_NET      DECIMAL(15, 2),
    DC_AMOUNT_FPA      DECIMAL(15, 2),
    FC_AMOUNT_FPA      DECIMAL(15, 2),
    DC_AMOUNT          DECIMAL(15, 2),
    TRANSFER_DATE      DATE,
    GL_TRN_DATE        DATE,
    GLG_COST_C_TYPE    CHAR(1),
    FINALIZATION_FLAG  CHAR(1),
    GLG_COST_C_FLAG    CHAR(1),
    TRANSFER_FLAG      CHAR(1),
    GLG_JOURNALJOUR    CHAR(2),
    GLG_DOCUMENTDO0    CHAR(2),
    GLG_JUSTIFYJUST    CHAR(4),
    GLG_DOCUMENTDOC    CHAR(4),
    GLG_COST_CENTER    CHAR(6),
    DEPR_CONTROL_ACC   CHAR(21),
    DB_CONTROL_ACC     CHAR(21),
    CR_CONTROL_ACC     CHAR(21),
    SUPPL_CONTROL_ACC  CHAR(21),
    TERMINAL_NUMBER    CHAR(30),
    REMARKS            VARCHAR(80),
    ASSET_ID           VARCHAR(10),
    ASSET_VALUE        DECIMAL(15, 2),
    ASSET_TOTAL_DEPR   DECIMAL(15, 2),
    ASSET_UNDEPR       DECIMAL(15, 2),
    ASSET_INCOME       DECIMAL(15, 2),
    ASSET_LOSS         DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    FK_CATEGORY_CODE   VARCHAR(2),
    ANNUAL_DEPR_PERCNT DECIMAL(8, 4),
    TRX_USR_INT_SN     DECIMAL(2) default 1 not null,
    TRN_TYPE           CHAR(1),
    constraint IXU_GL_018
        primary key (TRX_DATE, TRX_UNIT, TRX_USER, TRX_USR_SN, TRX_USR_INT_SN)
);

