create table ATM_TOTALS
(
    ACC_UNIT           INTEGER,
    ATM_CODE           DECIMAL(10),
    ATM_UNIT           INTEGER,
    CCY_CODE           SMALLINT,
    PRODUCTION_DATE    DATE,
    MAESTRO_POS_REV_CN DECIMAL(10),
    MAESTRO_POS_CNTR   DECIMAL(10),
    MAESTRO_REV_CNTR   DECIMAL(10),
    MAESTRO_CNTR       DECIMAL(10),
    DEPOSIT_CNTR       DECIMAL(10),
    BALANCE_INQ_CNTR   DECIMAL(10),
    MCRD_PAYMENT_CNTR  DECIMAL(10),
    MCRD_CASH_REV_CNTR DECIMAL(10),
    MCRD_CASH_CNTR     DECIMAL(10),
    VISA_CASH_REV_CNTR DECIMAL(10),
    VISA_CASH_CNTR     DECIMAL(10),
    VISA_PAYMENT_CNTR  DECIMAL(10),
    GB_JOURNAL_CNTR    DECIMAL(10),
    GB_CASH_REV_CNTR   DECIMAL(10),
    GB_CASH_CNTR       DECIMAL(10),
    GB_JOURNAL_REV     DECIMAL(15, 2),
    GB_CASH            DECIMAL(15, 2),
    MAESTRO_CASH_REV   DECIMAL(15, 2),
    MAESTRO_CASH       DECIMAL(15, 2),
    MAESTRO_POS        DECIMAL(15, 2),
    MCRD_PAYMENT       DECIMAL(15, 2),
    MCRD_CASH_REV      DECIMAL(15, 2),
    MCRD_CASH          DECIMAL(15, 2),
    VISA_CASH_REV      DECIMAL(15, 2),
    VISA_CASH          DECIMAL(15, 2),
    DIAS_CASH_REV      DECIMAL(15, 2),
    DIAS_CASH          DECIMAL(15, 2),
    GB_JOURNAL         DECIMAL(15, 2),
    GB_CASH_REV        DECIMAL(15, 2),
    MAESTRO_POS_REV    DECIMAL(15, 2)
);

create unique index IXU_ATM_019
    on ATM_TOTALS (ACC_UNIT, ATM_CODE, ATM_UNIT, CCY_CODE, PRODUCTION_DATE);

