create table ATM_DEB_CRED_MAP
(
    PROTOCOL_ID        SMALLINT not null,
    ISO_CODE           CHAR(6)  not null,
    MNEMONIC_CODE      CHAR(4)  not null,
    REVERSAL_FLAG      CHAR(1)  not null,
    TRANSACT_NAME      CHAR(30) not null,
    FORCE_POST_FLAG    CHAR(1)  not null,
    TRN_AMNT_CR        CHAR(20),
    TRN_AMNT_CR_TRX    INTEGER,
    TRN_AMNT_CR_JUST   INTEGER,
    TRN_AMNT_DB        CHAR(20),
    TRN_AMNT_DB_TRX    INTEGER,
    TRN_AMNT_DB_JUST   INTEGER,
    COMM_AMNT1_CR      CHAR(20),
    COMM_AMNT1_CR_TRX  INTEGER,
    COMM_AMNT1_CR_JUST INTEGER,
    COMM_AMNT2_CR      CHAR(20),
    COMM_AMNT2_CR_TRX  INTEGER,
    COMM_AMNT2_CR_JUST INTEGER,
    COMM_AMNT1_DB      CHAR(20),
    COMM_AMNT1_DB_TRX  INTEGER,
    COMM_AMNT1_DB_JUST INTEGER,
    COMM_AMNT2_DB      CHAR(20),
    COMM_AMNT2_DB_TRX  INTEGER,
    COMM_AMNT2_DB_JUST INTEGER,
    REVERSE_TRX        INTEGER,
    POS_ACCNT_ORIGIN   CHAR(1),
    constraint ATM_DEB_CRED_MAP_PK
        primary key (FORCE_POST_FLAG, TRANSACT_NAME, REVERSAL_FLAG, MNEMONIC_CODE, ISO_CODE, PROTOCOL_ID)
);

