create table ATM_SUB_ELEMENT
(
    PROTOCOL_ID    SMALLINT,
    ELEMENT_ID     SMALLINT,
    INTERNAL_SN    SMALLINT,
    ELEMENT_FRM_ID SMALLINT,
    PROFITS_FIELD  SMALLINT,
    ELEMENT_LENGTH SMALLINT,
    VAR_STATUS     CHAR(1),
    ELEMENT_DESC   CHAR(40)
);

create unique index IXU_ATM_018
    on ATM_SUB_ELEMENT (PROTOCOL_ID, ELEMENT_ID, INTERNAL_SN);

