create table ATM_MAESTRO_RECON
(
    ACCOUNT_NUMBER     DECIMAL(15),
    FORCE_POST         CHAR(1),
    RETRIEVAL_REF_NBR  DECIMAL(12),
    SOURCE_SEQ_NUMBER  DECIMAL(10),
    TRANS_AMOUNT       DECIMAL(15, 2),
    HOST_BUSINESS_DATE DATE,
    SOURCE_TYPE        CHAR(1),
    ENTRY_STRATUS      CHAR(1)
);

create unique index IXU_ATM_011
    on ATM_MAESTRO_RECON (ACCOUNT_NUMBER, FORCE_POST, RETRIEVAL_REF_NBR);

