create table ATM_PROCESS_CODE
(
    PROTOCOL_ID       SMALLINT,
    ISO_CODE          CHAR(6),
    MNEMONIC_CODE     CHAR(4),
    REVERSAL_FLAG     CHAR(1),
    INTER_TRANS_CODE  SMALLINT,
    DIAS_FLAG         CHAR(1),
    DESCRIPTION       CHAR(80),
    SECOND_TRANS_CODE INTEGER
);

create unique index IXU_ATM_016
    on ATM_PROCESS_CODE (PROTOCOL_ID, ISO_CODE, MNEMONIC_CODE, REVERSAL_FLAG);

