create table ATM_CP_AGREEMENT
(
    ATM_AGR_TYPE        CHAR(2),
    ATM_AGR_TYPE_SN     CHAR(2),
    CP_AGREEMENT_ID     DECIMAL(10),
    COMMISSION_DISCOUNT DECIMAL(8, 4),
    CHARGE_DISCOUNT     DECIMAL(8, 4)
);

create unique index IXU_ATM_028
    on ATM_CP_AGREEMENT (ATM_AGR_TYPE_SN, ATM_AGR_TYPE);

