create table ATM_MAESTRO_OUTSTA
(
    ACCOUNT_NUMBER   DECIMAL(15),
    IPS_PROD_DATE    DATE,
    PRODUCTION_DATE  DATE,
    CURRENCY_CODE    DECIMAL(10),
    CASH_AUTHOR_AMT  DECIMAL(15, 2),
    PURCH_AUTHOR_AMT DECIMAL(15, 2),
    PROCESS_STATE    CHAR(1),
    BRANCH_NUMBER    CHAR(5),
    BANK_IDENTIFIER  VARCHAR(10),
    PROFITS_RESULT   VARCHAR(40)
);

create unique index IXU_ATM_010
    on ATM_MAESTRO_OUTSTA (ACCOUNT_NUMBER, IPS_PROD_DATE, PRODUCTION_DATE);

