create table ATM_PROTOCOL
(
    PROTOCOL_ID      SMALLINT,
    ELEMENT_ID       SMALLINT,
    STATUS_INF       SMALLINT,
    ELEMENT_FRM_ID   SMALLINT,
    ELEMENT_LENGTH   SMALLINT,
    SUB_ELEMENT_FLAG CHAR(1),
    ELEMENT_DESC     CHAR(80),
    FIELD_ID         INTEGER
);

create unique index IXU_ATM_017
    on ATM_PROTOCOL (PROTOCOL_ID, ELEMENT_ID);

