create table ATM_AUTHORISORS
(
    MESSAGE_CODE     SMALLINT,
    COM_PERSENTAGE   DECIMAL(8, 4),
    FPA_PERCENTANGE  DECIMAL(8, 4),
    EFTE_PERCENTANGE DECIMAL(8, 4),
    DEBIT_JUSTIFIC   DECIMAL(10),
    AMOUNT_FOR_DIAS  DECIMAL(15, 2),
    INQUIRY_DEBIT    DECIMAL(15, 2),
    MAX_AMOUNT       DECIMAL(15, 2),
    MIN_AMOUNT       DECIMAL(15, 2),
    CASH_ADVANCE_FLG CHAR(1),
    AUTHORISOR_CODE  CHAR(4),
    DESCRIPTION      VARCHAR(40)
);

create unique index IXU_ATM_027
    on ATM_AUTHORISORS (MESSAGE_CODE);

