create table ATM_MAES_REF_BLOCK
(
    AUTHORIZATION_REFE DECIMAL(15) not null,
    YEAR0              INTEGER     not null,
    ENTRY_STATUS       CHAR(1),
    FK_BLOCK_TRANSATRX DATE,
    FK0BLOCK_TRANSATRX INTEGER,
    FK1BLOCK_TRANSATRX CHAR(8),
    FK2BLOCK_TRANSATRX INTEGER,
    constraint I0002193
        primary key (YEAR0, AUTHORIZATION_REFE)
);

