create table ATM_TRANS_PAR
(
    FORCE_POST_FLAG  CHAR(1),
    TRANSACTION_CODE DECIMAL(10),
    DAYS_DUE         SMALLINT,
    JUSTIFIC_ID2     DECIMAL(10),
    JUSTIFIC_ID3     DECIMAL(10),
    JUSTIFIC_ID4     DECIMAL(10),
    JUSTIFIC_ID6     DECIMAL(10),
    JUSTIFIC_ID7     DECIMAL(10),
    JUSTIFIC_ID8     DECIMAL(10),
    JUSTIFIC_ID9     DECIMAL(10),
    JUSTIFIC_ID10    DECIMAL(10),
    PRODUCT_ID       DECIMAL(10),
    JUSTIFIC_ID1     DECIMAL(10),
    JUSTIFIC_ID5     DECIMAL(10)
);

create unique index IXU_ATM_021
    on ATM_TRANS_PAR (FORCE_POST_FLAG, TRANSACTION_CODE);

