create table ATM_TRX_RECORDING
(
    TRANSACTION_DATE         CHAR(4),
    REFERENCE_NUMBER         CHAR(12),
    IDENT_RESPONSE           CHAR(6),
    CUST_ACCOUNT_SRC         CHAR(28),
    REVERSAL                 CHAR(1),
    COUNTRY_CODE             SMALLINT,
    XXXSOURCE_FI_NBR         SMALLINT,
    CHANNEL_ID               INTEGER,
    INTER_ID_TRANSACT        INTEGER,
    XXXATM_UNIT              INTEGER,
    I_TUN_UNIT               INTEGER,
    TUN_UNIT                 INTEGER,
    XXXSOURCE_TERM_NBR       INTEGER,
    CUST_ACC_UNIT_SRC        INTEGER,
    AUDIT_NUMBER             INTEGER,
    XXXSOURCE_SEQ_NUMBER     INTEGER,
    TUN_USER_SN              INTEGER,
    I_TUN_USR_SN             INTEGER,
    TUN_USER_SN_DST          INTEGER,
    I_TUN_USR_SN_DST         INTEGER,
    XXXREJ_ITEM_ACC_DST      DECIMAL(10),
    XXXSOURCE_ACCOUNT        DECIMAL(10),
    XXXREJECTED_ITEMS_ACC    DECIMAL(10),
    XXXDEST_ACCOUNT          DECIMAL(10),
    LOG_ID                   DECIMAL(10),
    XXXREJ_ITEM_ACC_SRC      DECIMAL(10),
    BANK_CODE                DECIMAL(11),
    XXXLOAN_ACCOUNT_NBR      DECIMAL(13),
    BANK_FEES                DECIMAL(15, 2),
    XXXCASH_AMOUNT           DECIMAL(15, 2),
    XXXJOURNAL_AMOUNT        DECIMAL(15, 2),
    DIAS_FEES                DECIMAL(15, 2),
    TRANSACTION_AMOUNT       DECIMAL(15, 2),
    TUN_DATE                 DATE,
    XXXSOURCE_BUSINESS_DATE  DATE,
    I_TUN_DATE               DATE,
    TUN_TMSTAMP_DST          TIMESTAMP(6),
    TMSTAMP                  TIMESTAMP(6),
    FFUI_TUN_TMSTAMP_DST     TIMESTAMP(6),
    TUN_TMSTAMP              TIMESTAMP(6),
    TLF_TRX_TMSTAMP          TIMESTAMP(6),
    FFUI_TUN_TMSTAMP         TIMESTAMP(6),
    RECONCILED_FLG           CHAR(1),
    TRN_TYPE                 CHAR(1),
    REVERSED                 CHAR(1),
    STAND_IN_FLAG            CHAR(1),
    UTILITY_TYPE             CHAR(2),
    MTI_CODE                 CHAR(4),
    SWITCH_DATE              CHAR(4),
    TD_ATIME                 CHAR(4),
    PROCESSING_CODE          CHAR(6),
    I_TUN_USR                CHAR(8),
    TUN_USR                  CHAR(8),
    TERMINAL                 CHAR(16),
    CUST_ACCOUNT_DST         CHAR(28),
    XXXTO_CARD               CHAR(28),
    CARD_NUMBER              CHAR(37),
    TO_CARD                  CHAR(28),
    RESPONSE_CODE            CHAR(2),
    CARD_ACCEPTOR_NAME       CHAR(40),
    MANUAL_RECONCIL          CHAR(1),
    SWITCH_TIME              TIME,
    TRANSACTION_TIME         TIME,
    COMPANY                  VARCHAR(50),
    PULL_PUSH_MSG            CHAR(4),
    PHONE_NUMBER             VARCHAR(25),
    OTHER_CARDS              CHAR(1),
    ATM_FLG                  CHAR(1),
    POS_FLG                  CHAR(1),
    ONUS_KENSWITCH           CHAR(1),
    OFFUS_KENSWITCH          CHAR(1),
    OFFUS_MASTERCARD         CHAR(1),
    ECOMMERCE_ONLINE         CHAR(1),
    POS_DATA_CODE            CHAR(15),
    MSG_REASON_CODE          CHAR(4),
    ADDITIONAL_NODE_DATA     CHAR(100),
    ABROAD_COUNTRY_INDICATOR CHAR(3),
    FIELD_60                 CHAR(100),
    FIELD_18                 CHAR(100),
    FIELD_19                 CHAR(100),
    FIELD_43                 CHAR(100)
);

create unique index IDX_ATM_TRX_RECORDING_FIELD_60
    on ATM_TRX_RECORDING (FIELD_60);

