create table ATM_VISA_TRANS
(
    AUTH_FI_NBR        SMALLINT,
    SOURCE_BUS_DATE    DATE,
    SOURCE_FI_NBR      SMALLINT,
    SOURCE_SEQ_NBR     INTEGER,
    SOURCE_TERM_NBR    INTEGER,
    TRANS_CODE         SMALLINT,
    BRANCH_CODE        INTEGER,
    RETRIEVAL_REFER_NO DECIMAL(12),
    ORIG_RETR_REFER_NO DECIMAL(12),
    TRANS_AMOUNT       DECIMAL(15, 2),
    TMSSTAMP           DATE,
    TRANS_DATE         DATE,
    PROCESS_STATE      CHAR(1),
    DELTA_RESP_CODE    CHAR(2),
    REG_E_VAL_CODE     CHAR(4),
    PASSTHRU_TRACE_NBR CHAR(6),
    AUTH_ID_RESP       CHAR(6),
    EXPIRE_DATE        CHAR(6),
    REG_E_TERMID       CHAR(8),
    ORIG_TMSTAMP       CHAR(14),
    REG_E_TRANSID      CHAR(15),
    CARD_NUMBER        CHAR(19),
    TRACK_2_DATA       CHAR(40),
    TRANS_TIME         TIME
);

create unique index IXU_ATM_026
    on ATM_VISA_TRANS (AUTH_FI_NBR, SOURCE_BUS_DATE, SOURCE_FI_NBR, SOURCE_SEQ_NBR, SOURCE_TERM_NBR, TRANS_CODE);

