create table ATM_ACC_BALANCES
(
    PRFT_ACCOUNT_NUM  CHAR(40) not null,
    PRFT_ACCOUNT_CD   SMALLINT not null,
    TYPE_OF_ACCOUNT   CHAR(1),
    FILE_CODE         SMALLINT,
    PRFT_SYSTEM       SMALLINT,
    ACCOUNT_NUMBER    DECIMAL(15),
    AVAILABLE_BALANCE DECIMAL(15, 2),
    BOOK_BALANCE      DECIMAL(15, 2),
    ACC_TYPE          CHAR(4),
    LST_REN_BOOK_BAL  DECIMAL(15, 2),
    LST_REN_AVAIL_BAL DECIMAL(15, 2),
    TMSTAMP           TIMESTAMP(6)
);

create unique index IXU_ATM_000
    on ATM_ACC_BALANCES (PRFT_ACCOUNT_NUM, PRFT_SYSTEM);

