create table AUDIT_TRAIL
(
    CUST_CD        SMALLINT,
    ACCOUNT_CD     SMALLINT,
    PRFT_SYSTEM    SMALLINT,
    TRX_UNIT       INTEGER,
    JUSTIFIC_ID    INTEGER,
    TRANS_ID       INTEGER,
    PRODUCT_ID     INTEGER,
    CURRENCY_ID    INTEGER,
    CUST_ID        INTEGER,
    TRX_SN         INTEGER,
    AMOUNT         DECIMAL(15, 2),
    VALUE_DATE     DATE,
    TRX_DATE       DATE,
    TMSTAMP        DATE,
    ACCOUNTED_FLAG CHAR(1),
    REVERSAL_FLAG  CHAR(1),
    CUST_TYPE      CHAR(1),
    TRX_USR        CHAR(8),
    ACCOUNT_NUMBER CHAR(40),
    PRODUCT_DESC   VARCHAR(40),
    JUSTIFIC_DESC  VARCHAR(40),
    TRANS_DESC     VARCHAR(40)
);

