create table BANK_VOUCHER_SETUP
(
    RULE_VOUCHER_ID  INTEGER,
    BANK_VOUCHER_KEY INTEGER,
    BANK_VOUCHER_ID  INTEGER,
    ENTRY_STATUS     CHAR(1),
    BANK_SETUP_DESCR CHAR(80)
);

create unique index IXU_BAN_003
    on BANK_VOUCHER_SETUP (RULE_VOUCHER_ID, BANK_VOUCHER_KEY);

