create table BANK_DRAFT_BOOK
(
    BANK_DRAFT_TYPE    CHAR(1)  not null,
    BANK_DRAFT_BOOK_SN INTEGER  not null,
    FST_DRAFT_NUMBER   CHAR(10) not null,
    LST_DRAFT_NUMBER   CHAR(10) not null,
    LST_DRAFT_NUMBER_U CHAR(10),
    ITEM_COUNT         INTEGER,
    ISSUE_DATE         DATE,
    LAST_UPDATE_DATE   DATE,
    ENTRY_STATUS       CHAR(1),
    TMSTAMP            TIMESTAMP(6),
    FK_UNITCODE        INTEGER,
    FK_PROFITS_ACCOUNT CHAR(40),
    DEP_ACC_NUMBER     DECIMAL(11),
    CUST_ID            INTEGER,
    SERVICE_PROD       INTEGER,
    SERVICE_JUST       INTEGER,
    ENTRY_COMMENTS     VARCHAR(40),
    DESIGNATED_UNIT    INTEGER default 0
);

create unique index SEC_BD_BOOK1
    on BANK_DRAFT_BOOK (ISSUE_DATE, FK_UNITCODE, CUST_ID, DEP_ACC_NUMBER, ENTRY_STATUS);

create unique index SEC_BD_BOOK2
    on BANK_DRAFT_BOOK (DEP_ACC_NUMBER, FK_UNITCODE, BANK_DRAFT_TYPE, FST_DRAFT_NUMBER, LST_DRAFT_NUMBER);

