create table BASE_RATE
(
    FK_GH_PAR_TYPE CHAR(5),
    FK_GD_SNUM     INTEGER,
    DURATION       SMALLINT,
    DUR_UNIT       CHAR(1),
    FK_CURRENCY    INTEGER,
    VALIDITY_DATE  DATE,
    TMSTAMP        TIMESTAMP(6),
    BASE_RATE_PERC DECIMAL(9, 6),
    ENTRY_STATUS   CHAR(1)
);

create unique index IXU_BAS_000
    on BASE_RATE (FK_GH_PAR_TYPE, FK_GD_SNUM, DURATION, DUR_UNIT, FK_CURRENCY, VALIDITY_DATE, TMSTAMP);

