create table BATCH_PARAMETERS
(
    PROGRAM_ID         CHAR(5),
    SN                 SMALLINT,
    MONTH_FROM         SMALLINT,
    MONTH_TO           SMALLINT,
    ACC_TYPE_TO        SMALLINT,
    ACC_TYPE_FROM      SMALLINT,
    EXEC_MONTH         SMALLINT,
    CURRENCY_TO        SMALLINT,
    CURRENCY_FROM      SMALLINT,
    EXEC_DAYS          SMALLINT,
    YEAR_FROM          SMALLINT,
    EXEC_YEAR          SMALLINT,
    YEAR_TO            SMALLINT,
    PRODUCT_TO         INTEGER,
    PRODUCT_FROM       INTEGER,
    UNIT_TO            INTEGER,
    UNIT_FROM          INTEGER,
    JUSTIFIC_ID        INTEGER,
    LOAN_PURP_FROM     INTEGER,
    LOAN_PURP_TO       INTEGER,
    PROD_CATEG_FROM    INTEGER,
    PROD_CATEG_TO      INTEGER,
    CUSTOMER_FROM      INTEGER,
    CUSTOMER_TO        INTEGER,
    ACC_PROD_NUM_FROM  DECIMAL(10),
    ACC_PROD_NUM_TO    DECIMAL(10),
    NUMBER_TO          DECIMAL(13),
    NUMBER_FROM        DECIMAL(13),
    AMOUNT_FROM        DECIMAL(15, 2),
    AMOUNT_TO          DECIMAL(15, 2),
    DATE_FROM          DATE,
    DATE_TO            DATE,
    UPDATE_FROM        TIMESTAMP(6),
    UPDATE_TO          TIMESTAMP(6),
    LOANS_STS_FROM     CHAR(1),
    CONV_URL_TO_RL_INT CHAR(1),
    INTEREST_CALC_FLG  CHAR(1),
    ON_REQUEST_FLAG    CHAR(1),
    LOANS_STS_TO       CHAR(1),
    FLAG_FROM          CHAR(2),
    FLAG_TO            CHAR(2),
    JOURNAL_TO         CHAR(3),
    JOURNAL_FROM       CHAR(3),
    CUST_CAT_TO        CHAR(8),
    CHAR_8_TO          CHAR(8),
    CHAR_8_FROM        CHAR(8),
    CUST_CAT_FROM      CHAR(8),
    CHAR_15_TO         CHAR(15),
    CHAR_15_FROM       CHAR(15),
    EXTRAIT_DESCR      VARCHAR(40),
    ASCII_FILENAME     VARCHAR(50)
);

create unique index IXU_BAT_000
    on BATCH_PARAMETERS (PROGRAM_ID, SN);

