create table BCK_TEIR_FILE_MME
(
    LINE_SN               INTEGER not null,
    FILE_DATE             CHAR(8) not null,
    OV_REJ_INDIC          CHAR(1) not null,
    BANK_CODE             SMALLINT,
    RECORD_COUNT          INTEGER,
    AMOUNT_COUNT          DECIMAL(15, 2),
    FK_UNITCODE           INTEGER,
    LOAN_PRIMARY_KEY      CHAR(16),
    LAST_TRX_DT           CHAR(8),
    LOAN_INDICATOR        CHAR(1),
    LOAN_IND_TRX_DATE     CHAR(8),
    STOP_RECYCLE_IND      CHAR(1),
    STOP_RECYCLE_DT       CHAR(8),
    SAME_LIMIT_IND        SMALLINT,
    SAME_LIMIT_CODE       CHAR(16),
    INSTALL_COUNT         SMALLINT,
    UNPAID_INSTALL_CNT    SMALLINT,
    OVERDUE_INDICATOR     SMALLINT,
    LOAN_REQUEST_AMNT     DECIMAL(12, 2),
    MIN_INSTALL_AMNT      DECIMAL(12, 2),
    ACC_LIMIT_AMN         DECIMAL(12, 2),
    INSTALL_FREQ          SMALLINT,
    PREV_PAYMENT_AMNT     DECIMAL(12, 2),
    LST_TRX_FINANC_DT     CHAR(8),
    NORMAL_BALANCE        DECIMAL(12, 2),
    OVERDUE_BALANCE       DECIMAL(12, 2),
    NEGATIVE_BALANCE      DECIMAL(12, 2),
    WHOLE_BALANCE         DECIMAL(12, 2),
    ACC_OPEN_DT           CHAR(8),
    LOAN_TYPE             CHAR(1),
    CUSTOMER_INDICATOR    CHAR(1),
    TEIRESIAS_IND         CHAR(1),
    TEIRESIAS_DATE        CHAR(8),
    AFM_NO                CHAR(9),
    OTHER_ID_NO           CHAR(9),
    OTHER_ID_ISSUE_DATE   CHAR(8),
    CUST_SEX              CHAR(1),
    CUST_SURNAME          CHAR(24),
    CUST_FIRST_NAME       CHAR(6),
    CUST_FATHER_NAME      CHAR(3),
    CUST_FIN_RANGE        DECIMAL(12, 2),
    FIN_RANGE_DT          CHAR(8),
    CUST_ADDRESS_1        CHAR(20),
    CUST_ADDRESS_NO       CHAR(4),
    CUST_CITY             CHAR(20),
    CUST_ZIP_CODE         CHAR(5),
    TOTAL_DRAWDOWN_AMOUNT DECIMAL(12, 2),
    DRAWDOWN_LST_DT       CHAR(8),
    OLD_LOAN_ACCOUNT      CHAR(16),
    TRANSFER_INDICATOR    SMALLINT,
    VALIDATION_CODE       CHAR(2),
    COMPANY_NAME          CHAR(58),
    COMPANY_SHORT_NAME    CHAR(20),
    CUST_ID               INTEGER,
    constraint I0000286
        primary key (OV_REJ_INDIC, FILE_DATE, LINE_SN)
);

