create table BDG_UNIT_TOTAL
(
    FK_BDG_ELEMENTID  CHAR(30) not null,
    FK_BDG_CNTR_UNIFK INTEGER  not null,
    YEAR0             SMALLINT not null,
    STATUS            SMALLINT,
    ACT_FST_RATE      DECIMAL(4, 2),
    ACT_FTH_RATE      DECIMAL(4, 2),
    ACT_THD_RATE      DECIMAL(4, 2),
    ACT_SEC_RATE      DECIMAL(4, 2),
    REV_FST_RATE      DECIMAL(4, 2),
    REV_FTH_RATE      DECIMAL(4, 2),
    REV_THD_RATE      DECIMAL(4, 2),
    REV_SEC_RATE      DECIMAL(4, 2),
    BDG_FST_RATE      DECIMAL(4, 2),
    BDG_SEC_RATE      DECIMAL(4, 2),
    BDG_THD_RATE      DECIMAL(4, 2),
    BDG_FTH_RATE      DECIMAL(4, 2),
    REV_THD_SIZE      DECIMAL(12),
    REV_SEC_SIZE      DECIMAL(12),
    REV_FST_RESULT    DECIMAL(12),
    REV_SEC_RESULT    DECIMAL(12),
    REV_THD_RESULT    DECIMAL(12),
    REV_FTH_RESULT    DECIMAL(12),
    REV_FST_SIZE      DECIMAL(12),
    BDG_FTH_RESULT    DECIMAL(12),
    BDG_THD_RESULT    DECIMAL(12),
    BDG_SEC_RESULT    DECIMAL(12),
    ACT_FST_SIZE      DECIMAL(12),
    ACT_SEC_SIZE      DECIMAL(12),
    ACT_THD_SIZE      DECIMAL(12),
    ACT_FTH_SIZE      DECIMAL(12),
    ACT_FST_RESULT    DECIMAL(12),
    ACT_SEC_RESULT    DECIMAL(12),
    ACT_THD_RESULT    DECIMAL(12),
    ACT_FTH_RESULT    DECIMAL(12),
    BDG_FST_RESULT    DECIMAL(12),
    BDG_FTH_SIZE      DECIMAL(12),
    BDG_THD_SIZE      DECIMAL(12),
    BDG_SEC_SIZE      DECIMAL(12),
    BDG_FST_SIZE      DECIMAL(12),
    REV_FTH_SIZE      DECIMAL(12),
    TMSTMP            DATE,
    constraint IXU_GL_030
        primary key (FK_BDG_ELEMENTID, FK_BDG_CNTR_UNIFK, YEAR0)
);

create unique index I0000351
    on BDG_UNIT_TOTAL (FK_BDG_ELEMENTID);

create unique index I0000353
    on BDG_UNIT_TOTAL (FK_BDG_CNTR_UNIFK);

