create table BDG_UNIT_REAL_TIME
(
    FK_BDG_ELEMENTID  CHAR(30) not null,
    FK_BDG_CNTR_UNIFK INTEGER  not null,
    YEAR0             SMALLINT not null,
    STATUS            SMALLINT,
    BDG_THD_SIZE      DECIMAL(12),
    BDG_SEC_SIZE      DECIMAL(12),
    BDG_FST_RESULT    DECIMAL(12),
    BDG_SEC_RESULT    DECIMAL(12),
    BDG_THD_RESULT    DECIMAL(12),
    BDG_FTH_RESULT    DECIMAL(12),
    REV_FST_SIZE      DECIMAL(12),
    REV_SEC_SIZE      DECIMAL(12),
    REV_THD_SIZE      DECIMAL(12),
    REV_FTH_SIZE      DECIMAL(12),
    REV_FST_RESULT    DECIMAL(12),
    REV_SEC_RESULT    DECIMAL(12),
    REV_THD_RESULT    DECIMAL(12),
    REV_FTH_RESULT    DECIMAL(12),
    ACT_FST_SIZE      DECIMAL(12),
    ACT_SEC_SIZE      DECIMAL(12),
    ACT_THD_SIZE      DECIMAL(12),
    ACT_FTH_SIZE      DECIMAL(12),
    ACT_FST_RESULT    DECIMAL(12),
    ACT_SEC_RESULT    DECIMAL(12),
    ACT_THD_RESULT    DECIMAL(12),
    ACT_FTH_RESULT    DECIMAL(12),
    BDG_FST_SIZE      DECIMAL(12),
    BDG_FTH_SIZE      DECIMAL(12),
    TMSTMP            DATE,
    constraint IXU_GL_049
        primary key (FK_BDG_ELEMENTID, FK_BDG_CNTR_UNIFK, YEAR0)
);

create unique index I0000343
    on BDG_UNIT_REAL_TIME (FK_BDG_ELEMENTID);

create unique index I0000345
    on BDG_UNIT_REAL_TIME (FK_BDG_CNTR_UNIFK);

