create table BDL_CLASSIFICATION
(
    CLASSIFY_CODE    SMALLINT,
    RISK_WEIGHT      INTEGER,
    TMSTAMP          TIMESTAMP(6),
    DIRECT_RISK_FLAG CHAR(1),
    ENTRY_STATUS     CHAR(1),
    DESCRIPTION      VARCHAR(40)
);

create unique index IXU_BDL_000
    on BDL_CLASSIFICATION (CLASSIFY_CODE);

