create table BENEFICIARY
(
    FK_CUSTOMERCUST_ID INTEGER,
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    BENEFICIARY_SN     SMALLINT,
    MANDATE_INSTRUCT   VARCHAR(2048)
);

create unique index IXN_BEN_000
    on BENEFICIARY (FK_DEPOSIT_ACCOACC, FK_CUSTOMERCUST_ID, BENEFICIARY_SN);

create unique index IXU_BEN_000
    on BENEFICIARY (FK_CUSTOMERCUST_ID, FK_DEPOSIT_ACCOACC);

