create table BILL_COMMISSIONS
(
    SERIAL_NUM         DECIMAL(10),
    DEP_ACC_NUMBER     DECIMAL(11),
    PROFITS_ACCOUNT    CHAR(40),
    PROFITS_ACC_CD     SMALLINT,
    PRFT_SYSTEM        SMALLINT,
    ITEM_SERIAL_NUMBER DECIMAL(10),
    BILL_SERIAL_NUMBER DECIMAL(10),
    COM_POSTING_DATE   DATE,
    COMMISSION_AMOUNT  DECIMAL(15, 2),
    ENTRY_STATUS       CHAR(1),
    COM_ID_JUSTIFIC    INTEGER,
    ACC_AMOUNT_1       DECIMAL(15, 2),
    ACC_AMOUNT_2       DECIMAL(15, 2),
    ACC_AMOUNT_3       DECIMAL(15, 2),
    ACC_AMOUNT_4       DECIMAL(15, 2),
    ACC_AMOUNT_5       DECIMAL(15, 2),
    ACC_AMOUNT_6       DECIMAL(15, 2),
    ACC_AMOUNT_7       DECIMAL(15, 2),
    ACC_AMOUNT_8       DECIMAL(15, 2),
    ACC_AMOUNT_9       DECIMAL(15, 2),
    ACC_AMOUNT_10      DECIMAL(15, 2),
    INSERT_DATE        DATE,
    PROGRAM_ID         CHAR(8),
    ERROR_DESC         CHAR(100)
);

create unique index IXN_BIL_118
    on BILL_COMMISSIONS (BILL_SERIAL_NUMBER);

create unique index IXN_BIL_119
    on BILL_COMMISSIONS (DEP_ACC_NUMBER);

create unique index IXU_BIL_010
    on BILL_COMMISSIONS (SERIAL_NUM);

