create table BILL_MASS_REGISTER
(
    EXPACC_PRFSYS      SMALLINT,
    EXPACC_CD          SMALLINT,
    BMAS_TOTBILL_COUNT INTEGER,
    COMM_DISCOUNT      DECIMAL(8, 4),
    EXP_DISCOUNT       DECIMAL(8, 4),
    BMAS_SERIAL_NUM    DECIMAL(10),
    BMAS_TOTBILL_AMNT  DECIMAL(15, 2),
    EXPACC_INTERDATE   DATE,
    BMAS_INS_DATE      DATE,
    BMAS_FINAL_DATE    DATE,
    TMSTAMP            TIMESTAMP(6),
    BMAS_ENTRY_STATUS  CHAR(1),
    BMAS_BILLANAL_FLAG CHAR(1),
    BMAS_CARRIER_ID    CHAR(10),
    BMAS_REF_NO        CHAR(15),
    BMAS_CARRIER_NAME  CHAR(30),
    EXPACC_NUMBER      CHAR(40),
    BMAS_CARRIER_TITLE CHAR(70),
    BMAS_CARRIER_NOTES CHAR(100),
    FK_PRODUCT_ID      INTEGER,
    FK_UNITCODE        INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_USRCODE         CHAR(8),
    BMAS_REG_CCY       INTEGER
);

create unique index IXU_BIL_015
    on BILL_MASS_REGISTER (BMAS_SERIAL_NUM);

