create table BILL_REGISTER
(
    BREG_SERIAL_NUM    DECIMAL(10),
    BREG_TOTBILL_COUNT INTEGER,
    FK_UNITCODE        INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    BREG_TOTBILL_AMNT  DECIMAL(15, 2),
    BREG_COLLECT_DATE  DATE,
    BREG_UPD_DATE      DATE,
    BREG_FINAL_DATE    DATE,
    BREG_INS_DATE      DATE,
    BREG_TMSTAMP       TIMESTAMP(6),
    BREG_ENTRY_STATUS  CHAR(1),
    BREG_BILLANAL_FLAG CHAR(1),
    BREG_STATUS_FLAG   CHAR(1),
    BREG_UPD_USER      CHAR(5),
    FK_USRCODE         CHAR(8),
    BREG_CARRIER_ID    CHAR(10),
    BREG_REF_NO        CHAR(15),
    BREG_CARRIER_NAME  CHAR(30),
    BREG_CARRIER_TITLE CHAR(70),
    BREG_CARRIER_NOTES CHAR(100),
    FK_GENERIC_HEAD    CHAR(5),
    FK_GENERDET_SERIAL INTEGER,
    COMMISSION_AMNT_1  DECIMAL(15, 2),
    COMMISSION_AMNT_2  DECIMAL(15, 2),
    COMMISSION_AMNT_3  DECIMAL(15, 2),
    EXPENSE_AMNT_1     DECIMAL(15, 2),
    EXPENSE_AMNT_2     DECIMAL(15, 2),
    EXPENSE_AMNT_3     DECIMAL(15, 2),
    TAX_AMNT_1         DECIMAL(15, 2),
    TAX_AMNT_2         DECIMAL(15, 2),
    TAX_AMNT_3         DECIMAL(15, 2),
    BREG_STATUS_DESCR  CHAR(20)
);

create unique index IXN_BIL_100
    on BILL_REGISTER (FK_GENERIC_HEAD, FK_GENERDET_SERIAL);

create unique index IXU_BIL_004
    on BILL_REGISTER (BREG_SERIAL_NUM);

