create table BILL_ISSUER
(
    BISS_CODE          INTEGER,
    BISS_CDIGIT        SMALLINT,
    BISS_SPRD_PERC     DECIMAL(8, 4),
    BISS_UTIL_LIMT     DECIMAL(15, 2),
    BISS_LIMIT         DECIMAL(15, 2),
    BISS_TMSTAMP       TIMESTAMP(6),
    BISS_TYPE          CHAR(1),
    BISS_IN_BLACK_LIST CHAR(1),
    BISS_ENTRY_STATUS  CHAR(1),
    BISS_LIMITTYPE     CHAR(1),
    BISS_TELEPHONE     CHAR(15),
    BISS_AFM_NO        CHAR(20),
    BISS_FATHERNAM     CHAR(20),
    BISS_FIRSTNAME     CHAR(20),
    BISS_ID_INFO       CHAR(20),
    BISS_APPRV_NO      CHAR(30),
    BISS_IBAN_CODE     CHAR(37),
    BISS_PROFES        CHAR(40),
    BISS_ADDRESS       CHAR(40),
    BISS_BLIST_MESS    CHAR(50),
    BISS_TITLE         CHAR(70),
    BISS_NON_RESIDENT  CHAR(1),
    FK_ISSUECNTRY_DFK  CHAR(5),
    FK_ISSUECNTRY_SER  INTEGER
);

create unique index IX3_BILL_ISS
    on BILL_ISSUER (BISS_AFM_NO, BISS_TYPE);

create unique index IXU_BIL_008
    on BILL_ISSUER (BISS_CODE);

