create table BILL_SEGMENT
(
    CR_DEP_TUN_INT_SN  SMALLINT,
    CR_LNS_TRX_INT_SN  SMALLINT,
    CRACC_CD           SMALLINT,
    CRACC_PRFSYS       SMALLINT,
    CR_LNS_TRX_UNIT    INTEGER,
    CR_DEP_TRX_UNIT    INTEGER,
    CR_DEP_TRX_USR_SN  INTEGER,
    CR_LNS_TRX_SN      INTEGER,
    SEGM_SERIAL_NUM    DECIMAL(10),
    FK_BILLSERIAL_NUM  DECIMAL(10),
    CRACC_AMOUNT       DECIMAL(15, 2),
    CR_DEP_TRX_DATE    DATE,
    CR_LNS_TRX_DATE    DATE,
    TMSTAMP            TIMESTAMP(6),
    CR_LNS_TMSTAMP     TIMESTAMP(6),
    CR_DEP_TRX_USR     CHAR(8),
    CR_LNS_TRX_USR     CHAR(8),
    CRACC_NUMBER       CHAR(40),
    CRACC_PAID_AMNT    DECIMAL(15, 2),
    REVERSE_FLG        CHAR(1),
    REVERSE_AMNT       DECIMAL(15, 2),
    DEALER_REF_NO      CHAR(20),
    DEALER_USRCOD      CHAR(8),
    ACC_CONVERTED_AMNT DECIMAL(15, 2),
    FXFT_TUN_SN        INTEGER,
    ACC_CONV_RATE      DECIMAL(12, 6)
);

create unique index I0000935
    on BILL_SEGMENT (FK_BILLSERIAL_NUM);

create unique index PK_BILLSEGM
    on BILL_SEGMENT (SEGM_SERIAL_NUM);

