create table BILL_GROUP_HEADER
(
    PRFT_SYSTEM        SMALLINT,
    ACCOUNT_CD         SMALLINT,
    GROUP_ID           SMALLINT,
    TRX_UNIT           INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    TOTAL_COUNT        INTEGER,
    BORDEREAU_NUM      DECIMAL(10),
    EXPENSES_AMOUNT    DECIMAL(15, 2),
    SUM_EXPENSE_AMNT   DECIMAL(15, 2),
    TOTAL_AMOUNT       DECIMAL(15, 2),
    STAMP_AMOUNT       DECIMAL(15, 2),
    TRX_DATE           DATE,
    TIMESTAMP          TIMESTAMP(6),
    TRX_USER           CHAR(8),
    PRFT_ACCOUNT       CHAR(40),
    COMMISSION_AMNT_1  DECIMAL(15, 2),
    COMMISSION_AMNT_2  DECIMAL(15, 2),
    COMMISSION_AMNT_3  DECIMAL(15, 2),
    EXPENSE_AMNT_1     DECIMAL(15, 2),
    EXPENSE_AMNT_2     DECIMAL(15, 2),
    EXPENSE_AMNT_3     DECIMAL(15, 2),
    SUM_COMM_AMNT      DECIMAL(15, 2),
    TAX_AMNT_1         DECIMAL(15, 2),
    TAX_AMNT_2         DECIMAL(15, 2),
    TAX_AMNT_3         DECIMAL(15, 2)
);

create unique index IXU_BIL_122
    on BILL_GROUP_HEADER (TRX_UNIT, TRX_DATE, TRX_USER, BORDEREAU_NUM, GROUP_ID);

