create table BILL
(
    BILL_SERIAL_NUM      DECIMAL(10),
    BILL_DEBACC_PRFSYS   SMALLINT,
    BILL_EXPACC_CD       SMALLINT,
    BILL_EXPACC_PRFSYS   SMALLINT,
    DEB_DEP_TUN_INT_SN   SMALLINT,
    DEB_LNS_TRX_INT_SN   SMALLINT,
    CR_DEP_TUN_INT_SN    SMALLINT,
    CR_LNS_TRX_INT_SN    SMALLINT,
    BILL_DEBACC_CD       SMALLINT,
    BILL_COLL_PRFSYS     SMALLINT,
    BILL_COLL_ACC_CD     SMALLINT,
    BILL_CRACC_PRFSYS    SMALLINT,
    BILL_CR_ACC_CD       SMALLINT,
    BILL_SENDTOCLR_CNT   SMALLINT,
    BILL_CHECK_DIGIT     SMALLINT,
    EXP_LNS_TRX_INT_SN   SMALLINT,
    EXP_DEP_TUN_INT_SN   SMALLINT,
    COLL_TUN_INT_SN      SMALLINT,
    FK_BGRP_SERIAL_NUM   SMALLINT,
    BILL_EXP_INTERDAYS   SMALLINT,
    BILL_CRACC_AVLDAYS   SMALLINT,
    BILL_CRACC_INTDAYS   SMALLINT,
    FK_OVD_GENERIC_SN    INTEGER,
    OVD_TUN_UNIT         INTEGER,
    BILL_CRACC_JUSTIF    INTEGER,
    BILL_COLL_JUSTIF     INTEGER,
    BILL_DEBACC_JUST     INTEGER,
    BILL_EXP_DB_JUST     INTEGER,
    DEB_DEP_TRX_UNIT     INTEGER,
    DEB_LNS_TRX_UNIT     INTEGER,
    CR_DEP_TRX_UNIT      INTEGER,
    CR_LNS_TRX_UNIT      INTEGER,
    EXP_DEP_TRX_UNIT     INTEGER,
    EXP_LNS_TRX_UNIT     INTEGER,
    COLL_TRX_UNIT        INTEGER,
    FK_BLST_COLBANK_ID   INTEGER,
    FK_UNITCODE          INTEGER,
    FK_COLL_BANK_ID      INTEGER,
    FK_CURR_ID_ISSUED    INTEGER,
    FK_CURR_ID_PAY       INTEGER,
    CLR_AGENT_CODE       INTEGER,
    BILL_PRODUCT_ID      INTEGER,
    BILL_PRFT_TRANS_ID   INTEGER,
    BILL_JUSTIFIC_ID     INTEGER,
    FK_CUSTOMERCUST_ID   INTEGER,
    FK_BISS_CODE         INTEGER,
    OVD_TUN_USR_SN       INTEGER,
    COLL_TRX_USR_SN      INTEGER,
    EXP_LNS_TRX_SN       INTEGER,
    EXP_DEP_TRX_USR_SN   INTEGER,
    CR_LNS_TRX_SN        INTEGER,
    CR_DEP_TRX_USR_SN    INTEGER,
    DEB_LNS_TRX_SN       INTEGER,
    BILL_COLL_YIELD_PERC DECIMAL(8, 5),
    DEB_DEP_TRX_USR_SN   INTEGER,
    FK_BGRP_BREGISTR     DECIMAL(10),
    FK_MASS_REG_SER      DECIMAL(10),
    BILL_COLL_SN         DECIMAL(10),
    FK_BREG_SERIAL_NUM   DECIMAL(10),
    BILL_AMOUNT          DECIMAL(15, 2),
    BILL_PURCHASE_DATE   DATE,
    CR_LNS_TRX_DATE      DATE,
    BILL_ISSUE_DATE      DATE,
    COLL_TRX_DATE        DATE,
    EXP_LNS_TRX_DATE     DATE,
    EXP_DEP_TRX_DATE     DATE,
    CR_DEP_TRX_DATE      DATE,
    DEB_LNS_TRX_DATE     DATE,
    DEB_DEP_TRX_DATE     DATE,
    BILL_EXP_INTERDATE   DATE,
    BILL_FINAL_DATE      DATE,
    BILL_UPD_DATE        DATE,
    BILL_INS_DATE        DATE,
    BILL_CRACC_AVLDT     DATE,
    BILL_CRACC_INTDT     DATE,
    OVD_TUN_DATE         DATE,
    CR_LNS_TMSTAMP       TIMESTAMP(6),
    BILL_COLL_TMSTAMP    TIMESTAMP(6),
    DEB_LNS_TMSTAMP      TIMESTAMP(6),
    EXP_LNS_TMSTAMP      TIMESTAMP(6),
    BILL_TMSTAMP         TIMESTAMP(6),
    BILL_CHARGES_ONACC   CHAR(1),
    BILL_CLRTYPE_FLAG    CHAR(1),
    BILL_PURCHASE_HOLD   CHAR(1),
    BILL_OWNBANK_FLAG    CHAR(1),
    BILL_VALIDATE_FLG    CHAR(1),
    BILL_TYPE_FLAG       CHAR(1),
    BILL_ENTRY_STATUS    CHAR(1),
    BILL_TRACEFLOW_FLG   CHAR(1),
    BILL_REJECTED_FLAG   CHAR(1),
    OVERDUE_FLG          CHAR(1),
    BILL_STATUS_FLAG     CHAR(2),
    FK_OVD_GENERHEAD     CHAR(5),
    BILL_BARCODE         CHAR(5),
    BILL_BRANCH_CODE     CHAR(5),
    BILL_SPECIAL_CHARS   CHAR(5),
    BILL_UPD_USER        CHAR(8),
    FK_USRCODE           CHAR(8),
    COLL_TRX_USR         CHAR(8),
    EXP_LNS_TRX_USR      CHAR(8),
    EXP_DEP_TRX_USR      CHAR(8),
    CR_LNS_TRX_USR       CHAR(8),
    CR_DEP_TRX_USR       CHAR(8),
    DEB_LNS_TRX_USR      CHAR(8),
    DEB_DEP_TRX_USR      CHAR(8),
    FK0USRCODE           CHAR(8),
    OVD_TUN_USR          CHAR(8),
    BILL_CARRIER_ID      CHAR(10),
    BILL_COLL_CODE       CHAR(20),
    BILL_NUMBER          CHAR(20),
    BILL_CARRIER_NAME    CHAR(30),
    BILL_IBAN_CODE       CHAR(37),
    BILL_ACCOUNT_NUMB    CHAR(40),
    BILL_EXPACC_NUMBER   CHAR(40),
    BILL_DEBACC_NUMBER   CHAR(40),
    BILL_CR_ACC_NUMBER   CHAR(40),
    BILL_COLL_ACC_NUMB   CHAR(40),
    BILL_CARRIER_TITLE   CHAR(70),
    BILL_CARRIER_NOTES   CHAR(100),
    BILL_REJECT_NOTES    CHAR(200),
    FK_BLST_CHEQUE_NUM   VARCHAR(20),
    COMMENTS             VARCHAR(200),
    BILL_NUMBER_NUM      DECIMAL(18),
    BILL_COMM_DISCOUNT   DECIMAL(8, 4),
    BILL_EXP_DISCOUNT    DECIMAL(8, 4),
    MIGRATED_FLG         CHAR(1),
    OVD_JUSTIFIC         INTEGER,
    COLL_REMOVAL_DATE    DATE,
    TEMP_BILL_STATUS_F   CHAR(2),
    CP_AGREEMENT_NO      DECIMAL(10),
    CP_DATA_FIELD_1      CHAR(80),
    CP_DATA_FIELD_2      CHAR(80),
    CP_DATA_FIELD_3      CHAR(80),
    CP_DATA_FIELD_4      CHAR(80),
    IMAGE_PATH           VARCHAR(200),
    CP_PROCESSED_FLG     CHAR(1),
    CP_TP_IDENTIFIER     DECIMAL(10),
    CP_DB_TRX_DATE       DATE,
    CP_DB_TRX_UNIT       INTEGER,
    CP_DB_TRX_USR        CHAR(8),
    CP_DB_TRX_USR_SN     INTEGER,
    CP_DB_TRX_INT_SN     SMALLINT,
    CLEARING_PRCSS_ID    DECIMAL(10),
    DEALER_REF_NO        CHAR(20),
    DEALER_USRCOD        CHAR(8),
    ACC_CONVERTED_AMNT   DECIMAL(15, 2),
    FXFT_TUN_SN          INTEGER,
    ACC_CONV_RATE        DECIMAL(12, 6),
    EXP_CONVERTED_AMNT   DECIMAL(15, 2),
    EXP_FXFT_TUN_SN      INTEGER,
    EXP_CONV_RATE        DECIMAL(12, 6),
    CR_FXFT_TUN_SN       INTEGER,
    CR_FXFT_TUN_INT_SN   SMALLINT,
    DB_FXFT_TUN_SN       INTEGER,
    DB_FXFT_TUN_INT_SN   SMALLINT,
    EXP_FXFT_TUNINT_SN   SMALLINT,
    BILL_CODELINE        CHAR(60),
    MCH_REJECTION_CD     CHAR(5),
    CP_HASH_CODE         VARCHAR(100)
);

create unique index IDX_BILL_255
    on BILL (BILL_CR_ACC_NUMBER, BILL_CR_ACC_CD, BILL_STATUS_FLAG);

create unique index IXN_BIL_038
    on BILL (BILL_COLL_ACC_NUMB);

create unique index IXN_BIL_103
    on BILL (BILL_NUMBER, BILL_SERIAL_NUM, BILL_ISSUE_DATE, BILL_FINAL_DATE, BILL_STATUS_FLAG, BILL_TYPE_FLAG,
             BILL_CLRTYPE_FLAG, OVERDUE_FLG, BILL_PURCHASE_DATE);

create unique index IXN_BIL_104
    on BILL (FK_BREG_SERIAL_NUM, BILL_SERIAL_NUM, FK_BGRP_BREGISTR, FK_BGRP_SERIAL_NUM, BILL_ISSUE_DATE,
             BILL_FINAL_DATE, BILL_STATUS_FLAG, BILL_TYPE_FLAG, BILL_CLRTYPE_FLAG, OVERDUE_FLG, BILL_PURCHASE_DATE);

create unique index IXN_BIL_107
    on BILL (FK_BISS_CODE, BILL_SERIAL_NUM, BILL_ISSUE_DATE, BILL_FINAL_DATE, BILL_STATUS_FLAG, BILL_TYPE_FLAG,
             BILL_CLRTYPE_FLAG, OVERDUE_FLG, BILL_PURCHASE_DATE);

create unique index IXN_BIL_108
    on BILL (BILL_STATUS_FLAG);

create unique index IXN_BIL_109
    on BILL (FK_UNITCODE);

create unique index IXN_BIL_112
    on BILL (FK_BISS_CODE, FK_BREG_SERIAL_NUM, FK_CURR_ID_PAY, FK_CUSTOMERCUST_ID, FK_UNITCODE, FK_CURR_ID_ISSUED,
             FK_COLL_BANK_ID, BILL_SERIAL_NUM);

create unique index IXN_BIL_115
    on BILL (FK_MASS_REG_SER, BILL_SERIAL_NUM);

create unique index IXN_BIL_117
    on BILL (BILL_NUMBER_NUM, BILL_SERIAL_NUM, FK_COLL_BANK_ID, BILL_COLL_SN);

create unique index IXU_BIL_006
    on BILL (BILL_SERIAL_NUM);

create unique index IXU_BIL_011
    on BILL (BILL_ISSUE_DATE);

create unique index IXU_BIL_012
    on BILL (BILL_PURCHASE_DATE, BILL_SERIAL_NUM, BILL_ISSUE_DATE, BILL_FINAL_DATE, BILL_STATUS_FLAG, BILL_TYPE_FLAG,
             BILL_CLRTYPE_FLAG, OVERDUE_FLG);

create unique index IXU_BIL_013
    on BILL (FK_CUSTOMERCUST_ID, BILL_SERIAL_NUM, BILL_PURCHASE_DATE, BILL_ISSUE_DATE, BILL_FINAL_DATE,
             BILL_STATUS_FLAG, BILL_TYPE_FLAG, BILL_CLRTYPE_FLAG, OVERDUE_FLG);

create unique index IXU_BIL_014
    on BILL (FK_UNITCODE, BILL_SERIAL_NUM, FK_CUSTOMERCUST_ID, BILL_PURCHASE_DATE, FK_BISS_CODE, BILL_ISSUE_DATE,
             BILL_FINAL_DATE, BILL_STATUS_FLAG, BILL_TYPE_FLAG, BILL_CLRTYPE_FLAG, OVERDUE_FLG);

