create table BILL_GS_REG_CHEQS
(
    FK_GSREG_SERIALNUM     DECIMAL(10),
    GS_CHQ_SERIAL_NUM      DECIMAL(10),
    GS_CHQ_BISS_CDIGIT     SMALLINT,
    GS_CHQ_ACCOUNT_CD      SMALLINT,
    GS_CHQ_COLLAB_BANK_ID  INTEGER,
    GS_CHQ_REJECTION_CD    INTEGER,
    GS_CHQ_BISS_CODE       INTEGER,
    GS_CHQ_BILL_SERIAL_NUM DECIMAL(10),
    GS_CHQ_AMOUNT          DECIMAL(15, 2),
    GS_CHQ_ISSUE_DATE      DATE,
    GS_CHQ_UPD_DATE        DATE,
    GS_CHQ_INS_DATE        DATE,
    GS_CHQ_TMSTAMP         TIMESTAMP(6),
    GS_CHQ_ENTRY_STATUS    CHAR(1),
    GS_CHQ_STATUS_FLAG     CHAR(1),
    GS_CHQ_TYPE_FLG        CHAR(1),
    GS_CHQ_UPD_USER        CHAR(8),
    GS_CHQ_NUMBER          CHAR(20),
    GS_CHQ_ACCOUNT_NUMBER  CHAR(40),
    GS_CHQ_CLEARING_DESC   CHAR(100),
    GS_CHQ_MAN_PAY_FLG     CHAR(1),
    GS_CHQ_CW_SERIAL       DECIMAL(10),
    GS_COM_REVERSED        CHAR(1),
    GS_COM_TOT_AMOUNT      DECIMAL(15, 2),
    GS_COM_TUN_DATE        DATE,
    GS_COM_TUN_INTERN_SN   SMALLINT,
    GS_COM_TUN_UNIT        INTEGER,
    GS_COM_TUN_USR         CHAR(8),
    GS_COM_TUN_USR_SN      INTEGER
);

create unique index IXU_BIL_001
    on BILL_GS_REG_CHEQS (FK_GSREG_SERIALNUM, GS_CHQ_SERIAL_NUM);

