create table BILL_PARAMETERS
(
    BPR_CURRENT_YEAR   CHAR(4),
    BPR_MAXISSUE_LIMIT SMALLINT,
    GS_SEND_UNIT       INTEGER,
    BPR_CLR_AGENT      INTEGER,
    BPR_MAXAMNT_PERCHQ DECIMAL(15, 2),
    CORR_UNPAID_LIMIT  DECIMAL(15, 2),
    BPR_CAN_FINALIZE   CHAR(1),
    BPR_CORR_FILE_FC   CHAR(20),
    BPR_CORR_FILENAME  CHAR(20),
    NO_COLL_REMOVAL    CHAR(1),
    ONL_DHSSE_JUSTIF   INTEGER,
    SEND_BEF_MAT_DAYS  SMALLINT,
    BPR_MINISSUE_LIMIT SMALLINT,
    CLEARING_SYSTEM    CHAR(2),
    NO_CHEQUE_CD_FLG   CHAR(1)
);

create unique index IXU_BIL_005
    on BILL_PARAMETERS (BPR_CURRENT_YEAR);

