create table BILL_MASSREG_SEGM
(
    BILL_CR_ACC_CD     SMALLINT,
    BILL_CRACC_PRFSYS  SMALLINT,
    MASSEG_SERIAL_NUM  DECIMAL(10),
    CRACC_AMOUNT       DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    BILL_CR_ACC_NUMBER CHAR(40),
    FK_MASS_REG_SERIAL DECIMAL(10),
    DEALER_REF_NO      CHAR(20),
    DEALER_USRCOD      CHAR(8),
    CONVERSION_RATE    DECIMAL(12, 6),
    CONVERTED_AMOUNT   DECIMAL(15, 2),
    COMMENTS           CHAR(40)
);

create unique index PK_MASSEG
    on BILL_MASSREG_SEGM (MASSEG_SERIAL_NUM);

