create table BILL_INV
(
    BILL_SERIAL_NUM      DECIMAL(10)    not null
        constraint IXU_BIL_17
            primary key,
    BINV_PRODUCT_ID      INTEGER,
    BINV_PRFT_TRANS_ID   INTEGER,
    BINV_JUSTIFIC_ID     INTEGER,
    BINV_CARRIER_TITLE   CHAR(70),
    BINV_CARRIER_NAME    CHAR(30),
    BINV_CARRIER_ID      CHAR(10),
    BINV_CARRIER_NOTES   CHAR(100),
    BINV_NUMBER          CHAR(20)       not null,
    BINV_ISSUE_DATE      DATE           not null,
    BINV_AMOUNT          DECIMAL(15, 2) not null,
    BINV_CLRTYPE_FLAG    CHAR(1)        not null,
    BINV_STATUS_FLAG     CHAR(2),
    BINV_TYPE_FLAG       CHAR(1),
    BINV_VALIDATE_FLG    CHAR(1),
    BINV_ACCOUNT_NUMB    CHAR(40)       not null,
    BINV_BARCODE         CHAR(5),
    BINV_BRANCH_CODE     CHAR(5),
    BINV_SPECIAL_CHARS   CHAR(5),
    BINV_INS_DATE        DATE,
    BINV_UPD_DATE        DATE,
    BINV_UPD_USER        CHAR(5),
    BINV_FINAL_DATE      DATE,
    BINV_OWNBANK_FLAG    CHAR(1),
    BINV_CHARGES_ONACC   CHAR(1),
    BINV_SENDTOCLR_CNT   SMALLINT,
    BINV_IBAN_CODE       CHAR(37),
    BINV_REJECTED_FLAG   CHAR(1),
    BINV_REJECT_NOTES    CHAR(200),
    BINV_TRACEFLOW_FLG   CHAR(1),
    BINV_ENTRY_STATUS    CHAR(1)        not null,
    BINV_TMSTAMP         TIMESTAMP(6)   not null,
    BINV_CR_ACC_NUMBER   CHAR(40),
    BINV_CR_ACC_CD       SMALLINT,
    BINV_CRACC_PRFSYS    SMALLINT,
    BINV_CRACC_JUSTIF    INTEGER,
    BINV_CRACC_AVLDAYS   SMALLINT,
    BINV_CRACC_INTDAYS   SMALLINT,
    BINV_COLL_ACC_NUMB   CHAR(40),
    BINV_COLL_ACC_CD     SMALLINT,
    BINV_COLL_PRFSYS     SMALLINT,
    BINV_COLL_JUSTIF     INTEGER,
    BINV_COLL_YIELD_PERC DECIMAL(8, 5),
    BINV_DEBACC_NUMBER   CHAR(40),
    BINV_DEBACC_CD       SMALLINT,
    BINV_DEBACC_PRFSYS   SMALLINT,
    BINV_DEBACC_JUST     INTEGER,
    BINV_EXP_INTERDATE   DATE,
    BINV_EXP_INTERDAYS   SMALLINT,
    BINV_EXP_DB_JUST     INTEGER,
    FK_BGRP_BREGISTR     DECIMAL(10),
    FK_BGRP_SERIAL_NUM   SMALLINT,
    FK_BREG_SERIAL_NUM   DECIMAL(10),
    FK_BISS_CODE         INTEGER,
    FK_CURR_ID_PAY       INTEGER,
    FK_CUSTOMERCUST_ID   INTEGER,
    FK_UNITCODE          INTEGER,
    FK_USRCODE           CHAR(8),
    FK_BLST_COLBANK_ID   INTEGER,
    FK_BLST_CHEQUE_NUM   VARCHAR(20),
    FK_CURR_ID_ISSUED    INTEGER,
    FK_COLL_BANK_ID      INTEGER,
    FK0USRCODE           CHAR(8),
    DEB_DEP_TRX_UNIT     INTEGER,
    DEB_DEP_TRX_DATE     DATE,
    DEB_DEP_TRX_USR      CHAR(8),
    DEB_DEP_TRX_USR_SN   INTEGER,
    DEB_DEP_TUN_INT_SN   SMALLINT,
    DEB_LNS_TMSTAMP      TIMESTAMP(6),
    DEB_LNS_TRX_DATE     DATE,
    DEB_LNS_TRX_UNIT     INTEGER,
    DEB_LNS_TRX_USR      CHAR(8),
    DEB_LNS_TRX_SN       INTEGER,
    DEB_LNS_TRX_INT_SN   SMALLINT,
    CR_DEP_TRX_UNIT      INTEGER,
    CR_DEP_TRX_DATE      DATE,
    CR_DEP_TRX_USR       CHAR(8),
    CR_DEP_TRX_USR_SN    INTEGER,
    CR_DEP_TUN_INT_SN    SMALLINT,
    CR_LNS_TMSTAMP       TIMESTAMP(6),
    CR_LNS_TRX_DATE      DATE,
    CR_LNS_TRX_UNIT      INTEGER,
    CR_LNS_TRX_USR       CHAR(8),
    CR_LNS_TRX_SN        INTEGER,
    EXP_DEP_TRX_UNIT     INTEGER,
    EXP_DEP_TRX_DATE     DATE,
    EXP_DEP_TRX_USR      CHAR(8),
    EXP_DEP_TRX_USR_SN   INTEGER,
    EXP_DEP_TUN_INT_SN   SMALLINT,
    EXP_LNS_TMSTAMP      TIMESTAMP(6),
    EXP_LNS_TRX_DATE     DATE,
    EXP_LNS_TRX_USR      CHAR(8),
    EXP_LNS_TRX_SN       INTEGER,
    EXP_LNS_TRX_INT_SN   SMALLINT,
    COLL_TRX_UNIT        INTEGER,
    COLL_TRX_DATE        DATE,
    COLL_TRX_USR         CHAR(8),
    COLL_TRX_USR_SN      INTEGER,
    COLL_TUN_INT_SN      SMALLINT,
    CR_LNS_TRX_INT_SN    SMALLINT,
    EXP_LNS_TRX_UNIT     INTEGER,
    BINV_CHECK_DIGIT     SMALLINT,
    BILL_COLL_SN         DECIMAL(10),
    BILL_COLL_CODE       CHAR(20),
    BILL_COLL_TMSTAMP    TIMESTAMP(6),
    BINV_EXPACC_NUMBER   CHAR(40),
    BINV_EXPACC_CD       SMALLINT,
    BINV_EXPACC_PRFSYS   SMALLINT,
    CLR_AGENT_CODE       INTEGER,
    BINV_PURCHASE_DATE   DATE,
    BINV_PURCHASE_HOLD   CHAR(1),
    FK_OVD_GENERHEAD     CHAR(5),
    FK_OVD_GENERIC_SN    INTEGER,
    OVERDUE_FLG          CHAR(1),
    OVD_TUN_UNIT         INTEGER,
    OVD_TUN_USR          CHAR(8),
    OVD_TUN_DATE         DATE,
    OVD_TUN_USR_SN       INTEGER,
    COMMENTS             VARCHAR(200),
    BINV_CRACC_AVLDT     DATE,
    BINV_CRACC_INTDT     DATE,
    FK_MASS_REG_SER      DECIMAL(10),
    BILL_NUMBER_NUM      DECIMAL(15),
    BINV_COMM_DISCOUNT   DECIMAL(8, 4),
    BINV_EXP_DISCOUNT    DECIMAL(8, 4),
    BINV_CUST_DESIG      CHAR(100),
    BINV_CUST_AFM        CHAR(20),
    BINV_CUST_DOY        CHAR(20),
    BINV_PAY_DATE        DATE,
    SEC_NOTICE_DATE      DATE,
    FIRST_NOTICE_DATE    DATE,
    EXP_AMOUNT           DECIMAL(15, 2),
    BINV_CR_PAID_AMNT    DECIMAL(15, 2),
    REVERSE_FLG          CHAR(1),
    REVERSE_AMNT         DECIMAL(15, 2),
    REV_TRX_DATE         DATE,
    REV_TRX_UNIT         INTEGER,
    REV_TRX_USR          CHAR(8),
    REV_TRX_SN           INTEGER,
    REV_TRX_INT_SN       SMALLINT,
    TUN_TRX_DATE         DATE,
    TUN_TRX_UNIT         INTEGER,
    TUN_TRX_USR          CHAR(8),
    TUN_TRX_USR_SN       INTEGER,
    TUN_TRX_INTERNAL_SN  SMALLINT,
    MONITOR_UNIT_CODE    INTEGER,
    COLL_REMOVAL_DATE    DATE,
    REV2_TRX_DATE        DATE,
    REV2_TRX_UNIT        INTEGER,
    REV2_TRX_USR         CHAR(8),
    REV2_TRX_USR_SN      INTEGER,
    REV2_TRX_INT_SN      SMALLINT
);

create unique index IXN_BIL_18
    on BILL_INV (FK_BREG_SERIAL_NUM);

create unique index IXN_BIL_19
    on BILL_INV (FK_CUSTOMERCUST_ID);

create unique index IXN_BIL_20
    on BILL_INV (FK_UNITCODE);

create unique index IXN_BIL_21
    on BILL_INV (FK_USRCODE);

create unique index IXN_BIL_22
    on BILL_INV (FK_BLST_COLBANK_ID, FK_BLST_CHEQUE_NUM);

create unique index IXN_BIL_23
    on BILL_INV (FK_CURR_ID_ISSUED);

create unique index IXN_BIL_24
    on BILL_INV (FK_COLL_BANK_ID);

create unique index IXN_BIL_25
    on BILL_INV (FK0USRCODE);

create unique index IXN_BIL_26
    on BILL_INV (FK_OVD_GENERHEAD, FK_OVD_GENERIC_SN);

create unique index IXN_BIL_27
    on BILL_INV (FK_MASS_REG_SER);

create unique index IXN_BIL_28
    on BILL_INV (FK_BGRP_BREGISTR, FK_BGRP_SERIAL_NUM);

create unique index IXN_BIL_29
    on BILL_INV (FK_BISS_CODE);

create unique index IXN_BIL_30
    on BILL_INV (FK_CURR_ID_PAY);

