create table BILL_SPRD_PER_CUST
(
    FK_CUSTOMERCUST_ID INTEGER,
    FK_BISS_CODE       INTEGER,
    BILLSPR_ENTRY_STAT CHAR(1),
    BILLSPR_TMSTAMP    TIMESTAMP(6),
    BILLSPR_PERCENT    DECIMAL(8, 4),
    BILLSPR_UTIL_AMNT  DECIMAL(15, 2),
    BILLSPR_AMOUNT     DECIMAL(15, 2),
    BILLSPR_SPRD_TYPE  CHAR(1)
);

create unique index IXU_BIL_003
    on BILL_SPRD_PER_CUST (FK_CUSTOMERCUST_ID, FK_BISS_CODE, BILLSPR_ENTRY_STAT, BILLSPR_TMSTAMP);

