create table BILL_LIMIT_U
(
    FK_CUSTOMERCUST_ID INTEGER        not null,
    FK_CURRENCYID_CUR  INTEGER,
    BLIMIT_TMSTAMP     TIMESTAMP(6)   not null,
    BLIMIT_AMOUNT      DECIMAL(15, 2) not null,
    BLIMIT_ENTRY_STAT  CHAR(1)        not null,
    BLIMIT_COUNT       INTEGER,
    BLIMIT_MAXISS_LIM  SMALLINT,
    BLIMIT_SPRD_VALUE  SMALLINT,
    BLIMIT_SPRD_AVAIL  SMALLINT,
    BLIMIT_YIELD_PERC  DECIMAL(5, 2),
    constraint IXU_CIU_003
        primary key (BLIMIT_ENTRY_STAT, BLIMIT_TMSTAMP, FK_CUSTOMERCUST_ID)
);

