create table BILL_LIMIT
(
    FK_CUSTOMERCUST_ID INTEGER,
    BLIMIT_ENTRY_STAT  CHAR(1),
    BLIMIT_TMSTAMP     TIMESTAMP(6),
    BLIMIT_MAXISS_LIM  SMALLINT,
    BLIMIT_SPRD_AVAIL  SMALLINT,
    BLIMIT_SPRD_VALUE  SMALLINT,
    BLIMIT_YIELD_PERC  DECIMAL(5, 2),
    FK_CURRENCYID_CUR  INTEGER,
    BLIMIT_COUNT       INTEGER,
    BLIMIT_AMOUNT      DECIMAL(15, 2)
);

create unique index IXU_BIL_009
    on BILL_LIMIT (FK_CUSTOMERCUST_ID, BLIMIT_ENTRY_STAT, BLIMIT_TMSTAMP);

