create table BILL_GS_REGISTER
(
    BREG_GS_SERIAL_NUM    DECIMAL(10),
    BREG_GS_TOTBILL_COUNT INTEGER,
    FK_UNITCODE           INTEGER,
    BREG_GS_TOTBILL_AMNT  DECIMAL(15, 2),
    BREG_GS_COLLECT_DATE  DATE,
    BREG_GS_FINAL_DATE    DATE,
    BREG_GS_UPD_DATE      DATE,
    BREG_GS_INS_DATE      DATE,
    BREG_GS_TMSTAMP       TIMESTAMP(6),
    BREG_GS_ENTRY_STATUS  CHAR(1),
    BREG_GS_STATUS_FLAG   CHAR(1),
    FK_USRCODE            CHAR(8),
    BREG_GS_UPD_USER      CHAR(8),
    BREG_GS_REF_NO        CHAR(15),
    BREG_GS_CCY           INTEGER
);

create unique index IXU_BIL_000
    on BILL_GS_REGISTER (BREG_GS_SERIAL_NUM);

