create table BILL_EXTRAIT
(
    C_DIGIT             SMALLINT,
    PRFT_SYSTEM         SMALLINT,
    DEB_ACC_CD          SMALLINT,
    EXP_PRFT_SYSTEM     SMALLINT,
    EXP_ACC_CD          SMALLINT,
    CR_PRFT_SYSTEM      SMALLINT,
    TUN_TRX_INTERNAL_SN SMALLINT,
    CR_ACC_CD           SMALLINT,
    COLL_ACC_CD         SMALLINT,
    COLL_PRFT_SYSTEM    SMALLINT,
    DEB_PRFT_SYSTEM     SMALLINT,
    TUN_TRX_UNIT        INTEGER,
    JUSTIFIC_ID         INTEGER,
    PRODUCT_ID          INTEGER,
    TRANSACT_ID         INTEGER,
    CUST_ID             INTEGER,
    EXP_DISCOUNT_PERC   DECIMAL(8, 4),
    TUN_TRX_USR_SN      INTEGER,
    COMM_DISCOUNT_PERC  DECIMAL(8, 4),
    BILL_SERIAL_NUM     DECIMAL(10),
    DUE_AMOUNT          DECIMAL(15, 2),
    BILL_AMOUNT         DECIMAL(15, 2),
    CREDIT_AMOUNT       DECIMAL(15, 2),
    DEBIT_AMOUNT        DECIMAL(15, 2),
    OVERDUE_AMOUNT      DECIMAL(15, 2),
    COMMISSION_AMOUNT   DECIMAL(15, 2),
    TUN_TRX_DATE        DATE,
    TMSTAMP             TIMESTAMP(6),
    OVERDUE_FLG         CHAR(1),
    TUN_TRX_USR         CHAR(8),
    EXP_ACC_NUMBER      CHAR(40),
    COLL_ACC_NUMBER     CHAR(40),
    CR_ACC_NUMBER       CHAR(40),
    DEB_ACC_NUMBER      CHAR(40),
    COLL_AMOUNT         DECIMAL(15, 2),
    COLL_SN             DECIMAL(10)
);

create unique index BEXTR2
    on BILL_EXTRAIT (TMSTAMP, CUST_ID, COLL_ACC_NUMBER, CR_ACC_NUMBER, PRODUCT_ID, BILL_SERIAL_NUM, TUN_TRX_DATE);

create unique index IXN_BILL_118
    on BILL_EXTRAIT (TUN_TRX_UNIT, TUN_TRX_DATE, TUN_TRX_USR, TUN_TRX_USR_SN);

create unique index IXU_BIL_100
    on BILL_EXTRAIT (TMSTAMP, BILL_SERIAL_NUM, CUST_ID);

