create table BLACK_ROCK_COMMERCIAL
(
    CORP_01              VARCHAR(100),
    CURR_TRX_DATE        DATE,
    CORP_02              VARCHAR(100),
    CORP_101             VARCHAR(100),
    CORP_102             VARCHAR(100),
    CORP_03              VARCHAR(100),
    LNS_ACCOUNT_NUMBER   CHAR(40),
    LNS_ACCOUNT_CD       SMALLINT,
    LNS_OPEN_UNIT        INTEGER,
    LNS_TYPE             SMALLINT,
    LNS_SN               INTEGER,
    CORP_103             VARCHAR(100),
    AGR_ACCOUNT_NUMBER   CHAR(40),
    AGR_ACCOUNT_CD       SMALLINT,
    AGR_UNIT             INTEGER,
    AGR_YEAR             SMALLINT,
    AGR_SN               INTEGER,
    AGR_MEMBERSHIP_SN    INTEGER,
    CORP_04              VARCHAR(100),
    CUST_ID              INTEGER,
    C_DIGIT              SMALLINT,
    FIRST_NAME           CHAR(20),
    SURNAME              CHAR(70),
    CUST_TYPE            CHAR(1),
    CORP_05              VARCHAR(100),
    GROUP_ID             INTEGER,
    GROUP_DESC           VARCHAR(40),
    CORP_06              VARCHAR(100),
    SURNAME6             CHAR(70),
    CORP_07              VARCHAR(100),
    FK_HAS_PROF_GH       CHAR(5),
    FK_HAS_PROF_GD       INTEGER,
    SHORT_DESC_PROF      CHAR(10),
    PROF_DESCRIPTION     VARCHAR(40),
    CORP_104             VARCHAR(100),
    FKGH_HAS_COUNTRY     CHAR(5),
    FKGD_HAS_COUNTRY     INTEGER,
    COUNTRY_SH_DESCR     CHAR(10),
    COUNTRY_DESCR        VARCHAR(40),
    CORP_08              VARCHAR(100),
    ZIP_CODE             CHAR(10),
    CORP_10              VARCHAR(100),
    FK_RATINGFK          CHAR(5),
    FK_RATINSER          INTEGER,
    RATING_SH_DESCR      CHAR(10),
    RATING_DESCR         VARCHAR(40),
    CORP_11              VARCHAR(100),
    CLASSIF_DATE         DATE,
    CORP_107             VARCHAR(100),
    CORP_109             VARCHAR(100),
    CORP_110             VARCHAR(100),
    CORP_111             VARCHAR(100),
    CORP_12              VARCHAR(100),
    CORP_16              VARCHAR(100),
    CORP_114             VARCHAR(100),
    CORP_115             VARCHAR(100),
    FKGH_HAS_AS_FINANC   CHAR(5),
    FKGD_HAS_AS_FINANC   INTEGER,
    FINANC_SH_DESCR      CHAR(10),
    FINANC_DESCR         VARCHAR(40),
    CORP_34              VARCHAR(100),
    ID_PRODUCT           INTEGER,
    PROD_DESCR           VARCHAR(100),
    CORP_17              VARCHAR(100),
    ACC_OPEN_DT          DATE,
    CORP_18              VARCHAR(100),
    FKGH_HAS_AS_LOAN_P   CHAR(5),
    FKGD_HAS_AS_LOAN_P   INTEGER,
    LOAN_P_SH_DESCR      CHAR(10),
    LOAN_P_DESCR         VARCHAR(40),
    CORP_19              VARCHAR(100),
    ACC_EXP_DT           DATE,
    CORP_20              VARCHAR(100),
    START_LIMIT_AMN      DECIMAL(15, 2),
    CORP_116             VARCHAR(100),
    GROUP_LIMIT_AMN      DECIMAL(15, 2),
    CORP_117             VARCHAR(100),
    CUST_LIMIT_AMN       DECIMAL(15, 2),
    CORP_21              VARCHAR(100),
    ACC_LIMIT_AMN        DECIMAL(15, 2),
    CORP_22              VARCHAR(100),
    BOOK_BALANCE_AMN     DECIMAL(15, 2),
    FIX_RATE             DECIMAL(12, 6),
    CORP_23              VARCHAR(100),
    CORP_24              VARCHAR(100),
    AVAILABLE_AMN        DECIMAL(15, 2),
    CORP_118             VARCHAR(100),
    OV_CAP_BAL           DECIMAL(15, 2),
    CORP_119             VARCHAR(100),
    OV_INT_BAL           DECIMAL(15, 2),
    CORP_120             VARCHAR(100),
    OV_EXP_BAL           DECIMAL(15, 2),
    CORP_25              VARCHAR(100),
    ID_CURRENCY          INTEGER,
    CURR_SHORT_DESCR     CHAR(5),
    CORP_26              VARCHAR(100),
    LOAN_MECHANISM       CHAR(1),
    CORP_27              VARCHAR(100),
    CORP_121             VARCHAR(100),
    START_INTEREST_ID    INTEGER,
    START_INT_PERCENTAGE DECIMAL(9, 6),
    CORP_28              VARCHAR(100),
    CURR_INTEREST_ID     INTEGER,
    CURR_INT_PERCENTAGE  DECIMAL(9, 6),
    CORP_29              VARCHAR(100),
    CORP_122             VARCHAR(100),
    SPR_EFFECTIVE_DT     DATE,
    DB_INT_RT_SPR        DECIMAL(8, 4),
    CORP_30              VARCHAR(100),
    CURR_EFFECTIVE_DT    DATE,
    CURR_DB_INT_RT_SPR   DECIMAL(8, 4),
    CORP_31              VARCHAR(100),
    DESC_BASE_RATE_IND   VARCHAR(40),
    DESC_BASE_RATE_GH    CHAR(5),
    DESC_BASE_RATE_GD    INTEGER,
    SH_DESC_BASE_RATE    CHAR(10),
    CORP_32              VARCHAR(100),
    CORP_33A             VARCHAR(100),
    RE_GD_SN1            INTEGER,
    REA_SELL_VALUE1      DECIMAL(15, 2),
    REAL_ESTATE_ID1      DECIMAL(10),
    CORP_33B             VARCHAR(100),
    RE_GD_SN2            INTEGER,
    REA_SELL_VALUE2      DECIMAL(15, 2),
    REAL_ESTATE_ID2      DECIMAL(10),
    CORP_33C             VARCHAR(100),
    RE_GD_SN3            INTEGER,
    REA_SELL_VALUE3      DECIMAL(15, 2),
    REAL_ESTATE_ID3      DECIMAL(10),
    RE_GD_SN             INTEGER,
    RE_GD_DESCR          CHAR(40),
    CORP_124             VARCHAR(100),
    CORP_14              VARCHAR(100),
    GUARANTOR_COUNT      INTEGER,
    CORP_15              VARCHAR(100),
    GUARANTEE_AMOUNT     DECIMAL(15, 2),
    CORP_37              VARCHAR(100),
    CORP_38              VARCHAR(100),
    CORP_125             VARCHAR(100),
    CORP_126             VARCHAR(100),
    COLLATERAL_CNT       INTEGER,
    CORP_39              VARCHAR(100),
    CORP_40              VARCHAR(100),
    CORP_127             VARCHAR(100),
    CORP_128             VARCHAR(100),
    CORP_129             VARCHAR(100),
    OV_DAYS              DECIMAL(10),
    OV_EXP_DT            DATE,
    CORP_42              VARCHAR(100),
    LOAN_STATUS          CHAR(1),
    CORP_43              VARCHAR(100),
    CORP_44              VARCHAR(100),
    CORP_45              VARCHAR(100),
    LNS_UPDATE_REASON    CHAR(1),
    DESC_UP_REAS         VARCHAR(40),
    DESC_UP_REAS_GH      CHAR(5),
    DESC_UP_REAS_GD      INTEGER,
    SH_DESC_UP_REAS      CHAR(10),
    CORP_46              VARCHAR(100),
    CORP_130             VARCHAR(100),
    CORP_47              VARCHAR(100),
    CORP_48              VARCHAR(100)
);

