create table BLK_FILE_DATA
(
    FILE_NAME              VARCHAR(50) not null,
    FILE_HASH              VARCHAR(50) not null,
    TEMPLATE_ID            INTEGER,
    ENTRY_STATUS           CHAR(1),
    LOAD_TRX_DATE          DATE,
    LOAD_TIMESTAMP         TIMESTAMP(6),
    FORECAST_STATUS        CHAR(1),
    FORECAST_RESULT        VARCHAR(80),
    PROCESS_RESULT         VARCHAR(80),
    PROCESS_TIMESTAMP      TIMESTAMP(6),
    GROUP_NUMBER           DECIMAL(10) not null,
    DATA_TYPE              VARCHAR(20),
    DATA_ROW_SN            INTEGER     not null,
    DATA_COLUMN_1          VARCHAR(100),
    DATA_COLUMN_2          VARCHAR(100),
    DATA_COLUMN_3          VARCHAR(100),
    DATA_COLUMN_4          VARCHAR(100),
    DATA_COLUMN_5          VARCHAR(100),
    DATA_COLUMN_6          VARCHAR(100),
    DATA_COLUMN_7          VARCHAR(100),
    DATA_COLUMN_8          VARCHAR(100),
    DATA_COLUMN_9          VARCHAR(100),
    DATA_COLUMN_10         VARCHAR(100),
    DATA_COLUMN_11         VARCHAR(100),
    DATA_COLUMN_12         VARCHAR(100),
    DATA_COLUMN_13         VARCHAR(100),
    DATA_COLUMN_14         VARCHAR(100),
    DATA_COLUMN_15         VARCHAR(100),
    DATA_COLUMN_16         VARCHAR(100),
    DATA_COLUMN_17         VARCHAR(100),
    DATA_COLUMN_18         VARCHAR(100),
    DATA_COLUMN_19         VARCHAR(100),
    DATA_COLUMN_20         VARCHAR(100),
    DATA_COLUMN_21         VARCHAR(100),
    DATA_COLUMN_22         VARCHAR(100),
    DATA_COLUMN_23         VARCHAR(100),
    DATA_COLUMN_24         VARCHAR(100),
    DATA_COLUMN_25         VARCHAR(100),
    DATA_COLUMN_26         VARCHAR(100),
    DATA_COLUMN_27         VARCHAR(100),
    DATA_COLUMN_28         VARCHAR(100),
    DATA_COLUMN_29         VARCHAR(100),
    DATA_COLUMN_30         VARCHAR(100),
    DATA_COLUMN_31         VARCHAR(100),
    DATA_COLUMN_32         VARCHAR(100),
    DATA_COLUMN_33         VARCHAR(100),
    DATA_COLUMN_34         VARCHAR(100),
    DATA_COLUMN_35         VARCHAR(100),
    DATA_COLUMN_36         VARCHAR(100),
    DATA_COLUMN_37         VARCHAR(100),
    DATA_COLUMN_38         VARCHAR(100),
    DATA_COLUMN_39         VARCHAR(100),
    DATA_COLUMN_40         VARCHAR(100),
    DATA_COLUMN_41         VARCHAR(100),
    DATA_COLUMN_42         VARCHAR(100),
    DATA_COLUMN_43         VARCHAR(100),
    DATA_COLUMN_44         VARCHAR(100),
    DATA_COLUMN_45         VARCHAR(100),
    DATA_COLUMN_46         VARCHAR(100),
    DATA_COLUMN_47         VARCHAR(100),
    DATA_COLUMN_48         VARCHAR(100),
    DATA_COLUMN_49         VARCHAR(100),
    DATA_COLUMN_50         VARCHAR(100),
    DATA_MECHANISM         VARCHAR(10),
    FORECAST_TIMESTAMP     TIMESTAMP(6),
    DATA_COLUMN_51         VARCHAR(100),
    DATA_COLUMN_52         VARCHAR(100),
    DATA_COLUMN_53         VARCHAR(100),
    DATA_COLUMN_54         VARCHAR(100),
    DATA_COLUMN_55         VARCHAR(100),
    DATA_COLUMN_56         VARCHAR(100),
    DATA_COLUMN_57         VARCHAR(100),
    DATA_COLUMN_58         VARCHAR(100),
    DATA_COLUMN_59         VARCHAR(100),
    DATA_COLUMN_60         VARCHAR(100),
    FLOW_STATUS            CHAR(1),
    REJECTION_REASON       VARCHAR(80),
    BY_PASS_FLG            CHAR(1),
    BY_PASS_USR            CHAR(8),
    CREDIT_REJECTED_STATUS CHAR(1) default '0',
    OLD_DATA_ROW_SN        INTEGER,
    constraint PK_BLK_FILE_DATA
        primary key (GROUP_NUMBER, FILE_NAME, FILE_HASH, DATA_ROW_SN)
);

create unique index INX_BLK_DATA_1
    on BLK_FILE_DATA (GROUP_NUMBER, FILE_NAME, FILE_HASH, DATA_ROW_SN, DATA_MECHANISM);

create unique index INX_BLK_DATA_2
    on BLK_FILE_DATA (FILE_HASH, DATA_ROW_SN, DATA_MECHANISM);

create unique index INX_BLK_DATA_3
    on BLK_FILE_DATA (FILE_HASH, DATA_ROW_SN);

create unique index INX_BLK_DATA_4
    on BLK_FILE_DATA (GROUP_NUMBER, ENTRY_STATUS, DATA_TYPE);

create unique index INX_BLK_DATA_777
    on BLK_FILE_DATA (FILE_HASH, DATA_TYPE, DATA_ROW_SN);

