create table BOP
(
    TRX_INTERNAL_SN    SMALLINT,
    TRX_USER           CHAR(8),
    TRX_UNIT           INTEGER,
    TRX_USR_SN         INTEGER,
    TRX_DATE           DATE,
    PRFT_SYSTEM        SMALLINT,
    BOPTR_SN           INTEGER,
    FK_TRANSACT        INTEGER,
    FK_JUSTIFIC        INTEGER,
    FK_PRODUCT         INTEGER,
    BOPBN_SN           INTEGER,
    CNTRY_SN           INTEGER,
    CUST_ID            INTEGER,
    TRX_AMOUNT         DECIMAL(15, 2),
    BOP_AMOUNT         DECIMAL(15, 2),
    REL_TRX_AMOUNT     DECIMAL(15, 2),
    EQUIVELANT         DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    REVERSED_FLG       CHAR(1),
    REVIEW_FLG         CHAR(1),
    PROCESS_FLG        CHAR(1),
    CR_DR              CHAR(2),
    REL_DB_CR          CHAR(2),
    SUBSYSTEM          CHAR(2),
    NON_RES_COUNTRY_ID CHAR(3),
    TRX_CURRENCY       CHAR(3),
    INDIVIDUAL         CHAR(4),
    CARD_IND           CHAR(5),
    REL_TRX_CAT        CHAR(5),
    BOPTR_PAR_TYPE     CHAR(5),
    BOPBN_PAR_TYPE     CHAR(5),
    TRX_CATEGORY       CHAR(5),
    CNTRY_PAR_TYPE     CHAR(5),
    CRGRP              CHAR(10),
    DRGRP              CHAR(10),
    BOPEC              CHAR(10),
    BOPFC              CHAR(10),
    BOPBC              CHAR(10),
    BOPSUB             CHAR(10),
    BOPCA              CHAR(10),
    CNTRY_ISO_CODE     CHAR(10),
    REL_CRGRP          CHAR(10),
    REL_DBGRP          CHAR(10),
    REL_BOPFC          CHAR(10),
    REL_BOPEC          CHAR(10),
    STATUTORY_TYPE     CHAR(10),
    ISIN_CODE          CHAR(15),
    NIMEXE             CHAR(20),
    REF_NO             CHAR(20),
    NORMAL_TUN         CHAR(25),
    LOAN_REF_NO        CHAR(30),
    CORPORATE_REG_NO   CHAR(30),
    CORPORATE_PHONE    CHAR(35),
    CORPORATE_ADDRESS  CHAR(70),
    CBG_TRX3           CHAR(100),
    CBG_TRX2           CHAR(100),
    CBG_TRX1           CHAR(100),
    COPRORATE_NAME     CHAR(150),
    STATUS             CHAR(1),
    SCR_TRG_FLG        CHAR(1),
    NOT_RESID_CUST     SMALLINT,
    FORCE_FLAG         SMALLINT,
    FORCE_FLAG_PTJ     SMALLINT,
    TRX_AMNT_DOM       DECIMAL(15, 2)
);

create unique index IXU_BOP_004
    on BOP (TRX_INTERNAL_SN, TRX_USER, TRX_UNIT, TRX_USR_SN, TRX_DATE);

