create table BOP_RELATION
(
    EXTRA_BOP        SMALLINT,
    SEC_TRX_INTER_SN SMALLINT,
    TRX_INTERNAL_SN  SMALLINT,
    TRX_UNIT         INTEGER,
    SEC_TRX_UNIT     INTEGER,
    SEC_TRX_USR_SN   INTEGER,
    TRX_USR_SN       INTEGER,
    TRX_DATE         DATE,
    SEC_TRX_DATE     DATE,
    SEC_TRX_USR      CHAR(8),
    TRX_USR          CHAR(8),
    SCR_TRG_FLG      CHAR(1)
);

create unique index IXP_BOP_000
    on BOP_RELATION (TRX_DATE, TRX_UNIT, TRX_USR, TRX_USR_SN, TRX_INTERNAL_SN, SEC_TRX_USR_SN, SEC_TRX_INTER_SN);

