create table BORDEREAU_HEADER
(
    TRX_UNIT        INTEGER,
    TRX_CODE        INTEGER,
    CURRENCY_ID     INTEGER,
    CLEARING_UNIT   INTEGER,
    ID_JUSTIFIC     INTEGER,
    TRX_USR_SN      INTEGER,
    TOTAL_ITEMS     INTEGER,
    BORDEREAU_NUM   DECIMAL(10),
    TOTAL_AMOUNT_DC DECIMAL(15, 2),
    TOTAL_AMOUNT_FC DECIMAL(15, 2),
    TRX_DATE        DATE,
    TRX_USR         CHAR(8),
    ENTRY_COMMENTS  CHAR(40)
);

create unique index IXU_BIL_121
    on BORDEREAU_HEADER (TRX_UNIT, TRX_DATE, TRX_USR, TRX_USR_SN);

