create table BOUNCED_FROM_INCOM
(
    ACCOUNT_NUMBER DECIMAL(11),
    CHEQUE_NUMBER  DECIMAL(10),
    CHEQUE_CD      SMALLINT,
    ACCOUNT_CD     SMALLINT,
    CHEQUE_AMOUNT  DECIMAL(15, 2),
    DEP_ON_US_FLAG CHAR(1)
);

create unique index IXU_BOU_000
    on BOUNCED_FROM_INCOM (ACCOUNT_NUMBER, CHEQUE_NUMBER);

