create table CARD_TOTAL
(
    AUTOKEY            DECIMAL(11) not null
        constraint PK_CRDPR
            primary key,
    CUST_ID            INTEGER,
    C_DIGIT            SMALLINT,
    FIO                CHAR(50)    not null,
    LATFIO             CHAR(50)    not null,
    DET_ID             INTEGER,
    DIZAIN             SMALLINT,
    ACCOUNT_NUM1       CHAR(40),
    ACCOUNT_NUM2       CHAR(40),
    ACCOUNT_NUM3       CHAR(40),
    ACCOUNT_NUM4       CHAR(40),
    ACCOUNT_NUM5       CHAR(50),
    VAL1               CHAR(3),
    VAL2               CHAR(3),
    VAL3               CHAR(3),
    VAL4               CHAR(4),
    VAL5               CHAR(5),
    PAN                CHAR(25),
    STATUS             SMALLINT    not null,
    OPTYPE             SMALLINT,
    PASNOM             CHAR(20)    not null,
    CARDPREFIX         CHAR(10),
    COMPANYCODE        INTEGER,
    FINPROF            SMALLINT,
    MAKEPRIOR          SMALLINT,
    ORDERTIME          DATE,
    CANCELDATE         SMALLINT,
    SEX                CHAR(1),
    BIRTHDAY           DATE,
    DGLIM              DECIMAL(10, 2),
    INN                CHAR(12),
    CURATOR            INTEGER     not null,
    REMAIN             DECIMAL(10, 2),
    ADDRESS            CHAR(80),
    PHONE              CHAR(15),
    JOBFONE            CHAR(15),
    EMAIL              CHAR(20),
    RESADDRESS         CHAR(80),
    REMARK             CHAR(80),
    CELLFONE           CHAR(15),
    DAM                CHAR(1),
    SABGAMCEM          CHAR(128),
    SABSER             CHAR(50),
    FIL                INTEGER,
    SC                 CHAR(3),
    CARD_NAME          INTEGER     not null,
    PRIORITY_TRAVELLER CHAR(1)     not null,
    PRIORITY_PASS      CHAR(1)     not null,
    RESERV1            CHAR(10),
    RESERV2            CHAR(10),
    RESERV3            CHAR(10),
    RESERV4            CHAR(10),
    RESERV5            CHAR(10),
    RESERV6            CHAR(10),
    RESERV7            CHAR(10),
    RESERV8            CHAR(10),
    RESERV9            CHAR(10),
    RESERV10           CHAR(10),
    TMSTP              TIME
);

