create table CAT_DETAIL_REL
(
    FK_CATEGORY_DETFK  CHAR(5),
    FK0CATEGORY_DETFK  INTEGER,
    FK1CATEGORY_DETFK  CHAR(8),
    SERIAL_NUM         SMALLINT,
    REL_FLAG           SMALLINT,
    REL_VALUE          INTEGER,
    FK_GENERIC_TABLSER INTEGER,
    REL_ID_NUM         DECIMAL(12),
    REL_AMOUNT         DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    FK_GENERIC_TABLFK  CHAR(5),
    REL_ID_DESC        CHAR(30),
    REL_COMMENTS       VARCHAR(40),
    REL_DESC           VARCHAR(50)
);

create unique index IXU_CAT_002
    on CAT_DETAIL_REL (FK_CATEGORY_DETFK, FK0CATEGORY_DETFK, FK1CATEGORY_DETFK, SERIAL_NUM);

