create table CAT_SPEC_AGREEMENT
(
    MIN_COMMISION_AMNT DECIMAL(15, 2),
    CHARGES_DISCOUNT   DECIMAL(8, 4),
    COMM_DISCOUNT      DECIMAL(8, 4),
    FK_JUSTIFICID_JUST INTEGER not null,
    FK_PRFT_TRANSACID  INTEGER not null,
    FK_PRODUCTID_PRODU INTEGER not null,
    FK_DFM_MECHANISID  INTEGER,
    constraint PKCATSPA
        primary key (FK_JUSTIFICID_JUST, FK_PRFT_TRANSACID, FK_PRODUCTID_PRODU)
);

