create table CATEGORY_DETAILS
(
    FK_GENERIC_TABLFK  CHAR(5),
    FK_GENERIC_TABLSER INTEGER,
    FK_CATEGORYCATEGOR CHAR(8),
    INDICATOR_FLAG     SMALLINT,
    MANDATORY_FLAG     SMALLINT,
    CASE_FLAG          SMALLINT,
    GENERIC_NUM        DECIMAL(15, 2),
    GENERIC_DATE       DATE,
    TMSTAMP            DATE,
    GENERIC_DESC       CHAR(80)
);

create unique index IXU_CAT_003
    on CATEGORY_DETAILS (FK_GENERIC_TABLFK, FK_GENERIC_TABLSER, FK_CATEGORYCATEGOR);

