create table CHEQUES_FOR_COLLE0
(
    FK_CHEQUES_FOR_IDE DECIMAL(13),
    FK_CHEQUES_FOR_ISS DATE,
    FK_CHEQUES_FOR_CHE VARCHAR(20),
    FK_CHEQUES_FOR_FK  INTEGER,
    OUR_CHARGES_AMOUNT DECIMAL(15, 2),
    PAYEE_ENDORSER_IND CHAR(1),
    PROCEEDS_INDICATOR CHAR(1),
    OUR_CHARGES_FLAG   CHAR(1),
    NON_PAYMENT_FLAG   CHAR(1),
    WAIVE_CHARGES_FLAG CHAR(1),
    TRACER_FLAG        CHAR(1),
    PROTEST_FLAG       CHAR(1),
    CHARGES_FLAG       CHAR(1),
    COLLECTION_ROUTE_I CHAR(1),
    COLLECTION_MAIL_ME CHAR(1),
    DRAWEE_BANK_CITY   CHAR(15),
    OBC_SERIAL_NUMBER  CHAR(18),
    PROCEEDS_ACCOUNT   CHAR(20),
    PROCEEDS_LOCATION  CHAR(40),
    DRAWEE_BANK_COUNTR CHAR(40),
    DRAWEE_BANK_ADDRE0 CHAR(40),
    DRAWEE_BANK_ADDRES CHAR(40),
    PAYEE_OR_ENDORSER  CHAR(40),
    DRAWERS_NAME       VARCHAR(40)
);

create unique index IXU_CHE_007
    on CHEQUES_FOR_COLLE0 (FK_CHEQUES_FOR_IDE, FK_CHEQUES_FOR_ISS, FK_CHEQUES_FOR_CHE, FK_CHEQUES_FOR_FK);

