create table CHEQUES_FOR_COLLEC
(
    IDENTIFIER          DECIMAL(13),
    FK_COLLABORATIOBAN  INTEGER,
    CHEQUE_NUMBER       VARCHAR(20),
    ISSUE_DATE          DATE,
    CUTOFF_SN           SMALLINT,
    IBAN_CD             SMALLINT,
    COLLATERAL_UNIT     SMALLINT,
    FK_UNITCODE         INTEGER,
    FK_JUSTIFICID_JUST  INTEGER,
    ACH_CLEARED_FLAG    INTEGER,
    ROUTING_CODE        INTEGER,
    FK_CURRENCYID_CURR  INTEGER,
    FK0UNITCODE         INTEGER,
    TARGET_CURRENCY     INTEGER,
    FK_PRODUCTID_PRODU  INTEGER,
    FK_CLEARING_AGEAGE  INTEGER,
    FK0CUSTOMERCUST_ID  INTEGER,
    FK_CUSTOMERCUST_ID  INTEGER,
    ACH_TRAN_CODE       INTEGER,
    BILL_SERIAL_NUM     DECIMAL(10),
    DISPATCH_NUMBER     DECIMAL(10),
    CFC_BILL_SERIAL_NUM DECIMAL(10),
    FK_DEPOSIT_ACCOACC  DECIMAL(11),
    CORRESP_ACC_GS      DECIMAL(11),
    RATE                DECIMAL(12, 6),
    BORDEREAU_NUM       DECIMAL(13),
    REFERENCE_NUMBERTO  DECIMAL(13),
    PURCHASE_NUMBER     DECIMAL(13),
    REFERENCE_NUMBER    DECIMAL(13),
    CHEQUE_AMOUNT_LC    DECIMAL(15, 2),
    CHEQUE_AMOUNT       DECIMAL(15, 2),
    RECEIPT_DATE        DATE,
    TMSTAMP             TIMESTAMP(6),
    CORR_SEND_DATE      DATE,
    CORR_PAYMENT_DATE   DATE,
    BEAR_PAYMENT_DATE   DATE,
    TRX_DATE            DATE,
    GS_SEND_DATE        DATE,
    BEAR_ID_ISSUE_DATE  DATE,
    CHEQUE_TYPE         CHAR(1),
    ACH_ENTRY_STATUS    CHAR(1),
    BILLS_CLEARING_FLG  CHAR(1),
    ENTRY_STATUS        CHAR(1),
    CORRESP_COLLECTION  CHAR(1),
    CODELINE_CD         CHAR(1),
    BEARER_ID_TYPE      CHAR(1),
    COLLECTION_FLAG     CHAR(1),
    IBAN_CNTRY          CHAR(2),
    TR_CODE             CHAR(2),
    SUBSYSTEM           CHAR(2),
    ACH_UNIT_CODE       CHAR(4),
    IBAN_DIGITS         CHAR(4),
    CHEQUE_ISSUE_PLACE  CHAR(6),
    FK_MODIFY_USR       CHAR(8),
    BEARER_ZIP_CODE     CHAR(10),
    FILE_NAME           CHAR(20),
    FK_GLG_ACCOUNTACCO  CHAR(21),
    CHEQUE_ACC_NUMBER   CHAR(23),
    BEARER_PHONE        VARCHAR(20),
    BEARER_TAX_REG_NO   VARCHAR(20),
    BEARER_ID_NUM       VARCHAR(20),
    CHEQUE_NUMBER_TO    VARCHAR(20),
    BEARER_CITY         VARCHAR(30),
    BEARER_ADDRESS2     VARCHAR(40),
    BEARER_NAME         VARCHAR(40),
    BEARER_ADDRESS1     VARCHAR(40),
    ENTRY_COMMENTS      VARCHAR(40),
    DRAWN_BANK          VARCHAR(40),
    BEAR_ID_ISSUE_AUTH  VARCHAR(40),
    CHEQUE_DRAWN_BY     VARCHAR(40),
    DHSSE_IBAN          CHAR(40),
    CORR_SEND_JUSTIFIC  INTEGER,
    PARTICIPATE_INFILE  CHAR(1),
    GS_BANK_CODE_SEND   INTEGER,
    BILLS_CLEARING_FLAG CHAR(1),
    CASH_LETTER_REF     CHAR(40),
    ORDER_NUMBER        INTEGER,
    FK_GH_BANK_COUNTRY  CHAR(5),
    FK_GD_BANK_COUNTRY  INTEGER
);

create unique index ICOM_BILL_MIGR_IND
    on CHEQUES_FOR_COLLEC (CHEQUE_TYPE, FK_CLEARING_AGEAGE, FK_CURRENCYID_CURR);

create unique index IXN_BIL_039
    on CHEQUES_FOR_COLLEC (CORR_SEND_DATE);

create unique index IXN_CHE_001
    on CHEQUES_FOR_COLLEC (BILL_SERIAL_NUM);

create unique index IXN_CHE_002
    on CHEQUES_FOR_COLLEC (BILLS_CLEARING_FLG, BILL_SERIAL_NUM);

create unique index IXN_CHE_003
    on CHEQUES_FOR_COLLEC (CHEQUE_NUMBER, CHEQUE_ACC_NUMBER, CHEQUE_AMOUNT, FK_COLLABORATIOBAN, COLLATERAL_UNIT);

create unique index IXN_GLG_009
    on CHEQUES_FOR_COLLEC (FK_CUSTOMERCUST_ID);

create unique index IXN_GLG_010
    on CHEQUES_FOR_COLLEC (FK0CUSTOMERCUST_ID);

create unique index IXU_CHE_005
    on CHEQUES_FOR_COLLEC (IDENTIFIER, FK_COLLABORATIOBAN, CHEQUE_NUMBER, ISSUE_DATE);

create unique index SEC_CFC_ORDER_NUM
    on CHEQUES_FOR_COLLEC (ORDER_NUMBER);

