create table CHEQUE_BOOK_ITEM
(
    ITEM_SERIAL_NUMBER DECIMAL(10),
    ACCOUNT_NUMBER     DECIMAL(11),
    CHEQUE_CD          SMALLINT,
    BOUNCED_CNT        SMALLINT,
    FK_CHEQUE_BOOKCARN INTEGER,
    BUYER_BANK         INTEGER,
    FK_CHEQUE_BOOKFK_D DECIMAL(11),
    CHEQUE_AMOUNT      DECIMAL(15, 2),
    TIMESTMP           TIMESTAMP(6),
    TRX_DATE           DATE,
    LAST_UPDATE_DATE   DATE,
    BOUNCED_DATE       DATE,
    DISHONOUR_DATE     DATE,
    ISSUE_DATE         DATE,
    STOPPED_TYPE       CHAR(1),
    DEP_ON_US_FLAG     CHAR(1),
    BOUNCED_REASON     CHAR(1),
    CHEQUE_STATUS      CHAR(1),
    STOP_PAYM_STATUS   CHAR(2),
    COMMENTS           VARCHAR(40),
    TRX_UNIT           INTEGER,
    ANNOUNCE_TOL_DAYS  SMALLINT,
    REJECTION_CODE     CHAR(2),
    TOT_COMM_AMOUNT    DECIMAL(15, 2),
    MANUFACTURER_SNUM  DECIMAL(15)
);

create unique index CSP_BATCH1
    on CHEQUE_BOOK_ITEM (ACCOUNT_NUMBER desc, ITEM_SERIAL_NUMBER desc);

create unique index IXN_BIL_106
    on CHEQUE_BOOK_ITEM (ACCOUNT_NUMBER);

create unique index IXN_CHE_004
    on CHEQUE_BOOK_ITEM (FK_CHEQUE_BOOKFK_D, FK_CHEQUE_BOOKCARN);

create unique index IXU_CHE_002
    on CHEQUE_BOOK_ITEM (ITEM_SERIAL_NUMBER, ACCOUNT_NUMBER);

