create table CHEQUE_BOOK
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    CARNET_SN          INTEGER,
    CHEQUE_CD          SMALLINT,
    ITEM_COUNT         SMALLINT,
    FST_CHEQUE_NUMBER  DECIMAL(10),
    LST_CHEQUE_NUMBER  DECIMAL(10),
    LAST_UPDATE_DATE   DATE,
    ISSUE_DATE         DATE,
    TIMESTMP           TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    COMMISSION_FLAG    CHAR(1)
);

create unique index IXU_CHE_010
    on CHEQUE_BOOK (FK_DEPOSIT_ACCOACC, CARNET_SN);

