create table CHQ_DEP_BOOK_ORDER
(
    ORDER_CREATION_DT  DATE,
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    ORDER_TYPE         CHAR(1),
    CHEQUE_CD          SMALLINT,
    BOOK_PAGES         SMALLINT,
    FK_GD_CHQ_ORDER    INTEGER,
    BOOKS_NUMBER       INTEGER,
    CHEQUE_FST_NUMBER  DECIMAL(10),
    TIMESTMP           TIMESTAMP(6),
    BOOK_DISPATCH_BY   CHAR(1),
    FIRST_TIME_ORDER   CHAR(1),
    BOOK_LEFT_HANDED   CHAR(1),
    FK_GH_CHQ_ORDER    CHAR(5),
    PRINTED_FLG        CHAR(1) default '0',
    CHEQUE_CD_2        SMALLINT,
    BANK_DRAFT_FLG     CHAR(1),
    PROCESS_STAGE      CHAR(1),
    ORDERING_UNIT      INTEGER,
    ISSUE_PRINT_DT     DATE,
    ATTACHED           CHAR(3),
    CHARGED            CHAR(3),
    COLLECTION_UNIT    INTEGER
);

create unique index IXU_CHQ_003
    on CHQ_DEP_BOOK_ORDER (ORDER_CREATION_DT, FK_DEPOSIT_ACCOACC, ORDER_TYPE);

