create table CHQBOOK_HIST
(
    ACCOUNT_NUMBER     DECIMAL(11),
    CARNET_SN          INTEGER,
    CHQBOOK_HIST_TIMES TIMESTAMP(6),
    CHEQUE_CD          SMALLINT,
    ITEM_COUNT         SMALLINT,
    TRX_UNIT           INTEGER,
    TRX_USR_SN         INTEGER,
    FST_CHEQUE_NUMBER  DECIMAL(10),
    LST_CHEQUE_NUMBER  DECIMAL(10),
    TIMESTMP           TIMESTAMP(6),
    TRX_DATE           DATE,
    LAST_UPDATE_DATE   DATE,
    ISSUE_DATE         DATE,
    ENTRY_STATUS       CHAR(1),
    CHQBOOK_HIST_TYPE  CHAR(1),
    ACCOUNT_STATUS     CHAR(1),
    COMMISSION_FLAG    CHAR(1),
    TRX_USR            CHAR(8)
);

create unique index IXU_CHQ_002
    on CHQBOOK_HIST (ACCOUNT_NUMBER, CARNET_SN, CHQBOOK_HIST_TIMES);

