create table CHQBOOK_ITEM_HIST
(
    ACCOUNT_NUMBER     DECIMAL(11),
    ITEM_SERIAL_NUMBER DECIMAL(10),
    CHQBOOK_HIST_TIMES TIMESTAMP(6),
    CHEQUE_CD          SMALLINT,
    BOUNCED_CNT        SMALLINT,
    CARNET_SN          INTEGER,
    CHEQUE_AMOUNT      DECIMAL(15, 2),
    ISSUE_DATE         DATE,
    TRX_DATE           DATE,
    TIMESTMP           TIMESTAMP(6),
    DEP_ON_US_FLAG     CHAR(1),
    CHEQUE_STATUS      CHAR(1),
    STOPPED_TYPE       CHAR(1),
    BOUNCED_REASON     CHAR(1)
);

create unique index IXU_CHQ_001
    on CHQBOOK_ITEM_HIST (ACCOUNT_NUMBER, ITEM_SERIAL_NUMBER, CHQBOOK_HIST_TIMES);

