create table CIE_AGGR_CUST_CHANNEL
(
    FK_PROFILE    SMALLINT,
    SEQ_ORDER_NBR SMALLINT,
    FK_CUSTOMER   INTEGER,
    FK_AGREEMENT  DECIMAL(10),
    NICKNAME      CHAR(16),
    PREFF_FLD_4   VARCHAR(256),
    PREFF_FLD_2   VARCHAR(256),
    PREFF_FLD_1   VARCHAR(256),
    PREFF_FLD_3   VARCHAR(256)
);

