create table CLASSIFICATION_H_U
(
    FK3GENERIC_DETASER INTEGER,
    FK3GENERIC_DETAFK  CHAR(5),
    FK1GENERIC_DETASER INTEGER,
    FK1GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_CUSTOMERCUST_ID INTEGER not null,
    CLASSIF_DATE       DATE    not null,
    SCORING_VALUE      DECIMAL(15),
    NEXT_CLASSIF_DATE  DATE,
    CLASSIF_COMMENTS   VARCHAR(255),
    COMPANY_HISTORY    SMALLINT,
    COMPANY_IMAGE      SMALLINT,
    CLASS_OF_EXCHANGE  SMALLINT,
    COMPETING_POSITION SMALLINT,
    COMPANY_RESULTS    SMALLINT,
    COMPANY_MANAGEMENT SMALLINT,
    COMPANY_BALANSHEET SMALLINT,
    COMPANY_STABILITY  SMALLINT,
    COMPANY_CASH_FLOW  SMALLINT,
    TMSTAMP            TIMESTAMP(6),
    CLASSIF_TRANS_DATE DATE,
    SERIAL_NUM         SMALLINT,
    CLASSIFICATION     CHAR(2),
    FK0GENERIC_DETAFK  CHAR(5),
    FK0GENERIC_DETASER INTEGER,
    FK2GENERIC_DETAFK  CHAR(5),
    FK2GENERIC_DETASER INTEGER
);

create unique index IXU_CIU_007
    on CLASSIFICATION_H_U (SERIAL_NUM, FK_CUSTOMERCUST_ID);

