create table CLASS_GL
(
    FK_CUST_CATEG_GD   INTEGER,
    FK_CUST_CATEG_GH   CHAR(5),
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    LOAN_STATUS        CHAR(1),
    FK_CODE_N1_GD      INTEGER,
    TIMESTMP           TIMESTAMP(6),
    TMSTAMP            TIMESTAMP(6),
    DR_INT_NOTAX_GLLVL CHAR(1),
    DR_INT_GL_ACC_LVL  CHAR(1),
    CR_INT_GL_ACC_LVL  CHAR(1),
    DR_INT_ACCR_GL_LVL CHAR(1),
    CR_INT_ACCR_GL_LVL CHAR(1),
    GL_NETWORK_LVL     CHAR(1),
    GL_ACCRUAL_LVL     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    DR_CNTR_GL_ACC_LVL CHAR(1),
    CR_CNTR_GL_ACC_LVL CHAR(1),
    CR_INT_NOTAX_GLLVL CHAR(1),
    FK_CODE_N1_GH      CHAR(5),
    DR_INT_NOTAX_GLACC CHAR(21),
    CR_INT_GL_ACC      CHAR(21),
    CR_INT_ACCR_GL_ACC CHAR(21),
    DR_INT_GL_ACC      CHAR(21),
    DR_INT_ACCR_GL_ACC CHAR(21),
    GL_NETWORK_ACC     CHAR(21),
    GL_ACCRUAL_ACC     CHAR(21),
    CR_INT_NOTAX_GLACC CHAR(21),
    CR_CNTR_GL_ACC     CHAR(21),
    DR_CNTR_GL_ACC     CHAR(21)
);

create unique index IXU_CLA_000
    on CLASS_GL (FK_CUST_CATEG_GD, FK_CUST_CATEG_GH, FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_PRODUCTID_PRODU,
                 LOAN_STATUS);

