create table CLC_AGENT
(
    AGENT_ID           DECIMAL(10) not null,
    AGENT_DESCRIPTION  CHAR(80),
    AGENT_TYPE         CHAR(1),
    AGENT_CUST_ID      INTEGER,
    AGENT_USER_CODE    CHAR(8),
    AGENT_CONTACT      VARCHAR(4000),
    AGENT_SERVICES     VARCHAR(4000),
    AGENT_ASSIGNMENTS  VARCHAR(4000),
    EVALUATION_DT      DATE,
    EVALUATION_NEXT_DT DATE,
    TOT_CASES_OPEN     DECIMAL(15),
    TOT_CASES_CLOSED   DECIMAL(15),
    TOT_CASES          DECIMAL(15),
    CREATE_UNIT        INTEGER,
    CREATE_DATE        DATE,
    CREATE_USER        CHAR(8),
    CREATE_TMSTAMP     TIMESTAMP(6),
    UPDATE_UNIT        INTEGER,
    UPDATE_DATE        DATE,
    UPDATE_USER        CHAR(8),
    UPDATE_TMSTAMP     TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    FK_AGENCY          DECIMAL(10) not null,
    constraint CLC_COLLECT_PK_3
        primary key (FK_AGENCY, AGENT_ID)
);

