create table CLC_COVERAGES
(
    CASE_ID               CHAR(40) not null,
    CLC_COVERAGE_SN       INTEGER  not null,
    COVERAGE_TYPE_DESC    VARCHAR(40),
    CUST_ID               INTEGER,
    CUST_CD               SMALLINT,
    RECORD_DESCR          CHAR(40),
    RECORD_DETAILS        VARCHAR(4000),
    HAS_AGENCY_LINK       CHAR(1),
    HAS_ALLOCATION        CHAR(1),
    HAS_ACCOUNT           CHAR(1),
    HAS_AGREEMENT         CHAR(1),
    HAS_OTHER_CASE        CHAR(1),
    HAS_VAULT             CHAR(1),
    COL_MECHANISM         SMALLINT,
    COL_KEY_PRODUCT       INTEGER,
    COL_KEY_UNIT          INTEGER,
    COL_KEY_COLLATERAL_SN DECIMAL(10),
    COL_TABLE_TYPE        CHAR(2),
    COL_TABLE_SN          DECIMAL(10),
    COL_SHIP_ID           DECIMAL(10),
    COL_REAL_ESTATE_ID    DECIMAL(10),
    COL_EST_VALUE_AMN     DECIMAL(18, 2),
    COL_CURRENCY          INTEGER,
    COL_REGISTRY_AMN      DECIMAL(18, 2),
    COL_REGISTRY_CURR     INTEGER,
    CREATE_UNIT           INTEGER,
    CREATE_DATE           DATE,
    CREATE_USER           CHAR(8),
    CREATE_TMSTAMP        TIMESTAMP(6),
    UPDATE_UNIT           INTEGER,
    UPDATE_DATE           DATE,
    UPDATE_USER           CHAR(8),
    UPDATE_TMSTAMP        TIMESTAMP(6),
    VAULT_ITEM_SN         DECIMAL(12),
    HAS_REVALUATION       CHAR(1),
    HAS_CASE_ASSIGN       CHAR(1),
    constraint CLC_COLLECT_PK_70
        primary key (CASE_ID, CLC_COVERAGE_SN)
);

