create table CLC_PRODUCT
(
    ID_PRODUCT        INTEGER not null
        constraint CLC_COLLECT_PK_1
            primary key,
    ACCOUNT_BAL_FROM  DECIMAL(18, 2),
    ACCOUNT_BAL_TO    DECIMAL(18, 2),
    OVERDUE_BAL_FROM  DECIMAL(18, 2),
    OVERDUE_BAL_TO    DECIMAL(18, 2),
    OVERDUE_DAYS_FROM DECIMAL(10),
    OVERDUE_DAYS_TO   DECIMAL(10),
    LOAN_STATUS_FROM  CHAR(1),
    LOAN_STATUS_TO    CHAR(1),
    ACC_CLASS_FROM    CHAR(5),
    ACC_CLASS_TO      CHAR(5),
    ACC_SUBCLASS_FROM CHAR(5),
    ACC_SUBCLASS_TO   CHAR(5),
    TOT_CASES_CREATE  DECIMAL(15),
    TOT_CASES_REMOVE  DECIMAL(15),
    CREATE_UNIT       INTEGER,
    CREATE_DATE       DATE,
    CREATE_USER       CHAR(8),
    CREATE_TMSTAMP    TIMESTAMP(6),
    UPDATE_UNIT       INTEGER,
    UPDATE_DATE       DATE,
    UPDATE_USER       CHAR(8),
    UPDATE_TMSTAMP    TIMESTAMP(6),
    AUTO_CASE         CHAR(1),
    WORKFLOW_ID       DECIMAL(10),
    PRODUCT_ID        INTEGER
);

