create table CLC_BLOCK_AMOUNT
(
    CASE_ID         CHAR(40) not null,
    CLC_BLOCK_SN    INTEGER  not null,
    PRFT_SYSTEM     SMALLINT,
    PRFT_ACC_NUMBER CHAR(40),
    PRFT_ACC_CD     SMALLINT,
    CUST_ID         INTEGER,
    CUST_CD         SMALLINT,
    DEP_ACC_NUMBER  DECIMAL(11),
    BLOCK_UNIT      INTEGER,
    BLOCK_DATE      DATE,
    BLOCK_USR       CHAR(8),
    BLOCK_USR_SN    INTEGER,
    BLOCK_AMN       DECIMAL(18, 2),
    BLOCK_DEP_CNT   DECIMAL(10),
    BLOCK_CURRENCY  INTEGER,
    CREATE_UNIT     INTEGER,
    CREATE_DATE     DATE,
    CREATE_USER     CHAR(8),
    CREATE_TMSTAMP  TIMESTAMP(6),
    UPDATE_UNIT     INTEGER,
    UPDATE_DATE     DATE,
    UPDATE_USER     CHAR(8),
    UPDATE_TMSTAMP  TIMESTAMP(6),
    BLOCK_COMMENTS  VARCHAR(80),
    BLOCK_STATUS    CHAR(1),
    constraint CLC_COLLECT_PK_9
        primary key (CASE_ID, CLC_BLOCK_SN)
);

