create table CMS_MERCH_DTL
(
    FILE_TRANS_CODE    CHAR(3),
    FILE_SN            INTEGER not null,
    FILE_LINE          INTEGER not null,
    LOAD_DATE          DATE    not null,
    REC_SN             INTEGER not null,
    REC_TYPE           CHAR(2),
    ENTRY_STATUS       CHAR(1) not null,
    ERROR_DESCR        CHAR(150),
    TMSTAMP            TIMESTAMP(6),
    TRANS_DATE         DATE,
    VALUE_DATE         DATE,
    REASON             CHAR(20),
    REJ_CODE           CHAR(2),
    SUB_CODE           CHAR(2),
    BRANCH_CONTRACT    CHAR(4),
    MONETARY_ADJ_FLG   CHAR(2),
    IBAN               CHAR(32),
    INSURANCE_ID       CHAR(3),
    SOURCE_CODE        CHAR(1),
    CLEAR_AMNT         DECIMAL(15, 2),
    CURR_CODE          CHAR(3),
    CHARGE_AMOUNT      DECIMAL(15, 2),
    CRED_DEB_IND       CHAR(1),
    BANK_ACCNT         CHAR(15),
    PREPAYM_IND        CHAR(2),
    PREPAYM_MONTH_AMNT DECIMAL(15, 2),
    PREPAYM_REST_AMNT  DECIMAL(15, 2),
    SOURCE_TYPE        CHAR(2),
    BATCH_TRANSM_DATE  DATE,
    MERCH_CODE         CHAR(9),
    MERCH_INSTALLMENTS CHAR(4),
    MERCH_TERMINAL     CHAR(4),
    EXT_BATCH_NO       CHAR(5),
    COMPLETE_LINE      CHAR(200),
    REPLY_DATE         DATE,
    REPLY_TMSTAMP      TIMESTAMP(6),
    constraint CMS_MERCH_DTL
        primary key (FILE_SN, FILE_LINE)
);

