create table CMS_EXTERNAL_CARD
(
    CUST_ID               INTEGER  not null,
    CARD_SN               INTEGER  not null,
    ACCOUNT_NUMBER        CHAR(40) not null,
    CARD_NUMBER           CHAR(20) not null,
    ACCOUNT_CD            SMALLINT,
    C_DIGIT               SMALLINT,
    CARD_STATUS           CHAR(2),
    LAST_FIVE_CARD_DIGITS CHAR(5),
    EXP_DATE              CHAR(4),
    NEW_EXP_DATE          CHAR(4),
    PIN_POSITION_1        SMALLINT,
    PIN_POSITION_2        SMALLINT,
    PIN_POSITION_3        SMALLINT,
    PIN_POSITION_4        SMALLINT,
    PIN_BLOCK             CHAR(16),
    BIN_NUMBER            CHAR(6),
    OTP_CODE              CHAR(8),
    CARD_BATCH_TYPE       CHAR(1),
    CORTEX_CARD_STATUS    CHAR(2),
    LAST_TRX_USR          CHAR(8),
    LAST_TRX_UNIT         INTEGER,
    LAST_TRX_SN           INTEGER,
    LAST_TRX_DATE         DATE,
    LAST_TMSTAMP          TIMESTAMP(6),
    LAST_TRX_INTERNAL_SN  SMALLINT,
    SDI_CUST_ACTION       CHAR(1),
    SDI_ACCNT_ACTION      CHAR(1),
    SDI_CARD_ACTION       CHAR(1),
    SDI_CUST_SENT_FLG     CHAR(1),
    SDI_ACCNT_SENT_FLG    CHAR(1),
    SDI_CARD_SENT_FLG     CHAR(1),
    SDI_CARD_SENT_DT      DATE,
    SDI_CUST_SENT_DT      DATE,
    SDI_ACCNT_SENT_DT     DATE,
    SDI_CARD_SENT_TMSTP   TIMESTAMP(6),
    SDI_CUST_SENT_TMSTP   TIMESTAMP(6),
    SDI_ACCNT_SENT_TMSTP  TIMESTAMP(6),
    EMBOSSING_NAME        VARCHAR(51),
    primary key (ACCOUNT_NUMBER, CARD_SN, CUST_ID)
);

