create table CMS_STOCK_ORDER
(
    CARD_ORDER_ID      DECIMAL(10) not null
        constraint PK_CMS_STOCK_ORDER
            primary key,
    NUM_CARDS_ORDERED  INTEGER,
    CREATED_UNIT       INTEGER,
    CREATED_USER       CHAR(8),
    CREATED_DATE       DATE,
    CREATED_TIMESTAMP  TIMESTAMP(6),
    LAST_ISS_AUTH_USER CHAR(8),
    UPDATE_UNIT        INTEGER,
    UPDATE_USER        CHAR(8),
    UPDATE_TIMESTAMP   TIMESTAMP(6),
    LAST_UPD_AUTH_USER CHAR(8),
    ORDER_STATUS       CHAR(1),
    NUM_CARDS_RECIEVED INTEGER,
    CONFIRMED_UNIT     INTEGER,
    CONFIRMED_USER     CHAR(8),
    CONFIRMED_DATE     DATE,
    CONFIRM_TIMESTAMP  TIMESTAMP(6),
    FK_GH_CARTP        CHAR(5),
    FK_GD_CARTP        INTEGER,
    RECEIVE_FILENAME   CHAR(80),
    ORDER_FILENAME     CHAR(80),
    SENT_DATE          DATE,
    SENT_TIMESTAMP     TIMESTAMP(6),
    RECEIVE_DATE       DATE,
    RECEIVE_TIMESTAMP  TIMESTAMP(6)
);

create unique index I0001105
    on CMS_STOCK_ORDER (FK_GH_CARTP, FK_GD_CARTP);

