create table CMS_RECONCILIATION_PROCESS
(
    INTERNAL_SN                   DECIMAL(10) not null
        constraint PK_CSM_RECON_PR
            primary key,
    PAN                           CHAR(16),
    FIID                          CHAR(6),
    TERMINAL_ID                   CHAR(8),
    REASON_CODE                   CHAR(4),
    BANK_ACCOUNT                  CHAR(30),
    ORIGINAL_MESSAGE_TYPE         CHAR(5),
    MESSAGE_TYPE                  CHAR(4),
    PROCESSING_CODE               CHAR(6),
    BILLING_CURRENCY              SMALLINT,
    BILLING_CURRENCY_DECIMALS     SMALLINT,
    BILLING_AMOUNT                DECIMAL(16),
    AMOUNT_INDICATOR              CHAR(2),
    POSTING_DATE                  DATE,
    TRANSACTION_DATE              DATE,
    TRANSACTION_CURRENCY          SMALLINT,
    TRANSACTION_CURRENCY_DECIMALS SMALLINT,
    TRANSACTION_AMOUNT            DECIMAL(16) not null,
    CLEARING_CURRENCY             SMALLINT,
    CLEARING_CURRENCY_DECIMALS    SMALLINT,
    CLEARING_AMOUNT               DECIMAL(16),
    RATE                          INTEGER,
    MESSAGE_DESCRIPTION           CHAR(60),
    TERMINAL_LOCATION             CHAR(60),
    COUNTRY                       CHAR(3),
    MCC                           CHAR(4),
    APPROVAL                      CHAR(6),
    ARN                           CHAR(23),
    RELATION                      CHAR(8),
    BANK_REFERENCE                CHAR(30),
    UNIQUE_IDENTIFIER             CHAR(20),
    ENTRY_CODE                    CHAR(50),
    CLIENT_ID                     CHAR(20),
    EXTERNAL_CLIENT_CODE          CHAR(20),
    CONTRACT_NUMBER               CHAR(30),
    CARD_BRANCH                   CHAR(3),
    ACCOUNT_BRANCH                CHAR(3),
    INTERNAL_ACCOUNT_NUMBER       CHAR(30),
    WEB_MOTO_IDENTIFIER           CHAR(4),
    RRN                           CHAR(12),
    STAN                          CHAR(6),
    CPD                           DATE,
    ACQUIRER_ID                   CHAR(6),
    EXTERNAL_STAN                 CHAR(6),
    RESERVED                      CHAR(9),
    RECONCILIATION_STATUS         CHAR(1),
    ERROR_MESSAGE                 CHAR(100),
    PROCESS_TMSTAMP               TIMESTAMP(6),
    LOADING_TMSTAMP               TIMESTAMP(6),
    CARD_TYPE                     CHAR(6),
    PROCESS_DATE                  DATE,
    COMPLETE_LINE                 VARCHAR(1000),
    BILLING_AMN_DEC               DECIMAL(15, 2),
    CLEARING_AMN_DEC              DECIMAL(15, 2)
);

