create table CNM74734_CR_DEB
(
    ACC_CODE           INTEGER  not null,
    BSECT              INTEGER  not null,
    ACC_OFF            CHAR(8)  not null,
    CUST_CAT           INTEGER  not null,
    PRODUCT_ID         INTEGER  not null,
    CUST_ID            INTEGER  not null,
    AGR_YEAR           SMALLINT not null,
    AGR_SN             INTEGER  not null,
    AGR_MEM_SN         INTEGER  not null,
    ACC_TYPE           SMALLINT not null,
    ACC_SN             INTEGER  not null,
    LNS_PROFITS_ACC_CD SMALLINT,
    AGR_PROFITS_ACC_CD SMALLINT,
    ACC_CD             SMALLINT,
    TOT_REQ            SMALLINT,
    REQ_AMN            DECIMAL(15, 2),
    OV_ACC_BAL         DECIMAL(15, 2),
    NRM_ACC_BAL        DECIMAL(15, 2),
    DP_AVAIL_BAL       DECIMAL(15, 2),
    DP_BLOCKED         DECIMAL(15, 2),
    DP_UNCLEAR         DECIMAL(15, 2),
    ACCOUNT_BAL        DECIMAL(15, 2),
    DP_TOLER           DECIMAL(15, 2),
    DP_TMP_BAL         DECIMAL(15, 2),
    ACC_AVAIL_BAL      DECIMAL(15, 2),
    AGR_AVAIL_LIMIT    DECIMAL(15, 2),
    AGR_UTIL_LMT       DECIMAL(15, 2),
    AGR_LIMIT          DECIMAL(15, 2),
    ACC_LIMIT          DECIMAL(15, 2),
    DP_EXP_TMP         DATE,
    LNS_PROFITS_ACC    CHAR(40),
    AGR_PROFITS_ACC    CHAR(40),
    constraint IXU_REP_163
        primary key (ACC_CODE, BSECT, ACC_OFF, CUST_CAT, PRODUCT_ID, CUST_ID, AGR_YEAR, AGR_SN, AGR_MEM_SN, ACC_TYPE,
                     ACC_SN)
);

