create table COL_LIMITS_HISTORY
(
    ACCOUNT_NUMBER   CHAR(40),
    PRFT_SYSTEM      SMALLINT,
    ID_CURRENCY      INTEGER,
    HISTORY_SN       DECIMAL(10),
    FROM_PRFT_SYS    SMALLINT,
    TRX_INTERNAL_SN  SMALLINT,
    TRX_CODE         INTEGER,
    TRX_UNIT         INTEGER,
    TRX_SN           INTEGER,
    NO_LIQ_UTIL      DECIMAL(15, 2),
    LIQ_LIMIT        DECIMAL(15, 2),
    LIQ_UTIL         DECIMAL(15, 2),
    NO_LIQ_LIMIT     DECIMAL(15, 2),
    TRX_DATE         DATE,
    TMSTAMP          TIMESTAMP(6),
    TRX_USR          CHAR(8),
    FROM_ACNT_NUMBER CHAR(40)
);

create unique index IXU_COL_029
    on COL_LIMITS_HISTORY (ACCOUNT_NUMBER, PRFT_SYSTEM, ID_CURRENCY, HISTORY_SN);

