create table COLLATERAL_LIMITS
(
    ACCOUNT_NUMBER CHAR(40),
    PRFT_SYSTEM    SMALLINT,
    ID_CURRENCY    INTEGER,
    HISTORY_CNT    DECIMAL(10),
    NO_LIQ_UTIL    DECIMAL(15, 2),
    NO_LIQ_LIMIT   DECIMAL(15, 2),
    LIQ_LIMIT      DECIMAL(15, 2),
    LIQ_UTIL       DECIMAL(15, 2),
    INTRACOM_FLG   CHAR(1)
);

create unique index IXU_COL_010
    on COLLATERAL_LIMITS (ACCOUNT_NUMBER, PRFT_SYSTEM, ID_CURRENCY);

