create table COLLTOTTEMP
(
    COL_MONTH          SMALLINT,
    PRFT_SYSTEM        SMALLINT,
    ACC_CD             SMALLINT,
    ACC_TYPE           SMALLINT,
    COL_YEAR           SMALLINT,
    CURRENCY           INTEGER,
    COLLATERAL_TYPE    INTEGER,
    COL_UNIT           INTEGER,
    ACC_UNIT           INTEGER,
    ACC_SN             INTEGER,
    ESTIMATED_INSUR_DB DECIMAL(15, 2),
    ESTIMATED_INSUR_CR DECIMAL(15, 2),
    CB_INSURANCE_DB    DECIMAL(15, 2),
    YIELD_UTILISED_AMN DECIMAL(15, 2),
    YIELD_LIMIT_AMN    DECIMAL(15, 2),
    ESTIMATED_VALUE_CR DECIMAL(15, 2),
    CB_INSURANCE_CR    DECIMAL(15, 2),
    ESTIMATED_VALUE_DB DECIMAL(15, 2),
    PRFT_ACCOUNT       CHAR(40)
);

