create table COLL_BAD_CHEQUES
(
    TMSTAMP            TIMESTAMP(6) not null,
    CHEQUES_CNTR       DECIMAL(15)  not null,
    COLLATERAL_SN      DECIMAL(10)  not null,
    ACC_UNIT           SMALLINT     not null,
    ACC_TYPE           SMALLINT     not null,
    ACC_SN             DECIMAL(15)  not null,
    PROFITS_SYSTEM     INTEGER      not null,
    ACCOUNT_CUST_ID    INTEGER,
    INSERTION_DT       DATE,
    ACC_CD             SMALLINT,
    CR_ACC_UNIT        SMALLINT,
    CR_ACC_TYPE        SMALLINT,
    CR_ACC_SN          DECIMAL(15),
    CR_ACC_CD          SMALLINT,
    CR_PRFT_SYSTEM     INTEGER,
    CHEQ_NUMBER        CHAR(20),
    CHEQ_ACCOUNT_NUM   CHAR(23),
    CHEQ_ACCOUNT_UNIT  SMALLINT,
    CHEQ_IBAN_ACC      CHAR(37),
    CHEQ_LACK_STS      CHAR(1)      not null,
    CHEQ_DHSSE_IND     CHAR(1),
    CHEQ_BANK_CODE     INTEGER,
    CHEQUE_TYPE        CHAR(1),
    IBAN_DIGITS        CHAR(4),
    EST_VALUE_AMN      DECIMAL(15, 2),
    EXPIRE_DATE        DATE,
    ENTRY_STS          CHAR(1),
    DRAWN_BANK         VARCHAR(40),
    ID_JUSTIFIC        INTEGER,
    FK_COLL_ISSUERISSU INTEGER      not null,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK_UNITCODE        INTEGER,
    COMMENT0           CHAR(40),
    OLD_ACC_UNIT       SMALLINT,
    OLD_ACC_TYPE       SMALLINT,
    OLD_ACC_SN         DECIMAL(15),
    OLD_ACC_CD         SMALLINT,
    OLD_CR_ACC_UNIT    SMALLINT,
    OLD_CR_ACC_TYPE    SMALLINT,
    OLD_CR_ACC_SN      DECIMAL(15),
    OLD_CR_ACC_CD      SMALLINT,
    TRX_UNIT           SMALLINT,
    constraint I0010740
        primary key (FK_COLL_ISSUERISSU, TMSTAMP, CHEQUES_CNTR, COLLATERAL_SN, ACC_UNIT, ACC_TYPE, ACC_SN,
                     PROFITS_SYSTEM)
);

