create table COLL_TYPES_VALUERS
(
    FK_COLLAT_TAB_SN DECIMAL(10),
    FK_RECORD_TYPE   CHAR(2),
    FK_VALUER_ID     INTEGER,
    ENTRY_STATUS     CHAR(1)
);

create unique index IXU_COL_042
    on COLL_TYPES_VALUERS (FK_COLLAT_TAB_SN, FK_RECORD_TYPE, FK_VALUER_ID);

