create table COLLATERAL_TBL_DTL
(
    HDR_INTERNAL_SN   DECIMAL(10) not null,
    HDR_RECORD_TYPE   CHAR(2)     not null,
    DTL_RECORD_TYPE   CHAR(2)     not null,
    DTL_SERIAL_NUMBER DECIMAL(10) not null,
    PROFITS_ACCOUNT_1 CHAR(40),
    ACCOUNT_CD_1      SMALLINT,
    PRFT_SYSTEM_1     SMALLINT,
    PROFITS_ACCOUNT_2 CHAR(40),
    ACCOUNT_CD_2      SMALLINT,
    PRFT_SYSTEM_2     SMALLINT,
    CUST_ID_1         INTEGER,
    C_DIGIT_1         SMALLINT,
    CUST_ID_2         INTEGER,
    C_DIGIT_2         SMALLINT,
    CURRENCY_ID_1     INTEGER,
    CURRENCY_ID_2     INTEGER,
    CURRENCY_ID_3     INTEGER,
    DATE_1            DATE,
    DATE_2            DATE,
    DATE_3            DATE,
    DATE_4            DATE,
    DATE_5            DATE,
    DATE_6            DATE,
    DATE_7            DATE,
    DATE_8            DATE,
    DATE_9            DATE,
    DATE_10           DATE,
    AMOUNT_1          DECIMAL(15, 2),
    AMOUNT_2          DECIMAL(15, 2),
    AMOUNT_3          DECIMAL(15, 2),
    AMOUNT_4          DECIMAL(15, 2),
    AMOUNT_5          DECIMAL(15, 2),
    AMOUNT_6          DECIMAL(15, 2),
    AMOUNT_7          DECIMAL(15, 2),
    AMOUNT_8          DECIMAL(15, 2),
    AMOUNT_9          DECIMAL(15, 2),
    AMOUNT_10         DECIMAL(15, 2),
    AMOUNT_18_4_1     DECIMAL(18, 4),
    AMOUNT_18_4_2     DECIMAL(18, 4),
    AMOUNT_18_4_3     DECIMAL(18, 4),
    NUMBER_1          DECIMAL(10),
    NUMBER_2          DECIMAL(10),
    NUMBER_3          DECIMAL(10),
    NUMBER_4          DECIMAL(11),
    NUMBER_5          DECIMAL(10),
    NUMBER_6          DECIMAL(10),
    NUMBER_7          DECIMAL(10),
    NUMBER_8          DECIMAL(10),
    NUMBER_9          DECIMAL(10),
    NUMBER_10         DECIMAL(10),
    DESCR_1           CHAR(40),
    DESCR_2           CHAR(40),
    DESCR_3           CHAR(40),
    DESCR_4           CHAR(40),
    DESCR_5           CHAR(40),
    DESCR_6           CHAR(40),
    DESCR_7           CHAR(40),
    DESCR_8           CHAR(40),
    DESCR_9           CHAR(40),
    DESCR_10          CHAR(40),
    DESCR_11          CHAR(40),
    DESCR_12          CHAR(40),
    DESCR_13          CHAR(40),
    DESCR_14          CHAR(40),
    DESCR_15          CHAR(40),
    DESCR_16          CHAR(40),
    DESCR_17          CHAR(40),
    DESCR_18          CHAR(40),
    DESCR_19          CHAR(40),
    DESCR_20          CHAR(40),
    FLAG_1            CHAR(1),
    FLAG_2            CHAR(1),
    FLAG_3            CHAR(1),
    FLAG_4            CHAR(1),
    FLAG_5            CHAR(1),
    FLAG_6            CHAR(1),
    FLAG_7            CHAR(1),
    FLAG_8            CHAR(1),
    FLAG_9            CHAR(1),
    FLAG_10           CHAR(1),
    GD_PAR_TYPE_1     CHAR(5),
    GD_SERIAL_NUM_1   INTEGER,
    GD_PAR_TYPE_2     CHAR(5),
    GD_SERIAL_NUM_2   INTEGER,
    GD_PAR_TYPE_3     CHAR(5),
    GD_SERIAL_NUM_3   INTEGER,
    GD_PAR_TYPE_4     CHAR(5),
    GD_SERIAL_NUM_4   INTEGER,
    GD_PAR_TYPE_5     CHAR(5),
    GD_SERIAL_NUM_5   INTEGER,
    GD_PAR_TYPE_6     CHAR(5),
    GD_SERIAL_NUM_6   INTEGER,
    LARGE_DESCR_1     CHAR(254),
    LAGRE_DESCR_2     CHAR(254),
    LARGE_DESCR_3     CHAR(254),
    INSERT_UNIT       INTEGER,
    INSERT_USR        CHAR(8),
    INSERT_DATE       DATE,
    INSERT_TIMESTAMP  TIMESTAMP(6),
    UPDATE_UNIT       INTEGER,
    UPDATE_USR        CHAR(8),
    UPDATE_DATE       DATE,
    UPDATE_TIMESTAMP  TIMESTAMP(6),
    ENTRY_COMMENTS    VARCHAR(255),
    ENTRY_STATUS      CHAR(1),
    RECORD_LAST       CHAR(1),
    AMOUNT_1_DOM      DECIMAL(15, 2),
    constraint PK_CTBLDETAIL
        primary key (DTL_SERIAL_NUMBER, DTL_RECORD_TYPE, HDR_RECORD_TYPE, HDR_INTERNAL_SN)
);

