create table COLL_TYPE_LIMIT
(
    FK_GENERIC_DETAFK  CHAR(5) not null,
    FK_GENERIC_DETASER INTEGER not null,
    FK_COLLABORATIOBAN INTEGER not null,
    AGREEMENT_LIMIT    DECIMAL(15, 2),
    UTILISED_LIMIT     DECIMAL(15, 2),
    MATURITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    constraint IXU_PRD_003
        primary key (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_COLLABORATIOBAN)
);

