create table COLLATERAL_REQUIRED
(
    COL_PRODUCT_ID INTEGER,
    PRFT_SYSTEM    SMALLINT,
    ACCOUNT_NUMBER CHAR(40),
    CUST_ID        INTEGER,
    ACC_TYPE       SMALLINT,
    ACCOUNT_CD     SMALLINT,
    ACC_UNIT       INTEGER,
    INSERTION_UNIT INTEGER,
    UPDATE_UNIT    INTEGER,
    COL_PERCENTAGE DECIMAL(8, 4),
    ACC_SN         DECIMAL(11),
    COL_AMOUNT     DECIMAL(15, 2),
    INSERTION_DT   DATE,
    UPDATE_DT      DATE,
    TMSTAMP        TIMESTAMP(6),
    INSERTION_USER CHAR(8),
    UPDATE_USER    CHAR(8)
);

create unique index IXU_COL_007
    on COLLATERAL_REQUIRED (COL_PRODUCT_ID, PRFT_SYSTEM, ACCOUNT_NUMBER, CUST_ID);

