create table COLLATERAL_TRANS
(
    TRANSACTION_DATE   DATE    not null,
    FK_UNITCODE        INTEGER not null,
    FK_USRCODE         CHAR(8) not null,
    TRANS_SER_NUM      INTEGER not null,
    FK_JUSTIFICID_JUST INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK_TRANSACTION0ID  INTEGER,
    ELEMENTS_COUNT     INTEGER,
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    FSV                DECIMAL(15, 2),
    AMOUNT             DECIMAL(15, 2),
    PRODUCTION_DATE    DATE,
    EXPIRATION_DATE    DATE,
    TRANSACTION_TYPE   CHAR(1),
    TRANSACTION_ORIGIN CHAR(1),
    ISSUE_BANK_NUMBER  CHAR(4),
    LIST_NUMBER        CHAR(6),
    REGISTRATION_NUM   CHAR(10),
    CHEQUE_BODY_NUMBER CHAR(10),
    CHEQUE_ACC_NUM     CHAR(15),
    COMMENTS_1         CHAR(80),
    ENTRY_COMMENTS     CHAR(80),
    constraint IXU_LNS_049
        primary key (TRANSACTION_DATE, FK_UNITCODE, FK_USRCODE, TRANS_SER_NUM)
);

