create table COLLATERAL_AUCTION
(
    COLL_AUCTION_SN    SMALLINT    not null,
    FK_COLLATERALFK_UN INTEGER     not null,
    FK_COLLATERALFK_CO INTEGER     not null,
    FK_COLLATERALCOLLA DECIMAL(10) not null,
    constraint PKCOLLAU
        primary key (FK_COLLATERALFK_UN, FK_COLLATERALFK_CO, FK_COLLATERALCOLLA, COLL_AUCTION_SN)
);

