create table COM_SCALE
(
    FK_COMMISSIONID_CO INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    VALIDITY_DATE      DATE,
    SCALE_ID           SMALLINT,
    PERCENTAGE         DECIMAL(8, 4),
    RESULT_AMOUNT      DECIMAL(15, 2),
    TO_AMOUNT          DECIMAL(15, 2),
    FROM_AMOUNT        DECIMAL(15, 2),
    COMMISSION         DECIMAL(15, 2),
    MIN_COMMISSION     DECIMAL(15, 2),
    MAX_COMMISSION     DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    SP_AGR_FLG         CHAR(1)
);

create unique index IXU_COM_006
    on COM_SCALE (FK_COMMISSIONID_CO, FK_CURRENCYID_CURR, VALIDITY_DATE, SCALE_ID);

