create table COMPOSITE_TRX
(
    FK0JUSTIFICID_JUST INTEGER,
    FK0TRANSACTION0ID  INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    FK_TRANSACTION0ID  INTEGER,
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    TMSTAMP            TIMESTAMP(6),
    DR_CR_FLAG         CHAR(1)
);

create unique index IXU_COM_003
    on COMPOSITE_TRX (FK0JUSTIFICID_JUST, FK0TRANSACTION0ID, FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_JUSTIFICID_JUST,
                      FK_PRODUCTID_PRODU, FK_TRANSACTION0ID);

