create table CORRESP_EXTRAIT
(
    ENTRY_SER_NUM     SMALLINT    not null,
    TRANS_SER_NUM     DECIMAL(10) not null,
    ACCOUNT_NUMBER    DECIMAL(11) not null,
    TRX_DATE          DATE        not null,
    PARTICIP_BAL_FLAG SMALLINT,
    ACCOUNT_PRODUCT   INTEGER,
    ACCOUNT_CURRENCY  INTEGER,
    ACCOUNT_UNIT      INTEGER,
    TRX_UNIT          INTEGER,
    ID_JUSTIFIC       INTEGER,
    ID_TRANSACT       INTEGER,
    CUSTOMER_NUMBER   INTEGER,
    FK_STATEMENT_SN   INTEGER,
    TRX_SN            INTEGER,
    EXPECTED_REF      DECIMAL(10),
    PREV_ACC_BALANCE  DECIMAL(15, 2),
    ENTRY_AMOUNT      DECIMAL(15, 2),
    AVAILABILITY_DATE DATE,
    ENTRY_DATE        DATE,
    VALUE_DATE        DATE,
    TRANSFERED_FLG    CHAR(1),
    REVERSE_FLAG      CHAR(1),
    EQUALITY_IND      CHAR(2),
    PROCESSED_FLAG    CHAR(1),
    POST_FLAG         CHAR(1),
    DEBIT_CREDIT_FLAG CHAR(2),
    TRX_USR           CHAR(8),
    FK_SWIFT_PRFT_NO  CHAR(16),
    REFERENCE_CODE    CHAR(16),
    ENTRY_COMMENTS    CHAR(40),
    ID_CODE           CHAR(4),
    SWIFT_ADDRESS     VARCHAR(12),
    INST_REFERENCE    CHAR(18),
    FUNDS_TYPE        CHAR(20),
    SETTLEMNT_COMM    CHAR(40),
    SETTLEMNT_INFO    CHAR(40),
    REC_MANUALLY      CHAR(1),
    IN_REFERENCE      CHAR(40),
    REFERENCE_CODE_2  CHAR(16),
    REFERENCE_CODE_3  CHAR(16),
    REFERENCE_CODE_4  CHAR(16),
    REFERENCE_CODE_5  CHAR(16),
    REF_PROCESSED     CHAR(1),
    CONFIGURE_REF     CHAR(1),
    PRFT_REF_NO       CHAR(16),
    constraint IXU_REP_042
        primary key (ENTRY_SER_NUM, TRANS_SER_NUM, ACCOUNT_NUMBER, TRX_DATE)
);

create unique index CORR_EXTR_RECON_SEC
    on CORRESP_EXTRAIT (ACCOUNT_NUMBER, TRX_DATE, EXPECTED_REF, CUSTOMER_NUMBER);

create unique index CORR_INSTREF_RECON_SEC
    on CORRESP_EXTRAIT (ACCOUNT_NUMBER, INST_REFERENCE, DEBIT_CREDIT_FLAG, TRX_DATE);

