create table CORRESP_CRITERIA_D
(
    CRITERIA_SN        INTEGER not null,
    CHARGES_TYPE       CHAR(1),
    AMOUNT_TO          DECIMAL(15, 2),
    ENTRY_STATUS       CHAR(1) not null,
    ENTRY_COMMENTS     CHAR(40),
    TWO_PARTY_CODE     CHAR(35),
    TMSTAMP            TIMESTAMP(6),
    FK_CORRESP_CRGHEAD CHAR(5) not null,
    FK_CORRESP_CRGDETA INTEGER not null,
    FK_CORRESP_CRVALUE DATE    not null,
    FK_CURRENCYID_CURR INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_COLLABORATIOBAN INTEGER,
    FK_COMMISSIONID_CO INTEGER,
    FK_CORRESP_BANK    INTEGER,
    FK_USRCODE         CHAR(8),
    constraint PK_CORRESP_CRITERIA
        primary key (FK_CORRESP_CRGHEAD, FK_CORRESP_CRGDETA, FK_CORRESP_CRVALUE, CRITERIA_SN)
);

create unique index I0000252B
    on CORRESP_CRITERIA_D (FK_CORRESP_BANK);

create unique index I0000254
    on CORRESP_CRITERIA_D (FK_COLLABORATIOBAN);

create unique index I0000256
    on CORRESP_CRITERIA_D (FK_CURRENCYID_CURR);

create unique index I0000258
    on CORRESP_CRITERIA_D (FK_GENERIC_DETAFK, FK_GENERIC_DETASER);

create unique index I0000260
    on CORRESP_CRITERIA_D (FK_COMMISSIONID_CO);

