create table CORR_BANK_RELATION
(
    FK_CURRENCYID_CURR INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_OTHER_BANKDISCR CHAR(15),
    FK_OTHER_BANKFK_G1 INTEGER,
    FK_OTHER_BANKFK_GE CHAR(5),
    TMSTAMP            TIMESTAMP(6)
);

create unique index IXU_COR_005
    on CORR_BANK_RELATION (FK_CURRENCYID_CURR, FK_CUSTOMERCUST_ID, FK_OTHER_BANKDISCR, FK_OTHER_BANKFK_G1,
                           FK_OTHER_BANKFK_GE);

