create table COS_MEMBER_HIST
(
    MEMBER_ID          DECIMAL(10)  not null,
    TMSTAMP            TIMESTAMP(6) not null,
    TRX_DATE           DATE,
    USER_CODE          CHAR(8),
    PREV_ENTRY_STATUS  CHAR(1),
    CURR_ENTRY_STATUS  CHAR(1),
    PREV_INSURANCE_FEE DECIMAL(15, 2),
    CURR_INSURANCE_FEE DECIMAL(15, 2),
    PREV_FUNERAL_FEE   DECIMAL(15, 2),
    CURR_FUNERAL_FEE   DECIMAL(15, 2),
    PREV_CAPITAL_FEE   DECIMAL(15, 2),
    CURR_CAPITAL_AMNT  DECIMAL(15, 2),
    PREV_SAYE_AMNT     DECIMAL(15, 2),
    CURR_SAYE_AMOUNT   DECIMAL(15, 2),
    PREV_BL_AMNT       DECIMAL(15, 2),
    CURR_BL_AMOUNT     DECIMAL(15, 2),
    PREV_MEMBER_STATUS SMALLINT,
    CURR_MEMBER_STATUS SMALLINT,
    PREV_SUB_FLAG      SMALLINT,
    CURR_SUB_FLAG      SMALLINT,
    BLOCKED_REASON     VARCHAR(40),
    constraint PK_MEMB_HIST
        primary key (MEMBER_ID, TMSTAMP)
);

