create table COS_APPLICATIONS
(
    APPLICATION_ID        DECIMAL(11),
    BLOCKED_TYPE          SMALLINT,
    APPL_TYPE             SMALLINT,
    APPL_STATUS           SMALLINT,
    JUSTIFIC_ID           INTEGER,
    SEC_JUSTIFIC_ID       INTEGER,
    SERVICE_PRODUCT       INTEGER,
    CUSTOMER_ID           INTEGER,
    SEC_CUST_ID           INTEGER,
    MEMBER_ID             DECIMAL(10),
    APPL_SHARE_PRICE      DECIMAL(10, 2),
    SEC_MEMBER_ID         DECIMAL(10),
    BLOCK_APPL_ID         DECIMAL(11),
    APPL_AMOUNT           DECIMAL(15, 2),
    EXPENSE_AMOUNT        DECIMAL(15, 2),
    COMMISSION_AMOUNT     DECIMAL(15, 2),
    NUMBER_OF_SHARES      DECIMAL(15),
    ACQ_BLK_USED_AMNT     DECIMAL(15, 2),
    ACQ_BLOCKED_AMNT      DECIMAL(15, 2),
    EXPIRATION_DATE       DATE,
    ACTIVATION_DATE       DATE,
    COMPLETION_DATE       DATE,
    CREATION_DATE         DATE,
    CREATED_DATE          DATE,
    UPDATED_DATE          DATE,
    UPDATED_TIMESTAMP     TIMESTAMP(6),
    SELECTION_TYPE        CHAR(1),
    CREATED_BY            CHAR(8),
    UPDATED_BY            CHAR(8),
    ACCOUNT_NUMBER        CHAR(40),
    SEC_ACCOUNT_NO        CHAR(40),
    COMMENTS              VARCHAR(255),
    CAPITAL_INCREASE_FLAG CHAR(1)
);

create unique index IXU_COS_016
    on COS_APPLICATIONS (APPLICATION_ID);

