create table CP_AGREEMENT_FILE
(
    ORGANIZ_FILENAME   CHAR(20),
    FK_FILE_FORMAT_REJ SMALLINT,
    FK_REFERTO_CP_FILE SMALLINT,
    FK_CP_COMFILE_FORM SMALLINT,
    FK_REPLY_FFILE_NUM INTEGER,
    FK_COMMITM_FF_NUM  INTEGER,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    FK_COMMITM_FF_TYPE CHAR(5),
    FK_REPLY_FFILETYPE CHAR(5)
);

create unique index IXU_CP__035
    on CP_AGREEMENT_FILE (ORGANIZ_FILENAME);

