create table CP_DD_INPHD_INTER
(
    CP_AGREEMENT_NO    DECIMAL(10),
    SOURCE_REPLY_FLAG  CHAR(1),
    DIAS_PRODUCT_CODE  CHAR(5),
    COMMITMENT_TYPE    CHAR(1),
    EXPIRY_DATE        DATE,
    TRANSACTION_TYPE   CHAR(1),
    BANK_CODE          SMALLINT,
    TOTAL_DTL_RECORDS  DECIMAL(13),
    TOTAL_RETURN_AMNT  DECIMAL(13, 2),
    TOTAL_PAYMENT_AMNT DECIMAL(13, 2),
    SETTLEMENT_DATE    DATE,
    RECEIVED_DATE      DATE,
    TIMESTMP           DATE,
    HD_STATUS          CHAR(1),
    PROCESSING_TYPE    CHAR(1),
    ORGANIZATION_CODE  CHAR(5),
    CURRENCY_DESCR     CHAR(5),
    INPUT_FILE_ID      CHAR(20),
    ORGANIZ_FILENAME   CHAR(20)
);

create unique index IXU_CP__040
    on CP_DD_INPHD_INTER (CP_AGREEMENT_NO, SOURCE_REPLY_FLAG, DIAS_PRODUCT_CODE, COMMITMENT_TYPE, EXPIRY_DATE,
                          TRANSACTION_TYPE);

