create table CP_DD_INPDTL_INTER
(
    FK_CPDDINPHD_AGRNO DECIMAL(10),
    FK_CPDDINPHD_SOURP CHAR(1),
    FK_CPDDINPHD_PRDCD CHAR(5),
    FK_CPDDINPHD_COMTY CHAR(1),
    FK_CPDDINPHD_EXPDT DATE,
    FK_CPDDINPHD_TRXTP CHAR(1),
    INTERNAL_SN        INTEGER,
    DAY_OF_PAYMENT     SMALLINT,
    REJECTION_CODE     SMALLINT,
    FREQ_OF_PAYMENT    SMALLINT,
    ACCOUNT_UNIT       INTEGER,
    DIAS_REFEREN_CODE  DECIMAL(14),
    MAXIM_DEBIT_AMOUNT DECIMAL(15, 2),
    PAYMENT_AMOUNT     DECIMAL(15, 2),
    RETURNED_AMOUNT    DECIMAL(15, 2),
    TIMESTMP           DATE,
    PAYMENT_DATE       DATE,
    LAST_PAYMENT_DATE  DATE,
    ISSUE_DATE         DATE,
    CANCELLATION_DATE  DATE,
    DTL_STATUS         CHAR(1),
    TRANSACTION_ID     CHAR(18),
    KEY_FIELD_1        CHAR(30),
    KEY_FIELD_2        CHAR(30),
    KEY_FIELD_3        CHAR(30),
    KEY_FIELD_4        CHAR(30),
    NEW_KEY_FIELD_2    CHAR(30),
    NEW_KEY_FIELD_3    CHAR(30),
    NEW_KEY_FIELD_4    CHAR(30),
    NEW_KEY_FIELD_1    CHAR(30),
    ERROR_DESCRIPTION  VARCHAR(40),
    ADDITIONAL_DATA    VARCHAR(70)
);

create unique index IXU_CP__039
    on CP_DD_INPDTL_INTER (FK_CPDDINPHD_AGRNO, FK_CPDDINPHD_SOURP, FK_CPDDINPHD_PRDCD, FK_CPDDINPHD_COMTY,
                           FK_CPDDINPHD_EXPDT, FK_CPDDINPHD_TRXTP, INTERNAL_SN);

