create table CP_FILE_FORMAT
(
    FILE_ID            SMALLINT,
    AMOUNT_DECIMALS    SMALLINT,
    TMSTAMP            TIMESTAMP(6),
    CHECK_ACCNT_NO_CD  CHAR(1),
    NO_CHECK_TRAIL_TOT CHAR(1),
    ENTRY_STATUS       CHAR(1),
    DATE_FORMAT        CHAR(1),
    PROCESSING_TYPE    CHAR(1),
    SUBGROUP_HEADER_ID CHAR(5),
    SUBGROUP_TRAILERID CHAR(5),
    FILE_TRAILER_ID    CHAR(5),
    GROUP_TRAILER_ID   CHAR(5),
    DETAIL_ID          CHAR(5),
    GROUP_HEADER_ID    CHAR(5),
    FILE_HEADER_ID     CHAR(5),
    FILE_DESCRIPTION   VARCHAR(40)
);

create unique index IXU_CP__042
    on CP_FILE_FORMAT (FILE_ID);

