create table CP_FILE_RECORDS
(
    ORGANIZATION_CODE CHAR(5),
    CP_AGREEMENT_NO   DECIMAL(10),
    EXPIRY_DATE       DATE,
    PAYMENT_TYPE      CHAR(2),
    RECORD_TYPE       CHAR(1),
    PAYM_PERIOD       CHAR(6),
    INTERNAL_SN       DECIMAL(13),
    FILE_RECORD       VARCHAR(1000)
);

create unique index IXU_CP__043
    on CP_FILE_RECORDS (ORGANIZATION_CODE, CP_AGREEMENT_NO, EXPIRY_DATE, PAYMENT_TYPE, RECORD_TYPE, PAYM_PERIOD,
                        INTERNAL_SN);

