create table CP_INPUT_COL_INTER
(
    ORIG_ACCESS_METHOD CHAR(1),
    ORIG_REF_NO        CHAR(30),
    HD_YY_REF          SMALLINT,
    TRX_UNIT           INTEGER,
    CP_AGREEMENT_NO    DECIMAL(10),
    CUST_OL_COMMISSION DECIMAL(15, 2),
    CUST_OL_EXPENSE    DECIMAL(15, 2),
    CUST_OL_COM_TAX    DECIMAL(15, 2),
    CUST_OL_EXP_TAX    DECIMAL(15, 2),
    CALC_OL_COMMISSION DECIMAL(15, 2),
    CALC_OL_EXPENCE    DECIMAL(15, 2),
    CALC_OL_EXP_TAX    DECIMAL(15, 2),
    CALC_OL_COM_TAX    DECIMAL(15, 2),
    COLLECTION_AMOUNT  DECIMAL(15, 2),
    PROCESS_DATE       DATE,
    COLLECTION_DATE    DATE,
    RECEIPT_DATE       DATE,
    BEN_PASSPORT_TYPE  CHAR(1),
    I_ACCESS_METHOD    CHAR(1),
    DOCUMENT_CODE      CHAR(2),
    CURR_SHORT_DESC    CHAR(5),
    TRX_USR            CHAR(8),
    BENEF_ZIP_CODE     CHAR(10),
    BENEF_PASSPORT     CHAR(10),
    HD_UN_REF          CHAR(11),
    BENEF_CITY         CHAR(15),
    BENEF_TELEPHONE    CHAR(15),
    ACTION_ENTRY_DESC  CHAR(20),
    DATA_FIELD_1       CHAR(30),
    I_REF_NO           CHAR(30),
    BENEF_NAME         CHAR(40),
    BENEF_ADDRESS1     CHAR(40),
    BENEF_COUNTRY      CHAR(40),
    BENEF_ADDRESS2     CHAR(40),
    ERROR_DESCRIPTION  CHAR(80)
);

create unique index IXU_CP__046
    on CP_INPUT_COL_INTER (ORIG_ACCESS_METHOD, ORIG_REF_NO);

