create table CP_INPUT_HD_INTER
(
    CP_AGREEMENT_NO    DECIMAL(10),
    EXPIRY_DATE        DATE,
    PAYMENT_TYPE       CHAR(2),
    PAYM_PERIOD        CHAR(6) default '000000',
    BANK_CODE          SMALLINT,
    CURRENCY_ID        INTEGER,
    COMMISSION_PCG     DECIMAL(8, 4),
    COMMISSION_TAX_PCG DECIMAL(8, 4),
    TOTAL_DTL_RECORDS  DECIMAL(13),
    MIN_COMMISSION     DECIMAL(15, 2),
    TOTAL_AMOUNT       DECIMAL(15, 2),
    MAX_COMMISSION     DECIMAL(15, 2),
    TIMESTMP           TIMESTAMP(6),
    RECEIVED_DATE      DATE,
    ONLINE_EXPIRY_DATE DATE,
    STARTING_DATE      DATE,
    HD_STATUS          CHAR(1),
    CHECK_ACCNT_NO_CD  CHAR(1),
    PROCESSING_TYPE    CHAR(1),
    FILE_SN            CHAR(12),
    ORGANIZ_FILENAME   CHAR(20),
    SETTLM_VALEUR_DATE DATE,
    TOT_COMMISS_AMNT   DECIMAL(15, 2)
);

create unique index IXU_CP__048
    on CP_INPUT_HD_INTER (CP_AGREEMENT_NO, EXPIRY_DATE, PAYMENT_TYPE, PAYM_PERIOD);

