create table CP_INPUT_DTL_INTER
(
    FK_INCL_CPAGRRNO   DECIMAL(10),
    FK_INCL_CPEXPIRDT  DATE,
    FK_INCL_CPPAYMTYPE CHAR(2),
    FK_PAYM_PERIOD     CHAR(6) default '000000',
    INTERNAL_SN        DECIMAL(13),
    ACCOUNT_CD         SMALLINT,
    ACCOUNT_UNIT_NO    INTEGER,
    ACCOUNT_NO         DECIMAL(11),
    COM_AMOUNT         DECIMAL(15, 2),
    INTEREST_AMOUNT    DECIMAL(15, 2),
    AMOUNT             DECIMAL(15, 2),
    TOTAL_AMOUNT       DECIMAL(15, 2),
    INVOICE_EXP_DT     DATE,
    TIMESTMP           TIMESTAMP(6),
    VALEUR_DATE        DATE,
    DTL_STATUS         CHAR(1),
    ASSIGN_RECALL_FLAG CHAR(1),
    ERROR_CODE         CHAR(2),
    ORGANIZATION_CODE  CHAR(5),
    IBAN               CHAR(27),
    OLD_KEY_FIELD_4    CHAR(80),
    KEY_FIELD_4        CHAR(80),
    KEY_FIELD_3        CHAR(80),
    OLD_KEY_FIELD_2    CHAR(80),
    KEY_FIELD_1        CHAR(80),
    KEY_FIELD_2        CHAR(80),
    OLD_KEY_FIELD_3    CHAR(80),
    OLD_KEY_FIELD_1    CHAR(80),
    ENTRY_COMMENTS     CHAR(40),
    ERROR_DESCRIPTION  VARCHAR(40),
    PROFITS_ACC_NO     CHAR(40),
    PROFITS_ACC_CD     SMALLINT,
    EXTRA_COMMENTS     VARCHAR(500)
);

create unique index IXU_CP__047
    on CP_INPUT_DTL_INTER (FK_INCL_CPAGRRNO, FK_INCL_CPEXPIRDT, FK_INCL_CPPAYMTYPE, FK_PAYM_PERIOD, INTERNAL_SN);

