create table CP_KRA_COLLECTION_DATA
(
    CP_AGREEMENT_NO     DECIMAL(10) not null,
    DIAS_REFERENCE_NO   DECIMAL(15) not null,
    SYSTEM_CODE         CHAR(2),
    BRANCH_CODE         INTEGER,
    TELLER_ID           VARCHAR(8),
    TELLER_NAME         VARCHAR(100),
    MEANS_OF_PAYMENT    CHAR(1),
    REMITTER_ID         VARCHAR(50),
    REMITTER_NAME       VARCHAR(100),
    ESLIP_NUMBER        VARCHAR(30),
    PAYMENT_ADVICE_DATE VARCHAR(20),
    PAYMENT_REFERENCE   VARCHAR(50),
    TAX_PAYER_PIN       VARCHAR(30),
    TAX_PAYER_FULLNAME  VARCHAR(100),
    TOTAL_AMOUNT        VARCHAR(20),
    COLLECTION_DATE     DATE,
    CURRENCY_DESCR      VARCHAR(3),
    CASH_AMOUNT         DECIMAL(15, 2),
    HASHCODE            VARCHAR(100),
    TIMESTMP            TIMESTAMP(6),
    constraint PK_CP_KRA_DATA
        primary key (DIAS_REFERENCE_NO, CP_AGREEMENT_NO)
);

