create table CP_OL_HD_HIST_COLL
(
    CP_AGREEMENT_NO    DECIMAL(10),
    EXPIRY_DATE        DATE,
    PAYMENT_TYPE       CHAR(2),
    TOTAL_RECS         DECIMAL(13),
    TOTAL_CR_RECS      DECIMAL(13),
    TOTAL_DR_RECS      DECIMAL(13),
    ORG_ITEM_CHARG_TAX DECIMAL(15, 2),
    ORG_ITEM_CHARGE    DECIMAL(15, 2),
    ORG_RET_CHARGE_TAX DECIMAL(15, 2),
    ORG_RET_CHARGE     DECIMAL(15, 2),
    CUST_OL_CHARGE_TAX DECIMAL(15, 2),
    CUST_OL_CHARGE     DECIMAL(15, 2),
    ORG_OL_CHARGE_TAX  DECIMAL(15, 2),
    TOTAL_ORG_AMNT     DECIMAL(15, 2),
    TOTAL_CUST_AMNT    DECIMAL(15, 2),
    ORG_OL_CHARGE      DECIMAL(15, 2),
    TOTAL_CR_AMNT      DECIMAL(15, 2),
    TOTAL_DR_AMNT      DECIMAL(15, 2),
    TOTAL_RETURN_AMOUN DECIMAL(15, 2),
    AGRM_BAL_AFTER_RET DECIMAL(15, 2),
    AGRM_INIT_BALANCE  DECIMAL(15, 2),
    RETURN_TRX_DATE    DATE,
    TRANSFERRED_DATE   DATE,
    TIMESTMP           TIMESTAMP(6),
    COLLECT_DATE_FROM  DATE,
    COLLECT_DATE_TO    DATE,
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_CP__052
    on CP_OL_HD_HIST_COLL (CP_AGREEMENT_NO, EXPIRY_DATE, PAYMENT_TYPE);

