create table CP_ONLINE_FIS
(
    ID                   DECIMAL(15) not null,
    CREDITOR_AGENT_BIC   CHAR(11),
    SETTLEMENT_DATE      DATE        not null,
    REMITTANCE_INFO      CHAR(140),
    CREDITOR_ID          CHAR(5)     not null,
    CREDITOR_IBAN        CHAR(34),
    ONLINE_BATCH         CHAR(1),
    NET_POSITION_AMOUNT  DECIMAL(15, 2),
    NUMBER_CRED_ONUS     DECIMAL(8),
    AMOUNT_CRED_ONUS     DECIMAL(15, 2),
    NUMBER_RPOS_ONUS     DECIMAL(8),
    AMOUNT_RPOS_ONUS     DECIMAL(15, 2),
    NUMBER_CRED_NOT_ONUS DECIMAL(8),
    AMOUNT_CRED_NOT_ONUS DECIMAL(15, 2),
    NUMBER_RPOS_NOT_ONUS DECIMAL(8),
    AMOUNT_RPOS_NOT_ONUS DECIMAL(15, 2),
    TMSTAMP              TIMESTAMP(6),
    primary key (ID, CREDITOR_ID, SETTLEMENT_DATE)
);

