create table CP_OUT_FILE_REC_ST
(
    PROGRAM_ID      CHAR(5),
    FIELD_SN        INTEGER,
    PAYMENT_TYPE    SMALLINT,
    SELECTED_LINES  SMALLINT,
    RECORD_TYPE     SMALLINT,
    FIELD_DEC       SMALLINT,
    FIELD_LENGTH    SMALLINT,
    FIELD_TYPE      SMALLINT,
    FIELD_USAGE     SMALLINT,
    FIELD_SECTION   SMALLINT,
    FIELD_START_POS SMALLINT,
    FILLER_LENGTH   SMALLINT,
    START_POSITION  SMALLINT,
    CP_AGREEMENT_NO DECIMAL(10),
    TMSTAMP         TIMESTAMP(6),
    GEN_DET_RET     CHAR(1),
    DEC_POINT_SEP   CHAR(1),
    PARAMETER_TYPE  CHAR(5),
    FILLER_VALUE    CHAR(8),
    CATEGORY_CODE   CHAR(8),
    DATE_FORMAT     CHAR(10),
    FIELD_NAME      CHAR(30),
    FIELD_VALUE     CHAR(30),
    OTHER           CHAR(30),
    PROGRAM_DESC    VARCHAR(100)
);

create unique index IXU_CP__003
    on CP_OUT_FILE_REC_ST (PROGRAM_ID, FIELD_SN);

