create table CP_PARAMETERS
(
    BANK_CODE            SMALLINT,
    JUST_OL_DEBIT        INTEGER,
    JUST_ITEM_CHRG_TAX   INTEGER,
    JUST_ITEM_CHRG       INTEGER,
    JUST_TP_BLOCK_DEP    INTEGER,
    JUST_RET_CHRG        INTEGER,
    JUST_OL_CHRG_TAX     INTEGER,
    JUST_OL_CHRG         INTEGER,
    REV_VOUCHER_ID       INTEGER,
    JUST_TP_DEP_ACC_CRED INTEGER,
    JUST_OL_CREDIT       INTEGER,
    JUST_RET_CHRG_TAX    INTEGER,
    OL_COL_RENDER_DELAY  CHAR(1),
    ENTITY_CODE          VARCHAR(60)
);

create unique index IXU_CP__004
    on CP_PARAMETERS (BANK_CODE);

