create table CP_RECORD_FIELDS
(
    FIELD_NAME         VARCHAR(40),
    FK_DESCRIB_CP_FILE SMALLINT,
    FIELD_LENGTH       SMALLINT,
    STARTING_POSITION  SMALLINT,
    RECORD_TYPE        CHAR(1)
);

create unique index IXU_CP__007
    on CP_RECORD_FIELDS (FIELD_NAME, FK_DESCRIB_CP_FILE);

