create table CP_SCHOOLS
(
    CP_AGREEMENT_NO DECIMAL(10) not null,
    STUDENT_NO      CHAR(40)    not null,
    STUDENT_NAME    CHAR(100),
    STUDENT_CLASS   CHAR(20),
    STUDENT_STATUS  CHAR(2),
    GUARDIAN_EMAIL  CHAR(40),
    GUARDIAN_PHONE  CHAR(15),
    GUARDIAN_NAME   CHAR(100),
    EFFECTIVE_DATE  DATE,
    TP_IDENTIFIER   DECIMAL(10) not null,
    INS_TMSTAMP     TIMESTAMP(6),
    UPD_TMSTAMP     TIMESTAMP(6),
    COMMENTS        VARCHAR(500),
    primary key (CP_AGREEMENT_NO, STUDENT_NO)
);

