create table CP_THIRDPART_TEMPL
(
    FK_DEFIN_CP_AGREEM      DECIMAL(10),
    SIZE_2                  SMALLINT,
    VALID_ALGOR_IND_3       SMALLINT,
    SIZE_3                  SMALLINT,
    VALID_ALGOR_IND_2       SMALLINT,
    VALID_ALGOR_IND_1       SMALLINT,
    VALID_ALGOR_IND_4       SMALLINT,
    SIZE_1                  SMALLINT,
    SIZE_4                  SMALLINT,
    TMPSTAMP                TIMESTAMP(6),
    CR_DR_INDICATOR         CHAR(1),
    KEY_4                   CHAR(1),
    FORMAT_4                CHAR(1),
    KEY_3                   CHAR(1),
    MANDATORY_FLAG_3        CHAR(1),
    FORMAT_3                CHAR(1),
    KEY_2                   CHAR(1),
    MANDATORY_FLAG_2        CHAR(1),
    FORMAT_2                CHAR(1),
    FORMAT_1                CHAR(1),
    MANDATORY_FLAG_1        CHAR(1),
    KEY_1                   CHAR(1),
    MANDATORY_FLAG_4        CHAR(1),
    FIELD_1_2_SEPERAT       CHAR(6),
    FIELD_3_4_SEPERAT       CHAR(6),
    PROMPT_2                CHAR(30),
    PROMPT_1                CHAR(30),
    PROMPT_3                CHAR(30),
    PROMPT_4                CHAR(30),
    ORG_EXTRAIT_COM1        CHAR(1),
    ORG_EXTRAIT_COM2        CHAR(1),
    ORG_EXTRAIT_COM3        CHAR(1),
    ORG_EXTRAIT_COM4        CHAR(1),
    CUS_EXTRAIT_COM1        CHAR(1),
    CUS_EXTRAIT_COM2        CHAR(1),
    CUS_EXTRAIT_COM3        CHAR(1),
    CUS_EXTRAIT_COM4        CHAR(1),
    DF1_WS_VALIDATION       CHAR(1),
    DF2_WS_VALIDATION       CHAR(1),
    DF3_WS_VALIDATION       CHAR(1),
    DF4_WS_VALIDATION       CHAR(1),
    DF1_WS_SERVICE_CONTRACT CHAR(5),
    DF2_WS_SERVICE_CONTRACT CHAR(5),
    DF3_WS_SERVICE_CONTRACT CHAR(5),
    DF4_WS_SERVICE_CONTRACT CHAR(5),
    DTF1_LIST_OF_VALUES     CHAR(5),
    DTF2_LIST_OF_VALUES     CHAR(5),
    DTF3_LIST_OF_VALUES     CHAR(5),
    DTF4_LIST_OF_VALUES     CHAR(5)
);

create unique index IXU_CP__014
    on CP_THIRDPART_TEMPL (FK_DEFIN_CP_AGREEM);

