create table CP_TEMP_INTERFACE
(
    INTERNAL_SN  DECIMAL(13),
    CURRENCY_ID  INTEGER,
    AMOUNT       DECIMAL(15, 2),
    EXPIRY_DATE  DATE,
    PRINTED_FLAG CHAR(1),
    UNIT_CODE    CHAR(8),
    FILE_RECORD  VARCHAR(500)
);

create unique index IXU_CP__011
    on CP_TEMP_INTERFACE (INTERNAL_SN);

