create table CP_WS_COLLECTION_DATA
(
    CP_AGREEMENT_NO      DECIMAL(10) not null,
    DIAS_REFERENCE_NO    DECIMAL(15) not null,
    SYSTEM_CODE          CHAR(10),
    BRANCH_CODE          INTEGER,
    TELLER_ID            VARCHAR(8),
    TELLER_NAME          VARCHAR(100),
    MEANS_OF_PAYMENT     CHAR(1),
    REMITTER_ID          VARCHAR(50),
    REMITTER_NAME        VARCHAR(100),
    ESLIP_NUMBER         VARCHAR(80),
    PAYMENT_ADVICE_DATE  VARCHAR(20),
    PAYMENT_REFERENCE    VARCHAR(50),
    TAX_PAYER_PIN        VARCHAR(80),
    TAX_PAYER_FULLNAME   VARCHAR(100),
    TOTAL_AMOUNT         VARCHAR(20),
    COLLECTION_DATE      DATE,
    CURRENCY_DESCR       VARCHAR(3),
    CASH_AMOUNT          DECIMAL(15, 2),
    ADVICE_ID            DECIMAL(10),
    COLLECTED_AMOUNT     DECIMAL(15, 2),
    ADJUSTED_AMOUNT      DECIMAL(15, 2),
    TRANSFER_AMOUNT      DECIMAL(15, 2),
    HASHCODE             VARCHAR(100),
    TRX_DATE             DATE,
    TRX_UNIT             INTEGER,
    TRX_USR              CHAR(8),
    TRX_USR_SN           INTEGER,
    TIMESTMP             TIMESTAMP(6),
    SERIAL_NO            CHAR(10),
    RESPONSE_STATUS      CHAR(3),
    ACCOUNT_CODE         CHAR(20),
    ENTITY_NAME          VARCHAR(100),
    ENTITY_CODE          CHAR(20),
    AUTH_TOKEN           CHAR(62),
    AUTH_TOKEN_SIGNATURE VARCHAR(200),
    CUST_VALUE_DATE      DATE
);

create unique index PK_CP_WS_DATA
    on CP_WS_COLLECTION_DATA (CP_AGREEMENT_NO, DIAS_REFERENCE_NO);

