create table CPDAY_USER_COLLECT
(
    CURRENCY_SHORTDESC CHAR(5),
    COLLECTION_DATE    DATE,
    TRX_UNIT           INTEGER,
    TRX_USR            CHAR(8),
    TOTAL_DR_ITEM      DECIMAL(13),
    TOTAL_COLLECT_ITEM DECIMAL(13),
    TOTAL_CR_ITEM      DECIMAL(13),
    TOTAL_COLLECT_AMNT DECIMAL(15, 2),
    TOTAL_DR_AMNT      DECIMAL(15, 2),
    TOTAL_CR_AMNT      DECIMAL(15, 2)
);

create unique index IXU_CPD_000
    on CPDAY_USER_COLLECT (CURRENCY_SHORTDESC, COLLECTION_DATE, TRX_UNIT, TRX_USR);

