create table CPM_FILE_DETAIL
(
    DETAIL_SN                 DECIMAL(15) not null,
    TEXT_01                   VARCHAR(100),
    TEXT_02                   VARCHAR(100),
    TEXT_03                   VARCHAR(100),
    TEXT_04                   VARCHAR(100),
    TEXT_05                   VARCHAR(100),
    TEXT_06                   VARCHAR(100),
    TEXT_07                   VARCHAR(100),
    TEXT_08                   VARCHAR(100),
    TEXT_09                   VARCHAR(100),
    TEXT_10                   VARCHAR(100),
    DATE_01                   DATE,
    DATE_02                   DATE,
    DATE_03                   DATE,
    DATE_04                   DATE,
    DATE_05                   DATE,
    DATE_06                   DATE,
    DATE_07                   DATE,
    DATE_08                   DATE,
    DATE_09                   DATE,
    DATE_10                   DATE,
    FLAG_01                   CHAR(2),
    FLAG_02                   CHAR(2),
    FLAG_03                   CHAR(2),
    FLAG_04                   CHAR(2),
    FLAG_05                   CHAR(2),
    FLAG_06                   CHAR(2),
    FLAG_07                   CHAR(2),
    FLAG_08                   CHAR(2),
    FLAG_09                   CHAR(2),
    FLAG_10                   CHAR(2),
    AMOUNT_01                 DECIMAL(18, 2),
    AMOUNT_02                 DECIMAL(18, 2),
    AMOUNT_03                 DECIMAL(18, 2),
    AMOUNT_04                 DECIMAL(18, 2),
    AMOUNT_05                 DECIMAL(18, 2),
    AMOUNT_06                 DECIMAL(18, 2),
    AMOUNT_07                 DECIMAL(18, 2),
    AMOUNT_08                 DECIMAL(18, 2),
    AMOUNT_09                 DECIMAL(18, 2),
    AMOUNT_10                 DECIMAL(18, 2),
    COUNTER_01                DECIMAL(15),
    COUNTER_02                DECIMAL(15),
    COUNTER_03                DECIMAL(15),
    COUNTER_04                DECIMAL(15),
    COUNTER_05                DECIMAL(15),
    TIMESTAMP_01              TIMESTAMP(6),
    TIMESTAMP_02              TIMESTAMP(6),
    TIMESTAMP_03              TIMESTAMP(6),
    TIMESTAMP_04              TIMESTAMP(6),
    TIMESTAMP_05              TIMESTAMP(6),
    TIME_01                   TIMESTAMP(6),
    TIME_02                   TIMESTAMP(6),
    TIME_03                   TIMESTAMP(6),
    TIME_04                   TIMESTAMP(6),
    TIME_05                   TIMESTAMP(6),
    LOCKED_USER               CHAR(8),
    TRX_USR                   CHAR(8),
    STATUS                    CHAR(2),
    TMSTAMP                   TIMESTAMP(6),
    DB_NAME                   VARCHAR(50),
    COMPLETE_RECORD           VARCHAR(4000),
    LOOKUP_RECORD             VARCHAR(4000),
    FK_CPM_BANK_YEEPI_ACCOUNT VARCHAR(40),
    FK_CPM_FILE_HEADER_SN     DECIMAL(15) not null,
    FK_FLAGGED_GH             CHAR(5),
    FK_FLAGGED_GD             INTEGER,
    constraint ICPM0032
        primary key (FK_CPM_FILE_HEADER_SN, DETAIL_SN)
);

create unique index CPM_DETAIL_SEARCH
    on CPM_FILE_DETAIL (FK_CPM_FILE_HEADER_SN, DETAIL_SN, FK_CPM_BANK_YEEPI_ACCOUNT, STATUS, FLAG_01, FLAG_02, FLAG_03,
                        LOCKED_USER);

create unique index ICPM0584
    on CPM_FILE_DETAIL (FK_CPM_BANK_YEEPI_ACCOUNT);

