create table CPM_TRANSACTION_PROCESS
(
    TRANSACTION_SN            DECIMAL(15) not null,
    PROCESS_METHOD            CHAR(2),
    PROCESS_TYPE              CHAR(2),
    AMOUNT_REQUESTED          DECIMAL(18, 2),
    AMOUNT_PROCESSED          DECIMAL(18, 2),
    TRX_USR                   CHAR(8),
    TRX_CODE                  INTEGER,
    TUN_TMSTAMP               TIMESTAMP(6),
    TUN_DATE                  DATE,
    TUN_UNIT                  INTEGER,
    TUN_USR                   CHAR(8),
    TUN_SN                    INTEGER,
    TUN_INTERNAL_SN           SMALLINT,
    STATUS                    CHAR(2),
    TMSTAMP                   TIMESTAMP(6),
    ERROR_DESCRIPTION         VARCHAR(255),
    COMMENTS                  VARCHAR(100),
    FK_CPM_FILE_HEADER_SN     DECIMAL(15) not null,
    FK_CPM_FILE_DETAIL_SN     DECIMAL(15) not null,
    FK_CPM_RECORD_PPROCESS_SN DECIMAL(15) not null,
    REQUEST_SN                SMALLINT,
    REQUEST_TYPE              CHAR(1),
    REQUEST_LOAN_STS          CHAR(1),
    ERROR_CODE                INTEGER,
    PAIR_TMSTAMP              TIMESTAMP(6),
    PAIR_USR_SN               INTEGER,
    PAIR_INTERNAL_SN          SMALLINT,
    AMNT_CAPITAL              DECIMAL(18, 2),
    AMNT_REAL_NRM_INT         DECIMAL(18, 2),
    AMNT_REAL_PNL_INT         DECIMAL(18, 2),
    AMNT_UNRL_NRM_INT         DECIMAL(18, 2),
    AMNT_UNRL_PNL_INT         DECIMAL(18, 2),
    AMNT_EXPENSE              DECIMAL(18, 2),
    AMNT_COMMISSION           DECIMAL(18, 2),
    AMNT_SUBSIDY              DECIMAL(18, 2),
    REQUEST_EXP_DATE          DATE,
    VALUE_DATE                DATE,
    LAST_ACR_CALC_DATE        DATE,
    constraint ICPM0040
        primary key (FK_CPM_FILE_HEADER_SN, FK_CPM_FILE_DETAIL_SN, FK_CPM_RECORD_PPROCESS_SN, TRANSACTION_SN)
);

