create table CPM_RECORD_MATCHING
(
    MATCHING_SN             DECIMAL(15) not null,
    CRITERIA_TYPE           VARCHAR(200),
    CRITERIA_KEY            VARCHAR(100),
    CRITERIA_REQ_SEQUENCE   SMALLINT,
    CRITERIA_REQ_PERCENTAGE DECIMAL(5, 2),
    CRITERIA_FND_PERCENTAGE DECIMAL(5, 2),
    CRITERIA_TOT_PERCENTAGE DECIMAL(5, 2),
    CRITERIA_MATCH_PART     VARCHAR(100),
    CRITERIA_FILE_COLUMN    VARCHAR(4000),
    CRITERIA_DB_ORIGINAL    VARCHAR(100),
    CRITERIA_DB_TRANSLATED  VARCHAR(100),
    TMSTAMP                 TIMESTAMP(6),
    FK_CPM_FILE_DETAIL_SN   DECIMAL(15) not null,
    FK_CPM_FILE_HEADER_SN   DECIMAL(15) not null,
    constraint ICPM0035
        primary key (FK_CPM_FILE_HEADER_SN, FK_CPM_FILE_DETAIL_SN, MATCHING_SN)
);

