create table CPM_BTC_RECORDING
(
    TRX_DATE                     DATE     not null,
    TRX_UNIT                     INTEGER  not null,
    TRX_USER                     CHAR(8)  not null,
    TRX_USR_SN                   INTEGER  not null,
    TRX_INTERNAL_SN              SMALLINT not null,
    TRX_PAIR_USR_SN              INTEGER,
    TRX_PAIR_INTERNAL_SN         SMALLINT,
    TRX_REVERSED                 CHAR(1),
    PRFT_SYSTEM                  SMALLINT,
    TRX_CODE                     INTEGER,
    TERMINAL_NUMBER              CHAR(30),
    CHANNEL_ID                   INTEGER,
    AUTHORIZER1                  CHAR(8),
    AUTHORIZER2                  CHAR(8),
    YS_ACCOUNT                   VARCHAR(40),
    YS_YEEPI_SERIAL_NUM          INTEGER,
    YS_YEEPI_HEADER              CHAR(5),
    YS_SYSTEM_SERIAL_NUM         INTEGER,
    YS_SYSTEM_HEADER             CHAR(5),
    YS_ACCOUNT_STATUS            CHAR(1),
    MC_SYSTEM_SERIAL_NUM         INTEGER,
    MC_SYSTEM_HEADER             CHAR(5),
    MC_FILE_FIELD_SERIAL_NUM     INTEGER,
    MC_FILE_FIELD_HEADER         CHAR(5),
    MC_DATABASE_FIELD_SERIAL_NUM INTEGER,
    MC_DATABASE_FIELD_HEADER     CHAR(5),
    MC_DATABASE_KEY_SERIAL_NUM   INTEGER,
    MC_DATABASE_KEY_HEADER       CHAR(5),
    MC_REQUIRED_PERCENTAGE       DECIMAL(5, 2),
    MC_REQUIRED_SEQUENCE         SMALLINT,
    MC_REQUIRED_DATA_TYPE        CHAR(1),
    MC_REQUIRED_MIN_LENGTH       SMALLINT,
    MC_REGULAR_EXPRESSION        VARCHAR(255),
    MC_REGULAR_FORMAT            VARCHAR(255),
    MC_DB_NAME                   VARCHAR(50),
    MC_STATUS                    CHAR(1),
    FH_HEADER_SN                 DECIMAL(15),
    FH_HEADER_STATUS             CHAR(2),
    FD_DETAIL_SN                 DECIMAL(15),
    FD_DETAIL_STATUS             CHAR(2),
    FD_FLAG_02                   CHAR(2),
    FD_FLAG_03                   CHAR(2),
    FD_LOCKED_USER               CHAR(8),
    RP_PROCESS_SN                DECIMAL(15),
    RP_LOAN_ACCOUNT_UNIT         INTEGER,
    RP_LOAN_ACCOUNT_TYPE         SMALLINT,
    RP_LOAN_ACCOUNT_SN           INTEGER,
    RP_LOAN_ACCOUNT_CD           SMALLINT,
    RP_GL_ACCOUNT                VARCHAR(40),
    RP_PROFITS_ACCOUNT           VARCHAR(40),
    RP_CUSTOMER                  DECIMAL(10),
    RP_IS_REPRESENTATIVE         CHAR(1),
    RP_REPRESENTATIVE_NAME       VARCHAR(30),
    RP_AMOUNT_REQUESTED          DECIMAL(18, 2),
    RP_AMOUNT_PROCESSED          DECIMAL(18, 2),
    RP_COMMENTS                  VARCHAR(100),
    RP_STATUS                    CHAR(2),
    TP_TRANSACTION_SN            DECIMAL(15),
    TP_TRX_CODE                  INTEGER,
    TP_VALUE_DATE                DATE,
    TP_AMOUNT_REQUESTED          DECIMAL(18, 2),
    TP_AMOUNT_PROCESSED          DECIMAL(18, 2),
    TP_AMNT_CAPITAL              DECIMAL(18, 2),
    TP_AMNT_REAL_NRM_INT         DECIMAL(18, 2),
    TP_AMNT_REAL_PNL_INT         DECIMAL(18, 2),
    TP_AMNT_UNRL_NRM_INT         DECIMAL(18, 2),
    TP_AMNT_UNRL_PNL_INT         DECIMAL(18, 2),
    TP_AMNT_EXPENSE              DECIMAL(18, 2),
    TP_AMNT_COMMISSION           DECIMAL(18, 2),
    TP_AMNT_SUBSIDY              DECIMAL(18, 2),
    TP_REQUEST_SN                SMALLINT,
    TP_REQUEST_TYPE              CHAR(1),
    TP_REQUEST_LOAN_STS          CHAR(1),
    TP_REQUEST_EXP_DATE          DATE,
    TP_LAST_ACR_CALC_DATE        DATE,
    TP_TUN_TMSTAMP               TIMESTAMP(6),
    TP_TUN_DATE                  DATE,
    TP_TUN_UNIT                  INTEGER,
    TP_TUN_USR                   CHAR(8),
    TP_TUN_SN                    INTEGER,
    TP_TUN_INTERNAL_SN           SMALLINT,
    TP_STATUS                    CHAR(2),
    TP_PROCESS_METHOD            CHAR(2),
    TP_PROCESS_TYPE              CHAR(2),
    TP_COMMENTS                  VARCHAR(100),
    MATCHING_SN                  DECIMAL(15),
    FILE_CODE                    CHAR(5),
    FILE_NAME                    VARCHAR(100),
    SWIFT_REF_NO                 CHAR(16),
    TMSTAMP                      TIMESTAMP(6),
    TP_TRX_CR01_DB02             CHAR(2),
    RP_CUST_PORTOFOLIO           VARCHAR(50),
    FD_DETAIL_PRV_STATUS         CHAR(2),
    FD_FLAG_HEADER               CHAR(5),
    FD_FLAG_SERIAL_NUM           INTEGER,
    constraint I0001007
        primary key (TRX_DATE, TRX_UNIT, TRX_USER, TRX_USR_SN, TRX_INTERNAL_SN)
);

