create table CPM_SETUP_MATCHING
(
    DB_NAME                VARCHAR(50) not null,
    REQUIRED_SEQUENCE      SMALLINT    not null,
    REQUIRED_DATA_TYPE     CHAR(1),
    REQUIRED_PERCENTAGE    DECIMAL(5, 2),
    REQUIRED_MIN_LENGTH    SMALLINT,
    REGULAR_EXPRESSION     VARCHAR(255),
    REGULAR_FORMAT         VARCHAR(255),
    STATUS                 CHAR(1),
    TRX_USR                CHAR(8),
    TMSTAMP                TIMESTAMP(6),
    FK_DATABASE_FIELD_HEAD CHAR(5)     not null,
    FK_DATABASE_FIELD_NUM  INTEGER     not null,
    FK_DATABASE_FIELD_SN   INTEGER     not null,
    FK_DATABASE_FIELD_TYPE CHAR(5)     not null,
    FK_FILE_DETAIL_HEAD    CHAR(5)     not null,
    FK_FILE_DETAIL_NUM     INTEGER     not null,
    FK_FILE_DETAIL_SN      INTEGER     not null,
    FK_FILE_DETAIL_TYPE    CHAR(5)     not null,
    FK_SYSTEMIC_BANK_HEAD  CHAR(5)     not null,
    FK_SYSTEMIC_BANK_NUM   INTEGER     not null,
    FK_SPECIFIC_KEY_HEAD   CHAR(5),
    FK_SPECIFIC_KEY_NUM    INTEGER,
    FK_SPECIFIC_KEY_SN     INTEGER,
    FK_SPECIFIC_KEY_TYPE   CHAR(5),
    constraint ICPM0017
        primary key (FK_DATABASE_FIELD_HEAD, FK_DATABASE_FIELD_NUM, FK_DATABASE_FIELD_SN, FK_DATABASE_FIELD_TYPE,
                     FK_FILE_DETAIL_HEAD, FK_FILE_DETAIL_NUM, FK_FILE_DETAIL_SN, FK_FILE_DETAIL_TYPE,
                     FK_SYSTEMIC_BANK_HEAD, FK_SYSTEMIC_BANK_NUM, DB_NAME)
);

create unique index ICPM0892
    on CPM_SETUP_MATCHING (FK_SPECIFIC_KEY_HEAD, FK_SPECIFIC_KEY_NUM, FK_SPECIFIC_KEY_SN, FK_SPECIFIC_KEY_TYPE);

create unique index ICPM0903
    on CPM_SETUP_MATCHING (FK_DATABASE_FIELD_HEAD, FK_DATABASE_FIELD_NUM, FK_DATABASE_FIELD_SN, FK_DATABASE_FIELD_TYPE);

create unique index ICPM0905
    on CPM_SETUP_MATCHING (FK_FILE_DETAIL_HEAD, FK_FILE_DETAIL_NUM, FK_FILE_DETAIL_SN, FK_FILE_DETAIL_TYPE);

create unique index ICPM0907
    on CPM_SETUP_MATCHING (FK_SYSTEMIC_BANK_HEAD, FK_SYSTEMIC_BANK_NUM);

create unique index ICPM1234
    on CPM_SETUP_MATCHING (DB_NAME, REQUIRED_SEQUENCE, FK_FILE_DETAIL_HEAD, FK_FILE_DETAIL_NUM, FK_FILE_DETAIL_SN,
                           FK_FILE_DETAIL_TYPE, FK_SYSTEMIC_BANK_HEAD, FK_SYSTEMIC_BANK_NUM);

