create table CPM_MANUAL_FILE
(
    MNL_HEADER_SN     DECIMAL(15) not null,
    MNL_DETAIL_SN     DECIMAL(15) not null,
    DATE_LOADED       DATE,
    HEADER_SN         DECIMAL(15),
    SYSTEMIC_BANK     INTEGER,
    PROVIDER_ACCOUNT  VARCHAR(40),
    CR01_DB02         CHAR(2),
    AMOUNT_01         DECIMAL(18, 2),
    TEXT_09_BAN_REF   VARCHAR(100),
    TEXT_10_CURRENCY  VARCHAR(100),
    DATE_01_VALUE     DATE,
    LOOKUP_RECORD     VARCHAR(4000),
    CUSTOMER_ACCOUNT  CHAR(16),
    CUSTOMER_PAGIA    CHAR(13),
    CUSTOMER_CARD     CHAR(16),
    CUSTOMER_AFM      CHAR(10),
    STATUS            CHAR(2),
    ERROR_DESCRIPTION VARCHAR(100),
    TMSTAMP           TIMESTAMP(6),
    COMMENTS          VARCHAR(100),
    constraint ICPM_MANUAL_FILE
        primary key (MNL_HEADER_SN, MNL_DETAIL_SN)
);

