create table CURRENCY
(
    ID_CURRENCY        INTEGER,
    ROUNDING_TO        SMALLINT,
    COEFFICIENT        SMALLINT,
    MIN_NEGOT_UNIT     SMALLINT,
    DISPLAYED_DECIMAL  SMALLINT,
    ISO_CODE           SMALLINT,
    DAYSBASE           SMALLINT,
    MAX_VALUE_DAYS     SMALLINT,
    MULTIPLIER         INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    EURO_LOCKED_RATE   DECIMAL(12, 6),
    FIXED_RATE         DECIMAL(12, 6),
    MIN_AMOUNT         DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    PARITE_METHOD      CHAR(1),
    EXCH_CATEGORY      CHAR(1),
    EURO_IDENTIFIER    CHAR(1),
    MAIN_CATEGORY      CHAR(1),
    ENTRY_STATUS       CHAR(1),
    ENTRY_TYPE         CHAR(1),
    PAYMNT_VALEUR_FLAG CHAR(1),
    NATIONAL_FLAG      CHAR(1),
    CURRENCY_TYPE      CHAR(1),
    RATE_TABLE_FLAG    CHAR(1),
    TARGET             CHAR(1),
    CONST_TABLE_FLAG   CHAR(1),
    SHORT_DESCR        CHAR(5),
    DESCRIPTION        VARCHAR(40)
);

create unique index IXU_CUR_003
    on CURRENCY (ID_CURRENCY);

