create table CURR_TABLE_PRICES
(
    FK_CURRENCYID_CURR INTEGER,
    FK_CURR_TABLETABLE INTEGER,
    SELL_RATE          DECIMAL(9, 6),
    BUY_RATE           DECIMAL(9, 6),
    TIMESTMP           TIMESTAMP(6),
    FK_CURR_TABLEISSUE DATE,
    FK0CURR_TABLEISSUE DATE,
    STATUS             CHAR(1),
    FK_CURR_TABLEFK_CU CHAR(3)
);

create unique index IXU_CUR_001
    on CURR_TABLE_PRICES (FK_CURRENCYID_CURR, FK_CURR_TABLETABLE);

