create table CUS_DTL_HISTORY
(
    FK_CUSTOMERCUST_ID INTEGER,
    REC_ID             DECIMAL(15),
    CUST_CATEGORY      INTEGER,
    CLASSIF_SCALE      INTEGER,
    CLASSIFICATION     INTEGER,
    ANNUALINCOME       DECIMAL(15, 2),
    CLASSIF_DATE       DATE,
    TMSTAMP            TIMESTAMP(6),
    UPDATE_USER        CHAR(8),
    RATAPPROVALNO      CHAR(20)
);

create unique index IXU_CUS_032
    on CUS_DTL_HISTORY (FK_CUSTOMERCUST_ID, REC_ID);

