create table CUST_CARD_APPLIC
(
    APPLICATION_NO     INTEGER not null,
    ADD_CH_FIRST_NAME  CHAR(20),
    ADD_CH_SURNAME     CHAR(70),
    ADD_CH_LFIRST_NAME CHAR(20),
    ADD_CH_LTN_SURNAME CHAR(70),
    APPLICATION_STATUS CHAR(1),
    APPLICATION_DATE   DATE,
    ACCOUNT_NO         CHAR(40),
    PRFT_SYSTEM        SMALLINT,
    CARD_NO            CHAR(16),
    APPROVAL_DATE      DATE,
    CARD_PRIORITY      CHAR(1),
    APPLICATION_USER   CHAR(8),
    APPROVAL_USER      CHAR(8),
    FK_CARDTYP_DETAFK  CHAR(5) not null,
    FK_CARDTYP_DETASER INTEGER not null,
    FK_DEL_TYP_DETAFK  CHAR(5),
    FK_DEL_TYP_DETASER INTEGER,
    FK_UNITCODE        INTEGER not null,
    FK_CUSTOMERCUST_ID INTEGER not null,
    FK0UNITCODE        INTEGER,
    MAX_WTHDRW_AMN     DECIMAL(15, 2),
    MAX_PURCH_AMN      DECIMAL(15, 2),
    APPROVED_FLAG      CHAR(1),
    ACCOUNT_CD         SMALLINT,
    CARD_EXPIRY_DATE   DATE,
    RENEW_CARD_NO      CHAR(16),
    APPROVE_CARD_NO    CHAR(16),
    SENT_TO_FILE       CHAR(1) default '0',
    TMSTAMP            TIMESTAMP(6),
    REJECTION_CMNTS    VARCHAR(255),
    PREFERRED_NAME     CHAR(28)
);

create unique index PK_CUST_CARD_APP
    on CUST_CARD_APPLIC (FK_CARDTYP_DETAFK, FK_CARDTYP_DETASER, FK_DEL_TYP_DETAFK, FK_DEL_TYP_DETASER, FK_UNITCODE,
                         FK_CUSTOMERCUST_ID, APPLICATION_NO);

