create table CUSTOMER_SHAREHOLDERS
(
    FK_CUSTOMERCUST_ID    INTEGER,
    SERIAL_NUM            SMALLINT,
    SHARES_PERC           DECIMAL(8, 4),
    SHAREHOLDER_ID_TYPE   CHAR(50),
    SHAREHOLDER_ID_NUMBER CHAR(50),
    SHAREHOLDER_NAME      CHAR(100),
    CUST_ID               INTEGER
);

create unique index IXU_CUS_027
    on CUSTOMER_SHAREHOLDERS (FK_CUSTOMERCUST_ID, SERIAL_NUM);

