create table CUST_STOCK_INFO
(
    FK_CUSTOMERCUST_ID INTEGER,
    INVESTOR_CODE      INTEGER,
    NO_OF_SHARES       INTEGER,
    PTS_USER_SN        DECIMAL(10),
    ASHS_CODE          DECIMAL(12),
    TMSTAMP            TIMESTAMP(6),
    SHAREHOLDER_IND    CHAR(1),
    ENTRY_STATUS       CHAR(1),
    PTS_ACCOUNT_CONFIR CHAR(1),
    PTS_REGISTRY_CONFI CHAR(1),
    PTS_USER_CODE      CHAR(10),
    PTS_ACCOUNT        CHAR(11),
    PTS_REGISTRY       CHAR(11),
    INVESTOR_ABBR      CHAR(15),
    MAIL_PERSON        CHAR(60),
    COMMUNICATION_PERS CHAR(60)
);

create unique index IXU_CUS_018
    on CUST_STOCK_INFO (FK_CUSTOMERCUST_ID);

