create table CUST_TRANSFER_MASS
(
    CUST_ID          INTEGER,
    SOURCE_UNIT      INTEGER,
    TARGET_UNIT      INTEGER,
    TMSTAMP          TIMESTAMP(6),
    TRANSFERED_FLAGS CHAR(12),
    TRANSFER_SHARES  CHAR(1),
    PORTFOLIO_CODE   INTEGER,
    PORTFOLIO_UNIT   INTEGER,
    TRANSFER_TYPE    CHAR(1),
    ROW_STATUS       CHAR(1),
    ROW_ERR_DESC     CHAR(254),
    SN               DECIMAL(10)
);

create unique index IXU_CUSTR_001
    on CUST_TRANSFER_MASS (CUST_ID, SOURCE_UNIT, TARGET_UNIT, PORTFOLIO_CODE, PORTFOLIO_UNIT);

create unique index IXU_CUSTR_002
    on CUST_TRANSFER_MASS (SN, ROW_STATUS);

