create table CUSTOMER_APPLICATION
(
    UNIT_CODE        INTEGER  not null,
    APPLICATION_ID   CHAR(15) not null,
    CUST_ID          INTEGER  not null,
    ACCOUNT_CD       SMALLINT,
    APPLICATION_TYPE INTEGER,
    INTERNAL_SN      DECIMAL(11),
    DRAWDOWN_AMN     DECIMAL(15, 2),
    REQUEST_AMN      DECIMAL(15, 2),
    REQUEST_DT       DATE,
    DRAWDOWN_DT      DATE,
    CONFIRM_DT       DATE,
    TMSTAMP          TIMESTAMP(6),
    APPLICATION_STS  CHAR(2),
    CONFIRM_USR      CHAR(8),
    INSERT_USR       CHAR(8),
    ACCOUNT_NUMBER   CHAR(40),
    REQUEST_FORECAST VARCHAR(200),
    CONFIRM_CMNTS    VARCHAR(250),
    INSERT_CMNTS     VARCHAR(250),
    CHANNEL_ID       INTEGER,
    REFERENCE_NUMBER CHAR(40),
    constraint IXU_CUS_029
        primary key (UNIT_CODE, APPLICATION_ID, CUST_ID)
);

