create table CUST_COLL_TOTALS_U
(
    CUSTOMER_ID        INTEGER not null,
    COLLATERAL_CATEGOR CHAR(1) not null,
    COLLATERAL_TYPE    INTEGER not null,
    CURRENCY           INTEGER not null,
    ESTIMATED_VALUE_DB DECIMAL(15, 2),
    ESTIMATED_VALUE_CR DECIMAL(15, 2),
    ESTIMATED_INSUR_DB DECIMAL(15, 2),
    ESTIMATED_INSUR_CR DECIMAL(15, 2),
    CB_INSURANCE_DB    DECIMAL(15, 2),
    CB_INSURANCE_CR    DECIMAL(15, 2),
    YIELD_LIMIT_AMN    DECIMAL(15, 2),
    YIELD_UTILISED_AMN DECIMAL(15, 2),
    constraint IXU_CIU_025
        primary key (CURRENCY, COLLATERAL_TYPE, COLLATERAL_CATEGOR, CUSTOMER_ID)
);

