create table CUSTOMER_SYSTEM
(
    FK_GENERIC_DETASER INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    TMSTAMP            TIMESTAMP(6),
    FK_GENERIC_DETAFK  CHAR(5)
);

create unique index PKCUSTSY
    on CUSTOMER_SYSTEM (FK_CUSTOMERCUST_ID, FK_GENERIC_DETAFK, FK_GENERIC_DETASER);

