create table CUST_CARD_ACCOUNT
(
    FK_CUST_CARD_INCAR CHAR(16),
    ACCOUNT_NO         CHAR(20),
    TMSTAMP            TIMESTAMP(6),
    START_DATE         DATE,
    END_DATE           DATE,
    ENTRY_STATUS       CHAR(1),
    ACCOUNT_TYPE       CHAR(1),
    PROFITS_ACCOUNT_NU CHAR(40),
    PRF_AC_PRFT_SYSTEM SMALLINT,
    PROFITS_ACCOUNT_CD SMALLINT
);

create unique index IXU_CIS_995
    on CUST_CARD_ACCOUNT (FK_CUST_CARD_INCAR, PRF_AC_PRFT_SYSTEM, PROFITS_ACCOUNT_NU, ACCOUNT_NO);

