create table CUSTOMER_RF_CODES
(
    CUSTOMER_CODE     DECIMAL(7) not null,
    ACCOUNT_NUMBER    CHAR(40)   not null,
    ACCOUNT_SYSTEM    DECIMAL(2) not null,
    CUSTOMER_ROLE     CHAR(1),
    CUSTOMER_ID_NO    CHAR(20),
    CUST_RF_ID        VARCHAR(50),
    COLLECTION_CASE   CHAR(40),
    COLLECTION_SYSTEM DECIMAL(2),
    ENTRY_STATUS      CHAR(1),
    TMSTAMP           TIMESTAMP(6),
    CUST_INTERNAL_SN  DECIMAL(15),
    CUST_INTERNAL_ID  CHAR(15),
    ACCOUNT_UNIT      DECIMAL(5),
    constraint PK_CUSTOMER_RF_CODES
        primary key (ACCOUNT_NUMBER, ACCOUNT_SYSTEM, CUSTOMER_CODE)
);

