create table CUST_REAL_ESTATE
(
    FK_CUSTOMERCUST_ID INTEGER,
    IMAGE_DATE         DATE,
    FK_CURRENCYID_CURR INTEGER,
    RLEST_CUR_VAL5     DECIMAL(15, 2),
    RLEST_CUR_VAL2     DECIMAL(15, 2),
    RLEST_CUR_VAL1     DECIMAL(15, 2),
    RLEST_CUR_VAL3     DECIMAL(15, 2),
    RLEST_CUR_VAL4     DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    RLEST_SHARES3      CHAR(50),
    RLEST_AREA1        CHAR(50),
    RLEST_AREA3        CHAR(50),
    RLEST_SHARES4      CHAR(50),
    RLEST_SHARES5      CHAR(50),
    RLEST_AREA2        CHAR(50),
    RLEST_SHARES2      CHAR(50),
    RLEST_SHARES1      CHAR(50),
    RLEST_AREA5        CHAR(50),
    RLEST_AREA4        CHAR(50),
    RLEST_AQUIS_DESC4  CHAR(80),
    RLEST_AQUIS_DESC5  CHAR(80),
    RLEST_AQUIS_DESC3  CHAR(80),
    RLEST_AQUIS_DESC1  CHAR(80),
    RLEST_AQUIS_DESC2  CHAR(80),
    RLEST_CHARGES3     CHAR(100),
    RLEST_DESC_LOC4    CHAR(100),
    RLEST_DESC_LOC2    CHAR(100),
    RLEST_CHARGES1     CHAR(100),
    RLEST_CHARGES2     CHAR(100),
    RLEST_CHARGES4     CHAR(100),
    RLEST_DESC_LOC5    CHAR(100),
    RLEST_DESC_LOC3    CHAR(100),
    RLEST_CHARGES5     CHAR(100),
    RLEST_DESC_LOC1    CHAR(100)
);

create unique index IXP_CUS_001
    on CUST_REAL_ESTATE (FK_CUSTOMERCUST_ID, IMAGE_DATE);

