create table CUSTOMER_EXTRAIT
(
    TMSTAMP         TIMESTAMP(6),
    TUN_INTERNAL_SN SMALLINT,
    TRX_USR_SN      INTEGER,
    TRX_USER        CHAR(8),
    TRX_DATE        DATE,
    TRX_UNIT        INTEGER,
    ACCOUNT_NUMBER  CHAR(40),
    CUST_ID         INTEGER,
    ACCOUNT_CD      SMALLINT,
    TRX_CODE        INTEGER,
    JUSTIFIC_CODE   INTEGER,
    ACCOUNT_BALANCE DECIMAL(15, 2),
    TRX_AMOUNT      DECIMAL(15, 2),
    VALUE_DATE      DATE,
    TRX_COMMENTS    CHAR(40)
);

create unique index IXN_GLG_008
    on CUSTOMER_EXTRAIT (CUST_ID);

create unique index IXU_CUS_035
    on CUSTOMER_EXTRAIT (TMSTAMP, TUN_INTERNAL_SN, TRX_USR_SN, TRX_USER, TRX_DATE, TRX_UNIT, ACCOUNT_NUMBER, CUST_ID);

