create table CUSTOMER_DOC_CMNTS
(
    CMNT_COUNT        SMALLINT not null,
    CUST_ID           INTEGER  not null,
    FK_GH_RQTP1       CHAR(5)  not null,
    FK_GD_RQTP1       INTEGER  not null,
    FK_GH_RQTP2       CHAR(5)  not null,
    FK_GD_RQTP2       INTEGER  not null,
    FK_GH_RQTP3       CHAR(5)  not null,
    FK_GD_RQTP3       INTEGER  not null,
    TRX_USER          CHAR(8)  not null,
    TRX_UNIT          INTEGER  not null,
    TRX_DATE          DATE     not null,
    ENTRY_COMMENTS    CHAR(254),
    TMSTAMP           TIMESTAMP(6),
    SCANNED_FILE      CHAR(1),
    SCANNED_IMAGE_ID  DECIMAL(12),
    LINKED_FILE       CHAR(1),
    LINKED_FILE_SN    DECIMAL(15),
    EXPIRY_DATE       DATE,
    FILE_NAME         VARCHAR(40),
    FILE_EXTENSION    VARCHAR(4),
    ENTRY_STATUS      CHAR(1),
    INSERT_USER       CHAR(8),
    INSERT_UNIT       INTEGER,
    INSERT_DATE       DATE,
    UPDATE_USER       CHAR(8),
    UPDATE_UNIT       INTEGER,
    UPDATE_DATE       DATE,
    INS_CHANNEL_USER  VARCHAR(40),
    INS_REFERENCE_NUM CHAR(40),
    INS_SOFT_ID       VARCHAR(10),
    UPD_CHANNEL_USER  VARCHAR(40),
    UPD_REFERENCE_NUM CHAR(40),
    UPD_SOFT_ID       VARCHAR(10),
    GIVEN_FLAG        CHAR(1),
    WS_ID             VARCHAR(20),
    COMMAND           VARCHAR(80),
    constraint IXU_CIS_180
        primary key (CMNT_COUNT, CUST_ID, FK_GH_RQTP1, FK_GD_RQTP1, FK_GH_RQTP2, FK_GD_RQTP2, FK_GH_RQTP3, FK_GD_RQTP3,
                     TRX_USER, TRX_UNIT, TRX_DATE)
);

