create table CUST_PROD_SPC_AGR
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    COM_CHARGE_FRQ     SMALLINT,
    COMMISSION_PERCENT DECIMAL(8, 4),
    COMMISS_DISCOUNT   DECIMAL(8, 4),
    EXPENCE_DISCOUNT   DECIMAL(8, 4),
    COMMISSION_AMOUNT  DECIMAL(15, 2),
    MIN_COMMISION_AMNT DECIMAL(15, 2),
    EXPIRY_DATE        DATE,
    TMSTAMP            TIMESTAMP(6),
    COM_CHARGE_FRQ_TYP CHAR(1),
    ENTRY_STATUS       CHAR(1),
    TRX_USR            CHAR(8)
);

create unique index IXP_CUS_000
    on CUST_PROD_SPC_AGR (FK_PRODUCTID_PRODU, FK_CUSTOMERCUST_ID);

