create table CUST_INCOME_EXPENSE
(
    FINANCIAL_YEAR      SMALLINT not null,
    SERIAL_NUM          SMALLINT not null,
    NET_MONTH_AMN       DECIMAL(15, 2),
    GROSS_MONTH_AMN     DECIMAL(15, 2),
    NET_YEAR_AMN        DECIMAL(15, 2),
    GROSS_YEAR_AMN      DECIMAL(15, 2),
    INC_EXP_INDICATOR   CHAR(1)  not null,
    AMOUNT_IN_LC        DECIMAL(15, 2),
    TIMESTMP            TIMESTAMP(6),
    FK_CUSTOMERCUST_ID  INTEGER  not null,
    FK_YEAR             SMALLINT not null,
    FK_GENERIC_DETAFK   CHAR(5)  not null,
    FK_GENERIC_DETASER  INTEGER  not null,
    FK_CURRENCYID_CURR  INTEGER  not null,
    FK0GENERIC_DETAFK   CHAR(5)  not null,
    FK0GENERIC_DETASER  INTEGER  not null,
    FK1_GENERIC_DETAFK  CHAR(5),
    FK1_GENERIC_DETASER INTEGER,
    constraint PK_CUST_INCOME_DATA
        primary key (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_CURRENCYID_CURR, FK0GENERIC_DETAFK, FK0GENERIC_DETASER,
                     FK_CUSTOMERCUST_ID, FK_YEAR, SERIAL_NUM, INC_EXP_INDICATOR, FINANCIAL_YEAR)
);

create unique index I0000619
    on CUST_INCOME_EXPENSE (FK_GENERIC_DETAFK, FK_GENERIC_DETASER);

create unique index I0000620
    on CUST_INCOME_EXPENSE (FK0GENERIC_DETAFK, FK0GENERIC_DETASER);

create unique index I0000623
    on CUST_INCOME_EXPENSE (FK_CURRENCYID_CURR);

create unique index I0010613
    on CUST_INCOME_EXPENSE (FK_CUSTOMERCUST_ID, FK_YEAR);

