create table CUSTOMER_CATEGORY
(
    FK_CUSTOMERCUST_ID INTEGER,
    FK_CATEGORYCATEGOR CHAR(8),
    FK_GENERIC_DETASER INTEGER,
    TMSTAMP            TIMESTAMP(6),
    FK_GENERIC_DETAFK  CHAR(5)
);

create unique index IXU_CUS_023
    on CUSTOMER_CATEGORY (FK_CUSTOMERCUST_ID, FK_CATEGORYCATEGOR);

