create table CUST_ORDER_AGR
(
    FK_CUSTOMERCUST_ID INTEGER,
    FK_ORDER_AGREEMREG SMALLINT,
    ID_EXP_USAGE5      SMALLINT,
    ID_EXP_USAGE4      SMALLINT,
    ID_EXP_USAGE3      SMALLINT,
    ID_EXP_USAGE2      SMALLINT,
    ID_EXP_USAGE1      SMALLINT,
    ID_COM_USAGE4      SMALLINT,
    ID_COM_USAGE3      SMALLINT,
    ID_COM_USAGE2      SMALLINT,
    ID_COM_USAGE1      SMALLINT,
    ID_COM_USAGE5      SMALLINT,
    ID_TAX_2           INTEGER,
    ID_TAX_4           INTEGER,
    ID_TAX_5           INTEGER,
    ID_TAX_3           INTEGER,
    ID_COMMISSION_1    INTEGER,
    ID_COMMISSION_2    INTEGER,
    FK_ORD_DURATION    INTEGER,
    FK_ORDER_TRX_CODE  INTEGER,
    ID_TAX_1           INTEGER,
    ID_EXPENSE_5       INTEGER,
    ID_EXPENSE_4       INTEGER,
    ID_EXPENSE_3       INTEGER,
    ID_EXPENSE_2       INTEGER,
    ID_EXPENSE_1       INTEGER,
    ID_COMMISSION_5    INTEGER,
    ID_COMMISSION_4    INTEGER,
    ID_COMMISSION_3    INTEGER,
    FK_ORD_CUSTOMERCUS INTEGER,
    TMSTAMP            TIMESTAMP(6),
    FK_ORDER_STP_FLAG  CHAR(1),
    FK_ORD_SERVICECODE CHAR(2),
    FK_ORD_DETAIL_CHAR CHAR(3),
    FK_ORDER_INSTRUM   CHAR(8)
);

create unique index IXU_CUS_010
    on CUST_ORDER_AGR (FK_CUSTOMERCUST_ID, FK_ORD_CUSTOMERCUS, FK_ORDER_AGREEMREG, FK_ORD_DURATION, FK_ORDER_TRX_CODE,
                       FK_ORD_DETAIL_CHAR, FK_ORDER_STP_FLAG, FK_ORDER_INSTRUM);

