create table CUST_MEC_SETUP
(
    MEC_ID                 DECIMAL(10)    not null
        constraint PK_CUST_MEC_SETUP
            primary key,
    DEP_PRODUCT_FIRST      INTEGER,
    PERC_DEP_FIRST         DECIMAL(8, 4),
    DEP_PRODUCT_SECOND     INTEGER,
    PERC_DEP_SECOND        DECIMAL(8, 4),
    DEP_PRODUCT_TERM       INTEGER,
    PERC_DEP_TERM          DECIMAL(8, 4),
    LOAN_PRODUCT           INTEGER,
    LOAN_AGREEMENT_PRODUCT INTEGER,
    FK_CUST_CATEG1_GD      INTEGER,
    FK_CUST_CATEG2_GD      INTEGER,
    PERCENTAGE             SMALLINT,
    FIRST_PERCENTAGE       SMALLINT,
    SECOND_PERCENTAGE      SMALLINT,
    LIMIT_ACC_BALANCE      DECIMAL(15, 2),
    ACCOUNT_OPEN_AMOUNT    DECIMAL(15, 2) not null,
    DEP_PRODUCT_THIRD      INTEGER,
    DEP_PRODUCT_FOURTH     INTEGER,
    FK_CUST_CATEG3_GD      INTEGER,
    FK_CUST_CATEG4_GD      INTEGER,
    DEP_PRODUCT_FIFTH      INTEGER,
    FK_CUST_CATEG5_GD      INTEGER
);

