create table CUST_ADD_INFO
(
    FK_CUSTOMERCUST_ID INTEGER,
    TOTAL_EMPLOYEES    INTEGER,
    TAX_END_DATE       DATE,
    CORPORATION_START  DATE,
    CORPORATION_END_DA DATE,
    LEGAL_END_DATE     DATE,
    INSURANCE_END_DATE DATE,
    TMSTAMP            TIMESTAMP(6),
    PROPERTY_OWNER     CHAR(1),
    SALARY_RECORD_NUMB CHAR(12),
    CO_REPRES_TERMS    CHAR(254),
    END_REASON         CHAR(254),
    QUALIFICATIONS     VARCHAR(40),
    PROPERTYINFO       VARCHAR(250),
    SIGNATURE          VARCHAR(2000),
    ZAST_EXCL_AMNT     DECIMAL(15, 2),
    EXCL_USE_FLG       CHAR(1),
    ZAST_EXCL_END_DT   DATE,
    ZAST_UTIL_AMNT     DECIMAL(15, 2),
    RELIGION_TAX       DECIMAL(8, 4),
    LMT_SN             INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER
);

create unique index IXU_CUS_001
    on CUST_ADD_INFO (FK_CUSTOMERCUST_ID);

