create table CUSTOMERS_OUT
(
    CUST_ID           INTEGER not null
        constraint ATECUSTO
            primary key,
    SHORT_NAME        CHAR(7),
    SURNAME           CHAR(70),
    FIRST_NAME        CHAR(20),
    NUM_OF_CHILDREN   SMALLINT,
    DATE_OF_BIRTH     TIMESTAMP(6),
    NON_REGISTERED    CHAR(1),
    TITLE             CHAR(6),
    SEX               CHAR(1),
    CUST_TYPE         CHAR(1),
    FKUNIT_IS_SERV    INTEGER,
    FATHER_NAME       VARCHAR(20),
    ENTRY_COMMENTS    CHAR(254),
    ID_NO             CHAR(20),
    CARD_NO           CHAR(16),
    ISSUE_DATE        TIMESTAMP(6),
    ISSUE_AUTHORITY   CHAR(30),
    CITIZEN           INTEGER,
    COUNTRY_OF_ORIGIN INTEGER,
    PROFCODE          INTEGER,
    MARITAL_STATUS    INTEGER,
    ADDRESS_TYPE_1    CHAR(1),
    ADDRESS_TYPE_2    CHAR(1),
    CITY_1            CHAR(30),
    CITY_2            CHAR(30),
    ZIP_CODE_1        CHAR(30),
    ZIP_CODE_2        CHAR(30),
    ADD_ENTRY_COM_1   CHAR(250),
    ADD_ENTRY_COM_2   CHAR(250),
    TELEPHONE_1       CHAR(15),
    TELEPHONE_2       CHAR(15),
    COMMUN_ADDR_1     CHAR(1),
    COMMUN_ADDR_2     CHAR(1),
    ADDRESS_1_1       CHAR(40),
    ADDRESS_2_1       CHAR(40),
    ADDRESS_1_2       CHAR(40),
    ADDRESS_2_2       CHAR(40),
    FKGD_HAS_COUNT_1  INTEGER,
    FKGD_HAS_COUNT_2  INTEGER,
    INVESTOR_CODE     INTEGER,
    PTS_USER_CODE     CHAR(10),
    PTS_REGISTRY      CHAR(11),
    PTS_ACCOUNT       CHAR(11),
    INVES_ABBR        CHAR(15)
);

