create table CUST_CONTACT
(
    FK_CUSTOMERCUST_ID INTEGER,
    SERIAL_NO          INTEGER,
    FK_GENERIC_DETASER INTEGER,
    FK0GENERIC_DETASER INTEGER,
    FK_UNITCODE        INTEGER,
    CONTACT_DATE       DATE,
    TMSTAMP            TIMESTAMP(6),
    FK_GENERIC_DETAFK  CHAR(5),
    FK0GENERIC_DETAFK  CHAR(5),
    FK_BANKEMPLOYEEID  CHAR(8),
    CONTACT_COMMENT    VARCHAR(100),
    ACCOUNT_CD         SMALLINT,
    ACCOUNT_NUMBER     CHAR(40),
    CONTACT_DETAILS    VARCHAR(2048),
    EMAIL_SENT         CHAR(1),
    ENTRY_STATUS       CHAR(1),
    INSERT_DATE        DATE,
    INSERT_TMSTAMP     TIMESTAMP(6),
    INSERT_UNIT        INTEGER,
    INSERT_USER        CHAR(8),
    PRFT_SYSTEM        SMALLINT,
    PROMISED_AMOUNT    DECIMAL(15, 2),
    PROMISED_DATE      DATE,
    SMS_SENT           CHAR(1),
    UPDATE_DATE        DATE,
    UPDATE_TMSTAMP     TIMESTAMP(6),
    UPDATE_UNIT        INTEGER,
    UPDATE_USER        CHAR(8)
);

create unique index IXU_CUS_006
    on CUST_CONTACT (FK_CUSTOMERCUST_ID, SERIAL_NO);

