create table CUSTOMER_U
(
    FK_CUST_BANKEMPID      CHAR(8),
    FK0BANKEMPLOYEEID      CHAR(8),
    FK_GLG_ACCOUNTACCO     CHAR(21),
    FK_BANKEMPLOYEEID      CHAR(8),
    FK_DISTR_CHANNEID      INTEGER,
    FKUNIT_IS_SERVICED     INTEGER,
    FKCURR_THINKS_IN       INTEGER,
    FKCURR_HAS_AS_LIMI     INTEGER,
    FKUNIT_IS_MONITORE     INTEGER,
    FKUNIT_BELONGS         INTEGER,
    STATUS_DATE            DATE,
    BUSINESS_IND           CHAR(1),
    MAIL_IND               CHAR(1),
    MAJOR_BENEFICIARY      CHAR(1),
    SELF_INDICATOR         CHAR(1),
    SELF_NAME              CHAR(40),
    SELF_NUM               INTEGER,
    LIMIT                  DECIMAL(15, 2),
    FAX_INDICATOR          CHAR(1),
    CHILDREN_ABOVE18       SMALLINT,
    EMPLOYER_ADDRESS       CHAR(40),
    BIRTHPLACE             CHAR(20),
    NON_RESIDENT_FOR_REP   CHAR(1),
    CHAMBER_COMMENTS       VARCHAR(30),
    PENSIONER_IND          CHAR(1),
    INSTITUTE_INV_IND      CHAR(1),
    CONSOLID_STATM_FLG     CHAR(1),
    NON_PROFIT             CHAR(1),
    PROMOCODE              VARCHAR(6),
    INTERNET_ADDRESS       VARCHAR(100),
    MIDDLE_NAME            VARCHAR(15),
    BLACKLISTED_IND        CHAR(1),
    CUST_ID                INTEGER      not null
        constraint IXU_CIU_019
            primary key,
    C_DIGIT                SMALLINT,
    SHORT_NAME             CHAR(15)     not null,
    CORRESPONDENT_LIMIT    DECIMAL(15, 2),
    ALERT_MSG              CHAR(30),
    LEGAL_EXPIRE_DATE      DATE,
    SWIFT_CONNECTION_IND   CHAR(1),
    ATTRACTION_DETAILS     VARCHAR(40),
    MARKETING_REMINDER     VARCHAR(80),
    EMPLOYEMENT_START_DATE DATE,
    CHAMBER_ID             CHAR(10),
    NUM_OF_CHILDREN        SMALLINT,
    CLEANESS               SMALLINT,
    CLEANESS_COMMENTS      CHAR(80),
    CUSTOMER_BEGIN_DATE    DATE,
    CUST_STATUS            CHAR(1),
    VIP_IND                CHAR(1),
    CUST_TYPE              CHAR(1)      not null,
    NON_RESIDENT           CHAR(1),
    DATE_OF_BIRTH          DATE,
    ENTRY_STATUS           CHAR(1)      not null,
    EXPIRE_DATE            DATE,
    NON_REGISTERED         CHAR(1),
    TITLE                  CHAR(6),
    EMPLOYER               CHAR(40),
    DOC_EXPIRE_DATE        DATE,
    TELEX_CONNECTION       CHAR(1),
    ENTRY_COMMENTS         VARCHAR(254),
    LATIN_SURNAME          CHAR(70),
    LATIN_FIRSTNAME        CHAR(20),
    FATHER_SURNAME         CHAR(40),
    E_MAIL                 CHAR(64),
    NO_AFM                 CHAR(1),
    SECOND_SURNAME         CHAR(40),
    FAMILY_MEMBERS         SMALLINT,
    FIRST_NAME             CHAR(20),
    SURNAME                CHAR(70)     not null,
    MOBILE_TEL             VARCHAR(15),
    FATHER_NAME            VARCHAR(20),
    MOTHER_NAME            VARCHAR(20),
    MOTHER_SURNAME         CHAR(40),
    TMSTAMP                TIMESTAMP(6) not null,
    NOSTRO_ACCOUNT_IND     CHAR(1),
    VOSTRO_ACCOUNT_IND     CHAR(1),
    TELEX                  CHAR(15),
    PROHIBIT_WITHDRAW      CHAR(1),
    SEX                    CHAR(1),
    SWIFT_ADDRESS          VARCHAR(14),
    TELEPHONE_1            VARCHAR(15),
    ATTRACTION_PERSON      CHAR(50),
    SPOUSE_NAME            VARCHAR(20),
    INCOMPLETE_U_COMNT     CHAR(30),
    LAST_UPDATE            TIMESTAMP(6),
    FIN_RANGE_DT           DATE,
    FIN_RANGE              DECIMAL(15, 2),
    FK_BISS_CODE           INTEGER,
    FK_BRANCH_PORTFBRA     INTEGER,
    FK_BRANCH_PORTFPOR     INTEGER,
    IBAN_ACCOUNT           CHAR(27),
    BASEL_STATUS           CHAR(25),
    BASEL_DESCRIPTION      CHAR(90),
    FICLI_DESC             CHAR(42),
    FICLI_CODE             INTEGER,
    NOT_RES_BOP            CHAR(1),
    REF_B_TRX_USR_SN       INTEGER,
    REF_D_TRX_USR_SN       INTEGER,
    REF_TRX_USR            CHAR(8),
    REF_TRX_DATE           DATE,
    REF_TRX_UNIT           INTEGER,
    REF_DEP_ACC            DECIMAL(11),
    REF_CUSTID             INTEGER,
    CITY_OF_BIRTH          CHAR(20),
    REPR_PHONE             CHAR(15),
    REPR_SURNAME           CHAR(70),
    REPR_FIRSTNAME         CHAR(20),
    DAI_NUMBER             CHAR(12),
    FK_USRCODE             CHAR(8),
    SPM_NUMBER             CHAR(7),
    SEGM_FLAGS             CHAR(5),
    SWIFT_CONNECTION_I     CHAR(1),
    SUN_NONWORK            CHAR(1),
    SAT_NONWORK            CHAR(1),
    CERTIFIC_CUST          CHAR(1),
    SEPA_AGR_FLG           CHAR(1),
    NON_RESIDENT_FOR_R     CHAR(1),
    EMPLOYEMENT_START      DATE,
    CUSTOMER_BEGIN_DAT     DATE,
    CERTIFIC_DATE          DATE,
    SEPA_AGR_DT            DATE,
    CORRESPONDENT_LIMI     DECIMAL(15, 2)
);

