create table CUST_BROKERAGE
(
    FK_CUSTOMERCUST_ID INTEGER  not null,
    FK_TRACCOUNT_UNITC INTEGER  not null,
    FK_TRACCOUNTACC_SN INTEGER  not null,
    FK_TRACCOUNT_TYPE  SMALLINT not null,
    ASHS_CODE          DECIMAL(12),
    TMSTAMP            TIMESTAMP(6),
    constraint IXU_CIS_182
        primary key (FK_CUSTOMERCUST_ID, FK_TRACCOUNT_UNITC, FK_TRACCOUNTACC_SN, FK_TRACCOUNT_TYPE)
);

