CREATE FUNCTION DATETEXT (
    P_DATE_STR	VARCHAR(200),
    P_FORMAT_MASK	VARCHAR(40) DEFAULT 'yyyymmdd'
    )
  RETURNS DATE
BEGIN
  DECLARE ERROR_FLAG INTEGER DEFAULT 0;
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ERROR_FLAG = 1;
   RETURN TO_DATE (p_date_str, p_format_mask);
END;

