create table DCD_VOUCHER_RUN
(
    TMSTAMP      TIMESTAMP(6),
    TRX_DATE     DATE,
    TRX_UNIT     INTEGER,
    TRX_USER     CHAR(8),
    TRX_USR_SN   INTEGER,
    INTERNAL_SN  SMALLINT,
    PRINTED_FLAG SMALLINT,
    VOUCHER_LINE VARCHAR(2048)
);

create unique index IXU_DCD_033
    on DCD_VOUCHER_RUN (TMSTAMP, TRX_DATE, TRX_UNIT, TRX_USER, TRX_USR_SN, INTERNAL_SN);

