create table DCD_WORD_VOUCHER
(
    DCD_VOU_CUST_LANG INTEGER,
    DCD_VOUCHER       DECIMAL(12),
    DCD_RULE          DECIMAL(12),
    DCD_SYSTEM        DECIMAL(12),
    DCD_WORD_TEMPLATE VARCHAR(40)
);

create unique index IXU_DCD_043
    on DCD_WORD_VOUCHER (DCD_VOU_CUST_LANG, DCD_VOUCHER, DCD_RULE, DCD_SYSTEM);

