create table DCD_RULE_EXECUTE
(
    PROJECT            SMALLINT,
    RULE_ID            DECIMAL(12),
    INTERNAL_SN        INTEGER,
    ROUTINE_SYSTEM     SMALLINT,
    CALL_RULE_PROJECT  SMALLINT,
    PROCESS_PROJECT    SMALLINT,
    MATCH_POSITION     SMALLINT,
    CALC_POSITION      SMALLINT,
    OUTPUT_POSITION    SMALLINT,
    TRANSFER_TO        SMALLINT,
    FIRST_POSITION     SMALLINT,
    SECOND_POSITION    SMALLINT,
    DEC_PLACES         INTEGER,
    FIELD_LENGTH       INTEGER,
    UPDATE_FIELD_LINE  INTEGER,
    SNUM               INTEGER,
    DCD_EXIT_STATE_ID  DECIMAL(10),
    ROUTINE_CODE       DECIMAL(12),
    VOUCHER_ID         DECIMAL(12),
    PROCESS_RULE_ID    DECIMAL(12),
    CALL_RULE_ID       DECIMAL(12),
    INPUT_OUTPUT_FLG   CHAR(1),
    SEND_OUT_TO_CLT    CHAR(1),
    UPDATE_FIELD       CHAR(1),
    DISABLE_LINE       CHAR(1),
    USE_REASON         CHAR(1),
    CHECK_FIELD_FLG    CHAR(2),
    DATE_ADD           CHAR(2),
    ENTIRE_LINE_FLG    CHAR(2),
    FUNCTION_PERFORMED CHAR(3),
    LABEL_GOTO         CHAR(10),
    LABEL_LINE         CHAR(10),
    PROCESS_FIELD      CHAR(30),
    FIELD_ALIAS        CHAR(40),
    FIELD_TABLE        CHAR(40),
    FIELD_ATTRIBUTE    CHAR(40),
    MATCHED_TABLE      CHAR(40),
    MATCHED_ATTRIBUTE  CHAR(40),
    TMSTAMP            TIMESTAMP(6)
);

create unique index IXU_DCD_006
    on DCD_RULE_EXECUTE (PROJECT, RULE_ID, PROCESS_PROJECT, PROCESS_RULE_ID, ROUTINE_SYSTEM, ROUTINE_CODE, SNUM);

create unique index IXU_DCD_007
    on DCD_RULE_EXECUTE (PROJECT, RULE_ID, PROCESS_PROJECT, PROCESS_RULE_ID, USE_REASON, UPDATE_FIELD,
                         UPDATE_FIELD_LINE);

create unique index IXU_DCD_026
    on DCD_RULE_EXECUTE (PROJECT, RULE_ID, INTERNAL_SN);

