create table DCD_FIELD
(
    TABLE_ENTITY       CHAR(40),
    TABLE_ATTRIBUTE    CHAR(40),
    PRFT_SYSTEM        SMALLINT,
    DEC_PLACES         INTEGER,
    FIELD_LENGTH       INTEGER,
    LANGUAGE_USED      INTEGER,
    MODEL_ID           DECIMAL(12),
    TYPE_IND           CHAR(1),
    VARYING_LENGTH     CHAR(1),
    FIELD_USED         CHAR(1),
    UPDATE_FIELD       CHAR(1),
    TEMPORARY_FIELD    CHAR(1),
    SECOND_FIELD       CHAR(1),
    FIRST_FIELD        CHAR(1),
    CALC_FIELD         CHAR(1),
    FROM_ENCYCLOPEDIA  CHAR(1),
    OPTIONAL_MANDATORY CHAR(2),
    CATEGORY_TYPE      CHAR(2),
    FIELD_TYPE         CHAR(2),
    DESCRIPTION        CHAR(40),
    ALIAS_TABLE_ORIGIN CHAR(40),
    RELATIONSHIP_TABLE CHAR(40),
    FUNCTIONALITY_DESC CHAR(240)
);

create unique index IXU_DCD_023
    on DCD_FIELD (TABLE_ENTITY, TABLE_ATTRIBUTE);

