create table DCD_GD_PROPERTIES
(
    FK_DCD_GD_WINDOFK  INTEGER  not null,
    FK_DCD_GD_WINDOFK0 INTEGER  not null,
    FK_DCD_GD_WINDOFK1 INTEGER  not null,
    FK0DCD_GD_WINDOFK  SMALLINT not null,
    FK0DCD_GD_WINDOFK0 CHAR(5)  not null,
    FK_DCD_GD_WINDOSER INTEGER  not null,
    SERIAL_NUMBER      INTEGER  not null,
    PRFT_SYSTEM        SMALLINT,
    EXEC_EVENT         SMALLINT,
    AFTER_EXEC         SMALLINT,
    FK_DCD_GH_WINOTHV  SMALLINT,
    FK_DCD_GH_WINPROD  INTEGER,
    FK_DCD_GH_WINPRFT  INTEGER,
    FK_DCD_GH_WINJUST  INTEGER,
    FK_DCD_GD_WINSER   INTEGER,
    RULE_ID            DECIMAL(12),
    FK_DCD_GH_WINPRDA  DATE,
    FK_DCD_GH_WINOTHT  CHAR(5),
    B_COMMAND          CHAR(10),
    constraint IXU_DEF_047
        primary key (FK_DCD_GD_WINDOFK, FK_DCD_GD_WINDOFK0, FK_DCD_GD_WINDOFK1, FK0DCD_GD_WINDOFK, FK0DCD_GD_WINDOFK0,
                     FK_DCD_GD_WINDOSER, SERIAL_NUMBER)
);

