create table DEAL_TICKET
(
    TICKET_DATE              DATE    not null,
    SN                       INTEGER not null,
    TRX_USER_INT_SN          SMALLINT,
    MM_INT_CALC_BASE         SMALLINT,
    BUY_BORROW_CCY           INTEGER,
    SELL_LEND_CCY            INTEGER,
    TRX_UNIT                 INTEGER,
    FK_BUY_CUSTOMER          INTEGER,
    FK_SELL_CUSTOMER         INTEGER,
    TRX_USER_SN              INTEGER,
    RATE                     DECIMAL(12, 6),
    LEG2_INTEREST_BUY        DECIMAL(12, 6),
    LEG2_INTEREST_SELL       DECIMAL(12, 6),
    LEG2_RATE                DECIMAL(12, 6),
    LEG2_BUY_AMOUNT          DECIMAL(15, 2),
    LEG2_SELL_AMOUNT         DECIMAL(15, 2),
    CR_AMOUNT                DECIMAL(15, 2),
    SELL_LEND_AMOUNT         DECIMAL(15, 2),
    DB_AMOUNT                DECIMAL(15, 2),
    BUY_BORROW_AMOUNT        DECIMAL(15, 2),
    LEG2_VALEUR_DATE         DATE,
    TRX_DATE                 DATE,
    END_DATE                 DATE,
    VALEUR_DATE              DATE,
    TMSTAMP                  TIMESTAMP(6),
    MM_TRANS_TYPE            CHAR(1),
    FX_TRANS_TYPE            CHAR(1),
    ENTRY_STATUS             CHAR(1),
    LEG1_PROCESSED_FLG       CHAR(1),
    FX_TYPE                  CHAR(1),
    TICKET_TYPE              CHAR(1),
    LEG2_PROCESSED_FLG       CHAR(1),
    PRIM_AMT_FLG             CHAR(1),
    VERIFY_DEALER            CHAR(8),
    FK_USRCODE               CHAR(8),
    TRX_USER                 CHAR(8),
    REFERENCE_NO             CHAR(16),
    FK_BUY_PROF_ACC          CHAR(40),
    FK_SELL_PROF_ACC         CHAR(40),
    BANK_INSTRUCTIONS        CHAR(80),
    DB_INSTRUCTIONS          CHAR(100),
    CR_INSTRUCTIONS          CHAR(100),
    SPECIAL_INSTRUCTIONS     CHAR(200),
    LEG2_INSTRUCTIONS        CHAR(200),
    SEC_TRANS_TYPE           CHAR(1),
    PRICE                    DECIMAL(15, 8),
    BANK_ID                  INTEGER,
    DB_BANK_ID               INTEGER,
    CR_BANK_ID               INTEGER,
    ROLLOVER_FLAG            CHAR(1),
    PREDETERMINE_FLAG        CHAR(1),
    PREDETERMINED_EXEC       CHAR(1),
    INITIAL_END_DATE         DATE,
    INITIAL_VALUE_DATE       DATE,
    INITIAL_RATE             DECIMAL(12, 6),
    INITIAL_AMOUNT           DECIMAL(15, 2),
    TICKET_DATE_ROLL         DATE,
    TICKET_SN_ROLL           INTEGER,
    BANK_ID_BIC              CHAR(11),
    BANK_ID_PARTY_ID         CHAR(60),
    CR_BANK_BIC              CHAR(11),
    CR_BANK_PARTY_ID         CHAR(60),
    CR_CUST_ID               INTEGER,
    DB_BANK_BIC              CHAR(11),
    DB_BANK_PARTY_ID         CHAR(60),
    DB_CUST_ID               INTEGER,
    INSTALLMENTS             DECIMAL(3),
    PAY_FREQUENCE            SMALLINT,
    INSTALLMNT_TYPE          DECIMAL(1),
    LOAN_PROGRAM             DECIMAL(5),
    INTEREST_ID              DECIMAL(5),
    CUST_ID                  DECIMAL(7),
    CUST_C_DIGIT             DECIMAL(1),
    LOAN_ACCOUNT             CHAR(40),
    LOAN_CD                  SMALLINT,
    LOAN_TICKET              CHAR(1),
    BOND_CODE                CHAR(15),
    YIELD_RATE               DECIMAL(15, 8),
    DIRTY_PRICE              DECIMAL(15, 8),
    SPOT_MARKET_RATE         DECIMAL(12, 6),
    FWD_PTS_MARKET_RATE      DECIMAL(12, 6),
    ALL_IN_MARKET_RATE       DECIMAL(12, 6),
    BASE_MARGIN              DECIMAL(12, 6),
    CUSTOMER_MARGIN          DECIMAL(12, 6),
    ALL_IN_MARGIN            DECIMAL(12, 6),
    SPOT_MARKET_RATE_LEG2    DECIMAL(12, 6),
    FWD_PTS_MARKET_RATE_LEG2 DECIMAL(12, 6),
    ALL_IN_MARKET_RATE_LEG2  DECIMAL(12, 6),
    BASE_MARGIN_LEG2         DECIMAL(12, 6),
    CUSTOMER_MARGIN_LEG2     DECIMAL(12, 6),
    ALL_IN_MARGIN_LEG2       DECIMAL(12, 6),
    CUST_HEDGE_INTERB        DECIMAL(1),
    ET_UNIQUE_NUMBER         CHAR(20),
    BLOCK_USR                CHAR(8),
    BLOCK_JUSTIFIC           DECIMAL(8),
    BLOCK_STATUS             CHAR(1),
    BLOCK_DATE               DATE,
    BLOCK_UNIT               DECIMAL(5),
    BLOCK_USR_SN             DECIMAL(8),
    BLOCK_AMOUNT             DECIMAL(15, 6),
    INTEREST_RATE_L          DECIMAL(15, 8),
    EXCHANGE_RATE_L          DECIMAL(15, 8),
    EXCHANGE_RATE2_L         DECIMAL(15, 8),
    FX_SPECIAL_RATE          CHAR(1),
    constraint IXU_FX_053
        primary key (TICKET_DATE, SN)
);

create unique index SKEY_ROLLOVER
    on DEAL_TICKET (TICKET_SN_ROLL, TICKET_DATE_ROLL);

