create table DEAL_POSITION
(
    FK_CURRENCYID_CURR INTEGER,
    EXCHANGE_NOTES_IND CHAR(1),
    TRX_DATE           DATE,
    TARGET_AMOUNT      DECIMAL(15, 2),
    SOURCE_EQUIVALENT  DECIMAL(15, 2),
    SOURCE_AMOUNT      DECIMAL(15, 2),
    TARGET_EQUIVALENT  DECIMAL(15, 2)
);

create unique index IXU_DEA_000
    on DEAL_POSITION (FK_CURRENCYID_CURR, EXCHANGE_NOTES_IND, TRX_DATE);

