create table DEL_EOM_REAL_ESTATE_TMP2
(
    PROPERTYID       DECIMAL(10) not null,
    DESCRIPTION      VARCHAR(40),
    DRAWDOWN_FST_DT  DATE,
    ACC_LIMIT_AMN    DECIMAL(15, 2),
    TOT_DRAWDOWN_AMN DECIMAL(15, 2)
);

