create table DEL_W_DIM_ISS_COMMITMENT
(
    ISS_COMMITMENT_KEY DECIMAL(15, 2),
    TP_SO_IDENTIFIER   DECIMAL(10),
    ROW_DATE_FROM      DATE,
    ROW_DATE_TO        DATE,
    ROW_CURRENT_FLAG   DECIMAL(15, 2),
    ENTRY_STATUS       CHAR(2),
    ENTRY_STATUS_NAME  VARCHAR(50)
);

