create table DEL_W_EOM_DH_ACCOUNT_AGREE
(
    EOM_DATE       DATE,
    ACCT_KEY       DECIMAL(11),
    AGREE_ACCT_KEY DECIMAL(11)
);

create unique index PK_W_EOM_DH_ACCOUNT_AGREE
    on DEL_W_EOM_DH_ACCOUNT_AGREE (EOM_DATE, ACCT_KEY, AGREE_ACCT_KEY);

