create table DEL_EOM_GENERIC_HEADER
(
    EOM_DATE         DATE,
    PARAMETER_TYPE   CHAR(5),
    DEFAULT_NUM      INTEGER,
    TMSTAMP          DATE,
    SYSTEM_PARAMETER CHAR(1),
    SHOW_FLAG        CHAR(1),
    PURPOSE_FLAG     CHAR(1),
    ENTRY_STATUS     CHAR(1),
    ABBREVIATION     VARCHAR(15),
    DESCRIPTION      VARCHAR(40)
);

create unique index PK_HEADER
    on DEL_EOM_GENERIC_HEADER (EOM_DATE, PARAMETER_TYPE);

