create table DEL_EOM_CUSTOMER_CATEGORY
(
    EOM_DATE           DATE,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_CATEGORYCATEGOR CHAR(8),
    FK_GENERIC_DETASER INTEGER,
    TMSTAMP            DATE,
    FK_GENERIC_DETAFK  CHAR(5)
);

create unique index EOM_CUSTOMER_CATEGORY_PK
    on DEL_EOM_CUSTOMER_CATEGORY (FK_CATEGORYCATEGOR, FK_CUSTOMERCUST_ID, EOM_DATE);

