create table DEL_W_STG_LOAN_APPLICATIO
(
    APPL_ID             CHAR(10),
    ACCOUNT_NUMBER      CHAR(40),
    APPLICATION_TYPE    CHAR(100),
    APPROVAL_DATE       DATE,
    SALES_PRICE         DECIMAL(15, 2),
    RECEIVE_RENT_AMOUNT DECIMAL(15, 2)
);

create unique index PK_W_STG_LOAN_APPLICATION
    on DEL_W_STG_LOAN_APPLICATIO (ACCOUNT_NUMBER, APPL_ID, APPLICATION_TYPE);

