create table DEP_PRICING
(
    FK_DEP_TRXJUSTFK_D INTEGER  not null,
    FK_DEP_TRXJUSTFK_J INTEGER  not null,
    FK_DEP_TRXJUSTFK_P INTEGER  not null,
    SNUM               SMALLINT not null,
    FK_PARAMETRIC_RSNU SMALLINT,
    ID_PRODUCT         INTEGER,
    FK_PARAMETRIC_RID  INTEGER,
    FK_EXPENSEID_EXPEN INTEGER,
    FK0TAXID_TAX       INTEGER,
    FK_COMMISSIONID_CO INTEGER,
    FK_TAXID_TAX       INTEGER,
    COM_UP_LIMIT       DECIMAL(8, 4),
    COM_LOW_LIMIT      DECIMAL(8, 4),
    EXP_UP_LIMIT       DECIMAL(8, 4),
    EXP_LOW_LIMIT      DECIMAL(8, 4),
    VALIDITY_DATE      DATE,
    ENTRY_STATUS       CHAR(1),
    constraint IXU_DEP_127
        primary key (FK_DEP_TRXJUSTFK_D, FK_DEP_TRXJUSTFK_J, FK_DEP_TRXJUSTFK_P, SNUM)
);

