create table DEP_ACC_ADD_INFO
(
    ACCOUNT_NUMBER  DECIMAL(11),
    ROW_ID          INTEGER,
    ROW_INTERNAL_SN INTEGER,
    RATE_DATA       DECIMAL(8, 4),
    NUM_DATA        DECIMAL(15, 2),
    AMOUNT_DATA     DECIMAL(15, 2),
    DATE_DATA       DATE,
    TMSTAMP_DATA    TIMESTAMP(6),
    ENTRY_STATUS    CHAR(1),
    TEXT_DATA       VARCHAR(100)
);

create unique index IXU_DEP_025
    on DEP_ACC_ADD_INFO (ACCOUNT_NUMBER, ROW_ID, ROW_INTERNAL_SN);

