create table DEP_HCLASS_GL
(
    LOAN_STATUS        CHAR(1) not null,
    TIMESTMP           TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    CR_INT_ACCR_GL_LVL CHAR(1),
    CR_INT_ACCR_GL_ACC CHAR(21),
    DR_INT_ACCR_GL_LVL CHAR(1),
    DR_INT_ACCR_GL_ACC CHAR(21),
    CR_INT_GL_ACC_LVL  CHAR(1),
    CR_INT_GL_ACC      CHAR(21),
    DR_INT_GL_ACC_LVL  CHAR(1),
    DR_INT_GL_ACC      CHAR(21),
    CR_CNTR_GL_ACC_LVL CHAR(1),
    CR_CNTR_GL_ACC     CHAR(21),
    DR_CNTR_GL_ACC_LVL CHAR(1),
    DR_CNTR_GL_ACC     CHAR(21),
    FK_HPRODUCTVALIDIT DATE    not null,
    FK_HPRODUCTID_PROD INTEGER not null,
    FK_GENERIC_DETAFK  CHAR(5) not null,
    FK_GENERIC_DETASER INTEGER not null,
    DELIVERED_FLG      CHAR(1),
    constraint PKCLASSG
        primary key (FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT, FK_GENERIC_DETASER, FK_GENERIC_DETAFK, LOAN_STATUS)
);

