create table DEP_INTERF_CUST
(
    CUST_ID       INTEGER,
    PROD_CATEGORY INTEGER,
    PROD_MONTH    SMALLINT,
    PROD_YEAR     SMALLINT
);

create unique index IXU_DEP_050
    on DEP_INTERF_CUST (CUST_ID, PROD_CATEGORY, PROD_MONTH, PROD_YEAR);

