create table DEP_TRN_SCALE
(
    ID_PRODUCT      INTEGER,
    VALIDITY_DATE   DATE,
    SCALE_ID        SMALLINT,
    TRN_COUNT_FROM  SMALLINT,
    TRN_COUNT_TO    SMALLINT,
    TRN_RATE_SPREAD DECIMAL(8, 4)
);

create unique index IXU_DEP_065
    on DEP_TRN_SCALE (ID_PRODUCT, VALIDITY_DATE, SCALE_ID);

