create table DEP_ACCOUNT_INFO
(
    FK1DEPOSIT_ACCOACC DECIMAL(11),
    LNS_ACC_TYPE       SMALLINT,
    LNS_UNITCODE       INTEGER,
    LNS_ACC_SN         INTEGER,
    LST_PRCSD_EXTRT_SN INTEGER,
    TOT_SPRD_INTEREST  DECIMAL(15, 2),
    TOT_PRODUCT_AMN    DECIMAL(15, 2),
    OVERDU_DB_ACCRUALS DECIMAL(15, 2),
    TOT_DB_INTEREST_AM DECIMAL(15, 2),
    TOT_SUBS_INTEREST  DECIMAL(15, 2),
    TOT_N128_INTEREST  DECIMAL(15, 2),
    TOT_PEN_INTEREST_A DECIMAL(15, 2),
    NORMAL_DB_ACCRUALS DECIMAL(15, 2),
    LAST_EXTRAIT_DATE  DATE,
    ERROR_STATUS       CHAR(1),
    PROCESS_FLG        CHAR(2),
    OA_DURATION        SMALLINT,
    OA_DURATION_UNIT   CHAR(1),
    OA_COLLECT_FREQ    SMALLINT,
    OA_COLL_FREQ_UNIT  CHAR(1),
    FKINT_CURRENT_FIX  INTEGER,
    CUR_FX_INT_ST_DT   DATE,
    CUR_FX_INT_EXP_DT  DATE,
    MT942_PRINT        INTEGER,
    DEBIT_INT_DATE     DATE,
    INTEREST_UTIL_AMNT DECIMAL(15, 2),
    SWIFT_MT940        INTEGER,
    SWIFT_MT942        INTEGER,
    MT940_TO           INTEGER,
    MT940_FROM         INTEGER,
    MT942_FROM         INTEGER,
    MT942_TO           INTEGER
);

create unique index IXN_DEP_001
    on DEP_ACCOUNT_INFO (LNS_UNITCODE, LNS_ACC_TYPE, LNS_ACC_SN);

create unique index IXU_DEP_018
    on DEP_ACCOUNT_INFO (FK1DEPOSIT_ACCOACC);

