create table DEP_IN_ACCOUNT
(
    ACCOUNT_NUMBER          DECIMAL(11),
    ID_PRODUCT              INTEGER,
    DEPOSIT_TYPE            CHAR(1),
    IN_ID_CURRENCY          INTEGER,
    IN_SHORT_DESCR          CHAR(5),
    IN_BOOK_BALANCE         DECIMAL(15, 2),
    EUR_F_BOOK_BALANCE      DECIMAL(15, 2),
    IN_AVAILABLE_BALANCE    DECIMAL(15, 2),
    IN_UNCLEAR_BALANCE      DECIMAL(15, 2),
    IN_BLOCKED_BALANCE      DECIMAL(15, 2),
    IN_FORECAST_BALANCE     DECIMAL(15, 2),
    IN_INIT_VALUE_BALANCE   DECIMAL(15, 2),
    IN_LAST_INT_AVG_BALANCE DECIMAL(15, 2),
    IN_ACCR_CR_INTEREST     DECIMAL(15, 2),
    IN_ACCR_DB_INTEREST     DECIMAL(15, 2),
    IN_DB_PROGRESS_INTER    DECIMAL(15, 2),
    IN_OVERDRAFT_SPREAD     DECIMAL(15, 2),
    IN_ENCROACH_TOLERANCE   DECIMAL(15, 2),
    IN_PSB_LINE_SN          INTEGER,
    IN_PSB_PENDING_LINES    SMALLINT,
    IN_PSB_LAST_BALANCE     DECIMAL(15, 2),
    IN_LST_STATEMENT_NUM    INTEGER,
    IN_EXTRAIT_TRX_COUNT    INTEGER,
    IN_PENDING_EXTR_LINES   DECIMAL(10),
    IN_CHEQUES_BAD_TOTAL    DECIMAL(15, 2),
    IN_STAMP_AMOUNT_TOTAL   DECIMAL(15, 2),
    IN_FC_INTER_LC_PRIM     DECIMAL(15, 2),
    IN_FC_INTEREST_LC_NET   DECIMAL(15, 2),
    IN_TEMPORARY_EXCESS     DECIMAL(15, 2),
    IN_ACCOUNT_LIMIT        DECIMAL(15, 2),
    IN_BLNC_BEF_OVERDRN     DECIMAL(15, 2),
    TMSTAMP                 TIMESTAMP(6)
);

create unique index IXP_DEP_000
    on DEP_IN_ACCOUNT (ACCOUNT_NUMBER);

