create table DEP_UNCLEAR_TRANS
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    UNCLEAR_COUNT      DECIMAL(10),
    AVAILABILITY_DATE  DATE,
    UNCLEARED_BALANCE  DECIMAL(15, 2),
    VALUE_DATE         DATE,
    AUTO_CLEAR         CHAR(1),
    ENTRY_STATUS       CHAR(1),
    TOLERANCE_FLGS     CHAR(8),
    REFERENCE_NUMBER   CHAR(20),
    ID_JUSTIFIC        INTEGER
);

create unique index IXU_DEP_070
    on DEP_UNCLEAR_TRANS (FK_DEPOSIT_ACCOACC, UNCLEAR_COUNT, AVAILABILITY_DATE);

