create table DEP_TRXJUST_CNT
(
    FK_TRANSACTION0ID  INTEGER,
    TRN_TYPE           VARCHAR(1),
    PENAL_APPLIED      VARCHAR(1),
    UNCLEAR_WITHDR_FLG VARCHAR(1),
    DEP_ACC_STATUS     VARCHAR(1),
    FK_PARAMETRIC_RID  INTEGER,
    CNT                DECIMAL(15, 2)
);

