create table DEP_PROD_SCALE
(
    VALIDITY_DATE    DATE,
    PROD_CATEGORY    INTEGER,
    ID_PRODUCT       INTEGER,
    PROD_RATE_SPREAD DECIMAL(8, 4)
);

create unique index IXU_DEP_062
    on DEP_PROD_SCALE (VALIDITY_DATE, PROD_CATEGORY, ID_PRODUCT);

