create table DEP_HISTORY
(
    ACCOUNT_NUMBER     DECIMAL(11),
    TUN_INTERNAL_SN    SMALLINT,
    TRX_USR_SN         INTEGER,
    TRX_USR            CHAR(8),
    TRX_UNIT           INTEGER,
    TRX_DATE           DATE,
    O_CR_INTR_RATE_SPR DECIMAL(8, 4),
    O_DB_INTR_RATE_SPR DECIMAL(8, 4),
    I_DB_INTR_RATE_SPR DECIMAL(8, 4),
    I_CR_INTR_RATE_SPR DECIMAL(8, 4),
    I_ENC_TOLERANCE    DECIMAL(15, 2),
    O_ENC_TOLERANCE    DECIMAL(15, 2),
    I_TEMP_EXCESS      DECIMAL(15, 2),
    O_TEMP_EXCESS      DECIMAL(15, 2),
    O_ACCOUNT_LIMIT    DECIMAL(15, 2),
    I_ACCOUNT_LIMIT    DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    O_DB_INT_RT_SP_IND CHAR(1),
    I_DB_INT_RT_SP_IND CHAR(1),
    I_CR_INT_RT_SP_IND CHAR(1),
    O_CR_INT_RT_SP_IND CHAR(1),
    I_STATUS           CHAR(1),
    O_STATUS           CHAR(1),
    O_EFFECTIVE_DATE   DATE,
    I_EXPIRY_DATE      DATE,
    O_EXPIRY_DATE      DATE
);

create unique index IXU_DEP_020
    on DEP_HISTORY (ACCOUNT_NUMBER, TUN_INTERNAL_SN, TRX_USR_SN, TRX_USR, TRX_UNIT, TRX_DATE);

