create table DEP_AGREEMENT
(
    AGREEMENT_NUMBER   DECIMAL(10) not null
        constraint IXU_DEF_128
            primary key,
    C_DIGIT            SMALLINT,
    AMENDMENT_COUNT    SMALLINT,
    FK_CUST_ADDRESSSER SMALLINT,
    FK_CURRENCYID_CURR INTEGER,
    FK_UNITCODE        INTEGER,
    FK_CUST_ADDRESSFK  INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    UTILISED_LIMIT     DECIMAL(15, 2),
    PREV_AGREEM_LIMIT  DECIMAL(15, 2),
    AGREEMENT_LIMIT    DECIMAL(15, 2),
    APPROVAL_DATE      DATE,
    ISSUE_DATE         DATE,
    TIMESTMP           TIMESTAMP(6),
    LAST_UPDATE_DATE   DATE,
    CURRENCY_INDICATOR CHAR(1),
    ENTRY_STATUS       CHAR(1),
    AGREEMENT_TYPE     CHAR(2),
    OLD_AGREEMENT_NUM  CHAR(8),
    APPROVAL_NUMBER    CHAR(12),
    ENTRY_COMMENTS     CHAR(40)
);

