create table DEP_CLASS_GL
(
    LOAN_STATUS        CHAR(1) not null,
    TIMESTMP           TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    CR_INT_ACCR_GL_LVL CHAR(1),
    CR_INT_ACCR_GL_ACC CHAR(21),
    DR_INT_ACCR_GL_LVL CHAR(1),
    DR_INT_ACCR_GL_ACC CHAR(21),
    CR_INT_GL_ACC_LVL  CHAR(1),
    CR_INT_GL_ACC      CHAR(21),
    DR_INT_GL_ACC_LVL  CHAR(1),
    DR_INT_GL_ACC      CHAR(21),
    CR_CNTR_GL_ACC_LVL CHAR(1),
    CR_CNTR_GL_ACC     CHAR(21),
    DR_CNTR_GL_ACC_LVL CHAR(1),
    DR_CNTR_GL_ACC     CHAR(21),
    FK_PRODUCTID_PRODU INTEGER not null,
    FK_GENERIC_DETAFK  CHAR(5) not null,
    FK_GENERIC_DETASER INTEGER not null,
    constraint I0000009
        primary key (FK_GENERIC_DETASER, FK_GENERIC_DETAFK, FK_PRODUCTID_PRODU, LOAN_STATUS)
);

