create table DHSSE_INTERFACE
(
    PROGRAM_ID          CHAR(5)  not null,
    ACH_SETTLE_DATE     CHAR(8)  not null,
    CUTOFF_SN           SMALLINT not null,
    IDENTIFIER          INTEGER  not null,
    ACH_BANK_CODE       CHAR(3)  not null,
    PAY_BRANCH          CHAR(6),
    PAY_ACCNO           CHAR(23),
    IBAN_CD             SMALLINT,
    IBAN_CNTRY          CHAR(2),
    IBAN_DIGITS         CHAR(4),
    CHQ_NO              CHAR(20),
    AMOUNT              CHAR(15),
    ACH_CURRENCY        CHAR(5)  not null,
    TRAN_DATE           CHAR(8),
    ISS_DATE            CHAR(8),
    BUY_BRANCH          CHAR(6),
    SETTLE_REF          CHAR(1),
    ACC_CODE            CHAR(3),
    TRAN_CODE           CHAR(8),
    DHSSE_REF           CHAR(7),
    FILENAME            CHAR(30) not null,
    FILE_SN             SMALLINT,
    FILE_DATA           VARCHAR(300),
    IMAGE_PATH          VARCHAR(200),
    PROCESSED           CHAR(1),
    PROCESSING_ID       DECIMAL(10),
    IMG_PROCESSED       CHAR(1),
    COLLECTION_DETAILS  CHAR(40),
    CODELINE            CHAR(60),
    BILL_SERIAL_NUM     DECIMAL(10),
    SETTLEMENT_PROCESS  CHAR(1),
    GROUP_ID            INTEGER default 0,
    XML_FILE_NAME       CHAR(100),
    IMAGE_OFFSET_FRONT  DECIMAL(10),
    IMAGE_DATA_LENGTH_F DECIMAL(10),
    IMAGE_OFFSET_BACK   DECIMAL(10),
    IMAGE_DATA_LENGTH_B DECIMAL(10),
    XML_FILE_ID         DECIMAL(15),
    constraint PK_DHSSE_INTERF
        primary key (FILENAME, ACH_SETTLE_DATE, IDENTIFIER, CUTOFF_SN, PROGRAM_ID)
);

comment on table DHSSE_INTERFACE is 'DHSSE INPUT/OUTPUT TEMPORARY FILE.IT IS DETAIL RECORD OF DHSSE_CTRL_TOT_FOUTGING CHEQUES :   PROFITS DATA THAT MUST BE FILE-TRANSFERED TO     DIASCHEQUE.INCOMING DIASCHEQUES :  DIASCHEQUE DATA THAT MUST BE LOADED FROM    FILE-TRANSFERS OF DIASCHEQUE TO U';

comment on column DHSSE_INTERFACE.PROGRAM_ID is 'BATCH PROGRAM ID. EVERY BATCH PROCESS MUST RUN FOR ITS OWN SPECIFIC DATA. e.g. PROCESS 73621 MUST FIND RECORDS WITH PROGRAM ID = 73621.';

comment on column DHSSE_INTERFACE.ACH_SETTLE_DATE is 'BUY DATE FOR THE CHEQUES FOUND IN DHSSE_INTERFACE TABLE 1. EQUALS TO THE DATE OF THE : INCOMING, OUTGOING, INCOMING-REJECTIONS, OUTGOING-REJECTIONS DIASCHEQUES. IT REFERS TO THE WHOLE FILE TRANSFERED THRU DIASCHEQUES2. IT IS ALSO THE 1ST FINANCIAL SETTLE';

comment on column DHSSE_INTERFACE.CUTOFF_SN is 'OUTGOING CHEQUES : IT IS INCREASED BY ONE EVERY TIME THE 73611 PROCESS RUNS ON THE SAME ACH_SETTLE_DATE IF THE CURRENT BATCH_CONTROL STATUS IS ''COMPLETED SUCCESFULLY'' (i.e. PREVIOUS CUTOFF HAS BEEN COMPLETED)IN ANY OTHER CASE :IT IS SET TO 0.';

comment on column DHSSE_INTERFACE.IDENTIFIER is 'A/A : UNIQUE NUMBER FOR EVERY RECORD';

comment on column DHSSE_INTERFACE.ACH_BANK_CODE is 'CASE OF THE CHEQUES FOUND IN DHSSE_INTERFACECASE OUTGOING CHEQUESPAY_BANKCASE INCOMING CHEQUESBUY_BANK';

comment on column DHSSE_INTERFACE.PAY_BRANCH is 'MAX ALLOWED BY BBAN (see COLLABORATION BANKS)';

comment on column DHSSE_INTERFACE.PAY_ACCNO is 'ACCOUNT NUMBER FOR THE CHEQUE PAID BY PAY_BANK';

comment on column DHSSE_INTERFACE.IBAN_CD is 'IBAN account number Check Digit';

comment on column DHSSE_INTERFACE.IBAN_CNTRY is 'IBAN Country Code (e.g. "GR")';

comment on column DHSSE_INTERFACE.IBAN_DIGITS is 'IBAN DIGITS  .     ,      4   CODE LINE       (  ).         ';

comment on column DHSSE_INTERFACE.CHQ_NO is 'CHEQUE NUMBER';

comment on column DHSSE_INTERFACE.ACH_CURRENCY is 'CURRENCY CODE';

comment on column DHSSE_INTERFACE.TRAN_DATE is 'TRANSACTION DATE. THE DATE THE CHEQUE WAS RECEIVED';

comment on column DHSSE_INTERFACE.ISS_DATE is 'ISSUE DATE';

comment on column DHSSE_INTERFACE.BUY_BRANCH is 'UNIT OF THE PAY BANK MAX ALLOWED BY BBAN (see COLLABORATION BANKS)';

comment on column DHSSE_INTERFACE.SETTLE_REF is 'IT IS AN INDICATOR SHOWING THE FINANCIAL SETTLEMENT DATE FOR EACH CHEQUE FOUND IN DHSSE_INTERFACE TABLE.IF EQUALS 1 THEN SETTLE DATE IS THE BUY DATE OF THE CHEQUE OR THE DATE THE BOUGHT CHEQUES WERE SEND TO DIASCHEQUE. IT IS THE DHSSE_CTRL_TOT_F.ACH_SETT';

comment on column DHSSE_INTERFACE.ACC_CODE is 'REJECTION CODE USED BY DIASCHEQUE TO IDENTIFY THE REFUSAL OF A CHEQUE PAYMENT BY PAY_BANK';

comment on column DHSSE_INTERFACE.TRAN_CODE is 'ITS IS A NUMBER THAT IDENTIFIES UNIQUELLY EVERY CHEQUES_FOR_COLLECTION THAT IS SEND TO DIASCHEQUE FOR A SPECIFIC SEND DATE TO DIASCHEQUE. THIS DATA IS TRANSFERED TO AND FROM DIAS UNCHANGED. IT IS A NUMBER THAT HAS MEANING ONLY TO PROFITS.';

comment on column DHSSE_INTERFACE.DHSSE_REF is 'DATA IN THIS FIELD IS SET ONLY BY DIASCHEQUE.';

comment on column DHSSE_INTERFACE.FILENAME is 'THE FILE FROM WHICH THE ENTRY HAS BEEN EXTRACTED.';

comment on column DHSSE_INTERFACE.PROCESSING_ID is 'Unique processing id. Gets its value from COUNTER DCHQS.';

