create table DHSSE_CTRL_TOT_G
(
    PROGRAM_ID      CHAR(5),
    ACH_BANK_CODE   CHAR(3),
    ACH_CURRENCY    CHAR(5),
    CUTOFF_SN       SMALLINT,
    ACH_SETTLE_DATE CHAR(8),
    ACH_CTRL_NUM    CHAR(6),
    ACH_CTRL_AMOUNT CHAR(15)
);

create unique index IXU_DHS_000
    on DHSSE_CTRL_TOT_G (PROGRAM_ID, ACH_BANK_CODE, ACH_CURRENCY, CUTOFF_SN, ACH_SETTLE_DATE);

