create table DIAS_POSITION
(
    CLEARING_DATE   DATE,
    FILE_ID         INTEGER,
    LINE_SN         INTEGER,
    RECORD_TYPE     SMALLINT,
    RECORD_CODE     SMALLINT,
    BANK_CODE       SMALLINT,
    ORDER_ITEMS     INTEGER,
    RETURN_ITEMS    INTEGER,
    TOT_AMT_RECEIVE DECIMAL(15, 2),
    RETURN_VALUE    DECIMAL(15, 2),
    TOT_AMOUNT_PAY  DECIMAL(15, 2),
    ORDER_VALUE     DECIMAL(15, 2),
    TMSTAMP         TIMESTAMP(6)
);

create unique index IXU_DIA_013
    on DIAS_POSITION (CLEARING_DATE, FILE_ID, LINE_SN);

