create table DIAS_OUTGOING_ORD
(
    REFERENCE_NUMBER       DECIMAL(15) not null
        constraint IXU_DIA_003
            primary key,
    FILE_NUMBER            SMALLINT,
    FK_PAY_UNIT            INTEGER,
    FK_RECV_BANK           INTEGER,
    FK_SEND_BANK           INTEGER,
    FK_SEND_UNIT           INTEGER,
    FK_CURRENCYID_CURR     INTEGER,
    FK_PRODUCTID_PRODU     INTEGER,
    FK_ISSUE_CUST          INTEGER,
    FK_BENEF_CUST          INTEGER,
    FK_DEBIT_DEPOS_ACC     DECIMAL(11),
    CHARGES_ACCOUNT        DECIMAL(11),
    BENEFICIARY_COMMISSION DECIMAL(15, 2),
    PREV_REFER_NUMBER      DECIMAL(15, 2),
    TRANS_AMNT             DECIMAL(15, 2),
    TRANS_COMM             DECIMAL(15, 2),
    RECV_TRANS_COMM        DECIMAL(15, 2),
    FILE_DATE              DATE,
    LST_UPDATE_DATE        DATE,
    SEND_MOVE              DATE,
    SEND_VALUE             DATE,
    DIAS_VALUE             DATE,
    TMSTAMP                TIMESTAMP(6),
    ORDER_ORIGIN           CHAR(1),
    ORDER_ID_TYPE          CHAR(1),
    ENTRY_STATUS           CHAR(1),
    TRANS_COMM_SIGN        CHAR(1),
    BENEF_ORIGIN           CHAR(1),
    ORIGIN_CODE            CHAR(2),
    SERVICE_CODE           CHAR(2),
    REJECT_CODE            CHAR(3),
    DETAIL_OF_CHARGE       CHAR(3),
    TRANS_TYPE_CODE        CHAR(3),
    TRANS_CODE             CHAR(3),
    RECEIVER_DIAS_UNIT     CHAR(4),
    INSTIT_FUNC_CODE       CHAR(4),
    BENEF_ZIP_CODE         CHAR(5),
    ORDER_ZIP_CODE         CHAR(5),
    FILE_NAME              CHAR(8),
    BENEF_PHONE2           CHAR(10),
    BENEF_PHONE1           CHAR(10),
    ORDER_PHONE2           CHAR(10),
    ORDER_PHONE1           CHAR(10),
    EXCHANGE_RATE          CHAR(12),
    SENDER_REF_NUM         CHAR(16),
    DIAS_REFERENCE         CHAR(17),
    TRANS_AMOUNT_CUR       CHAR(18),
    ORDER_CITY             CHAR(18),
    BENEF_CITY             CHAR(18),
    ORDER_TAX_REG_NO       CHAR(20),
    ORDER_ID_NUM           CHAR(20),
    ORDER_ADDRESS2         CHAR(24),
    BENEF_ADDRESS2         CHAR(24),
    BENEF_ACCOUNT          CHAR(27),
    CR_ACCOUNT_DTL         CHAR(34),
    INFORMATION5           CHAR(35),
    INFORMATION6           CHAR(35),
    INFORMATION4           CHAR(35),
    INFORMATION3           CHAR(35),
    INFORMATION2           CHAR(35),
    INFORMATION1           CHAR(35),
    BENEF_ADDRESS1         CHAR(35),
    BENEF_CUST_NAME        CHAR(35),
    ORDER_ADDRESS1         CHAR(35),
    ORDER_CUST_NAME        CHAR(35),
    JUSTIFIC4              CHAR(35),
    JUSTIFIC3              CHAR(35),
    JUSTIFIC1              CHAR(35),
    JUSTIFIC2              CHAR(35),
    REGULATORY_REP         CHAR(35),
    ENTRY_COMMENTS         CHAR(40),
    ORDER_ISSUE_AUTH       CHAR(40),
    SENDER_CHARGES         CHAR(54),
    FREE_TEXT              CHAR(154),
    INTERM_INSTITUTION     CHAR(175),
    ACC_WITH_INSTITUT      CHAR(175),
    ORDER_INSTITUTION      CHAR(175),
    INSTRUCTION_CODE       CHAR(175)
);

