create table DIAS_COMM_TOTALS
(
    PAYMENT_CATEGORY   SMALLINT not null,
    TRX_DATE           DATE     not null,
    OUT_ORDER_ITEMS    INTEGER,
    OUT_ORDER_AMOUNTS  DECIMAL(15, 2),
    OUT_ORDER_COMM     DECIMAL(15, 2),
    OUT_RETURN_ITEMS   INTEGER,
    OUT_RETURN_AMOUNTS DECIMAL(15, 2),
    OUT_RETURN_COMM    DECIMAL(15, 2),
    IN_ORDER_ITEMS     INTEGER,
    IN_ORDER_AMOUNTS   DECIMAL(15, 2),
    IN_ORDER_COMM      DECIMAL(15, 2),
    IN_RETURN_ITEMS    INTEGER,
    IN_RETURN_AMOUNTS  DECIMAL(15, 2),
    IN_RETURN_COMM     DECIMAL(15, 2),
    DIAS_COMM          DECIMAL(15, 2),
    BANK_POSITION      DECIMAL(15, 2),
    FK_COLLAB_BANK     INTEGER  not null,
    constraint PKDIASCO
        primary key (FK_COLLAB_BANK, PAYMENT_CATEGORY, TRX_DATE)
);

