create table DIAS_TRAN_FIELDS
(
    FILE_ID            SMALLINT,
    RECORD_TYPE        CHAR(1),
    POSITION_IN_LINE   SMALLINT,
    AMOUNT_DECIMALS    SMALLINT,
    FIELD_LENGTH       SMALLINT,
    STARTING_POSITION  SMALLINT,
    FIELD_TYPE         CHAR(1),
    CHECK_BEN_RESIDENT CHAR(1),
    CHECK_ACCNT_NO_CD  CHAR(1),
    OPTIONALITY        CHAR(1),
    FIELD_FORMAT       CHAR(12),
    FIELD_NAME         VARCHAR(40)
);

create unique index IXU_DIA_012
    on DIAS_TRAN_FIELDS (FILE_ID, RECORD_TYPE, POSITION_IN_LINE);

