create table DISTR_CHANNEL
(
    ID_CHANNEL        INTEGER,
    FK_DISTR_CHANNEID INTEGER,
    TMSTAMP           TIMESTAMP(6),
    CHANNEL_IND       CHAR(1),
    CHANNEL_STATUS    CHAR(1),
    SHORT_DESCR       CHAR(5),
    DESCRIPTION       VARCHAR(40),
    FK_GH_WSICH       CHAR(5),
    FK_GD_WSICH       INTEGER,
    PASS_ENCRYTPED    CHAR(128),
    PASS_EXPIRY_DT    DATE,
    PASS_TRIES        SMALLINT,
    PASS_TRIES_USED   SMALLINT,
    PASS_STATUS       CHAR(1),
    PASS_TIMEOUT      SMALLINT,
    CREATE_UNIT       INTEGER,
    CREATE_USER       CHAR(8),
    CREATE_DATE       DATE,
    CREATE_TMSTAMP    TIMESTAMP(6),
    UPDATE_UNIT       INTEGER,
    UPDATE_USER       CHAR(8),
    UPDATE_DATE       DATE,
    UPDATE_TMSTAMP    TIMESTAMP(6),
    DESCR_ANALYSIS    LONG VARCHAR(32700),
    LOG_MESSAGE       CHAR(1),
    USE_CHANNEL_USR   CHAR(1),
    UNBIND_SECONDS    INTEGER,
    ACCESS_STATUS     CHAR(2),
    E_COUNT           INTEGER,
    AGENT_LINK        CHAR(1),
    USER_CONCURRENT   CHAR(1),
    USER_STATISTICS   CHAR(1),
    LOG_SYSTEM_ERROR  CHAR(1),
    LOG_LOGICAL_ERROR CHAR(1)
);

create unique index IXU_DIS_002
    on DISTR_CHANNEL (ID_CHANNEL);

