create table DOCUMENT_FIELDS
(
    FILE_NAME     CHAR(24),
    SERIAL_NUMBER SMALLINT,
    FIELD_NAME    CHAR(20),
    FIELD_INDEX   SMALLINT,
    FIELD_TYPE    CHAR(12),
    FIELD_TEXT    CHAR(100)
);

create unique index IXU_DOC_006
    on DOCUMENT_FIELDS (FILE_NAME, SERIAL_NUMBER, FIELD_NAME);

