create table DOCUMENT_TEMPLATE
(
    FKGH_HAS_LANGUAGE  CHAR(5),
    FKGD_HAS_LANGUAGE  INTEGER,
    PRFT_SYSTEM        SMALLINT,
    CODE               INTEGER,
    FKGD_HAS_TMPL_TYPE INTEGER,
    CREATION_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    SWIFT_IND          CHAR(1),
    MS_DOC_TYPE        CHAR(1),
    FKGH_HAS_TMPL_TYPE CHAR(5),
    FK_USRCODE         CHAR(8),
    FILE_NAME          CHAR(20),
    DESCRIPTION        CHAR(40)
);

create unique index IXU_DOC_001
    on DOCUMENT_TEMPLATE (FKGH_HAS_LANGUAGE, FKGD_HAS_LANGUAGE, PRFT_SYSTEM, CODE);

