create table DP_ACC_MOVE_REC
(
    TUN_INTERNAL_SN SMALLINT,
    TRX_USR_SN      INTEGER,
    TRX_USER        CHAR(8),
    TRX_DATE        DATE,
    TRX_UNIT        INTEGER,
    C_DIGIT         SMALLINT,
    P_N128_INTEREST INTEGER,
    O_N128_INTEREST INTEGER,
    P_XS_INTEREST   INTEGER,
    O_XS_INTEREST   INTEGER,
    P_CR_INTEREST   INTEGER,
    O_PRODUCT       INTEGER,
    P_PRODUCT       INTEGER,
    O_DB_INTEREST   INTEGER,
    P_DB_INTEREST   INTEGER,
    O_CR_INTEREST   INTEGER,
    ACCOUNT_NUMBER  DECIMAL(11),
    TMSTAMP         DATE
);

create unique index IXU_DP__005
    on DP_ACC_MOVE_REC (TUN_INTERNAL_SN, TRX_USR_SN, TRX_USER, TRX_DATE, TRX_UNIT);

