create table DP_HIST_INTER_RATE
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    EFFECTIVE_DATE     DATE,
    CR_INTER_RATE_SPR  DECIMAL(8, 4),
    DB_INTER_RATE_SPR  DECIMAL(8, 4),
    ACCOUNT_LIMIT      DECIMAL(15, 2),
    TEMPORARY_EXCESS   DECIMAL(15, 2),
    ENCROACH_TOLERANCE DECIMAL(15, 2),
    CR_INT_RT_SPRD_IND CHAR(1),
    DB_INT_RT_SPRD_IND CHAR(1)
);

create unique index IXU_DP__004
    on DP_HIST_INTER_RATE (FK_DEPOSIT_ACCOACC, EFFECTIVE_DATE);

