create table DP_PSB_LOST_HIST
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    PSB_LOST_SN        INTEGER,
    PSB_PENDING_LINES  SMALLINT,
    PSB_LAST_PRINT_LN  SMALLINT,
    TRX_UNIT           INTEGER,
    TRX_USR_SN         INTEGER,
    BOOK_BALANCE       DECIMAL(15, 2),
    PSB_LAST_BALANCE   DECIMAL(15, 2),
    TIMESTMP           TIMESTAMP(6),
    TRX_DATE           DATE,
    TRX_USR            CHAR(8),
    PSB_LOST_COMMENT   VARCHAR(40)
);

create unique index IXU_DP__008
    on DP_PSB_LOST_HIST (FK_DEPOSIT_ACCOACC, PSB_LOST_SN);

