create table DP_TRX_SPECIAL_AGR
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    FK_TRANSACTION0ID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    PRICING_SN         SMALLINT,
    VALUE_DATE_SPREAD  SMALLINT,
    AVAIL_DATE_SPREAD  SMALLINT,
    COMMISS_DISCOUNT   DECIMAL(8, 4),
    EXPENSE_DISCOUNT   DECIMAL(8, 4),
    TIMESTMP           TIMESTAMP(6),
    STAMP_CHARGE_FLAG  CHAR(1),
    FK_COMMISSION      INTEGER,
    FK_EXPENSE         INTEGER,
    FK_TAX             INTEGER
);

create unique index IXU_DP__009
    on DP_TRX_SPECIAL_AGR (FK_DEPOSIT_ACCOACC, FK_TRANSACTION0ID, FK_JUSTIFICID_JUST, PRICING_SN);

