create table EOM_PRFT_TRANSACT
(
    EOM_DATE         DATE,
    ID_TRANSACT      INTEGER,
    PRFT_SYSTEM      INTEGER,
    TMSTAMP          DATE,
    DISABLE_BOP      CHAR(1),
    ENTRY_STATUS     CHAR(1),
    REVERSIBLE       CHAR(1),
    ACCOUNTABLE      CHAR(1),
    DEP_ACC_STATUS0  CHAR(1),
    DEP_ACC_STATUS1  CHAR(1),
    DEP_ACC_STATUS5  CHAR(1),
    DEP_ACC_STATUS4  CHAR(1),
    DEP_ACC_STATUS3  CHAR(1),
    DEP_ACC_STATUS2  CHAR(1),
    DEP_ACC_STATUS6  CHAR(1),
    SWIFT_SHORT_DESC CHAR(3),
    SHORT_DESCR      CHAR(5),
    ENGL_DESCRIPTION CHAR(40),
    DESCRIPTION      VARCHAR(40),
    FK_WINDOW_CODE   CHAR(8),
    FK_WINDOW_ACTION CHAR(8)
);

create unique index EOM_PRFT_TRANSACT_PK
    on EOM_PRFT_TRANSACT (EOM_DATE, ID_TRANSACT);

