create table EOM_BRANCH_PORTFOLIO
(
    EOM_DATE       DATE,
    BRANCH         INTEGER,
    PORTFOLIO_CODE INTEGER,
    ENTRY_STATUS   CHAR(1),
    FK_USRCODE     CHAR(8),
    DESCRIPTION    CHAR(40)
);

create unique index EOM_BRANCH_PORTFOLIO_PK
    on EOM_BRANCH_PORTFOLIO (EOM_DATE, BRANCH, PORTFOLIO_CODE);

