create table EOM_IPS_MESSAGE_HDR
(
    EOM_DATE                    DATE,
    ORDER_CODE                  VARCHAR(20)    not null,
    FK_ORDER_CODE               VARCHAR(20),
    ORDER_STATUS                CHAR(1),
    ORDER_AMOUNT                DECIMAL(15, 2) not null,
    ORDER_TYPE                  VARCHAR(3)     not null,
    ORDER_TIMESTAMP             TIMESTAMP(6),
    ISSUER_CUST_ID              INTEGER,
    BENEF_CUST_ID               INTEGER,
    SERVICE_PRODUCT             INTEGER        not null,
    JUSTIFIC_ID                 INTEGER        not null,
    CREDIT_BIC_ADDRESS          VARCHAR(40),
    DEBIT_BIC_ADDRESS           VARCHAR(40),
    PRFT_ACCOUNT                VARCHAR(40),
    ISSUER_IBAN_ACC             VARCHAR(37),
    BENEF_IBAN_ACC              VARCHAR(37),
    GENERIC_ACCOUNT             VARCHAR(40),
    TRX_CODE                    INTEGER        not null,
    TRX_DATE                    DATE,
    COMPLETE_MESSAGE            VARCHAR(2048),
    REJECTION_CODE              VARCHAR(40),
    EXTERNAL_ID_REF             VARCHAR(40),
    ORDER_FILENAME              VARCHAR(50),
    CHARGES_JUSTIFIC            INTEGER,
    ISSUER_FULLNAME             VARCHAR(100),
    BENEF_FULLNAME              VARCHAR(100),
    COMBO_JUSTIFIC              INTEGER,
    COMBO_TRANSACTION           INTEGER,
    CHARGES_ACCOUNT             VARCHAR(40),
    ORDER_CURRENCY              INTEGER,
    ISSUER_PROD_DATE            DATE,
    EXPENSE_JUSTIFIC            INTEGER,
    EXPENSE_PROD_DATE           DATE,
    ORDER_FILE_LINE             INTEGER,
    ISSUER_RESIDENT             VARCHAR(1),
    BENEF_RESIDENT              VARCHAR(1),
    COMMENTS                    VARCHAR(250),
    EXECUTION_SN                SMALLINT,
    TRX_UNIT                    INTEGER,
    ORDER_EXPENSE               DECIMAL(15, 2) not null,
    ORDER_COMMISSION            DECIMAL(15, 2) not null,
    COLLECTED_AMOUNT            DECIMAL(15, 2) not null,
    SETTLEMENT_AMNT             DECIMAL(15, 2) not null,
    PROCESS_RESULTS             VARCHAR(255),
    FILE_BIC_ADDRESS            VARCHAR(12),
    PRFT_ACC_SYSTEM             SMALLINT,
    REMITTANCE_INFO             VARCHAR(140),
    CLEARING_SYSTEM             CHAR(35),
    PROCESS_TYPE                CHAR(10),
    ORDER_GROUP_1               CHAR(10),
    ORDER_GROUP_2               CHAR(10),
    INSTRUCTION_REF_ID          VARCHAR(40),
    CHARGES_ACC_SYSTEM          SMALLINT,
    CHARGES_DISCOUNT            DECIMAL(8, 4),
    COMMISSION_DISCOUNT         DECIMAL(8, 4),
    TRANSIT_CUSTOMER            CHAR(1),
    NEW_ORDER_CODE              CHAR(20),
    DEST_BIC_ADDRESS            VARCHAR(11),
    DEST_COUNTRY                VARCHAR(2),
    SRC_BIC_ADDRESS             VARCHAR(11),
    SRC_COUNTRY                 VARCHAR(2),
    JUSTIFIC_DESCR              VARCHAR(40),
    POS_RETURN_FLG              VARCHAR(2),
    POS_PROD_CODE               VARCHAR(150),
    CHARGE_BEARER               VARCHAR(150),
    CR_PRFT_ACCOUNT             VARCHAR(40),
    DR_PRFT_ACCOUNT             VARCHAR(40),
    ACCOUNT_NUMBER              CHAR(40),
    ACCOUNT_CD                  SMALLINT,
    PRFT_SYSTEM                 SMALLINT,
    DEP_ACC_NUMBER              DECIMAL(11),
    MOVEMENT_CURRENCY           INTEGER,
    PRODUCT_DESC                VARCHAR(40),
    DEPPRODUCT_DESC             VARCHAR(40),
    MAINBENEF_CUST_ID           INTEGER,
    MAINBENEF_C_DIGIT           SMALLINT,
    MAINBENEF_SURNAME           CHAR(70),
    MAINBENEF_FIRST_NAME        CHAR(20),
    MAINBENEF_FATHER_NAME       VARCHAR(20),
    MAINBENEF_FK_BANKEMPLOYEEID CHAR(8),
    CUST_CUST_ID                INTEGER,
    CUST_C_DIGIT                SMALLINT,
    CUST_SURNAME                CHAR(70),
    CUST_FIRST_NAME             CHAR(20),
    CUST_FATHER_NAME            VARCHAR(20),
    CUST_FK_BANKEMPLOYEEID      CHAR(8)
);

create unique index EOM_IPS_MESSAGE_HDR_PK
    on EOM_IPS_MESSAGE_HDR (EOM_DATE, ORDER_CODE);

