create table EOM_USER
(
    EOM_DATE                 DATE,
    CODE                     CHAR(8),
    GL_LEVEL                 SMALLINT,
    ACCOUNTING_ORIG          SMALLINT,
    FK_GENERIC_DETASER       INTEGER,
    FK_DISTR_CHANNEL         INTEGER,
    OFFSIDE_UNIT             INTEGER,
    AK_SELLER_CODE           INTEGER,
    DEPT_SN                  INTEGER,
    FK_UNITCODE              INTEGER,
    BOUND_TO_CUST_ID         INTEGER,
    TMSTAMP                  DATE,
    DEACTIVATION_DATE        DATE,
    ACTIVATION_DATE          DATE,
    BOUND_AT                 TIMESTAMP(6),
    PASS_TMSTAMP             TIMESTAMP(6),
    USR_BTCH_EXP_FLG         CHAR(1),
    NEW_PSWD_PLCY_FLG        CHAR(1),
    RM_IND                   CHAR(1),
    VIRTUAL_USER             CHAR(1),
    NON_HOUSE_UNIT           CHAR(1),
    ATM_USER                 CHAR(1),
    ENTRY_STATUS             CHAR(1),
    FK_GENERIC_DETAFK        CHAR(5),
    FK_BANKEMPLOYEEID        CHAR(8),
    FKUCATEG_OWNS_AS_3       CHAR(8),
    SUBSTITUTE_CODE          CHAR(8),
    FKUCATEG_OWNS_MAIN       CHAR(8),
    FKUCATEG_OWNS_AS_2       CHAR(8),
    PASSWORD                 CHAR(26),
    EMAIL                    CHAR(40),
    PASS_DIGEST              CHAR(64),
    PERM_UNITS               SMALLINT,
    LIMITED_ACCESS           CHAR(1),
    START_TIME               DATE,
    END_TIME                 DATE,
    SUN                      CHAR(1),
    MON                      CHAR(1),
    TUE                      CHAR(1),
    WED                      CHAR(1),
    THU                      CHAR(1),
    FRI                      CHAR(1),
    SAT                      CHAR(1),
    BATCH_USER               CHAR(1),
    WSI_CREATE_TMSTAMP       TIMESTAMP(6),
    WSI_CHANNEL_ID           INTEGER,
    WSI_CHANNEL_USER         VARCHAR(40),
    WSI_USER_SN              INTEGER,
    WSI_CURR_TRX_DATE        DATE,
    WORK_PHONE               VARCHAR(20),
    MOBILE_PHONE             VARCHAR(20),
    TEMP_PSWD_DT             DATE,
    TASKS_NO                 INTEGER,
    WFL_TASKS_NO             INTEGER,
    BANKEMPLOYEE_ID          VARCHAR(8),
    BANKEMPLOYEE_CARD_ID     VARCHAR(8),
    BANKEMPLOYEE_STAFF_NO    VARCHAR(8),
    BANKEMPLOYEE_FATHER_NAME VARCHAR(40),
    BANKEMPLOYEE_FIRST_NAME  VARCHAR(20),
    BANKEMPLOYEE_LAST_NAME   VARCHAR(20),
    BANKEMPLOYEE_SEX         VARCHAR(1)
);

create unique index EOM_USER_PK
    on EOM_USER (CODE, EOM_DATE);

