create table EOM_PRODUCT
(
    EOM_DATE       DATE,
    ID_PRODUCT     INTEGER,
    BLOCKED_PERCNT DECIMAL(8, 4),
    TMSTAMP        DATE,
    LAST_MODIFIED  DATE,
    PRD_EXP_DT     DATE,
    VALIDITY_DATE  DATE,
    INTER_BEARING  CHAR(1),
    INVEST_FLAG    CHAR(1),
    ENTRY_STATUS   CHAR(1),
    ENTERPRISE     CHAR(1),
    PRODUCT_TYPE   CHAR(1),
    DESCRIPTION    VARCHAR(40),
    COMMENT1       VARCHAR(75)
);

