create table EOM_COMPANY_SHARES
(
    EOM_DATE          DATE,
    MEMBER_ID         DECIMAL(10),
    MEMBER_STATUS     SMALLINT,
    ASSEMBLY_NUMBER   SMALLINT,
    COUNCIL_NUMBER    SMALLINT,
    MONITORING_UNIT   INTEGER,
    CUSTOMER_ID       INTEGER,
    SHARES_TOTAL      DECIMAL(10),
    DELETION_DATE     DATE,
    CREATION_DATE     DATE,
    UPDATED_DATE      DATE,
    CREATED_DATE      DATE,
    COUNCIL_DATE      DATE,
    ASSEMBLY_DATE     DATE,
    UPDATED_TIMESTAMP TIMESTAMP(6),
    UPDATED_BY        CHAR(8),
    CREATED_BY        CHAR(8),
    REG_ACCOUNT       CHAR(40),
    DIVIDENT_ACCOUNT  CHAR(40)
);

create unique index EOM_COMPANY_SHARES_PK
    on EOM_COMPANY_SHARES (EOM_DATE, MEMBER_ID);

