create table EOM_CUST_CARDS
(
    EOM_DATE            DATE,
    CARD_NO             CHAR(16),
    ACCOUNT_NO          VARCHAR(20),
    PROFITS_ACCOUNT_NU  CHAR(40) not null,
    PRF_AC_PRFT_SYSTEM  SMALLINT not null,
    ACCOUNT_CD          SMALLINT,
    ACCOUNT_TYPE        SMALLINT,
    CUST_ID             INTEGER,
    C_DIGIT             SMALLINT,
    SURNAME             CHAR(70),
    FIRST_NAME          CHAR(20),
    CARD_TMSTAMP        DATE,
    CARD_START_DATE     DATE,
    CARD_END_DATE       DATE,
    CARD_ENTRY_STATUS   CHAR(1),
    CARD_COMNTS         VARCHAR(30),
    FK_GENERIC_DETAFK   CHAR(5),
    FK_GENERIC_DETASER  INTEGER,
    CARD_RENEWAL        CHAR(1),
    FK_DISABLE_DETAFK   CHAR(5),
    FK_DISABLE_DETASER  INTEGER,
    DISABLE_REASON_COM  CHAR(80),
    TMSTAMP             DATE,
    START_DATE          DATE,
    END_DATE            DATE,
    ENTRY_STATUS        CHAR(1),
    ACC_PRODUCT_DESCR   VARCHAR(40),
    ACC_PRODUCT_ID      INTEGER,
    ACC_MONITORING_UNIT INTEGER
);

create unique index EOM_CUST_CARDS_PK
    on EOM_CUST_CARDS (EOM_DATE, CARD_NO, ACCOUNT_NO, PROFITS_ACCOUNT_NU, PRF_AC_PRFT_SYSTEM);

