create table ETL_TRANSACTION_DIARY
(
    TMSTAMP               TIMESTAMP(6) not null,
    TRX_UNIT              INTEGER      not null,
    TRX_DATE              DATE         not null,
    TRX_USR               CHAR(8)      not null,
    TRX_USR_SN            INTEGER      not null,
    TUN_INTERNAL_SN       SMALLINT     not null,
    INTERNAL_SN           INTEGER      not null,
    FINANCIAL_IND         INTEGER,
    TRX_CODE              INTEGER,
    TRX_JUSTIFIC          INTEGER,
    ID_CURRENCY           INTEGER,
    ID_CURR_TARGET        INTEGER,
    CASH_CR               DECIMAL(15, 2),
    CASH_DB               DECIMAL(15, 2),
    CASH_DIFF             DECIMAL(15, 2),
    JOURNAL_CR            DECIMAL(15, 2),
    JOURNAL_DB            DECIMAL(15, 2),
    JOURNAL_DIFF          DECIMAL(15, 2),
    CHEQUE_NO             DECIMAL(10),
    ACCOUNT_NUMBER        DECIMAL(11),
    C_DIGIT               SMALLINT,
    NON_FINANCIAL         DECIMAL(15, 2),
    PRFT_ACCOUNT_NUMBER   CHAR(40),
    VALUE_DATE            DATE,
    ACCOUNT_CD            SMALLINT,
    REVERSAL_FLG          CHAR(1),
    PRFT_SYSTEM           SMALLINT,
    COMMENTS              CHAR(100),
    CUST_NAME             CHAR(95),
    ATM_USER              CHAR(1),
    ACC_UNIT              INTEGER,
    ID_CHANNEL            INTEGER,
    SOURCE_TBL            VARCHAR(80),
    SOURCE_TBL_STAMP      TIMESTAMP(6),
    ETL_COUNTER           DECIMAL(15),
    ETL_TAXABLE_FLG       CHAR(1),
    ETL_RECORD_METHOD     VARCHAR(80),
    DEST_ACC_NUMBER       CHAR(40),
    SERVICE_NAME          VARCHAR(80),
    ETL_LOCAL_CURR        INTEGER,
    ETL_FIXING_RATE       DECIMAL(12, 6),
    ETL_TRX_AMN           DECIMAL(15, 2),
    ETL_TRX_AMN_DOM       DECIMAL(15, 2),
    ETL_FEE_AMN           DECIMAL(15, 2),
    ETL_FEE_AMN_DOM       DECIMAL(15, 2),
    ETL_TAX_AMN           DECIMAL(15, 2),
    ETL_TAX_AMN_DOM       DECIMAL(15, 2),
    ETL_EXP_AMN           DECIMAL(15, 2),
    ETL_EXP_AMN_DOM       DECIMAL(15, 2),
    ETL_COM_AMN           DECIMAL(15, 2),
    ETL_COM_AMN_DOM       DECIMAL(15, 2),
    ETL_TAX_UNIT          INTEGER,
    ETL_REV_TRX           CHAR(1),
    ORIG_TRX_UNIT         INTEGER,
    ORIG_TRX_USER         CHAR(8),
    ORIG_TRX_DATE         DATE,
    ORIG_TRX_SN           INTEGER,
    ORIG_TRX_INT_SN       SMALLINT,
    ORIG_ETL_COUNTER      DECIMAL(15),
    INSTRUM_CODE          CHAR(3),
    ACCEPTANCE_DATE       DATE,
    CUST_ID               INTEGER,
    SOURCE_TAX_ID         CHAR(20),
    ACCOUNT_USAGE_GRP     CHAR(4),
    SOURCE_SIGN           CHAR(1),
    SOURCE_ACCOUNT_NUMBER DECIMAL(11),
    TARGET_ORDER_CODE     VARCHAR(20),
    FK_ORDER_CODE         VARCHAR(20),
    TARGET_CURRENCY       INTEGER,
    TARGET_AMOUNT         DECIMAL(15, 2),
    TARGET_AMOUNT_DC      DECIMAL(15, 2),
    TARGET_BIC_ADDRESS    VARCHAR(12),
    ORGANIZATION_CODE     INTEGER,
    ETL_INSTRUCTION_ID    CHAR(35),
    ETL_TAX_ID            CHAR(20),
    TARGET_BENEF_NAME     VARCHAR(100),
    DATE_GROUP_HEADER     CHAR(6),
    MCC                   CHAR(4),
    TRX_YEAR              DECIMAL(4),
    TRX_MONTH             DECIMAL(2),
    constraint PK_USR_TRX_DIARY
        primary key (TMSTAMP, TRX_UNIT, TRX_DATE, TRX_USR, TRX_USR_SN, TUN_INTERNAL_SN, INTERNAL_SN)
);

