create table EXP_SCALE
(
    FK_EXPENSEID_EXPEN INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    VALIDITY_DATE      DATE,
    SCALE_ID           SMALLINT,
    PERCENTAGE         DECIMAL(8, 4),
    RESULT_AMOUNT      DECIMAL(15, 2),
    EXPENSE            DECIMAL(15, 2),
    TO_AMOUNT          DECIMAL(15, 2),
    FROM_AMOUNT        DECIMAL(15, 2),
    MIN_EXPENSE        DECIMAL(15, 2),
    MAX_EXPENSE        DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6)
);

create unique index IXU_EXP_001
    on EXP_SCALE (FK_EXPENSEID_EXPEN, FK_CURRENCYID_CURR, VALIDITY_DATE, SCALE_ID);

