create table EXPLAIN_OBJECT
(
    EXPLAIN_REQUESTER            VARCHAR(128) not null,
    EXPLAIN_TIME                 TIMESTAMP(6) not null,
    SOURCE_NAME                  VARCHAR(128) not null,
    SOURCE_SCHEMA                VARCHAR(128) not null,
    SOURCE_VERSION               VARCHAR(64)  not null,
    EXPLAIN_LEVEL                CHAR(1)      not null,
    STMTNO                       INTEGER      not null,
    SECTNO                       INTEGER      not null,
    OBJECT_SCHEMA                VARCHAR(128) not null,
    OBJECT_NAME                  VARCHAR(128) not null,
    OBJECT_TYPE                  CHAR(2)      not null,
    CREATE_TIME                  TIMESTAMP(6),
    STATISTICS_TIME              TIMESTAMP(6),
    COLUMN_COUNT                 SMALLINT     not null,
    ROW_COUNT                    BIGINT       not null,
    WIDTH                        INTEGER      not null,
    PAGES                        BIGINT       not null,
    DISTINCT                     CHAR(1)      not null,
    TABLESPACE_NAME              VARCHAR(128),
    OVERHEAD                     DOUBLE       not null,
    TRANSFER_RATE                DOUBLE       not null,
    PREFETCHSIZE                 INTEGER      not null,
    EXTENTSIZE                   INTEGER      not null,
    CLUSTER                      DOUBLE       not null,
    NLEAF                        BIGINT       not null,
    NLEVELS                      INTEGER      not null,
    FULLKEYCARD                  BIGINT       not null,
    OVERFLOW                     BIGINT       not null,
    FIRSTKEYCARD                 BIGINT       not null,
    FIRST2KEYCARD                BIGINT       not null,
    FIRST3KEYCARD                BIGINT       not null,
    FIRST4KEYCARD                BIGINT       not null,
    SEQUENTIAL_PAGES             BIGINT       not null,
    DENSITY                      INTEGER      not null,
    STATS_SRC                    CHAR(1)      not null,
    AVERAGE_SEQUENCE_GAP         DOUBLE       not null,
    AVERAGE_SEQUENCE_FETCH_GAP   DOUBLE       not null,
    AVERAGE_SEQUENCE_PAGES       DOUBLE       not null,
    AVERAGE_SEQUENCE_FETCH_PAGES DOUBLE       not null,
    AVERAGE_RANDOM_PAGES         DOUBLE       not null,
    AVERAGE_RANDOM_FETCH_PAGES   DOUBLE       not null,
    NUMRIDS                      BIGINT       not null,
    NUMRIDS_DELETED              BIGINT       not null,
    NUM_EMPTY_LEAFS              BIGINT       not null,
    ACTIVE_BLOCKS                BIGINT       not null,
    NUM_DATA_PARTS               INTEGER      not null,
    NULLKEYS                     CHAR(1),
    foreign key (EXPLAIN_REQUESTER, EXPLAIN_TIME, SOURCE_NAME, SOURCE_SCHEMA, SOURCE_VERSION, EXPLAIN_LEVEL, STMTNO,
                 SECTNO) references EXPLAIN_STATEMENT
        on delete cascade
);

create unique index OBJ_I2
    on EXPLAIN_OBJECT (EXPLAIN_TIME, EXPLAIN_LEVEL, STMTNO, SECTNO);

