create table EXT_IPROFITS_APPLY
(
    CURR_TRX_DATE       DATE         not null,
    APPLY_SN            DECIMAL(15)  not null,
    TMSTAMP             TIMESTAMP(6) not null,
    MIDDLE_NAME         VARCHAR(15),
    DATE_OF_BIRTH       DATE,
    E_MAIL              CHAR(64),
    FIRST_NAME          CHAR(20),
    SURNAME             CHAR(70)     not null,
    MOBILE_TEL          VARCHAR(15),
    ACCOUNT_NUMBER      CHAR(40),
    ACCOUNT_CD          SMALLINT,
    PRFT_SYSTEM         SMALLINT,
    ADDRESS_1           VARCHAR(40),
    ADDRESS_2           VARCHAR(40),
    ZIP_CODE            CHAR(10),
    ID_NO               CHAR(20),
    ID_DESCRIPTION      VARCHAR(40),
    AFM_NO              CHAR(20),
    MATCH_CUST_ID       INTEGER,
    MATCH_C_DIGIT       SMALLINT,
    MATCH_NUMBER        SMALLINT,
    MATCHED_ID_1        CHAR(1),
    MATCHED_NAME_2      CHAR(1),
    MATCHED_BIRTHDAY_3  CHAR(1),
    MATCHED_EMAIL_4     CHAR(1),
    MATCHED_MOBILE_5    CHAR(1),
    MATCHED_ADDRESS_6   CHAR(1),
    MATCHED_ACCOUNT_7   CHAR(1),
    VIEW_FIRST_NAME     CHAR(20),
    VIEW_MIDDLE_NAME    VARCHAR(15),
    VIEW_SURNAME        CHAR(70),
    VIEW_DATE_OF_BIRTH  DATE,
    VIEW_E_MAIL         CHAR(64),
    VIEW_MOBILE_TEL     VARCHAR(15),
    VIEW_ADDRESS_1      VARCHAR(40),
    VIEW_ADDRESS_2      VARCHAR(40),
    VIEW_ZIP_CODE       CHAR(10),
    VIEW_ID_DESCRIPTION VARCHAR(40),
    VIEW_ID_NO          CHAR(20),
    VIEW_AFM_NO         CHAR(20),
    VIEW_PRFT_SYSTEM    SMALLINT,
    VIEW_ACCOUNT_NUMBER CHAR(40),
    VIEW_ACCOUNT_CD     SMALLINT,
    MATCHED_AFM_8       CHAR(1),
    VIEW_IBAN           CHAR(50),
    FATHER_NAME         VARCHAR(20),
    constraint PK_EXTRNL_IPROFITS
        primary key (TMSTAMP, APPLY_SN, CURR_TRX_DATE)
);

