create table EXT_INTERBRCH_ORD
(
    ORDER_TYPE        CHAR(1),
    ORDER_NUMBER      DECIMAL(10),
    PRFT_TRX_INTER_SN SMALLINT,
    PRFT_BEN_UNIT     INTEGER,
    PRODUCT           INTEGER,
    PRFT_ISSUE_UNIT   INTEGER,
    PRFT_TRX_UNIT     INTEGER,
    FK_ORDER_NUMBER   INTEGER,
    PRFT_TRX_SN       INTEGER,
    ORDER_AMOUNT      DECIMAL(15, 2),
    ORDER_ISSUE_DATE  DATE,
    PRFT_TRX_DATE     DATE,
    PAYMENT_DATE      DATE,
    TMSTAMP           TIMESTAMP(6),
    ORDER_STATUS      CHAR(1),
    ORDER_CURRENCY    CHAR(3),
    PRFT_TRX_USR      CHAR(8),
    ISSUER_ACC_UNIT   CHAR(9),
    ORDER_UNIT        CHAR(9),
    BEN_MFO           CHAR(9),
    ISSUER_ZIP_CODE   VARCHAR(10),
    TRX_CONFIRM_USR   VARCHAR(10),
    TRX_USR           VARCHAR(10),
    BEN_ZIP_CODE      VARCHAR(10),
    BEN_PID           VARCHAR(15),
    ISSUER_PID        VARCHAR(15),
    ISSUER_PHONE      VARCHAR(20),
    BEN_DEP_ACC       VARCHAR(20),
    ISSUER_DEP_ACC    VARCHAR(20),
    BEN_PHONE         VARCHAR(20),
    BEN_CITY          VARCHAR(30),
    ISSUER_CITY       VARCHAR(30),
    ISSUER_ADDRESS    VARCHAR(40),
    BEN_ADDRESS       VARCHAR(40),
    ISSUER_NAME       VARCHAR(70),
    BEN_NAME          VARCHAR(70),
    ORDER_COMMENTS    VARCHAR(255)
);

create unique index IXU_EXT_000
    on EXT_INTERBRCH_ORD (ORDER_TYPE, ORDER_NUMBER);

