create table EXTRNL_ACC_LD_DT
(
    EXTRNL_ACC_SN     DECIMAL(10)  not null,
    FILE_SN           INTEGER      not null,
    ACC_PRFT_SYSTEM   SMALLINT     not null,
    ACCOUNT_NUMBER    CHAR(40)     not null,
    ACCOUNT_CD        SMALLINT     not null,
    MONITORING_UNIT   INTEGER      not null,
    CUSTOMER_ID       INTEGER      not null,
    CUSTOMER_CD       SMALLINT     not null,
    PRODUCT_ID        INTEGER      not null,
    ACCOUNT_STATUS    CHAR(1)      not null,
    MOVEMENT_CURRENCY INTEGER      not null,
    LIMIT_CURRENCY    INTEGER      not null,
    AMOUNT_1          DECIMAL(15, 2),
    AMOUNT_2          DECIMAL(15, 2),
    AMOUNT_3          DECIMAL(15, 2),
    AMOUNT_4          DECIMAL(15, 2),
    AMOUNT_5          DECIMAL(15, 2),
    AMOUNT_6          DECIMAL(15, 2),
    AMOUNT_7          DECIMAL(15, 2),
    AMOUNT_8          DECIMAL(15, 2),
    AMOUNT_9          DECIMAL(15, 2),
    AMOUNT_10         DECIMAL(15, 2),
    TIMSTAMP          TIMESTAMP(6) not null,
    ACC_INSERT_STS    CHAR(1)      not null,
    ACC_INSERT_ERR    VARCHAR(200),
    PROCESS_STATUS    CHAR(1)      not null,
    PROCESS_ERROR     VARCHAR(200),
    FK_FILE_SN        SMALLINT     not null,
    FK_FILE_DATE      DATE         not null,
    AMOUNT_11         DECIMAL(15, 2),
    DATE_1            DATE,
    DATE_3            DATE,
    DATE_4            DATE,
    DATE_11           DATE,
    FLAG_1            CHAR(1),
    FLAG_3            CHAR(1),
    FLAG_4            CHAR(1),
    NUMERIC_1         DECIMAL(10),
    NUMERIC_2         DECIMAL(10),
    NUMERIC_3         DECIMAL(10),
    NUMERIC_4         DECIMAL(10),
    NUMERIC_5         DECIMAL(10),
    NUMERIC_6         DECIMAL(10),
    RATE_1            DECIMAL(12, 6),
    FLAG_2            CHAR(1),
    DATE_2            DATE,
    constraint PK_EXTRNL_ACC_LD_DT
        primary key (FK_FILE_SN, FK_FILE_DATE, EXTRNL_ACC_SN)
);

