create table EXTRNL_ACC_INFO
(
    ACCOUNT_NUMBER CHAR(40) not null,
    PRFT_SYSTEM    SMALLINT not null,
    AMOUNT_11      DECIMAL(15, 2),
    AMOUNT_12      DECIMAL(15, 2),
    AMOUNT_13      DECIMAL(15, 2),
    AMOUNT_14      DECIMAL(15, 2),
    AMOUNT_15      DECIMAL(15, 2),
    AMOUNT_16      DECIMAL(15, 2),
    AMOUNT_17      DECIMAL(15, 2),
    AMOUNT_18      DECIMAL(15, 2),
    AMOUNT_19      DECIMAL(15, 2),
    AMOUNT_20      DECIMAL(15, 2),
    AMOUNT_21      DECIMAL(15, 2),
    AMOUNT_22      DECIMAL(15, 2),
    AMOUNT_23      DECIMAL(15, 2),
    AMOUNT_24      DECIMAL(15, 2),
    AMOUNT_25      DECIMAL(15, 2),
    DATE_1         DATE,
    DATE_2         DATE,
    DATE_3         DATE,
    DATE_4         DATE,
    DATE_5         DATE,
    DATE_6         DATE,
    DATE_7         DATE,
    DATE_8         DATE,
    DATE_9         DATE,
    DATE_10        DATE,
    DATE_11        DATE,
    DATE_12        DATE,
    DATE_13        DATE,
    DATE_14        DATE,
    DATE_15        DATE,
    CHAR_1         CHAR(40),
    CHAR_2         CHAR(40),
    CHAR_3         CHAR(40),
    CHAR_4         CHAR(40),
    CHAR_5         CHAR(40),
    CHAR_6         CHAR(40),
    CHAR_7         CHAR(40),
    CHAR_8         CHAR(40),
    CHAR_9         CHAR(40),
    CHAR_10        CHAR(40),
    FLAG_1         CHAR(2),
    FLAG_2         CHAR(2),
    FLAG_3         CHAR(2),
    FLAG_4         CHAR(2),
    FLAG_5         CHAR(2),
    FLAG_6         CHAR(2),
    FLAG_7         CHAR(2),
    FLAG_8         CHAR(2),
    FLAG_9         CHAR(2),
    FLAG_10        CHAR(2),
    LARGE_CHAR_1   CHAR(254),
    LARGE_CHAR_2   CHAR(254),
    LARGE_CHAR_3   CHAR(254),
    LARGE_CHAR_4   CHAR(254),
    LARGE_CHAR_5   CHAR(254),
    constraint PK_EXTRNL_ADD
        primary key (PRFT_SYSTEM, ACCOUNT_NUMBER)
);

