create table FAST_ENTRY_PARAMET
(
    INSUFF_CHARGE_CODE         INTEGER,
    ACC_PRODUCT_TYPE           CHAR(1),
    CR_CHARGES_IND             CHAR(1),
    DR_CHARGES_IND             CHAR(1),
    MAX_NO_OF_ATTEMPTS         SMALLINT,
    ORDER_TYPE                 CHAR(1),
    BOOKS_NUMBER               INTEGER,
    BOOK_PAGES                 SMALLINT,
    FK_PRFT_TRANSACID_TRANSACT INTEGER not null
        constraint PKFASTEN
            primary key,
    FK_JUSTIFICID_JUSTIFIC     INTEGER,
    FK0JUSTIFICID_JUSTIFIC     INTEGER,
    FK1JUSTIFICID_JUSTIFIC     INTEGER,
    FK_PRODUCTID_PRODUCT       INTEGER,
    FK0PRODUCTID_PRODUCT       INTEGER
);

create unique index I0000574
    on FAST_ENTRY_PARAMET (FK_JUSTIFICID_JUSTIFIC);

create unique index I0000576
    on FAST_ENTRY_PARAMET (FK0JUSTIFICID_JUSTIFIC);

create unique index I0000578
    on FAST_ENTRY_PARAMET (FK1JUSTIFICID_JUSTIFIC);

create unique index I0000582
    on FAST_ENTRY_PARAMET (FK_PRODUCTID_PRODUCT);

create unique index I0000584
    on FAST_ENTRY_PARAMET (FK0PRODUCTID_PRODUCT);

