create table FD_GL_ACCOUNTS
(
    FK_REFERS_DEPOSIT  INTEGER,
    TMSTAMP            TIMESTAMP(6),
    DR_INT_NOTAX_GLLVL CHAR(1),
    CR_INT_NOTAX_GL_LV CHAR(1),
    CR_INT_NOTAX_GL_AC CHAR(21),
    DR_INT_NOTAX_GLACC CHAR(21)
);

create unique index IXU_FD__000
    on FD_GL_ACCOUNTS (FK_REFERS_DEPOSIT);

