create table FD_VALEUR_BALANCE
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    INT_CALC_PERIOD    DECIMAL(11),
    VALUE_DATE         DATE,
    INIT_BALANCE_FLAG  CHAR(1),
    VALEUR_BALANCE     DECIMAL(15, 2)
);

create unique index IXP_FD__001
    on FD_VALEUR_BALANCE (FK_DEPOSIT_ACCOACC, INT_CALC_PERIOD, VALUE_DATE, INIT_BALANCE_FLAG);

