create table FILE_EXPORT_LOG_DTL
(
    FILE_LINE_NO        DECIMAL(15),
    FK_FILE_EXP_TMSTAMP TIMESTAMP(6),
    FILE_LINE_TEXT      CHAR(254)
);

create unique index PK_FILE_EXPORT_LOG_DTL
    on FILE_EXPORT_LOG_DTL (FK_FILE_EXP_TMSTAMP, FILE_LINE_NO);

