create table FIXING_RATE
(
    FK_CURRENCYID_CURR INTEGER,
    ACTIVATION_DATE    DATE,
    MULTIPLIER         INTEGER,
    RATE               DECIMAL(12, 6),
    TMSTAMP            TIMESTAMP(6),
    ACTIVATION_TIME    TIME
);

create unique index PK_FIXING
    on FIXING_RATE (FK_CURRENCYID_CURR, ACTIVATION_DATE, ACTIVATION_TIME);

