create table FORECAST_TRANS
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    CHEQUE_NUMBER      DECIMAL(10),
    REFERENCE_NUMBER   VARCHAR(20),
    CHEQUE_CD          SMALLINT,
    TRX_UNIT           INTEGER,
    FK_UNITCODE        INTEGER,
    TRX_USR_SN         INTEGER,
    U_INTER_WITHDR     DECIMAL(15, 2),
    U_WITHDR_BALANCE   DECIMAL(15, 2),
    AMOUNT             DECIMAL(15, 2),
    TRX_DATE           DATE,
    ENTRY_STATUS       CHAR(1),
    O_CHEQUE_STATUS    CHAR(1),
    P_CHEQUE_STATUS    CHAR(1),
    TRX_USR            CHAR(8),
    NOTIF_REF_NUMBER   VARCHAR(20)
);

create unique index IXU_FOR_000
    on FORECAST_TRANS (FK_DEPOSIT_ACCOACC, CHEQUE_NUMBER, REFERENCE_NUMBER);

