create table FORWARD_ANALYSIS
(
    UNIT        INTEGER,
    POS_DATE    DATE,
    CURRENCY    INTEGER,
    TODAY_FW_DC DECIMAL(18, 2),
    CURR_FW_FC  DECIMAL(18, 2),
    TODAY_FW_FC DECIMAL(18, 2),
    CURR_FW_DC  DECIMAL(18, 2),
    PREV_FW_FC  DECIMAL(18, 2),
    PREV_FW_DC  DECIMAL(18, 2)
);

create unique index IXU_FOR_001
    on FORWARD_ANALYSIS (UNIT, POS_DATE, CURRENCY);

