create table FX_FT_PARAMETERS
(
    DIAS_SOURCE_TRN_TYPE CHAR(1),
    DIAS_TARGET_TRN_TYPE CHAR(1),
    DIAS_SOURCE_POSITION CHAR(1),
    DIAS_TARGET_POSITION CHAR(1),
    DIAS_FX_TYPE         CHAR(1),
    DIAS_BUY_RATE_IND    CHAR(1),
    DIAS_SELL_RATE_IND   CHAR(1),
    CODE                 INTEGER,
    DEFAULT_UNIT         INTEGER,
    DIAS_PRODUCT         INTEGER,
    DIAS_SUCCESS_JUST    INTEGER,
    DIAS_FAIL_JUST       INTEGER,
    DIAS_005_NEG         INTEGER,
    DIAS_AMNT_ORIGIN     DECIMAL(15, 2),
    DIAS_ANALYSIS_FLG    CHAR(1),
    DIAS_UNSUC_JUST1     INTEGER,
    DIAS_UNSUC_JUST2     INTEGER,
    DIAS_UNSUC_JUST3     INTEGER,
    DIAS_UNSUC_JUST4     INTEGER,
    DIAS_UNSUC_JUST5     INTEGER,
    DIAS_SUC_JUST5       INTEGER,
    DIAS_SUC_JUST4       INTEGER,
    DIAS_SUC_JUST3       INTEGER,
    DIAS_SUC_JUST2       INTEGER,
    DIAS_SUC_JUST1       INTEGER,
    DIAS_IO_JUST         INTEGER,
    DIAS_IO_UNSUC_JUST   INTEGER,
    DIAS_IO_SUC_JUST     INTEGER,
    DIAS_COLLE_PRFTTRANS INTEGER
);

create unique index IXP_FX__000
    on FX_FT_PARAMETERS (CODE);

