create table FX_FT_BATCH_PARAM
(
    PROGRAM_ID       CHAR(5),
    UPD_TUN_INTER_SN SMALLINT,
    EXEC_MONTH       SMALLINT,
    MONTH_FROM       SMALLINT,
    MONTH_TO         SMALLINT,
    EXEC_YEAR        SMALLINT,
    BANK_TO          INTEGER,
    BANK_FROM        INTEGER,
    BANK             INTEGER,
    AGENT_TO         INTEGER,
    UPD_TRX_UNIT     INTEGER,
    AGENT            INTEGER,
    UNIT_TO          INTEGER,
    UNIT_FROM        INTEGER,
    UNIT             INTEGER,
    AGENT_FROM       INTEGER,
    CURRENCY_TO      INTEGER,
    CURRENCY_FROM    INTEGER,
    CURRENCY         INTEGER,
    EXEC_DAYS        INTEGER,
    PRODUCT_TO       INTEGER,
    PRODUCT_FROM     INTEGER,
    PRODUCT          INTEGER,
    CUSTOMER         INTEGER,
    CUSTOMER_FROM    INTEGER,
    CUSTOMER_TO      INTEGER,
    UPD_TRX_SN       INTEGER,
    AMOUNT_FROM      DECIMAL(15, 2),
    AMOUNT           DECIMAL(15, 2),
    AMOUNT_TO        DECIMAL(15, 2),
    DATE0            DATE,
    DATE_FROM        DATE,
    UPD_TRX_DATE     DATE,
    DATE_TO          DATE,
    UPDATE_FROM      TIMESTAMP(6),
    UPDATE_TO        TIMESTAMP(6),
    AMOUNT_FLAG      CHAR(1),
    PRODUCT_FLAG     CHAR(1),
    BANK_FLAG        CHAR(1),
    JOURNAL_FLAG     CHAR(1),
    AGENT_FLAG       CHAR(1),
    CUSTOMER_FLAG    CHAR(1),
    UNIT_FLAG        CHAR(1),
    MONTH_FLAG       CHAR(1),
    YEAR_FLAG        CHAR(1),
    DATE_FLAG        CHAR(1),
    CURRENCY_FLAG    CHAR(1),
    JOURNAL_FROM     CHAR(2),
    JOURNAL          CHAR(2),
    JOURNAL_TO       CHAR(2),
    UPD_TRX_USR      CHAR(8),
    ORGANIZ_FILENAME CHAR(20),
    DESCRIPTION      CHAR(40),
    ID_JUSTIFIC      INTEGER,
    FILE_NAME        VARCHAR(100),
    PROCESS_ACTION   CHAR(1)
);

create unique index IXU_FX__000
    on FX_FT_BATCH_PARAM (PROGRAM_ID);

