CREATE VIEW FX_OPEN_POS_TRX (
TRX_UNIT, TRX_DATE, TRX_USR, TRX_SN, TUN_INTERNAL_SN, I_TUN_UNIT, CHARGES_CURRENCY, TARGET_CURRENCY, ACC_SOURCE_CURR, ACCOUNT_UNIT, GL_ARTICLE_CODE3, GL_ARTICLE_CODE1,
GL_ARTICLE_CODE2, CHANNEL_ID, TRX_CODE, CUST_ID, FIXING_RATE, ACC_AMOUNT_28, ACC_AMOUNT_29, ACC_AMOUNT_30, ACC_AMOUNT_31, ACC_AMOUNT_32, ACC_AMOUNT_33, ACC_AMOUNT_34, ACC_AMOUNT_35,
ACC_AMOUNT_36, ACC_AMOUNT_37, ACC_AMOUNT_38, ACC_AMOUNT_39, ACC_AMOUNT_40, ACC_AMOUNT_41, ACC_AMOUNT_42, ACC_AMOUNT_43, ACC_AMOUNT_44, ACC_AMOUNT_45, ACC_AMOUNT_46, ACC_AMOUNT_47,
ACC_AMOUNT_48, ACC_AMOUNT_49, ACC_AMOUNT_50, ACC_AMOUNT_51, ACC_AMOUNT_52, ACC_AMOUNT_53, ACC_AMOUNT_54, ACC_AMOUNT_55, ACC_AMOUNT_56, ACC_AMOUNT_57, ACC_AMOUNT_58, ACC_AMOUNT_59,
ACC_AMOUNT_60, ACC_AMOUNT_61, ACC_AMOUNT_62, ACC_AMOUNT_63, ACC_AMOUNT_64, ACC_AMOUNT_65, ACC_AMOUNT_66, ACC_AMOUNT_67, ACC_AMOUNT_68, ACC_AMOUNT_69, ACC_AMOUNT_70, ACC_AMOUNT_71,
ACC_AMOUNT_72, ACC_AMOUNT_73, ACC_AMOUNT_74, ACC_AMOUNT_75, ACC_AMOUNT_76, ACC_AMOUNT_77, ACC_AMOUNT_78, ACC_AMOUNT_79, ACC_AMOUNT_80, ACC_AMOUNT_81, ACC_AMOUNT_82, ACC_AMOUNT_83,
ACC_AMOUNT_84, ACC_AMOUNT_85, ACC_AMOUNT_86, ACC_AMOUNT_87, ACC_AMOUNT_88, ACC_AMOUNT_89, ACC_AMOUNT_90, ACC_AMOUNT_91, ACC_AMOUNT_92, ACC_AMOUNT_93, ACC_AMOUNT_94, ACC_AMOUNT_95,
ACC_AMOUNT_96, ACC_AMOUNT_97, ACC_AMOUNT_98, ACC_AMOUNT_99, USER_TOTAL_AMN, ACC_AMOUNT_1, ACC_AMOUNT_2, ACC_AMOUNT_3, ACC_AMOUNT_4, ACC_AMOUNT_5, ACC_AMOUNT_6, ACC_AMOUNT_7, ACC_AMOUNT_8,
ACC_AMOUNT_9, ACC_AMOUNT_10, ACC_AMOUNT_11, ACC_AMOUNT_12, ACC_AMOUNT_13, ACC_AMOUNT_14, ACC_AMOUNT_15, ACC_AMOUNT_16, ACC_AMOUNT_17, ACC_AMOUNT_18, ACC_AMOUNT_19, ACC_AMOUNT_20,
ACC_AMOUNT_21, ACC_AMOUNT_22, ACC_AMOUNT_23, ACC_AMOUNT_24, ACC_AMOUNT_25, ACC_AMOUNT_26, ACC_AMOUNT_27, O_VALUE_DATE_3, O_VALUE_DATE_2, O_VALUE_DATE_1, NON_PRFT_FLG, TARGET_TRN_TYPE,
SOURCE_TRN_TYPE, DR_GL_TARGET_LVL, GL_COR_LVL, TRANSACTION_STATUS, ACCOUNTED_FLAG, DR_GL_INT_TARG_LVL, DR_GL_COLLATER_LVL, CR_GL_COLLATER_LVL, DR_GL_ACCR_INT_LVL, CR_GL_CONTROL_LVL,
CR_GL_INTEREST_LVL, CR_GL_ACCR_INT_LVL, GL_ACCRUAL_LVL, DR_GL_CONTROL_LVL, DR_GL_INTEREST_LVL, GL_NETWORK_LVL, ACC_SUBSYS, CUST_TAX_REG_NO, TERMINAL_CODE, DR_GL_INTEREST_ACC,
GL_NETWORK_ACC, DR_GL_TARGET_ACC, DR_GL_INT_TARG_ACC, DR_GL_COLLATER_ACC, DR_GL_ACCR_INT_ACC, CR_GL_CONTROL_ACC, CR_GL_INTEREST_ACC, CR_GL_ACCR_INT_ACC, GL_ACCRUAL_ACC, GL_COR_ACC, DR_GL_CONTROL_ACC,
CR_GL_COLLATER_ACC
)
AS
    SELECT
    TRX_UNIT, TRX_DATE, TRX_USR, TRX_SN, TUN_INTERNAL_SN, I_TUN_UNIT, CHARGES_CURRENCY, TARGET_CURRENCY, ACC_SOURCE_CURR, ACCOUNT_UNIT, GL_ARTICLE_CODE3, GL_ARTICLE_CODE1, GL_ARTICLE_CODE2, CHANNEL_ID,
    TRX_CODE, CUST_ID, FIXING_RATE, ACC_AMOUNT_28, ACC_AMOUNT_29, ACC_AMOUNT_30, ACC_AMOUNT_31, ACC_AMOUNT_32, ACC_AMOUNT_33, ACC_AMOUNT_34, ACC_AMOUNT_35, ACC_AMOUNT_36, ACC_AMOUNT_37, ACC_AMOUNT_38,
    ACC_AMOUNT_39, ACC_AMOUNT_40, ACC_AMOUNT_41, ACC_AMOUNT_42, ACC_AMOUNT_43, ACC_AMOUNT_44, ACC_AMOUNT_45, ACC_AMOUNT_46, ACC_AMOUNT_47, ACC_AMOUNT_48, ACC_AMOUNT_49, ACC_AMOUNT_50, ACC_AMOUNT_51,
    ACC_AMOUNT_52, ACC_AMOUNT_53, ACC_AMOUNT_54, ACC_AMOUNT_55, ACC_AMOUNT_56, ACC_AMOUNT_57, ACC_AMOUNT_58, ACC_AMOUNT_59, ACC_AMOUNT_60, ACC_AMOUNT_61, ACC_AMOUNT_62, ACC_AMOUNT_63, ACC_AMOUNT_64,
    ACC_AMOUNT_65, ACC_AMOUNT_66, ACC_AMOUNT_67, ACC_AMOUNT_68, ACC_AMOUNT_69, ACC_AMOUNT_70, ACC_AMOUNT_71, ACC_AMOUNT_72, ACC_AMOUNT_73, ACC_AMOUNT_74, ACC_AMOUNT_75, ACC_AMOUNT_76, ACC_AMOUNT_77,
    ACC_AMOUNT_78, ACC_AMOUNT_79, ACC_AMOUNT_80, ACC_AMOUNT_81, ACC_AMOUNT_82, ACC_AMOUNT_83, ACC_AMOUNT_84, ACC_AMOUNT_85, ACC_AMOUNT_86, ACC_AMOUNT_87, ACC_AMOUNT_88, ACC_AMOUNT_89, ACC_AMOUNT_90,
    ACC_AMOUNT_91, ACC_AMOUNT_92, ACC_AMOUNT_93, ACC_AMOUNT_94, ACC_AMOUNT_95, ACC_AMOUNT_96, ACC_AMOUNT_97, ACC_AMOUNT_98, ACC_AMOUNT_99, USER_TOTAL_AMN, ACC_AMOUNT_1, ACC_AMOUNT_2, ACC_AMOUNT_3,
    ACC_AMOUNT_4, ACC_AMOUNT_5, ACC_AMOUNT_6, ACC_AMOUNT_7, ACC_AMOUNT_8, ACC_AMOUNT_9, ACC_AMOUNT_10, ACC_AMOUNT_11, ACC_AMOUNT_12, ACC_AMOUNT_13, ACC_AMOUNT_14, ACC_AMOUNT_15, ACC_AMOUNT_16,
    ACC_AMOUNT_17, ACC_AMOUNT_18, ACC_AMOUNT_19, ACC_AMOUNT_20, ACC_AMOUNT_21, ACC_AMOUNT_22, ACC_AMOUNT_23, ACC_AMOUNT_24, ACC_AMOUNT_25, ACC_AMOUNT_26, ACC_AMOUNT_27, O_VALUE_DATE_3, O_VALUE_DATE_2,
    O_VALUE_DATE_1, NON_PRFT_FLG, TARGET_TRN_TYPE, SOURCE_TRN_TYPE, DR_GL_TARGET_LVL, GL_COR_LVL, TRANSACTION_STATUS, ACCOUNTED_FLAG, DR_GL_INT_TARG_LVL, DR_GL_COLLATER_LVL, CR_GL_COLLATER_LVL,
    DR_GL_ACCR_INT_LVL, CR_GL_CONTROL_LVL, CR_GL_INTEREST_LVL, CR_GL_ACCR_INT_LVL, GL_ACCRUAL_LVL, DR_GL_CONTROL_LVL, DR_GL_INTEREST_LVL, GL_NETWORK_LVL, ACC_SUBSYS, CUST_TAX_REG_NO,
    TERMINAL_CODE, DR_GL_INTEREST_ACC, GL_NETWORK_ACC, DR_GL_TARGET_ACC, DR_GL_INT_TARG_ACC, DR_GL_COLLATER_ACC, DR_GL_ACCR_INT_ACC, CR_GL_CONTROL_ACC, CR_GL_INTEREST_ACC, CR_GL_ACCR_INT_ACC,
    GL_ACCRUAL_ACC, GL_COR_ACC, DR_GL_CONTROL_ACC, CR_GL_COLLATER_ACC
    FROM
        TRX_RECORDING dtr
    WHERE dtr.TRX_DATE = (SELECT CURR_TRX_DATE FROM BANK_PARAMETERS bp)	 AND dtr.GL_ARTICLE_CODE1 != '0' AND dtr.ACCOUNTED_FLAG = '0' AND dtr.TRX_UNIT >= 0
	AND NOT EXISTS (SELECT * FROM FX_OPEN_POS_HDR foph WHERE dtr.TRX_UNIT= foph.TRX_UNIT AND dtr.TRX_DATE= foph.TRX_DATE AND dtr.TRX_USR= foph.TRX_USR AND dtr.TRX_SN= foph.TRX_SN AND dtr.TUN_INTERNAL_SN= foph.TRX_INT_SN );

