create table FXFT_AUTH_LOG
(
    FK_AUTH_LOGAUTH_DA DATE,
    FK_AUTH_LOGUNITCOD INTEGER,
    FK_AUTH_LOGREQUEST INTEGER,
    CORRESP_ACC_C_DIGI SMALLINT,
    CUST_ACC_C_DIGIT   SMALLINT,
    CORRESP_C_DIGIT    SMALLINT,
    ACCOUNT_UNIT       INTEGER,
    PRODUCT            INTEGER,
    ACCOUNT_PRODUCT    INTEGER,
    ORDER_NUMBER       INTEGER,
    CORRESPONDENT_ID   INTEGER,
    CORRESP_ACC_NUMBER DECIMAL(10),
    CUSTOMER_ACCOUN_NO DECIMAL(10),
    PO_AMOUNT          DECIMAL(15, 2),
    FUNDING_AMOUNT     DECIMAL(15, 2),
    VALUE_DATE         DATE,
    PO_VALUE_DATE      DATE,
    PO_CURRENCY        CHAR(5),
    FUNDING_CURRENCY   CHAR(5),
    ACCOUNT_CURRENCY   CHAR(5),
    POST_CODE          CHAR(7),
    CITY               CHAR(15),
    BENEFICIARY_ACC_NO CHAR(35),
    DETAILS_OF_PAYMENT CHAR(100),
    BANK_CITY          VARCHAR(15),
    SWIFT_ADDRESS      VARCHAR(35),
    ACCOUNT_WITH_BANK  VARCHAR(35),
    BANK               VARCHAR(40),
    COUNTRY            VARCHAR(40),
    ADDRESS_1          VARCHAR(40),
    BENEFICIARY_NAME   VARCHAR(40),
    ADDRESS_2          VARCHAR(40),
    BANK_COUNTRY       VARCHAR(40),
    ACCOUNT_DESCR      VARCHAR(60),
    SENDER_TO_RECEIVER VARCHAR(210),
    ENTRY_COMMENTS     VARCHAR(235),
    WPROFITS_REQUEST   CHAR(1)
);

create unique index IXU_FXF_002
    on FXFT_AUTH_LOG (FK_AUTH_LOGAUTH_DA, FK_AUTH_LOGUNITCOD, FK_AUTH_LOGREQUEST);

