create table FXFT_OTHER_SYS_TRX
(
    FXFT_TUN_INTE_SN  SMALLINT,
    FXFT_TRX_SN       INTEGER,
    FXFT_TRX_USR      CHAR(8),
    FXFT_TRX_DATE     DATE,
    FXFT_TRX_UNIT     INTEGER,
    TRX_USR_SN        INTEGER,
    TUN_INTERNAL_SN   SMALLINT,
    PRFT_SYSTEM       SMALLINT,
    FXFT_PRFT_SYSTEM  SMALLINT,
    TRX_UNIT          INTEGER,
    ACCOUNT_NUMBER    DECIMAL(11),
    U_USER_TOTALS_AMN DECIMAL(15, 2),
    TRX_DATE          DATE,
    TRX_USR           CHAR(8),
    ACTION_FLAG       CHAR(1),
    ORDER_NUMBER      INTEGER
);

create unique index IXU_FXF_004
    on FXFT_OTHER_SYS_TRX (FXFT_TUN_INTE_SN, FXFT_TRX_SN, FXFT_TRX_USR, FXFT_TRX_DATE, FXFT_TRX_UNIT, TRX_USR_SN,
                           TUN_INTERNAL_SN);

