create table GENERIC_HEADER
(
    PARAMETER_TYPE    CHAR(5),
    DEFAULT_NUM       INTEGER,
    TMSTAMP           TIMESTAMP(6),
    SYSTEM_PARAMETER  CHAR(1),
    SHOW_FLAG         CHAR(1),
    PURPOSE_FLAG      CHAR(1),
    ENTRY_STATUS      CHAR(1),
    ABBREVIATION      VARCHAR(15),
    DESCRIPTION       VARCHAR(40),
    SYSTEM_PARAM_TYPE CHAR(1),
    DETAILED_ANALYSIS VARCHAR(4000)
);

create unique index IXU_GEN_013
    on GENERIC_HEADER (PARAMETER_TYPE);

