create table GENERIC_D_WINDOW
(
    FK_GWH_TRANSACTION INTEGER,
    FK_GWH_JUSTIFIC    INTEGER,
    FK_GWH_PRODUCT_ID  INTEGER,
    FK_GWH_HPROD_VDATE DATE,
    SERIAL_NUMBER      INTEGER,
    DESCRIPTION        CHAR(40),
    SEC_NUMBER         INTEGER,
    TMSTAMP            TIMESTAMP(6),
    ITEM_TYPE          CHAR(1),
    GENERIC_SIZE       SMALLINT,
    MANDATORY          CHAR(1),
    MODULE_NUMBER      INTEGER,
    GENERIC_TYPE       CHAR(2),
    VALRULE_TABLE_NAME CHAR(20),
    SEC_TYPE           CHAR(5),
    PRFT_SYSTEM        SMALLINT,
    LANGUAGE_USED      INTEGER,
    VAL_RULE_NAME      CHAR(20),
    V_POSITION         SMALLINT,
    H_POSITION         SMALLINT,
    V_DIRECTION        CHAR(1),
    H_DIRECTION        CHAR(1)
);

create unique index IXP_GEN_001
    on GENERIC_D_WINDOW (FK_GWH_TRANSACTION, FK_GWH_JUSTIFIC, FK_GWH_PRODUCT_ID, FK_GWH_HPROD_VDATE, SERIAL_NUMBER);

