create table GENERIC_DETAIL_INF
(
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    GEN_NUMBER         INTEGER,
    TMSTAMP            TIMESTAMP(6),
    GENERIC_FLAG       CHAR(1),
    GEN_INFO           CHAR(5),
    GEN_DESCRIPTION    CHAR(40),
    LATIN_DESCRIPTION  VARCHAR(40)
);

create unique index IXU_GEN_012
    on GENERIC_DETAIL_INF (FK_GENERIC_DETAFK, FK_GENERIC_DETASER);

