create table GENERIC_LIMIT
(
    LIMIT_ID         DECIMAL(10),
    ID_CURRENCY      INTEGER,
    LIMIT_HIST_CNT   INTEGER,
    MAX_ACC_NO       DECIMAL(10),
    ACTIVE_ACC_CNT   DECIMAL(10),
    COVERED_AMN      DECIMAL(15, 2),
    LIMIT_AMN        DECIMAL(15, 2),
    USED_LIMIT_AMN   DECIMAL(15, 2),
    USED_COVERED_AMN DECIMAL(15, 2),
    LAST_UPDATE_DT   TIMESTAMP(6),
    EXPIRE_DATE      DATE,
    USAGE_FLG        CHAR(1),
    CONSUMPTION_TYPE CHAR(1),
    ENTRY_STATUS     CHAR(1),
    LIMIT_TYPE       CHAR(3),
    LAST_UPDATE_USER CHAR(8),
    ENTITY_KEY_DESC  CHAR(40),
    LIMIT_COMMENT    CHAR(40),
    ENTITY_KEY       CHAR(40)
);

create unique index IXU_GEN_006
    on GENERIC_LIMIT (LIMIT_ID);

