create table GENERIC_D_RELATION
(
    FK_G_H_W_PRODUCTID INTEGER,
    FK_G_H_W_PRODUCTVD DATE,
    FK_G_H_W_TRANSACT  INTEGER,
    FK_G_H_W_JUSTIFIC  INTEGER,
    FK_G_H_W_SERIALNUM INTEGER,
    SERIAL_NUMBER      INTEGER,
    REL_NUMBER         INTEGER,
    TMSTAMP            TIMESTAMP(6),
    REL_TYPE           CHAR(2),
    DESCRIPTION        CHAR(40)
);

create unique index IXU_GEN_004
    on GENERIC_D_RELATION (FK_G_H_W_PRODUCTID, FK_G_H_W_PRODUCTVD, FK_G_H_W_TRANSACT, FK_G_H_W_JUSTIFIC,
                           FK_G_H_W_SERIALNUM, SERIAL_NUMBER);

