create table GENERIC_H_WINDOW
(
    FK_PRFT_TRANSACT  INTEGER,
    FK_JUSTIFIC       INTEGER,
    FK_HPRODUCT_ID    INTEGER,
    FK_HPRODUCT_VDATE DATE,
    DESCRIPTION       CHAR(40),
    TMSTAMP           TIMESTAMP(6),
    FOR_ATM           CHAR(1),
    FOR_ATM_LN        CHAR(1)
);

create unique index IXP_GEN_000
    on GENERIC_H_WINDOW (FK_PRFT_TRANSACT, FK_JUSTIFIC, FK_HPRODUCT_ID, FK_HPRODUCT_VDATE);

