create table GENERIC_DETAIL
(
    FK_GENERIC_HEADPAR CHAR(5),
    SERIAL_NUM         INTEGER,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PARAMETER_TYPE     CHAR(5),
    SHORT_DESCRIPTION  CHAR(10),
    LATIN_DESC         VARCHAR(40),
    DESCRIPTION        VARCHAR(40),
    DETAILED_ANALYSIS  VARCHAR(4000),
    NOT_EXPOSED        CHAR(1)
);

create unique index IXN_GEN_100
    on GENERIC_DETAIL (PARAMETER_TYPE, SERIAL_NUM);

create unique index IXU_GEN_011
    on GENERIC_DETAIL (FK_GENERIC_HEADPAR, SERIAL_NUM);

