CREATE FUNCTION PROFITS.GET_AMOUNT_FOR_AGR(
    SELECT_STAT    VARCHAR(3000),
    TABLE_NAME     VARCHAR(128),
    LFK_UNITCODE   DECFLOAT(16),
    LACC_TYPE      DECFLOAT(16),
    LACC_SN        DECFLOAT(16),
    LACCOUNTNUMBER VARCHAR(32),
    LCHARGE_TYPE   VARCHAR(32),
    LCHARGE_CODE   DECFLOAT(16))
  RETURNS DECFLOAT(16)
LANGUAGE SQL
BEGIN
/* modified: 2016-05-24 / g.dim. / prepare dynamic statement for execute */
   DECLARE CONDITION    VARCHAR(1000);
   DECLARE SQL_QUERY    VARCHAR(3000);
   DECLARE LAMOUNT      DECIMAL(15,2); -- DEFAULT 0.0;
   IF TABLE_NAME ='R_LOAN_ACCOUNT'
      THEN SET CONDITION = 'WHERE FK_UNITCODE='||LFK_UNITCODE||' AND ACC_TYPE='||LACC_TYPE||' AND ACC_SN='||LACC_SN;
   ELSEIF TABLE_NAME ='CUST_ACC_CHARGES'
      THEN SET CONDITION = 'WHERE ACCOUNT_NUMBER='''||LACCOUNTNUMBER||''' AND CHARGE_TYPE='''||LCHARGE_TYPE||''' AND CHARGE_CODE='||LCHARGE_CODE;
   ELSEIF TABLE_NAME ='R_LOAN_ACCOUNT_INF'
      THEN SET CONDITION = 'WHERE FK_LOAN_ACCOUNTFK='||LFK_UNITCODE||' AND FK0LOAN_ACCOUNTACC='||LACC_TYPE||' AND FK_LOAN_ACCOUNTACC='||LACC_SN;
   END IF;
 
   SET SQL_QUERY = SELECT_STAT||' '||CONDITION;
 
   --CALL DBMS_OUTPUT.PUT_LINE(SQL_QUERY); --just for debugging
 
   PREPARE stmnt from 'set ? = (' || SQL_QUERY || ')';
   EXECUTE stmnt into LAMOUNT;
 
   IF TABLE_NAME IN ('R_LOAN_ACCOUNT', 'R_LOAN_ACCOUNT_INF')
      THEN SET LAMOUNT = LAMOUNT*(-1);
   END IF;
 
   RETURN LAMOUNT;
END;

