CREATE FUNCTION PROFITS.GETLOAN_PENALTY (
    PRODUCT_ID	INTEGER,
    CURR	INTEGER )
  RETURNS DECFLOAT(16)
  SPECIFIC SQL170120163750268
  NOT SECURED
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  READS SQL DATA
  INHERIT SPECIAL REGISTERS
BEGIN
DECLARE ttt DECFLOAT(16);
select I.PERCENTAGE INTO ttt
from int_scale I, LOAN L
where L.FKINT_HAS_OVERDUE=I.FK_INTERESTID_INTE
AND L.FK_PRODUCTID_PRODU=PRODUCT_ID
AND I.fk_currencyid_curr=Curr
ORDER BY VALIDITY_DATE DESC
FETCH FIRST 1 ROWS ONLY;
return ttt;
END;

