CREATE FUNCTION PROFITS.GETLOAN_RATE ( PROFITS_ACCOUNT VARCHAR(40) )
  RETURNS DECFLOAT(16)
  SPECIFIC SQL170120162622367
  NOT SECURED
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  READS SQL DATA
  INHERIT SPECIAL REGISTERS
BEGIN
DECLARE ttt DECFLOAT(16);
select sc.PERCENTAGE INTO ttt
     FROM LOAN_ACCOUNT L,
     PROFITS_ACCOUNT Pr,
     int_scale sc,
    bank_parameters p
WHERE PR.LNS_OPEN_UNIT = L.FK_UNITCODE
  AND PR.LNS_SN = L.ACC_SN
  AND PR.LNS_TYPE = L.ACC_TYPE
  AND sc.FK_INTERESTID_INTE= GetRateCode(p.curr_trx_date,  L.FKINT_PREV_FIXED,  L.PRV_FX_INT_EXP_DT, L.FKINT_CURRENT_FIX,  L.CUR_FX_INT_EXP_DT, L.FKINT_AS_FLOATING)
  and sc.validity_date=GETRATEVALDATE (p.curr_trx_date,  L.PRV_FX_INT_SCAL_DT,  L.PRV_FX_INT_EXP_DT, L.CUR_FX_INT_SCAL_DT,  L.CUR_FX_INT_EXP_DT, L.FKINT_AS_FLOATING, L.FKCUR_IS_MOVED_IN)
  and sc.fk_currencyid_curr= L.FKCUR_IS_MOVED_IN
  and pr.account_number=profits_account;
return ttt;
END;

