create table GL_CONFIG_AUDIT
(
    REPORT_NAME    VARCHAR(50),
    EXCEL_SHEET    VARCHAR(10),
    EXCEL_CELL     VARCHAR(10),
    GL_ACCOUNT     VARCHAR(50),
    GL_DESCRIPTION VARCHAR(500),
    AMOUNT_TYPE    VARCHAR(50),
    CURRENCY_TYPE  VARCHAR(10),
    CURRENCY       VARCHAR(10),
    FACTOR1        INTEGER,
    DATE_FROM      DATE,
    DATE_TO        DATE,
    AMOUNT         DECIMAL(15, 2)
);

