create table GLG_ENTEP_CTL
(
    ID                          CHAR(1),
    LEVELUNIT                   SMALLINT,
    LAST_PERIOD_UPDATE          SMALLINT,
    BACK_DAYS                   SMALLINT,
    TPT_PERIOD                  SMALLINT,
    LAST_OFFICIAL_RPT2          SMALLINT,
    LAST_PERIOD_UPD_NE          SMALLINT,
    LAST_OFFICIAL_RPT1          SMALLINT,
    NEXT_FISCYEAR               SMALLINT,
    KEPYO_YEAR                  SMALLINT,
    DEL_FISCYEAR                SMALLINT,
    TPT_YEAR                    SMALLINT,
    CURR_FISCYEAR               SMALLINT,
    FK_UNITCODE                 INTEGER,
    FK_CURRENCYID_CURR          INTEGER,
    KEPYO_REF                   INTEGER,
    AFM_AMOUNT                  DECIMAL(15, 2),
    TRANSFER_DATE               DATE,
    LAST_TO_DATE                DATE,
    TIMESTMP                    TIMESTAMP(6),
    TRANSFER_FLG                CHAR(1),
    GLI_TRX_EXTRACT_FL          CHAR(1),
    FCN_LEVEL                   CHAR(1),
    FEA_LEVEL                   CHAR(1),
    FK_GLG_DOCUMENTDO0          CHAR(2),
    FK_CURR_RATE_TYTYP          CHAR(3),
    FK_GLG_DOCUMENTDOC          CHAR(4),
    FK_USRCODE                  CHAR(8),
    PRFT_FX_ACCOUNT             CHAR(21),
    PRFT_FB_ACCOUNT             CHAR(21),
    FK_JOURNAL_INTERME          CHAR(21),
    FK_INTERMED_FCCINV          CHAR(21),
    FK_GLG_ACCOUNTACC6          CHAR(21),
    FK_GLG_ACCOUNTACC5          CHAR(21),
    FK_GLG_ACCOUNTACC4          CHAR(21),
    FK_GLG_ACCOUNTACC3          CHAR(21),
    FK_GLG_ACCOUNTACC1          CHAR(21),
    FK_GLG_ACCOUNTACC0          CHAR(21),
    FK_GLG_ACCOUNTACC2          CHAR(21),
    FK_GLG_ACCOUNTACCO          CHAR(21),
    KEPYO_AMNT                  DECIMAL(15, 2),
    LAST_CLOSED_PERIOD          SMALLINT,
    ANAL_GL_DATE                DATE not null,
    MUTUAL                      VARCHAR(1),
    MUTUAL_SKIP                 VARCHAR(1),
    ANAL_LEVEL                  CHAR(1)    default '9',
    REQ_PAIRS_GL                CHAR(1)    default '0',
    FK_GLG_ACC_CASH_DISCREPANCY VARCHAR(21),
    FEA_LEVEL_ADD               VARCHAR(1) default '0',
    FK_UNITCODE_80              INTEGER,
    FK_UNITCODE_81              INTEGER,
    FK_UNITCODE_82              INTEGER,
    AUTH_REQUIRED               VARCHAR(1) default '0',
    TC_CODE                     DECIMAL(10),
    FK_GLG_INTERBRANCH          CHAR(21),
    FK_PHASE_ID                 CHAR(2),
    FK_STAGE_ID                 DECIMAL(5),
    FK_VERSION_ID               DECIMAL(5),
    BUDGET_CONTROL              VARCHAR(1) default 'N'
);

create unique index IXU_GLG_067
    on GLG_ENTEP_CTL (ID);

