create table GLG_D_YEAR_RANGE
(
    FK_GLG_H_YEAR_RTRA CHAR(6),
    LINE_NUM           SMALLINT,
    DEACTIVATION_DATE  DATE,
    TIMESTMP           TIMESTAMP(6),
    CHANGE_STATUS_FLAG CHAR(1),
    STATUS             CHAR(1),
    FK_GLG_JUSTIFYJUS0 CHAR(4),
    FK_GLG_JUSTIFYJUST CHAR(4),
    FK_GLG_ACCOUNTACC0 CHAR(21),
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_GLG_ACCOUNTACC1 CHAR(21)
);

create unique index IXU_GLG_062
    on GLG_D_YEAR_RANGE (FK_GLG_H_YEAR_RTRA, LINE_NUM);

