create table GLG_FINAL_TOTALS
(
    FK_GH_SUBSYSTEM   CHAR(5) not null,
    FK_GD_SUBSYSTEM   INTEGER not null,
    FK_GLG_FINAL_DATE DATE    not null,
    FK_GLG_FINAL_UNIT INTEGER not null,
    TRX_CURRENCY_ID   INTEGER not null,
    MEMO_DB_AMNT      DECIMAL(15, 2),
    JOURNAL_CR_AMNT   DECIMAL(15, 2),
    JOURNAL_DB_AMNT   DECIMAL(15, 2),
    CASH_CR_AMNT      DECIMAL(15, 2),
    MEMO_CR_AMNT      DECIMAL(15, 2),
    B_JOURNAL_DB_AMNT DECIMAL(15, 2),
    CASH_DB_AMNT      DECIMAL(15, 2),
    B_MEMO_DB_AMNT    DECIMAL(15, 2),
    B_MEMO_CR_AMNT    DECIMAL(15, 2),
    B_JOURNAL_CR_AMNT DECIMAL(15, 2),
    constraint IXU_GL_055
        primary key (FK_GH_SUBSYSTEM, FK_GD_SUBSYSTEM, FK_GLG_FINAL_DATE, FK_GLG_FINAL_UNIT, TRX_CURRENCY_ID)
);

