create table GLG_UNIT_LIMITS
(
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_CURRENCYID_CURR INTEGER,
    FK_UNITCODE        INTEGER,
    ALERT_MAX_BAL      DECIMAL(15, 2),
    ALERT_MIN_AMOUNT   DECIMAL(15, 2),
    TIMESTMP           TIMESTAMP(6),
    STATUS             CHAR(1)
);

create unique index IXU_GLG_100
    on GLG_UNIT_LIMITS (FK_GLG_ACCOUNTACCO, FK_CURRENCYID_CURR, FK_UNITCODE);

