create table GLG_FORMAT
(
    FORMAT_ID     CHAR(1),
    NUM_OF_LEVELS SMALLINT,
    LEVEL02_SIZE  SMALLINT,
    LEVEL05_SIZE  SMALLINT,
    LEVEL01_SIZE  SMALLINT,
    LEVEL03_SIZE  SMALLINT,
    LEVEL04_SIZE  SMALLINT,
    TIMESTMP      TIMESTAMP(6),
    FORMAT        CHAR(21)
);

create unique index IXU_GLG_074
    on GLG_FORMAT (FORMAT_ID);

