create table GLG_END_YEAR_BAL
(
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_CURRENCYID_CURR INTEGER,
    FK_UNITCODE        INTEGER,
    CENTRALIZED_UNIT   INTEGER,
    CR_AMOUNT          DECIMAL(15, 2),
    DB_AMOUNT          DECIMAL(15, 2),
    LEVEL0             CHAR(1),
    TO_ACCOUNT         CHAR(21)
);

create unique index IXU_GLG_064
    on GLG_END_YEAR_BAL (FK_GLG_ACCOUNTACCO, FK_CURRENCYID_CURR, FK_UNITCODE);

