create table GLG_POOLRATE_HEADER
(
    TRAN_ID              CHAR(6) not null
        constraint IXU_GLG_POOLRATE_H
            primary key,
    DESCR                VARCHAR(100),
    CHANGE_STATUS_FLAG   CHAR(1),
    ENTRY_STATUS         CHAR(1),
    DEACTIVATION_DATE    DATE,
    FK_GLG_ACCOUNTACC0   CHAR(21),
    FK_CURRENCYID_CURR   INTEGER,
    FK_GLG_DOCUMENTDOC   CHAR(4),
    FK_GLG_DOCUMENTDO0   CHAR(2),
    FK_GLG_ACCOUNTACCO   CHAR(21),
    FK_GLG_ACCOUNTACC1   CHAR(21),
    FK_GLG_ACCOUNTACC2   CHAR(21),
    FK_CURRENCYID_CUR0   INTEGER,
    TIMESTMP             TIMESTAMP(6),
    VALIDITY_DATE        CHAR(1),
    FK_GLG_JUSTIFYJUST   CHAR(4),
    FK_GLG_JUSTIFYJUS0   CHAR(4),
    REMARKS              VARCHAR(100),
    LAST_CALCULATED_DATE DATE,
    FK_GLG_ACCOUNTACC3   CHAR(21)
);

