create table GLG_ACCOUNT_DEFAULT
(
    ACCOUNT_ID         CHAR(21) not null
        constraint PK_DEFACC_99
            primary key,
    LEVEL0             CHAR(1),
    STATE              CHAR(1),
    EVAL_FLAG          CHAR(1),
    CENTRAL_FLAG       CHAR(1),
    COST_ACC_FLAG      CHAR(1),
    COST_USED_CNTR     SMALLINT,
    UNIT_REAL_TIME     CHAR(1),
    UPDATE_WAY_IND     CHAR(1),
    CLASS_TYPE         CHAR(1),
    POSITION_FLAG      CHAR(1),
    SUBS_CONS_FLAG     CHAR(1),
    SUBSID_COUNT       INTEGER,
    DB_CR_BAL_FLAG     CHAR(1),
    UPDATED_FLAG       CHAR(1),
    SHORT_DESCR        VARCHAR(30),
    DESCR              VARCHAR(60),
    OPTIONAL_FLAG      CHAR(1),
    DSUB_TRN_FLAG      CHAR(1),
    REAL_TIME_FLAG     CHAR(1),
    RECON_FLAG         CHAR(1),
    FCCONV_FLAG        CHAR(1),
    VALEUR_DATE        CHAR(1),
    LAST_UPD_DATE      DATE,
    DEACTIVATION_DATE  DATE,
    MAND_ADDITIONAL_IN CHAR(1),
    MAND_CUST_INFO     CHAR(1),
    MODIFY_DATE        DATE,
    OPEN_DATE          DATE,
    SEC_LEVEL          SMALLINT,
    BOP_FLG            CHAR(1),
    BOP_GROUP_ACCOUNT  INTEGER,
    RECON_START_DT     DATE,
    RECON_RUN_DT       DATE,
    CNFTAX_FLAG        CHAR(1),
    VALEUR_FLG         CHAR(1),
    STATUS             CHAR(1),
    TIMESTMP           TIMESTAMP(6),
    UNIT_GROUP_ID      INTEGER,
    EXTERNAL_GLACCOUNT CHAR(21),
    FK_GLG_H_CURR_GGRO CHAR(4),
    FK0USRCODE         CHAR(8),
    FK_USRCODE         CHAR(8),
    FK_GH_HAS_PERM_UNI CHAR(5),
    FK_GD_HAS_PERM_UNI INTEGER,
    FK_GH_HAS_SUBSYS   CHAR(5),
    FK_GD_HAS_SUBSYS   INTEGER,
    FK_GLG_REPORT_ATRN CHAR(6)
);

