create table GLG_PROCESS_CTL
(
    USR        CHAR(8)  not null,
    USER_SN    SMALLINT not null,
    PROCESS_ID CHAR(6)  not null,
    YEAR0      SMALLINT,
    PERIOD
    SMALLINT,
    LEVEL0 CHAR
(
    1
),
    PREV_YEAR SMALLINT,
    FROM_JUST_ID CHAR(4),
    TO_JUST_ID CHAR(4),
    FROM_JOURNAL_ID CHAR(2),
    TO_JOURNAL_ID CHAR(2),
    FROM_UNIT INTEGER,
    TO_UNIT INTEGER,
    FROM_CURR_ID INTEGER,
    TO_CURR_ID INTEGER,
    FROM_DATE DATE,
    TO_DATE DATE,
    FROM_ACCOUNT_ID CHAR(21),
    TO_ACCOUNT_ID CHAR(21),
    FROM_DOC_ID CHAR(4),
    TO_DOC_ID CHAR(4),
    FROM_DOC_SERIES CHAR(2),
    TO_DOC_SERIES CHAR(2),
    FROM_DOC_NUM INTEGER,
    TO_DOC_NUM INTEGER,
    FROM_GROUP_ID CHAR(4),
    TO_GROUP_ID CHAR(4),
    FROM_TAX_TYPE CHAR(4),
    TO_TAX_TYPE CHAR(4),
    FROM_TAX_ID CHAR(4),
    TO_TAX_ID CHAR(4),
    MODEL_TRN_TYPE CHAR(1),
    FROM_MODEL_ID CHAR(6),
    TO_MODEL_ID CHAR(6),
    FINANCIAL_REP_ID CHAR(2),
    FROM_REF_NUM DECIMAL(10),
    TO_REF_NUM DECIMAL(10),
    TIMESTMP TIMESTAMP(6),
    constraint PIXGLGPR
        primary key (USR, USER_SN, PROCESS_ID)
    );

