create table GLG_RECON_ARTICLE
(
    TIMESTMP           TIMESTAMP(6),
    TRAN_TYPE          CHAR(1),
    ENTRY_STATUS       CHAR(1),
    FK_GLG_DOCUMENTDOC CHAR(2),
    FK0GLG_JUSTIFYJUST CHAR(4),
    FK_GLG_JUSTIFYJUST CHAR(4),
    FK0GLG_DOCUMENTDOC CHAR(4),
    FK_GLG_ACCOUNTACCO CHAR(21)
);

create unique index PK_RECON_ARTICLE
    on GLG_RECON_ARTICLE (TRAN_TYPE);

