create table GLG_ENTEP_LIMITS
(
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_CURRENCYID_CURR INTEGER,
    ALERT_MAX_BAL      DECIMAL(15, 2),
    ALERT_MIN_BAL      DECIMAL(15, 2),
    TIMESTMP           TIMESTAMP(6),
    DEACTIVATION_DATE  DATE,
    STATUS             CHAR(1)
);

create unique index IXU_GLG_068
    on GLG_ENTEP_LIMITS (FK_GLG_ACCOUNTACCO, FK_CURRENCYID_CURR);

