create table GLG_INTERFACE_MIG
(
    FK_USRCODE         CHAR(8)  not null,
    FK_UNITCODE        INTEGER  not null,
    TRN_DATE           DATE     not null,
    TRN_SNUM           INTEGER  not null,
    LINE_NUM           SMALLINT not null,
    FK1UNITCODE        INTEGER,
    FK_CURR_TABLE_PFK  INTEGER,
    FK0UNITCODE        INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK_CUSTOMERCODE    INTEGER,
    DOC_NUM            INTEGER,
    FK_CURR_TABLE_PFK0 DECIMAL(10),
    DEAL_SLIP_NUM      DECIMAL(10),
    REF_NUM            DECIMAL(10),
    RATE               DECIMAL(12, 6),
    AMOUNT             DECIMAL(15, 2),
    VALEUR_DATE        DATE,
    GL_TRN_DATE        DATE,
    CANCEL_DATE        DATE,
    ENTRY_TYPE         CHAR(1),
    LEVEL0             CHAR(1),
    AUTO_FLAG          CHAR(1),
    STATUS             CHAR(1),
    RECON_FLAG         CHAR(1),
    REF_NUM_FLAG       CHAR(1),
    PRIM_AGRE_IND      CHAR(1),
    TRN_TYPE           CHAR(1),
    TRN_ACTION_TYPE    CHAR(1),
    DOC_TYPE           CHAR(1),
    SUBSYSTEM          CHAR(2),
    FK_GLG_JOURNALJOUR CHAR(2),
    FK_GLG_DOCUMENTDO0 CHAR(2),
    FK_GLG_JUSTIFYJUST CHAR(4),
    FK_GLG_DOCUMENTDOC CHAR(4),
    FK_GLG_CURR_CATCUR CHAR(4),
    FK_COST_MODEL_TTRN CHAR(6),
    FK_GLG_MODEL_TRTRN CHAR(6),
    TAX_REG_NO         CHAR(10),
    DOC_CTL_NUM        CHAR(20),
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_TERMINALTERMINA CHAR(99),
    REMARKS            VARCHAR(80),
    constraint IXU_GL_034
        primary key (FK_USRCODE, FK_UNITCODE, TRN_DATE, TRN_SNUM, LINE_NUM)
);

