create table GLG_UNIT_DOC
(
    FK_UNITCODE        INTEGER,
    FK_GLG_DOCUMENTDO0 CHAR(2),
    FK_GLG_DOCUMENTDOC CHAR(4),
    LAST_NUM_CYEAR     DECIMAL(15),
    LAST_NUM_NYEAR     DECIMAL(15),
    LAST_UPDATE_DATE   DATE,
    VALIDITY_DATE      DATE,
    DEACTIVATION_DATE  DATE,
    TIMESTMP           TIMESTAMP(6),
    STATUS             CHAR(1),
    CHANGE_STATUS_FLAG CHAR(1)
);

create unique index IXU_GLG_097
    on GLG_UNIT_DOC (FK_UNITCODE, FK_GLG_DOCUMENTDO0, FK_GLG_DOCUMENTDOC);

