create table GLG_RECONS
(
    REF_NUM            DECIMAL(10),
    AGRE_UNIT_CR_AMOUN DECIMAL(15, 2),
    PRIM_UNIT_CR_AMOUN DECIMAL(15, 2),
    AGRE_UNIT_DB_AMOUN DECIMAL(15, 2),
    PRIM_UNIT_DB_AMOUN DECIMAL(15, 2),
    STATUS             CHAR(1),
    FK_CURRENCYID_CURR DECIMAL(10),
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_UNITCODE        INTEGER,
    FK0UNITCODE        INTEGER
);

create unique index IXU_GLG_090
    on GLG_RECONS (REF_NUM);

