create table GLG_RECON_MULT
(
    FK0GLG_RECONACCOUN CHAR(21),
    FK0GLG_RECONTRN_UN INTEGER,
    FK0GLG_RECONGL_TRN DATE,
    FK0GLG_RECONDOC_ID CHAR(4),
    FK0GLG_RECONDOC_SE CHAR(2),
    FK0GLG_RECONDOC_NU INTEGER,
    FK0GLG_RECONLINE_N SMALLINT,
    FK0GLG_RECONCURREN INTEGER,
    FK_GLG_RECONACCOUN CHAR(21),
    FK_GLG_RECONTRN_UN INTEGER,
    FK_GLG_RECONGL_TRN DATE,
    FK_GLG_RECONDOC_ID CHAR(4),
    FK_GLG_RECONDOC_SE CHAR(2),
    FK_GLG_RECONDOC_NU INTEGER,
    FK_GLG_RECONLINE_N SMALLINT,
    FK_GLG_RECONCURREN INTEGER,
    TIMESTMP           TIMESTAMP(6),
    TRX_USR            CHAR(8)
);

create unique index IXU_GLG_089
    on GLG_RECON_MULT (FK0GLG_RECONACCOUN, FK0GLG_RECONTRN_UN, FK0GLG_RECONGL_TRN, FK0GLG_RECONDOC_ID,
                       FK0GLG_RECONDOC_SE, FK0GLG_RECONDOC_NU, FK0GLG_RECONLINE_N, FK0GLG_RECONCURREN,
                       FK_GLG_RECONACCOUN, FK_GLG_RECONTRN_UN, FK_GLG_RECONGL_TRN, FK_GLG_RECONDOC_ID,
                       FK_GLG_RECONDOC_SE, FK_GLG_RECONDOC_NU, FK_GLG_RECONLINE_N, FK_GLG_RECONCURREN);

