create table GLI_INTERFACE
(
    FK_UNITCODE        INTEGER,
    FK_USRCODE         CHAR(8),
    TRN_DATE           DATE,
    TRN_SNUM           INTEGER,
    LINE_NUM           SMALLINT,
    PRF_ACC_CD         SMALLINT,
    AMOUNT_SER_NO      SMALLINT,
    DEPT_SN            INTEGER,
    FK_TRANSACTION0ID  INTEGER,
    FK_CURR_TABLE_PFK  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK1UNITCODE        INTEGER,
    FK0UNITCODE        INTEGER,
    FK_CUSTOMERCODE    INTEGER,
    FK_CURR_TABLE_PFK0 INTEGER,
    DOC_NUM            INTEGER,
    DEAL_SLIP_NUM      DECIMAL(10),
    REF_NUM            DECIMAL(10),
    ACCOUNT_NUMBER     DECIMAL(11),
    REATE              DECIMAL(12, 6),
    AMOUNT             DECIMAL(15, 2),
    VALEUR_DATE        DATE,
    GL_TRN_DATE        DATE,
    CANCEL_DATE        DATE,
    AUTO_FLAG          CHAR(1),
    STATUS             CHAR(1),
    ENTRY_TYPE         CHAR(1),
    ACCOUNTED_FLAG     CHAR(1),
    RECON_FLAG         CHAR(1),
    TRN_ACTION_TYPE    CHAR(1),
    REF_NUM_FLAG       CHAR(1),
    DOC_TYPE           CHAR(1),
    PRIM_AGRE_IND      CHAR(1),
    TRN_TYPE           CHAR(1),
    LEVEL0             CHAR(1),
    FK_GLG_DOCUMENTDO0 CHAR(2),
    FK_GLG_JOURNALJOUR CHAR(2),
    SUBSYSTEM          CHAR(2),
    GLACC_ORIGIN       CHAR(2),
    FK_GLG_JUSTIFYJUST CHAR(4),
    FK_GLG_CURR_CATCUR CHAR(4),
    FK_GLG_DOCUMENTDOC CHAR(4),
    FK_GLG_MODEL_TRTRN CHAR(6),
    FK_COST_MODEL_TTRN CHAR(6),
    DOC_CTL_NUM        CHAR(9),
    TAX_REG_NO         CHAR(10),
    FK_GLG_ACCOUNTACCO CHAR(21),
    REMARKS            CHAR(50),
    PRF_ACCOUNT_NUMBER CHAR(40),
    FK_TERMINALTERMINA CHAR(99),
    ID_PRODUCT         DECIMAL(5)
);

create unique index IDX_GLI_VW1
    on GLI_INTERFACE (FK_GLG_ACCOUNTACCO, TRN_DATE, FK_CURRENCYID_CURR, FK1UNITCODE, REMARKS);

create unique index IXN_GLG_002
    on GLI_INTERFACE (FK1UNITCODE, FK_CURRENCYID_CURR, FK_GLG_ACCOUNTACCO, GL_TRN_DATE);

create unique index IXN_GLG_003
    on GLI_INTERFACE (REMARKS);

create unique index IXU_GLI_001
    on GLI_INTERFACE (FK_UNITCODE, FK_USRCODE, TRN_DATE, TRN_SNUM, LINE_NUM);

