CREATE VIEW GLI_TRX_EXTRACT_GL_ACC_VIEW
(
   FK_GLG_ACCOUNTACCO,
   FK1UNITCODE,
   ID_CURRENCY,
   TRX_USR,
   FC_AMOUNT,
   ENTRY_TYPE,
   SUBSYSTEM,
   TRX_CODE,
   ID_JUSTIFIC,
   TRN_DATE,
   REMARKS
)
    AS SELECT A.FK_GLG_ACCOUNTACCO AS FK_GLG_ACCOUNTACCO,
              A.FK1UNITCODE AS FK1UNITCODE,
			  A.FK_CURRENCYID_CURR AS ID_CURRENCY,
              TRIM(A.TRX_USR) AS TRX_USR,
              A.AMOUNT AS FC_AMOUNT,
              A.ENTRY_TYPE,
              A.SUBSYSTEM,
              A.FK_TRANSACTION0ID AS TRX_CODE,
              A.FK_JUSTIFICID_JUST AS ID_JUSTIFIC,
              A.TRN_DATE,
              A.REMARKS
         FROM DEP_GLI_INTERFACE A
        WHERE A.TRN_DATE           IN (SELECT D.SELECTED_DATE FROM GL_EXTRACT_CRITERIA D)
          AND A.FK_CURRENCYID_CURR IN (SELECT D.ID_CURRENCY   FROM GL_EXTRACT_CRITERIA D)
		  AND A.REMARKS            >= (SELECT MIN(D.LAST_REMARKS)  FROM GL_EXTRACT_CRITERIA D)
        UNION ALL
       SELECT A.FK_GLG_ACCOUNTACCO AS FK_GLG_ACCOUNTACCO,
              A.FK1UNITCODE AS FK1UNITCODE,
			  A.FK_CURRENCYID_CURR AS ID_CURRENCY,
              SUBSTR(A.REMARKS, 16, LENGTH(TRIM(A.REMARKS)) - 16 - 11) AS TRX_USR,
              A.AMOUNT AS FC_AMOUNT,
              A.ENTRY_TYPE,
              A.SUBSYSTEM,
              A.FK_TRANSACTION0ID AS TRX_CODE,
              A.FK_JUSTIFICID_JUST AS ID_JUSTIFIC,
              A.TRN_DATE,
              A.REMARKS
         FROM LNS_GLI_INTERFACE A
        WHERE A.TRN_DATE           IN (SELECT D.SELECTED_DATE FROM GL_EXTRACT_CRITERIA D)
          AND A.FK_CURRENCYID_CURR IN (SELECT D.ID_CURRENCY   FROM GL_EXTRACT_CRITERIA D)
		  AND A.REMARKS            >= (SELECT MIN(D.LAST_REMARKS)  FROM GL_EXTRACT_CRITERIA D)
        UNION ALL
       SELECT A.FK_GLG_ACCOUNTACCO AS FK_GLG_ACCOUNTACCO,
              A.FK1UNITCODE AS FK1UNITCODE,
			  A.FK_CURRENCYID_CURR AS ID_CURRENCY,
              TRIM(A.TRX_USR) AS TRX_USR,
              A.AMOUNT AS FC_AMOUNT,
              A.ENTRY_TYPE,
              A.SUBSYSTEM,
              A.FK_TRANSACTION0ID AS TRX_CODE,
              A.FK_JUSTIFICID_JUST AS ID_JUSTIFIC,
              A.TRN_DATE,
              A.REMARKS
         FROM FXFT_GLI_INTERFACE A
        WHERE A.TRN_DATE           IN (SELECT D.SELECTED_DATE FROM GL_EXTRACT_CRITERIA D)
          AND A.FK_CURRENCYID_CURR IN (SELECT D.ID_CURRENCY   FROM GL_EXTRACT_CRITERIA D)
		  AND A.REMARKS            >= (SELECT MIN(D.LAST_REMARKS)  FROM GL_EXTRACT_CRITERIA D)
        UNION ALL
       SELECT A.FK_GLG_ACCOUNTACCO AS FK_GLG_ACCOUNTACCO,
              A.FK1UNITCODE AS FK1UNITCODE,
			  A.FK_CURRENCYID_CURR AS ID_CURRENCY,
              SUBSTR(A.REMARKS, 16, LENGTH(TRIM(A.REMARKS)) - 16 - 11) AS TRX_USR,
              A.AMOUNT AS FC_AMOUNT,
              A.ENTRY_TYPE,
              A.SUBSYSTEM,
              A.FK_TRANSACTION0ID AS TRX_CODE,
              A.FK_JUSTIFICID_JUST AS ID_JUSTIFIC,
              A.TRN_DATE,
              A.REMARKS
         FROM GLI_INTERFACE A
        WHERE A.TRN_DATE           IN (SELECT D.SELECTED_DATE FROM GL_EXTRACT_CRITERIA D)
          AND A.FK_CURRENCYID_CURR IN (SELECT D.ID_CURRENCY   FROM GL_EXTRACT_CRITERIA D)
		  AND A.REMARKS            >= (SELECT MIN(D.LAST_REMARKS)  FROM GL_EXTRACT_CRITERIA D)
        UNION ALL
       SELECT A.FK_GLG_ACCOUNTACCO AS FK_GLG_ACCOUNTACCO,
              A.FK1UNITCODE AS FK1UNITCODE,
			  A.FK_CURRENCYID_CURR AS ID_CURRENCY,
              SUBSTR(A.REMARKS, 16, LENGTH(TRIM(A.REMARKS)) - 16 - 11) AS TRX_USR,
              A.AMOUNT AS FC_AMOUNT,
              A.ENTRY_TYPE,
              A.SUBSYSTEM,
              A.FK_TRANSACTION0ID AS TRX_CODE,
              A.FK_JUSTIFICID_JUST AS ID_JUSTIFIC,
              A.TRN_DATE,
              A.REMARKS
         FROM PRF_GLI_INTERFACE A
        WHERE A.TRN_DATE           IN (SELECT D.SELECTED_DATE FROM GL_EXTRACT_CRITERIA D)
          AND A.FK_CURRENCYID_CURR IN (SELECT D.ID_CURRENCY   FROM GL_EXTRACT_CRITERIA D)
		  AND A.REMARKS            >= (SELECT MIN(D.LAST_REMARKS)  FROM GL_EXTRACT_CRITERIA D);

