create table GLOBAL_ORDERS
(
    ID                            DECIMAL(15) not null,
    GLOBAL_ORDER_CODE             VARCHAR(50) not null,
    DIRECTION                     CHAR(1)     not null,
    MESSAGE_TYPE                  VARCHAR(40) not null,
    PRFT_CUST_ID                  INTEGER,
    PRFT_CUST_ACCOUNT_NUMBER      CHAR(40),
    ID_PRODUCT                    INTEGER,
    ID_TRANSACT                   INTEGER,
    ID_JUSTIFIC                   INTEGER,
    ORDER_AMOUNT                  DECIMAL(18, 2),
    ORDER_CURRENCY                INTEGER,
    FK_GH_CHARGE_BEARER           VARCHAR(5),
    FK_GD_CHARGE_BEARER           INTEGER,
    BENEF_ACCOUNT                 VARCHAR(37),
    BENEF_BIC                     VARCHAR(11),
    BENEF_SORT_CODE               VARCHAR(11),
    BENEF_NAME                    VARCHAR(100),
    BENEF_ADDRESS_LINE_1          VARCHAR(80),
    BENEF_ADDRESS_LINE_2          VARCHAR(80),
    BENEF_ISO_COUNTRY             CHAR(2),
    ORDER_COMMENTS                VARCHAR(250),
    DEAL_USR_CODE                 VARCHAR(8),
    DEAL_REF_NO                   VARCHAR(20),
    PROCESSING_STATUS             SMALLINT,
    PROCESSING_RESULTS            VARCHAR(250),
    EXTERNAL_ID_REF               VARCHAR(50),
    RELATED_GLOBAL_ORDER_CODE     VARCHAR(50),
    FK_GLOBAL_GENERAL_ROUTING_SN  INTEGER,
    FK_GLOBAL_CUSTOMER_ROUTING_SN INTEGER,
    FKGH_ROUTING_RESULT           VARCHAR(5),
    FKGD_ROUTING_RESULT           INTEGER,
    FKGD_ROUTING_RESULT_DESCR     VARCHAR(40),
    PRFT_PROCESS_TYPE             VARCHAR(10),
    PRFT_CORRESP_ACCOUNT          VARCHAR(40),
    PRF_CORRESP_CUST_ID           INTEGER,
    PRFT_ORDER_LOGICAL_KEY        VARCHAR(50),
    PRFT_ORDER_SEC_LOGICAL_KEY    VARCHAR(50),
    AML_STATUS                    SMALLINT,
    AML_RESULT                    VARCHAR(250),
    TRX_DATE                      DATE,
    TRX_USR                       VARCHAR(8),
    TRX_UNIT                      INTEGER,
    TMSTAMP                       TIMESTAMP(6),
    SYSTEM_DATE                   DATE,
    FINANCIAL_DATE                DATE,
    TRANSFER_DATE                 DATE,
    ORDER_VALUE_DATE              DATE,
    PRIORITY                      CHAR(1),
    WEB_USER_CUST_ID              INTEGER,
    HAS_ATTACHMENT                CHAR(1),
    HAS_RATE_REQUEST              CHAR(1),
    HAS_MANDATES                  CHAR(1),
    TRX_RATE_GIVEN                DECIMAL(12, 6),
    TRX_SETTLEMENT_AMN            DECIMAL(18, 2),
    TRX_COLLECTED_AMN             DECIMAL(18, 2),
    TRX_COMMISSION_AMN            DECIMAL(18, 2),
    TRX_EXPENSES_AMN              DECIMAL(18, 2),
    TRX_TAX_AMN                   DECIMAL(18, 2),
    TRX_OMNI_ID                   DECIMAL(10),
    CORE_CANCELLED                CHAR(1),
    CORE_EXECUTED                 CHAR(1),
    TRX_OMNI_APP_ID               DECIMAL(10),
    PROCESSED_STATUS              SMALLINT,
    TRX_USR_SN                    INTEGER,
    IPROFITS_STATUS               SMALLINT,
    SAME_DAY_VALUE                CHAR(1),
    TARGET_ACCOUNT_CREDIT_AMOUNT  DECIMAL(18, 2),
    constraint PKEY_ID
        primary key (GLOBAL_ORDER_CODE, ID)
);

comment on table GLOBAL_ORDERS is 'The Global table for all Profits Payment Orders-Incoming/Outgoing-All Services (SWIFT/SEPA/INSTAN/NON-SWIFT/CLEARBANK etc)-All Message Types (Orders & R-Messages)';

comment on column GLOBAL_ORDERS.DIRECTION is 'I: Incoming to ProfitsO: Outgoing from Profits';

comment on column GLOBAL_ORDERS.PROCESSING_STATUS is '0: Initial (Before Routing Decision)1:ToBeSettled (Routing Decided - Profits Subsystem will be called)3.Settled_OK (Sucesfully Processed by Profits Subsystem)99:Failed';

comment on column GLOBAL_ORDERS.AML_STATUS is '0:NOT_SEND1:SEND2:PASS3:FAILED4:SOFT_STOP"';

