create table GLOBAL_ORDERS_DETAIL
(
    ID                     DECIMAL(15) not null,
    GLOBAL_ORDER_CODE      VARCHAR(50) not null,
    PRFT_ORDER_LOGICAL_KEY VARCHAR(50),
    COR_CBR                CHAR(20),
    BIC_BANK_CODE          CHAR(9),
    INN_TAXPAYER_CODE      CHAR(12),
    KPP_BENEFICIARY        CHAR(9),
    VOC_GH_CODE            CHAR(5),
    VOC_GD_CODE            INTEGER,
    BOP_GH                 CHAR(5),
    BOP_GD                 INTEGER,
    ORDERING_CUST_NAME     VARCHAR(100),
    ORDERING_CUST_ADDRESS  VARCHAR(80),
    ORDERING_CUST_COUNTRY  VARCHAR(80),
    ORDERING_CUST_ACCOUNT  CHAR(37),
    ORDERING_CUST_SORT     CHAR(11),
    ORDERING_CUST_BIC      CHAR(11),
    ORDERING_CUST_COMMENTS VARCHAR(140),
    ORDERING_CUST_VALUE_DT DATE,
    PAYROLL_GROUP_NUMBER   DECIMAL(10),
    PAYROLL_FILENAME       VARCHAR(50),
    PAYROLL_FILE_HASH      VARCHAR(50),
    PAYROLL_DATA_ROW_SN    INTEGER,
    constraint PK_GO_DTL
        primary key (GLOBAL_ORDER_CODE, ID)
);

