create table GLOBAL_ROUTE_COUNTRY
(
    COUNTRY_TYPE   CHAR(1),
    ENTRY_COMMENTS VARCHAR(100),
    CREATE_UNIT    INTEGER,
    CREATE_DATE    DATE,
    CREATE_USR     CHAR(8),
    CREATE_TMSTAMP TIMESTAMP(6),
    UPDATE_UNIT    INTEGER,
    UPDATE_DATE    DATE,
    UPDATE_USR     CHAR(8),
    UPDATE_TMSTAMP TIMESTAMP(6),
    ENTRY_STATUS   CHAR(1),
    FK_GH_COUNTRY  CHAR(5) not null,
    FK_GD_COUNTRY  INTEGER not null,
    FK_ROUTE       INTEGER not null,
    constraint PK_GLOBAL_COUNTRY
        primary key (FK_GH_COUNTRY, FK_GD_COUNTRY, FK_ROUTE)
);

