create table GUARANTEE_ORDER
(
    ID_GUARANTEE     INTEGER,
    UNPAID_COLL_CNT  SMALLINT,
    CONFIRM_END_PRD  SMALLINT,
    EXPIRY_DT        DATE,
    TMSTAMP          TIMESTAMP(6),
    EFFECTIVE_DT     DATE,
    ENTRY_STATUS     CHAR(1),
    DESCRIPTION      CHAR(40),
    GUARANT_GOV_CODE CHAR(40),
    GUAR_ORDER_CODE  CHAR(40),
    ENTRY_COMMENTS   CHAR(50)
);

create unique index IXU_GUA_000
    on GUARANTEE_ORDER (ID_GUARANTEE);

