create table HAGREEMENT_TYPE
(
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    TMSTAMP            TIMESTAMP(6),
    ONE_ACCOUNT_FLG    CHAR(1),
    ACC_EXPIRY         CHAR(1),
    AGR_EXPIRY         CHAR(1),
    AGR_LIMIT_IND      CHAR(1),
    DELIVERED_FLG      CHAR(1)
);

create unique index IXU_HAG_000
    on HAGREEMENT_TYPE (FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT);

