create table HAGR_TRXJUST
(
    FK_HAGREEMENT_TFK  INTEGER,
    FK0HAGREEMENT_TFK  DATE,
    FK_PRFT_TRANSACID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    VALIDITY_DATE      DATE,
    FK_PARAMETRIC_RSN2 SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_ACCOUNTING_RID  INTEGER,
    FK_PARAMETRIC_RID  INTEGER,
    FK_PARAMETRIC_RID2 INTEGER,
    TMSTAMP            TIMESTAMP(6),
    DELIVERED_FLG      CHAR(1),
    ENTRY_STATUS       CHAR(1),
    HOME_BRANCH        CHAR(1),
    PROFIT_INDICATOR   CHAR(1)
);

create unique index IXU_HAG_001
    on HAGR_TRXJUST (FK_HAGREEMENT_TFK, FK0HAGREEMENT_TFK, FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST, VALIDITY_DATE);

