create table HCLASS_GL_TD_H_DET
(
    FK_PRODUCTID_PRODU INTEGER not null,
    FK_HPRODUCTVALIDIT DATE    not null,
    FK_GEN_DET_FINSC   CHAR(5) not null,
    FK_GEN_DET_FINSCV  INTEGER not null,
    FK_GENERIC_DETAFK  CHAR(5) not null,
    FK_GENERIC_DETASER INTEGER not null,
    FK_CUST_CATEG_GH   CHAR(5) not null,
    FK_CUST_CATEG_GD   INTEGER not null,
    FK_GLG_H_CURR_GGRO CHAR(4) not null,
    ACCNT_STATUS       CHAR(1) not null,
    ACCNT_CLASS        CHAR(1) not null,
    DURATION_DAYS_TO   INTEGER not null,
    ORIGIN_ID          CHAR(2) not null,
    ORIGIN_TYPE        CHAR(1) not null,
    CHARGE_CODE        INTEGER not null,
    FK_GLG_ACCOUNT     CHAR(21),
    COMMENTS           VARCHAR(200),
    constraint PKHCLASSGLTDD
        primary key (FK_PRODUCTID_PRODU, FK_HPRODUCTVALIDIT, FK_GEN_DET_FINSC, FK_GEN_DET_FINSCV, FK_GENERIC_DETAFK,
                     FK_GENERIC_DETASER, FK_CUST_CATEG_GH, FK_CUST_CATEG_GD, FK_GLG_H_CURR_GGRO, ACCNT_STATUS,
                     ACCNT_CLASS, DURATION_DAYS_TO, ORIGIN_ID, ORIGIN_TYPE, CHARGE_CODE)
);

