create table HCLASS_GL
(
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    FK_CUST_CATEG_GH   CHAR(5),
    FK_CUST_CATEG_GD   INTEGER,
    LOAN_STATUS        CHAR(1),
    FK_CODE_N1_GD      INTEGER,
    TIMESTMP           TIMESTAMP(6),
    DR_INT_NOTAX_GLLVL CHAR(1),
    ENTRY_STATUS       CHAR(1),
    CR_INT_ACCR_GL_LVL CHAR(1),
    DR_INT_ACCR_GL_LVL CHAR(1),
    CR_INT_GL_ACC_LVL  CHAR(1),
    DR_INT_GL_ACC_LVL  CHAR(1),
    CR_CNTR_GL_ACC_LVL CHAR(1),
    DR_CNTR_GL_ACC_LVL CHAR(1),
    DELIVERED_FLG      CHAR(1),
    GL_ACCRUAL_LVL     CHAR(1),
    GL_NETWORK_LVL     CHAR(1),
    CR_INT_NOTAX_GLLVL CHAR(1),
    FK_CODE_N1_GH      CHAR(5),
    CR_INT_NOTAX_GLACC CHAR(21),
    DR_INT_ACCR_GL_ACC CHAR(21),
    GL_ACCRUAL_ACC     CHAR(21),
    CR_CNTR_GL_ACC     CHAR(21),
    DR_CNTR_GL_ACC     CHAR(21),
    CR_INT_ACCR_GL_ACC CHAR(21),
    CR_INT_GL_ACC      CHAR(21),
    DR_INT_NOTAX_GLACC CHAR(21),
    GL_NETWORK_ACC     CHAR(21),
    DR_INT_GL_ACC      CHAR(21)
);

create unique index IXU_HCL_000
    on HCLASS_GL (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT, FK_CUST_CATEG_GH,
                  FK_CUST_CATEG_GD, LOAN_STATUS);

