create table HCOLLATERAL_TYPE
(
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    COL_MECHANISM      SMALLINT,
    TOLERANCE_DAYS     SMALLINT,
    FK_GENERIC_DETASER INTEGER,
    VALUE_FCT          DECIMAL(8, 4),
    YIELD_PERC         DECIMAL(8, 4),
    LGDC               DECIMAL(8, 4),
    LGD                DECIMAL(8, 4),
    LGDCC              DECIMAL(8, 4),
    RELIABILITY_FCT    DECIMAL(8, 4),
    CB_ASSUR_FACTOR    DECIMAL(8, 4),
    TMSTAMP            TIMESTAMP(6),
    GL_ACC_LEVEL_DB    CHAR(1),
    BASEL_II_ACPT      CHAR(1),
    ASSOC_UNIQUE_IND   CHAR(1),
    COLL_EXP_DT_IND    CHAR(1),
    REVALUATION_DT_IND CHAR(1),
    ASSOCIATION_IND    CHAR(1),
    AUTOM_REMOV_FLAG   CHAR(1),
    UNIT_IND           CHAR(1),
    NOTE_IND           CHAR(1),
    CUST_DETAILS_IND   CHAR(1),
    ITEM_CNT_IND       CHAR(1),
    COLLATERAL_CATEGOR CHAR(1),
    CB_ASSUR_CALC_IND  CHAR(1),
    ACC_NO_IND         CHAR(1),
    COLLATERAL_CODE_IN CHAR(1),
    GL_ACC_LEVEL_CR    CHAR(1),
    LAND_REGISTRY_IND  CHAR(1),
    ASSUR_VAL_CALC_IND CHAR(1),
    FK_GENERIC_DETAFK  CHAR(5),
    GENERAL_FLGS       CHAR(10),
    RELIABILITY_CODE   CHAR(10),
    GL_ACCOUNT_DB      CHAR(21),
    GL_ACCOUNT_CR      CHAR(21),
    FK_DYNAMIC_FIELD   CHAR(20)
);

create unique index IXU_HCO_003
    on HCOLLATERAL_TYPE (FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT);

