create table HCOLL_TRXJUST
(
    FK_PRFT_TRANSACID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    FK_PARAMETRIC_RSN2 SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_HCOLLATERAL_FK  INTEGER,
    FK_PARAMETRIC_RID2 INTEGER,
    FK_PARAMETRIC_RID  INTEGER,
    FK_ACCOUNTING_RID  INTEGER,
    FK0HCOLLATERAL_FK  DATE,
    VALIDITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    PROFIT_INDICATOR   CHAR(1),
    HOME_BRANCH        CHAR(1),
    DELIVERED_FLG      CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_HCO_006
    on HCOLL_TRXJUST (FK_HCOLLATERAL_FK, FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST, VALIDITY_DATE);

