create table HCOMPOSITE_TRX
(
    FK0JUSTIFICID_JUST INTEGER,
    FK0TRANSACTION0ID  INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    FK_JUSTIFICID_JUST INTEGER,
    FK_TRANSACTION0ID  INTEGER,
    VALIDITY_DATE      DATE,
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    TMSTAMP            TIMESTAMP(6),
    DELIVERED_FLG      CHAR(1),
    DR_CR_FLAG         CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_HCO_004
    on HCOMPOSITE_TRX (FK0JUSTIFICID_JUST, FK0TRANSACTION0ID, FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_HPRODUCTID_PROD,
                       FK_HPRODUCTVALIDIT, FK_JUSTIFICID_JUST, FK_TRANSACTION0ID, VALIDITY_DATE);

