create table HDEP_TRXJUST_TMP
(
    VALUE_DAYS         SMALLINT,
    AVAIL_DAYS         SMALLINT,
    MIN_AVAIL_DAYS     SMALLINT,
    MIN_VALUE_DAYS     SMALLINT,
    MAX_AVAIL_DAYS     SMALLINT,
    MAX_VALUE_DAYS     SMALLINT,
    FK_JUSTIFICID_JUST INTEGER,
    FK_TRANSACTION0ID  INTEGER,
    FK0HDEPOSITFK_HPRO INTEGER
);

