create table HDEP_PRICING
(
    FK_HDEP_TRXJUSTFK  INTEGER  not null,
    FK0HDEP_TRXJUSTFK  INTEGER  not null,
    FK_HDEP_TRXJUSTFK0 INTEGER  not null,
    FK1HDEP_TRXJUSTFK  DATE     not null,
    FK_HDEP_TRXJUSTVAL DATE     not null,
    VALIDITY_DATE      DATE     not null,
    SNUM               SMALLINT not null,
    FK0LNS_TAXID_TAX   INTEGER,
    FK_LNS_TAXID_TAX   INTEGER,
    FK_LNS_EXPENSEID_E INTEGER,
    FK_LNS_COMMISSIID  INTEGER,
    EXP_UP_LIMIT       DECIMAL(8, 4),
    COM_LOW_LIMIT      DECIMAL(8, 4),
    COM_UP_LIMIT       DECIMAL(8, 4),
    EXP_LOW_LIMIT      DECIMAL(8, 4),
    DELIVERED_FLG      CHAR(1),
    ENTRY_STATUS       CHAR(1),
    constraint IXU_PRD_001
        primary key (FK_HDEP_TRXJUSTFK, FK0HDEP_TRXJUSTFK, FK_HDEP_TRXJUSTFK0, FK1HDEP_TRXJUSTFK, FK_HDEP_TRXJUSTVAL,
                     VALIDITY_DATE, SNUM)
);

