create table HINT_SCALE
(
    LOW_LIMIT00        DECIMAL(8, 4),
    UP_LIMIT00         DECIMAL(8, 4),
    AMOUNT00           DECIMAL(15, 2),
    PERCENTAGE00       DECIMAL(8, 4),
    LOW_LIMIT01        DECIMAL(8, 4),
    UP_LIMIT01         DECIMAL(8, 4),
    AMOUNT01           DECIMAL(15, 2),
    PERCENTAGE01       DECIMAL(8, 4),
    LOW_LIMIT02        DECIMAL(8, 4),
    UP_LIMIT02         DECIMAL(8, 4),
    AMOUNT02           DECIMAL(15, 2),
    PERCENTAGE02       DECIMAL(8, 4),
    LOW_LIMIT03        DECIMAL(8, 4),
    UP_LIMIT03         DECIMAL(8, 4),
    AMOUNT03           DECIMAL(15, 2),
    PERCENTAGE03       DECIMAL(8, 4),
    LOW_LIMIT04        DECIMAL(8, 4),
    UP_LIMIT04         DECIMAL(8, 4),
    AMOUNT04           DECIMAL(15, 2),
    PERCENTAGE04       DECIMAL(8, 4),
    LOW_LIMIT05        DECIMAL(8, 4),
    UP_LIMIT05         DECIMAL(8, 4),
    AMOUNT05           DECIMAL(15, 2),
    PERCENTAGE05       DECIMAL(8, 4),
    LOW_LIMIT06        DECIMAL(8, 4),
    UP_LIMIT06         DECIMAL(8, 4),
    AMOUNT06           DECIMAL(15, 2),
    PERCENTAGE06       DECIMAL(8, 4),
    LOW_LIMIT07        DECIMAL(8, 4),
    UP_LIMIT07         DECIMAL(8, 4),
    AMOUNT07           DECIMAL(15, 2),
    PERCENTAGE07       DECIMAL(8, 4),
    LOW_LIMIT08        DECIMAL(8, 4),
    UP_LIMIT08         DECIMAL(8, 4),
    AMOUNT08           DECIMAL(15, 2),
    PERCENTAGE08       DECIMAL(8, 4),
    LOW_LIMIT09        DECIMAL(8, 4),
    UP_LIMIT09         DECIMAL(8, 4),
    AMOUNT09           DECIMAL(15, 2),
    PERCENTAGE09       DECIMAL(8, 4),
    LOW_LIMIT10        DECIMAL(8, 4),
    UP_LIMIT10         DECIMAL(8, 4),
    AMOUNT10           DECIMAL(15, 2),
    PERCENTAGE10       DECIMAL(8, 4),
    LOW_LIMIT11        DECIMAL(8, 4),
    UP_LIMIT11         DECIMAL(8, 4),
    AMOUNT11           DECIMAL(15, 2),
    PERCENTAGE11       DECIMAL(8, 4),
    LOW_LIMIT12        DECIMAL(8, 4),
    UP_LIMIT12         DECIMAL(8, 4),
    AMOUNT12           DECIMAL(15, 2),
    PERCENTAGE12       DECIMAL(8, 4),
    LOW_LIMIT13        DECIMAL(8, 4),
    UP_LIMIT13         DECIMAL(8, 4),
    AMOUNT13           DECIMAL(15, 2),
    PERCENTAGE13       DECIMAL(8, 4),
    LOW_LIMIT14        DECIMAL(8, 4),
    UP_LIMIT14         DECIMAL(8, 4),
    AMOUNT14           DECIMAL(15, 2),
    PERCENTAGE14       DECIMAL(8, 4),
    CONTINUATION       CHAR(1),
    UP_LIMIT           DECIMAL(8, 4),
    LOW_LIMIT          DECIMAL(8, 4),
    MAX_BALANCE        DECIMAL(15, 2),
    ID_INTEREST        INTEGER,
    TMSTAMP            TIMESTAMP(6),
    SNUM               SMALLINT not null,
    ABOVE_LIMIT_XX     CHAR(1)  not null,
    VALIDITY_DATE      DATE     not null,
    DEPOS_PAYOFF       CHAR(1)  not null,
    DEPOS_DURATION     SMALLINT not null,
    FK_INTERESTID_INTE INTEGER  not null,
    FK_CURRENCYID_CURR INTEGER  not null,
    ENTRY_STATUS       CHAR(1),
    constraint PHINTSCA
        primary key (FK_INTERESTID_INTE, FK_CURRENCYID_CURR, DEPOS_DURATION, DEPOS_PAYOFF, ABOVE_LIMIT_XX, SNUM,
                     VALIDITY_DATE)
);

create unique index I0000869
    on HINT_SCALE (FK_INTERESTID_INTE);

create unique index I0000871
    on HINT_SCALE (FK_CURRENCYID_CURR);

