create table HISSU_PROD_PERM_FREQ
(
    FREQUENCY_UNIT CHAR(1),
    FREQUENCY      SMALLINT,
    FK_PRODUCT     INTEGER,
    VALIDITY_DATE  DATE
);

create unique index HISPRODP
    on HISSU_PROD_PERM_FREQ (FK_PRODUCT, VALIDITY_DATE, FREQUENCY, FREQUENCY_UNIT);

