create table HISSU_PROD_PERM
(
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PERMISSIBLE_IND    CHAR(1)
);

create unique index IXU_HIS_022
    on HISSU_PROD_PERM (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT);

