create table HISSU_PROD_CUST
(
    PRODUCT         INTEGER,
    VALIDITY_DATE   DATE,
    CUSTOMER        INTEGER,
    DEFAULT_IND     SMALLINT,
    CR_DEP_ACCOUNT  DECIMAL(11) not null,
    BANK_ACCOUNT_NO CHAR(40)
);

create unique index IXU_HIS_020
    on HISSU_PROD_CUST (PRODUCT, VALIDITY_DATE, CUSTOMER, CR_DEP_ACCOUNT);

