create table HIST_SO_SWIFT_202
(
    ACTIVATION_DATE    DATE,
    TP_SO_IDENTIFIER   DECIMAL(10),
    FK_SWMSG_PRFTREFNO CHAR(16),
    OUTG_BENEF_ACCOUNT CHAR(35),
    SNDR_TO_RCVR_72    CHAR(215),
    ACC_WITH_INSTI_57A VARCHAR(183)
);

create unique index IXU_HIS_028
    on HIST_SO_SWIFT_202 (ACTIVATION_DATE, TP_SO_IDENTIFIER);

