create table HIST_CHQ_BOOK_ITEM
(
    TUN_INTERNAL_SN    SMALLINT,
    TRX_UNIT           INTEGER,
    TRX_USR_SN         INTEGER,
    ITEM_SERIAL_NUMBER DECIMAL(10),
    ACCOUNT_NUMBER     DECIMAL(11),
    CHEQUE_AMOUNT      DECIMAL(15, 2),
    TRX_DATE           DATE,
    TMSTAMP            TIMESTAMP(6),
    CHEQUE_STATUS      CHAR(1),
    PROCESSED_FLG      CHAR(1),
    TRX_USR            CHAR(8),
    REJECTION_CODE     CHAR(2),
    TOT_COMM_AMOUNT    DECIMAL(15, 2)
);

create unique index IXP_HIS_000
    on HIST_CHQ_BOOK_ITEM (ITEM_SERIAL_NUMBER, ACCOUNT_NUMBER, TMSTAMP);

