create table HISTORY_M_F_DISTRI
(
    TRANS_SER_NUM    INTEGER,
    TUN_INTERNAL_SN  SMALLINT,
    TRX_USR_SN       INTEGER,
    TRX_USR          CHAR(8),
    TRX_DATE         DATE,
    TRX_UNIT         INTEGER,
    MAX_LAST_DP_PER  DECIMAL(8, 4),
    MIN_LAST_M_F_PER DECIMAL(8, 4),
    TRX_CODE         DECIMAL(10),
    ACCOUNT_NUMBER   DECIMAL(11),
    TMSTAMP          DATE,
    ENTRY_STATUS     CHAR(1)
);

create unique index IXU_HIS_030
    on HISTORY_M_F_DISTRI (TRANS_SER_NUM, TUN_INTERNAL_SN, TRX_USR_SN, TRX_USR, TRX_DATE, TRX_UNIT);

