create table HIST_DEP_ACC_INFO
(
    FK1DEPOSIT_ACCOACC DECIMAL(11) not null,
    TRX_DATE           DATE        not null,
    TMSTAMP            DATE        not null,
    LNS_ACC_TYPE       SMALLINT,
    LNS_UNITCODE       INTEGER,
    LNS_ACC_SN         INTEGER,
    LST_PRCSD_EXTRT_SN INTEGER,
    TOT_SPRD_INTEREST  DECIMAL(15, 2),
    TOT_PRODUCT_AMN    DECIMAL(15, 2),
    OVERDU_DB_ACCRUALS DECIMAL(15, 2),
    TOT_DB_INTEREST_AM DECIMAL(15, 2),
    TOT_SUBS_INTEREST  DECIMAL(15, 2),
    TOT_N128_INTEREST  DECIMAL(15, 2),
    TOT_PEN_INTEREST_A DECIMAL(15, 2),
    NORMAL_DB_ACCRUALS DECIMAL(15, 2),
    constraint PK_HDEP_ACC_INFO
        primary key (FK1DEPOSIT_ACCOACC, TRX_DATE, TMSTAMP)
);

create unique index HDEPACCINFO
    on HIST_DEP_ACC_INFO (LNS_UNITCODE, LNS_ACC_TYPE, LNS_ACC_SN);

