create table HKEEP_HEADER
(
    IDN             INTEGER,
    SRC_TABLE       VARCHAR(50),
    HST_TABLE       VARCHAR(50),
    ENABLED         CHAR(1),
    CLASSIFICATION  VARCHAR(100),
    WHERE_CLAUSE    VARCHAR(2000),
    COMMIT_INTERVAL DECIMAL(10),
    DESCRIPTION     VARCHAR(2000),
    LAST_VALUE_1    VARCHAR(100),
    LAST_VALUE_2    VARCHAR(100),
    LAST_VALUE_3    VARCHAR(100),
    DELTA_VALUE_1   VARCHAR(100),
    DELTA_VALUE_2   VARCHAR(100),
    DELTA_VALUE_3   VARCHAR(100)
);

create unique index IXH_HDR_001
    on HKEEP_HEADER (IDN);

