create table HLG
(
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    REVIEW_FRQ         SMALLINT,
    COM_CHARGE_FRQ     SMALLINT,
    FKGD_CBANK_RISK    INTEGER,
    FKGD_ACCOUNT_TYPE  INTEGER,
    FKGD_CREDIT_LINE   INTEGER,
    FKGD_BANK_RISK     INTEGER,
    MIN_AMN_TOLERANCE  DECIMAL(8, 4),
    MAX_AMN_TOLERANCE  DECIMAL(8, 4),
    RISK_FACTOR        DECIMAL(8, 4),
    PRINT_STATEMENT_DT DATE,
    NXT_PRINT_TRANS_DT DATE,
    LST_PRINT_TRANS_DT DATE,
    TMSTAMP            TIMESTAMP(6),
    COM_CHARGE_FRQ_TYP CHAR(1),
    ENTRY_STATUS       CHAR(1),
    WITHIN_LIMIT_FLG   CHAR(1),
    GL_NETWORK_LVL     CHAR(1),
    DR_GL_ACCOUNT_LVL  CHAR(1),
    CR_GL_ACCOUNT_LVL  CHAR(1),
    LG_TYPE            CHAR(1),
    FKGH_CREDIT_LINE   CHAR(5),
    FKGH_CBANK_RISK    CHAR(5),
    FKGH_ACCOUNT_TYPE  CHAR(5),
    FKGH_BANK_RISK     CHAR(5),
    GENERAL_FLAGS      CHAR(10),
    DR_GL_ACCOUNT      CHAR(21),
    CR_GL_ACCOUNT      CHAR(21),
    GL_NETWORK_ACC     CHAR(21)
);

create unique index IXU_HLG_003
    on HLG (FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT);

