create table HLG_TRXJUST
(
    VALIDITY_DATE      DATE,
    FK_JUSTIFICID_JUST INTEGER,
    FK_PRFT_TRANSACID  INTEGER,
    FK_HLGFK_HPRODUCTI INTEGER,
    FK_HLGFK_HPRODUCTV DATE,
    FK_DOCUMENT_TEMPRF SMALLINT,
    MIN_AVAIL_DAYS     SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    VALUE_DAYS         SMALLINT,
    AVAIL_DAYS         SMALLINT,
    MIN_VALUE_DAYS     SMALLINT,
    MAX_VALUE_DAYS     SMALLINT,
    MAX_AVAIL_DAYS     SMALLINT,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_CURRENCYID_CURR INTEGER,
    FK_PARAMETRIC_RID  INTEGER,
    FK_ACCOUNTING_RID  INTEGER,
    FKGD_HAS_LANGUAGE  INTEGER,
    FK_DOCUMENT_TEMCOD INTEGER,
    EXP_UP_LIMIT       DECIMAL(8, 4),
    COM_LOW_LIMIT      DECIMAL(8, 4),
    COM_UP_LIMIT       DECIMAL(8, 4),
    EXP_LOW_LIMIT      DECIMAL(8, 4),
    MAX_TRN_AMOUNT     DECIMAL(15, 2),
    MIN_TRN_AMOUNT     DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    CURRENCY_TYPE      CHAR(1),
    DEFAULT_INDICATOR  CHAR(1),
    HOME_BRANCH        CHAR(1),
    RECYCLED_LIMIT     CHAR(1),
    DELIVERED_FLG      CHAR(1),
    ENTRY_STATUS       CHAR(1),
    FKGH_HAS_LANGUAGE  CHAR(5)
);

create unique index IXU_HLG_002
    on HLG_TRXJUST (VALIDITY_DATE, FK_JUSTIFICID_JUST, FK_PRFT_TRANSACID, FK_HLGFK_HPRODUCTI, FK_HLGFK_HPRODUCTV);

