create table HPENALTY
(
    SNUM               SMALLINT not null,
    ENTRY_STATUS       CHAR(1),
    MIN_PENALTY0       DECIMAL(15, 2),
    MAX_PENALTY0       DECIMAL(15, 2),
    ALLOWED0           SMALLINT,
    PENALTY0           DECIMAL(15, 2),
    BALANCE0           DECIMAL(15, 2),
    CONTINUATION       CHAR(1),
    MIN_PENALTY8       DECIMAL(15, 2),
    MAX_PENALTY8       DECIMAL(15, 2),
    ALLOWED8           SMALLINT,
    PENALTY8           DECIMAL(15, 2),
    BALANCE8           DECIMAL(15, 2),
    MIN_PENALTY7       DECIMAL(15, 2),
    MAX_PENALTY7       DECIMAL(15, 2),
    ALLOWED7           SMALLINT,
    PENALTY7           DECIMAL(15, 2),
    BALANCE7           DECIMAL(15, 2),
    MIN_PENALTY6       DECIMAL(15, 2),
    MAX_PENALTY6       DECIMAL(15, 2),
    ALLOWED6           SMALLINT,
    PENALTY6           DECIMAL(15, 2),
    BALANCE6           DECIMAL(15, 2),
    MIN_PENALTY5       DECIMAL(15, 2),
    MAX_PENALTY5       DECIMAL(15, 2),
    ALLOWED5           SMALLINT,
    PENALTY5           DECIMAL(15, 2),
    BALANCE5           DECIMAL(15, 2),
    MIN_PENALTY4       DECIMAL(15, 2),
    MAX_PENALTY4       DECIMAL(15, 2),
    ALLOWED4           SMALLINT,
    PENALTY4           DECIMAL(15, 2),
    BALANCE4           DECIMAL(15, 2),
    MIN_PENALTY3       DECIMAL(15, 2),
    MAX_PENALTY3       DECIMAL(15, 2),
    ALLOWED3           SMALLINT,
    PENALTY3           DECIMAL(15, 2),
    BALANCE3           DECIMAL(15, 2),
    MIN_PENALTY2       DECIMAL(15, 2),
    MAX_PENALTY2       DECIMAL(15, 2),
    ALLOWED2           SMALLINT,
    PENALTY2           DECIMAL(15, 2),
    BALANCE2           DECIMAL(15, 2),
    MIN_PENALTY1       DECIMAL(15, 2),
    MAX_PENALTY1       DECIMAL(15, 2),
    ALLOWED1           SMALLINT,
    PENALTY1           DECIMAL(15, 2),
    BALANCE1           DECIMAL(15, 2),
    MIN_PENALTY9       DECIMAL(15, 2),
    MAX_PENALTY9       DECIMAL(15, 2),
    ALLOWED9           SMALLINT,
    PENALTY9           DECIMAL(15, 2),
    BALANCE9           DECIMAL(15, 2),
    ID_PRODUCT         INTEGER,
    VALIDITY_DATE      DATE     not null,
    DELIVERED_FLG      CHAR(1),
    TMSTAMP            TIMESTAMP(6),
    FK_HPRODUCTVALIDIT DATE     not null,
    FK_HPRODUCTID_PROD INTEGER  not null,
    FK_CHANNELID_CHANN INTEGER  not null,
    constraint PKEY0006
        primary key (FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT, FK_CHANNELID_CHANN, VALIDITY_DATE, SNUM)
);

