create table HPROD_SUBSIDY
(
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    FK_SUBSIDY_ORDEID  INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERM_RESTR_IND     CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_HPR_005
    on HPROD_SUBSIDY (FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT, FK_SUBSIDY_ORDEID);

