create table HPROD_CURRENCY
(
    FK_CURRENCYID_CURR INTEGER,
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PERM_RESTR_IND     CHAR(1),
    MIN_OPENING_AMOUNT DECIMAL(15, 2),
    MIN_TRX_AMOUNT     DECIMAL(15, 2),
    MAX_BOOK_BALANCE   DECIMAL(15, 2)
);

create unique index IXU_HPR_009
    on HPROD_CURRENCY (FK_CURRENCYID_CURR, FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT);

