create table HPROD_FORMULA_DT
(
    FORML_SERIAL_NUM   DECIMAL(10)  not null,
    FORML_FIELD1       CHAR(40),
    NUM_FIELD1         DECIMAL(18, 6),
    FLDVALUES1_CD      DECIMAL(10),
    MULTI_FLDVAL1_CD   DECIMAL(10),
    FORML_OPERATOR     CHAR(5),
    FORML_FIELD2       CHAR(40),
    NUM_FIELD2         DECIMAL(18, 6),
    FLDVALUES2_CD      DECIMAL(10),
    MULTI_FLDVAL2_CD   DECIMAL(10),
    TMP_RESULT_FIELD   CHAR(40),
    FK_HPRODUCTID      INTEGER      not null,
    FK_HPRDVALIDITY_DT DATE         not null,
    TMSTAMP            TIMESTAMP(6) not null,
    FK_HPRFORMULA_RF   CHAR(40)     not null,
    FK_HPRD_FORMULA_SN DECIMAL(10)  not null,
    constraint PK_HPRD_FORMULA_DT
        primary key (FK_HPRODUCTID, FK_HPRDVALIDITY_DT, TMSTAMP, FK_HPRFORMULA_RF, FK_HPRD_FORMULA_SN, FORML_SERIAL_NUM)
);

