create table HPROD_INTEREST
(
    FK_HPRODUCTVALIDIT DATE,
    FK_HPRODUCTID_PROD INTEGER,
    FK_INTERESTID_INTE INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERM_RESTR_IND     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    DELIVERED_FLG      CHAR(1),
    INTEREST_CASE      CHAR(1)
);

create unique index IXU_HPR_008
    on HPROD_INTEREST (FK_HPRODUCTVALIDIT, FK_HPRODUCTID_PROD, FK_INTERESTID_INTE);

