create table HPROD_TRXCHAN
(
    FK_CHANNELID_CHANN INTEGER,
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    FK_TRANSACTION0ID  INTEGER,
    TMSTAMP            TIMESTAMP(6),
    DELIVERED_FLG      CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_HPR_004
    on HPROD_TRXCHAN (FK_CHANNELID_CHANN, FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT, FK_TRANSACTION0ID);

