create table HPRODUCT
(
    ID_PRODUCT       INTEGER,
    VALIDITY_DATE    DATE,
    BLOCKED_PERCENT  DECIMAL(8, 4),
    TMSTAMP          TIMESTAMP(6),
    LAST_MODIFIED    DATE,
    PRD_EXP_DT       DATE,
    ENTRY_STATUS     CHAR(1),
    CONFIRM_IND      CHAR(1),
    DELIVERED_FLG    CHAR(1),
    PRODUCT_TYPE     CHAR(1),
    INTER_BEARING    CHAR(1),
    INVEST_FLAG      CHAR(1),
    ENTERPRISE       CHAR(1),
    DESCRIPTION      VARCHAR(40),
    COMMENT1         VARCHAR(75),
    LAST_UPD_USER    CHAR(8),
    LAST_UPD_UNIT    DECIMAL(5),
    LAST_UPD_DATE    DATE,
    LAST_UPD_TMSTAMP TIMESTAMP(6)
);

create unique index IXU_HPR_002
    on HPRODUCT (ID_PRODUCT, VALIDITY_DATE);

