create table HPROD_UNIT
(
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    OPERATION_STATUS_F CHAR(1),
    PERM_RESTR_IND     CHAR(1)
);

create unique index IXU_HPR_003
    on HPROD_UNIT (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT);

