create table HREP_74220A
(
    PRFT_SYSTEM   SMALLINT,
    ACC_UNIT      INTEGER,
    ACC_MOVE_CURR INTEGER,
    GL_BALANCE    DECIMAL(15, 2),
    LEGER_BALANCE DECIMAL(15, 2),
    GL_TRN_DATE   DATE,
    GL_ACCOUNT    CHAR(21)
);

