create table HRESTR_VALUE
(
    DELIVERED_FLG     CHAR(1),
    DESCRIPTION       VARCHAR(40),
    RESTR_VALUE_TYPE  INTEGER not null,
    ENTRY_STATUS      CHAR(1),
    TMSTAMP           TIMESTAMP(6),
    FK0HPROD_RESTRIFK INTEGER not null,
    FK_HPROD_RESTRIFK DATE    not null,
    FK1HPROD_RESTRIFK INTEGER not null,
    constraint PKEY0011
        primary key (FK1HPROD_RESTRIFK, FK_HPROD_RESTRIFK, FK0HPROD_RESTRIFK, RESTR_VALUE_TYPE)
);

