create table HSDB_TRXJUST
(
    FK_PRFT_TRANSACID  INTEGER not null,
    FKHPR_PRODUCT_ID   INTEGER not null,
    FKHPR_VALIDITYDATE DATE    not null,
    FK_JUSTIFICID_JUST INTEGER not null,
    VALIDITY_DATE      DATE    not null,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_PARAMETRIC_RID  INTEGER,
    FK_ACCOUNTING_RID  INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    MAX_TRN_AMOUNT     DECIMAL(15, 2),
    MIN_TRN_AMOUNT     DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    DELIVERED_FLG      CHAR(1),
    HOME_BRANCH        CHAR(1),
    FK_LNS_COMMISSION  INTEGER default 0,
    FK_LNS_TAX         INTEGER default 0,
    FK_LNS_EXPENSE     INTEGER default 0,
    constraint IXU_HSD_001
        primary key (FK_PRFT_TRANSACID, FKHPR_PRODUCT_ID, FKHPR_VALIDITYDATE, FK_JUSTIFICID_JUST, VALIDITY_DATE)
);

