create table HSECURITIES_GL
(
    FK_CLEARING_SYSCOD CHAR(10),
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALIDIT DATE,
    FKGH_GROUP_MEMBER  CHAR(5),
    FKGD_GROUP_MEMBER  INTEGER,
    FKGH_CUST_CATEGORY CHAR(5),
    FKGD_CUST_CATEGORY INTEGER,
    TMSTAMP            DATE,
    DR_CNTR_GL_ACC_LVL CHAR(1),
    ENTRY_STATUS       CHAR(1),
    CR_CNTR_GL_ACC_LVL CHAR(1),
    DR_CNTR_GL_ACC     CHAR(21),
    CR_CNTR_GL_ACC     CHAR(21),
    BANK_SECUR_ACC     CHAR(21)
);

create unique index IXU_HSE_001
    on HSECURITIES_GL (FK_CLEARING_SYSCOD, FK_HPRODUCTID_PROD, FK_HPRODUCTVALIDIT, FKGH_GROUP_MEMBER, FKGD_GROUP_MEMBER,
                       FKGH_CUST_CATEGORY, FKGD_CUST_CATEGORY);

