create table HSECURITIES
(
    FK_HPRODUCTID_PROD INTEGER,
    FK_HPRODUCTVALDATE DATE,
    FK_SECURITIES_TYPE SMALLINT,
    FK_REPO_TAX        INTEGER,
    DELIVERED_FLG      CHAR(1),
    ENTRY_STATUS       CHAR(1),
    RESIDENT_IND       CHAR(1)
);

create unique index IXU_HSE_002
    on HSECURITIES (FK_HPRODUCTID_PROD, FK_HPRODUCTVALDATE);

