create table HSECUR_TRXJUST
(
    FK_HSECUR_PROD_ID   INTEGER,
    FK_HSECUR_VAL_DATE  DATE,
    FK_JUSTIFICID_JUST  INTEGER,
    FK_PRFT_TRANSACID   INTEGER,
    VALIDITY_DATE       DATE,
    MAX_VALUE_DAYS      SMALLINT,
    MIN_VALUE_DAYS      SMALLINT,
    FK_PARAMETRIC_RSNU2 SMALLINT,
    VALUE_DAYS          SMALLINT,
    FK_ACCOUNTING_RSNU  SMALLINT,
    FK_PARAMETRIC_RSNU  SMALLINT,
    FK_PARAMETRIC_RID   INTEGER,
    FK_CURRENCYID_CURR  INTEGER,
    FK_ACCOUNTING_RID   INTEGER,
    FK_PARAMETRIC_RID2  INTEGER,
    COM_UP_LIMIT        DECIMAL(8, 4),
    EXP_LOW_LIMIT       DECIMAL(8, 4),
    EXP_UP_LIMIT        DECIMAL(8, 4),
    COM_LOW_LIMIT       DECIMAL(8, 4),
    MAX_TRN_AMOUNT      DECIMAL(15, 2),
    MIN_TRN_AMOUNT      DECIMAL(15, 2),
    DELIVERED_FLG       CHAR(1),
    ENTRY_STATUS        CHAR(1),
    HOME_BRANCH         CHAR(1)
);

create unique index IXU_HSE_005
    on HSECUR_TRXJUST (FK_HSECUR_PROD_ID, FK_HSECUR_VAL_DATE, FK_JUSTIFICID_JUST, FK_PRFT_TRANSACID, VALIDITY_DATE);

