create table HSERVICE_PRICING
(
    FK1HSERVICE_TRXFK  INTEGER,
    FK0HSERVICE_TRXFK  INTEGER,
    FK_HSERVICE_TRXFK0 INTEGER,
    FK_HSERVICE_TRXFK  DATE,
    FK_HSERVICE_TRXVAL DATE,
    SNUM               SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_PARAMETRIC_RID  INTEGER,
    FK_LNS_COMMISSIID  INTEGER,
    FK1LNS_TAXID_TAX   INTEGER,
    FK_CHEQ_ITEM_CHID  INTEGER,
    FK0LNS_TAXID_TAX   INTEGER,
    FK_LNS_EXPENSEID_E INTEGER,
    FK_LNS_TAXID_TAX   INTEGER,
    CPI_UP_LIMIT       DECIMAL(8, 4),
    CPI_LOW_LIMIT      DECIMAL(8, 4),
    COM_UP_LIMIT       DECIMAL(8, 4),
    EXP_LOW_LIMIT      DECIMAL(8, 4),
    EXP_UP_LIMIT       DECIMAL(8, 4),
    COM_LOW_LIMIT      DECIMAL(8, 4),
    TMSTAMP            DATE,
    ENTRY_STATUS       CHAR(1),
    DELIVERED_FLG      CHAR(1)
);

create unique index IXU_HSE_000
    on HSERVICE_PRICING (FK1HSERVICE_TRXFK, FK0HSERVICE_TRXFK, FK_HSERVICE_TRXFK0, FK_HSERVICE_TRXFK,
                         FK_HSERVICE_TRXVAL, SNUM);

