create table HTD_DURATION_GL
(
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_HDEPOSITFK_HPRO INTEGER,
    FK0HDEPOSITFK_HPRO DATE,
    DURATION_DAYS_TO   SMALLINT,
    TMSTAMP            TIMESTAMP(6),
    GL_ACCOUNT_LEVEL   CHAR(1),
    CR_INT_GL_LVL      CHAR(1),
    GL_ACCRUAL_LVL     CHAR(1),
    CR_INT_NOTAX_GL_LV CHAR(1),
    CR_INT_NOTAX_GLLVL CHAR(1),
    CR_INT_ACCR_GL_LVL CHAR(1),
    GL_ACCRUAL_ACC     CHAR(21),
    CR_INT_ACCR_GL_ACC CHAR(21),
    CR_INT_GL_ACC      CHAR(21),
    GL_ACCOUNT         CHAR(21),
    CR_INT_NOTAX_GLACC CHAR(21),
    CR_INT_NOTAX_GL_AC CHAR(21)
);

create unique index IXU_HTD_000
    on HTD_DURATION_GL (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_HDEPOSITFK_HPRO, FK0HDEPOSITFK_HPRO, DURATION_DAYS_TO);

