create table IBANK_DENOMINATION
(
    FK_INTERBANK_REREM INTEGER,
    SERIAL_NUM         INTEGER,
    QUANTITY           INTEGER,
    DENOMINATION       DECIMAL(15, 2),
    ENTRY_COMMENTS     VARCHAR(40),
    STRAPS_ROLLS       DECIMAL(10),
    NOTES_COINS_TYPE   CHAR(1)
);

create unique index IXU_IBA_000
    on IBANK_DENOMINATION (FK_INTERBANK_REREM, SERIAL_NUM);

