create table IBRANCH_DENOMINATI
(
    FK_INTERBRANCH_REM INTEGER,
    SERIAL_NUM         SMALLINT,
    QUANTITY           INTEGER,
    DENOMINATION       DECIMAL(15, 2),
    ENTRY_COMMENTS     VARCHAR(160),
    NOTES_COINS_TYPE   CHAR(1),
    STRAPS_ROLLS       DECIMAL(10)
);

create unique index IXU_IBR_000
    on IBRANCH_DENOMINATI (FK_INTERBRANCH_REM, SERIAL_NUM);

