create table INCOM_DRAFT_TO_ISS
(
    SEQ_NO             DECIMAL(10),
    FK_TRX_JUST        INTEGER,
    COLLABORATION_BANK INTEGER,
    FK_IS_DEP_ACC_JUST INTEGER,
    FK_TRX_PRODUCT     INTEGER,
    FK_DRAWN_UNIT      INTEGER,
    FK_REFER_CURRENCY  INTEGER,
    FK_ISSUER_CUSTOMER INTEGER,
    FK_ISSUER_DEP_ACC  DECIMAL(11),
    DRAFT_AMOUNT       DECIMAL(15, 2),
    VALUE_DATE         DATE,
    TMSTAMP            TIMESTAMP(6),
    PAYMENT_DATE       DATE,
    DRAFT_ORIGIN       CHAR(1),
    DRAFT_TYPE         CHAR(1),
    STATUS             CHAR(1),
    BENEF_ZIP_CODE     CHAR(7),
    ISSUER_ZIP_CODE    CHAR(7),
    BANK_DRAFT_NO      CHAR(10),
    ISSUER_CITY        CHAR(15),
    BENEF_CITY         CHAR(15),
    BENEF_PHONE        CHAR(20),
    ISSUER_PHONE       CHAR(20),
    BENEF_ADDRESS1     CHAR(40),
    BENEF_ADDRESS2     CHAR(40),
    BENEF_NAME         CHAR(40),
    ISSUER_ADDRESS1    CHAR(40),
    ISSUER_COUNTRY     CHAR(40),
    BENEF_COUNTRY      CHAR(40),
    ISSUER_NAME        CHAR(40),
    ISSUER_ADDRESS2    CHAR(40),
    COMMENTS           CHAR(40),
    BP_COMMENTS        VARCHAR(40)
);

create unique index IXU_INC_002
    on INCOM_DRAFT_TO_ISS (SEQ_NO);

