create table INP_BGM_SCHEDULE
(
    EXT_SYSTEM_ID          INTEGER     not null,
    EXT_APPLICATION_GRP_ID VARCHAR(40) not null,
    EXT_APPLICATION_ID     VARCHAR(40) not null,
    BGM_APPLICATION_ID     CHAR(15)    not null,
    BGM_CUSTOMER           VARCHAR(20) not null,
    BGM_PROGRAM            VARCHAR(20) not null,
    BGM_TYPE               INTEGER     not null,
    BGM_PROGRAM_STEP       INTEGER     not null,
    BGM_PROGRAM_STEP_SN    INTEGER     not null,
    BGM_OFFICER            CHAR(8),
    BGM_TRX_DATE           DATE,
    BGM_PROGRAM_STEP_REF   INTEGER,
    DATE_01                DATE,
    DATE_02                DATE,
    DATE_03                DATE,
    DATE_04                DATE,
    DATE_05                DATE,
    DATE_06                DATE,
    DATE_07                DATE,
    DATE_08                DATE,
    DATE_09                DATE,
    DATE_10                DATE,
    NUMBER_01              DECIMAL(10),
    NUMBER_02              DECIMAL(10),
    NUMBER_03              DECIMAL(10),
    NUMBER_04              DECIMAL(10),
    NUMBER_05              DECIMAL(10),
    NUMBER_06              DECIMAL(10),
    NUMBER_07              DECIMAL(10),
    NUMBER_08              DECIMAL(10),
    NUMBER_09              DECIMAL(10),
    NUMBER_10              DECIMAL(10),
    NUMBER_11              DECIMAL(10),
    NUMBER_12              DECIMAL(10),
    NUMBER_13              DECIMAL(10),
    NUMBER_14              DECIMAL(10),
    NUMBER_15              DECIMAL(10),
    NUMBER_16              DECIMAL(10),
    NUMBER_17              DECIMAL(10),
    NUMBER_18              DECIMAL(10),
    NUMBER_19              DECIMAL(10),
    NUMBER_20              DECIMAL(10),
    AMOUNT_01              DECIMAL(15, 2),
    AMOUNT_02              DECIMAL(15, 2),
    AMOUNT_03              DECIMAL(15, 2),
    AMOUNT_04              DECIMAL(15, 2),
    AMOUNT_05              DECIMAL(15, 2),
    AMOUNT_06              DECIMAL(15, 2),
    AMOUNT_07              DECIMAL(15, 2),
    AMOUNT_08              DECIMAL(15, 2),
    AMOUNT_09              DECIMAL(15, 2),
    AMOUNT_10              DECIMAL(15, 2),
    FLAG_01                CHAR(1),
    FLAG_02                CHAR(1),
    FLAG_03                CHAR(1),
    FLAG_04                CHAR(1),
    FLAG_05                CHAR(1),
    FLAG_06                CHAR(1),
    FLAG_07                CHAR(1),
    FLAG_08                CHAR(1),
    FLAG_09                CHAR(1),
    FLAG_10                CHAR(1),
    CHAR_01                VARCHAR(100),
    CHAR_02                VARCHAR(100),
    CHAR_03                VARCHAR(100),
    CHAR_04                VARCHAR(100),
    CHAR_05                VARCHAR(100),
    CHAR_06                VARCHAR(100),
    CHAR_07                VARCHAR(100),
    CHAR_08                VARCHAR(100),
    CHAR_09                VARCHAR(100),
    CHAR_10                VARCHAR(100),
    RATE_01                DECIMAL(8, 4),
    RATE_02                DECIMAL(8, 4),
    RATE_03                DECIMAL(8, 4),
    RATE_04                DECIMAL(8, 4),
    RATE_05                DECIMAL(8, 4),
    RATE_06                DECIMAL(8, 4),
    RATE_07                DECIMAL(8, 4),
    RATE_08                DECIMAL(8, 4),
    RATE_09                DECIMAL(8, 4),
    RATE_10                DECIMAL(8, 4),
    INSERT_TMSTAMP         TIMESTAMP(6),
    ENTRY_STATUS           CHAR(1),
    PROCESS_TMPSTAMP       TIMESTAMP(6),
    PROCESS_STATUS         CHAR(1),
    SENT_STATUS            CHAR(1),
    BATCH_ERROR            VARCHAR(100),
    constraint PK_INP_BGM_SCHEDULE
        primary key (EXT_SYSTEM_ID, EXT_APPLICATION_GRP_ID, EXT_APPLICATION_ID, BGM_APPLICATION_ID, BGM_CUSTOMER,
                     BGM_PROGRAM, BGM_TYPE, BGM_PROGRAM_STEP, BGM_PROGRAM_STEP_SN)
);

