create table INT_SCALE
(
    DEPOS_DURATION     SMALLINT,
    DEPOS_PAYOFF       CHAR(1),
    DEP_DUR_UNIT       CHAR(1),
    FK_CURRENCYID_CURR INTEGER,
    FK_INTERESTID_INTE INTEGER,
    SCALE_ID           SMALLINT,
    TMSTAMP            TIMESTAMP(6),
    VALIDITY_DATE      DATE,
    FK_BASE_RATEDURATI SMALLINT,
    FK_BASE_RATEFK_CUR INTEGER,
    FK_BASE_RATEFK_GD  INTEGER,
    INT_RATE_TAB_NO    INTEGER,
    INT_RATE_BNK_GR_NO INTEGER,
    IC_LOW_LIMIT       DECIMAL(8, 4),
    UP_LIMIT           DECIMAL(8, 4),
    LOW_LIMIT          DECIMAL(8, 4),
    IC_UP_LIMIT        DECIMAL(8, 4),
    PERCENTAGE         DECIMAL(9, 6),
    BONUS_SPRD_RATE    DECIMAL(9, 6),
    BANK_SPREAD        DECIMAL(12, 6),
    MAX_BALANCE        DECIMAL(15, 2),
    RESULT_AMOUNT      DECIMAL(15, 2),
    FROM_AMOUNT        DECIMAL(15, 2),
    NON_INTER_BEAR_LIM DECIMAL(15, 2),
    TO_AMOUNT          DECIMAL(15, 2),
    FK_BASE_RATEVALIDI DATE,
    FK_BASE_RATETMSTAM DATE,
    SUBS_PERCENT_IND   CHAR(1),
    BONUS_SPRD_IND     CHAR(1),
    FK_BASE_RATEDUR_UN CHAR(1),
    FK_BASE_RATEFK_GH  CHAR(5),
    MIN_MAX_IND        CHAR(1),
    MAX_PERCENTAGE     DECIMAL(9, 6),
    MIN_PERCENTAGE     DECIMAL(9, 6),
    CONFIRM_TMSTAMP    TIMESTAMP(6)
);

create unique index IXU_INT_005
    on INT_SCALE (DEPOS_DURATION, DEPOS_PAYOFF, DEP_DUR_UNIT, FK_CURRENCYID_CURR, FK_INTERESTID_INTE, SCALE_ID, TMSTAMP,
                  VALIDITY_DATE);

create unique index IX_INT_RATE
    on INT_SCALE (FK_CURRENCYID_CURR asc, FK_INTERESTID_INTE asc, VALIDITY_DATE desc);

