create table INTEREST_CALC_RULE
(
    PRODUCT_ID      INTEGER,
    EFFECTIVE_DATE  DATE,
    MAX_BALANCE     DECIMAL(15, 2),
    DURATION_VALUE  SMALLINT,
    TRANSACTION_CNT INTEGER,
    INTER_RATE_SPRD DECIMAL(8, 4)
);

create unique index PKINTCALCRULE
    on INTEREST_CALC_RULE (PRODUCT_ID, EFFECTIVE_DATE, MAX_BALANCE);

