create table INTERBRANCH_REMITT
(
    REMITTANCE_NUMBER  INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    FK_UNITCODE        INTEGER,
    FK0UNITCODE        INTEGER,
    RATE_TO_DC         DECIMAL(12, 6),
    RATE               DECIMAL(12, 6),
    AMOUNT_IN_DC       DECIMAL(15, 2),
    AMOUNT             DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    DATE_ISSUED        DATE,
    DATE_RECEIVED      DATE,
    ENTRY_STATUS       CHAR(1),
    ENTRY_COMMENTS     VARCHAR(40)
);

create unique index IXU_INT_007
    on INTERBRANCH_REMITT (REMITTANCE_NUMBER);

