create table INTEREST_NOT_TAXED
(
    TRX_DATE          DATE,
    ACCOUNT_NUMBER    DECIMAL(11),
    JUSTIFICATION     INTEGER,
    ACCOUNT_CHECK_DIG SMALLINT,
    PENDING_TAX_AMNT  DECIMAL(15, 2),
    GROSS_INTER_AMNT  DECIMAL(15, 2)
);

create unique index IXU_INT_009
    on INTEREST_NOT_TAXED (TRX_DATE, ACCOUNT_NUMBER, JUSTIFICATION);

