create table INTERBANK_REMITTAN
(
    REMITTANCE_NUMBER  INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    FK0CURRENCYID_CURR INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK0UNITCODE        INTEGER,
    FK_UNITCODE        INTEGER,
    FK_COLLABORATIOBAN INTEGER,
    RATE               DECIMAL(12, 6),
    RATE_TO_DC         DECIMAL(12, 6),
    AMOUNT             DECIMAL(15, 2),
    AMOUNT_IN_DC       DECIMAL(15, 2),
    TMSTAMP            DATE,
    DATE_ISSUED        DATE,
    DATE_RECEIVED      DATE,
    ENTRY_STATUS       CHAR(1),
    IN_OUT_INDICATOR   CHAR(1),
    ENTRY_COMMENTS     VARCHAR(40)
);

create unique index IXU_INT_006
    on INTERBANK_REMITTAN (REMITTANCE_NUMBER);

