create table IPS_ORGANIZATION_STAGE
(
    FILENAME               CHAR(20),
    PRODUCT_CODE           CHAR(8) not null,
    ORGANIZATION_CODE      INTEGER not null,
    START_DATE             DATE    not null,
    RECORD_TYPE            CHAR(1),
    BIC_ADDRESS            CHAR(11),
    IBAN_CODE              CHAR(34),
    ORGANIZATION_NAME      CHAR(70),
    REMITTANCE_CODE        CHAR(20),
    REMITTANCE_SN          INTEGER,
    EXPIRY_DATE            DATE,
    REMITTANCE_UNIQUE      CHAR(1),
    REMITTANCE_UNIQUE_DAYS SMALLINT,
    ADMIN_COST_TYPE        CHAR(1),
    ALLOWED_CUTOFF_TYPE    CHAR(1),
    RELATED_CUTOFF_TIME    CHAR(4),
    SETTLEMENT_FROM_OFFSET SMALLINT,
    SETTLEMENT_TO_OFFSET   SMALLINT,
    NATIONAL_CHAR_SET      CHAR(1),
    COLLECTION_CODE_1      SMALLINT,
    COLLECTION_CODE_2      SMALLINT,
    COLLECTION_CODE_3      SMALLINT,
    COLLECTION_CODE_4      SMALLINT,
    SYSTEM_CODE            CHAR(3),
    FILE_TIMESTAMP         CHAR(14),
    FILE_TYPE              CHAR(3),
    ACTIVATION_DATE        DATE,
    ACTIVE                 SMALLINT,
    CREDITOR_NAME_ENG      CHAR(32),
    TAX_ID                 CHAR(9),
    IRIS_ECOMMERCE         CHAR(1),
    NEXT_SAME_DAY          CHAR(1),
    FEE_COLLEC_METHOD      CHAR(1),
    FEE_BASE               CHAR(1),
    FEE_INTERNET           CHAR(1),
    INTERNET               DECIMAL(4, 2),
    FEE_INTERNAT_OL        CHAR(1),
    INTERNETOL             DECIMAL(4, 2),
    FEE_MOBILE             CHAR(1),
    MOBILE                 DECIMAL(4, 2),
    FEE_MOBILE_OL          CHAR(1),
    MOBILE_OL              DECIMAL(4, 2),
    FEE_BRANCHA            CHAR(1),
    BRANCHA                DECIMAL(4, 2),
    FEE_BRANCH_AOL         CHAR(1),
    BRANCH_AOL             DECIMAL(4, 2),
    FEE_BRANCHC            CHAR(1),
    BRANCHC                DECIMAL(4, 2),
    FEE_BRANCH_COL         CHAR(1),
    BRANCH_COL             DECIMAL(4, 2),
    FEE_PHONE              CHAR(1),
    PHONE                  DECIMAL(4, 2),
    FEE_PHONEOL            CHAR(1),
    PHONE_OL               DECIMAL(4, 2),
    FEE_ATM                CHAR(1),
    ATM                    DECIMAL(4, 2),
    FEE_ATMOL              CHAR(1),
    ATMOL                  DECIMAL(4, 2),
    FEE_APS                CHAR(1),
    APS                    DECIMAL(4, 2),
    FEE_APSOL              CHAR(1),
    APSOL                  DECIMAL(4, 2),
    FEE_IRIS_EBANKING      CHAR(1),
    IRIS_EBANKING          DECIMAL(4, 2),
    FEE_IRIS_MBANKING      CHAR(1),
    IRIS_MBANKING          DECIMAL(4, 2),
    FEE_AGENTS             CHAR(1),
    AGENTS                 DECIMAL(4, 2),
    FEE_AGENTS_OL          CHAR(1),
    AGENTS_OL              DECIMAL(4, 2),
    FEE_APIS               CHAR(1),
    APIS                   DECIMAL(4, 2),
    FEE_APIS_OL            CHAR(1),
    APIS_OL                DECIMAL(4, 2),
    FEE_FILE               CHAR(1),
    FILE0                  DECIMAL(4, 2),
    FEE_FILE_OL            CHAR(1),
    FILE_OL                DECIMAL(4, 2),
    TMSTAMP                TIMESTAMP(6),
    ROUTING_OPTION         CHAR(1),
    IBAN_USAGE             CHAR(1),
    ONLINE_MESSAGES        CHAR(1),
    constraint PK_IPS_ORG_STAGE
        primary key (START_DATE, ORGANIZATION_CODE, PRODUCT_CODE)
);

