create table IPS_MESSAGE_HEADER
(
    ORDER_CODE            VARCHAR(20)              not null
        constraint IXU_CP__61
            primary key,
    FK_ORDER_CODE         VARCHAR(20),
    ORDER_STATUS          CHAR(1),
    ORDER_AMOUNT          DECIMAL(15, 2)           not null,
    ORDER_TYPE            VARCHAR(3)               not null,
    ORDER_TIMESTAMP       TIMESTAMP(6),
    ISSUER_CUST_ID        INTEGER,
    BENEF_CUST_ID         INTEGER,
    SERVICE_PRODUCT       INTEGER                  not null,
    JUSTIFIC_ID           INTEGER                  not null,
    CREDIT_BIC_ADDRESS    VARCHAR(40),
    DEBIT_BIC_ADDRESS     VARCHAR(40),
    PRFT_ACCOUNT          VARCHAR(40),
    ISSUER_IBAN_ACC       VARCHAR(37),
    BENEF_IBAN_ACC        VARCHAR(37),
    GENERIC_ACCOUNT       VARCHAR(40),
    TRX_CODE              INTEGER                  not null,
    TRX_DATE              DATE,
    COMPLETE_MESSAGE      VARCHAR(2048),
    REJECTION_CODE        VARCHAR(40),
    EXTERNAL_ID_REF       VARCHAR(40),
    ORDER_FILENAME        VARCHAR(50),
    CHARGES_JUSTIFIC      INTEGER,
    ISSUER_FULLNAME       VARCHAR(100),
    BENEF_FULLNAME        VARCHAR(100),
    COMBO_JUSTIFIC        INTEGER,
    COMBO_TRANSACTION     INTEGER,
    CHARGES_ACCOUNT       VARCHAR(40),
    ORDER_CURRENCY        INTEGER,
    ISSUER_PROD_DATE      DATE,
    EXPENSE_JUSTIFIC      INTEGER,
    EXPENSE_PROD_DATE     DATE,
    ORDER_FILE_LINE       INTEGER,
    ISSUER_RESIDENT       VARCHAR(1),
    BENEF_RESIDENT        VARCHAR(1),
    COMMENTS              VARCHAR(250),
    EXECUTION_SN          SMALLINT,
    TRX_UNIT              INTEGER,
    ORDER_EXPENSE         DECIMAL(15, 2) default 0 not null,
    ORDER_COMMISSION      DECIMAL(15, 2) default 0 not null,
    COLLECTED_AMOUNT      DECIMAL(15, 2) default 0 not null,
    SETTLEMENT_AMNT       DECIMAL(15, 2) default 0 not null,
    PROCESS_RESULTS       VARCHAR(255),
    FILE_BIC_ADDRESS      VARCHAR(12),
    PRFT_ACC_SYSTEM       SMALLINT,
    REMITTANCE_INFO       VARCHAR(140),
    CLEARING_SYSTEM       CHAR(35),
    CHARGE_BEARER         CHAR(4),
    PROCESS_TYPE          CHAR(10),
    ORDER_GROUP_1         CHAR(10),
    ORDER_GROUP_2         CHAR(10),
    INSTRUCTION_REF_ID    VARCHAR(40),
    CHARGES_ACC_SYSTEM    SMALLINT,
    CHARGES_DISCOUNT      DECIMAL(8, 4),
    COMMISSION_DISCOUNT   DECIMAL(8, 4),
    TRANSIT_CUSTOMER      CHAR(1),
    NEW_ORDER_CODE        CHAR(20),
    ACCEPTANCE_TIMESTAMP  TIMESTAMP(6),
    GROUP_MESSAGE_ID      VARCHAR(35),
    ORI_GROUP_MESSAGE_ID  VARCHAR(35),
    ORI_END_TO_END_ID     VARCHAR(35),
    END_TO_END_ID         VARCHAR(35),
    DEALER_USR            CHAR(8),
    DEALER_REF_NO         CHAR(20),
    RATE                  DECIMAL(12, 6),
    ORDER_CATEGORY        VARCHAR(20),
    LOADED_DATE           DATE,
    SORT_CREDIT_DEBIT     CHAR(10),
    SORT_BIC_ADDRESS      VARCHAR(12),
    UNCLEAR_CNT           DECIMAL(10),
    UNCLEAR_AVAIL_DATE    DATE,
    SETTLEMENT_FLAG       CHAR(1),
    ITEM_SERIAL_NUMBER    DECIMAL(10),
    APPROVAL_STATUS       CHAR(1),
    SESSION_NO            CHAR(1),
    APPROVED_USR          CHAR(8),
    APPROVED_DATE         DATE,
    APPROVAL_TIMESTAMP    TIMESTAMP(6),
    DATA_ROW_SN           DECIMAL(10),
    SETTL_PROCESSED       CHAR(1),
    HOSTED_BANK_BIC       VARCHAR(12),
    GROUP_ID              DECIMAL(10),
    AML_CLEARANCE_FLG     DECIMAL(1)     default 0,
    TRX_USER              CHAR(8),
    FX_USR_SN             INTEGER,
    AML_EXPORT            SMALLINT,
    AML_GRP_MESSAGE_ID    VARCHAR(35),
    CATEGORY_PURPOSE      CHAR(4),
    ULTIMATE_CRED_ID      CHAR(37),
    ULTIMATE_DEB_ID       CHAR(37),
    PURPOSE_CODE          CHAR(35),
    INSTR_NEXTAGENTS6     CHAR(1),
    INSTR_NEXTAGENTS5     CHAR(1),
    INSTR_NEXTAGENTS4     CHAR(1),
    INSTR_NEXTAGENTS3     CHAR(1),
    INSTR_NEXTAGENTS2     CHAR(1),
    INSTR_NEXTAGENTS1     CHAR(1),
    CRED_AGENT_INSTR_INFO CHAR(140),
    CRED_AGENT_INSTR_CODE CHAR(4),
    CRED_AGENT_BRANCH     CHAR(35),
    CRED_RESIDENCE_CNTRY  CHAR(2),
    CRED_IDENTIFICATION   CHAR(37),
    CRED_ADDRESS_CNTRY    CHAR(2),
    CRED_ADDRESS_LINE2    CHAR(70),
    CRED_ADDRESS_LINE1    CHAR(70),
    ULTIMATE_CRED_NAME    CHAR(70),
    DEB_AGENT_BRANCH      CHAR(35),
    DEB_RESIDENCE_CNTRY   CHAR(2),
    DEB_IDENTIFICATION    CHAR(37),
    DEB_ADDRESS_CNTRY     CHAR(2),
    DEB_ADDRESS_LINE2     CHAR(70),
    DEB_ADDRESS_LINE1     CHAR(70),
    ULTIMATE_DEB_NAME     CHAR(70),
    ETC_ORIG_INSTR_IDS    VARCHAR(464),
    ADDITIONAL_INFO       VARCHAR(105),
    INTERBANK_SETTLE_DT   DATE,
    RECALL_ORI_GRP_MSG_ID VARCHAR(35)
);

create unique index INDX_DEBIT_1
    on IPS_MESSAGE_HEADER (ORDER_GROUP_1, ORDER_TYPE);

create unique index INDX_FK_ORDER
    on IPS_MESSAGE_HEADER (FK_ORDER_CODE);

create unique index IPS_MSG_HDR_EXTERN_ID_IND
    on IPS_MESSAGE_HEADER (EXTERNAL_ID_REF);

create unique index IPS_MSG_HDR_SORT_INDEX
    on IPS_MESSAGE_HEADER (ORDER_TYPE, ORDER_STATUS, SORT_BIC_ADDRESS, SORT_CREDIT_DEBIT, ORDER_CURRENCY);

create unique index IXN_IPSMSG_02
    on IPS_MESSAGE_HEADER (TRX_DATE, ORDER_TYPE, ORDER_STATUS);

create unique index IXN_IPS_MSG_HDR_01
    on IPS_MESSAGE_HEADER (ORDER_FILENAME, ORDER_STATUS, ORDER_CODE);

create unique index IX_END_TO_END_ID
    on IPS_MESSAGE_HEADER (END_TO_END_ID);

