CREATE PROCEDURE IPS_STATEMENT_RCN_BAL_SEQ
LANGUAGE SQL
DYNAMIC RESULT SETS 1
BEGIN ATOMIC
DECLARE Query VARCHAR(1000);
DECLARE MAX_PROCESS_SN NUMERIC(15,0);
SET MAX_PROCESS_SN = (SELECT COALESCE(MAX(ID),1) FROM IPS_STATEMENT_RCN_BAL);
SET Query = 'CREATE SEQUENCE IPS_STATEMENT_RCN_SEQ AS NUMERIC(15,0) START WITH ' || MAX_PROCESS_SN || ' INCREMENT BY 1 MINVALUE 1 NO CACHE NO CYCLE';
execute immediate Query;
END;

