create table IPS_MESSAGE_STAGE
(
    TP_SO_IDENTIFIER             DECIMAL(10) not null,
    BENEF_FULLNAME               VARCHAR(100),
    BENEF_ADDRESS_LINE_1         VARCHAR(100),
    BENEF_ADDRESS_LINE_2         VARCHAR(100),
    BENEF_ADDRESS_POST_CODE      VARCHAR(10),
    BENEF_ADDRESS_COUNTRY        VARCHAR(2),
    BENEF_RESIDENT               VARCHAR(1),
    BENEF_IDENTIFICATION_TYPE    VARCHAR(5),
    BENEF_IDENTIFICATION_VALUE   VARCHAR(20),
    BENEF_BIC_ADDRESS            VARCHAR(12),
    BENEF_BANK_ACCOUNT           VARCHAR(40),
    ORDER_REMMITANCE_INFO        VARCHAR(140),
    ORDER_CHARGE_BEARER          VARCHAR(4),
    ORDER_INSTR_NEXT_AGENT_3     VARCHAR(1),
    ORDER_INSTRUMENT_JUSTIFIC_ID INTEGER,
    ORDER_INSTRUMENT_CODE        CHAR(10),
    ORDER_CLEARING_SYSTEM        CHAR(11),
    ORDER_PURPOSE_CODE           CHAR(35),
    ORDER_CURRENCY               INTEGER,
    ID_TRANSACT                  INTEGER default 9002,
    ORGANIZATION_CODE            INTEGER,
    DATAFIELD_1                  CHAR(50),
    DATAFIELD_2                  CHAR(50),
    DATAFIELD_3                  CHAR(50),
    DATAFIELD_4                  CHAR(50),
    DATAFIELD_5                  CHAR(50),
    DATAFIELD_6                  CHAR(50)
);

create unique index IXU_CP_128
    on IPS_MESSAGE_STAGE (TP_SO_IDENTIFIER);

