create table IPS_INSTRUMENT
(
    PRFT_TRANS_CODE     INTEGER  not null,
    INSTRUM_CODE        CHAR(10) not null,
    TIME_FROM           CHAR(5),
    TIME_TO             CHAR(5),
    AMOUNT_FROM         DECIMAL(15, 2),
    AMOUNT_TO           DECIMAL(15, 2),
    CREDIT_JUSTIF       INTEGER,
    DEBIT_JUSTIF        INTEGER,
    SERV_SUCC_JUST      INTEGER,
    SERV_UNSUCC_JUST    INTEGER,
    INSTRUM_JUSTIFIC    INTEGER,
    REJECTION_JUSTIFIC  INTEGER,
    CLEARING_SYSTEM     VARCHAR(11),
    EXPORT_OUT_JUST     INTEGER,
    EXPORT_REJ_JUST     INTEGER,
    MECHANISM_CODE      SMALLINT,
    DESCRIPTION         VARCHAR(80),
    CHARGE_OPTIONS      CHAR(20),
    ACTIVE              CHAR(1),
    USER_SELECTABLE     CHAR(1),
    CHARGES_JUSTIFIC    INTEGER,
    CHARGES_TRANSACTION INTEGER,
    AUTOMATIC_REJECTION CHAR(1),
    REJECTION_RERIOD    SMALLINT    default 0,
    CP_AGREEMENT_NO     DECIMAL(10) default 0,
    EXP_OUT_REJ_JUST    INTEGER,
    CSM_NAME            VARCHAR(35),
    STP_LIMIT_AMOUNT    DECIMAL(15, 2)
);

create unique index PK_IPS_INSTRUMENT
    on IPS_INSTRUMENT (CLEARING_SYSTEM, PRFT_TRANS_CODE, INSTRUM_CODE);

create unique index SC_IPS_INSTRUMENT
    on IPS_INSTRUMENT (INSTRUM_JUSTIFIC);

