create table IPS_REMITTANCE_SETUP
(
    REMITTANCE_CODE   CHAR(20) not null,
    REMITTANCE_SN     INTEGER  not null,
    DESCRIPTION       VARCHAR(50),
    ALGORITHM_ID      SMALLINT,
    LABEL_1           CHAR(30),
    SIZE_1            SMALLINT,
    MANDATORY_FLAG_1  CHAR(1),
    LABEL_2           CHAR(30),
    SIZE_2            SMALLINT,
    MANDATORY_FLAG_2  CHAR(1),
    LABEL_3           CHAR(30),
    SIZE_3            SMALLINT,
    MANDATORY_FLAG_3  CHAR(1),
    LABEL_4           CHAR(30),
    SIZE_4            SMALLINT,
    MANDATORY_FLAG_4  CHAR(1),
    LABEL_5           CHAR(30),
    SIZE_5            SMALLINT,
    MANDATORY_FLAG_5  CHAR(1),
    LABEL_6           CHAR(30),
    SIZE_6            SMALLINT,
    MANDATORY_FLAG_6  CHAR(1),
    REMITTANCE_FORMAT VARCHAR(100),
    DF_ORDER_1        SMALLINT,
    DF_ORDER_3        SMALLINT,
    DF_ORDER_4        SMALLINT,
    DF_ORDER_5        SMALLINT,
    DF_ORDER_6        SMALLINT,
    DF_TYPE_1         CHAR(1),
    DF_TYPE_2         CHAR(1),
    DF_TYPE_3         CHAR(1),
    DF_TYPE_4         CHAR(1),
    DF_TYPE_5         CHAR(1),
    DF_ORDER_2        SMALLINT,
    DF_TYPE_6         CHAR(1),
    constraint PK_IPS_REMITTANCE_SETUP
        primary key (REMITTANCE_CODE, REMITTANCE_SN)
);

