create table ISN_CBK_GLOBAL_TRANS
(
    REPORT_DT     DATE                           not null,
    ENT           VARCHAR(4)                     not null,
    TABLENAME     VARCHAR(1)                     not null,
    DEALNUM       INTEGER                        not null,
    ST_DT_SEG     DATE                           not null,
    MT_DT_SEG     DATE                           not null,
    ST_DT         DATE,
    MT_DT         DATE,
    ENT_ORG       VARCHAR(4),
    TABLENAME_ORG VARCHAR(1),
    DEALNUM_ORG   INTEGER,
    CREATE_DT     DATE,
    DEAL_DT       DATE,
    VAL_DT        DATE,
    FINPROD       VARCHAR(10),
    FIN_RECDESC   VARCHAR(35),
    FINPROD_BANK  VARCHAR(40),
    HDG           VARCHAR(1),
    HDG_PURPOSES  VARCHAR(30),
    CUST          VARCHAR(9),
    CUST_RECDESC  VARCHAR(40),
    CUST_REF      VARCHAR(20),
    CUST_INTERBNK VARCHAR(1),
    HDOFCRGN      VARCHAR(8),
    CUSTRGN       VARCHAR(8),
    CUST_ADLINE5  VARCHAR(35),
    CUST_COUNTRY  VARCHAR(3),
    CUSTTYP       VARCHAR(12),
    RECDESC_TYP   VARCHAR(35),
    CCY           VARCHAR(3),
    CCY_LOC_FOR   VARCHAR(20),
    BUY_CCY       VARCHAR(3),
    SEL_CCY       VARCHAR(3),
    BUY_AMT       DECIMAL(18, 4),
    BUY_LOC_AMT   DECIMAL(18, 4),
    SEL_AMT       DECIMAL(18, 4),
    SEL_LOC_AMT   DECIMAL(18, 4),
    SPTBUY_DT     DATE,
    SPTSEL_DT     DATE,
    VALBUY_DT     DATE,
    VALSEL_DT     DATE,
    TRNTYP        VARCHAR(1),
    TRNTYP_DESC   VARCHAR(30),
    REPO_DESC     VARCHAR(30),
    EXCHANGE      VARCHAR(15),
    CONTRACTNUM   INTEGER,
    CNTRCT_AMT    DECIMAL(18, 4),
    PRC           DECIMAL(16, 10),
    AMT           DECIMAL(18, 4),
    LOC_AMT       DECIMAL(18, 4),
    CUMACR_AMT    DECIMAL(18, 4),
    CUMACRLOC_AMT DECIMAL(18, 4),
    INT_AMT       DECIMAL(18, 4),
    INT_RT        DECIMAL(16, 10),
    FX_RT         DECIMAL(16, 10),
    SECURITY      VARCHAR(15),
    ASSET_ID      VARCHAR(15),
    ISSUER        VARCHAR(9),
    ISS_RECDESC   VARCHAR(35),
    ISS_GRP       VARCHAR(5),
    ISS_GRP_REC   VARCHAR(35),
    ISS_TYP       VARCHAR(12),
    ISS_TYP_REC   VARCHAR(35),
    ISS_COUNTRY   VARCHAR(10),
    APSYSTEM      VARCHAR(9) default 'BTSVISION' not null,
    CUSTGRP       VARCHAR(5),
    LIMTGRP       VARCHAR(10),
    LIMCAT        VARCHAR(10),
    LOCAMTLIM     DECIMAL(18, 4)
);

create unique index ISN_CBK_GLOBAL_TRANS_INDX
    on ISN_CBK_GLOBAL_TRANS (REPORT_DT, ENT, TABLENAME, DEALNUM, ST_DT_SEG, MT_DT_SEG);

alter table ISN_CBK_GLOBAL_TRANS
    add constraint PK_ISN_CBK_GLOBAL_TRANS
        primary key (REPORT_DT, ENT, TABLENAME, DEALNUM, ST_DT_SEG, MT_DT_SEG);

