create table ISS_HOUSING_DETAIL
(
    TP_SO_IDENTIFIER    DECIMAL(10) not null
        constraint ISS_HOUSING_DETAILS_PK
            primary key,
    REINSTATEMENT_VAL   DECIMAL(15, 2),
    TMSTAMP             TIMESTAMP(6),
    USE_BASEMENT        CHAR(1),
    USE_GROUND          CHAR(1),
    USE_FLOOR           CHAR(1),
    ADDRESS1            CHAR(40),
    ADDRESS2            CHAR(40),
    CITY                CHAR(20),
    ZIP_CODE            CHAR(10),
    HOUSE_USE           CHAR(1),
    HOUSE_TYPE          INTEGER,
    FLOOR               SMALLINT,
    SQUERE              SMALLINT,
    NO_FLOORS           SMALLINT,
    SKELETON            INTEGER,
    ROOF                INTEGER,
    PARTIAL             CHAR(1),
    PARTIAL_COMMENTS    CHAR(40),
    CONSTR_DATE         DATE,
    EARTHQUAKE_CODE     INTEGER,
    CANCELLED_CONTR     CHAR(1),
    CONTR_COMMENTS      CHAR(40),
    DAMAGE_IND          CHAR(1),
    HS_ISSUANCE_AMOUNT  DECIMAL(15, 2),
    HS_ISSUANCE_CAPITAL DECIMAL(15, 2),
    OTHER_CUST_IND      CHAR(1),
    OTHER_CUST_COMMENT  CHAR(40),
    LNS_ACC_UNIT2       INTEGER,
    LNS_ACC_TYPE2       SMALLINT,
    LNS_ACC_SN2         INTEGER,
    LNS_ACC_CD2         SMALLINT,
    LNS_ACC_UNIT3       INTEGER,
    LNS_ACC_TYPE3       SMALLINT,
    LNS_ACC_SN3         INTEGER,
    LNS_ACC_CD3         SMALLINT,
    BLOCK_AMOUNT        DECIMAL(15, 2),
    LOAN_EXP_DT         DATE,
    LOAN_AMOUNT         DECIMAL(15, 2),
    LOAN_AMOUNT2        DECIMAL(15, 2),
    LOAN_AMOUNT3        DECIMAL(15, 2),
    BLOCK_AMOUNT2       DECIMAL(15, 2),
    BLOCK_AMOUNT3       DECIMAL(15, 2),
    LOAN_EXP_DT2        DATE,
    LOAN_EXP_DT3        DATE,
    WALE                INTEGER
);

