create table ISSU_PROD_PERM_FREQ
(
    FREQUENCY_UNIT CHAR(1),
    FREQUENCY      SMALLINT,
    FK_PRODUCT     INTEGER
);

create unique index ISPRODPE
    on ISSU_PROD_PERM_FREQ (FK_PRODUCT, FREQUENCY, FREQUENCY_UNIT);

