create table ISSUE_ORDER_AGR
(
    FK_CUSTOMERCUST_ID INTEGER,
    CUST_SAME_FLG      CHAR(1),
    REGION             SMALLINT,
    STP_FLAG           CHAR(1),
    DETAIL_OF_CHARGE   CHAR(3),
    TRX_CODE           INTEGER,
    DURATION           INTEGER,
    ID_EXP_USAGE5      SMALLINT,
    ID_EXP_USAGE4      SMALLINT,
    ID_EXP_USAGE3      SMALLINT,
    ID_EXP_USAGE2      SMALLINT,
    ID_EXP_USAGE1      SMALLINT,
    ID_COM_USAGE5      SMALLINT,
    ID_COM_USAGE4      SMALLINT,
    ID_COM_USAGE3      SMALLINT,
    ID_COM_USAGE2      SMALLINT,
    ID_COM_USAGE1      SMALLINT,
    ID_TAX_5           INTEGER,
    ID_TAX_4           INTEGER,
    ID_TAX_3           INTEGER,
    ID_TAX_2           INTEGER,
    ID_TAX_1           INTEGER,
    ID_EXPENSE_5       INTEGER,
    ID_EXPENSE_4       INTEGER,
    ID_EXPENSE_3       INTEGER,
    ID_EXPENSE_2       INTEGER,
    ID_EXPENSE_1       INTEGER,
    ID_COMMISSION_5    INTEGER,
    ID_COMMISSION_4    INTEGER,
    ID_COMMISSION_3    INTEGER,
    ID_COMMISSION_2    INTEGER,
    ID_COMMISSION_1    INTEGER,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_ISS_000
    on ISSUE_ORDER_AGR (FK_CUSTOMERCUST_ID, CUST_SAME_FLG, REGION, STP_FLAG, DETAIL_OF_CHARGE, TRX_CODE, DURATION);

