create table ISSU_PROD_PERM
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERMISSIBLE_IND    CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_ISS_002
    on ISSU_PROD_PERM (FK_PRODUCTID_PRODU, FK_GENERIC_DETAFK, FK_GENERIC_DETASER);

