create table ISSU_MIGR_COMPANY
(
    ISSUE_TYPE          SMALLINT,
    NUMBER_OF_ATTEMPTS  SMALLINT,
    SERV_PRODUCT_ID     INTEGER,
    MAX_NUMBER_ATTEMPTS INTEGER,
    CATEGORY_ID         INTEGER,
    CR_ACC_CUSTOMER_ID  INTEGER,
    CR_DEP_ACCOUNT      DECIMAL(11),
    RENEWAL_DATE        DATE,
    EXPIRATION_DATE     DATE,
    ACTIVATION_DATE     DATE,
    INSU_COMP_ID        CHAR(2),
    MIGR_ISSU_TYPE      CHAR(5)
);

create unique index ISSU_MIGR_COMPANY
    on ISSU_MIGR_COMPANY (MIGR_ISSU_TYPE, INSU_COMP_ID);

