create table LG
(
    FK_PRODUCTID_PRODU INTEGER,
    REVIEW_FREQ        SMALLINT,
    COM_CHARGE_FREQ    SMALLINT,
    FKGD_CBANK_RISK    INTEGER,
    FKGD_BANK_RISK     INTEGER,
    FKGD_CREDIT_LINE   INTEGER,
    FKGD_ACCOUNT_TYPE  INTEGER,
    RISK_FACTOR        DECIMAL(8, 4),
    MAX_AMN_TOLERANCE  DECIMAL(8, 4),
    MIN_AMN_TOLERANCE  DECIMAL(8, 4),
    LST_PRINT_TRANS_DT DATE,
    PRINT_STATEMENT_DT DATE,
    NXT_PRINT_TRANS_DT DATE,
    TMSTAMP            TIMESTAMP(6),
    COM_CHARGE_FRQ_TYP CHAR(1),
    ENTRY_STATUS       CHAR(1),
    WITHIN_LIMIT_FLG   CHAR(1),
    GL_NETWORK_LVL     CHAR(1),
    DR_GL_ACCOUNT_LVL  CHAR(1),
    CR_GL_ACCOUNT_LVL  CHAR(1),
    LG_TYPE            CHAR(1),
    FKGH_CBANK_RISK    CHAR(5),
    FKGH_BANK_RISK     CHAR(5),
    FKGH_CREDIT_LINE   CHAR(5),
    FKGH_ACCOUNT_TYPE  CHAR(5),
    GENERAL_FLAGS      CHAR(10),
    DR_GL_ACCOUNT      CHAR(21),
    CR_GL_ACCOUNT      CHAR(21),
    GL_NETWORK_ACC     CHAR(21)
);

create unique index IXU_LG0_000
    on LG (FK_PRODUCTID_PRODU);

