create table LG_SPC_AGRMNT
(
    FK_LG_ACCOUNTACC_S DECIMAL(13),
    FK_PRFT_TRANSACID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    TMSTAMP            TIMESTAMP(6),
    VALUE_DATE_SPREAD  SMALLINT,
    COM_CHARGE_FRQ     SMALLINT,
    AVAIL_DATE_SPREAD  SMALLINT,
    COMMISS_DISCOUNT   DECIMAL(8, 4),
    COMMISSION_PERCENT DECIMAL(8, 4),
    EXPENCE_DISCOUNT   DECIMAL(8, 4),
    MIN_COMMISION_AMNT DECIMAL(15, 2),
    EXPIRY_DATE        DATE,
    LAST_UPD_DT        DATE,
    COM_CHARGE_FRQ_TYP CHAR(1),
    ENTRY_STATUS       CHAR(1),
    USR                CHAR(8)
);

create unique index PIXSPCAGRM
    on LG_SPC_AGRMNT (FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST, FK_LG_ACCOUNTACC_S, TMSTAMP);

