create table LG_TRXJUST
(
    FK_JUSTIFICID_JUST INTEGER,
    FK_LGFK_PRODUCTID  INTEGER,
    FK_PRFT_TRANSACID  INTEGER,
    FK_DOCUMENT_TEMPRF SMALLINT,
    MIN_VALUE_DAYS     SMALLINT,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    VALUE_DAYS         SMALLINT,
    AVAIL_DAYS         SMALLINT,
    MAX_VALUE_DAYS     SMALLINT,
    MAX_AVAIL_DAYS     SMALLINT,
    MIN_AVAIL_DAYS     SMALLINT,
    FK_CURRENCYID_CURR INTEGER,
    FKGD_HAS_LANGUAGE  INTEGER,
    FK_ACCOUNTING_RID  INTEGER,
    FK_PARAMETRIC_RID  INTEGER,
    FK_DOCUMENT_TEMCOD INTEGER,
    COM_LOW_LIMIT      DECIMAL(8, 4),
    EXP_LOW_LIMIT      DECIMAL(8, 4),
    EXP_UP_LIMIT       DECIMAL(8, 4),
    COM_UP_LIMIT       DECIMAL(8, 4),
    MAX_TRN_AMOUNT     DECIMAL(15, 2),
    MIN_TRN_AMOUNT     DECIMAL(15, 2),
    VALIDITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    RECYCLED_LIMIT     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    DEFAULT_INDICATOR  CHAR(1),
    CURRENCY_TYPE      CHAR(1),
    HOME_BRANCH        CHAR(1),
    PROFIT_INDICATOR   CHAR(1),
    FKGH_HAS_LANGUAGE  CHAR(5)
);

create unique index IXU_LG__011
    on LG_TRXJUST (FK_JUSTIFICID_JUST, FK_LGFK_PRODUCTID, FK_PRFT_TRANSACID);

