create table LMS_BANK_INFO
(
    LMS_BANKS_SN      DECIMAL(10) not null,
    SN                DECIMAL(10) not null,
    K_BANK_CODE       SMALLINT    not null,
    K_BANK_TAX_REG_NO VARCHAR(10),
    K_BANK_NAME       VARCHAR(40),
    K_BANK_ADDRESS    VARCHAR(40),
    K_VDATABASE_DBID  DECIMAL(15),
    K_VDATABASE_NAME  CHAR(15),
    K_VINSTANCE_HOST  CHAR(15),
    K_VINSTANCE_NAME  CHAR(15),
    K_MAC_ADDRESS     CHAR(80),
    K_DATABASE_USER   CHAR(80),
    LICENSE_FREQ      INTEGER,
    LICENSE_FREQ_TYPE CHAR(1),
    PRV_DATE_KEY_DT   DATE,
    NXT_DATE_KEY_DT   DATE,
    EMAIL_BANK_ADDR   CHAR(254),
    EMAIL_FILE_PATH   CHAR(200),
    LICENSE_COMMENTS  VARCHAR(500),
    ENVIRONMENT_TYPE  CHAR(1),
    constraint PK_LMS_5
        primary key (LMS_BANKS_SN, SN)
);

