create table LMS_BANKS
(
    SN                  DECIMAL(10) not null
        constraint PK_LMS_99
            primary key,
    BANK_NAME           CHAR(80),
    BANK_NOTES          VARCHAR(2056),
    BANK_STATUS         CHAR(1),
    CONTACT_1           CHAR(80),
    CONTACT_1_EMAIL     CHAR(254),
    CONTACT_1_TELEPHONE CHAR(80),
    CONTACT_1_MOBILE    CHAR(80),
    CONTACT_2           CHAR(80),
    CONTACT_2_EMAIL     CHAR(254),
    CONTACT_2_TELEPHONE CHAR(80),
    CONTACT_2_MOBILE    CHAR(80),
    CONTACT_3           CHAR(80),
    CONTACT_3_EMAIL     CHAR(254),
    CONTACT_3_TELEPHONE CHAR(80),
    CONTACT_3_MOBILE    CHAR(80),
    CONTACT_4           CHAR(80),
    CONTACT_4_EMAIL     CHAR(254),
    CONTACT_4_TELEPHONE CHAR(80),
    CONTACT_4_MOBILE    CHAR(80),
    CONTACT_5           CHAR(80),
    CONTACT_5_EMAIL     CHAR(254),
    CONTACT_5_TELEPHONE CHAR(80),
    CONTACT_5_MOBILE    CHAR(80),
    LICENSE_FIRST_DATE  DATE,
    TOTAL_PROD_ISSUED   DECIMAL(10),
    TOTAL_TEST_ISSUED   DECIMAL(10),
    PROD_EXPIRY_DATE    DATE,
    FILE_PATH_IN        VARCHAR(200),
    FILE_PATH_OUT       VARCHAR(200),
    LICENSE_FREQ        INTEGER,
    LICENSE_FREQ_TYPE   CHAR(1)
);

