create table LNS_MNT_LOAD
(
    OLD_AGR_NO           CHAR(40) not null,
    OLD_LNS_NO           CHAR(40) not null,
    COLL_STATUS          SMALLINT,
    LNS_TRN_STATUS       SMALLINT,
    NEW_ACC_CD           SMALLINT,
    PRFT_ACC_C_DIGIT     SMALLINT,
    MIG_STATUS           SMALLINT,
    DEP_ACC_TYPE         SMALLINT,
    DEP_ACC_CD           SMALLINT,
    ACC_TYPE             SMALLINT,
    NEW_ACC_TYPE         SMALLINT,
    RECYCLING_FRQ        SMALLINT,
    SPRD_DURATION        SMALLINT,
    INSTALL_COUNT        SMALLINT,
    INSTALL_FREQ         SMALLINT,
    MORATORIUM_INT_FRQ   SMALLINT,
    AGR_YEAR             SMALLINT,
    CLOAN_CODE           INTEGER,
    BSECT_CODE           INTEGER,
    CBPURP_CODE          INTEGER,
    LPURP_CODE           INTEGER,
    FINSC_CODE           INTEGER,
    CCODE_CODE           INTEGER,
    CHARGE_CURR          INTEGER,
    MOVE_CURR            INTEGER,
    LIMIT_CURR           INTEGER,
    DEP_CURR             INTEGER,
    AGR_UNIT             INTEGER,
    AGR_SN               INTEGER,
    AGR_MEMBERSHIP_SN    INTEGER,
    ACC_UNIT             INTEGER,
    TRX_UNIT             INTEGER,
    ID_PRODUCT           INTEGER,
    FLOATING_INT_CODE    INTEGER,
    DEP_ACC_UNIT         INTEGER,
    NEW_ACC_UNIT         INTEGER,
    ID_INTEREST          INTEGER,
    FUT_ID_INTEREST      INTEGER,
    NEW_ACC_SN           INTEGER,
    CR_INT_SPRD          DECIMAL(8, 4),
    FUT_INT_SPRD         INTEGER,
    FIXED_INTER_PERC     DECIMAL(8, 4),
    INTER_RATE_SPRD      DECIMAL(8, 4),
    SPRD_PERCENT         DECIMAL(9, 6),
    MP_INTEREST          DECIMAL(9, 6),
    DEP_ACC_SN           DECIMAL(10),
    PRFT_DEP_ACC_NO      DECIMAL(11),
    UNCLEAR_AMN          DECIMAL(15, 2),
    POSITIVE_AMN         DECIMAL(15, 2),
    ACC_LIMIT_AMN        DECIMAL(15, 2),
    DORMANT_AMN          DECIMAL(15, 2),
    ACC_OPEN_DT          DATE,
    CUR_FX_INT_EXP_DT    DATE,
    ACC_EXP_DT           DATE,
    LNS_TRN_TMSTAMP      DATE,
    LNS_TRN_PROCESS_DATE DATE,
    COLL_PROCESS_DATE    DATE,
    COLL_TMSTAMP         DATE,
    FUT_FX_INT_SCAL_DT   DATE,
    CR_SPRD_ST_DT        DATE,
    FUT_FX_INT_EXP_DT    DATE,
    FUT_SPRD_ST_DT       DATE,
    CUR_FX_INT_SCAL_DT   DATE,
    CR_SPRD_END_DT       DATE,
    FUT_SPRD_END_DT      DATE,
    NEW_ACC_EXP_DT       DATE,
    SPRD_END_DT          DATE,
    INT_SCAL_DT          DATE,
    CURR_TRX_DT          DATE,
    INSTALL_NEXT_DT      DATE,
    INSTALL_FIRST_DT     DATE,
    DRAWDOWN_EXP_DT      DATE,
    INT_CAPITAL_FLG      CHAR(1),
    INT_PAYABLE_FLG      CHAR(1),
    SPREAD_FLG           CHAR(1),
    STATEMENT_FREQ       CHAR(1),
    ACCOUNT_CD           CHAR(2),
    MOVE_SHORT_DESC      CHAR(5),
    DEP_SHORT_DESC       CHAR(5),
    MG_ACCOUNT_TYPE      CHAR(5),
    USR_CODE             CHAR(8),
    OLD_DEP_NO           CHAR(15),
    USE_FIXED            CHAR(20),
    ACC_DESCRIPTION      CHAR(40),
    DEP_ACCOUNT_NO       CHAR(40),
    LNS_TRN_ERR_DESC     CHAR(80),
    COLL_ERR_DESC        VARCHAR(80),
    constraint IXU_MIG_009
        primary key (OLD_AGR_NO, OLD_LNS_NO)
);

