create table LNS_ADJUSTMENT_LOG
(
    TRX_DATE       DATE,
    TRX_UNIT       INTEGER,
    TRX_USER       CHAR(8),
    TRX_USER_SN    INTEGER,
    INTERNAL_SN    INTEGER,
    TMSTAMP        TIMESTAMP(6),
    REFERENCE      CHAR(40),
    TRX_CODE       INTEGER,
    FIELD_CODE     INTEGER,
    PREVIOUS_VALUE CHAR(40),
    CURRENT_VALUE  CHAR(40),
    REF_IND        CHAR(1)
);

create unique index IXP_LNS_000
    on LNS_ADJUSTMENT_LOG (INTERNAL_SN, TRX_DATE, TRX_UNIT, TRX_USER, TRX_USER_SN);

