create table LNS_CRD_LOAN_DATA
(
    REPORTING_DATE        DATE        not null,
    LOAN_CODE             VARCHAR(40) not null,
    LOAN_PURPOSE          VARCHAR(128),
    LOAN_CURRENCY         VARCHAR(128),
    LOAN_PHASE            VARCHAR(128),
    LOAN_NEGATIVE_STATUS  VARCHAR(128),
    RECHEDULER_LOAN       VARCHAR(128),
    PAST_DUE_DAYS         DECIMAL(10),
    PAST_DUE_AMOUNT       DECIMAL(15, 2),
    ECONOMIC_SECTOR       VARCHAR(128),
    LOAN_END_DATE         DATE,
    LAST_PAYMENT_DATE     DATE,
    REAL_LOAN_END_DATE    DATE,
    LOAN_START_DATE       DATE,
    ADDITIONAL_FEE_SUM    DECIMAL(15, 2),
    ADDITIONAL_FEE_PAID   DECIMAL(15, 2),
    LOAN_TYPE             VARCHAR(128),
    LOAN_AMOUNT           DECIMAL(15, 2),
    INSTALLMENT_TYPE      VARCHAR(128),
    PAYMENTS_PERIODICITY  VARCHAR(128),
    PAYMENT_METHOD        VARCHAR(128),
    TOTAL_INSTALLMENTS    DECIMAL(15, 2),
    INSTALLMENT_AMOUNT    DECIMAL(15, 2),
    OVERDUE_INSTAL_COUNT  DECIMAL(15, 2),
    OVERDUE_AMOUNT        DECIMAL(15, 2),
    OVERDUE_REMAIN_INSTAL DECIMAL(15, 2),
    REMAINING_CAPITAL_AMN DECIMAL(15, 2),
    constraint CRDLO01
        primary key (REPORTING_DATE, LOAN_CODE)
);

