create table LNS_MIGR
(
    OLD_LNS_NO         CHAR(15)       not null
        constraint PKLNSMIG
            primary key,
    ACC_UNIT           INTEGER,
    ACC_TYPE           SMALLINT       not null,
    ACC_SN             INTEGER,
    ACC_CD             SMALLINT,
    OLD_DEP_NO         CHAR(15),
    DEP_ACC_UNIT       INTEGER,
    DEP_ACC_TYPE       SMALLINT,
    DEP_ACC_SN         DECIMAL(10),
    DEP_ACC_CD         SMALLINT,
    TEX_PERCENT        DECIMAL(9, 6),
    PERCENT            DECIMAL(9, 6),
    TEX_PEN_PERCENT    DECIMAL(9, 6),
    PENALTY_PERCENT    DECIMAL(9, 6),
    ID_INTEREST        INTEGER,
    PENALTY_ID_INT     INTEGER,
    LIMIT_CURRENCY     INTEGER,
    MOVE_CURRENCY      INTEGER,
    PRODUCT_ID         INTEGER,
    PROD_DESCR         CHAR(40),
    OLD_AGR_NO         CHAR(15),
    AGR_UNIT           INTEGER,
    AGR_SN             INTEGER,
    AGR_MEMBERSHIP_SN  SMALLINT,
    ACC_OPEN_DT        DATE,
    AGR_SIGNING_DT     DATE,
    MORATORIUM_INT_FRQ SMALLINT,
    MORATORIUM_INT_DT  DATE,
    ACC_EXP_DT         DATE,
    ACC_LIMIT_AMN      DECIMAL(15, 2) not null,
    DRAWDOWN_EXP_DT    DATE,
    INT_CAPITALIZE_FLG CHAR(1),
    INTER_RATE_SPRD    DECIMAL(8, 4),
    INSTALL_FREQ       SMALLINT,
    INSTALL_COUNT      SMALLINT,
    INSTALL_NEXT_DT    DATE,
    INSTALL_PREV_DT    DATE,
    REQ_INSTALL_SN     SMALLINT,
    CUST_ID            INTEGER
);

