create table LNS_BTC_EXTRAIT
(
    CUST_ID            INTEGER,
    C_DIGIT            SMALLINT not null,
    FIRST_NAME         CHAR(20),
    SURNAME            CHAR(70) not null,
    ACCOUNT_NUMBER     CHAR(40) not null,
    ACCOUNT_CD         SMALLINT,
    TRX_DATE           DATE,
    VALEUR_DT          DATE,
    TRANSACTION_CODE   INTEGER,
    TRANS_DESC         VARCHAR(40),
    JUSTIFICATION_CODE INTEGER,
    JUST_DESC          VARCHAR(40),
    TRX_INTERNAL_SN    SMALLINT,
    AMOUNT             DECIMAL(15, 2),
    AMT_TYPE           CHAR(5),
    AMT_DESC           VARCHAR(40),
    DB_CR              CHAR(1),
    REQUEST_TYPE       CHAR(1),
    REQUEST_TYPE_DESC  VARCHAR(20),
    REQUEST_LOAN_STS   CHAR(1),
    REQ_LOAN_STS_DESC  VARCHAR(20),
    REQUEST_SN         SMALLINT,
    RQ_EXPIRE_DT       DATE,
    TRX_UNIT           INTEGER,
    TRX_USR            CHAR(8),
    EXTRAIT_COMMENTS   VARCHAR(40),
    TRX_SN             INTEGER,
    REVERSED_FLG       CHAR(1),
    TRX                VARCHAR(101),
    TUN_REV            VARCHAR(101),
    TRX_REV_FLG        CHAR(1),
    TMSTAMP            TIMESTAMP(6)
);

