create table LNS_STAND_DEPOS
(
    ACCOUNT_NUMBER CHAR(40)     not null,
    PRFT_SYSTEM    SMALLINT     not null,
    ACCOUNT_CD     SMALLINT,
    SO_ACCOUNT_NUM CHAR(40)     not null,
    SO_PRFT_SYSTEM SMALLINT     not null,
    SO_ACCOUNT_CD  SMALLINT,
    PRIORITY_ORDER SMALLINT,
    ENTRY_STATUS   CHAR(1)      not null,
    TMSTAMP        TIMESTAMP(6) not null,
    UPD_TMPSTAMP   TIMESTAMP(6),
    constraint PK_LNS_STAND_DEPOS
        primary key (ACCOUNT_NUMBER, PRFT_SYSTEM, SO_ACCOUNT_NUM, SO_PRFT_SYSTEM, TMSTAMP)
);

