create table LNS_CRD_CUST_DATA
(
    REPORTING_DATE       DATE     not null,
    CUST_ID              CHAR(32) not null,
    CUST_TYPE            CHAR(1),
    IND_CLASS            CHAR(32),
    FIRST_NAME           CHAR(128),
    MIDDLE_NAME          CHAR(128),
    SURNAME              CHAR(128),
    MARITAL_STS          CHAR(10),
    SPOUSE_FULLNAME      CHAR(128),
    GENDER               CHAR(6),
    BIRTH_SURNAME        CHAR(128),
    NATIONALITY          CHAR(2),
    CITIZENSHIP          CHAR(2),
    PROFESSION           CHAR(32),
    EMPLOYER             CHAR(128),
    MONTHLY_INC_AMN      DECIMAL(18, 4),
    MONTHLY_INC_CUR      CHAR(3),
    NUM_OF_CHILDREN      DECIMAL(2),
    NUM_OF_SPOUSES       DECIMAL(2),
    EDUCATION            CHAR(12),
    MONTHLY_EXP_AMN      DECIMAL(18, 4),
    MONTHLY_EXP_CUR      CHAR(3),
    DATE_OF_BIRTH        DATE,
    DISTRICT_OF_BIRTH    CHAR(32),
    COUNTRY_OF_BIRTH     CHAR(2),
    PASSPORT_ID          CHAR(16),
    P_ISSUE_DT           DATE,
    P_EXPIRE_DT          DATE,
    P_ISSUE_LOCAT        CHAR(32),
    P_ISSUE_AUTH         CHAR(128),
    DRIVING_LICENCE_ID   CHAR(16),
    DL_ISSUE_DT          DATE,
    DL_EXPIRE_DT         DATE,
    DL_ISSUE_LOCAT       CHAR(32),
    DL_ISSUE_AUTH        CHAR(128),
    NATIONAL_ID          CHAR(20),
    NI_ISSUE_DT          DATE,
    NI_EXPIRE_DT         DATE,
    NI_ISSUE_LOCAT       CHAR(32),
    NI_ISSUE_AUTH        CHAR(128),
    PERMISSION_ID        CHAR(16),
    PR_ISSUE_DT          DATE,
    PR_EXPIRE_DT         DATE,
    PR_ISSUE_LOC         CHAR(32),
    PR_ISSUE_AUTH        CHAR(128),
    VOTER_REG_ID         CHAR(16),
    VR_ISSUE_DT          DATE,
    VR_EXPIRE_DT         DATE,
    VR_ISSUE_LOC         CHAR(32),
    VR_ISSUE_AUTH        CHAR(128),
    WARD_ID              CHAR(16),
    WI_ISSUE_DT          DATE,
    WI_EXPIRE_DT         DATE,
    WI_ISSUE_LOC         CHAR(32),
    WI_ISSUE_AUTH        CHAR(128),
    ZANZIBAR_ID          CHAR(16),
    ZI_ISSUE_DT          DATE,
    ZI_EXPIRE_DT         DATE,
    ZI_ISSUE_LOC         CHAR(32),
    ZI_ISSUE_AUTH        CHAR(128),
    BUSINESS_NAME        CHAR(128),
    CELLULAR_PHONE       CHAR(16),
    FIXED_LINE           CHAR(16),
    FAX                  CHAR(16),
    EMAIL                CHAR(64),
    WEBPAGE              CHAR(64),
    LEGAL_FORM           CHAR(32),
    NO_OF_EMPLOYEES      DECIMAL(5),
    REGISTRATION_COUNTRY CHAR(2),
    REGISTRATION_NUMBER  CHAR(32),
    TAX_ID               CHAR(16),
    constraint CRDCU01
        primary key (REPORTING_DATE, CUST_ID)
);

