create table LNS_TAX
(
    ID_TAX             INTEGER,
    FK_HSERVICE_PRISNU SMALLINT,
    USAGE_COUNTER      SMALLINT,
    FK_CURRENCYID_CURR INTEGER,
    FK0HSERVICE_PRIFK  INTEGER,
    FK_HSERVICE_PRIFK0 INTEGER,
    FK_HSERVICE_PRIFK1 INTEGER,
    FK_HSERVICE_PRIFK  DATE,
    TMSTAMP            TIMESTAMP(6),
    CONFIRM_DATE       DATE,
    FK1HSERVICE_PRIFK  DATE,
    APPLY_TAX          CHAR(1),
    ENTRY_STATUS       CHAR(1),
    CONFIRM_IND        CHAR(1),
    CURRENCY_EXIST_FLG CHAR(1),
    SHORT_DESCR        CHAR(5),
    DESCRIPTION        VARCHAR(40)
);

create unique index IXU_LNS_000
    on LNS_TAX (ID_TAX);

