create table LNS_GLI_INTERFACE
(
    FK_USRCODE         CHAR(8),
    FK_UNITCODE        INTEGER,
    TRN_DATE           DATE,
    LINE_NUM           SMALLINT,
    TRN_SNUM           INTEGER,
    C_DIGIT            SMALLINT,
    AMOUNT_SER_NO      SMALLINT,
    PRF_ACC_CD         SMALLINT,
    FK_TRANSACTION0ID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    DEPT_SN            INTEGER,
    FK0UNITCODE        INTEGER,
    FK_CURR_TABLE_PFK  INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK1UNITCODE        INTEGER,
    FK_CUSTOMERCODE    INTEGER,
    DOC_NUM            INTEGER,
    FK_CURR_TABLE_PFK0 INTEGER,
    REF_NUM            DECIMAL(10),
    ACCOUNT_NUMBER     DECIMAL(10),
    DEAL_SLIP_NUM      DECIMAL(10),
    RATE               DECIMAL(12, 6),
    LNS_ACCOUNT_NUMBER DECIMAL(13),
    AMOUNT             DECIMAL(15, 2),
    GL_TRN_DATE        DATE,
    VALEUR_DATE        DATE,
    CANCEL_DATE        DATE,
    ACCOUNTED_FLAG     CHAR(1),
    ACCNT_LEVEL        CHAR(1),
    DOC_TYPE           CHAR(1),
    ENTRY_STATUS       CHAR(1),
    ENTRY_TYPE         CHAR(1),
    RECON_FLAG         CHAR(1),
    REF_NUM_FLAG       CHAR(1),
    PRIM_AGRE_IND      CHAR(1),
    TRN_TYPE           CHAR(1),
    TRN_ACTION_TYPE    CHAR(1),
    AUTO_FLAG          CHAR(1),
    FK_GLG_JOURNALJOUR CHAR(2),
    FK_GLG_DOCUMENTDO0 CHAR(2),
    SUBSYSTEM          CHAR(2),
    GLACC_ORIGIN       CHAR(2),
    FK_GLG_JUSTIFYJUST CHAR(4),
    FK_GLG_CURR_CATCUR CHAR(4),
    FK_GLG_DOCUMENTDOC CHAR(4),
    FK_GLG_MODEL_TRTRN CHAR(6),
    FK_COST_MODEL_TTRN CHAR(6),
    DOC_CTL_NUM        CHAR(9),
    TAX_REG_NO         CHAR(10),
    FK_GLG_ACCOUNTACCO CHAR(21),
    REMARKS            CHAR(50),
    PRF_ACCOUNT_NUMBER CHAR(40),
    FK_TERMINALTERMINA CHAR(99),
    TRX_CATEGORY       CHAR(1)
);

create unique index ESKORT_IDX2
    on LNS_GLI_INTERFACE (TRX_CATEGORY, ENTRY_TYPE, FK_TRANSACTION0ID);

create unique index IDX_LNS_VW1
    on LNS_GLI_INTERFACE (FK_GLG_ACCOUNTACCO, TRN_DATE, FK_CURRENCYID_CURR, FK1UNITCODE, REMARKS);

create unique index IXN_LNS_001
    on LNS_GLI_INTERFACE (FK1UNITCODE, FK_CURRENCYID_CURR, FK_GLG_ACCOUNTACCO, GL_TRN_DATE);

create unique index IXN_LNS_033
    on LNS_GLI_INTERFACE (REMARKS);

create unique index IXN_LNS_GLI_BATCH_CONS
    on LNS_GLI_INTERFACE (FK1UNITCODE asc, ACCOUNTED_FLAG desc);

create unique index IXU_LNS_006
    on LNS_GLI_INTERFACE (FK_USRCODE, FK_UNITCODE, TRN_DATE, LINE_NUM, TRN_SNUM);

