create table LNS_INTEREST
(
    ID_INTEREST        INTEGER,
    BALN_INTEREST_FREQ SMALLINT,
    USAGE_COUNTER      SMALLINT,
    DAYSBASE           SMALLINT,
    INT_DURATION       SMALLINT,
    FK_GD_SNUM         INTEGER,
    FK_GENERIC_DETASER INTEGER,
    FIX_INT_EXP_DT     DATE,
    TMSTAMP            TIMESTAMP(6),
    DAYS_RETRIEVAL_IND CHAR(1),
    FIX_INT_DT_CHG_FLG CHAR(1),
    EXCESS_CALC_FLG    CHAR(1),
    ENTRY_STATUS       CHAR(1),
    SINGLE_SCALE_IND   CHAR(1),
    FOR_DEBIT          CHAR(1),
    DURATION_UNIT      CHAR(1),
    DURATION_IND       CHAR(1),
    FIXED_FLG          CHAR(1),
    NEGOTIATION_FLAG   CHAR(1),
    APPLY_INTER        CHAR(1),
    AVG_VAL_BALNC      CHAR(1),
    FK_GH_PAR_TYPE     CHAR(5),
    FK_GENERIC_DETAFK  CHAR(5),
    DESCRIPTION        VARCHAR(40)
);

create unique index IXU_LNS_004
    on LNS_INTEREST (ID_INTEREST);

