create table LNS_INSTANT_SETUP
(
    PROGRAM_SN               INTEGER            not null,
    FIRST_FX_JUSTIFIC        INTEGER,
    FIRST_FX_TRANSACT        INTEGER,
    FX_PRODUCT_ID            INTEGER,
    SECOND_FX_JUSTIFIC       INTEGER,
    SECOND_FX_TRANSACT       INTEGER,
    FX_JUSTIFIC_ID           INTEGER,
    FX_TRANSACT_ID           INTEGER,
    AGR_LOAN_COLL_FLG        CHAR(1),
    FLOATING_INTEREST        INTEGER,
    FIXED_INTEREST           INTEGER,
    CBPURP                   INTEGER,
    FINSC                    INTEGER,
    LPURP                    INTEGER,
    DEP_ACC_TYPE             INTEGER,
    LNS_CLOAN                INTEGER,
    LNS_CCODE                INTEGER,
    DEP_CCODE                INTEGER,
    DEP_CLOAN                INTEGER,
    SALES_UNIT               INTEGER,
    SALES_PERSON             INTEGER,
    AGR_PRODUCT_ID           INTEGER,
    DEP_PRODUCT_ID           INTEGER,
    LNS_PRODUCT_ID           INTEGER,
    COLL_PRODUCT_ID          INTEGER,
    BSECT                    INTEGER,
    ACCOUNTS_PERMIT          SMALLINT,
    DESCRIPTION              VARCHAR(50),
    EXCL_DEP_STND_LNK        CHAR(1),
    FIXED_INST_FLG           CHAR(1),
    MIN_INSTALL_CNT          SMALLINT,
    MAX_INSTALL_CNT          SMALLINT,
    MIN_FREQ                 SMALLINT,
    MAX_FREQ                 SMALLINT,
    PERM_ALLOC_TYPE          CHAR(1),
    ELIGIBLE_AMN_CHECK       CHAR(1),
    STEP_SELECTION_FLG       CHAR(50),
    APPLICATION_PRODUCT      INTEGER,
    REGISTRY_TYPE            INTEGER,
    DYNAMIC_REGISTRY_CODE    CHAR(20),
    CUST_ID_TYPE             INTEGER,
    CUST_ECONOMIC_GRP        INTEGER,
    CUST_ACTIVITY_TYPE       INTEGER,
    CUSTOMER_ACTIVITY        INTEGER,
    CUST_PROFESSION_STS      INTEGER,
    CUST_PROFESSION          INTEGER,
    CUST_CARD_TYPE           INTEGER,
    ADDRESS_COUNTRY          CHAR(10),
    RELATIONSHIP_TYPE        CHAR(12),
    INSTANT_MECHANISM        SMALLINT default 0 not null,
    ID_COUNTRY               CHAR(10),
    INT_CALC_STOP_FLG        CHAR(1),
    MECH_6_RENT_FLG          CHAR(1),
    VALIDATION_SELECTION_FLG CHAR(50),
    ENTRY_STATUS             CHAR(1),
    ELIGIBLE_FACTOR          DECIMAL(8, 4),
    LOAN_EXTRA_JUSTIFIC      INTEGER,
    LOAN_EXTRA_TRANSACT      INTEGER,
    DEP_EXTRA_JUSTIFIC       INTEGER,
    DEP_EXTRA_TRANSACT       INTEGER,
    INSTALLMENT_TOL          SMALLINT,
    INTEREST_TOL             SMALLINT,
    LOAN_RQ_TOL              SMALLINT,
    CHARGES_TOL              SMALLINT,
    PROMISSORY_TOL           SMALLINT,
    GP_INTEREST_MANIPULATION CHAR(5),
    constraint INST_PRG
        primary key (PROGRAM_SN, INSTANT_MECHANISM)
);

