create table LNS_PRD_CHNG_DF
(
    OLD_ACC_SN        INTEGER,
    OLD_ACC_TYPE      SMALLINT,
    OLD_ACC_UNIT      INTEGER,
    UD_CUSTOMER_CODE  DECIMAL(10),
    UD_ACCOUNT_NUMBER CHAR(40),
    UD_PRFT_SYSTEM    SMALLINT,
    UD_RECORD_TYPE    CHAR(2),
    PFG_TAG_SET_CODE  CHAR(20),
    PFG_TAG           CHAR(10),
    PFG_SET_SN        INTEGER,
    PFG_SET_CATEGORY  CHAR(1),
    SHOW_ORDER        INTEGER,
    FIELD_LABEL       CHAR(40),
    FIELD_VALUE       VARCHAR(100),
    UD_SN             SMALLINT,
    TRX_DATE          DATE,
    TMSTMP            TIMESTAMP(6),
    REVERSED_FLAG     CHAR(1),
    TRX_USR           CHAR(8)
);

create unique index IXU_LOA_068
    on LNS_PRD_CHNG_DF (OLD_ACC_SN, OLD_ACC_TYPE, OLD_ACC_UNIT, UD_CUSTOMER_CODE, UD_ACCOUNT_NUMBER, UD_PRFT_SYSTEM,
                        UD_RECORD_TYPE, PFG_TAG_SET_CODE, PFG_TAG, PFG_SET_SN, PFG_SET_CATEGORY, UD_SN);

