create table LNS_INSTANT_APP_REPRESENT
(
    IMAGE_TYPE_2      VARCHAR(20) not null,
    IMAGE_2           BLOB(1048576),
    CATEGORY_ID_2     CHAR(4)     not null,
    FILENAME_2        CHAR(75)    not null,
    DESCRIPTION_2     CHAR(100),
    COMMENTS_2        CHAR(100),
    IMAGE_TYPE_1      VARCHAR(20) not null,
    IMAGE_1           BLOB(1048576),
    CATEGORY_ID_1     CHAR(4)     not null,
    FILENAME_1        CHAR(75)    not null,
    DESCRIPTION_1     CHAR(100),
    COMMENTS_1        CHAR(100),
    REPRESENTATIVE_SN SMALLINT    not null,
    APPLICATION_ID    DECIMAL(18) not null,
    ID_NO             CHAR(20),
    ISSUE_AUTHORITY   VARCHAR(30),
    ISSUE_DATE        DATE,
    CUST_ID_TYPE      INTEGER,
    ID_COUNTRY        CHAR(10),
    CUST_TYPE         CHAR(1),
    TITLE             CHAR(6),
    FIRST_NAME        CHAR(20),
    SURNAME           CHAR(70),
    SEX               CHAR(1),
    DATE_OF_BIRTH     DATE,
    MOBILE_TEL        VARCHAR(15),
    E_MAIL            CHAR(64),
    ADDRESS_1         VARCHAR(40),
    ADDRESS_2         VARCHAR(40),
    CITY              CHAR(30),
    ZIP_CODE          CHAR(10),
    TELEPHONE_1       CHAR(15),
    NON_REGISTERED    CHAR(1),
    CUST_ID           INTEGER     not null,
    C_DIGIT           SMALLINT,
    constraint INSTANT_REPRESENT_PK
        primary key (APPLICATION_ID, REPRESENTATIVE_SN)
);

