create table LNS_PAYROLL_CHG
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK_LOAN_ACCOUNTACC INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    PAYROLL_AGR_CODE   INTEGER,
    TMPSTAMP           TIMESTAMP(6),
    NEW_INSTALL        DECIMAL(9, 2),
    PAYROLL_NUMBER     CHAR(15),
    PROCESS_IND        SMALLINT,
    ACC_CD             SMALLINT,
    ACC_TYPE           SMALLINT,
    ACC_UNIT           INTEGER,
    ACC_SN             INTEGER,
    LOAN_IND           INTEGER,
    LOAN_BALANCE       DECIMAL(9, 2),
    OLD_INSTALL        DECIMAL(9, 2),
    PAYROLL_DIAS_CODE  DECIMAL(15),
    STARTING_DATE      DATE,
    CHANGE_DATE        DATE,
    PROCESS_DATE       DATE,
    NAME0              CHAR(30)
);

create unique index IXU_LNS_001
    on LNS_PAYROLL_CHG (FK_LOAN_ACCOUNTFK, FK_LOAN_ACCOUNTACC, FK0LOAN_ACCOUNTACC, PAYROLL_AGR_CODE, TMPSTAMP,
                        NEW_INSTALL, PAYROLL_NUMBER);

