create table LNS_NEW_PAYROLL
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK_LOAN_ACCOUNTACC INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    TMPSTAMP           TIMESTAMP(6),
    INSTALL_AMN        DECIMAL(13, 2),
    H_PAYROLL_AGR_CODE INTEGER,
    PAYROLL_NUMBER     CHAR(15),
    RECORD_TYPE        SMALLINT,
    PROCESS_IND        SMALLINT,
    RECORD_IND         SMALLINT,
    H_BANK             SMALLINT,
    H_YPOYRGEIO        SMALLINT,
    ACC_CD             SMALLINT,
    ACC_TYPE           SMALLINT,
    INSTALL_COUNT      SMALLINT,
    ACC_UNIT           INTEGER,
    H_UNIT             INTEGER,
    ACC_SN             INTEGER,
    TOTAL_LOANS        INTEGER,
    DATE_FILLER        INTEGER,
    LOAN_IND           INTEGER,
    TOTAL_INSTALL      DECIMAL(13, 2),
    TOTAL_DEDUCTED     DECIMAL(13, 2),
    DRAWDOWN_AMN       DECIMAL(13, 2),
    TOTAL_DRAWDOWN     DECIMAL(13, 2),
    PAYROLL_DIAS_CODE  DECIMAL(15),
    H_PRODUCTION_DATE  DATE,
    PROCESS_DATE       DATE,
    DRAWDOWN_DT        DATE,
    H_SYSTEM_DATE      DATE,
    H_CREDIT_DATE      DATE,
    FILLER1            CHAR(9),
    NAME0              CHAR(30),
    FILLER3            CHAR(50),
    H_FILLER           CHAR(64)
);

create unique index IXU_LNS_003
    on LNS_NEW_PAYROLL (FK_LOAN_ACCOUNTFK, FK_LOAN_ACCOUNTACC, FK0LOAN_ACCOUNTACC, TMPSTAMP, INSTALL_AMN,
                        H_PAYROLL_AGR_CODE, PAYROLL_NUMBER, RECORD_TYPE);

