create table LNS_WRITE_DOWN_REC
(
    TRX_DATE          DATE     not null,
    ACCOUNT_NUMBER    CHAR(40) not null,
    ACTUAL_PAYMENT_DT DATE,
    NEXT_WRITE_OFF_DT DATE,
    WRITE_OFF_AMOUNT  DECIMAL(15, 2),
    ALLOCATED_AMOUNT  DECIMAL(15, 2),
    REMAINING_AMOUNT  DECIMAL(15, 2),
    CALCULATED_AMOUNT DECIMAL(15, 2),
    PAYMENT_STATUS    CHAR(1),
    NORMAL_BALANCE    DECIMAL(15, 2),
    OVERDUE_BALANCE   DECIMAL(15, 2),
    TMSTAMP           TIMESTAMP(6),
    constraint I0011147
        primary key (TRX_DATE, ACCOUNT_NUMBER)
);

