create table LOAN_GLACC
(
    PKLOAN_GLACC       INTEGER not null
        constraint I0000142
            primary key,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK0GENERIC_DETAFK  CHAR(5),
    FK0GENERIC_DETASER INTEGER,
    FK1GENERIC_DETAFK  CHAR(5),
    FK1GENERIC_DETASER INTEGER,
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK0GLG_ACCOUNTACCO CHAR(21),
    FK1GLG_ACCOUNTACCO CHAR(21),
    FK2GLG_ACCOUNTACCO CHAR(21),
    FK3GLG_ACCOUNTACCO CHAR(21),
    FK4GLG_ACCOUNTACCO CHAR(21),
    FK5GLG_ACCOUNTACCO CHAR(21),
    FK6GLG_ACCOUNTACCO CHAR(21),
    STATUS0            CHAR(1)
);

