create table LOANS_REPORT_CONFIG
(
    REPORT              CHAR(50),
    EXCEL_SHEET         CHAR(20),
    EXCEL_CELL          CHAR(10),
    EXCEL_ROW           CHAR(10),
    LNS_SN              INTEGER,
    PRODUCT_CODE        INTEGER,
    PRODUCT_FROM        INTEGER,
    PRODUCT_TO          INTEGER,
    LIMIT_AMOUNT        DECIMAL(15, 2),
    LIMIT_FROM          DECIMAL(15, 2),
    LIMIT_TO            DECIMAL(15, 2),
    FINSC_CODE          INTEGER,
    FINSC_FROM          INTEGER,
    FINSC_TO            INTEGER,
    CCODE_CODE          INTEGER,
    CCODE_FROM          INTEGER,
    CCODE_TO            INTEGER,
    LPURP_CODE          INTEGER,
    LPURP_FROM          INTEGER,
    LPURP_TO            INTEGER,
    LPUCB_CODE          INTEGER,
    LPUCB_FROM          INTEGER,
    LPUCB_TO            INTEGER,
    LOAN_STS            CHAR(20),
    LOAN_STS_FROM       CHAR(20),
    LOAN_STS_TO         CHAR(20),
    CLASSIFIC           CHAR(20),
    CLASSIFIC_FROM      CHAR(20),
    CLASSIFIC_TO        CHAR(20),
    AMT_TYPE            CHAR(20),
    CURRENCY            CHAR(20),
    FACTOR1             INTEGER,
    DATE_SP             CHAR(50),
    DATE_FROM           CHAR(50),
    DATE_TO             CHAR(50),
    RATE                DECIMAL(12, 6),
    RATE_FROM           DECIMAL(12, 6),
    RATE_TO             DECIMAL(12, 6),
    MONTH_DURATION_FROM DECIMAL(10, 2),
    MONTH_DURATION_TO   DECIMAL(10, 2),
    OV_DAYS_FROM        INTEGER,
    OV_DAYS_TO          INTEGER,
    SUB_CLASS_FROM      INTEGER,
    SUB_CLASS_TO        INTEGER,
    CUST_CATEG_FROM     INTEGER,
    CUST_CATEG_TO       INTEGER,
    MEDIATOR_CODE       INTEGER,
    MEDIATOR_FROM       INTEGER,
    MEDIATOR_TO         INTEGER
);

