create table LOAN_ACC_DTS_PREV
(
    FK_UNITCODE       INTEGER,
    ACC_TYPE          SMALLINT,
    ACC_SN            INTEGER,
    MORATORIUM_INT_DT DATE,
    INSTALL_FIRST_DT  DATE,
    SUBS2_EXP_DT      DATE,
    INSTALL_NEXT_DT   DATE,
    CUR_FX_INT_ST_DT  DATE,
    CUR_FX_INT_EXP_DT DATE,
    SUBSIDY_START_DT  DATE,
    SUBSIDY_EXP_DT    DATE,
    SPREAD_ST_DT      DATE,
    SPREAD_END_DT     DATE,
    SUBS2_START_DT    DATE,
    ACC_EXP_DT        DATE,
    DRAWDOWN_EXP_DT   DATE,
    ACC_OPEN_DT       DATE,
    INSTALL_PREV_DT   DATE
);

create unique index IXU_LOA_019
    on LOAN_ACC_DTS_PREV (FK_UNITCODE, ACC_TYPE, ACC_SN);

