create table LOAN_ACC_INT_PERM
(
    INTEREST_ID   INTEGER,
    DURATION_FROM INTEGER,
    DURATION_TO   INTEGER,
    AMOUNT_TO     DECIMAL(15, 2),
    AMOUNT_FROM   DECIMAL(15, 2),
    ENTRY_STATUS  CHAR(1)
);

create unique index IXP_LOA_007
    on LOAN_ACC_INT_PERM (INTEREST_ID);

