create table LOAN_MOVE_PRODUCT
(
    NEW_ACC_SN         INTEGER,
    NEW_ACC_TYPE       SMALLINT,
    NEW_ACC_UNIT       INTEGER,
    NEW_ACC_CD         SMALLINT,
    OLD_ACC_CD         SMALLINT,
    OLD_ACC_TYPE       SMALLINT,
    OLD_INSTALL_SN     SMALLINT,
    OLD_INST_FRQ       SMALLINT,
    OLD_INST_COUNT     SMALLINT,
    TRX_MOVCOL_SN      INTEGER,
    OLD_ACC_UNIT       INTEGER,
    TRX_OPEN_SN        INTEGER,
    TRX_INT_CRE_SN     INTEGER,
    TRX_CLOSE_SN       INTEGER,
    OLD_INTEREST_ID    INTEGER,
    OLD_PRODUCT        INTEGER,
    OLD_ACC_SN         INTEGER,
    TRX_CAPITAL_AMN    DECIMAL(15, 2),
    TRX_NRM_INT_AMN    DECIMAL(15, 2),
    TRX_PNL_INT_AMN    DECIMAL(15, 2),
    OLD_OPEN_DT        DATE,
    OLD_INT_SCALE_DT   DATE,
    OLD_EXPIRY_DT      DATE,
    OLD_DRAWDOWN_DT    DATE,
    OLD_INT_EXP_DT     DATE,
    TRX_DATE           DATE,
    TMSTMP             TIMESTAMP(6),
    TRX_OPEN_TMSTMP    TIMESTAMP(6),
    TRX_INT_CRE_TMSTMP TIMESTAMP(6),
    TRX_CLOSE_TMSTMP   TIMESTAMP(6),
    TRX_MOVCOL_TMSTMP  TIMESTAMP(6),
    REVERSED_FLAG      CHAR(1),
    TRX_USR            CHAR(8)
);

create unique index IXU_LOA_052
    on LOAN_MOVE_PRODUCT (NEW_ACC_SN, NEW_ACC_TYPE, NEW_ACC_UNIT);

