create table LOANS_BGM_SCHEDULE
(
    EXT_SYSTEM_ID          INTEGER     not null,
    EXT_APPLICATION_GRP_ID VARCHAR(40) not null,
    EXT_APPLICATION_ID     VARCHAR(40) not null,
    BGM_APPLICATION_ID     CHAR(15)    not null,
    BGM_CUSTOMER           CHAR(20)    not null,
    BGM_PROGRAM            VARCHAR(20) not null,
    BGM_TYPE               INTEGER     not null,
    BGM_PROGRAM_STEP       INTEGER     not null,
    BGM_PROGRAM_STEP_SN    INTEGER     not null,
    BGM_OFFICER            CHAR(8),
    BGM_TRX_DATE           TIMESTAMP(6),
    BGM_PROGRAM_STEP_REF   INTEGER,
    DATE_01                TIMESTAMP(6),
    DATE_02                TIMESTAMP(6),
    DATE_03                TIMESTAMP(6),
    DATE_04                TIMESTAMP(6),
    DATE_05                TIMESTAMP(6),
    DATE_06                TIMESTAMP(6),
    DATE_07                TIMESTAMP(6),
    DATE_08                TIMESTAMP(6),
    DATE_09                TIMESTAMP(6),
    DATE_10                TIMESTAMP(6),
    NUMBER_01              DECIMAL(10),
    NUMBER_02              DECIMAL(10),
    NUMBER_03              DECIMAL(10),
    NUMBER_04              DECIMAL(10),
    NUMBER_05              DECIMAL(10),
    NUMBER_06              DECIMAL(10),
    NUMBER_07              DECIMAL(10),
    NUMBER_08              DECIMAL(10),
    NUMBER_09              DECIMAL(10),
    NUMBER_10              DECIMAL(10),
    NUMBER_11              DECIMAL(10),
    NUMBER_12              DECIMAL(10),
    NUMBER_13              DECIMAL(10),
    NUMBER_14              DECIMAL(10),
    NUMBER_15              DECIMAL(10),
    NUMBER_16              DECIMAL(10),
    NUMBER_17              DECIMAL(10),
    NUMBER_18              DECIMAL(10),
    NUMBER_19              DECIMAL(10),
    NUMBER_20              DECIMAL(10),
    AMOUNT_01              DECIMAL(15, 2),
    AMOUNT_02              DECIMAL(15, 2),
    AMOUNT_03              DECIMAL(15, 2),
    AMOUNT_04              DECIMAL(15, 2),
    AMOUNT_05              DECIMAL(15, 2),
    AMOUNT_06              DECIMAL(15, 2),
    AMOUNT_07              DECIMAL(15, 2),
    AMOUNT_08              DECIMAL(15, 2),
    AMOUNT_09              DECIMAL(15, 2),
    AMOUNT_10              DECIMAL(15, 2),
    RATE_01                DECIMAL(8, 4),
    RATE_02                DECIMAL(8, 4),
    RATE_03                DECIMAL(8, 4),
    RATE_04                DECIMAL(8, 4),
    RATE_05                DECIMAL(8, 4),
    RATE_06                DECIMAL(8, 4),
    RATE_07                DECIMAL(8, 4),
    RATE_08                DECIMAL(8, 4),
    RATE_09                DECIMAL(8, 4),
    RATE_10                DECIMAL(8, 4),
    FLAG_01                CHAR(1),
    FLAG_02                CHAR(1),
    FLAG_03                CHAR(1),
    FLAG_04                CHAR(1),
    FLAG_05                CHAR(1),
    FLAG_06                CHAR(1),
    FLAG_07                CHAR(1),
    FLAG_08                CHAR(1),
    FLAG_09                CHAR(1),
    FLAG_10                CHAR(1),
    CHAR_01                VARCHAR(100),
    CHAR_02                VARCHAR(100),
    CHAR_03                VARCHAR(100),
    CHAR_04                VARCHAR(100),
    CHAR_05                VARCHAR(100),
    CHAR_06                VARCHAR(100),
    CHAR_07                VARCHAR(100),
    CHAR_08                VARCHAR(100),
    CHAR_09                VARCHAR(100),
    CHAR_10                VARCHAR(100),
    INSERT_TMSTAMP         TIMESTAMP(6),
    ENTRY_STATUS           CHAR(1),
    PROCESS_TMPSTAMP       TIMESTAMP(6),
    PROCESS_STATUS         CHAR(1),
    ENRICHED_FLAG          CHAR(1),
    BATCH_ERROR            VARCHAR(100),
    RESULT_SENT            CHAR(1),
    RESULT_TMSTAMP         TIMESTAMP(6),
    INSTANCE_NO            CHAR(8),
    constraint BGMSCHEDULE
        primary key (EXT_SYSTEM_ID, EXT_APPLICATION_GRP_ID, EXT_APPLICATION_ID, BGM_APPLICATION_ID, BGM_PROGRAM,
                     BGM_TYPE, BGM_CUSTOMER, BGM_PROGRAM_STEP, BGM_PROGRAM_STEP_SN)
);

create unique index IXN_BGM_74021_01
    on LOANS_BGM_SCHEDULE (EXT_SYSTEM_ID, BGM_TYPE, BGM_PROGRAM_STEP, BGM_PROGRAM_STEP_SN);

create unique index IXN_BGM_74021_02
    on LOANS_BGM_SCHEDULE (BGM_APPLICATION_ID, ENTRY_STATUS, PROCESS_STATUS);

create unique index IXN_BGM_74021_03
    on LOANS_BGM_SCHEDULE (BGM_PROGRAM, ENRICHED_FLAG);

