create table LOAN_BLOCK_UNCLEAR
(
    ACC_UNIT          INTEGER,
    ACC_TYPE          SMALLINT,
    ACC_SN            INTEGER,
    TMSTAMP           TIMESTAMP(6),
    ENTRY_TYPE        CHAR(1),
    ENTRY_SN          INTEGER,
    BGRP_SERIAL_NUM   SMALLINT,
    INSERT_UNIT       INTEGER,
    INSERT_JUSTIFIC   INTEGER,
    INSERT_USR_SN     INTEGER,
    PRIORITY_SN       INTEGER,
    BREG_SERIAL_NUM   DECIMAL(10),
    BILL_SERIAL_NUM   DECIMAL(10),
    INSERTION_AMN     DECIMAL(15, 2),
    UTILIZED_AMN      DECIMAL(15, 2),
    INSERT_DATE       DATE,
    PROCESS_DT        DATE,
    VALEUR_DT         DATE,
    ENTRY_STATUS      CHAR(1),
    AUTO_UNCLEAR_FLG  CHAR(1),
    AVALIABLE_LIM_FLG CHAR(1),
    PART_FULL_FLG     CHAR(1),
    INSERT_USR        CHAR(8),
    ENTRY_COMMENTS    CHAR(40)
);

create unique index IXU_LOA_016
    on LOAN_BLOCK_UNCLEAR (ACC_UNIT, ACC_TYPE, ACC_SN, TMSTAMP, ENTRY_TYPE, ENTRY_SN);

