create table LOAN_ACC_EXTR_HD
(
    FK_UNITCODE       INTEGER  not null,
    ACC_TYPE          SMALLINT not null,
    ACC_SN            INTEGER  not null,
    CURR_TRX_DATE     DATE     not null,
    TOT_AMN_DB        DECIMAL(15, 2),
    TOT_AMN_CR        DECIMAL(15, 2),
    TOT_AMN_REMAIN    DECIMAL(15, 2),
    REMAIN_AMN        DECIMAL(15, 2),
    DATE_TO           DATE,
    DATE_FROM         DATE,
    UNIT_NAME         VARCHAR(40),
    UNIT_CODE         INTEGER,
    PROD_DESCR        VARCHAR(40),
    ID_PRODUCT        INTEGER,
    OV_ACCOUNT_BAL    DECIMAL(15, 2),
    NRM_ACCOUNT_BAL   DECIMAL(15, 2),
    EXP_COM_CR        DECIMAL(15, 2),
    RL_PNL_INT_CR     DECIMAL(15, 2),
    RL_INT_CR         DECIMAL(15, 2),
    CAPITAL_CR        DECIMAL(15, 2),
    EXP_COM_DB        DECIMAL(15, 2),
    RL_PNL_INT_DB     DECIMAL(15, 2),
    RL_INT_DB         DECIMAL(15, 2),
    CAPITAL_DB        DECIMAL(15, 2),
    INSTALL_FIXED_AMN DECIMAL(15, 2),
    REMAIN_INST       SMALLINT,
    INSTALL_NEXT_DT   DATE,
    OV_EXP_COM_BAL    DECIMAL(15, 2),
    OV_RL_PNL_INT_BAL DECIMAL(15, 2),
    OV_RL_NRM_INT_BAL DECIMAL(15, 2),
    OV_CAP_BAL        DECIMAL(15, 2),
    CUR_FX_INT_ST_DT  DATE,
    INTER_RATE_SPRD   DECIMAL(8, 4),
    DEP_ACC_CD        SMALLINT,
    DEP_ACC_SN        INTEGER,
    DEP_ACC_TYPE      SMALLINT,
    DEP_ACC_UNIT      INTEGER,
    ACC_CD            SMALLINT,
    OV_ID_INTEREST    INTEGER,
    NRM_ID_INTEREST   INTEGER,
    N128_INT_PERC     DECIMAL(9, 6),
    BANK_SPREAD       DECIMAL(12, 6),
    OV_INT_PERC       DECIMAL(9, 6),
    NRM_INT_PERC      DECIMAL(9, 6),
    C_DIGIT           SMALLINT,
    CUST_ID           INTEGER,
    FATHER_NAME       VARCHAR(20),
    SURNAME           CHAR(70),
    FIRST_NAME        CHAR(20),
    CITY              CHAR(30),
    ZIP_CODE          CHAR(10),
    ADDRESS_2         VARCHAR(40),
    ADDRESS_1         VARCHAR(40),
    BASE_RATE_PERC    DECIMAL(9, 6),
    CURRENCY_DESC     CHAR(5),
    constraint IXU_LOA_105
        primary key (ACC_SN, ACC_TYPE, CURR_TRX_DATE, FK_UNITCODE)
);

