create table LOAN_INFO
(
    EXECUTION_SN       INTEGER  not null,
    INTER_RATE_SPRD    DECIMAL(8, 4),
    NEXT_INT_CALC_DATE DATE,
    PREV_INT_CALC_DATE DATE,
    ID_PRODUCT         INTEGER,
    ID_INTEREST        INTEGER,
    DURATION_UNIT      CHAR(1),
    DURATION_FREQ      SMALLINT,
    EXECUTION_FLG      CHAR(1),
    COMMENTS0          VARCHAR(200),
    FK_LOAN_ACCOUNTFK  INTEGER  not null,
    FK0LOAN_ACCOUNTACC INTEGER  not null,
    FK_LOAN_ACCOUNTACC SMALLINT not null,
    constraint LOAN_INFO_PK
        primary key (FK_LOAN_ACCOUNTFK, FK_LOAN_ACCOUNTACC, FK0LOAN_ACCOUNTACC, EXECUTION_SN)
);

