create table LOAN_INT_SPREAD
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    FK_LOAN_ACCOUNTACC INTEGER,
    EFFECTIVE_DATE     DATE,
    UNIT               INTEGER,
    UPDATE_UNIT        INTEGER,
    DB_INTER_RATE_SPR  DECIMAL(8, 4),
    CR_INTER_RATE_SPR  DECIMAL(8, 4),
    CRINT_SPREAD       DECIMAL(8, 4),
    UPDATE_TMSTMP      TIMESTAMP(6),
    CREATE_TMSTMP      TIMESTAMP(6),
    USR                CHAR(8),
    UPDATE_USER        CHAR(8)
);

create unique index IXU_LOA_048
    on LOAN_INT_SPREAD (FK_LOAN_ACCOUNTFK, FK0LOAN_ACCOUNTACC, FK_LOAN_ACCOUNTACC, EFFECTIVE_DATE);

