create table LOAN_EXP_CAP_INF
(
    ACC_UNIT       INTEGER,
    ACC_TYPE       SMALLINT,
    ACC_SN         INTEGER,
    LOAN_STATUS    CHAR(1),
    CAPITAL_EXP_DT DATE,
    CAPITAL_AMN    DECIMAL(15, 2),
    BALANCE_AMN    DECIMAL(15, 2),
    INTEREST_ID    INTEGER,
    INTEREST_RATE  DECIMAL(8, 4)
);

create unique index IXU_LOA_066
    on LOAN_EXP_CAP_INF (ACC_UNIT, ACC_TYPE, CAPITAL_EXP_DT, LOAN_STATUS, ACC_SN);

