create table LOAN_SCENARIO_DATA
(
    TMSTAMP                TIMESTAMP(6) not null,
    INSTALL_SN             DECIMAL(10)  not null,
    INSTALL_DT             DATE,
    PRODUCT_ID             INTEGER,
    CUST_ID                INTEGER,
    C_DIGIT                SMALLINT,
    ID_CURRENCY            INTEGER,
    CURR_SHORT_DESC        CHAR(5),
    FIXED_INT_ID           INTEGER,
    FIXED_INT_EXP_DT       DATE,
    FIXED_INT_ST_DT        DATE,
    FIX_IND_DURATION       SMALLINT,
    FIX_DURATION_UNIT      CHAR(1),
    FIXED_INT_PRC          DECIMAL(8, 4),
    FLOATING_INT_ID        INTEGER,
    FLOATING_INT_PRC       DECIMAL(8, 4),
    N128_INT_ID            INTEGER,
    N128_INT_PRC           DECIMAL(8, 4),
    SPREAD_INT_PRC         DECIMAL(8, 4),
    SUBSIDY_ID             INTEGER,
    SUBSIDY_PRC            DECIMAL(8, 4),
    ACC_OPET_DT            DATE,
    DRAWDOWN_AMN           DECIMAL(15, 2),
    MORATOR_END_DT         DATE,
    LOAN_INST_TOT_INT      DECIMAL(15),
    LOAN_INSTALL_FREQ      SMALLINT,
    LOAN_INSTALL_CNT       SMALLINT,
    INSTALL_FIRST_DT       DATE,
    INST_FIRST_DRW_DT      DATE,
    ACC_EXP_DT             DATE,
    MORATOR_INT_FRQ        SMALLINT,
    GRACE_PD_INST_CNT      DECIMAL(15),
    MAINTAIN_EQ_INST       CHAR(1),
    NON_INT_CAPIT_FLG      CHAR(1),
    INT_CAPITAL_FLG        CHAR(1),
    INT_PAYABLE_FLG        CHAR(1),
    MORAT_INT_PAY_FLG      CHAR(1),
    INSTALL_NORMAL         CHAR(1),
    INSTALL_OMIT           CHAR(1),
    INSTALL_DOUBLE         CHAR(1),
    INSTALL_13TH_PAY       CHAR(1),
    INSTALL_CHG_NUM        SMALLINT,
    INST_FLEX_STAB_OMIT    CHAR(1),
    INSTALL_FLEX_FIX       CHAR(1),
    INST_FLEX_FIX_AMN      DECIMAL(15, 2),
    INST_FLEX_VAR_OMIT     CHAR(1),
    AGR_ACCOUNT_NUM        CHAR(40),
    AGR_ACCOUNT_CD         SMALLINT,
    DEP_ACCOUNT_NUM        CHAR(40),
    DEP_ACCOUNT_CD         SMALLINT,
    CUST_CAT_SN            INTEGER,
    TRANSACT_SM            INTEGER,
    TRANSACT_IND           CHAR(1),
    FINSC_SN               INTEGER,
    ACTSC_SN               INTEGER,
    LPURP_SN               INTEGER,
    BSECT_SN               INTEGER,
    CBPUR_SN               INTEGER,
    STATEMENT_FREQ         CHAR(1),
    APPLICATION_ID         VARCHAR(30),
    APPLICATION_STS        CHAR(1),
    SALE_UNIT_SN           INTEGER,
    SALE_PERSON_SN         INTEGER,
    PENALTY_INT_ID         INTEGER,
    PENALTY_INT_PRC        DECIMAL(8, 4),
    MORAT_INT_AMORTIZED    CHAR(1),
    EXPENSES               DECIMAL(15, 2),
    ENOIKIAGORA_EXPENSES   DECIMAL(15, 2),
    WFE_APPLICATION_ID     CHAR(40),
    WFE_APPLICATION_SYSTEM SMALLINT,
    TRX_USER               CHAR(8),
    constraint PK_LNSSCENDATA
        primary key (TMSTAMP, INSTALL_SN)
);

