create table LOAN_LIQ_RATE_SENS
(
    ACC_TYPE         SMALLINT,
    REQUEST_SN       SMALLINT,
    ID_PRODUCT       INTEGER,
    ACC_CURRENCY     INTEGER,
    ACC_UNIT         INTEGER,
    ACC_SN           INTEGER,
    ACC_RATE         DECIMAL(8, 4),
    CAPITAL_FC_AMN   DECIMAL(15, 2),
    CAPITAL_LC_AMN   DECIMAL(15, 2),
    EXPIRE_DT        DATE,
    ACC_LIQ_MECH     CHAR(1),
    LOAN_STATUS      CHAR(1),
    REQUEST_LOAN_STS CHAR(1),
    REQUEST_TYPE     CHAR(1)
);

create unique index LNLIQPK
    on LOAN_LIQ_RATE_SENS (REQUEST_LOAN_STS, REQUEST_TYPE, REQUEST_SN, ACC_UNIT, ACC_SN, ACC_TYPE);

