create table LOAN_INTER_CHANGE
(
    TRX_UNIT               INTEGER not null,
    TRX_DATE               DATE    not null,
    TRX_USR                CHAR(8) not null,
    TRX_USR_SN             INTEGER not null,
    LNS_TYPE               SMALLINT,
    LNS_OPEN_UNIT          INTEGER,
    FLT_INT                INTEGER,
    OLD_FLT_INT            INTEGER,
    OLD_PRV_FX_INT         INTEGER,
    OLD_CUR_FX_INT         INTEGER,
    PRV_FX_INT             INTEGER,
    CUR_FX_INT             INTEGER,
    LNS_SN                 INTEGER,
    OV_ACR_NRM_INT_BAL     DECIMAL(15, 2),
    NRM_ACR_INT_BAL        DECIMAL(15, 2),
    INSTALL_FIXED_AMN      DECIMAL(15, 2),
    OV_ACR_PNL_INT_BAL     DECIMAL(15, 2),
    CUR_FX_INT_SCAL_DT     DATE,
    CUR_FX_INT_ST_DT       DATE,
    CUR_FX_INT_EXP_DT      DATE,
    VALEUR_DATE            DATE,
    OLD_PRV_FX_INT_ST_DT   DATE,
    OLD_PRV_FX_INT_SCAL_DT DATE,
    OLD_PRV_FX_INT_EXP_DT  DATE,
    OLD_CUR_FX_INT_ST_DT   DATE,
    PRV_FX_INT_EXP_DT      DATE,
    PRV_FX_INT_SCAL_DT     DATE,
    PRV_FX_INT_ST_DT       DATE,
    OLD_CUR_FX_INT_EXP_DT  DATE,
    OLD_CUR_FX_INT_SCAL_DT DATE,
    TMSTAMP                TIMESTAMP(6),
    INT_CALC_FLG           CHAR(1),
    I_TRX_COMMENTS         CHAR(40),
    PRV_ID_PRODUCT         INTEGER,
    OLD_INTER_RATE_SPRD    DECIMAL(8, 4),
    INTER_RATE_SPRD        DECIMAL(8, 4),
    OLD_SPREAD_ST_DT       DATE,
    SPREAD_ST_DT           DATE,
    PNL_INT                INTEGER,
    OLD_PNL_INT            INTEGER,
    OLD_CONTRIBUTION_INT   INTEGER,
    CONTRIBUTION_INT       INTEGER,
    CUR_FX_INT_IND         CHAR(1),
    PRV_FX_INT_IND         CHAR(1),
    OLD_CUR_FX_INT_IND     CHAR(1),
    constraint IXU_LOA_004
        primary key (TRX_UNIT, TRX_DATE, TRX_USR, TRX_USR_SN)
);

