create table LOAN_NRM_VAL_BAL
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    FK_LOAN_ACCOUNTACC INTEGER,
    VALUE_DATE         DATE,
    INIT_BALANCE_FLAG  CHAR(1),
    CURR_INTEREST_PRD  SMALLINT,
    INTEREST_CALC_PRD  SMALLINT,
    VALEUR_BALANCE     DECIMAL(15, 2),
    ACCPAYOFFTMPSTAMP  TIMESTAMP(6)
);

create unique index IXU_LOA_053
    on LOAN_NRM_VAL_BAL (FK_LOAN_ACCOUNTFK, FK0LOAN_ACCOUNTACC, FK_LOAN_ACCOUNTACC, VALUE_DATE, INIT_BALANCE_FLAG,
                         CURR_INTEREST_PRD);

