create table LOAN_SPC_AGRMNT
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    FK_LOAN_ACCOUNTACC INTEGER,
    FK_PRFT_TRANSACID  INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    LOAN_STATUS        CHAR(1),
    TMSTAMP            TIMESTAMP(6),
    VALUE_DATE_SPREAD  SMALLINT,
    AVAIL_DATE_SPREAD  SMALLINT,
    EXPENCE_DISCOUNT   DECIMAL(8, 4),
    COMMISS_DISCOUNT   DECIMAL(8, 4),
    LAST_UPD_DT        TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    USR                CHAR(8)
);

create unique index IXU_LOA_000
    on LOAN_SPC_AGRMNT (FK_LOAN_ACCOUNTFK, FK0LOAN_ACCOUNTACC, FK_LOAN_ACCOUNTACC, FK_PRFT_TRANSACID,
                        FK_JUSTIFICID_JUST, LOAN_STATUS, TMSTAMP);

