CREATE PROCEDURE PROFITS.LOANS_CRD_BOT_POPULATE_V2 ( )
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
BEGIN
DELETE FROM BOT_46_SECONDARYSUBJECT       ;
DELETE FROM BOT_25_SECONDARYSUBJECT       ;
DELETE FROM BOT_24_PRIMARYSUBJECT   ;
DELETE FROM BOT_22_SUBJECTRELATIONS       ;
DELETE FROM BOT_41_NONINSTCONNSUBJ ;
DELETE FROM BOT_40_NONINSTCOLLATERAL      ;
DELETE FROM BOT_21_NONINSTALMENT    ;
DELETE FROM BOT_39_INVBILLCONNSUBJ ;
DELETE FROM BOT_38_INVBILLCOLLATERAL      ;
DELETE FROM BOT_19_INVOICEBILL      ;
DELETE FROM BOT_36_INSTCONNSUBJECT ;
DELETE FROM BOT_35_INSTCOLLATERAL   ;
DELETE FROM BOT_17_INSTALMENT       ;
DELETE FROM BOT_70_FEESANDPENALTIES       ;
DELETE FROM BOT_91_DISPUTE    ;
DELETE FROM BOT_72_CONTRACTDATES    ;
DELETE FROM BOT_45_SPOUSEFULLNAME   ;
DELETE FROM BOT_34_PERSONSPOUSE     ;
DELETE FROM BOT_49_MONTHLYINCOME    ;
DELETE FROM BOT_69_EXPENDITURES     ;
DELETE FROM BOT_68_BIRTHDATA ;
DELETE FROM BOT_77_ZANZIBARID       ;
DELETE FROM BOT_76_WARDID     ;
DELETE FROM BOT_75_VOTERREGNUMBER   ;
DELETE FROM BOT_74_PERMITRESIDENCE ;
DELETE FROM BOT_68_PASSPORT   ;
DELETE FROM BOT_73_NATIONALID       ;
DELETE FROM BOT_71_DRIVINGLICENSE   ;
DELETE FROM BOT_67_POSTAL     ;
DELETE FROM BOT_66_PHYSICAL   ;
DELETE FROM BOT_65_PERMRESIDENCE    ;
DELETE FROM BOT_64_EMPLOYER   ;
DELETE FROM BOT_63_PERSONALDATA     ;
DELETE FROM BOT_62_IDENTIFICATIONS ;
DELETE FROM BOT_33_INDENTREPRENEUR ;
DELETE FROM BOT_61_INDCONTACTS      ;
DELETE FROM BOT_60_INDADDRESSES     ;
DELETE FROM BOT_16_REGISTRATION     ;
DELETE FROM BOT_15_POSTAL     ;
DELETE FROM BOT_28_BUSINESS   ;
DELETE FROM BOT_32_COMPANYRPERSON   ;
DELETE FROM BOT_30_CONNECTEDSUBJECT       ;
DELETE FROM BOT_2_SUBJECTCHOICE     ;
DELETE FROM BOT_44_RELATEDPERSON    ;
DELETE FROM BOT_14_CONTACTSCOMPANY ;
DELETE FROM BOT_13_COMPANYDATA      ;
DELETE FROM BOT_12_ADDRESSESCOMPANY       ;
DELETE FROM BOT_11_INDIVIDUAL       ;
DELETE FROM BOT_10_COMPANY    ;
DELETE FROM BOT_43_COLLATERAL       ;
DELETE FROM BOT_27_CCARDCONNSUBJECT       ;
DELETE FROM BOT_31_CCARDCOLLATERAL ;
DELETE FROM BOT_8_CREDITCARD ;
DELETE FROM BOT_4_STORINSTALMENT    ;
DELETE FROM BOT_90_STORHEADER       ;
DELETE FROM BOT_7_STSUBJECTRELATIONS      ;
DELETE FROM BOT_6_STORNONINSTALMENT       ;
DELETE FROM BOT_5_STORINVOICEBILL   ;
DELETE FROM BOT_3_STORCREDITCARD    ;
DELETE FROM BOT_1_COMMAND     ;
DELETE FROM LNS_CRD_LOAN_DATA ;
DELETE FROM LNS_CRD_CUST_SUB_DATA;
DELETE FROM LNS_CRD_COLL_SUB_DATA;
DELETE FROM LNS_CRD_CUST_DATA;
DELETE FROM LNS_CRD_CUST_ADDRESS;
DELETE FROM LNS_CRD_CUST_RELAT;
INSERT INTO LNS_CRD_LOAN_DATA
    (REPORTING_DATE ,
        LOAN_CODE  ,
        LOAN_PURPOSE  ,
        LOAN_CURRENCY  ,
        LOAN_PHASE  ,
        LOAN_NEGATIVE_STATUS ,
        RECHEDULER_LOAN ,
        PAST_DUE_DAYS ,
        PAST_DUE_AMOUNT ,
        ECONOMIC_SECTOR ,
        LOAN_END_DATE ,
        LAST_PAYMENT_DATE ,
        REAL_LOAN_END_DATE ,
        LOAN_START_DATE ,
        ADDITIONAL_FEE_SUM ,
        ADDITIONAL_FEE_PAID ,
        LOAN_TYPE ,
        LOAN_AMOUNT ,
        INSTALLMENT_TYPE ,
        PAYMENTS_PERIODICITY ,
        PAYMENT_METHOD ,
        TOTAL_INSTALLMENTS  ,
        INSTALLMENT_AMOUNT ,
        OVERDUE_INSTAL_COUNT  ,
        OVERDUE_AMOUNT ,
        OVERDUE_REMAIN_INSTAL ,
        REMAINING_CAPITAL_AMN)
SELECT  (SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
             P.ACCOUNT_NUMBER AS LOAN_CODE,
             (SELECT D.DESCRIPTION FROM GENERIC_DETAIL D WHERE D.SERIAL_NUM=L.FKGD_HAS_AS_LOAN_P AND D.FK_GENERIC_HEADPAR=L.FKGH_HAS_AS_LOAN_P) AS LOAN_PURPOSE,
              (SELECT H.SHORT_DESCR FROM CURRENCY H WHERE L.FKCUR_IS_MOVED_IN=H.ID_CURRENCY) AS LOAN_CURRENCY,
              '1' AS   LOAN_PHASE ,
              DECODE( L.LOAN_STATUS, 1, 'NoNegativeStatus',
                    2, 'LoanWrittenOff',
                    3, 'LoanWrittenOff',
                    4, 'LoanWrittenOff')  AS LOAN_NEGATIVE_STATUS,
              CASE WHEN F.FKGD_HAS_ADJUST<>0 THEN 'TRUE' ELSE 'FALSE' END AS RECHEDULER_LOAN,
             CASE WHEN L.LOAN_STATUS>1 THEN ((SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B)-L.OV_EXP_DT) ELSE 0 END AS PAST_DUE_DAYS ,
              (L.OV_CAP_BAL+ L.OV_COM_BAL+ L.OV_EXP_BAL+ L.OV_RL_NRM_INT_BAL+ L.OV_RL_PNL_INT_BAL+ L.OV_URL_NRM_INT_BAL+ L.OV_URL_PNL_INT_BAL)*-1 AS PAST_DUE_AMOUNT,
               (SELECT D.DESCRIPTION FROM GENERIC_DETAIL D WHERE D.SERIAL_NUM=L.FKGD_HAS_AS_FINANC AND D.FK_GENERIC_HEADPAR=L.FKGH_HAS_AS_FINANC ) AS  ECONOMIC_SECTOR,
              L.ACC_EXP_DT AS  LOAN_END_DATE,
              TO_DATE('01-01-0001','DD-MM-YYYY') AS  LAST_PAYMENT_DATE,
              L.ACC_EXP_DT AS  REAL_LOAN_END_DATE,
              L.ACC_OPEN_DT AS LOAN_START_DATE,
              0 AS  ADDITIONAL_FEE_SUM,
              0 AS  ADDITIONAL_FEE_PAID,
               (SELECT T.DESCRIPTION FROM LOAN W ,GENERIC_DETAIL T
                       WHERE W.FK_PRODUCTID_PRODU=L.FK_LOANFK_PRODUCTI
                           AND W.FKGD_HAS_ACCOUNT_T=T.SERIAL_NUM AND
                             W.FKGH_HAS_ACCOUNT_T=T.FK_GENERIC_HEADPAR) AS LOAN_TYPE,
               L.DRAWDOWN_FST_AMN AS LOAN_AMOUNT,
                CASE WHEN L.ACC_MECHANISM IN (4,5) THEN 'Fixed' ELSE 'Variable' END AS INSTALLMENT_TYPE,
                CASE WHEN L.INSTALL_FREQ=1 THEN 'MonthlyInstalments30Days'
                         WHEN L.INSTALL_FREQ=2 THEN 'BimonthlyInstalments60Days'
                         WHEN L.INSTALL_FREQ=3 THEN 'QuarterlyInstalments90Days'
                         WHEN L.INSTALL_FREQ=4 THEN 'FourMonthInstalments120Days'
                         WHEN L.INSTALL_FREQ=5 THEN 'FiveMonthInstalments150Days'
                         WHEN L.INSTALL_FREQ=6 THEN 'SixMonthInstalments180Days'
                         WHEN L.INSTALL_FREQ=12 THEN 'AnnualInstalments360Days'
                         ELSE
                         CASE WHEN L.INSTALL_COUNT=1 THEN 'AtTheFinalDayOfThePeriodOfContract'
                         ELSE 'IrregularInstalments'
                         END
                END AS PAYMENTS_PERIODICITY,
                '' AS PAYMENT_METHOD,
                L.INSTALL_COUNT AS TOTAL_INSTALLMENTS,
                (F.INSTALL_FIXED_AMN*-1) AS INSTALLMENT_AMOUNT,
                (L.OV_CHRG_CNT+ L.OV_INST_CNT+ L.OV_INT_CNT+ L.OV_LOAN_CNT) AS OVERDUE_INSTAL_COUNT,
                (L.OV_CAP_BAL+ L.OV_COM_BAL+ L.OV_EXP_BAL+ L.OV_RL_NRM_INT_BAL+ L.OV_RL_PNL_INT_BAL+
                        L.OV_URL_NRM_INT_BAL+ L.OV_URL_PNL_INT_BAL+F.OV_ACCRUAL_AMN )*-1 AS OVERDUE_AMOUNT,
                L.INSTALL_COUNT-L.REQ_INSTALL_SN  AS REMAINING_INSTALLMENTS,
                L.MP_START_CAP_AMN  AS REMAINING_CAPITAL_AMN
                FROM PROFITS_ACCOUNT P ,LOAN_ACCOUNT L ,LOAN_ACCOUNT_INFO F
                WHERE P.LNS_OPEN_UNIT=L.FK_UNITCODE
                AND P.LNS_SN=L.ACC_SN
                AND P.LNS_TYPE=L.ACC_TYPE
                AND L.ACC_STATUS <> 3                               /* KAposto 01/02/2023 */
                AND L.FK_UNITCODE=F.FK_LOAN_ACCOUNTFK
                AND L.ACC_SN=F.FK_LOAN_ACCOUNTACC
                AND L.ACC_TYPE=F.FK0LOAN_ACCOUNTACC
                AND L.ACC_TYPE<>14;
/* Second Insert for acc_status =3 and lst_nrm_trx_date < 6months*/
INSERT INTO LNS_CRD_LOAN_DATA
    (REPORTING_DATE ,
        LOAN_CODE  ,
        LOAN_PURPOSE  ,
        LOAN_CURRENCY  ,
        LOAN_PHASE  ,
        LOAN_NEGATIVE_STATUS ,
        RECHEDULER_LOAN ,
        PAST_DUE_DAYS ,
        PAST_DUE_AMOUNT ,
        ECONOMIC_SECTOR ,
        LOAN_END_DATE ,
        LAST_PAYMENT_DATE ,
        REAL_LOAN_END_DATE ,
        LOAN_START_DATE ,
        ADDITIONAL_FEE_SUM ,
        ADDITIONAL_FEE_PAID ,
        LOAN_TYPE ,
        LOAN_AMOUNT ,
        INSTALLMENT_TYPE ,
        PAYMENTS_PERIODICITY ,
        PAYMENT_METHOD ,
        TOTAL_INSTALLMENTS  ,
        INSTALLMENT_AMOUNT ,
        OVERDUE_INSTAL_COUNT  ,
        OVERDUE_AMOUNT ,
        OVERDUE_REMAIN_INSTAL ,
        REMAINING_CAPITAL_AMN)
SELECT  (SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
             P.ACCOUNT_NUMBER AS LOAN_CODE,
             (SELECT D.DESCRIPTION FROM GENERIC_DETAIL D WHERE D.SERIAL_NUM=L.FKGD_HAS_AS_LOAN_P AND D.FK_GENERIC_HEADPAR=L.FKGH_HAS_AS_LOAN_P) AS LOAN_PURPOSE,
              (SELECT H.SHORT_DESCR FROM CURRENCY H WHERE L.FKCUR_IS_MOVED_IN=H.ID_CURRENCY) AS LOAN_CURRENCY,
              '1' AS   LOAN_PHASE ,
              DECODE( L.LOAN_STATUS, 1, 'NoNegativeStatus',
                    2, 'LoanWrittenOff',
                    3, 'LoanWrittenOff',
                    4, 'LoanWrittenOff')  AS LOAN_NEGATIVE_STATUS,
              CASE WHEN F.FKGD_HAS_ADJUST<>0 THEN 'TRUE' ELSE 'FALSE' END AS RECHEDULER_LOAN,
             CASE WHEN L.LOAN_STATUS>1 THEN ((SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B)-L.OV_EXP_DT) ELSE 0 END AS PAST_DUE_DAYS ,
              (L.OV_CAP_BAL+ L.OV_COM_BAL+ L.OV_EXP_BAL+ L.OV_RL_NRM_INT_BAL+ L.OV_RL_PNL_INT_BAL+ L.OV_URL_NRM_INT_BAL+ L.OV_URL_PNL_INT_BAL)*-1 AS PAST_DUE_AMOUNT,
               (SELECT D.DESCRIPTION FROM GENERIC_DETAIL D WHERE D.SERIAL_NUM=L.FKGD_HAS_AS_FINANC AND D.FK_GENERIC_HEADPAR=L.FKGH_HAS_AS_FINANC ) AS  ECONOMIC_SECTOR,
              L.ACC_EXP_DT AS  LOAN_END_DATE,
              TO_DATE('01-01-0001','DD-MM-YYYY') AS  LAST_PAYMENT_DATE,
              L.ACC_EXP_DT AS  REAL_LOAN_END_DATE,
              L.ACC_OPEN_DT AS LOAN_START_DATE,
              0 AS  ADDITIONAL_FEE_SUM,
              0 AS  ADDITIONAL_FEE_PAID,
               (SELECT T.DESCRIPTION FROM LOAN W ,GENERIC_DETAIL T
                       WHERE W.FK_PRODUCTID_PRODU=L.FK_LOANFK_PRODUCTI
                           AND W.FKGD_HAS_ACCOUNT_T=T.SERIAL_NUM AND
                             W.FKGH_HAS_ACCOUNT_T=T.FK_GENERIC_HEADPAR) AS LOAN_TYPE,
               L.DRAWDOWN_FST_AMN AS LOAN_AMOUNT,
                CASE WHEN L.ACC_MECHANISM IN (4,5) THEN 'Fixed' ELSE 'Variable' END AS INSTALLMENT_TYPE,
                CASE WHEN L.INSTALL_FREQ=1 THEN 'MonthlyInstalments30Days'
                         WHEN L.INSTALL_FREQ=2 THEN 'BimonthlyInstalments60Days'
                         WHEN L.INSTALL_FREQ=3 THEN 'QuarterlyInstalments90Days'
                         WHEN L.INSTALL_FREQ=4 THEN 'FourMonthInstalments120Days'
                         WHEN L.INSTALL_FREQ=5 THEN 'FiveMonthInstalments150Days'
                         WHEN L.INSTALL_FREQ=6 THEN 'SixMonthInstalments180Days'
                         WHEN L.INSTALL_FREQ=12 THEN 'AnnualInstalments360Days'
                         ELSE
                         CASE WHEN L.INSTALL_COUNT=1 THEN 'AtTheFinalDayOfThePeriodOfContract'
                         ELSE 'IrregularInstalments'
                         END
                END AS PAYMENTS_PERIODICITY,
                '' AS PAYMENT_METHOD,
                L.INSTALL_COUNT AS TOTAL_INSTALLMENTS,
                (F.INSTALL_FIXED_AMN*-1) AS INSTALLMENT_AMOUNT,
                (L.OV_CHRG_CNT+ L.OV_INST_CNT+ L.OV_INT_CNT+ L.OV_LOAN_CNT) AS OVERDUE_INSTAL_COUNT,
                (L.OV_CAP_BAL+ L.OV_COM_BAL+ L.OV_EXP_BAL+ L.OV_RL_NRM_INT_BAL+ L.OV_RL_PNL_INT_BAL+
                        L.OV_URL_NRM_INT_BAL+ L.OV_URL_PNL_INT_BAL+F.OV_ACCRUAL_AMN )*-1 AS OVERDUE_AMOUNT,
                L.INSTALL_COUNT-L.REQ_INSTALL_SN  AS REMAINING_INSTALLMENTS,
                L.MP_START_CAP_AMN  AS REMAINING_CAPITAL_AMN
                FROM PROFITS_ACCOUNT P ,LOAN_ACCOUNT L ,LOAN_ACCOUNT_INFO F
                WHERE P.LNS_OPEN_UNIT=L.FK_UNITCODE
                AND P.LNS_SN=L.ACC_SN
                AND P.LNS_TYPE=L.ACC_TYPE
                AND L.ACC_STATUS = '3'
                AND (SELECT days(CURR_TRX_DATE) - days(L.LST_TRX_DT)	FROM BANK_PARAMETERS)<90
                AND L.FK_UNITCODE=F.FK_LOAN_ACCOUNTFK
                AND L.ACC_SN=F.FK_LOAN_ACCOUNTACC
                AND L.ACC_TYPE=F.FK0LOAN_ACCOUNTACC
                AND L.ACC_TYPE<>14;
----- LOAN_PHASE
UPDATE LNS_CRD_LOAN_DATA  L SET  L.LOAN_PHASE=2
WHERE EXISTS (SELECT * FROM PROFITS_ACCOUNT P ,LOAN_ACCOUNT L
WHERE  P.LNS_OPEN_UNIT=L.FK_UNITCODE
AND P.LNS_SN=L.ACC_SN
AND P.LNS_TYPE=L.ACC_TYPE
AND L.ACC_STATUS=3
AND P.ACCOUNT_NUMBER=L.LOAN_CODE
AND EXISTS (SELECT max(E.TMSTAMP) FROM LOAN_ACCOUNT_EXTRA E
                    WHERE E.ACC_UNIT =L.FK_UNITCODE
                    AND E.ACC_SN=L.ACC_SN
                    AND E.ACC_TYPE=L.ACC_TYPE
                    AND E.TRANSACTION_CODE=4291));
 
UPDATE LNS_CRD_LOAN_DATA  L SET  L.LOAN_PHASE=3
WHERE EXISTS (SELECT * FROM PROFITS_ACCOUNT P ,LOAN_ACCOUNT L
WHERE  P.LNS_OPEN_UNIT=L.FK_UNITCODE
AND P.LNS_SN=L.ACC_SN
AND P.LNS_TYPE=L.ACC_TYPE
AND L.ACC_STATUS=3
AND P.ACCOUNT_NUMBER=L.LOAN_CODE
AND EXISTS (SELECT max(E.TMSTAMP) FROM LOAN_ACCOUNT_EXTRA E
                    WHERE E.ACC_UNIT =L.FK_UNITCODE
                    AND E.ACC_SN=L.ACC_SN
                    AND E.ACC_TYPE=L.ACC_TYPE
                    AND E.TRANSACTION_CODE=4271));
 
UPDATE LNS_CRD_LOAN_DATA  L SET  L.LOAN_PHASE=4
WHERE EXISTS (SELECT * FROM PROFITS_ACCOUNT P ,LOAN_ACCOUNT L
WHERE  P.LNS_OPEN_UNIT=L.FK_UNITCODE
AND P.LNS_SN=L.ACC_SN
AND P.LNS_TYPE=L.ACC_TYPE
AND L.ACC_STATUS=3
and L.LOAN_STATUS=4
AND P.ACCOUNT_NUMBER=L.LOAN_CODE
AND EXISTS (SELECT max(E.TMSTAMP) FROM LOAN_ACCOUNT_EXTRA E
                    WHERE E.ACC_UNIT =L.FK_UNITCODE
                    AND E.ACC_SN=L.ACC_SN
                    AND E.ACC_TYPE=L.ACC_TYPE
                    AND E.TRANSACTION_CODE=4271));
 Insert into LNS_CRD_CUST_DATA
   (   CUST_ID, CUST_TYPE, IND_CLASS,
        FIRST_NAME, MIDDLE_NAME, SURNAME,
        MARITAL_STS, SPOUSE_FULLNAME, GENDER, BIRTH_SURNAME,
        NATIONALITY, CITIZENSHIP,
        PROFESSION, EMPLOYER, MONTHLY_INC_AMN, MONTHLY_INC_CUR, NUM_OF_CHILDREN, NUM_OF_SPOUSES, EDUCATION,
        MONTHLY_EXP_AMN, MONTHLY_EXP_CUR, DATE_OF_BIRTH, DISTRICT_OF_BIRTH, COUNTRY_OF_BIRTH, DRIVING_LICENCE_ID, DL_ISSUE_DT, DL_EXPIRE_DT,
        DL_ISSUE_LOCAT, DL_ISSUE_AUTH, NATIONAL_ID, NI_ISSUE_DT, NI_EXPIRE_DT, NI_ISSUE_LOCAT, NI_ISSUE_AUTH, PERMISSION_ID,
        PR_ISSUE_DT, PR_EXPIRE_DT, PR_ISSUE_LOC, PR_ISSUE_AUTH, VOTER_REG_ID, VR_ISSUE_DT, VR_EXPIRE_DT, VR_ISSUE_LOC,
        VR_ISSUE_AUTH, WARD_ID, WI_ISSUE_DT, WI_EXPIRE_DT, WI_ISSUE_LOC, WI_ISSUE_AUTH, ZANZIBAR_ID, ZI_ISSUE_DT,
        ZI_EXPIRE_DT, ZI_ISSUE_LOC, ZI_ISSUE_AUTH, BUSINESS_NAME, CELLULAR_PHONE, FIXED_LINE, FAX, EMAIL, WEBPAGE,
        LEGAL_FORM,  NO_OF_EMPLOYEES, REGISTRATION_COUNTRY, REGISTRATION_NUMBER, TAX_ID,REPORTING_DATE )
SELECT C.CUST_ID , C.CUST_TYPE ,
CASE WHEN (C.BUSINESS_IND='1' AND C.CUST_TYPE='1') THEN  'SoleProprietor'
     WHEN (C.CUST_TYPE='1' AND C.BUSINESS_IND<>'1') THEN 'Individual' ELSE '' END ,
        TRIM(C.FIRST_NAME) , TRIM(C.MIDDLE_NAME) , TRIM(C.SURNAME) ,
        '',  TRIM(C.FATHER_SURNAME) || ' '  || TRIM(C.FATHER_NAME),
            CASE WHEN C.SEX='F' THEN 'FEMALE' WHEN C.SEX='M' THEN 'MALE' ELSE '' END , TRIM(C.SURNAME) ,
        '', '',
        '', (CASE WHEN C.EMPLOYER='' THEN NULL ELSE C.EMPLOYER END) , 0, '', C.NUM_OF_CHILDREN , C.FAMILY_MEMBERS, '',
        0, '', C.DATE_OF_BIRTH , '', '', '', TO_DATE('01-01-0001','DD-MM-YYYY'),TO_DATE('01-01-0001','DD-MM-YYYY'),
        '', '', '', TO_DATE('01-01-0001','DD-MM-YYYY'), TO_DATE('01-01-0001','DD-MM-YYYY'), '', '', '',
        TO_DATE('01-01-0001','DD-MM-YYYY'),TO_DATE('01-01-0001','DD-MM-YYYY'), '', '', '', TO_DATE('01-01-0001','DD-MM-YYYY'),TO_DATE('01-01-0001','DD-MM-YYYY'), '',
        '', '', TO_DATE('01-01-0001','DD-MM-YYYY'), TO_DATE('01-01-0001','DD-MM-YYYY'), '', '', '', TO_DATE('01-01-0001','DD-MM-YYYY'),
        TO_DATE('01-01-0001','DD-MM-YYYY'), '', '',  CASE WHEN C.BUSINESS_IND='1' THEN C.SECOND_SURNAME ELSE '' END,  C.MOBILE_TEL , C.TELEPHONE_1, '', C.E_MAIL , C.INTERNET_ADDRESS ,
        '', C.NO_OF_EMPLOYEES,  '' , '', '' ,(SELECT SCHEDULED_DATE FROM BANK_PARAMETERS)
            FROM CUSTOMER C WHERE EXISTS (SELECT * FROM LOAN_ACCOUNT LA WHERE LA.CUST_ID=C.CUST_ID AND (LA.ACC_STATUS <> '3' OR (LA.ACC_STATUS= '3' AND (SELECT days(CURR_TRX_DATE) - days(LA.LST_TRX_DT)	FROM BANK_PARAMETERS)<90 )));  --  KAposto 01/02/2023
 
UPDATE  LNS_CRD_CUST_DATA LC SET LC.MARITAL_STS= TRIM(NVL((select TRIM(GD.DESCRIPTION)
from customer_category cc, generic_Detail gd where CC.FK_CATEGORYCATEGOR='FAMILY' and CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR and
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.cust_id=CC.FK_CUSTOMERCUST_ID ),'SINGLE')) WHERE LC.cust_type='1';
UPDATE  LNS_CRD_CUST_DATA LC SET LC.MARITAL_STS= 'OTHER' WHERE LC.cust_type='2';
UPDATE  LNS_CRD_CUST_data lc SET LC.nationality = (select TRIM(GD.LATIN_DESC)
from customer_category cc, generic_Detail gd where CC.FK_CATEGORYCATEGOR='NATIONAL' and CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR and
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.cust_id=CC.FK_CUSTOMERCUST_ID ) WHERE LC.cust_type='1';
UPDATE  LNS_CRD_CUST_data lc SET LC.citizenship = (select TRIM(GD.LATIN_DESC)
from customer_category cc, generic_Detail gd where CC.FK_CATEGORYCATEGOR='CITIZEN' and CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR and
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.cust_id=CC.FK_CUSTOMERCUST_ID ) WHERE LC.cust_type='1';
UPDATE  LNS_CRD_CUST_DATA LC SET LC.PROFESSION  = (SELECT TRIM(GD.LATIN_DESC )
FROM CUSTOMER_CATEGORY CC, GENERIC_DETAIL GD WHERE CC.FK_CATEGORYCATEGOR='PROFES' AND CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR AND
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.CUST_ID=CC.FK_CUSTOMERCUST_ID ) WHERE LC.CUST_TYPE='1';
UPDATE LNS_CRD_CUST_data lc SET (LC.monthly_inc_amn, LC.monthly_inc_cur, LC.monthly_exp_amn, LC.monthly_exp_cur ) =
(SELECT CI.IND_MAIN_INCOME/12, CR.SHORT_DESCR, CI.BK_COST_OF_SELLING/12 , CR.SHORT_DESCR FROM CUST_IMAGE CI, CURRENCY CR
WHERE CI.FK_CUSTOMERCUST_ID=LC.cust_id AND CI.FK_CURRENCYID_CURR=CR.ID_CURRENCY )
WHERE LC.cust_type='1';
UPDATE LNS_CRD_CUST_DATA LC SET LC.EDUCATION  = (select TRIM(GD.LATIN_DESC)
FROM CUSTOMER_CATEGORY CC, GENERIC_DETAIL GD WHERE CC.FK_CATEGORYCATEGOR='EDULEVEL' AND CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR AND
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.CUST_ID=CC.FK_CUSTOMERCUST_ID ) WHERE LC.CUST_TYPE='1';
UPDATE  LNS_CRD_CUST_data lc SET LC.country_of_birth  = (select TRIM(GD.SHORT_DESCRIPTION)
from customer_category cc, generic_Detail gd where CC.FK_CATEGORYCATEGOR='BCOUNTRY' and CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR and
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.cust_id=CC.FK_CUSTOMERCUST_ID ) WHERE LC.cust_type='1';
-- UPDATE PASS
--PASSPORT DATA
--UPDATE  LNS_CRD_CUST_data lc SET (LC.PASSPORT_id , LC.P_expire_dt, LC.P_issue_dt, LC.P_issue_locat, LC.P_issue_auth) =
--( SELECT  OI.ID_NO, OI.EXPIRY_DATE, OI.ISSUE_DATE,TRIM(GD.DESCRIPTION), OI.ISSUE_AUTHORITY
--FROM OTHER_ID OI, GENERIC_DETAIL GD WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id AND
--GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_BEEN_ISSU AND GD.SERIAL_NUM=OI.FKGD_HAS_BEEN_ISSU AND GD.LATIN_DESC='P' ) WHERE LC.cust_type='1' ;
UPDATE  LNS_CRD_CUST_data lc
    SET (LC.PASSPORT_id, LC.P_expire_dt, LC.P_issue_dt, lc.P_ISSUE_LOCAT, LC.P_issue_auth) =
      ( SELECT  OI.ID_NO, OI.EXPIRY_DATE, OI.ISSUE_DATE,
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=2
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=2 );
UPDATE  LNS_CRD_CUST_data lc
SET (LC.driving_licence_id, LC.dl_expire_dt, LC.dl_issue_dt, LC.DL_ISSUE_LOCAT, LC.dl_issue_auth) =
      ( SELECT  OI.ID_NO, OI.EXPIRY_DATE, OI.ISSUE_DATE,
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=15
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=15 );
UPDATE  LNS_CRD_CUST_data lc SET (LC.national_id, LC.ni_expire_dt, LC.ni_issue_dt, LC.ni_issue_locat, LC.ni_issue_auth)=
      ( SELECT  SUBSTR(TRIM(OI.ID_NO),1,20), OI.EXPIRY_DATE, OI.ISSUE_DATE,
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=1
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=1 );
UPDATE  LNS_CRD_CUST_data lc SET (LC.permission_id , LC.pr_expire_dt, LC.pr_issue_dt, LC.pr_issue_loc, LC.pr_issue_auth)=
      ( SELECT  OI.ID_NO, OI.EXPIRY_DATE, OI.ISSUE_DATE,
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.LATIN_DESC='PR'
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.LATIN_DESC='PR' );
UPDATE  LNS_CRD_CUST_data lc SET (LC.voter_reg_id , LC.vr_expire_dt, LC.vr_issue_dt, LC.vr_issue_loc, LC.vr_issue_auth )=
      ( SELECT  SUBSTR(TRIM(OI.ID_NO),1,16), OI.EXPIRY_DATE, OI.ISSUE_DATE,
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=999
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=999 );
UPDATE  LNS_CRD_CUST_data lc SET (LC.ward_id , LC.wi_expire_dt, LC.wi_issue_dt, LC.wi_issue_loc, LC.wi_issue_auth )=
      ( SELECT  CHAR(REPLACE(OI.ID_NO,'-',''),16),(case when OI.EXPIRY_DATE =TO_DATE('01-01-0001','DD-MM-YYYY') then NULL else OI.EXPIRY_DATE end),
      (case when OI.ISSUE_DATE =TO_DATE('01-01-0001','DD-MM-YYYY') then NULL else OI.ISSUE_DATE end),
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=16
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.SERIAL_NUM=16 );
UPDATE  LNS_CRD_CUST_data lc SET (LC.zanzibar_id, LC.zi_expire_dt, LC.zi_issue_dt, LC.zi_issue_loc, LC.zi_issue_auth )=
      ( SELECT  OI.ID_NO, OI.EXPIRY_DATE, OI.ISSUE_DATE,
                (SELECT TRIM(GD1.DESCRIPTION )
                   FROM GENERIC_DETAIL GD1
                  WHERE GD1.FK_GENERIC_HEADPAR= OI.FKGH_HAS_BEEN_ISSU
                    AND GD1.SERIAL_NUM = OI.FKGD_HAS_BEEN_ISSU
                    ) AS ISSUE_LOCAT,
                OI.ISSUE_AUTHORITY
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.LATIN_DESC='ZI'
         )
WHERE LC.cust_type='1'
  AND EXISTS (SELECT *
          FROM OTHER_ID OI, GENERIC_DETAIL GD
          WHERE OI.FK_CUSTOMERCUST_ID=LC.cust_id
            AND GD.FK_GENERIC_HEADPAR=OI.FKGH_HAS_TYPE
            AND GD.SERIAL_NUM=OI.FKGD_HAS_TYPE
            AND GD.LATIN_DESC='ZI' );
UPDATE  LNS_CRD_CUST_data lc SET LC.legal_form  = (select TRIM(GD.DESCRIPTION)
from customer_category cc, generic_Detail gd where CC.FK_CATEGORYCATEGOR='LAWSHAPE' and CC.FK_GENERIC_DETAFK=GD.FK_GENERIC_HEADPAR and
CC.FK_GENERIC_DETASER=GD.SERIAL_NUM AND LC.cust_id=CC.FK_CUSTOMERCUST_ID ) WHERE LC.cust_type='2';
UPDATE  LNS_CRD_CUST_data lc SET LC.tax_id= (SELECT CONCAT((CONCAT((CONCAT(SUBSTR(TRIM(OA.AFM_NO),1,3),'-')),((CONCAT(SUBSTR(TRIM(OA.AFM_NO),4,3),'-'))))),SUBSTR(TRIM(OA.AFM_NO),7,3)) FROM OTHER_AFM OA
WHERE OA.FK_CUSTOMERCUST_ID=LC.cust_id AND OA.MAIN_FLAG='1')
WHERE LC.cust_type='2' OR (LC.cust_type='1' AND LC.IND_CLASS='SoleProprietor');
INSERT INTO LNS_CRD_CUST_SUB_DATA
(REPORTING_DATE,
LOAN_CODE,
CUST_ID,
CLIENT_ROLE,
COLLATERAL_VALUE)
SELECT
(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
  J.LOAN_CODE,
  C.CUST_ID AS CUST_ID,
  'MainDebtor' AS CLIENT_ROLE,
  0
FROM LNS_CRD_LOAN_DATA J,CUSTOMER C,AGREEMENT_BENEF B,PROFITS_ACCOUNT P
WHERE P.ACCOUNT_NUMBER=J.LOAN_CODE
AND P.PRFT_SYSTEM=4
AND P.AGR_MEMBERSHIP_SN=B.FK_AGREEMENTAGR_ME
AND P.AGR_SN=B.FK_AGREEMENTAGR_SN
AND P.AGR_UNIT=B.FK_AGREEMENTFK_UNI
AND P.AGR_YEAR=B.FK_AGREEMENTAGR_YE
AND B.BENEF_STATUS='1'
AND B.MAIN_BENEF_FLG='1'
AND B.FK_CUSTOMERCUST_ID=C.CUST_ID;
INSERT INTO LNS_CRD_CUST_SUB_DATA
(REPORTING_DATE,
LOAN_CODE,
CUST_ID,
CLIENT_ROLE,
COLLATERAL_VALUE)
SELECT
(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
   J.LOAN_CODE,
  C.CUST_ID AS CUST_ID,
  'CoDebtor' AS CLIENT_ROLE,
  0
FROM LNS_CRD_LOAN_DATA J,CUSTOMER C,AGREEMENT_BENEF AB,PROFITS_ACCOUNT P
WHERE P.ACCOUNT_NUMBER=J.LOAN_CODE
AND P.PRFT_SYSTEM=4
AND P.AGR_MEMBERSHIP_SN=AB.FK_AGREEMENTAGR_ME
AND P.AGR_SN=AB.FK_AGREEMENTAGR_SN
AND P.AGR_UNIT=AB.FK_AGREEMENTFK_UNI
AND P.AGR_YEAR=AB.FK_AGREEMENTAGR_YE
AND AB.BENEF_STATUS='1'
AND AB.MAIN_BENEF_FLG<>'1'
AND AB.FK_CUSTOMERCUST_ID=C.CUST_ID;
INSERT INTO LNS_CRD_CUST_SUB_DATA
(REPORTING_DATE,
LOAN_CODE,
CUST_ID,
CLIENT_ROLE,
COLLATERAL_VALUE)
SELECT
(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
   J.LOAN_CODE,
  C.CUST_ID AS CUST_ID,
  'Guarantor' AS CLIENT_ROLE,
  B.GUARANTEE_AMOUNT
FROM LNS_CRD_LOAN_DATA J,CUSTOMER C,AGREEMENT_GUARANT B,PROFITS_ACCOUNT P
WHERE P.ACCOUNT_NUMBER=J.LOAN_CODE
AND P.PRFT_SYSTEM=4
AND P.AGR_MEMBERSHIP_SN=B.FK_AGREEMENTAGR_ME
AND P.AGR_SN=B.FK_AGREEMENTAGR_SN
AND P.AGR_UNIT=B.FK_AGREEMENTFK_UNI
AND P.AGR_YEAR=B.FK_AGREEMENTAGR_YE
AND B.GUARANTOR_STATUS='1'
AND B.FK_CUSTOMERCUST_ID=C.CUST_ID;
INSERT INTO LNS_CRD_CUST_address
  ( CUST_ID, ADDRESS_TYPE, COUNTRY, DISTRICT, HOUSE_NUM,
    ZIP_CODE, REGION, STREET_WARD,CITY,REPORTING_DATE)
  SELECT
  CA.FK_CUSTOMERCUST_ID, 'Physical', TRIM(GD.SHORT_DESCRIPTION) ,
  TRIM(GD1.DESCRIPTION), TRIM(CA.ADDRESS_6), TRIM(CA.ZIP_CODE),
  TRIM(CA.REGION), TRIM(CA.ADDRESS_1),TRIM(CA.CITY), (SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B)
  FROM
  CUST_ADDRESS CA, LNS_CRD_CUST_DATA LC, GENERIC_DETAIL GD, GENERIC_DETAIL GD1
  ,customer c
  WHERE LC.CUST_ID = CA.FK_CUSTOMERCUST_ID
  AND CA.COMMUNICATION_ADDR='1'
  AND C.CUST_TYPE = 1
  AND NOT EXISTS (SELECT * FROM LNS_CRD_CUST_ADDRESS L WHERE L.CUST_ID = C.CUST_ID AND L.ADDRESS_TYPE = 'Physical' )
  AND GD.FK_GENERIC_HEADPAR=CA.FKGH_HAS_COUNTRY
  AND GD.SERIAL_NUM=CA.FKGD_HAS_COUNTRY
  AND GD1.FK_GENERIC_HEADPAR=CA.FKGH_HAS_AS_DISTRI
  AND GD1.SERIAL_NUM=CA.FKGD_HAS_AS_DISTRI
  and c.cust_id = CA.FK_CUSTOMERCUST_ID  ;
INSERT INTO LNS_CRD_CUST_address
  ( CUST_ID, ADDRESS_TYPE, COUNTRY, DISTRICT, HOUSE_NUM,
    ZIP_CODE, REGION, STREET_WARD,CITY,REPORTING_DATE)
  SELECT
  CA.FK_CUSTOMERCUST_ID, 'Registration', TRIM(GD.SHORT_DESCRIPTION) ,
  TRIM(GD1.DESCRIPTION), TRIM(CA.ADDRESS_6), TRIM(CA.ZIP_CODE),
  TRIM(CA.REGION), TRIM(CA.ADDRESS_1),TRIM(CA.CITY),(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B)
  FROM
  CUST_ADDRESS CA, LNS_CRD_CUST_DATA LC, GENERIC_DETAIL GD, GENERIC_DETAIL GD1
  ,customer c
  WHERE LC.CUST_ID = CA.FK_CUSTOMERCUST_ID
  AND CA.COMMUNICATION_ADDR='1'
  AND C.CUST_TYPE = 2
  AND NOT EXISTS (SELECT * FROM LNS_CRD_CUST_ADDRESS L WHERE L.CUST_ID = C.CUST_ID AND L.ADDRESS_TYPE = 'Registration' )
  AND GD.FK_GENERIC_HEADPAR=CA.FKGH_HAS_COUNTRY
  AND GD.SERIAL_NUM=CA.FKGD_HAS_COUNTRY
  AND GD1.FK_GENERIC_HEADPAR=CA.FKGH_HAS_AS_DISTRI
  AND GD1.SERIAL_NUM=CA.FKGD_HAS_AS_DISTRI
  and c.cust_id = CA.FK_CUSTOMERCUST_ID  ;
DELETE FROM LNS_CRD_CUST_address WHERE ADDRESS_TYPE IS NULL;
INSERT INTO LNS_CRD_COLL_SUB_DATA
(REPORTING_DATE,
LOAN_CODE,
COLLATERAL_TYPE,
COLLATERAL_SN,
COLLATERAL_VALUE,
COLL_TYPE,
COLL_UNIT,
INTERNAL_SN,
CUST_ID
)
SELECT
(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
  J.LOAN_CODE,
  CASE
  WHEN AC.FK_COLLATERALFK_CO =20019 THEN 'Deposit'
  WHEN AC.FK_COLLATERALFK_CO =20020 THEN 'RealEstate'
  WHEN AC.FK_COLLATERALFK_CO =20021 THEN 'SalaryDeposit'
  WHEN AC.FK_COLLATERALFK_CO =20022 THEN 'MotorVehicle'
  WHEN AC.FK_COLLATERALFK_CO =20024 THEN 'Stocks'
  WHEN AC.FK_COLLATERALFK_CO =20026 THEN 'GovernmentSecurities'
  WHEN AC.FK_COLLATERALFK_CO =20027 THEN 'Other'
  WHEN AC.FK_COLLATERALFK_CO =20029 THEN 'Other'
  WHEN AC.FK_COLLATERALFK_CO =20030 THEN 'Other'
  WHEN AC.FK_COLLATERALFK_CO =20031 THEN 'Equipment'
ELSE
'Other'
END ,
AC.FK_COLLATERALCOLLA,
AC.YIELD_LIMIT_AMN,
AC.FK_COLLATERALFK_CO,
FK_COLLATERALFK_UN,
AC.INTERNAL_SN,
FK_CUSTOMERCUST_ID
FROM ACCOUNT_COLLATERAL AC,LNS_CRD_LOAN_DATA J
WHERE AC.PRFT_ACCOUNT=J.LOAN_CODE
AND AC.ENTRY_STATUS=1;
INSERT INTO LNS_CRD_COLL_SUB_DATA
(REPORTING_DATE,
LOAN_CODE,
COLLATERAL_TYPE,
COLLATERAL_SN,
COLLATERAL_VALUE,
COLL_TYPE,
COLL_UNIT,
INTERNAL_SN,
CUST_ID
)
SELECT
(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B) AS REPORTING_DATE,
  J.LOAN_CODE,
  CASE
  WHEN AC.FK_COLLATERALFK_CO =20019 THEN 'Deposit'
  WHEN AC.FK_COLLATERALFK_CO =20020 THEN 'RealEstate'
  WHEN AC.FK_COLLATERALFK_CO =20021 THEN 'SalaryDeposit'
  WHEN AC.FK_COLLATERALFK_CO =20022 THEN 'MotorVehicle'
  WHEN AC.FK_COLLATERALFK_CO =20024 THEN 'Stocks'
  WHEN AC.FK_COLLATERALFK_CO =20026 THEN 'GovernmentSecurities'
  WHEN AC.FK_COLLATERALFK_CO =20027 THEN 'Other'
  WHEN AC.FK_COLLATERALFK_CO =20029 THEN 'Other'
  WHEN AC.FK_COLLATERALFK_CO =20030 THEN 'Other'
 WHEN AC.FK_COLLATERALFK_CO =20031 THEN 'Equipment'
ELSE
'Other'
END ,
AC.FK_COLLATERALCOLLA,
AC.YIELD_LIMIT_AMN,
AC.FK_COLLATERALFK_CO,
FK_COLLATERALFK_UN,
AC.INTERNAL_SN,
FK_CUSTOMERCUST_ID
FROM ACCOUNT_COLLATERAL AC,LNS_CRD_LOAN_DATA J,PROFITS_ACCOUNT LP,PROFITS_ACCOUNT AP
WHERE LP.ACCOUNT_NUMBER=J.LOAN_CODE
AND LP.PRFT_SYSTEM=4
AND LP.AGR_MEMBERSHIP_SN=AP.AGR_MEMBERSHIP_SN
AND LP.AGR_SN=AP.AGR_SN
AND LP.AGR_UNIT=AP.AGR_UNIT
AND LP.AGR_YEAR=AP.AGR_YEAR
AND AP.PRFT_SYSTEM=19
AND AP.ACCOUNT_NUMBER=AC.PRFT_ACCOUNT
AND AC.ENTRY_STATUS=1;
INSERT INTO LNS_CRD_CUST_address
  ( CUST_ID, ADDRESS_TYPE, COUNTRY, DISTRICT, HOUSE_NUM,
    ZIP_CODE, REGION, STREET_WARD,CITY,REPORTING_DATE)
  SELECT
  CA.FK_CUSTOMERCUST_ID,
  CASE WHEN ( CA.ADDRESS_TYPE='2' AND LC.CUST_TYPE='1') THEN 'Permanent residence'
       WHEN ( CA.ADDRESS_TYPE='3' AND LC.CUST_TYPE='1') THEN 'Physical'
       WHEN ( CA.ADDRESS_TYPE='4' AND LC.CUST_TYPE='1') THEN 'Employer'
       WHEN ( CA.ADDRESS_TYPE='1' AND LC.CUST_TYPE='2') THEN 'Registration'
       WHEN ( CA.ADDRESS_TYPE='4' AND LC.CUST_TYPE='2') THEN 'Business'
    END ,
  TRIM(GD.SHORT_DESCRIPTION) , TRIM(GD1.DESCRIPTION), TRIM (CA.ADDRESS_6), TRIM(CA.ZIP_CODE), TRIM(CA.REGION) , TRIM(CA.ADDRESS_1),TRIM(CA.CITY),(SELECT B.SCHEDULED_DATE FROM BANK_PARAMETERS B)
  FROM
  CUST_ADDRESS CA, LNS_CRD_CUST_DATA LC, GENERIC_DETAIL GD, GENERIC_DETAIL GD1
  WHERE LC.CUST_ID = CA.FK_CUSTOMERCUST_ID
  --AND LC.CUST_TYPE='1'
  AND CA.ADDRESS_TYPE NOT IN ('3','1')
  AND CA.COMMUNICATION_ADDR <> '1'
  AND GD.FK_GENERIC_HEADPAR=CA.FKGH_HAS_COUNTRY
  AND GD.SERIAL_NUM=CA.FKGD_HAS_COUNTRY
  AND GD1.FK_GENERIC_HEADPAR=CA.FKGH_HAS_AS_DISTRI
  AND GD1.SERIAL_NUM=CA.FKGD_HAS_AS_DISTRI ;
 
UPDATE LNS_CRD_CUST_DATA SET CELLULAR_PHONE = CONCAT(0,substr(CELLULAR_PHONE,5,12)) WHERE substr(CELLULAR_PHONE,1,4)= '+255';
UPDATE LNS_CRD_CUST_DATA SET CELLULAR_PHONE = CONCAT(0,substr(CELLULAR_PHONE,4,12)) WHERE substr(CELLULAR_PHONE,1,3)= '255';
UPDATE LNS_CRD_CUST_DATA SET CELLULAR_PHONE = CONCAT(0,substr(FIXED_LINE,5,12)) WHERE substr(FIXED_LINE,1,4)= '+255';
UPDATE LNS_CRD_CUST_DATA SET CELLULAR_PHONE = CONCAT(0,substr(FIXED_LINE,4,12)) WHERE substr(FIXED_LINE,1,3)= '255';
UPDATE BATCH_CONTROL
SET PROGRAM_STS = 0
WHERE PROGRAM_ID = 'U9682'
AND SCHEDULED_DATE = (SELECT SCHEDULED_DATE FROM BANK_PARAMETERS);
END;

