create table LOAN_BATCH_INST_HD_ALL
(
    TMSTAMP           TIMESTAMP(6) not null,
    TRX_USER          CHAR(8)      not null,
    ACC_UNIT          INTEGER      not null,
    ACC_TYPE          INTEGER      not null,
    ACC_SN            INTEGER      not null,
    ACC_MECHANISM     CHAR(1),
    ACC_STATUS        CHAR(1),
    LOAN_STATUS       CHAR(1),
    PROFITS_ACCOUNT   CHAR(40),
    ID_CURRENCY       INTEGER,
    ID_PRODUCT        INTEGER,
    ID_CUSTOMER       INTEGER,
    AAIR_INTEREST     DECIMAL(8, 4),
    BANK_NAME         VARCHAR(40),
    UNIT_TELEPHONE    VARCHAR(15),
    UNIT_EMAIL        VARCHAR(320),
    UNIT_FAX          VARCHAR(15),
    UNIT_LONGITUDE    CHAR(50),
    UNIT_LATITUDE     CHAR(50),
    CUST_NAME         CHAR(100),
    CUST_ADDRESS      VARCHAR(40),
    CUST_CITY         CHAR(30),
    CUST_ZIP_CODE     CHAR(10),
    AGREEMENT_NUM     CHAR(40),
    AGREEMENT_CD      INTEGER,
    DRAWDOWN_FST_AMN  DECIMAL(15, 2),
    ACC_EXP_DT        DATE,
    TOT_NRM_INT_PRC   DECIMAL(8, 4),
    N128_PRC          DECIMAL(8, 4),
    N128_DESC         VARCHAR(40),
    WRITE_OFF_AMN     DECIMAL(15, 2),
    TEXT_DEL_AMN      VARCHAR(1000),
    BENEF_CUST_ID     INTEGER,
    BENEF_CUST_CD     INTEGER,
    BENEF_CUST_NAME   CHAR(100),
    TEXT_01           VARCHAR(100),
    TEXT_02           VARCHAR(100),
    TEXT_03           VARCHAR(100),
    TEXT_04           VARCHAR(100),
    TEXT_05           VARCHAR(100),
    SIGNIFICANT_VALUE VARCHAR(100),
    FILENAME          VARCHAR(100),
    PRINT_FLG         CHAR(1),
    TRX_CODE          INTEGER,
    constraint PK_HD_INST_ALL
        primary key (ACC_SN, ACC_TYPE, ACC_UNIT, TRX_USER, TMSTAMP)
);

