create table LOAN_DRAWDOWN_SCHEDULE
(
    ACCOUNT_NUMBER    CHAR(40) not null,
    ACCOUNT_SYSTEM    SMALLINT not null,
    DRAWDOWN_DATE     DATE     not null,
    DRAWDOWN_FULL     CHAR(1),
    DRAWDOWN_LIMIT    DECIMAL(15, 2),
    DRAWDOWN_USED     DECIMAL(15, 2),
    DAYS_BEFORE       SMALLINT,
    DAYS_AFTER        SMALLINT,
    DRAWDOWN_COMMENTS VARCHAR(250),
    ENTRY_STATUS      CHAR(1),
    TRX_USER          CHAR(8),
    TRX_DATE          DATE,
    TRX_TIMESTAMP     TIMESTAMP(6),
    UTILIZED_STATUS   CHAR(1),
    UTIL_TRX_UNIT     INTEGER,
    UTIL_TRX_USR      CHAR(8),
    UTIL_TRX_DATE     DATE,
    UTIL_TMSTAMP      TIMESTAMP(6),
    constraint LOAN_DRAWDOWN_SCHEDULE_KEY
        primary key (ACCOUNT_NUMBER, ACCOUNT_SYSTEM, DRAWDOWN_DATE)
);

