create table LOANS_GLI_INTERFAC
(
    FK_UNITCODE        INTEGER  not null,
    FK_USRCODE         CHAR(8)  not null,
    LINE_NUM           SMALLINT not null,
    TRN_SNUM           INTEGER  not null,
    TRN_DATE           DATE     not null,
    AMOUNT_SER_NO      SMALLINT,
    FK0UNITCODE        INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK_CURR_TABLE_PFK  INTEGER,
    FK1UNITCODE        INTEGER,
    FK_CUSTOMERCODE    INTEGER,
    DOC_NUM            INTEGER,
    FK0CURR_TABLE_PFK  DECIMAL(10),
    DEAL_SLIP_NUM      DECIMAL(10),
    REF_NUM            DECIMAL(10),
    RATE               DECIMAL(12, 6),
    AMOUNT             DECIMAL(15, 2),
    CANCEL_DATE        DATE,
    GL_TRN_DATE        DATE,
    VALEUR_DATE        DATE,
    DOC_TYPE           CHAR(1),
    ENTRY_STATUS       CHAR(1),
    AUTO_FLAG          CHAR(1),
    ENTRY_TYPE         CHAR(1),
    RECON_FLAG         CHAR(1),
    TRN_ACTION_TYPE    CHAR(1),
    REF_NUM_FLAG       CHAR(1),
    PRIM_AGRE_IND      CHAR(1),
    TRN_TYPE           CHAR(1),
    ACCOUNTED_FLAG     CHAR(1),
    ACCNT_LEVEL        CHAR(1),
    FK_GLG_JOURNALJOUR CHAR(2),
    FK_GLG_DOCUMENTDO0 CHAR(2),
    SUBSYSTEM          CHAR(2),
    GLACC_ORIGIN       CHAR(2),
    FK_GLG_CURR_CATCUR CHAR(4),
    FK_GLG_JUSTIFYJUST CHAR(4),
    FK_GLG_DOCUMENTDOC CHAR(4),
    FK_COST_MODEL_TTRN CHAR(6),
    FK_GLG_MODEL_TRTRN CHAR(6),
    TAX_REG_NO         CHAR(10),
    REMARKS            CHAR(20),
    DOC_CTL_NUM        CHAR(20),
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_TERMINALTERMINA CHAR(99),
    constraint IXU_DEF_027
        primary key (FK_UNITCODE, FK_USRCODE, LINE_NUM, TRN_SNUM, TRN_DATE)
);

