create table LOAN_CORRECTION
(
    LNS_SN            INTEGER      not null,
    LNS_TYPE          SMALLINT     not null,
    LNS_OPEN_UNIT     INTEGER      not null,
    TMSTAMP           TIMESTAMP(6) not null,
    FLOAT_INTER_ID    INTEGER,
    MOVEMENT_CURRENCY INTEGER,
    FIXED_INTER_ID    INTEGER,
    K_MORAT_NRM_RATE  DECIMAL(9, 6),
    K_MORAT_SPR_RATE  DECIMAL(9, 6),
    P_MORAT_SPR_RATE  DECIMAL(9, 6),
    K_MORAT_SUBS_RATE DECIMAL(9, 6),
    P_MORAT_SUBS_RATE DECIMAL(9, 6),
    P_MORAT_NRM_RATE  DECIMAL(9, 6),
    P_MORAT_N128_RATE DECIMAL(9, 6),
    K_MORAT_N128_RATE DECIMAL(9, 6),
    K_INSTL_FIXED_AMN DECIMAL(15, 2),
    P_INSTL_FIXED_AMN DECIMAL(15, 2),
    K_MP_ST_CAP_AMN   DECIMAL(15, 2),
    P_MP_ST_CAP_AMN   DECIMAL(15, 2),
    LOAN_CORR_STATUS  CHAR(1),
    constraint IXU_LNS_035
        primary key (LNS_SN, LNS_TYPE, LNS_OPEN_UNIT, TMSTAMP)
);

