create table LOAN_ACC_STMENT_HD
(
    BATCH_DATE            DATE           not null,
    ACCOUNT_NUMBER        CHAR(40)       not null,
    ACCOUNT_PRFT_SYS      SMALLINT       not null,
    ACCOUNT_CD            SMALLINT,
    PRODUCT_ID            INTEGER,
    CUST_ID               INTEGER        not null,
    CUST_CD               SMALLINT,
    CUST_ADDR_SN          SMALLINT,
    AGR_PRFT_ACC          CHAR(40),
    AGR_ACC_PRFT_SYS      SMALLINT,
    AGR_ACC_CD            SMALLINT,
    MOVE_CURR_ID          INTEGER,
    ACC_OPEN_UNIT         INTEGER,
    ACC_MONITOR_UNIT      INTEGER,
    ACC_OPEN_DT           DATE,
    ACC_EXP_DT            DATE,
    TOT_DRAWDOWN_AMN      DECIMAL(15, 2),
    INSTALL_NEXT_DT       DATE,
    REMAIN_INSTALL        SMALLINT,
    INSTALL_FIXED_AMN     DECIMAL(15, 2),
    INSUR_REMAIN          DECIMAL(15, 2),
    LCATG_DESC            CHAR(40),
    LAND_REGIST_ID        CHAR(50),
    ACCOUNT_BAL           DECIMAL(15, 2),
    NRM_ACCOUNT_BAL       DECIMAL(15, 2),
    OV_ACCOUNT_BAL        DECIMAL(15, 2),
    TOT_URL_BAL           DECIMAL(15, 2),
    STATEMENT_DT_FROM     DATE,
    STATEMENT_DT_TO       DATE,
    PREV_TOTAL_BAL        DECIMAL(15, 2),
    NRM_CAP_BAL           DECIMAL(15, 2),
    TOT_CAP_BAL           DECIMAL(15, 2),
    TOT_OV_NO_CAP_BAL     DECIMAL(15, 2),
    TOT_OV_BAL            DECIMAL(15, 2),
    OV_RL_NRM_INT_BAL     DECIMAL(15, 2),
    OV_RL_PNL_INT_BAL     DECIMAL(15, 2),
    PERIOD_INT_CHARGE     DECIMAL(15, 2) not null,
    TOT_DEL_BAL           DECIMAL(15, 2),
    ACCOUNT_TOTAL_BAL     DECIMAL(15, 2),
    NRM_INT_RATE          DECIMAL(8, 4),
    PNL_INT_RATE          DECIMAL(8, 4),
    FINAL_INT_RATE        DECIMAL(8, 4),
    TOT_PNL_INT_RATE      DECIMAL(8, 4),
    BASE_INT_RATE         DECIMAL(8, 4),
    EXTRA_INT_RATE        DECIMAL(8, 4),
    SEPE_RATE             DECIMAL(8, 4),
    RELATE_MGR_USR        CHAR(8),
    STATEMENT_FEE         DECIMAL(15, 2),
    NUM_OF_STMNT_LINES    INTEGER,
    RECORD_STATUS         CHAR(1),
    RECORD_STATUS_DESC    CHAR(80),
    CONTRACT_DATE         DATE,
    COUNTRY               CHAR(40),
    FREQUENCY             CHAR(30),
    REAL_ESTATE_DESC      CHAR(40),
    INSURER               CHAR(70),
    POLICY_NO             CHAR(30),
    ISS_EXPIRY_DATE       DATE,
    INSURANCE_PRD1        CHAR(40),
    INSURANCE_PRD2        CHAR(40),
    INSURANCE_PRD3        CHAR(40),
    INSURANCE_PRD4        CHAR(40),
    INSURANCE_PRD5        CHAR(40),
    INSURANCE_AMN1        DECIMAL(15, 2),
    INSURANCE_AMN2        DECIMAL(15, 2),
    INSURANCE_AMN3        DECIMAL(15, 2),
    INSURANCE_AMN4        DECIMAL(15, 2),
    INSURANCE_AMN5        DECIMAL(15, 2),
    BSECT_DESC            CHAR(40),
    UNIT_TELEPHONE        CHAR(15),
    UNIT_EMAIL            CHAR(40),
    UNIT_FAX              CHAR(15),
    UNIT_LONGITUDE        CHAR(50),
    UNIT_LATITUDE         CHAR(50),
    TOT_NRM_INT_NO_N128   DECIMAL(8, 4),
    N128_DESC             CHAR(40),
    EOM_OV_CAP_BAL        DECIMAL(15, 2),
    EOM_OV_RL_NRM_INT_BAL DECIMAL(15, 2),
    EOM_OV_RL_PNL_INT_BAL DECIMAL(15, 2),
    EOM_OV_EXP_BAL        DECIMAL(15, 2),
    MIN_PAY_AMN_MECH_7    DECIMAL(15, 2),
    NEXT_PAY_DT_MECH_7    DATE,
    FILENAME              CHAR(70),
    TOT_OV_NRM_INT        DECIMAL(15, 2),
    TOT_OV_PNL_INT        DECIMAL(15, 2),
    TMSTAMP               DATE,
    WRITE_OFF_AMN         DECIMAL(15, 2),
    AUCTION_AMN           DECIMAL(15, 2),
    TEXT_DEL_AMN          VARCHAR(1000),
    RF_CODE_TXT_1         VARCHAR(250),
    RF_CODE_TXT_2         VARCHAR(1000),
    constraint PK_LNS_ACC_STMENT_HD
        primary key (ACCOUNT_PRFT_SYS, ACCOUNT_NUMBER, BATCH_DATE, CUST_ID)
);

