create table LOAN_HISTORY
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    FK_LOAN_ACCOUNTACC INTEGER,
    FK_UPD_CAUSE_GEN_H CHAR(5),
    FK_UPD_CAUSE_GEN_D INTEGER,
    TMPSTAMP           TIMESTAMP(6),
    EXCMPT_PNL_PRD_NO  SMALLINT,
    TRX_INTERNAL_SN    SMALLINT,
    TRX_UNIT           INTEGER,
    TRX_SN             INTEGER,
    ACCOUNT_BAL_AMN    DECIMAL(15, 2),
    ACCOUNT_LIMIT_AMN  DECIMAL(15, 2),
    DRAWDOWN_EXPIRE_DT DATE,
    ACCOUNT_EXPIRE_DT  DATE,
    TRX_DATE           DATE,
    ACCOUNT_STATUS     CHAR(1),
    LOAN_STATUS        CHAR(1),
    REPAYMENT_SCH_FLG  CHAR(1),
    MAINTAIN_EQ_INST   CHAR(1),
    OV_EXP_EXT_FLG     CHAR(1),
    TRX_USR            CHAR(8),
    LOAN_CLASS         CHAR(1),
    LOAN_SUB_CLASS     CHAR(1),
    COLLATERAL_OMVALUE DECIMAL(15, 2),
    NXT_INT_CALC_DT    DATE,
    PRV_INT_CALC_DT    DATE,
    INTER_RATE_SPRD    DECIMAL(8, 4),
    ADJUST_CODE        INTEGER,
    ADJUST_DT          DATE,
    HISTORY_COMMENTS   CHAR(80)
);

create unique index PIXLNHST
    on LOAN_HISTORY (FK_LOAN_ACCOUNTFK, FK0LOAN_ACCOUNTACC, FK_LOAN_ACCOUNTACC, FK_UPD_CAUSE_GEN_H, FK_UPD_CAUSE_GEN_D,
                     TMPSTAMP);

