create table LOAN_GL_AGREEMENT
(
    CLASS_CODE        INTEGER,
    CUST_CATEGORY     INTEGER,
    ID_CURRENCY       INTEGER,
    ID_PRODUCT        INTEGER,
    LOAN_STS          CHAR(1),
    TRX_DATE          DATE,
    UNIT_CODE         INTEGER,
    TOTAL_ACC_BALANCE DECIMAL(15, 2),
    DR_CNTR_GL_ACC    CHAR(21)
);

create unique index IXU_LOA_045
    on LOAN_GL_AGREEMENT (CLASS_CODE, CUST_CATEGORY, ID_CURRENCY, ID_PRODUCT, LOAN_STS, TRX_DATE, UNIT_CODE);

