create table LOAN_SCENARIO_INST
(
    TMSTAMP            TIMESTAMP(6) not null,
    TRX_USER           CHAR(8)      not null,
    INSTALL_SN         INTEGER      not null,
    INSTALL_DT         DATE,
    INSTALL_CAP_AMN    DECIMAL(15, 2),
    INSTALL_CHARGE_AMN DECIMAL(15, 2),
    INSTALLMENT_AMN    DECIMAL(15, 2),
    REMAIN_CAP_AMN     DECIMAL(15, 2),
    INSTALL_INT_AMN    DECIMAL(15, 2),
    INSTALL_SPREAD_AMN DECIMAL(15, 2),
    INSTALL_N128_AMN   DECIMAL(15, 2),
    INSTALL_SUBS_AMN   DECIMAL(15, 2),
    INSTALL_EFTE_AMN   DECIMAL(15, 2),
    INSTALL_INSURANCE  DECIMAL(15, 2),
    INSTALL_COM_AMN    DECIMAL(15, 2),
    INTERNAL_TMSTAMP   TIMESTAMP(6) not null,
    INSTALL_SN_DATA    DECIMAL(10),
    constraint PK_LNSSCENINST
        primary key (TMSTAMP, TRX_USER, INSTALL_SN, INTERNAL_TMSTAMP)
);

create unique index PK_LNSSCENINST
    on LOAN_SCENARIO_INST (TMSTAMP, TRX_USER, INSTALL_SN);

