create table LOAN_ACC_PRD_TOT
(
    ACC_SN           INTEGER,
    ACC_TYPE         SMALLINT,
    ACC_UNIT         INTEGER,
    TMSTAMP          TIMESTAMP(6),
    ACC_CD           SMALLINT,
    TRX_CALC_DAYS    SMALLINT,
    VALUE_CALC_DAYS  SMALLINT,
    VALUE_FULL       DECIMAL(15, 2),
    VALUE_UNREAL     DECIMAL(15, 2),
    VALUE_POSOTIVE   DECIMAL(15, 2),
    VALUE_NRM_FULL   DECIMAL(15, 2),
    VALUE_NRM_UNREAL DECIMAL(15, 2),
    VALUE_OV_FULL    DECIMAL(15, 2),
    VALUE_OV_UNREAL  DECIMAL(15, 2),
    VALUE_DD_FULL    DECIMAL(15, 2),
    VALUE_DD_UNREAL  DECIMAL(15, 2),
    VALUE_WO_FULL    DECIMAL(15, 2),
    TRX_WO_UNREAL    DECIMAL(15, 2),
    TRX_WO_FULL      DECIMAL(15, 2),
    VALUE_WO_UNREAL  DECIMAL(15, 2),
    TRX_DD_FULL      DECIMAL(15, 2),
    TRX_OV_UNREAL    DECIMAL(15, 2),
    TRX_OV_FULL      DECIMAL(15, 2),
    TRX_NRM_UNREAL   DECIMAL(15, 2),
    TRX_NRM_FULL     DECIMAL(15, 2),
    TRX_POSOTIVE     DECIMAL(15, 2),
    TRX_UNREAL       DECIMAL(15, 2),
    TRX_FULL         DECIMAL(15, 2),
    TRX_DD_UNREAL    DECIMAL(15, 2),
    TRX_DATE_TO      DATE,
    TRX_DATE_FROM    DATE,
    VALUE_DATE_TO    DATE,
    VALUE_DATE_FROM  DATE
);

create unique index IXU_LOA_033
    on LOAN_ACC_PRD_TOT (ACC_SN, ACC_TYPE, ACC_UNIT, TMSTAMP);

