create table LOAN_INSTALL_CHG
(
    FK_LOAN_ACCOUNTFK  INTEGER,
    FK0LOAN_ACCOUNTACC SMALLINT,
    FK_LOAN_ACCOUNTACC INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PAYROLL_AGR_CODE   INTEGER,
    CHANGE_DT          DATE,
    INSTALL_COUNT      SMALLINT,
    INSTALL_FREQ       SMALLINT,
    MORATOR_NRM_RATE   DECIMAL(9, 6),
    MORATOR_SUBS_RATE  DECIMAL(9, 6),
    MORATOR_SPR_RATE   DECIMAL(9, 6),
    MORATOR_N128_RATE  DECIMAL(9, 6),
    PREPAYMENT_AMOUNT  DECIMAL(15, 2),
    DRAWDOWN_FST_AMN   DECIMAL(15, 2),
    INSTALL_FIXED_AMN  DECIMAL(15, 2),
    DRAWDOWN_FST_DT    DATE,
    ACC_EXP_DT         DATE,
    DRAWDOWN_EXP_DT    DATE,
    CHANGE_REASON      CHAR(1),
    PROCESSED_FLG      CHAR(1),
    ICOM_KEEP_TMDATE   DATE,
    ICOM_KEEP_TMSTAMP  TIMESTAMP(6)
);

create unique index IXU_LOA_047
    on LOAN_INSTALL_CHG (FK_LOAN_ACCOUNTFK, FK0LOAN_ACCOUNTACC, FK_LOAN_ACCOUNTACC, TMSTAMP, PAYROLL_AGR_CODE,
                         CHANGE_DT);

