create table LOAN_MOVE_ACCOUNT
(
    OLD_ACC_UNIT       INTEGER,
    OLD_ACC_TYPE       SMALLINT,
    OLD_ACC_SN         INTEGER,
    CUST_ID            INTEGER,
    TMSTAMP            TIMESTAMP(6),
    OLD_ACC_CD         SMALLINT,
    NEW_ACC_TYPE       SMALLINT,
    NEW_ACC_CD         SMALLINT,
    LAST_NRM_TRX_CNT   SMALLINT,
    NEW_ACC_UNIT       INTEGER,
    NEW_ACC_SN         INTEGER,
    OV_ACR_PUB_INT_AMN DECIMAL(15, 2),
    OV_SUBSIDY_BAL     DECIMAL(15, 2),
    NRM_CAP_BAL        DECIMAL(15, 2),
    NRM_RL_INT_BAL     DECIMAL(15, 2),
    NRM_URL_INT_BAL    DECIMAL(15, 2),
    NRM_EXP_BAL        DECIMAL(15, 2),
    OV_URL_PUB_INT_AMN DECIMAL(15, 2),
    OV_ACR_PNL_INT_BAL DECIMAL(15, 2),
    OV_ACR_NRM_INT_BAL DECIMAL(15, 2),
    OV_COM_BAL         DECIMAL(15, 2),
    OV_EXP_BAL         DECIMAL(15, 2),
    OV_URL_PNL_INT_BAL DECIMAL(15, 2),
    OV_URL_NRM_INT_BAL DECIMAL(15, 2),
    OV_RL_PNL_INT_BAL  DECIMAL(15, 2),
    OV_RL_NRM_INT_BAL  DECIMAL(15, 2),
    OV_CAP_BAL         DECIMAL(15, 2),
    POSOTIVE_BAL       DECIMAL(15, 2),
    NRM_SUBSIDY_BAL    DECIMAL(15, 2),
    NR_ACR_PUB_INT_AMN DECIMAL(15, 2),
    NRM_COM_BAL        DECIMAL(15, 2),
    NRM_ACR_INT_BAL    DECIMAL(15, 2),
    NR_URL_PUB_INT_AMN DECIMAL(15, 2),
    TRANSFER_TRX_DATE  DATE,
    LST_TRX_DT         DATE,
    ACCOUNT_TMSTAMP    TIMESTAMP(6),
    REVERSED_FLG       CHAR(1)
);

create unique index IXN_LOA_000
    on LOAN_MOVE_ACCOUNT (NEW_ACC_UNIT, NEW_ACC_TYPE, NEW_ACC_SN, NEW_ACC_CD);

create unique index IXP_LOA_004
    on LOAN_MOVE_ACCOUNT (OLD_ACC_UNIT, OLD_ACC_TYPE, OLD_ACC_SN, CUST_ID, TMSTAMP);

