create table LOANS_BGM_SCHEDULE_HISTORY
(
    TRX_DATE               DATE     not null,
    TRX_UNIT               INTEGER  not null,
    TRX_USR                CHAR(8)  not null,
    TRX_SN                 INTEGER  not null,
    TRX_INTERNAL_SN        SMALLINT not null,
    TMSTMP                 TIMESTAMP(6),
    EXT_SYSTEM_ID          INTEGER,
    EXT_APPLICATION_GRP_ID VARCHAR(40),
    EXT_APPLICATION_ID     VARCHAR(40),
    BGM_APPLICATION_ID     CHAR(15),
    BGM_CUSTOMER           CHAR(20),
    BGM_PROGRAM            VARCHAR(20),
    BGM_TYPE               INTEGER,
    BGM_PROGRAM_STEP       INTEGER,
    BGM_PROGRAM_STEP_SN    INTEGER,
    BGM_OFFICER            CHAR(8),
    BGM_TRX_DATE           DATE,
    BGM_PROGRAM_STEP_REF   INTEGER,
    DATE_01                DATE,
    DATE_02                DATE,
    DATE_03                DATE,
    DATE_04                DATE,
    DATE_05                DATE,
    DATE_06                DATE,
    DATE_07                DATE,
    DATE_08                DATE,
    DATE_09                DATE,
    DATE_10                DATE,
    NUMBER_01              DECIMAL(10),
    NUMBER_02              DECIMAL(10),
    NUMBER_03              DECIMAL(10),
    NUMBER_04              DECIMAL(10),
    NUMBER_05              DECIMAL(10),
    NUMBER_06              DECIMAL(10),
    NUMBER_07              DECIMAL(10),
    NUMBER_08              DECIMAL(10),
    NUMBER_09              DECIMAL(10),
    NUMBER_10              DECIMAL(10),
    NUMBER_11              DECIMAL(10),
    NUMBER_12              DECIMAL(10),
    NUMBER_13              DECIMAL(10),
    NUMBER_14              DECIMAL(10),
    NUMBER_15              DECIMAL(10),
    NUMBER_16              DECIMAL(10),
    NUMBER_17              DECIMAL(10),
    NUMBER_18              DECIMAL(10),
    NUMBER_19              DECIMAL(10),
    NUMBER_20              DECIMAL(10),
    AMOUNT_01              DECIMAL(15, 2),
    AMOUNT_02              DECIMAL(15, 2),
    AMOUNT_03              DECIMAL(15, 2),
    AMOUNT_04              DECIMAL(15, 2),
    AMOUNT_05              DECIMAL(15, 2),
    AMOUNT_06              DECIMAL(15, 2),
    AMOUNT_07              DECIMAL(15, 2),
    AMOUNT_08              DECIMAL(15, 2),
    AMOUNT_09              DECIMAL(15, 2),
    AMOUNT_10              DECIMAL(15, 2),
    RATE_01                DECIMAL(8, 4),
    RATE_02                DECIMAL(8, 4),
    RATE_03                DECIMAL(8, 4),
    RATE_04                DECIMAL(8, 4),
    RATE_05                DECIMAL(8, 4),
    RATE_06                DECIMAL(8, 4),
    RATE_07                DECIMAL(8, 4),
    RATE_08                DECIMAL(8, 4),
    RATE_09                DECIMAL(8, 4),
    RATE_10                DECIMAL(8, 4),
    FLAG_01                CHAR(1),
    FLAG_02                CHAR(1),
    FLAG_03                CHAR(1),
    FLAG_04                CHAR(1),
    FLAG_05                CHAR(1),
    FLAG_06                CHAR(1),
    FLAG_07                CHAR(1),
    FLAG_08                CHAR(1),
    FLAG_09                CHAR(1),
    FLAG_10                CHAR(1),
    CHAR_01                VARCHAR(100),
    CHAR_02                VARCHAR(100),
    CHAR_03                VARCHAR(100),
    CHAR_04                VARCHAR(100),
    CHAR_05                VARCHAR(100),
    CHAR_06                VARCHAR(100),
    CHAR_07                VARCHAR(100),
    CHAR_08                VARCHAR(100),
    CHAR_09                VARCHAR(100),
    CHAR_10                VARCHAR(100),
    INSERT_TMSTAMP         TIMESTAMP(6),
    ENTRY_STATUS           CHAR(1),
    PROCESS_TMPSTAMP       TIMESTAMP(6),
    PROCESS_STATUS         CHAR(1),
    constraint BGMHIST
        primary key (TRX_INTERNAL_SN, TRX_SN, TRX_USR, TRX_UNIT, TRX_DATE)
);

comment on column LOANS_BGM_SCHEDULE_HISTORY.TRX_DATE is 'TRX_DATE   TUN';

comment on column LOANS_BGM_SCHEDULE_HISTORY.TRX_UNIT is 'TRX_UNIT  TUN';

comment on column LOANS_BGM_SCHEDULE_HISTORY.TRX_USR is 'TRX_USR  TUN';

comment on column LOANS_BGM_SCHEDULE_HISTORY.TRX_SN is 'TRX_SN/   TUN';

comment on column LOANS_BGM_SCHEDULE_HISTORY.TRX_INTERNAL_SN is 'TRX_INTERNAL_SN /   TUN';

comment on column LOANS_BGM_SCHEDULE_HISTORY.ENTRY_STATUS is 'ENTRY_STATUS0 = INACTIVE1 = ACTIVE';

comment on column LOANS_BGM_SCHEDULE_HISTORY.PROCESS_STATUS is 'PROCESS_STATUS0 = WAITING1 = PROCESSED-OK3 = PROCESSED-ERROR';

