create table LOAN_INSTALL_TIME
(
    ACC_UNIT   INTEGER  not null,
    ACC_TYPE   SMALLINT not null,
    ACC_SN     INTEGER  not null,
    ACC_CD     SMALLINT,
    TMSTAMP_01 TIMESTAMP(6),
    TMSTAMP_02 TIMESTAMP(6),
    TMSTAMP_03 TIMESTAMP(6),
    TMSTAMP_04 TIMESTAMP(6),
    TMSTAMP_05 TIMESTAMP(6),
    TMSTAMP_06 TIMESTAMP(6),
    TMSTAMP_07 TIMESTAMP(6),
    TMSTAMP_08 TIMESTAMP(6),
    TMSTAMP_09 TIMESTAMP(6),
    TMSTAMP_10 TIMESTAMP(6),
    constraint I0000928
        primary key (ACC_SN, ACC_TYPE, ACC_UNIT)
);

