create table LOGIN_HISTORY
(
    USERCODE       CHAR(8),
    UNITCODE       INTEGER,
    TERMINAL_ID    CHAR(99),
    LOGIN_TMSTAMP  TIMESTAMP(6),
    LOGOFF_TMSTAMP TIMESTAMP(6),
    MAC_ADDRESS    VARCHAR(20)
);

create unique index IXU_LOG_000
    on LOGIN_HISTORY (USERCODE, UNITCODE, TERMINAL_ID, LOGIN_TMSTAMP);

