create table MANDATE_EXE_HD
(
    ACCOUNT_NUMBER    CHAR(40) not null,
    PRFT_SYSTEM       SMALLINT not null,
    ID_TRANSACT       INTEGER  not null,
    SCALE_ID          SMALLINT not null,
    CONDITION_SN      INTEGER  not null,
    TRX_REFER_NO      CHAR(40) not null,
    ID_CHANNEL        INTEGER  not null,
    STATUS            CHAR(1),
    TIMESTAMP         TIMESTAMP(6),
    TRX_DATE          DATE,
    TRX_UNIT          INTEGER,
    TRX_USR           CHAR(8),
    TRX_USR_SN        INTEGER,
    TRX_AMOUNT        DECIMAL(15, 2),
    INITIATE_DATE     DATE,
    INITIATE_UNIT     INTEGER,
    INITIATE_USR      CHAR(8),
    INITIATE_TRX_CODE INTEGER,
    INITIATE_JUSTIFIC INTEGER,
    INITIATE_AMOUNT   DECIMAL(15, 2),
    IPROFITS_USERID   VARCHAR(40),
    IPROFITS_USERNAME VARCHAR(256),
    IPROFITS_USER     VARCHAR(105),
    I_COMPL_GR_SN     INTEGER,
    I_COMPL_GR_TMSTMP TIMESTAMP(6),
    IPROFITS_CUST_ID  INTEGER,
    constraint PK_MANDATE_EXE_HD
        primary key (ID_CHANNEL, TRX_REFER_NO, CONDITION_SN, SCALE_ID, ID_TRANSACT, PRFT_SYSTEM, ACCOUNT_NUMBER)
);

