create table MG_BILL_INV_INTER
(
    FILE_NAME            CHAR(50)       not null,
    FILE_DETAIL_ID       CHAR(2)        not null,
    SERIAL_NO            INTEGER        not null,
    BINV_TYPE_FLAG       CHAR(1),
    BINV_NUMBER          CHAR(20)       not null,
    REG_UNIT             INTEGER,
    REG_INS_DATE         DATE,
    REG_FINAL_DATE       DATE,
    CUSTOMER_CODE        CHAR(20),
    REGISTER_ID          CHAR(15),
    ISSUER_CUST_CODE     CHAR(20),
    PRF_ISSUER_CUST_ID   INTEGER,
    PRF_ISSUER_CODE      INTEGER,
    ISSUER_TYPE          CHAR(1),
    SURNAME              CHAR(70),
    FIRST_NAME           CHAR(20),
    FATHER_NAME          VARCHAR(20),
    ID_NO                CHAR(20),
    AFM_NO               CHAR(20),
    SUBJECT              CHAR(40),
    ADDRESS              CHAR(40),
    TELEPHONE            CHAR(15),
    WEIGHT_LIMIT         DECIMAL(15, 2),
    DISPERSAL_RATE       DECIMAL(8, 4),
    IBAN                 CHAR(40),
    BLACK_LIST           CHAR(1),
    FIRST_NOTICE_DATE    DATE,
    SEC_NOTICE_DATE      DATE,
    BINV_CARRIER_TITLE   CHAR(70),
    BINV_CARRIER_NAME    CHAR(30),
    BINV_CARRIER_ID      CHAR(10),
    BINV_CARRIER_NOTES   CHAR(100),
    BINV_ISSUE_DATE      DATE           not null,
    BINV_PAY_DATE        DATE,
    BINV_AMOUNT          DECIMAL(15, 2) not null,
    CURR_SHORT_DESCR     CHAR(5),
    BINV_CR_PAID_AMNT    DECIMAL(15, 2),
    BINV_STATUS_FLAG     CHAR(2),
    BINV_INS_DATE        DATE,
    BINV_FINAL_DATE      DATE,
    BINV_ENTRY_STATUS    CHAR(1)        not null,
    BINV_TMSTAMP         TIMESTAMP(6)   not null,
    BINV_CR_ACC_NUMBER   CHAR(40),
    BINV_CR_ACC_CD       SMALLINT,
    BINV_CRACC_PRFSYS    SMALLINT,
    BINV_CRACC_JUSTIF    INTEGER,
    BINV_CRACC_AVLDT     DATE,
    BINV_CRACC_INTDT     DATE,
    BINV_COLL_ACC_NUMB   CHAR(40),
    BINV_COLL_ACC_CD     SMALLINT,
    BINV_COLL_PRFSYS     SMALLINT,
    BINV_COLL_JUSTIF     INTEGER,
    BINV_COLL_YIELD_PERC DECIMAL(8, 5),
    BINV_EXPACC_NUMBER   CHAR(40),
    BINV_EXPACC_CD       SMALLINT,
    BINV_EXPACC_PRFSYS   SMALLINT,
    BINV_EXP_INTERDATE   DATE,
    BINV_COMM_DISCOUNT   DECIMAL(8, 4),
    BINV_EXP_DISCOUNT    DECIMAL(8, 4),
    COMMENTS             VARCHAR(200),
    MONITOR_UNIT_CODE    INTEGER,
    ROW_STATUS           CHAR(1),
    ROW_ERR_DESC         CHAR(80),
    BINV_CLRTYPE_FLAG    CHAR(1),
    constraint PK_BILL_INV_INTER
        primary key (SERIAL_NO, FILE_NAME)
);

