create table MG_CP_APPL_INTER
(
    DEP_TRANS_STATUS   SMALLINT,
    ACCOUNT1_TAUT      INTEGER,
    ACCOUNT2_TAUT      INTEGER,
    ACCOUNT_UNIT       INTEGER,
    SERIAL_NO          INTEGER,
    PRF_CUST_ID        INTEGER,
    MAX_DEBIT_AMOUNT   DECIMAL(15, 2),
    ISSUE_DATE         DATE,
    ACTIVATION_DATE    DATE,
    DEP_TRANS_PROC_DT  DATE,
    DEP_TRANS_TMSTAMP  TIMESTAMP(6),
    DEP_TMSTAMP        TIMESTAMP(6),
    COMMITMENT_TYPE    CHAR(1),
    ROW_STATUS         CHAR(1),
    FILE_DETAIL_ID     CHAR(2),
    AGREEMENT_NO       CHAR(5),
    CUSTOMER_CODE      CHAR(20),
    DATA_FIELD_2       CHAR(30),
    DATA_FIELD_1       CHAR(30),
    ACCOUNT2           CHAR(40),
    ENTRY_COMMENTS     CHAR(40),
    ACCOUNT1           CHAR(40),
    FILE_NAME          CHAR(50),
    DEP_TRANS_ERR_DESC VARCHAR(80)
);

create unique index I0000427
    on MG_CP_APPL_INTER (FILE_NAME, SERIAL_NO);

create unique index I0010441
    on MG_CP_APPL_INTER (SERIAL_NO, FILE_NAME);

