create table MG_CHEQUE_INTER
(
    DEP_TRN_STATUS     SMALLINT,
    PRFT_ACC_C_DIGIT   SMALLINT,
    BOUNCED_CNT        SMALLINT,
    ITEM_COUNT         INTEGER,
    CANRET_SN          INTEGER,
    ACCOUNT_NO_TAUT    INTEGER,
    PRFT_CARNET_SN     INTEGER,
    ACC_TRN_SERIAL_NO  INTEGER,
    SERIAL_NO          INTEGER,
    ITEM_SERIAL_NUMBER DECIMAL(10),
    LST_CHEQUE_NUMBER  DECIMAL(10),
    FST_CHEQUE_NUMBER  DECIMAL(10),
    PRFT_CHEQUE_SN     DECIMAL(10),
    PRFT_DEP_ACC_NO    DECIMAL(11),
    ITEM_CHEQUE_AMT    DECIMAL(15, 2),
    TRX_DATE           DATE,
    LAST_UPDATE_DATE   DATE,
    ITEM_ISSUE_DATE    DATE,
    ISSUE_DATE         DATE,
    BOUNCED_DATE       DATE,
    DEP_TRN_PROC_DT    DATE,
    DISHONOUR_DATE     DATE,
    DEP_TRN_TMSTAMP    TIMESTAMP(6),
    ITEM_CHEQUE_STS    CHAR(1),
    STOPPED_TYPE       CHAR(1),
    BOUNCED_REASON     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    COMMISSION_FLAG    CHAR(1),
    ROW_STATUS         CHAR(1),
    FILE_DETAIL_ID     CHAR(2),
    FILE_TYPE          CHAR(3),
    MG_ACCOUNT_TYPE    CHAR(5),
    ACCOUNT_NO         CHAR(40),
    FILE_NAME          CHAR(50),
    DEP_TRN_ERR_DESC   CHAR(80)
);

create unique index MGCHQ001
    on MG_CHEQUE_INTER (ACCOUNT_NO, CANRET_SN, ACC_TRN_SERIAL_NO);

create unique index MGCHQ002
    on MG_CHEQUE_INTER (DEP_TRN_STATUS);

create unique index MGCHQS_PK
    on MG_CHEQUE_INTER (FILE_NAME, SERIAL_NO);

