create table MG_CUSTOMER_INTER
(
    FILE_NAME          CHAR(50) not null,
    SERIAL_NO          INTEGER  not null,
    PRFT_CUST_C_DIGIT  SMALLINT,
    NUMBER_OF_CHILDREN SMALLINT,
    MONITORING_UNIT    INTEGER,
    PRFT_CUST_ID       INTEGER,
    ID_ISSUE_DATE      DATE,
    ROW_PROCESS_DATE   DATE,
    UDF_DATE3          DATE,
    UDF_DATE2          DATE,
    UDF_DATE1          DATE,
    CLASSIF_DATE       DATE,
    LEGAL_EXPIRE_DATE  DATE,
    TAX_CURR_EXPIRE_DT DATE,
    TIRESIA_ACCEPT_DT  DATE,
    DATE_OF_BIRTH      DATE,
    ID_EXPIRE_DATE     DATE,
    SEX                CHAR(1),
    ADDRESS_TYPE       CHAR(1),
    CITIZEN_STATUS     CHAR(1),
    TIRESIA_ACCEPTANCE CHAR(1),
    CUST_TYPE          CHAR(1),
    ROW_STATUS         CHAR(1),
    CBANK_CURR_CLASSIF CHAR(2),
    CURR_CLASSIF       CHAR(2),
    FILE_DETAIL_ID     CHAR(2),
    CUSTOMER_CD        CHAR(2),
    THINKING_CURRENCY  CHAR(5),
    ID_TYPE            CHAR(5),
    TITLE              CHAR(6),
    ZIP_CODE           CHAR(10),
    FAMILY_STATUS      CHAR(15),
    FAX_NO             CHAR(15),
    ID_ISSUER          CHAR(20),
    ID_NO              CHAR(20),
    FIRST_NAME         CHAR(20),
    REGISTR_AUTH_ID_NO CHAR(20),
    CUSTOMER_CODE      CHAR(20),
    AFM_NO             CHAR(20),
    AFM_TAX_OFFICE     CHAR(30),
    CITY               CHAR(30),
    ADDRESS_COUNTRY    CHAR(30),
    REGISTR_AUTH_CNTRY CHAR(30),
    CLASSIFIED_BY      CHAR(30),
    ALERT_MSG          CHAR(30),
    PRFST              CHAR(30),
    PROFF              CHAR(30),
    CCODE              CHAR(30),
    FINSC              CHAR(30),
    COMLANG            CHAR(30),
    CITIZEN            CHAR(30),
    NATIONAL           CHAR(30),
    BCOUNTRY           CHAR(30),
    LAWSHAPE           CHAR(30),
    ID_ISS_CNTRY       CHAR(30),
    MOTHER_SURNAME     CHAR(40),
    SURNAME            CHAR(70),
    UDF_TEXT4          CHAR(80),
    UDF_TEXT5          CHAR(80),
    UDF_TEXT6          CHAR(80),
    UDF_TEXT7          CHAR(80),
    ROW_ERR_DESC       CHAR(80),
    UDF_TEXT2          CHAR(80),
    UDF_TEXT1          CHAR(80),
    UDF_TEXT3          CHAR(80),
    TELEPHONE_COMMUN   VARCHAR(15),
    TELEPHONE_MOBILE   VARCHAR(15),
    TELEPHONE          VARCHAR(15),
    LATIN_NAME         VARCHAR(20),
    FATHER_NAME        VARCHAR(20),
    MOTHER_NAME        VARCHAR(20),
    WIFE_FULL_NAME     VARCHAR(40),
    ADDRESS            VARCHAR(80),
    E_MAIL             VARCHAR(64),
    LATIN_SURNAME      VARCHAR(70),
    UDF_TEXT8          CHAR(80),
    UDF_TEXT9          CHAR(80),
    UDF_TEXT10         CHAR(80),
    constraint IXU_MIG_022
        primary key (FILE_NAME, SERIAL_NO)
);

comment on column MG_CUSTOMER_INTER.UDF_TEXT8 is 'kps-605 will keep the Member_StatusCHAR(1)Value 1. MEMBER IS ACTIVE, 2. DORMANT, 3. CLOSED,  If the customer is NOT Member  then 0';

comment on column MG_CUSTOMER_INTER.UDF_TEXT9 is 'KPS-605 will keep the employee_id';

comment on column MG_CUSTOMER_INTER.UDF_TEXT10 is 'KPS-605 Will keep the Chamber_Id';

create unique index UNIC_CUST
    on MG_CUSTOMER_INTER (CUSTOMER_CODE);

