create table MG_COLL_INTER_NEW
(
    SERIAL_NO          INTEGER  not null,
    FILE_NAME          CHAR(50) not null,
    COLL_STATUS        SMALLINT,
    ACCOUNT2_SYSTEM    SMALLINT,
    ACCOUNT1_SYSTEM    SMALLINT,
    COOP_BANK_CODE     INTEGER,
    ACCOUNT_NO_TAUT    INTEGER,
    ENTRY_UNIT         INTEGER,
    INTERNAL_SN        DECIMAL(10),
    PRFT_COLLATERAL_SN DECIMAL(10),
    NUMBER1            DECIMAL(10),
    NUMBER2            DECIMAL(10),
    NUMBER3            DECIMAL(10),
    NUMBER10           DECIMAL(10),
    NUMBER9            DECIMAL(10),
    NUMBER8            DECIMAL(10),
    NUMBER4            DECIMAL(10),
    NUMBER6            DECIMAL(10),
    NUMBER7            DECIMAL(10),
    NUMBER5            DECIMAL(10),
    AMOUNT1            DECIMAL(15, 2),
    AMOUNT2            DECIMAL(15, 2),
    AMOUNT3            DECIMAL(15, 2),
    AMOUNT4            DECIMAL(15, 2),
    AMOUNT5            DECIMAL(15, 2),
    AMOUNT6            DECIMAL(15, 2),
    AMOUNT7            DECIMAL(15, 2),
    AMOUNT8            DECIMAL(15, 2),
    AMOUNT9            DECIMAL(15, 2),
    AMOUNT10           DECIMAL(15, 2),
    COL_EST_VALUE_AMN  DECIMAL(15, 2),
    COL_EST_INSUR_AMN  DECIMAL(15, 2),
    COL_VAL_FOR_CBANK  DECIMAL(15, 2),
    DATE9              DATE,
    DATE2              DATE,
    COLL_PROCESS_DATE  DATE,
    DATE3              DATE,
    DATE5              DATE,
    DATE1              DATE,
    ENTRY_DATE         DATE,
    DATE10             DATE,
    DATE4              DATE,
    DATE8              DATE,
    DATE7              DATE,
    DATE6              DATE,
    COLL_TMSTAMP       TIMESTAMP(6),
    FLAG1              CHAR(1),
    FLAG3              CHAR(1),
    COLLATERAL_USAGE   CHAR(1),
    FLAG2              CHAR(1),
    FLAG4              CHAR(1),
    FLAG5              CHAR(1),
    FLAG6              CHAR(1),
    ENTRY_STATUS       CHAR(1),
    ROW_STATUS         CHAR(1),
    FLAG10             CHAR(1),
    FLAG9              CHAR(1),
    FLAG8              CHAR(1),
    FLAG7              CHAR(1),
    FILE_DETAIL_ID     CHAR(2),
    CURRENCY_ISO       CHAR(3),
    COLLATERAL_TYPE    CHAR(5),
    ENTRY_USER         CHAR(8),
    CUSTOMER1_CODE     CHAR(20),
    BOND_CODE          CHAR(20),
    REAL_ESTATE_ID     CHAR(20),
    CUSTOMER2_CODE     CHAR(20),
    PARAMETER6         CHAR(30),
    PARAMETER5         CHAR(30),
    PARAMETER1         CHAR(30),
    PARAMETER2         CHAR(30),
    PARAMETER3         CHAR(30),
    PARAMETER4         CHAR(30),
    DESCRIPTION7       CHAR(40),
    DESCRIPTION8       CHAR(40),
    DESCRIPTION9       CHAR(40),
    DESCRIPTION10      CHAR(40),
    DESCRIPTION6       CHAR(40),
    DESCRIPTION5       CHAR(40),
    DESCRIPTION4       CHAR(40),
    DESCRIPTION3       CHAR(40),
    DESCRIPTION2       CHAR(40),
    DESCRIPTION1       CHAR(40),
    ACCOUNT2           CHAR(40),
    ACCOUNT1           CHAR(40),
    COLLATERAL_DESC    CHAR(40),
    COVERED_ACCOUNT    CHAR(40),
    COLLATERAL_SN      CHAR(40),
    TEXT1              CHAR(80),
    TEXT2              CHAR(80),
    TEXT3              CHAR(80),
    COLL_ERR_DESC      VARCHAR(80),
    AMOUNT_18_4_1      DECIMAL(18, 4),
    COMMENTS           VARCHAR(255),
    COUNTRY_COURT      CHAR(40),
    MORTGAGE_IND       CHAR(1),
    REQUIRED_IND       CHAR(1),
    YIELD_PERC         DECIMAL(8, 4),
    constraint IXU_MIG_014
        primary key (SERIAL_NO, FILE_NAME)
);

create unique index I0000382
    on MG_COLL_INTER_NEW (FILE_NAME, SERIAL_NO);

create unique index IX_COLLATERAL_SN
    on MG_COLL_INTER_NEW (COLLATERAL_SN);

