create table MG_CUST_DPAC_INTER
(
    FILE_NAME              CHAR(50) not null,
    SERIAL_NO              INTEGER  not null,
    DEP_ACC_STATUS         SMALLINT,
    DEP_TRANS_STATUS       SMALLINT,
    MULTI_CURR_ORDER       SMALLINT,
    PRFT_ACC_C_DIGIT       SMALLINT,
    ACC_UNIT_CODE          INTEGER,
    UDF_RATE1              DECIMAL(8, 4),
    UDF_RATE2              DECIMAL(8, 4),
    PRFT_DEP_ACC_NO        DECIMAL(11),
    ACC_LIMIT              DECIMAL(15, 2),
    UDF_NUM2               DECIMAL(15, 2),
    UDF_NUM1               DECIMAL(15, 2),
    DP_PROCESS_DATE        DATE,
    ACC_EXP_DT             DATE,
    DEP_TRANS_PROCESS_DATE DATE,
    UDF_DATE1              DATE,
    UDF_DATE2              DATE,
    OPENING_DATE           DATE,
    ACC_LIMIT_START_DT     DATE,
    ACC_LIMIT_REVISION     DATE,
    DEP_TRANS_TMSTAMP      TIMESTAMP(6),
    DEP_TMSTAMP            TIMESTAMP(6),
    TD_RENEWAL_FLG         CHAR(1),
    MULTI_CURR_FLAG        CHAR(1),
    ATM_CARD_FLAG          CHAR(1),
    ACCOUNT_CD             CHAR(2),
    STATEMENT_ISS_FREQ     CHAR(2),
    FILE_DETAIL_ID         CHAR(2),
    FILE_TYPE              CHAR(3),
    ACC_ID_CURRENCY        CHAR(5),
    MG_ACCOUNT_TYPE        CHAR(5),
    CUSTOMER_CODE          CHAR(20),
    CCODE                  CHAR(30),
    ACCOUNT_DEP_CATEG      CHAR(30),
    ACCOUNT_LOAN_CATEG     CHAR(30),
    LPUCB                  CHAR(30),
    LPURP                  CHAR(30),
    AGREEMENT_CODE         CHAR(40),
    ACCOUNT_NO             CHAR(40),
    SERVICE_ACCOUNT2       CHAR(40),
    GL_ACCOUNT_REF         CHAR(40),
    SERVICE_ACCOUNT1       CHAR(40),
    DEP_ERR_DESC           CHAR(80),
    UDF_TEXT2              CHAR(80),
    UDF_TEXT1              CHAR(80),
    DEP_TRANS_ERR_DESC     VARCHAR(80),
    RECYCLING_FRQ          SMALLINT,
    OLD_LNS_NO             CHAR(40),
    CUST_ADDRESS_SN        SMALLINT,
    TEMPORARY_EXCESS       DECIMAL(15, 2),
    TEMP_EXC_START_DT      DATE,
    TEMP_EXC_END_DT        DATE,
    ACCOUNT_OPEN_USER      CHAR(8),
    ACCOUNT_OFFICER        CHAR(8),
    CUST_STATUS            SMALLINT,
    CUST_ACTIONDESC        CHAR(20),
    CUST_ERR_DESC          CHAR(80),
    PRFT_CUST_ID           INTEGER,
    PRFT_CUST_C_DIGIT      INTEGER,
    CUST_PROCESS_DATE      DATE,
    ACCOUNT_NO_TAUT        INTEGER,
    SC_ACCOUNT_NO          INTEGER,
    SC_BENEFICIARY_SN      INTEGER,
    TMSTAMP                TIMESTAMP(6),
    SC_ACCOUNT_NO_TAUT     INTEGER,
    BENEFICIARY_SN         INTEGER,
    constraint IXU_MIG_019
        primary key (FILE_NAME, SERIAL_NO)
);

