create table MG_CMS
(
    FILE_NAME          CHAR(50)    not null,
    SN                 DECIMAL(10) not null,
    SEQUENCE_NO        CHAR(10),
    PAN                CHAR(19),
    PLASTIC            CHAR(5),
    NAME               CHAR(20),
    INSTITUTION_ID     CHAR(10),
    CARD_STATUS        CHAR(1),
    LAST_USED_DATE     CHAR(8),
    LIMIT_GROUP        CHAR(30),
    PIN_OFFSET_PVV     CHAR(16),
    DDA_PRIMARY        CHAR(28),
    SAV_PRIMARY        CHAR(28),
    ORIGINAL_ISSUE_DAT CHAR(8),
    FUNDING_ACCOUNT_NO CHAR(28),
    CARD_PRODUCT_ID    CHAR(30),
    CLIENT_ID_1        CHAR(20),
    DDA_2              CHAR(28),
    DDA_3              CHAR(28),
    DDA_4              CHAR(28),
    DDA_5              CHAR(28),
    DDA_6              CHAR(28),
    SAV_2              CHAR(28),
    SAV_3              CHAR(28),
    SAV_4              CHAR(28),
    SAV_5              CHAR(28),
    SAV_6              CHAR(28),
    CRD_1              CHAR(28),
    CRD_2              CHAR(28),
    CRD_3              CHAR(28),
    CRD_4              CHAR(28),
    FD_SURNAME         CHAR(20),
    FD_NAME            CHAR(20),
    FD_HOME_ADDRESS    CHAR(30),
    FD_HOME_TOWN       CHAR(20),
    FD_HOME_POST_CODE  CHAR(5),
    FD_HOME_PHONE_NO   CHAR(10),
    FD_EXPIRATION_DATE CHAR(8),
    FD_EMBOSS_NAME     CHAR(80),
    FD_PERS_FATHER     CHAR(20),
    FD_PERS_LATIN_NAME CHAR(40),
    FD_MOBILE_PHONE_NO CHAR(10),
    FD_CARD_MODE       CHAR(1),
    FD_HOME_ADDRESS_DE CHAR(20),
    FD_EMAIL_ADDRESS   CHAR(30),
    FLAG1              CHAR(1),
    FLAG2              CHAR(1),
    ROW_STATUS         CHAR(1),
    ROW_ERR_DESC       CHAR(80),
    CARD_TYPE_1        CHAR(1),
    PRIMARY_ACC_1      CHAR(40),
    PRIMARY_ACC_SYS_1  CHAR(1),
    ACCOUNT_2          CHAR(40),
    ACCOUNT_SYS_2      CHAR(1),
    ACCOUNT_3          CHAR(40),
    ACCOUNT_SYS_3      CHAR(1),
    ACCOUNT_4          CHAR(40),
    ACCOUNT_SYS_4      CHAR(1),
    ACCOUNT_5          CHAR(40),
    ACCOUNT_SYS_5      CHAR(1),
    ACCOUNT_6          CHAR(40),
    ACCOUNT_SYS_6      CHAR(1),
    ACCOUNT_7          CHAR(40),
    ACCOUNT_SYS_7      CHAR(1),
    ACCOUNT_8          CHAR(40),
    ACCOUNT_SYS_8      CHAR(1),
    ACCOUNT_9          CHAR(40),
    ACCOUNT_SYS_9      CHAR(1),
    ACCOUNT_10         CHAR(40),
    ACCOUNT_SYS_10     CHAR(1),
    RECORD_TYPE        CHAR(2),
    constraint PK_CMS_MIGR
        primary key (SN, FILE_NAME)
);

