create table MG_CUST_DPAC_INTER_XXX
(
    FILE_NAME              CHAR(50) not null,
    FILE_TYPE              CHAR(3),
    FILE_DETAIL_ID         CHAR(2),
    SERIAL_NO              INTEGER  not null,
    ACCOUNT_NO_TAUT        INTEGER  not null,
    ACCOUNT_NO             CHAR(40) not null,
    ACCOUNT_CD             CHAR(2),
    BENEFICIARY_SN         SMALLINT not null,
    MG_ACCOUNT_TYPE        CHAR(5),
    ACC_ID_CURRENCY        CHAR(5),
    ACC_UNIT_CODE          INTEGER,
    SC_ACCOUNT_NO_TAUT     INTEGER,
    SC_ACCOUNT_NO          CHAR(40),
    SC_BENEFICIARY_SN      SMALLINT,
    CUSTOMER_CODE          CHAR(20),
    BENEFICIARY_TYPE       CHAR(1),
    CUST_TYPE              CHAR(1),
    TITLE                  CHAR(6),
    FIRST_NAME             CHAR(20),
    SURNAME                CHAR(70),
    FATHER_NAME            VARCHAR(20),
    WIFE_FULL_NAME         VARCHAR(40),
    MOTHER_NAME            VARCHAR(20),
    MOTHER_SURNAME         CHAR(40),
    LATIN_NAME             VARCHAR(20),
    LATIN_SURNAME          VARCHAR(70),
    DATE_OF_BIRTH          DATE,
    BCOUNTRY               CHAR(30),
    SEX                    CHAR(1),
    ID_TYPE                CHAR(5),
    ID_NO                  CHAR(20),
    ID_ISSUE_DATE          DATE,
    ID_ISSUER              CHAR(20),
    ID_EXPIRE_DATE         DATE,
    ID_ISS_CNTRY           CHAR(30),
    AFM_NO                 CHAR(20),
    AFM_TAX_OFFICE         CHAR(30),
    ADDRESS1               VARCHAR(40),
    CITY1                  CHAR(30),
    ZIP_CODE1              CHAR(10),
    ADDRESS_COUNTRY1       CHAR(30),
    ADDRESS_TYPE1          CHAR(1),
    ADDRESS2               VARCHAR(40),
    CITY2                  CHAR(30),
    ZIP_CODE2              CHAR(10),
    ADDRESS_COUNTRY2       CHAR(30),
    ADDRESS_TYPE2          CHAR(1),
    TELEPHONE_1            VARCHAR(15),
    TELEPHONE_COMMUN       VARCHAR(15),
    TELEPHONE_MOBILE       VARCHAR(15),
    FAX_NO                 CHAR(15),
    E_MAIL                 VARCHAR(64),
    NATIONAL               CHAR(30),
    CITIZEN                CHAR(30),
    COMLANG                CHAR(30),
    FAMILY_STATUS          CHAR(15),
    NUMBER_OF_CHILDREN     SMALLINT,
    FINSC                  CHAR(30),
    CCODE                  CHAR(30),
    PROFF                  CHAR(30),
    PRFST                  CHAR(30),
    MONITORING_UNIT        INTEGER,
    THINKING_CURRENCY      CHAR(5),
    CITIZEN_STATUS         CHAR(1),
    ALERT_MSG              CHAR(30),
    TIRESIA_ACCEPTANCE     CHAR(1),
    TIRESIA_ACCEPT_DT      DATE,
    TAX_CURR_EXPIRE_DT     DATE,
    LEGAL_EXPIRE_DATE      DATE,
    REGISTR_AUTH_ID_NO     CHAR(20),
    REGISTR_AUTH_CNTRY     CHAR(30),
    OFFICE_ADDRESS         CHAR(40),
    OFFICE_CITY            CHAR(30),
    OFFICE_ADDR_CNTRY      CHAR(30),
    LAWSHAPE               CHAR(30),
    CLASSIF_DATE           DATE,
    CLASSIFIED_BY          CHAR(30),
    CURR_CLASSIF           CHAR(2),
    CBANK_CURR_CLASSIF     CHAR(2),
    ACCOUNT_LOAN_CATEG     CHAR(30),
    ATM_CARD_FLAG          CHAR(1),
    OPENING_DATE           DATE,
    ACCOUNT_DEP_CATEG      CHAR(30),
    STATEMENT_ISS_FREQ     CHAR(2),
    AGREEMENT_CODE         CHAR(40),
    AGREEMENT_CD           CHAR(2),
    AGR_LIMIT              DECIMAL(15, 2),
    AGR_CURR_SHORT_DESC    CHAR(5),
    ACC_OFFICER            CHAR(8),
    OFF_ASGN_DT            DATE,
    DEL_OFFICER            CHAR(8),
    DEL_OFF_ASN_DT         DATE,
    VILLA                  CHAR(30),
    AGR_SIGNING_DT         DATE,
    SERVICE_ACCOUNT1       CHAR(40),
    SERVICE_ACCOUNT2       CHAR(40),
    ACC_LIMIT              DECIMAL(15, 2),
    ACC_LIMIT_START_DT     DATE,
    ACC_LIMIT_REVISION     DATE,
    EXP_CURR_SHORT_DESC    CHAR(5),
    LPURP                  CHAR(30),
    BSECT                  CHAR(30),
    LPUCB                  CHAR(30),
    STATEMENT_FREQ         CHAR(1),
    DORG                   CHAR(30),
    DRAWDOWN_EXP_DT        DATE,
    INSTALL_COUNT          SMALLINT,
    INSTALL_FREQ           SMALLINT,
    INTER_CAPITALIZE_FLG   CHAR(1),
    MORATORIUM_INT_FRQ     SMALLINT,
    POSOTIVE_AMN           DECIMAL(15, 2),
    DORMANT_AMN            DECIMAL(15, 2),
    UNCLEAR_AMN            DECIMAL(15, 2),
    ACC_OPEN_DT            DATE,
    ACC_EXP_DT             DATE,
    LG_COMM_FREQ           SMALLINT,
    LG_COMM_FREQ_TYPE      CHAR(1),
    LG_NEXT_COMM_DT        DATE,
    LG_TYPE                INTEGER,
    LG_EXPIRE_TYPE         CHAR(1),
    LG_EXPIRE_DATE         DATE,
    LG_INITIAL_AMN         DECIMAL(15, 2),
    LG_CURRENT_AMN         DECIMAL(15, 2),
    LG_PURPOSE1            VARCHAR(80),
    LG_PURPOSE2            VARCHAR(80),
    LG_PURPOSE3            VARCHAR(80),
    LG_GUARANT_TYPE        CHAR(30),
    LG_GUARANT_CODE        CHAR(10),
    PTS_REGISTRY           CHAR(11),
    PTS_ACCOUNT            CHAR(11),
    INT1_CODE              CHAR(30),
    INT1_SCALE_DT          DATE,
    INT1_EXPIRE_DT         DATE,
    SPREAD1_RATE           DECIMAL(8, 4),
    SPREAD1_START_DT       DATE,
    SPREAD1_EXPIRE_DT      DATE,
    INT2_CODE              CHAR(30),
    INT2_SCALE_DT          DATE,
    INT2_EXPIRE_DT         DATE,
    SPREAD2_RATE           DECIMAL(8, 4),
    SPREAD2_START_DT       DATE,
    SPREAD2_EXPIRE_DT      DATE,
    INT3_CODE              CHAR(30),
    LG_COM_MINIMUM_AMN     DECIMAL(15, 2),
    LG_COM_PERC_ON_AMN     DECIMAL(8, 4),
    LG_COM_DISCOUNT        DECIMAL(8, 4),
    LG_COM_CALC_TYPE       CHAR(1),
    TMSTAMP                TIMESTAMP(6),
    TRX_USER               CHAR(8),
    TRX_UNIT               INTEGER,
    TRX_DATE               DATE,
    TRX_USR_SN             INTEGER,
    ONLINE_PROCESS_DATE    DATE,
    PRFT_CUST_ID           INTEGER,
    PRFT_CUST_C_DIGIT      SMALLINT,
    LNS_TRANS_TMSTAMP      TIMESTAMP(6),
    LNS_TRANS_PROCESS_DATE DATE,
    LNS_TRANS_ERR_DESC     VARCHAR(80),
    LNS_TRANS_STATUS       SMALLINT,
    LNS_ERR_DESC           CHAR(80),
    LNS_TMSTAMP            TIMESTAMP(6),
    LNS_PROCESS_DATE       DATE,
    LNS_STATUS             SMALLINT,
    DEP_TRANS_TMSTAMP      TIMESTAMP(6),
    DEP_TRANS_PROCESS_DATE DATE,
    DEP_TRANS_ERR_DESC     VARCHAR(80),
    DEP_TRANS_STATUS       SMALLINT,
    DEP_TMSTAMP            TIMESTAMP(6),
    DEP_ACC_STATUS         SMALLINT,
    DP_PROCESS_DATE        DATE,
    DEP_ERR_DESC           CHAR(80),
    TRACCOUNT_STATUS       SMALLINT,
    TRACCOUNT_ERR_DESC     CHAR(80),
    TRACCOUNT_TMSTAMP      TIMESTAMP(6),
    TRACCOUNT_PRS_DT       DATE,
    PRFT_ACC_C_DIGIT       SMALLINT,
    PRFT_DEP_ACC_NO        DECIMAL(11),
    CUST_PROCESS_DATE      DATE,
    CUST_ERR_DESC          CHAR(80),
    CUST_ACTIONDESC        CHAR(20),
    CUST_STATUS            SMALLINT,
    MORATOR_NRM_RATE       DECIMAL(9, 6),
    MORATOR_N128_RATE      DECIMAL(9, 6),
    MORATOR_SUBS_RATE      DECIMAL(9, 6),
    MORATOR_SPR_RATE       DECIMAL(9, 6),
    RECYCLING_FRQ          SMALLINT,
    TD_AUTONUM_CREATE      CHAR(1),
    PRFT_TRACC_UNIT        INTEGER,
    PRFT_TRACC_TYPE        SMALLINT,
    PRFT_TRACC_SN          INTEGER,
    PRFT_TRACC_CD          SMALLINT,
    TR_TRANS_STATUS        SMALLINT,
    TR_TRANS_ERR_DESC      CHAR(80),
    TR_TRANS_PROCESS_DATE  DATE,
    TR_TRANS_TMSTAMP       DATE,
    AGR_UNIT               INTEGER,
    AGR_YEAR               SMALLINT,
    AGR_SN                 INTEGER,
    AGR_MEMBERSHIP_SN      INTEGER,
    LG_ACC_SN              DECIMAL(13),
    OLD_BENEFICIARY_SN     SMALLINT,
    OLD_ACC_NUMBER         CHAR(20),
    LNS_TRN_STATUS         SMALLINT,
    LNS_TRN_TMSTAMP        TIMESTAMP(6),
    LNS_TRN_ERR_DESC       CHAR(80),
    CUR_FX_INT_EXP_DT      DATE,
    LNS_TRN_PROCESS_DATE   DATE,
    LNS_CURR_SHORT_DESC    CHAR(5),
    XCUR_FX_INT_EXP_DT     DATE,
    XADDRESS_1             VARCHAR(40),
    XADDRESS_2             VARCHAR(40),
    XOCCUPATION_CODE       SMALLINT,
    XMIDDLE_NAME           VARCHAR(15),
    constraint MG_CUST_DPAC_INTER_PK
        primary key (FILE_NAME, SERIAL_NO)
);

