create table MG_EMTE_STEP_UP_ACCOUNTS
(
    ACCOUNT_NUMBER CHAR(40) not null,
    ACCOUNT_SYSTEM SMALLINT not null,
    TMSTAMP        TIMESTAMP(6)
);

create unique index MG_EMTE_STEP_UP_ACCOUNTS_INDEX
    on MG_EMTE_STEP_UP_ACCOUNTS (ACCOUNT_NUMBER, ACCOUNT_SYSTEM);

