create table MG_EMTE_STEP_UP_INSTALLMENTS
(
    ACCOUNT_NUMBER     CHAR(40) not null,
    ACCOUNT_SYSTEM     SMALLINT not null,
    INSTALLMENT_DATE   DATE     not null,
    REMAINING_CAPITAL  DECIMAL(15, 2),
    INSTALLMENT        DECIMAL(15, 2),
    INSTALLMENT_CAP    DECIMAL(15, 2),
    INSTALLMENT_INT    DECIMAL(15, 2),
    INSTALLMENT_N128   DECIMAL(15, 2),
    AMOUNT_CAPITALIZED DECIMAL(15, 2),
    AMOUNT_SUBSIDIZED  DECIMAL(15, 2),
    ENTRY_STATUS       CHAR(1),
    PROCESSED_STATUS   CHAR(1),
    ERROR_DESCRIPTION  VARCHAR(100),
    TMSTAMP            TIMESTAMP(6)
);

create unique index MG_EMTE_STEP_UP_INSTALL_INDEX
    on MG_EMTE_STEP_UP_INSTALLMENTS (ACCOUNT_NUMBER, ACCOUNT_SYSTEM, INSTALLMENT_DATE);

