create table MG_IPS_MESSAGE_STAGE
(
    FILE_NAME                    CHAR(50)    not null,
    SERIAL_NO                    DECIMAL(10) not null,
    OTHER_SYSTEM_ID              CHAR(20),
    MIGR_STATUS                  CHAR(1),
    MIGR_ERROR_DESC              CHAR(80),
    MIGR_TIMESTAMP               TIMESTAMP(6),
    BENEF_FULLNAME               VARCHAR(100),
    BENEF_ADDRESS_LINE_1         VARCHAR(100),
    BENEF_ADDRESS_LINE_2         VARCHAR(100),
    BENEF_ADDRESS_POST_CODE      VARCHAR(10),
    BENEF_ADDRESS_COUNTRY        VARCHAR(2),
    BENEF_RESIDENT               VARCHAR(1),
    BENEF_IDENTIFICATION_TYPE    VARCHAR(5),
    BENEF_IDENTIFICATION_VALUE   VARCHAR(20),
    BENEF_BIC_ADDRESS            VARCHAR(12),
    BENEF_BANK_ACCOUNT           VARCHAR(40),
    ORDER_REMMITANCE_INFO        VARCHAR(140),
    ORDER_CHARGE_BEARER          VARCHAR(4),
    ORDER_INSTR_NEXT_AGENT_3     VARCHAR(1),
    ORDER_INSTRUMENT_JUSTIFIC_ID INTEGER,
    ORDER_INSTRUMENT_CODE        CHAR(10),
    ORDER_CLEARING_SYSTEM        CHAR(11),
    ORDER_PURPOSE_CODE           CHAR(35),
    constraint I0000202
        primary key (SERIAL_NO, FILE_NAME)
);

