create table MG_LNS_MNT_LOAD
(
    SERIAL_NO            INTEGER  not null,
    FILE_NAME            CHAR(50) not null,
    LNS_TRN_STATUS       SMALLINT,
    NEW_ACC_TYPE         SMALLINT,
    RECYCLING_FRQ        SMALLINT,
    MIG_STATUS           SMALLINT,
    NEW_ACC_CD           SMALLINT,
    MORATORIUM_INT_FRQ   SMALLINT,
    INSTALL_COUNT        SMALLINT,
    INSTALL_FREQ         SMALLINT,
    REF_LPUCB_CODE       INTEGER,
    ID_PRODUCT           INTEGER,
    MOVE_CURRENCY_ID     INTEGER,
    CHARGE_CURRENCY_ID   INTEGER,
    LIMIT_CURRENCY_ID    INTEGER,
    REF_FINSC_CODE       INTEGER,
    REF_CCODE_CODE       INTEGER,
    REF_CBPURP_CODE      INTEGER,
    REF_BSECT_CODE       INTEGER,
    REF_CLOAN_CODE       INTEGER,
    REF_LPURP_CODE       INTEGER,
    FUT_INTER_ID         INTEGER,
    FLOATING_INT_ID      INTEGER,
    CUR_FX_INTER_ID      INTEGER,
    NEW_ACC_UNIT         INTEGER,
    ACC_UNIT             INTEGER,
    NEW_ACC_SN           INTEGER,
    CR_INT_SPRD          DECIMAL(8, 4),
    FUT_FX_INT_PERC      DECIMAL(8, 4),
    FUT_INT_SPRD         DECIMAL(8, 4),
    FLOATING_INT_PERC    DECIMAL(8, 4),
    UDF_RATE1            DECIMAL(8, 4),
    UDF_RATE2            DECIMAL(8, 4),
    CUR_FX_INT_PERC      DECIMAL(8, 4),
    ACC_LIMIT_AMN        DECIMAL(15, 2),
    POSITIVE_AMN         DECIMAL(15, 2),
    UNCLEAR_AMN          DECIMAL(15, 2),
    UDF_NUM1             DECIMAL(15, 2),
    UDF_NUM2             DECIMAL(15, 2),
    DORMANT_AMN          DECIMAL(15, 2),
    CUR_FX_INT_EXP_DT    DATE,
    DRAWDOWN_EXP_DT      DATE,
    ACC_EXP_DT           DATE,
    ACC_OPEN_DT          DATE,
    LNS_TRN_PROCESS_DT   DATE,
    NEW_ACC_EXP_DT       DATE,
    ROW_PROCESS_DATE     DATE,
    LNS_TRN_PROCESS_DATE DATE,
    CC_INSTALL_NEXT_DT   DATE,
    CC_INSTALL_FIRST_DT  DATE,
    UDF_DATE2            DATE,
    UDF_DATE1            DATE,
    FUT_SPRD_END_DT      DATE,
    FUT_SPRD_ST_DT       DATE,
    FUT_FX_INT_SCAL_DT   DATE,
    FUT_FX_INT_EXP_DT    DATE,
    CUR_FX_INT_SCAL_DT   DATE,
    CR_SPRD_END_DT       DATE,
    CR_SPRD_ST_DT        DATE,
    LNS_TRN_TMSTAMP      TIMESTAMP(6),
    INT_CAPITAL_FLG      CHAR(1),
    USE_FIXED            CHAR(1),
    INTER_CAPITALIZE_F   CHAR(1),
    ROW_STATUS           CHAR(1),
    STATEMENT_FREQ       CHAR(1),
    INT_PAYABLE_FLG      CHAR(1),
    ACCOUNT_CD           CHAR(2),
    FILE_TYPE            CHAR(3),
    MG_ACCOUNT_TYPE      CHAR(5),
    MOVE_CURRENCY        CHAR(5),
    LIMIT_CURRENCY       CHAR(5),
    CHARGE_CURRENCY      CHAR(5),
    CUR_FX_INTER_CODE    CHAR(20),
    FUT_FX_INTER_CODE    CHAR(20),
    FLOATING_INT_CODE    CHAR(20),
    CUSTOMER_CODE        CHAR(20),
    LPURP                CHAR(30),
    BSECT                CHAR(30),
    LPUCB                CHAR(30),
    CLOAN                CHAR(30),
    FINSC                CHAR(30),
    CCODE                CHAR(30),
    OLD_LNS_NO           CHAR(40),
    GL_ACCOUNT_REF       CHAR(40),
    AGREEMENT_CODE       CHAR(40),
    DEP_ACCOUNT_NO       CHAR(40),
    ACC_DESCRIPTION      CHAR(40),
    LNS_TRN_ERR_DESC     CHAR(80),
    UDF_TEXT1            CHAR(80),
    UDF_TEXT2            CHAR(80),
    ROW_ERR_DESC         CHAR(80),
    NEW_DEP_ACC_SN       DECIMAL(11),
    constraint IXU_MIG_027
        primary key (SERIAL_NO, FILE_NAME)
);

create unique index BUS0001
    on MG_LNS_MNT_LOAD (OLD_LNS_NO, AGREEMENT_CODE);

