create table MG_TF_STATIC
(
    FILE_NAME                 CHAR(50)    not null,
    SERIAL_NO                 DECIMAL(10) not null,
    MIGR_STATUS               CHAR(1),
    MIGR_ERROR_DESC           CHAR(80),
    MIGR_TIMESTAMP            TIMESTAMP(6),
    LEGACY_SYSTEM             CHAR(40),
    TYPE                      CHAR(1),
    STATUS                    CHAR(1),
    ISS_BEN_CUST              CHAR(20),
    ISS_BEN_DEP_ACC           CHAR(40),
    BEN_ISS_CUST_NAME         CHAR(80),
    BEN_ISS_CUST_ADDR         CHAR(40),
    BEN_ISS_CUST_ACC          CHAR(40),
    PRODUCT                   CHAR(5),
    OPENING_UNIT              INTEGER,
    MONITORING_UNIT           INTEGER,
    AMOUNT                    DECIMAL(15, 2),
    UTILIZED_AMOUNT           DECIMAL(15, 2),
    ISSUED_AMOUNT             DECIMAL(15, 2),
    CURRENCY                  CHAR(5),
    CLOSING_LOCATION          CHAR(20),
    EXPIRATION_DATE           DATE,
    APPLICABLE_RULES          SMALLINT,
    LAST_SHIPMENT_DATE        DATE,
    LC_TYPE                   SMALLINT,
    SETTLEMENT_TYPE           SMALLINT,
    CENTRAL_BANK_PRODUCT_CODE CHAR(30),
    COUNTRY_OF_ORIGIN         CHAR(30),
    REFERENCE_NUMBER          CHAR(40),
    CONFIRMED                 CHAR(1),
    IRREVOCABLE               CHAR(1),
    PARTIAL_SHIPMENTS         CHAR(1),
    TRANSHIPMENT              CHAR(1),
    ASSIGN_OF_PROCEED         CHAR(1),
    RED_CLAUSE                CHAR(1),
    REVORVING_LIMIT           CHAR(1),
    COLLECTING_ISSUING_BANK   CHAR(11),
    REMITTING_ADVISING_BANK   CHAR(11),
    NEGOTIATING_BANK          CHAR(11),
    CONFIRMING_BANK           CHAR(11),
    AGR_NO_INC_REF            CHAR(40),
    CORRESPONDENT_CUSTOMER    CHAR(20),
    CORRESPONDENT_ACCOUNT     CHAR(40),
    TENOR                     SMALLINT,
    CHRG_COMM_FRQ             SMALLINT,
    CHRG_COMM_FRQT            CHAR(1),
    COMMENTS                  CHAR(80),
    TFLC_ACC                  CHAR(40),
    DOCS_REQ_1                CHAR(80),
    DOCS_REQ_2                CHAR(80),
    DOCS_REQ_3                CHAR(80),
    DOCS_REQ_4                CHAR(80),
    DOCS_REQ_5                CHAR(80),
    DOCS_REQ_6                CHAR(80),
    DOCS_REQ_7                CHAR(20),
    ADD_COND_1                CHAR(80),
    ADD_COND_2                CHAR(80),
    ADD_COND_3                CHAR(80),
    ADD_COND_4                CHAR(80),
    ADD_COND_5                CHAR(80),
    ADD_COND_6                CHAR(80),
    ADD_COND_7                CHAR(20),
    DRAWEE_1                  CHAR(70),
    DRAWEE_2                  CHAR(70),
    CHARGES_1                 CHAR(70),
    CHARGES_2                 CHAR(70),
    CHARGES_3                 CHAR(70),
    DESC_GOODS_1              CHAR(80),
    DESC_GOODS_2              CHAR(80),
    DESC_GOODS_3              CHAR(80),
    DESC_GOODS_4              CHAR(80),
    DESC_GOODS_5              CHAR(80),
    DESC_GOODS_6              CHAR(80),
    DESC_GOODS_7              CHAR(20),
    INCO_TERMS                SMALLINT,
    PER_PRES_1                CHAR(70),
    PER_PRES_2                CHAR(70),
    SEND_TO_REC_1             CHAR(70),
    SEND_TO_REC_2             CHAR(70),
    SEND_TO_REC_3             CHAR(70),
    SHIPM_INFO_LOAD           CHAR(65),
    SHIPM_INFO_DEST           CHAR(65),
    constraint PK_MG_TF_STATIC
        primary key (SERIAL_NO, FILE_NAME)
);

