create table MG_USERS
(
    FILE_NAME           CHAR(50) not null,
    SERIAL_NO           INTEGER  not null,
    USERID              INTEGER,
    CUSTID              CHAR(10),
    CUSTID_CD           SMALLINT,
    APPLICATIONID       SMALLINT,
    ROLEID              SMALLINT,
    USERNAME            CHAR(20),
    PASSWORD            CHAR(5),
    EMAIL               VARCHAR(256),
    ACTIVE              SMALLINT,
    LOCKED              SMALLINT,
    CREATEDATE          DATE,
    LASTLOGIN           DATE,
    LASTUSERNAMECHANGED DATE,
    LASTPSWCHANGED      DATE,
    LASTLOCKEDDATE      DATE,
    COMMENTS            VARCHAR(256),
    LASTACTIVITYDATE    DATE,
    ISLEGAL             CHAR(1),
    FIRST_NAME          CHAR(30),
    LATIN_FIRST_NAME    CHAR(30),
    SURNAME             CHAR(70),
    LATIN_SURNAME       CHAR(70),
    COMPANY_CUSTID      CHAR(10),
    COMPANY_CUSTID_CD   SMALLINT,
    COMPANY_NAME        CHAR(80),
    COMPANY_BRANDNAME   CHAR(80),
    FATHER_NAME         CHAR(30),
    MOTHER_NAME         CHAR(30),
    ADDRESS             CHAR(50),
    LATIN_ADDRESS       CHAR(50),
    ZIP                 CHAR(10),
    CITY                CHAR(30),
    COUNTRY             CHAR(2),
    PHONE               CHAR(15),
    MOBILE              CHAR(15),
    BIRTHDATE           DATE,
    PROFESSION          CHAR(50),
    ID_TYPE             SMALLINT,
    ID_VALUE            CHAR(20),
    MASTER_USERID       INTEGER,
    ROW_STATUS          SMALLINT not null,
    ROW_TMSTAMP         DATE,
    ROW_ERR_DESC        CHAR(80),
    ROW_PROCESS_DATE    DATE,
    constraint PK_MG_USERS
        primary key (SERIAL_NO, FILE_NAME)
);

