create table MIG_DEP_CROSS_CHECK
(
    TOTAL_FIN_COUNT    DECIMAL(10),
    TOTAL_STATIC_COUNT DECIMAL(10),
    MIG_DEBIT_ACCRUAL  DECIMAL(15, 2),
    MIG_CREDIT_ACCRUAL DECIMAL(15, 2),
    DEBIT_ACCRUAL      DECIMAL(15, 2),
    CREDIT_ACCRUAL     DECIMAL(15, 2),
    FIN_FAIL_COUNT     DECIMAL(10),
    FIN_PASS_COUNT     DECIMAL(10),
    STATIC_FAIL_COUNT  DECIMAL(10),
    STATIC_PASS_COUNT  DECIMAL(10),
    MIGR_LIMIT         DECIMAL(15, 2),
    DEP_LIMIT          DECIMAL(15, 2),
    MIGR_BALANCE       DECIMAL(15, 2),
    DEP_BALANCE        DECIMAL(15, 2),
    PRODUCT            CHAR(5) not null
        constraint MIG_DEP_CROSS_CHECK_PKEY
            primary key
);

