create table MIGR_TP_SO_COMMITMENT
(
    FILE_NAME                  CHAR(50)    not null,
    SERIAL_NO                  DECIMAL(10) not null,
    ROW_STATUS                 SMALLINT,
    ROW_ERR_DESC               CHAR(80),
    ROW_PROCESS_DATE           DATE,
    ROW_TMSTAMP                TIMESTAMP(6),
    UTF_TEXT1                  CHAR(80),
    UTF_TEXT2                  CHAR(80),
    UTF_TEXT3                  CHAR(80),
    UTF_DATE1                  DATE,
    UTF_DATE2                  DATE,
    UTF_NUM1                   DECIMAL(15),
    UTF_NUM2                   DECIMAL(15),
    DESCRIPTION                CHAR(40),
    ACTIVATION_DATE            DATE,
    MAX_NUM_OF_ATTEMPS         SMALLINT,
    ENTRY_STATUS               CHAR(1),
    FIRST_PAYMENT_DATE         DATE,
    LAST_PAYMENT_DATE          DATE,
    FREQUENCY_UNIT             CHAR(1),
    CR_DR_INDICATOR            CHAR(1),
    PAYMENT_AMOUNT             DECIMAL(15, 2),
    CREDIT_ACC_COMMENTS        CHAR(40),
    DEBIT_ACC_COMMENTS         CHAR(40),
    SO_METHOD                  CHAR(1),
    SO_INDICATOR               CHAR(1),
    DR_CUSTOMER_ID             INTEGER,
    CR_CUSTOMER_ID             INTEGER,
    FIRST_PAYMENT_AMOUNT       DECIMAL(15, 2),
    LAST_PAYMENT_AMOUNT        DECIMAL(15, 2),
    SUSPENSION_DATE_FROM       DATE,
    SUSPENSION_DATE_TO         DATE,
    SUSPENSION_EXECUTION       CHAR(1),
    PRIVILIGED_FLAG            CHAR(1),
    CR_BONUS_DISC_COMM         DECIMAL(8, 4),
    DEBIT_CHARGES_INDICATOR    CHAR(1),
    CREDIT_CHARGES_INDICATOR   CHAR(1),
    ACCOUNT_TYPE               CHAR(1),
    DEBIT_ACCOUNT_CURRENCY     INTEGER,
    CREDIT_ACCOUNT_CURRENCY    INTEGER,
    INSUFF_CHARGE_CODE         INTEGER,
    INSUFF_CHARGE_DISC         DECIMAL(8, 4),
    CR_BONUS_COMM_CODE         INTEGER,
    FREQUENCY                  SMALLINT,
    CHARGES_DISC_PERCENTAGE    DECIMAL(8, 4),
    COMM_DISC_PERCENTAGE       DECIMAL(8, 4),
    ALLOWED_UNSUCCESSFUL_TRIES INTEGER,
    TOTAL_AVAILABLE_TRIES      INTEGER,
    TOTAL_AMOUNT               DECIMAL(15, 2),
    CREDIT_CHARGE_TYPE         CHAR(1),
    DEBIT_ACCOUNT_NUMBER       CHAR(40),
    DEBIT_JUSTIFIC_ID          INTEGER,
    CREDIT_ACCOUNT_NUMBER      CHAR(40),
    CREDIT_JUSTIFIC_ID         INTEGER,
    RESPONSIBLE_UNIT           INTEGER,
    OTHER_SYS_IDENTIFIER       CHAR(20),
    CR_CUSTOMER_CODE           CHAR(20),
    DR_CUSTOMER_CODE           CHAR(20),
    constraint PK_MIGR_TP_SO_COMMITMENT
        primary key (SERIAL_NO, FILE_NAME)
);

