create table MOF_OUTACCREG_REQ
(
    PRFT_SERIAL_NUM    DECIMAL(10) not null
        constraint PK_OUTACCREG_RQ
            primary key,
    PRFT_CUST_ID       INTEGER,
    PRFT_MSG_TYPE      CHAR(2),
    PRFT_REQUEST_ID    CHAR(12)    not null,
    PRFT_EOP_STRING    CHAR(10),
    PRFT_TAXID         CHAR(9),
    PRFT_SURNAME_TITLE CHAR(70),
    PRFT_FIRST_NAME    CHAR(20),
    PRFT_FATHERNAME    CHAR(20),
    PRFT_MOTHERNAME    CHAR(20),
    PRFT_BIRTH_DATE    CHAR(10),
    PRFT_IDDOC_TYPE    CHAR(2),
    PRFT_IDDOC_NUM     CHAR(20),
    PRFT_ACCOUNT_NUM   CHAR(27),
    PRFT_IBAN          CHAR(27),
    PRFT_COBENEFS      SMALLINT,
    PRFT_ACC_STATUS    CHAR(1),
    PRFT_ACC_OPEN_DT   DATE,
    PRFT_CLOSURE_DT    DATE,
    PRFT_ACC_TYPE      CHAR(1),
    PRFT_ACC_CURR      CHAR(3),
    PRFT_BOOK_BALANCE  DECIMAL(18, 2),
    PRFT_DBCR_BOOK_IND CHAR(1),
    PRFT_AVAIL_BALANCE DECIMAL(18, 2),
    PRFT_DBCR_AVL_IND  CHAR(1),
    TMSTAMP            TIMESTAMP(6),
    PRFT_DEPLSTRX_DT   DATE
);

