create table MONTRAN_IN
(
    FILE_NAME        CHAR(50)    not null,
    IN_KEY           DECIMAL(10) not null,
    SUM_SV           DECIMAL(15, 2),
    SUM              DECIMAL(15, 2),
    REFERENCE_NUMBER DECIMAL(15),
    UN_NOM           DECIMAL(15, 2),
    PRFT_INSERTED_DT TIMESTAMP(6),
    PRFT_CREATED_DT  TIMESTAMP(6),
    Z_R              CHAR(1),
    PDK              CHAR(1),
    BIRJA            CHAR(1),
    PRFT_PROCESS_FLG CHAR(1),
    VOBR             CHAR(1),
    VOP              CHAR(2),
    POR_E            CHAR(3),
    POR              CHAR(3),
    N_ORGD           CHAR(3),
    N_ORGB           CHAR(3),
    N_ORGA           CHAR(3),
    BANK_B           CHAR(3),
    BANK_D           CHAR(3),
    BANK_A           CHAR(3),
    NDOC_SV          CHAR(4),
    NDOC             CHAR(4),
    B_DATE           CHAR(6),
    DATE_SV          CHAR(6),
    REC_DATE         CHAR(6),
    MDATE            CHAR(6),
    DRO              CHAR(8),
    NLS              CHAR(9),
    SAXAZKOD         CHAR(9),
    PIRV_DOK         CHAR(9),
    NFA              CHAR(9),
    NFB              CHAR(9),
    NLSK             CHAR(9),
    MIK              CHAR(11),
    GIK              CHAR(11),
    EL_X1            CHAR(25),
    EL_X2            CHAR(25),
    SIGNFLDC         CHAR(32),
    NLSK_AX          CHAR(34),
    NLS_AX           CHAR(34),
    MB               CHAR(50),
    GB               CHAR(50),
    M_O              CHAR(60),
    G_O              CHAR(60),
    THP_NAME         CHAR(60),
    ZXZ3             CHAR(64),
    GD               VARCHAR(190),
    DAMINF           VARCHAR(250),
    constraint IXU_FX_017
        primary key (FILE_NAME, IN_KEY)
);

