create table MONTHDAY_SEQ
(
    MONTHDATE_SEQ_NO SMALLINT,
    FLAG_01          SMALLINT,
    FLAG_02          SMALLINT,
    FLAG_03          SMALLINT,
    FLAG_04          SMALLINT,
    FLAG_05          SMALLINT,
    FLAG_06          SMALLINT,
    FLAG_07          SMALLINT,
    FLAG_08          SMALLINT,
    FLAG_09          SMALLINT,
    FLAG_10          SMALLINT,
    FLAG_11          SMALLINT,
    FLAG_12          SMALLINT,
    FLAG_13          SMALLINT,
    FLAG_14          SMALLINT,
    FLAG_15          SMALLINT,
    FLAG_16          SMALLINT,
    FLAG_17          SMALLINT,
    FLAG_18          SMALLINT,
    FLAG_19          SMALLINT,
    FLAG_20          SMALLINT,
    FLAG_21          SMALLINT,
    FLAG_22          SMALLINT,
    FLAG_23          SMALLINT,
    FLAG_24          SMALLINT,
    FLAG_25          SMALLINT,
    FLAG_26          SMALLINT,
    FLAG_27          SMALLINT,
    FLAG_28          SMALLINT,
    FLAG_29          SMALLINT,
    FLAG_30          SMALLINT,
    FLAG_31          SMALLINT
);

