create table MONTRAN_OUT
(
    MDATE              CHAR(6)     not null,
    NFB                CHAR(9)     not null,
    FILE_NAME          CHAR(50)    not null,
    REFERENCE_NUMBER   DECIMAL(15) not null,
    SUM_SV             DECIMAL(15, 2),
    SUM                DECIMAL(15, 2),
    PRFT_EXTRACTED_DT  TIMESTAMP(6),
    PRFT_CREATED_DT    TIMESTAMP(6),
    PRFT_EXTRACTED_FLG CHAR(1),
    PDK                CHAR(1),
    Z_R                CHAR(1),
    VOBR               CHAR(1),
    VOP                CHAR(2),
    BANK_A             CHAR(3),
    BANK_B             CHAR(3),
    NDOC               CHAR(4),
    NDOC_SV            CHAR(4),
    B_DATE             CHAR(6),
    REC_DATE           CHAR(6),
    DATE_SV            CHAR(6),
    NLSK               CHAR(9),
    NFA                CHAR(9),
    NLS                CHAR(9),
    SAXAZKOD           CHAR(9),
    GIK                CHAR(11),
    MIK                CHAR(11),
    NLS_AX             CHAR(34),
    NLSK_AX            CHAR(34),
    MB                 CHAR(50),
    GB                 CHAR(50),
    THP_NAME           CHAR(60),
    M_O                CHAR(60),
    G_O                CHAR(60),
    ZXZ3               CHAR(64),
    GD                 VARCHAR(190),
    DAMINF             VARCHAR(250),
    constraint IXU_FX_018
        primary key (MDATE, NFB, FILE_NAME, REFERENCE_NUMBER)
);

