create table MSG_DOCUMENT_INFO
(
    DOCUMENTID         VARCHAR(100),
    EXTERNALDOCUMENTID VARCHAR(100),
    DOCUMENTNAME       VARCHAR(100),
    DOCUMENTTYPENAME   VARCHAR(100),
    DOCUMENTTYPECODE   VARCHAR(100),
    NROFPAGES          INTEGER,
    PORTFOLIOCODE      VARCHAR(100),
    DOCUMENTSOURCE     VARCHAR(100),
    ACCOUNT            VARCHAR(100),
    AGREEMENT          VARCHAR(100),
    CUSTOMER           VARCHAR(100),
    PROFITS_DOC_TYPE   VARCHAR(100),
    TASK               INTEGER,
    TMSTMP             TIMESTAMP(6),
    DOCUMENTPATH       VARCHAR(512),
    ENTRYSTATUS        CHAR(1),
    PRINTSTATUS        CHAR(1),
    DATE01             DATE,
    DATE02             DATE,
    DATE03             DATE,
    DATE04             DATE,
    DATE05             DATE,
    DATE06             DATE,
    DATE07             DATE,
    DATE08             DATE,
    DATE09             DATE,
    DATE10             DATE,
    FLAG01             CHAR(1),
    FLAG02             CHAR(1),
    FLAG03             CHAR(1),
    FLAG04             CHAR(1),
    FLAG05             CHAR(1),
    FLAG06             CHAR(1),
    FLAG07             CHAR(1),
    FLAG08             CHAR(1),
    FLAG09             CHAR(1),
    FLAG10             CHAR(1),
    NUMBER01           INTEGER,
    NUMBER02           INTEGER,
    NUMBER03           INTEGER,
    NUMBER04           INTEGER,
    NUMBER05           INTEGER,
    NUMBER06           INTEGER,
    NUMBER07           INTEGER,
    NUMBER08           INTEGER,
    NUMBER09           INTEGER,
    NUMBER10           INTEGER,
    CHAR01             VARCHAR(100),
    CHAR02             VARCHAR(100),
    CHAR03             VARCHAR(100),
    CHAR04             VARCHAR(100),
    CHAR05             VARCHAR(100),
    CHAR06             VARCHAR(100),
    CHAR07             VARCHAR(100),
    CHAR08             VARCHAR(100),
    CHAR09             VARCHAR(100),
    CHAR10             VARCHAR(100),
    AMOUNT01           DECIMAL(18, 2),
    AMOUNT02           DECIMAL(18, 2),
    AMOUNT03           DECIMAL(18, 2),
    AMOUNT04           DECIMAL(18, 2),
    AMOUNT05           DECIMAL(18, 2),
    AMOUNT06           DECIMAL(18, 2),
    AMOUNT07           DECIMAL(18, 2),
    AMOUNT08           DECIMAL(18, 2),
    AMOUNT09           DECIMAL(18, 2),
    AMOUNT10           DECIMAL(18, 2)
);

