create table MSG_WATCHDOG_ALERTS
(
    TASK_ID             BIGINT not null
        primary key,
    ZEROROWSALERT       SMALLINT,
    ZEROMESSAGESCREATED SMALLINT,
    SQLRUNALERT         SMALLINT,
    MSGPREPAREALERT     SMALLINT,
    MSGDELIVERYALERT    SMALLINT,
    SQLRUN_LASTID       SMALLINT,
    MSGPREPARE_LASTID   SMALLINT,
    MSGDELIVERY_LASTID  SMALLINT,
    SQLRUN_EXECWINDOW   TIME,
    CREATED             DATE   not null,
    UPDATED             DATE   not null,
    TASKEXECUTED        SMALLINT
);

