create table NEW_PTJ_TMP
(
    FK0HDEPOSITFK_HPRO INTEGER,
    FK_JUSTIFICID_JUST INTEGER,
    FK_TRANSACTION0ID  INTEGER
);

create unique index IX_PK_PTJ
    on NEW_PTJ_TMP (FK0HDEPOSITFK_HPRO, FK_JUSTIFICID_JUST, FK_TRANSACTION0ID);

