CREATE FUNCTION NUMTEXT (
    P_STRING	VARCHAR(200),
    P_FORMAT_MASK	VARCHAR(40) DEFAULT NULL
    )
  RETURNS DECIMAL(30, 12)
BEGIN
  DECLARE ERROR_FLAG INTEGER DEFAULT 0;
  DECLARE CONTINUE HANDLER FOR SQLEXCEPTION SET ERROR_FLAG = 1;
  IF NVL(LENGTH (TRIM (p_format_mask)), 0) = 0 THEN
    RETURN TO_NUMBER (P_STRING);
  ELSE
    RETURN TO_NUMBER (P_STRING, p_format_mask);
  END IF;
END;

