create table ORDER_AGREEMENTS_U
(
    FK_CUSTOMERCUST_ID INTEGER  not null,
    REGION             SMALLINT not null,
    DURATION           INTEGER  not null,
    TRX_CODE           INTEGER  not null,
    SERVICE_CODE       CHAR(2)  not null,
    DETAIL_OF_CHARGE   CHAR(3)  not null,
    STP_FLAG           CHAR(1)  not null,
    INSTRUM_CODE       CHAR(8)  not null,
    ID_COM_USAGE1      SMALLINT,
    ID_COM_USAGE2      SMALLINT,
    ID_COM_USAGE3      SMALLINT,
    ID_COM_USAGE4      SMALLINT,
    ID_COM_USAGE5      SMALLINT,
    ID_EXP_USAGE1      SMALLINT,
    ID_EXP_USAGE2      SMALLINT,
    ID_EXP_USAGE3      SMALLINT,
    ID_EXP_USAGE4      SMALLINT,
    ID_EXP_USAGE5      SMALLINT,
    ID_COMMISSION_1    INTEGER,
    ID_COMMISSION_2    INTEGER,
    ID_COMMISSION_3    INTEGER,
    ID_COMMISSION_4    INTEGER,
    ID_COMMISSION_5    INTEGER,
    ID_EXPENSE_1       INTEGER,
    ID_EXPENSE_2       INTEGER,
    ID_EXPENSE_3       INTEGER,
    ID_EXPENSE_4       INTEGER,
    ID_EXPENSE_5       INTEGER,
    ID_TAX_1           INTEGER,
    ID_TAX_2           INTEGER,
    ID_TAX_3           INTEGER,
    ID_TAX_4           INTEGER,
    ID_TAX_5           INTEGER,
    ENTRY_STATUS       CHAR(1),
    TMSTAMP            TIMESTAMP(6),
    constraint IXU_CIU_047
        primary key (INSTRUM_CODE, STP_FLAG, DETAIL_OF_CHARGE, SERVICE_CODE, TRX_CODE, DURATION, REGION,
                     FK_CUSTOMERCUST_ID)
);

