create table ORDER_AGREEMENTS
(
    FK_CUSTOMERCUST_ID INTEGER,
    TRX_CODE           INTEGER,
    DETAIL_OF_CHARGE   CHAR(3),
    REGION             SMALLINT,
    STP_FLAG           CHAR(1),
    ID_EXP_USAGE3      SMALLINT,
    ID_EXP_USAGE2      SMALLINT,
    ID_EXP_USAGE1      SMALLINT,
    ID_COM_USAGE5      SMALLINT,
    ID_COM_USAGE4      SMALLINT,
    ID_COM_USAGE3      SMALLINT,
    ID_COM_USAGE2      SMALLINT,
    ID_COM_USAGE1      SMALLINT,
    ID_EXP_USAGE4      SMALLINT,
    ID_EXP_USAGE5      SMALLINT,
    ID_TAX_5           INTEGER,
    ID_TAX_4           INTEGER,
    ID_TAX_3           INTEGER,
    ID_TAX_2           INTEGER,
    ID_TAX_1           INTEGER,
    ID_EXPENSE_5       INTEGER,
    ID_EXPENSE_4       INTEGER,
    ID_EXPENSE_3       INTEGER,
    ID_EXPENSE_2       INTEGER,
    ID_EXPENSE_1       INTEGER,
    ID_COMMISSION_5    INTEGER,
    ID_COMMISSION_4    INTEGER,
    ID_COMMISSION_3    INTEGER,
    ID_COMMISSION_2    INTEGER,
    ID_COMMISSION_1    INTEGER,
    DURATION           INTEGER,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    SERVICE_CODE       CHAR(2),
    INSTRUM_CODE       CHAR(8)
);

create unique index IXU_ORD_000
    on ORDER_AGREEMENTS (FK_CUSTOMERCUST_ID, REGION, DURATION, TRX_CODE, SERVICE_CODE, DETAIL_OF_CHARGE, STP_FLAG,
                         INSTRUM_CODE);

