create table PACKAGE
(
    ID_PACKAGE         INTEGER,
    INSERTION_DT       DATE,
    PACKAGE_DESCR      CHAR(80),
    MODIFICATION_DT    DATE,
    MODIFICATION_USR   CHAR(8),
    PACKAGE_STATUS     CHAR(1),
    BUSINESS_PROJECT   SMALLINT,
    BUSINESS_RULE      DECIMAL(12),
    PACKAGE_END_DT     DATE,
    PACKAGE_FUNC       VARCHAR(2056),
    FOR_PRODUCTION     CHAR(1),
    START_DATE         DATE,
    PACKAGE_STATUS_FLG CHAR(1),
    SOURCE_CODE        CHAR(12),
    AUTO_ACCOUNTS_FLG  CHAR(1)
);

create unique index IXP_PAC_003
    on PACKAGE (ID_PACKAGE);

