create table PACKAGE_PROD_INFO
(
    ID_PACKAGE         INTEGER,
    ID_PRODUCT         INTEGER,
    BUSINESS_PROJECT   SMALLINT,
    TOTAL_ACCS         INTEGER,
    DB_INTER_RATE_SPR  INTEGER,
    CR_INTER_RATE_SPR  INTEGER,
    BUSINESS_RULE      DECIMAL(12),
    INSERTION_DT       DATE,
    MODIFICATION_DT    DATE,
    PRODUCT_USED       CHAR(1),
    PRODUCT_INDICATOR  CHAR(1),
    PRODUCT_STATUS_FLG CHAR(1),
    MODIFICATION_USR   CHAR(8),
    PACK_PRODUCT_FUNCT VARCHAR(2056)
);

create unique index IXP_PAC_002
    on PACKAGE_PROD_INFO (ID_PACKAGE, ID_PRODUCT);

