create table PACKAGE_PROD_PRICING
(
    ID_JUSTIFICATION  INTEGER not null,
    ID_TRANSACTION    INTEGER not null,
    ID_PRODUCT        INTEGER not null,
    ID_PACKAGE        INTEGER not null,
    VALUE_DATE_SPREAD SMALLINT,
    AVAIL_DATE_SPREAD SMALLINT,
    COMMISS_DISCOUNT  DECIMAL(8, 4),
    EXPENSE_DISCOUNT  DECIMAL(8, 4),
    INSERTION_DT      DATE,
    MODIFICATION_DT   DATE,
    STAMP_CHARGE_FLAG CHAR(1),
    MODIFICATION_USR  CHAR(8),
    PTJ_VALIDITY_DATE DATE,
    constraint IXU_PAC_000
        primary key (ID_JUSTIFICATION, ID_TRANSACTION, ID_PRODUCT, ID_PACKAGE)
);

