create table PACKAGE_PRODUCT
(
    ID_PRODUCT          INTEGER,
    OPEN_PROJECT        SMALLINT,
    INFORMATION_PROJECT SMALLINT,
    INFORMATION_RULE    DECIMAL(12),
    OPEN_RULE           DECIMAL(12),
    MODIFICATION_DT     DATE,
    INSERTION_DT        DATE,
    ENTRY_STATUS_FLG    CHAR(1),
    PRODUCT_TYPE_FLG    CHAR(1),
    PACKAGE_USED        CHAR(1),
    PROFITS_SYSTEM_FLG  CHAR(1),
    PRODUCT_STATUS      CHAR(1),
    MODIFICATION_USR    CHAR(8),
    PRODUCT_DESCR       CHAR(40),
    PRODUCT_FUNCT       VARCHAR(2056)
);

create unique index IXP_PAC_000
    on PACKAGE_PRODUCT (ID_PRODUCT);

