create table PAPERLESS_SECURITY
(
    ISIN               CHAR(12),
    NUMBER_OF_COUPONS  SMALLINT,
    FREQUENCY          SMALLINT,
    FK_BELONG_UNIT     INTEGER,
    FK_INTEREST_TAX    INTEGER,
    AIS_PS_TITLE_CODE  INTEGER,
    FK_REFER_CP_AGREEM DECIMAL(10),
    PRIM_SALE_REMN_AMN DECIMAL(15, 2),
    PRIM_SALE_UNIT_VAL DECIMAL(15, 2),
    PRIM_SALE_MAX_AMNT DECIMAL(15, 2),
    PRIM_SALE_USED_AMN DECIMAL(15, 2),
    PS_MIN_UNIT_VALUE  DECIMAL(15, 2),
    PS_ISSUE_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    LAST_UPDATE_DATE   DATE,
    LST_COUPON_SALE_DT DATE,
    ISSUE_DATE         DATE,
    PS_MATURITY_DATE   DATE,
    PRIM_SALE_END_DATE DATE,
    PRIM_SALE_START_DT DATE,
    PS_TYPE            CHAR(1),
    ENTRY_STATUS       CHAR(1),
    FREQUENCY_UNIT     CHAR(1),
    PS_CURRENCY        CHAR(5),
    PS_DESCRIPTION     VARCHAR(40),
    PRIM_SALE_END_TIME TIME
);

create unique index IXU_PAP_000
    on PAPERLESS_SECURITY (ISIN);

