create table PAR_RELATION_DETAI
(
    FKGD_HAS_A_PRIMARY INTEGER,
    FKGD_HAS_A_SECONDA INTEGER,
    FKGH_HAS_A_PRIMARY CHAR(5),
    FKGH_HAS_A_SECONDA CHAR(5),
    FK_PAR_RELATIONCOD CHAR(8),
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_PAR_005
    on PAR_RELATION_DETAI (FKGD_HAS_A_PRIMARY, FKGD_HAS_A_SECONDA, FKGH_HAS_A_PRIMARY, FKGH_HAS_A_SECONDA,
                           FK_PAR_RELATIONCOD);

