create table PAR_VOUCHER_DEF
(
    VOUCHER_ID     INTEGER,
    CUST_LANG      INTEGER,
    VOUCHER_ROW    SMALLINT,
    VOUCHER_COLUMN SMALLINT,
    VAR_LIT_IND    SMALLINT,
    DISPLAY_LENGTH SMALLINT,
    VOUCHER_DATA   VARCHAR(200),
    FORMAT_NAME    CHAR(30)
);

create unique index IXP_PAR_001
    on PAR_VOUCHER_DEF (VOUCHER_ID, CUST_LANG, VOUCHER_ROW, VOUCHER_COLUMN);

