create table PARAMETRIC_WINDOW
(
    PRFT_SYSTEM    SMALLINT,
    SEC_WINDOW_SN  SMALLINT,
    RULE_ID        DECIMAL(12),
    DEFAULT_WINDOW CHAR(1),
    STATUS         CHAR(1),
    SEC_WINDOW_ID  CHAR(8),
    DESCRIPTION    CHAR(80)
);

create unique index PK_PAR_WD
    on PARAMETRIC_WINDOW (SEC_WINDOW_ID, SEC_WINDOW_SN);

