create table PARAMETRIC_PRODUCT
(
    SEC_WINDOW_SN SMALLINT,
    ID_PRODUCT    INTEGER,
    SNUM          INTEGER,
    DELIVERED_FLG CHAR(1),
    PRODUCT_TYPE  CHAR(1),
    SEC_WINDOW_ID CHAR(8)
);

create unique index PK_PAR_PR
    on PARAMETRIC_PRODUCT (SEC_WINDOW_ID, SEC_WINDOW_SN, SNUM);

