create table PAYROLL_ORG
(
    FK_CUSTOMERCUST_ID  INTEGER not null
        constraint IXU_CP_126
            primary key,
    AUTO_LIMIT_RENEW    SMALLINT,
    NEXT_INSTALL_DAYS   SMALLINT,
    LIMIT_ACTIVE_AFTER  SMALLINT,
    MAX_OVERDRFT_LIMIT  SMALLINT,
    STD_OVERDRFT_LIMIT  SMALLINT,
    LIMIT_ACTIVE_DATE_F DATE
);

