create table PENALTY
(
    FK_CHANNELID_CHANN INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    SNUM               SMALLINT,
    ALLOWED2           SMALLINT,
    ALLOWED9           SMALLINT,
    ALLOWED4           SMALLINT,
    ALLOWED1           SMALLINT,
    ALLOWED3           SMALLINT,
    ALLOWED8           SMALLINT,
    ALLOWED7           SMALLINT,
    ALLOWED6           SMALLINT,
    ALLOWED5           SMALLINT,
    ID_PRODUCT         INTEGER,
    BALANCE2           DECIMAL(15, 2),
    PENALTY2           DECIMAL(15, 2),
    MIN_PENALTY2       DECIMAL(15, 2),
    BALANCE3           DECIMAL(15, 2),
    PENALTY3           DECIMAL(15, 2),
    MIN_PENAL1         DECIMAL(15, 2),
    MAX_PENALTY3       DECIMAL(15, 2),
    MIN_PENALTY3       DECIMAL(15, 2),
    BALANCE4           DECIMAL(15, 2),
    PENALTY4           DECIMAL(15, 2),
    MAX_PENAL1         DECIMAL(15, 2),
    MAX_PENALTY4       DECIMAL(15, 2),
    MIN_PENALTY4       DECIMAL(15, 2),
    BALANCE5           DECIMAL(15, 2),
    PENALTY5           DECIMAL(15, 2),
    PENALTY1           DECIMAL(15, 2),
    MAX_PENALTY5       DECIMAL(15, 2),
    MIN_PENALTY5       DECIMAL(15, 2),
    BALANCE6           DECIMAL(15, 2),
    PENALTY6           DECIMAL(15, 2),
    BALANCE1           DECIMAL(15, 2),
    MAX_PENALTY6       DECIMAL(15, 2),
    MIN_PENALTY6       DECIMAL(15, 2),
    BALANCE7           DECIMAL(15, 2),
    PENALTY7           DECIMAL(15, 2),
    MIN_PENALTY9       DECIMAL(15, 2),
    MAX_PENALTY7       DECIMAL(15, 2),
    MIN_PENALTY7       DECIMAL(15, 2),
    BALANCE8           DECIMAL(15, 2),
    PENALTY8           DECIMAL(15, 2),
    MAX_PENALTY9       DECIMAL(15, 2),
    MAX_PENALTY8       DECIMAL(15, 2),
    MIN_PENALTY8       DECIMAL(15, 2),
    PENALTY9           DECIMAL(15, 2),
    BALANCE0           DECIMAL(15, 2),
    PENALTY0           DECIMAL(15, 2),
    ALLOWED0           DECIMAL(15),
    MAX_PENAL0         DECIMAL(15, 2),
    MIN_PENAL0         DECIMAL(15, 2),
    BALANCE9           DECIMAL(15, 2),
    MAX_PENAL2         DECIMAL(15, 2),
    VALIDITY_DATE      DATE,
    TMSTAMP            DATE,
    ENTRY_STATUS       CHAR(1),
    CONTINUATION       CHAR(1)
);

create unique index IXU_PEN_001
    on PENALTY (FK_CHANNELID_CHANN, FK_PRODUCTID_PRODU, SNUM);

