create table PIG_ORGANIZATION
(
    ORGANIZATION         CHAR(10),
    IN_DCD_PRFT_SYS      SMALLINT,
    PROJECT_ORIGIN       SMALLINT,
    OUT_DCD_PRFT_SYS     SMALLINT,
    FK0PIG_TO_EXCELFIELD INTEGER,
    IN_PRCSS_TRX_CODE    INTEGER,
    FK_PIG_TO_EXCELFIELD INTEGER,
    IN_DCD_LANG_ID       INTEGER,
    OUT_DCD_LANG_ID      INTEGER,
    FK_PIG_DATAREC_CODE  DECIMAL(10),
    IN_DCD_RULE_ID       DECIMAL(12),
    OUT_DCD_RULE_ID      DECIMAL(12),
    TMSTAMP              TIMESTAMP(6),
    IN_TOTAL_PRCS        CHAR(1),
    TOTALS_FLAG          CHAR(1),
    FK0PIG_TO_EXCELFK_PI CHAR(5),
    FK_PIG_TO_EXCELFK_PI CHAR(5),
    FK_HAS_FOR_OUTFILE   CHAR(5),
    FK_HAS_FOR_INFILES   CHAR(5),
    DESCRIPTION          VARCHAR(40),
    ASCII_FILENAME       VARCHAR(50)
);

create unique index IXU_PIG_008
    on PIG_ORGANIZATION (ORGANIZATION);

