create table PIG_ASC_DATAREC_DT
(
    FK_PIG_ASC_DTF_TP  CHAR(1),
    FK0PIG_ASC_DTFI_SN DECIMAL(10),
    REC_SN             INTEGER,
    FIELD_SN           INTEGER,
    FIELD_SECTION      SMALLINT,
    TOTAL_STEPS        SMALLINT,
    DEC_MULTIPLIED     SMALLINT,
    MONTH              SMALLINT,
    LAST_PROCESS_STEP  SMALLINT,
    YEAR               SMALLINT,
    VALUE_NUMERIC      DECIMAL(18, 4),
    PROGGR_TOT_NUM     DECIMAL(18, 4),
    CREATED_DATE       DATE,
    VALUE_DATE         DATE,
    PROCESS_DATE       DATE,
    VALUE_TIMESTAMP    TIMESTAMP(6),
    CREATED_TIMESTAMP  TIMESTAMP(6),
    PROCESS_TIMESTAMP  TIMESTAMP(6),
    FIELD_CONTINUE     CHAR(1),
    PROCESS_STATUS     CHAR(1),
    CURRENT_STATUS     CHAR(1),
    APPROVED_FLAG      CHAR(1),
    FIELD_TYPE         CHAR(2),
    TABLE_ATTRIBUTE    CHAR(40),
    TABLE_ENTITY       CHAR(40),
    ERROR_DESCRIPTION  VARCHAR(80),
    VALUE_CHAR         VARCHAR(100),
    VALUE_TIME         TIME
);

create unique index IXN_PIG_001
    on PIG_ASC_DATAREC_DT (PROCESS_STATUS);

create unique index IXU_PIG_004
    on PIG_ASC_DATAREC_DT (FK_PIG_ASC_DTF_TP, FK0PIG_ASC_DTFI_SN, REC_SN, FIELD_SN);

