create table PIG_ASC_DATAREC_HD
(
    FILE_TYPE         CHAR(1),
    FILE_SN           DECIMAL(10),
    TOTAL_STEPS       SMALLINT,
    MONTH             SMALLINT,
    LAST_PROCESS_STEP SMALLINT,
    YEAR              SMALLINT,
    CREATE_TRX_CODE   INTEGER,
    PROCESS_TRX_CODE  INTEGER,
    TOT_PRCS_REC      INTEGER,
    TOT_CRT_REC       INTEGER,
    PROCESSED_DATE    DATE,
    PROCESSED_TMSTAMP TIMESTAMP(6),
    CREATED_DATE      DATE,
    CREATED_TMSTAMP   TIMESTAMP(6),
    CURRENT_STATUS    CHAR(1),
    APPROVED_FLAG     CHAR(1),
    PRCS_STATUS       CHAR(1),
    ORGANIZATION      CHAR(10),
    ASCII_FILENAME    VARCHAR(50),
    ERROR_DESCRIPTION VARCHAR(80)
);

create unique index IXU_PIG_005
    on PIG_ASC_DATAREC_HD (FILE_TYPE, FILE_SN);

