create table PIG_ASCFILE_FRM_DT
(
    FK_PIG_ASCFILE_FRM CHAR(5),
    FIELD_SECTION      SMALLINT,
    FIELD_SN           INTEGER,
    FIELD_USAGE        SMALLINT,
    MIN_LENGTH         SMALLINT,
    DEC_PLACES         INTEGER,
    START_POSITION     INTEGER,
    FIELD_LENGTH       INTEGER,
    TMSTAMP            TIMESTAMP(6),
    FIELD_CONTINUE     CHAR(1),
    SIGN_POS           CHAR(1),
    DECIMAL_SEP        CHAR(1),
    THOUSAND_SEP       CHAR(1),
    LINE_BREAK         CHAR(1),
    FIELD_TYPE         CHAR(2),
    DATE_FORMAT        CHAR(10),
    TIME_FORMAT        CHAR(10),
    TIMESTAMP_FORMAT   CHAR(26),
    FK_DCD_FIELDTABENT CHAR(40),
    FK0DCD_FIELDTABATR CHAR(40),
    FK0DCD_FIELDTABENT CHAR(40),
    FK_DCD_FIELDTABATR CHAR(40),
    USAGE_VALUE        VARCHAR(100)
);

create unique index IXU_PIG_006
    on PIG_ASCFILE_FRM_DT (FK_PIG_ASCFILE_FRM, FIELD_SECTION, FIELD_SN);

