create table PLAN_TABLE
(
    OTHER           LONG VARCHAR(32700),
    OBJECT_INSTANCE INTEGER,
    BYTES           INTEGER,
    COST            INTEGER,
    POSITION        INTEGER,
    PARENT_ID       INTEGER,
    ID              INTEGER,
    SEARCH_COLUMNS  DECIMAL(15, 2),
    PARTITION_ID    INTEGER,
    CARDINALITY     INTEGER,
    TIMESTAMP       DATE,
    OPERATION       VARCHAR(30),
    STATEMENT_ID    VARCHAR(30),
    OBJECT_TYPE     VARCHAR(30),
    OBJECT_NAME     VARCHAR(30),
    OBJECT_OWNER    VARCHAR(30),
    OPTIONS         VARCHAR(30),
    DISTRIBUTION    VARCHAR(30),
    REMARKS         VARCHAR(80),
    OBJECT_NODE     VARCHAR(128),
    OTHER_TAG       VARCHAR(255),
    PARTITION_START VARCHAR(255),
    PARTITION_STOP  VARCHAR(255),
    OPTIMIZER       VARCHAR(255)
);

