create table PO_TREASURY
(
    FK2GENERIC_DETASER INTEGER,
    FK_LNS_COMMISSIID  INTEGER,
    FK3GENERIC_DETASER INTEGER,
    FK1GENERIC_DETASER INTEGER,
    FK0GENERIC_DETASER INTEGER,
    FK_GENERIC_DETASER INTEGER,
    SERIAL_NUMBER      INTEGER,
    COMMISSION_SPLIT   DECIMAL(15, 2),
    AMOUNT             DECIMAL(15, 2),
    TOTAL_AMOUNT       DECIMAL(15, 2),
    TIMESTMP           TIMESTAMP(6),
    FK3GENERIC_DETAFK  CHAR(5),
    FK2GENERIC_DETAFK  CHAR(5),
    FK1GENERIC_DETAFK  CHAR(5),
    FK0GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETAFK  CHAR(5),
    RECEIVER_BANK_CODE CHAR(9),
    TAX_REG_NO         CHAR(20),
    GL_TRANSIT_CODE    CHAR(21),
    RECEIVER_ACCOUNT   CHAR(34),
    ADD_INFO           CHAR(40),
    RECEIVER_ACC_DESC  CHAR(60)
);

