create table POS_DAY_REP_EXC1
(
    ID_CURRENCY      INTEGER,
    TRX_DATE         DATE,
    CURRENCY_ORD     SMALLINT,
    FIXING_RATE_FC   DECIMAL(10, 6),
    FIXING_RATE_DC   DECIMAL(10, 6),
    PRESPOT_SELL     DECIMAL(18, 2),
    SPOT_BUY         DECIMAL(18, 2),
    SPOT_SELL        DECIMAL(18, 2),
    FW_BUY           DECIMAL(18, 2),
    FW_SELL          DECIMAL(18, 2),
    SWAP_SPOT_BUY    DECIMAL(18, 2),
    SWAP_SPOT_SELL   DECIMAL(18, 2),
    SWAP_FW_BUY      DECIMAL(18, 2),
    SWAP_FW_SELL     DECIMAL(18, 2),
    SWAP_ACCR        DECIMAL(18, 2),
    CLEAN_POS_FC     DECIMAL(18, 2),
    CLEAN_POS_OUT    DECIMAL(18, 2),
    FUTURES_FC       DECIMAL(18, 2),
    PREV_AMNTS       DECIMAL(18, 2),
    POS_SPOT_FW_FC   DECIMAL(18, 2),
    PRESPOT_BUY      DECIMAL(18, 2),
    SDAY_SELL        DECIMAL(18, 2),
    SDAY_BUY         DECIMAL(18, 2),
    ACCRUALS_BUY_FC  DECIMAL(18, 2),
    TOTAL_AMNT_FC    DECIMAL(18, 2),
    TOTAL_AMNT_DC    DECIMAL(18, 2),
    ACCRUALS_SELL_FC DECIMAL(18, 2),
    CURR_SHORT_DESC  CHAR(5)
);

create unique index IXU_POS_001
    on POS_DAY_REP_EXC1 (ID_CURRENCY, TRX_DATE);

