create table POS_DTL_TLF
(
    RECORD_SN            INTEGER,
    FK_POS_HD_TLFFILE    INTEGER,
    FK_POS_HD_TLFCREAT   DATE,
    SRC_AMOUNT_CURR_CD   SMALLINT,
    BILL_AMNT_CUR_CD     SMALLINT,
    TRANS_AMNT_CUR_CD    SMALLINT,
    TRANSACTION_CODE     SMALLINT,
    AUTHORISATION_REF    INTEGER,
    DELTA_REF            INTEGER,
    LEDGER_ACC_NUM       DECIMAL(11),
    BANK_ACC_NUM         DECIMAL(11),
    BILLING_AMOUNT       DECIMAL(15, 2),
    TRANSACTION_AMOUNT   DECIMAL(15, 2),
    SOURCE_AMOUNT        DECIMAL(15, 2),
    TRANSACTION_DATE     DATE,
    PROCESS_DATE         DATE,
    TIMESTMP             TIMESTAMP(6),
    RECONCILE_STS        CHAR(1),
    MERCHANT_COUNTRY     CHAR(2),
    SRC_AMNT_CURR_LIT    CHAR(3),
    AUTHORISATION_CD     CHAR(6),
    MERCHANT_CITY        CHAR(13),
    MERCHANT_ID          CHAR(15),
    ACQUIRER_ID          CHAR(18),
    CARD_NUMBER          CHAR(19),
    MERCHANT_NAME        CHAR(25),
    PRFT_ACC_NUM         VARCHAR(40),
    ACTUAL_ERROR         VARCHAR(200),
    AUTHORISATION_REF_UG CHAR(12)
);

create unique index IXU_POS_004
    on POS_DTL_TLF (RECORD_SN, FK_POS_HD_TLFFILE, FK_POS_HD_TLFCREAT);

