create table PRF_TRX_ADD_INFO
(
    FK_PRF_TRX_RECOTRX DATE,
    FK_PRF_TRX_RECOTR1 INTEGER,
    FK_PRF_TRX_RECOTR2 CHAR(8),
    FK_PRF_TRX_RECOTR3 INTEGER,
    FK_PRF_TRX_RECOTUN SMALLINT,
    CASH_DB_DOC_NUM    SMALLINT,
    JOURNAL_DB_DOC_NUM SMALLINT,
    CASH_CR_DOC_NUM    SMALLINT,
    MEMO_CR_DOC_NUM    SMALLINT,
    MEMO_DB_DOC_NUM    SMALLINT,
    JOURNAL_CR_DOC_NUM SMALLINT,
    PRFT_SYSTEM        INTEGER,
    JOURNAL_CR_TOT_AMN DECIMAL(15, 2),
    MEMO_DB_TOT_AMNT   DECIMAL(15, 2),
    CASH_CR_TOT_AMNT   DECIMAL(15, 2),
    CASH_DB_TOT_AMNT   DECIMAL(15, 2),
    MEMO_CR_TOT_AMNT   DECIMAL(15, 2),
    JOURNAL_DB_TOT_AMN DECIMAL(15, 2)
);

create unique index IXU_PRF_002
    on PRF_TRX_ADD_INFO (FK_PRF_TRX_RECOTRX, FK_PRF_TRX_RECOTR1, FK_PRF_TRX_RECOTR2, FK_PRF_TRX_RECOTR3,
                         FK_PRF_TRX_RECOTUN);

