create table PRINTING_REPORT_SIA
(
    SERIAL_NO            INTEGER,
    NAMEFILE             VARCHAR(100),
    TOTAL_ENVELOPES      INTEGER,
    TOTAL_SHEETS         INTEGER,
    TOTAL_PAGES          INTEGER,
    FIRST_CUSTOMER       VARCHAR(20),
    LAST_CUSTOMER        VARCHAR(20),
    ENTRY_STATUS         CHAR(1),
    TMSTAMP              TIMESTAMP(6),
    TOTAL_ENVELOPES_SPV1 INTEGER,
    TOTAL_SHEETS_SPV1    INTEGER,
    TOTAL_PAGES_SPV1     INTEGER,
    TOTAL_ENVELOPES_SPV2 INTEGER,
    TOTAL_SHEETS_SPV2    INTEGER,
    TOTAL_PAGES_SPV2     INTEGER,
    TOTAL_ENVELOPES_SPV4 INTEGER,
    TOTAL_SHEETS_SPV4    INTEGER,
    TOTAL_PAGES_SPV4     INTEGER
);

