create table PRL_CHK_VALID
(
    SYSTEM_CODE        DECIMAL(10) not null
        constraint PKRULEPW
            primary key,
    CHECK_TOP          DECIMAL(15, 2),
    CHECK_BOTTOM       DECIMAL(15, 2),
    CHECK_VALID_NUMBER DECIMAL(15, 2),
    CREATED_LAST_DATE  DATE,
    UPDATE_LAST_DATE   DATE,
    UPDATE_RULE_DESC   CHAR(40),
    CREATED_LAST_RULE  INTEGER,
    CREATED_RULE_DESC  CHAR(40),
    UPDATE_LAST_RULE   INTEGER,
    LST_ENTRY_COMMENTS VARCHAR(200)
);

