CREATE PROCEDURE PROFITS.PROC_REP_RECONC (
    IN DATE_FROM_IN	DATE,
    IN DATE_TO_IN	DATE )
  LANGUAGE SQL
  MODIFIES SQL DATA
/* STATHOULIS K. 19/22/2016 */
BEGIN
DELETE FROM TMP_REP_RECONC;
-- report 1 - profits reconciliation
-- input [date to], [date from]
    INSERT INTO TMP_REP_RECONC
       (GL_ACCOUNT, ACC_UNIT, ACC_MOVE_CURR, PRFT_SYSTEM, END_SYS_BALANCE, END_GL_BALANCE,
        END_DIF, START_SYS_BALANCE, START_GL_BALANCE, START_DIF, DIF)
    SELECT A.GL_ACCOUNT, A.ACC_UNIT, A.ACC_MOVE_CURR, A.PRFT_SYSTEM, A.GL_BALANCE, A.LEGER_BALANCE,
--    A.GL_BALANCE- A.LEGER_BALANCE,
    (case when (A.PRFT_SYSTEM <> 4 AND A.PRFT_SYSTEM <> 8 AND A.PRFT_SYSTEM <>88) THEN nvl(A.GL_BALANCE,0) + nvl(A.LEGER_BALANCE,0) ELSE nvl(A.GL_BALANCE,0) - nvl(A.LEGER_BALANCE,0) end ),
    0, 0, 0, 0
    FROM REP_74220 A
    WHERE DATE_TO_IN = (SELECT MAX(SCHEDULED_DATE) FROM BATCH_CONTROL B WHERE B.PROGRAM_ID = '74331' AND B.PROGRAM_STS = '1');
    INSERT INTO TMP_REP_RECONC
       (GL_ACCOUNT, ACC_UNIT, ACC_MOVE_CURR, PRFT_SYSTEM, END_SYS_BALANCE, END_GL_BALANCE,
        END_DIF, START_SYS_BALANCE, START_GL_BALANCE, START_DIF, DIF)
    SELECT A.GL_ACCOUNT, A.ACC_UNIT, A.ACC_MOVE_CURR, A.PRFT_SYSTEM,
    nvl(A.GL_BALANCE,0) ,
    nvl(A.LEGER_BALANCE,0),
--    nvl(A.GL_BALANCE- A.LEGER_BALANCE,
    (case when (A.PRFT_SYSTEM <> 4 AND A.PRFT_SYSTEM <> 8 AND A.PRFT_SYSTEM <>80 AND A.PRFT_SYSTEM <>88) THEN nvl(A.GL_BALANCE,0) + nvl(A.LEGER_BALANCE,0) ELSE nvl(A.GL_BALANCE,0) - nvl(A.LEGER_BALANCE,0) end ),
    0, 0, (case when (A.PRFT_SYSTEM <> 4 AND A.PRFT_SYSTEM <> 8 AND A.PRFT_SYSTEM <>80 AND A.PRFT_SYSTEM <>88) THEN nvl(A.GL_BALANCE,0) + nvl(A.LEGER_BALANCE,0) ELSE nvl(A.GL_BALANCE,0) - nvl(A.LEGER_BALANCE,0) end ), 0
    FROM HREP_74220 A
    WHERE DATE_TO_IN <> (SELECT MAX(SCHEDULED_DATE) FROM BATCH_CONTROL B WHERE B.PROGRAM_ID = '74331' AND B.PROGRAM_STS = '1')
    AND A.GL_TRN_DATE = DATE_TO_IN;
    UPDATE TMP_REP_RECONC T
        SET START_SYS_BALANCE = (SELECT B.GL_BALANCE FROM HREP_74220 B
        WHERE B.GL_ACCOUNT = T.GL_ACCOUNT
        AND B.ACC_UNIT = T.ACC_UNIT
        AND B.ACC_MOVE_CURR = T.ACC_MOVE_CURR
        AND B.PRFT_SYSTEM = T.PRFT_SYSTEM
        AND B.GL_TRN_DATE = DATE_FROM_IN);
    UPDATE TMP_REP_RECONC T
        SET START_GL_BALANCE = (SELECT B.LEGER_BALANCE FROM HREP_74220 B
        WHERE B.GL_ACCOUNT = T.GL_ACCOUNT
        AND B.ACC_UNIT = T.ACC_UNIT
        AND B.ACC_MOVE_CURR = T.ACC_MOVE_CURR
        AND B.PRFT_SYSTEM = T.PRFT_SYSTEM
        AND B.GL_TRN_DATE = DATE_FROM_IN);
    INSERT INTO TMP_REP_RECONC
       (GL_ACCOUNT, ACC_UNIT, ACC_MOVE_CURR, PRFT_SYSTEM, END_SYS_BALANCE, END_GL_BALANCE,
        END_DIF, START_SYS_BALANCE, START_GL_BALANCE, START_DIF, DIF)
    SELECT A.GL_ACCOUNT,
    A.ACC_UNIT,
    A.ACC_MOVE_CURR,
    A.PRFT_SYSTEM,
    0,
    0,
    0,
    A.GL_BALANCE,
    A.LEGER_BALANCE,
    (case when (A.PRFT_SYSTEM <> 4 AND A.PRFT_SYSTEM <> 8 AND A.PRFT_SYSTEM <>80 AND A.PRFT_SYSTEM <>88) THEN nvl(A.GL_BALANCE,0) + nvl(A.LEGER_BALANCE,0) ELSE nvl(A.GL_BALANCE,0) - nvl(A.LEGER_BALANCE,0) end ),
    0
    FROM HREP_74220 A
    WHERE A.GL_TRN_DATE = DATE_FROM_IN
    AND NOT EXISTS (SELECT 1 FROM TMP_REP_RECONC C
    WHERE C.GL_ACCOUNT = A.GL_ACCOUNT
    AND C.ACC_UNIT = A.ACC_UNIT
    AND C.ACC_MOVE_CURR = A.ACC_MOVE_CURR
    AND C.PRFT_SYSTEM = A.PRFT_SYSTEM);
   UPDATE TMP_REP_RECONC T
     SET START_DIF = (case when (PRFT_SYSTEM <> 4 AND PRFT_SYSTEM <> 8 AND PRFT_SYSTEM <>80 AND PRFT_SYSTEM <>88) THEN nvl(START_SYS_BALANCE,0) + nvl(START_GL_BALANCE,0) ELSE nvl(START_SYS_BALANCE,0) - nvl(START_GL_BALANCE,0) end );
    UPDATE TMP_REP_RECONC T
        SET DIF = END_DIF - START_DIF;
END;

