CREATE PROCEDURE PROC_REP_RECONC_DET (
    IN SUBSYS_IN	INTEGER,
    IN DATE_FROM_IN	DATE,
    IN DATE_TO_IN	DATE,
    IN GL_ACCOUNT_IN	VARCHAR(40),
    IN UNIT_IN	INTEGER,
    IN CCY_IN	INTEGER )
  SPECIFIC SQL160728110011128
  LANGUAGE SQL
  NOT DETERMINISTIC
  EXTERNAL ACTION
  MODIFIES SQL DATA
  CALLED ON NULL INPUT
  INHERIT SPECIAL REGISTERS
  OLD SAVEPOINT LEVEL
BEGIN
/* STATHOULIS K. 19/22/2016 */
DELETE FROM TMP_REP_RECONC_DET;
-- report 2 - profits analytical
-- input SubSystem 03 (deposits), 04 (loans)
-- date to, date from, gl account, UNIT, CURRENCY
---- common
INSERT INTO TMP_REP_RECONC_DET
   (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
    START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
    DIF)
SELECT A.PROF_ACCOUNT, 0, A.ORIGIN_TYPE, A.ORIGIN_ID, A.CHARGE_CODE, nvl(A.GL_BALANCE,0), 0, 0, 0, 0, 0, 0
FROM REP_74220_DET A
WHERE  DATE_TO_in = (SELECT MAX(SCHEDULED_DATE) FROM BATCH_CONTROL B WHERE B.PROGRAM_ID = '74331' AND B.PROGRAM_STS = '1')
AND trim(A.GL_ACCOUNT)    = trim(GL_ACCOUNT_in)
AND A.ACC_UNIT      = UNIT_in
AND A.ACC_MOVE_CURR = CCY_in
AND A.PRFT_SYSTEM   = SUBSYS_in;
INSERT INTO TMP_REP_RECONC_DET
   (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
    START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
    DIF)
SELECT A.PROF_ACCOUNT, 0, A.ORIGIN_TYPE, A.ORIGIN_ID, A.CHARGE_CODE, nvl(A.GL_BALANCE,0), 0, 0, 0, 0, 0, 0
FROM HREP_74220_DET A
WHERE  DATE_TO_in <> (SELECT MAX(SCHEDULED_DATE) FROM BATCH_CONTROL B WHERE B.PROGRAM_ID = '74331' AND B.PROGRAM_STS = '1')
AND A.GL_TRN_DATE   = DATE_TO_in
AND trim(A.GL_ACCOUNT)    = trim(GL_ACCOUNT_in)
AND A.ACC_UNIT      = UNIT_in
AND A.ACC_MOVE_CURR = CCY_in
AND A.PRFT_SYSTEM   = SUBSYS_in;
UPDATE TMP_REP_RECONC_DET T
SET START_SYS_BALANCE   = (SELECT nvl(B.GL_BALANCE,0) FROM HREP_74220_DET B
WHERE trim(B.GL_ACCOUNT)      = trim(GL_ACCOUNT_in)
AND B.ACC_UNIT          = UNIT_in
AND B.ACC_MOVE_CURR     = CCY_in
AND B.PRFT_SYSTEM       = SUBSYS_in
AND B.PROF_ACCOUNT      = T.PROF_ACCOUNT
AND B.ORIGIN_ID         = T.ORIGIN_ID
AND B.ORIGIN_TYPE       = T.ORIGIN_TYPE
AND B.CHARGE_CODE       = T.CHARGE_CODE
AND B.GL_TRN_DATE       = DATE_FROM_in);
INSERT INTO TMP_REP_RECONC_DET
   (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
    START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
    DIF)
SELECT A.PROF_ACCOUNT, 0,  A.ORIGIN_TYPE, A.ORIGIN_ID, A.CHARGE_CODE, 0, nvl(A.GL_BALANCE,0), 0, 0, 0, 0, 0
FROM HREP_74220_DET A
WHERE A.GL_TRN_DATE         = DATE_FROM_in
AND trim(A.GL_ACCOUNT)            = trim(GL_ACCOUNT_in)
AND A.ACC_UNIT              = UNIT_in
AND A.ACC_MOVE_CURR         = CCY_in
AND A.PRFT_SYSTEM           = SUBSYS_in
AND NOT EXISTS (SELECT 1 FROM TMP_REP_RECONC_DET C
                WHERE C.PROF_ACCOUNT = A.PROF_ACCOUNT
                AND C.ORIGIN_ID = A.ORIGIN_ID
                AND C.ORIGIN_TYPE = A.ORIGIN_TYPE
                AND C.CHARGE_CODE = A.CHARGE_CODE);
----- end of common
CASE WHEN SUBSYS_in = 3 THEN
-- FOR DEPOSITS
        UPDATE TMP_REP_RECONC_DET T
        SET DR_GL = NVL((SELECT SUM(NVL(C.AMOUNT, 0)) FROM DEP_GLI_INTERFACE C
        WHERE trim(C.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND C.PRF_ACCOUNT_NUMBER    = T.PROF_ACCOUNT
        AND C.FK1UNITCODE           = UNIT_in
        AND C.FK_CURRENCYID_CURR    = CCY_in
        AND C.ENTRY_TYPE            = '1'
        AND C.TRN_DATE              > DATE_FROM_in
        AND C.TRN_DATE              <= DATE_TO_in), 0);
        UPDATE TMP_REP_RECONC_DET T
        SET CR_GL = NVL((SELECT SUM(NVL(C.AMOUNT, 0)) FROM DEP_GLI_INTERFACE C
        WHERE trim(C.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND C.PRF_ACCOUNT_NUMBER    = T.PROF_ACCOUNT
        AND C.FK1UNITCODE           = UNIT_in
        AND C.FK_CURRENCYID_CURR    = CCY_in
        AND C.ENTRY_TYPE            = '2'
        AND C.TRN_DATE              > DATE_FROM_in
        AND C.TRN_DATE              <= DATE_TO_in), 0);
        INSERT INTO TMP_REP_RECONC_DET
           (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
            START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
            DIF)
        SELECT A.PRF_ACCOUNT_NUMBER, 0, 0, 0, 0, 0, 0, 0, SUM(NVL(A.AMOUNT, 0)), 0, 0, 0
        FROM DEP_GLI_INTERFACE A
        WHERE trim(A.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND A.FK1UNITCODE           = UNIT_in
        AND A.FK_CURRENCYID_CURR    = CCY_in
        AND A.ENTRY_TYPE            = '1'
        AND A.TRN_DATE              > DATE_FROM_in
        AND A.TRN_DATE              <= DATE_TO_in
        AND NOT EXISTS (SELECT 1 FROM TMP_REP_RECONC_DET C
                        WHERE C.PROF_ACCOUNT = A.PRF_ACCOUNT_NUMBER)
                        GROUP BY A.PRF_ACCOUNT_NUMBER;
        INSERT INTO TMP_REP_RECONC_DET
           (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
            START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
            DIF)
        SELECT A.PRF_ACCOUNT_NUMBER, 0,  0, 0, 0, 0, 0, 0, 0, SUM(NVL(A.AMOUNT, 0)), 0, 0
        FROM DEP_GLI_INTERFACE A
        WHERE trim(A.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND A.FK1UNITCODE           = UNIT_in
        AND A.FK_CURRENCYID_CURR    = CCY_in
        AND A.ENTRY_TYPE            = '2'
        AND A.TRN_DATE              > DATE_FROM_in
        AND A.TRN_DATE              <= DATE_TO_in
        AND NOT EXISTS (SELECT 1 FROM TMP_REP_RECONC_DET C
                        WHERE C.PROF_ACCOUNT = A.PRF_ACCOUNT_NUMBER)
                        GROUP BY A.PRF_ACCOUNT_NUMBER;
 
 
UPDATE TMP_REP_RECONC_DET T
SET SYS_DIF = NVL(END_SYS_BALANCE,0) - NVL(START_SYS_BALANCE,0),
    GL_DIF = NVL(CR_GL,0) - NVL(DR_GL,0);
 
WHEN SUBSYS_in = 4 THEN
-- only for loans
        UPDATE TMP_REP_RECONC_DET T
        SET DR_GL = NVL((SELECT SUM(NVL(C.AMOUNT, 0)) FROM LNS_GLI_INTERFACE C
        WHERE trim(C.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND C.PRF_ACCOUNT_NUMBER    = T.PROF_ACCOUNT
        AND C.FK1UNITCODE           = UNIT_in
        AND C.FK_CURRENCYID_CURR    = CCY_in
        AND C.ENTRY_TYPE            = '1'
        AND C.TRN_DATE              > DATE_FROM_in
        AND C.TRN_DATE              <= DATE_TO_in), 0);
        UPDATE TMP_REP_RECONC_DET T
        SET CR_GL = NVL((SELECT SUM(NVL(C.AMOUNT, 0)) FROM LNS_GLI_INTERFACE C
        WHERE trim(C.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND C.PRF_ACCOUNT_NUMBER    = T.PROF_ACCOUNT
        AND C.FK1UNITCODE           = UNIT_in
        AND C.FK_CURRENCYID_CURR    = CCY_in
        AND C.ENTRY_TYPE            = '2'
        AND C.TRN_DATE              >  DATE_FROM_in
        AND C.TRN_DATE              <= DATE_TO_in), 0);
        INSERT INTO TMP_REP_RECONC_DET
           (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
            START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
            DIF)
        SELECT A.PRF_ACCOUNT_NUMBER, 0, 0, 0, 0, 0, 0, 0, SUM(NVL(A.AMOUNT, 0)), 0, 0, 0
        FROM LNS_GLI_INTERFACE A
        WHERE trim(A.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND A.FK1UNITCODE           = UNIT_in
        AND A.FK_CURRENCYID_CURR    = CCY_in
        AND A.ENTRY_TYPE            = '1'
        AND A.TRN_DATE              > DATE_FROM_in
        AND A.TRN_DATE              <= DATE_TO_in
        AND NOT EXISTS (SELECT 1 FROM TMP_REP_RECONC_DET C
                        WHERE C.PROF_ACCOUNT = A.PRF_ACCOUNT_NUMBER)
                        GROUP BY A.PRF_ACCOUNT_NUMBER;
        INSERT INTO TMP_REP_RECONC_DET
           (PROF_ACCOUNT, CHECK_DIGIT, ORIGIN_TYPE, ORIGIN_ID, CHARGE_CODE, END_SYS_BALANCE,
            START_SYS_BALANCE, SYS_DIF, DR_GL, CR_GL, GL_DIF,
            DIF)
        SELECT A.PRF_ACCOUNT_NUMBER, 0,  0, 0, 0, 0, 0, 0, 0, SUM(NVL(A.AMOUNT, 0)), 0, 0
        FROM LNS_GLI_INTERFACE A
        WHERE trim(A.FK_GLG_ACCOUNTACCO)  = trim(GL_ACCOUNT_in)
        AND A.FK1UNITCODE           = UNIT_in
        AND A.FK_CURRENCYID_CURR    = CCY_in
        AND A.ENTRY_TYPE            = '2'
        AND A.TRN_DATE              > DATE_FROM_in
        AND A.TRN_DATE              <= DATE_TO_in
        AND NOT EXISTS (SELECT 1 FROM TMP_REP_RECONC_DET C
                        WHERE C.PROF_ACCOUNT = A.PRF_ACCOUNT_NUMBER)
                        GROUP BY A.PRF_ACCOUNT_NUMBER;
 
 
UPDATE TMP_REP_RECONC_DET T
SET SYS_DIF = nvl(END_SYS_BALANCE,0) - nvl(START_SYS_BALANCE,0),
    GL_DIF = NVL(DR_GL,0) - NVL(CR_GL,0);
WHEN SUBSYS_in <>'4' AND SUBSYS_IN<>'3' THEN
UPDATE TMP_REP_RECONC_DET T
SET SYS_DIF = 0,
    GL_DIF = 0;
END CASE;
-- common again
UPDATE TMP_REP_RECONC_DET T
SET T.CHECK_DIGIT = (SELECT A.ACCOUNT_CD  FROM PROFITS_ACCOUNT A WHERE A.ACCOUNT_NUMBER = T.PROF_ACCOUNT AND A.PRFT_SYSTEM = SUBSYS_in);
UPDATE TMP_REP_RECONC_DET T
SET DIF = nvl(SYS_DIF,0) - nvl(GL_DIF,0);
END;

