create table PRODUCT_CUSTOMER
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    ACCOUNT_COUNTER    SMALLINT
);

create unique index IXU_PRO_008
    on PRODUCT_CUSTOMER (FK_PRODUCTID_PRODU, FK_CUSTOMERCUST_ID);

