create table PROD_CURRENCY
(
    FK_CURRENCYID_CURR INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERM_RESTR_IND     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    MIN_OPENING_AMOUNT DECIMAL(15, 2),
    MIN_TRX_AMOUNT     DECIMAL(15, 2),
    MAX_BOOK_BALANCE   DECIMAL(15, 2)
);

create unique index IXU_PRO_021
    on PROD_CURRENCY (FK_CURRENCYID_CURR, FK_PRODUCTID_PRODU);

