create table PROD_INTEREST
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_INTERESTID_INTE INTEGER,
    ID_PRODUCT         DECIMAL(10),
    VALIDITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PERM_RESTR_IND     CHAR(1),
    INTEREST_CASE      CHAR(1)
);

create unique index IXU_PRO_020
    on PROD_INTEREST (FK_PRODUCTID_PRODU, FK_INTERESTID_INTE);

