create table PROD_COLLATERAL
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_COLLATERAL_TFK  INTEGER,
    VALIDITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_PRO_022
    on PROD_COLLATERAL (FK_PRODUCTID_PRODU, FK_COLLATERAL_TFK);

