create table PROD_TRXCHAN
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_TRANSACTION0ID  INTEGER,
    FK_CHANNELID_CHANN INTEGER,
    ID_PRODUCT         INTEGER,
    VALIDITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6)
);

create unique index IXU_PRO_003
    on PROD_TRXCHAN (FK_PRODUCTID_PRODU, FK_TRANSACTION0ID, FK_CHANNELID_CHANN);

