create table PROD_SUBSIDY
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_SUBSIDY_ORDEID  INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERM_RESTR_IND     CHAR(1),
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_PRO_002
    on PROD_SUBSIDY (FK_PRODUCTID_PRODU, FK_SUBSIDY_ORDEID);

