create table PROD_PERMISSIBLES
(
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_PRODUCTID_PRODU INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERM_RESTR_IND     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    FK_CATEGORYCATEGOR CHAR(8)
);

create unique index IXU_PRO_000
    on PROD_PERMISSIBLES (FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_PRODUCTID_PRODU);

