create table PRODUCT_GLACCOUNT
(
    FK_GLG_ACCOUNTACCO CHAR(21),
    FK_PRODUCTID_PRODU INTEGER,
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_PRO_009
    on PRODUCT_GLACCOUNT (FK_GLG_ACCOUNTACCO, FK_PRODUCTID_PRODU);

