create table PROD_UNIT
(
    FK_PRODUCTID_PRODU INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    TMSTAMP            TIMESTAMP(6),
    PERM_RESTR_IND     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    OPERATION_STATUS_F CHAR(1)
);

create unique index IXU_PRO_004
    on PROD_UNIT (FK_PRODUCTID_PRODU, FK_GENERIC_DETAFK, FK_GENERIC_DETASER);

