create table PROD_CAT_INTER_DT
(
    FK_LNS_INT_ID_INTEREST     INTEGER not null,
    FK_GEN_DET_FK_GENERIC_HEAD CHAR(5) not null,
    FK_GEN_DET_SERIAL_NUM      INTEGER not null,
    FK_HPRODUCT_ID_PRODUCT     INTEGER not null,
    FK_HPRODUCT_VALIDITY_DATE  DATE    not null,
    TMSTAMP                    TIMESTAMP(6),
    constraint PROD_CAT_INTER_DT_PK
        primary key (FK_LNS_INT_ID_INTEREST, FK_GEN_DET_FK_GENERIC_HEAD, FK_GEN_DET_SERIAL_NUM, FK_HPRODUCT_ID_PRODUCT,
                     FK_HPRODUCT_VALIDITY_DATE)
);

create unique index PROD_CAT_INTER_DT_IDX
    on PROD_CAT_INTER_DT (FK_LNS_INT_ID_INTEREST);

create unique index PROD_CAT_INTER_DT_IDX2
    on PROD_CAT_INTER_DT (FK_GEN_DET_FK_GENERIC_HEAD, FK_GEN_DET_SERIAL_NUM, FK_HPRODUCT_ID_PRODUCT,
                          FK_HPRODUCT_VALIDITY_DATE);

