create table PRODUCT
(
    ID_PRODUCT     INTEGER,
    BLOCKED_PERCNT DECIMAL(8, 4),
    TMSTAMP        TIMESTAMP(6),
    LAST_MODIFIED  DATE,
    PRD_EXP_DT     DATE,
    VALIDITY_DATE  DATE,
    INTER_BEARING  CHAR(1),
    INVEST_FLAG    CHAR(1),
    ENTRY_STATUS   CHAR(1),
    ENTERPRISE     CHAR(1),
    PRODUCT_TYPE   CHAR(1),
    DESCRIPTION    VARCHAR(40),
    COMMENT1       VARCHAR(75)
);

create unique index IXU_PRO_006
    on PRODUCT (ID_PRODUCT);

