create table PROD_FORMULA_DT
(
    FORML_SERIAL_NUM DECIMAL(10) not null,
    FORML_FIELD1     CHAR(40),
    NUM_FIELD1       DECIMAL(18, 6),
    FLDVALUES1_CD    DECIMAL(10),
    MULTI_FLDVAL1_CD DECIMAL(10),
    FORML_OPERATOR   CHAR(5),
    FORML_FIELD2     CHAR(40),
    NUM_FIELD2       DECIMAL(18, 6),
    FLDVALUES2_CD    DECIMAL(10),
    MULTI_FLDVAL2_CD DECIMAL(10),
    TMSTAMP          TIMESTAMP(6),
    FK_PRODUCT_ID    INTEGER     not null,
    FK_RESULT_FIELD  CHAR(40)    not null,
    FK_FORMULA_SN    DECIMAL(10) not null,
    TMP_RESULT_FIELD CHAR(40),
    constraint PK_PRD_FORMULA_DT
        primary key (FK_PRODUCT_ID, FK_RESULT_FIELD, FK_FORMULA_SN, FORML_SERIAL_NUM)
);

