create table PROFITS_SCENARIO
(
    KEY_TMSTAMP              TIMESTAMP(6) not null,
    KEY_SYSTEM               SMALLINT     not null,
    KEY_SN                   DECIMAL(15)  not null,
    APPLICATION_ID           CHAR(30),
    APPLICATION_STS          CHAR(1),
    PRODUCT_ID               INTEGER,
    CUSTOMER_ID_1            INTEGER,
    CUSTOMER_CD_1            SMALLINT,
    CUSTOMER_ID_2            INTEGER,
    CUSTOMER_CD_2            SMALLINT,
    CUSTOMER_ID_3            INTEGER,
    CUSTOMER_CD_3            SMALLINT,
    ACCOUNT_NUMBER_1         CHAR(40),
    ACCOUNT_CD_1             SMALLINT,
    ACCOUNT_SYSTEM_1         SMALLINT,
    ACCOUNT_NUMBER_2         CHAR(40),
    ACCOUNT_CD_2             SMALLINT,
    ACCOUNT_SYSTEM_2         SMALLINT,
    ACCOUNT_NUMBER_3         CHAR(40),
    ACCOUNT_CD_3             SMALLINT,
    ACCOUNT_SYSTEM_3         SMALLINT,
    CURRENCY_ID_1            INTEGER,
    CURRENCY_ID_2            INTEGER,
    CURRENCY_ID_3            INTEGER,
    DATE_1                   DATE,
    DATE_2                   DATE,
    DATE_3                   DATE,
    DATE_4                   DATE,
    DATE_5                   DATE,
    DATE_6                   DATE,
    DATE_7                   DATE,
    DATE_8                   DATE,
    DATE_9                   DATE,
    DATE_10                  DATE,
    DATE_11                  DATE,
    DATE_12                  DATE,
    DATE_13                  DATE,
    DATE_14                  DATE,
    DATE_15                  DATE,
    AMOUNT_1                 DECIMAL(15, 2),
    AMOUNT_2                 DECIMAL(15, 2),
    AMOUNT_3                 DECIMAL(15, 2),
    AMOUNT_4                 DECIMAL(15, 2),
    AMOUNT_5                 DECIMAL(15, 2),
    AMOUNT_6                 DECIMAL(15, 2),
    AMOUNT_7                 DECIMAL(15, 2),
    AMOUNT_8                 DECIMAL(15, 2),
    AMOUNT_9                 DECIMAL(15, 2),
    AMOUNT_10                DECIMAL(15, 2),
    AMOUNT_11                DECIMAL(15, 2),
    AMOUNT_12                DECIMAL(15, 2),
    AMOUNT_13                DECIMAL(15, 2),
    AMOUNT_14                DECIMAL(15, 2),
    AMOUNT_15                DECIMAL(15, 2),
    DESCR_1                  VARCHAR(40),
    DESCR_2                  VARCHAR(40),
    DESCR_3                  VARCHAR(40),
    DESCR_4                  VARCHAR(40),
    DESCR_5                  VARCHAR(40),
    DESCR_6                  VARCHAR(40),
    DESCR_7                  VARCHAR(40),
    DESCR_8                  VARCHAR(40),
    DESCR_9                  VARCHAR(40),
    DESCR_10                 VARCHAR(40),
    NUMBER_1                 DECIMAL(10),
    NUMBER_2                 DECIMAL(10),
    NUMBER_3                 DECIMAL(10),
    NUMBER_4                 DECIMAL(10),
    NUMBER_5                 DECIMAL(10),
    NUMBER_6                 DECIMAL(10),
    NUMBER_7                 DECIMAL(10),
    NUMBER_8                 DECIMAL(10),
    NUMBER_9                 DECIMAL(10),
    NUMBER_10                DECIMAL(10),
    INTEGER_1                INTEGER,
    INTEGER_2                INTEGER,
    INTEGER_3                INTEGER,
    INTEGER_4                INTEGER,
    INTEGER_5                INTEGER,
    INTEGER_6                INTEGER,
    INTEGER_7                INTEGER,
    INTEGER_8                INTEGER,
    INTEGER_9                INTEGER,
    INTEGER_10               INTEGER,
    FLAG_1                   VARCHAR(2),
    FLAG_2                   VARCHAR(2),
    FLAG_3                   VARCHAR(2),
    FLAG_4                   VARCHAR(2),
    FLAG_5                   VARCHAR(2),
    FLAG_6                   VARCHAR(2),
    FLAG_7                   VARCHAR(2),
    FLAG_8                   VARCHAR(2),
    FLAG_9                   VARCHAR(2),
    FLAG_10                  VARCHAR(2),
    AMOUNT_18_4_1            DECIMAL(18, 4),
    AMOUNT_18_4_2            DECIMAL(18, 4),
    AMOUNT_18_4_3            DECIMAL(18, 4),
    INSERT_DATE              DATE,
    INSERT_UNIT              INTEGER,
    INSERT_USER              CHAR(8),
    UPDATE_DATE              DATE,
    UPDATE_UNIT              INTEGER,
    UPDATE_USER              CHAR(8),
    SCENARIO_STS             CHAR(1),
    SCENARIO_ACCOUNT         CHAR(40),
    SCENARIO_ACCOUNT_CD      SMALLINT,
    LARGE_DESC_1             VARCHAR(500),
    LARGE_DESC_2             VARCHAR(500),
    LARGE_DESC_3             VARCHAR(500),
    CUSTOMER_ID_4            INTEGER,
    CUSTOMER_CD_4            SMALLINT,
    CUSTOMER_ID_5            INTEGER,
    CUSTOMER_CD_5            SMALLINT,
    CUSTOMER_ID_6            INTEGER,
    CUSTOMER_CD_6            SMALLINT,
    CUSTOMER_ID_7            INTEGER,
    CUSTOMER_CD_7            SMALLINT,
    CUSTOMER_ID_8            INTEGER,
    CUSTOMER_CD_8            SMALLINT,
    CUSTOMER_ID_9            INTEGER,
    CUSTOMER_CD_9            SMALLINT,
    CUSTOMER_ID_10           INTEGER,
    CUSTOMER_CD_10           SMALLINT,
    ACCOUNT_NUMBER_4         CHAR(40),
    ACCOUNT_CD_4             SMALLINT,
    ACCOUNT_SYSTEM_4         SMALLINT,
    ACCOUNT_NUMBER_5         CHAR(40),
    ACCOUNT_CD_5             SMALLINT,
    ACCOUNT_SYSTEM_5         SMALLINT,
    DESCR_11                 VARCHAR(40),
    DESCR_12                 VARCHAR(40),
    DESCR_13                 VARCHAR(40),
    DESCR_14                 VARCHAR(40),
    DESCR_15                 VARCHAR(40),
    DESCR_16                 VARCHAR(40),
    DESCR_17                 VARCHAR(40),
    DESCR_18                 VARCHAR(40),
    DESCR_19                 VARCHAR(40),
    DESCR_20                 VARCHAR(40),
    LARGE_DESC_4             VARCHAR(500),
    LARGE_DESC_5             VARCHAR(500),
    LARGE_DESC_6             VARCHAR(500),
    LARGE_DESC_7             VARCHAR(500),
    LARGE_DESC_8             VARCHAR(500),
    LARGE_DESC_9             VARCHAR(500),
    LARGE_DESC_10            VARCHAR(500),
    WFE_APPLICATION_ID       CHAR(40),
    WFE_APPLICATION_SYSTEM   DECIMAL(2),
    WFE_APPLICATION_APPROVED CHAR(1),
    constraint PK_PRFSCEN
        primary key (KEY_TMSTAMP, KEY_SYSTEM, KEY_SN)
);

