create table PROFITS_EXECUTE
(
    SCRIPT_NAME        VARCHAR(100),
    ACTUAL_SCRIPT      CLOB(1048576),
    TIMESTAMP_EXECUTED TIMESTAMP(6),
    VERSION_NUMBER     VARCHAR(20),
    RESULT             CLOB(1048576),
    SCRIPT_TYPE        VARCHAR(20),
    RELEASE_NAME       VARCHAR(20)
);

