create table PROFITS_RESTRUCTURES
(
    ACCOUNT_NUMBER    CHAR(40) not null,
    ACCOUNT_SYSTEM    SMALLINT not null,
    RESTRUCTURE_SN    INTEGER  not null,
    RESTRUCTURE_DATE  DATE,
    RESTRUCTURE_GOVT  CHAR(1),
    LINKED_ACCOUNT    CHAR(40),
    LINKED_SYSTEM     SMALLINT,
    CREATE_USER       CHAR(8),
    CREATE_UNIT       INTEGER,
    CREATE_DATE       DATE,
    CREATE_TMSTAMP    TIMESTAMP(6),
    UPDATE_USER       CHAR(8),
    UPDATE_UNIT       INTEGER,
    UPDATE_DATE       DATE,
    UPDATE_TMSTAMP    TIMESTAMP(6),
    AUTO_CREATED      CHAR(1),
    ENTRY_STATUS      CHAR(1),
    FK_GH_ADJUST      CHAR(5),
    FK_GD_ADJUST      INTEGER,
    RESTRUCTURE_CMNTS VARCHAR(500),
    constraint PK_RESTRUCT
        primary key (ACCOUNT_SYSTEM, ACCOUNT_NUMBER, RESTRUCTURE_SN)
);

