create table PROFITS_CHECKSUM_COMPARISON
(
    FILENAME                 VARCHAR(100) not null,
    COMPARISON_DATE          VARCHAR(19)  not null,
    TYPE                     VARCHAR(10)  not null,
    LOCAL_CHECKSUM           VARCHAR(50),
    REMOTE_CHECKSUM          VARCHAR(50),
    LOCAL_MODIFICATION_DATE  VARCHAR(19),
    REMOTE_MODIFICATION_DATE VARCHAR(19),
    COMPARISON_RESULT        VARCHAR(50)
);

create unique index PROFITS_CHECKSUM_COMPARISON_PK
    on PROFITS_CHECKSUM_COMPARISON (COMPARISON_DATE, FILENAME, TYPE);

