create table PROFITS_GL_CONFIGURATION
(
    REPORT          VARCHAR(50),
    EXCEL_SHEET     VARCHAR(20),
    EXCEL_CELL      VARCHAR(10),
    GL_SN           INTEGER,
    GL_ACCOUNT_FROM VARCHAR(20),
    GL_ACCOUNT_TO   VARCHAR(20),
    AMT_TYPE        VARCHAR(20),
    CURRENCY_TYPE   VARCHAR(20),
    CURRENCY        VARCHAR(20),
    FACTOR1         DECIMAL(5, 2),
    DATE_FROM       VARCHAR(50),
    DATE_TO         VARCHAR(50),
    REF_REPORT      VARCHAR(50),
    REF_EXCEL_SHEET VARCHAR(20),
    REF_EXCEL_CELL  VARCHAR(10)
);

