create table PROFILE_OPERATIONE_BAK062016
(
    FK_UNIT_CATEGORID  CHAR(8),
    FK_SEC_OPERATIOFK  CHAR(8),
    FK_SEC_OPERATIOFK1 CHAR(8),
    MENU_POS           SMALLINT,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PRFT_SYSTEM_FLAG   CHAR(1),
    MEMORY_CHOICE      CHAR(6)
);

