create table PROF_MSG_HEADER
(
    LISTENER_IP   VARCHAR(15),
    LISTENER_PORT VARCHAR(5),
    WINDOW_POSX   VARCHAR(4),
    WINDOW_POSY   VARCHAR(4),
    WINDOW_WIDTH  VARCHAR(4),
    WINDOW_HEIGHT VARCHAR(4)
);

create unique index PKPROFMSGHEAD
    on PROF_MSG_HEADER (LISTENER_IP, LISTENER_PORT);

