create table PROFITS_RELEASE_DBLOG
(
    TIMESTAMP        TIMESTAMP(6),
    ISSUE_NUMBER     VARCHAR(255),
    VERSION_NUMBER   CHAR(12),
    EXECUTION_LOG    CLOB(1048576),
    PREVIOUS_VERSION BLOB(1048576)
);

