create table PROFILE_OPERATION
(
    FK_UNIT_CATEGORID  CHAR(8),
    FK_SEC_OPERATIOFK  CHAR(8),
    FK_SEC_OPERATIOFK1 CHAR(8),
    MENU_POS           SMALLINT,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PRFT_SYSTEM_FLAG   CHAR(1),
    MEMORY_CHOICE      CHAR(6)
);

create unique index IXU_PRO_010
    on PROFILE_OPERATION (FK_UNIT_CATEGORID, FK_SEC_OPERATIOFK, FK_SEC_OPERATIOFK1);

