create table PROFITS_MIGR_FIN_LOANS
(
    NON_MIGR_ACR_PNL_INT_BAL DECIMAL(15, 2),
    MIGR_ACR_PNL_INT_BAL     DECIMAL(15, 2),
    ACR_PNL_INT_BAL          DECIMAL(15, 2),
    NON_MIGR_URL_PNL_INT_BAL DECIMAL(15, 2),
    MIGR_URL_PNL_INT_BAL     DECIMAL(15, 2),
    URL_PNL_INT_BAL          DECIMAL(15, 2),
    NON_MIGR_RL_PNL_INT_BAL  DECIMAL(15, 2),
    MIGR_RL_PNL_INT_BAL      DECIMAL(15, 2),
    RL_PNL_INT_BAL           DECIMAL(15, 2),
    NON_MIGR_ACR_INT_BAL     DECIMAL(15, 2),
    MIGR_ACR_INT_BAL         DECIMAL(15, 2),
    ACR_INT_BAL              DECIMAL(15, 2),
    NON_MIGR_COM_BAL         DECIMAL(15, 2),
    MIGR_COM_BAL             DECIMAL(15, 2),
    COM_BAL                  DECIMAL(15, 2),
    NON_MIGR_EXP_BAL         DECIMAL(15, 2),
    MIGR_EXP_BAL             DECIMAL(15, 2),
    EXP_BAL                  DECIMAL(15, 2),
    NON_MIGR_URL_INT_BAL     DECIMAL(15, 2),
    MIGR_URL_INT_BAL         DECIMAL(15, 2),
    URL_INT_BAL              DECIMAL(15, 2),
    NON_MIGR_RL_INT_BAL      DECIMAL(15, 2),
    MIGR_RL_INT_BAL          DECIMAL(15, 2),
    RL_INT_BAL               DECIMAL(15, 2),
    NON_MIGR_CAP_BAL         DECIMAL(15, 2),
    MIGR_CAP_BAL             DECIMAL(15),
    CAP_BAL                  DECIMAL(15),
    NON_MIGR_REQUESTS        DECIMAL(10),
    MIGR_REQUESTS            DECIMAL(10),
    REQUESTS                 DECIMAL(10),
    LOAN_STATUS              CHAR(1) not null,
    REQUEST_TYPE             CHAR(1) not null,
    PRODUCT_ID               CHAR(5) not null,
    constraint PR_MIGR_FIN_LOANS_PK
        primary key (PRODUCT_ID, REQUEST_TYPE, LOAN_STATUS)
);

