create table PROFITS_ACC_GRP
(
    FK_GH_GRP_TYPE CHAR(5),
    FK_GD_GRP_TYPE INTEGER,
    ACCOUNT_NUMBER CHAR(40),
    PRFT_SYSTEM    SMALLINT
);

create unique index PKACCGRP
    on PROFITS_ACC_GRP (FK_GH_GRP_TYPE, FK_GD_GRP_TYPE, ACCOUNT_NUMBER, PRFT_SYSTEM);

