create table PROFITS_REPORTS_CONFIGURATION
(
    REPORT           VARCHAR(20),
    EXCEL_SHEET      VARCHAR(30),
    EXCEL_CELL       VARCHAR(10),
    PRODUCT_SN       INTEGER,
    PRODUCT          VARCHAR(20),
    TRN_TYPE         VARCHAR(20),
    PURPOSE          VARCHAR(20),
    VISION_HDG       VARCHAR(20),
    CURRENCY         VARCHAR(30),
    ORIGIN           VARCHAR(20),
    CATEGORY         VARCHAR(20),
    DAYS_FROM        DECIMAL(10),
    DAYS_TO          DECIMAL(10),
    ACCRUALS         VARCHAR(1),
    WEIGHTED_AVERAGE VARCHAR(1),
    AVERAGE_TENOR    VARCHAR(1),
    AMOUNT_SIGN      VARCHAR(1),
    AMOUNT_FLAG      VARCHAR(1)
);

create unique index PRC_PK
    on PROFITS_REPORTS_CONFIGURATION (REPORT, EXCEL_SHEET, EXCEL_CELL, PRODUCT_SN);

