create table PROFITS_PARAM
(
    TRANSACT_ID  DECIMAL(10),
    PARAM_NAME   CHAR(20),
    ACTIVE_FLAG  CHAR(1),
    DESCRIPTION  CHAR(50),
    DATE_VALUE   DATE,
    STRING_50    CHAR(50),
    NUMBER_10    DECIMAL(10),
    NUMBER_15_2  DECIMAL(15, 2),
    FLAG         CHAR(1),
    TMSTAMP_PROC TIMESTAMP(6),
    TIME_VALUE   TIME
);

create unique index IXP_PRO_001
    on PROFITS_PARAM (PARAM_NAME, TRANSACT_ID);

