create table PROFITS_EXT_CONFIGURATION
(
    REPORT        VARCHAR(50),
    EXCEL_SHEET   VARCHAR(20),
    EXCEL_CELL    VARCHAR(10),
    LNS_SN        INTEGER,
    FINSC_FROM    INTEGER,
    FINSC_TO      INTEGER,
    AMT_TYPE      VARCHAR(20),
    CURRENCY_TYPE VARCHAR(20),
    CURRENCY      VARCHAR(20),
    FACTOR1       INTEGER,
    DATE_FROM     VARCHAR(50),
    DATE_TO       VARCHAR(50)
);

