create table PROFITS_LOANS_CONFIGURATION
(
    REPORT              VARCHAR(50),
    EXCEL_SHEET         VARCHAR(20),
    EXCEL_CELL          VARCHAR(10),
    LNS_SN              INTEGER,
    PRODUCT_FROM        INTEGER,
    PRODUCT_TO          INTEGER,
    FINSC_FROM          INTEGER,
    FINSC_TO            INTEGER,
    CCODE_FROM          INTEGER,
    CCODE_TO            INTEGER,
    LPURP_FROM          INTEGER,
    LPURP_TO            INTEGER,
    LPUCB_FROM          INTEGER,
    LPUCB_TO            INTEGER,
    LOAN_STS_FROM       VARCHAR(20),
    LOAN_STS_TO         VARCHAR(20),
    CLASSIFIC_FROM      VARCHAR(20),
    CLASSIFIC_TO        VARCHAR(20),
    AMT_TYPE            VARCHAR(20),
    CURRENCY_TYPE       VARCHAR(20),
    CURRENCY            VARCHAR(20),
    FACTOR1             DECIMAL(5, 2),
    DATE_FROM           VARCHAR(50),
    DATE_TO             VARCHAR(50),
    RATE_FROM           DECIMAL(12, 6),
    RATE_TO             DECIMAL(12, 6),
    MONTH_DURATION_FROM DECIMAL(10, 2),
    MONTH_DURATION_TO   DECIMAL(10, 2),
    OV_DAYS_FROM        INTEGER,
    OV_DAYS_TO          INTEGER,
    SUB_CLASS_FROM      INTEGER,
    SUB_CLASS_TO        INTEGER,
    CUST_CATEG_FROM     INTEGER,
    CUST_CATEG_TO       INTEGER,
    RESTRUCTURED        VARCHAR(20)
);

