create table PROFITS_RELEASE
(
    CREATION_TMSTAMP TIMESTAMP(6),
    RESPONSIBLE      VARCHAR(511),
    MODEL_AFFECTED   VARCHAR(511),
    SYSTEM           VARCHAR(511),
    RELEASE_AFFECTED VARCHAR(511),
    RELEASE_PATCH    VARCHAR(511),
    F12              VARCHAR(511),
    VERSION_NUMBER   VARCHAR(4000),
    TYPE             VARCHAR(511),
    EXECUTABLES      VARCHAR(255),
    ICOM_CREATE_DT   VARCHAR(511)
);

