create table PROFITS_BDG_CONFIGURATION
(
    REPORT        VARCHAR(50),
    EXCEL_SHEET   VARCHAR(10),
    EXCEL_CELL    VARCHAR(10),
    GL_SN         INTEGER,
    ELEMENT_FROM  VARCHAR(50),
    ELEMENT_TO    VARCHAR(50),
    AMOUNT_TYPE   VARCHAR(50),
    CURRENCY_TYPE VARCHAR(50),
    CURRENCY      VARCHAR(10),
    FACTOR1       DECIMAL(5, 2),
    DATE_FROM     VARCHAR(50),
    DATE_TO       VARCHAR(50),
    FORMULA       VARCHAR(50)
);

