create table PROJECT
(
    NUMBER0               SMALLINT,
    FK_DIVISIONNUMBER0    SMALLINT,
    FK_EMPLOYEENUMBER0    INTEGER,
    COST_TO_DATE          DECIMAL(11, 2),
    ESTIMATED_COST        DECIMAL(11, 2),
    ACTUAL_COST           DECIMAL(11, 2),
    ACTUAL_START_DATE     DATE,
    ESTIMATED_START_DATE  DATE,
    ESTIMATED_DUE_DATE    DATE,
    ACTUAL_DATE_COMPLETED DATE,
    NAME                  CHAR(25)
);

