create table QA_DAILY_ACCOUNTS
(
    WLT_DATE                    DATE        not null,
    ID                          CHAR(40)    not null,
    PRFT_SYSTEM                 SMALLINT    not null,
    DEP_ACC_NUMBER              DECIMAL(11),
    LNS_SN                      INTEGER,
    LNS_TYPE                    SMALLINT,
    LNS_OPEN_UNIT               INTEGER,
    NAME                        VARCHAR(70) not null,
    MONITOR                     SMALLINT,
    EXEMPTION_STATUS            CHAR(11),
    NOTES                       VARCHAR(500),
    BRANCH                      INTEGER,
    OPEN_DATE                   DATE,
    OWNER_BRANCH                INTEGER,
    OWNER_DEPT                  CHAR(11),
    OWNER_OPER                  CHAR(11),
    CLOSED                      SMALLINT,
    CLOSE_DATE                  DATE,
    CLOSE_REASON                VARCHAR(100),
    TYPE                        INTEGER,
    REFERENCE                   VARCHAR(100),
    REQUEST                     SMALLINT,
    POLICY_AMOUNT               DECIMAL(15, 2),
    POLICY_EXPIRY_DATE          DATE,
    FREE_LOOK_END_DATE          DATE,
    CASH_VALUE                  DECIMAL(15, 2),
    SINGLE_PREMIUM              SMALLINT,
    ACCOUNT_OFFICER             VARCHAR(35),
    BALANCE_AMT                 DECIMAL(15, 2),
    SOURCE_OF_PAYMENT           VARCHAR(250),
    AC_STATUS                   VARCHAR(35),
    INITIAL_DEPOSIT             DECIMAL(15, 2),
    TYPE_OF_FUNDS               CHAR(25),
    REQ_WIRE_TRANS              SMALLINT,
    ACC_ACH_PAY                 SMALLINT,
    ORG_ACH_PAY                 SMALLINT,
    MONTHLY_DEPOSITS            INTEGER,
    TOT_DEPOSIT_AMT_MNTH        DECIMAL(15, 2),
    MONTHLY_CASH_DEPOSITS       INTEGER,
    TOT_CASH_DEPOSIT_AMT_MNTH   DECIMAL(15, 2),
    MONTHLY_CASH_WITHD          INTEGER,
    TOT_CASH_WITHD_AMT_MNTH     DECIMAL(15, 2),
    MONTHLY_CHECK_W             INTEGER,
    TOT_CHECK_W_AMT_MNTH        DECIMAL(15, 2),
    MONTHLY_DOM_IN_WIRE         INTEGER,
    TOT_DOM_IN_WIRE_AMT_MNTH    DECIMAL(15, 2),
    MONTHLY_DOM_OUT_WIRE        INTEGER,
    TOT_DOM_OUT_WIRE_AMT_MNTH   DECIMAL(15, 2),
    REQ_FOR_IN_WIRE_TRANS       SMALLINT,
    MONTHLY_FOR_IN_WIRE         INTEGER,
    TOT_FOR_IN_WIRE_AMT_MNTH    DECIMAL(15, 2),
    ORIG_CNTRY_FOR_IN_WIRES     INTEGER,
    REQ_FOR_OUT_WIRE_TRANS      SMALLINT,
    MONTHLY_FOR_OUT_WIRE        INTEGER,
    TOT_FOR_OUT_WIRE_AMT_MNTH   DECIMAL(15, 2),
    DEST_CNTRY_FOR_OUT_WIRES    INTEGER,
    IS_PROSPECT                 SMALLINT,
    USER1                       INTEGER,
    USER2                       DECIMAL(15, 2),
    USER3                       VARCHAR(40),
    USER4                       VARCHAR(40),
    USER5                       VARCHAR(40),
    DESC_OF_ACCT_PURPOSE        VARCHAR(255),
    POWER_OF_ATTORNEY           SMALLINT,
    REMOTE_DEPOSIT_CAPTURE      SMALLINT,
    REMOTE_DEPOSIT_CAPTURE_RISK VARCHAR(40),
    ACCOUNT_MEMBERS             VARCHAR(1000),
    primary key (ID, WLT_DATE)
);

