create table QA_DAILY_CUSTOMER
(
    WLT_DATE                      DATE        not null,
    ID                            INTEGER     not null,
    PARENT                        INTEGER,
    NAME                          VARCHAR(70) not null,
    DBA                           VARCHAR(40),
    SIC_CODE                      INTEGER,
    ADDRESS                       VARCHAR(120),
    CITY                          VARCHAR(40),
    STATE                         INTEGER,
    ZIP                           CHAR(15),
    COUNTRY                       INTEGER,
    TELEPHONE                     CHAR(20),
    EMAIL                         VARCHAR(60),
    TIN                           CHAR(20),
    PASSPORT_NO                   CHAR(20),
    DOB                           DATE,
    TYPE_OF_BUSINESS              INTEGER,
    SOURCE_OF_FUNDS               VARCHAR(80),
    ACCOUNT_OFFICER               VARCHAR(40),
    ACCT_OFF_TEL                  CHAR(20),
    ACCT_OFF_EMAIL                VARCHAR(60),
    COMPLIANCE_OFFICER            VARCHAR(40),
    COMP_OFF_TEL                  CHAR(20),
    COMP_OFF_EMAIL                VARCHAR(60),
    IDLIST                        VARCHAR(255),
    NOTES                         VARCHAR(2000),
    EXEMPTION_STATUS              CHAR(11),
    OWNER_BRANCH                  INTEGER,
    OWNER_DEPARTMENT              CHAR(11),
    OWNER_OPER                    CHAR(11),
    RISK_CLASS                    CHAR(11),
    COUNTRY_OF_INCORP             INTEGER,
    COUNTRY_OF_ORIGIN             INTEGER,
    OFFSHORE_CORPORATION          INTEGER,
    BEARER_SHARES                 SMALLINT,
    NOME_DE_PLUME                 SMALLINT,
    CTRAMT                        DECIMAL(15, 2),
    USER1                         VARCHAR(70),
    USER2                         INTEGER,
    USER3                         INTEGER,
    USER4                         VARCHAR(40),
    USER5                         VARCHAR(40),
    BUSS_RELATION_NATURE          VARCHAR(40),
    PREV_RELATIONS                VARCHAR(40),
    POLITICAL_POSITION            VARCHAR(40),
    US_PERSON                     VARCHAR(40),
    SEX                           CHAR(1),
    CUSTOMER_TYPE                 INTEGER,
    CORR_BANK_RELATION            SMALLINT,
    HIGH_RISK_RESPONDENT_BANK     SMALLINT,
    OFFSHORE_BANK                 SMALLINT,
    PAYTHROUGH_AC                 SMALLINT,
    PEP                           SMALLINT,
    REGULATED_AFFILIATE           SMALLINT,
    RESIDENT                      SMALLINT,
    RF_CALCULATE                  SMALLINT,
    SHELL_BANK                    SMALLINT,
    LICENSE_NO                    VARCHAR(35),
    LICENSE_STATE                 VARCHAR(40),
    SWIFT_BIC                     CHAR(12),
    EMBASSY                       SMALLINT,
    FOREIGN_GOVT                  SMALLINT,
    CHARITY_ORG                   SMALLINT,
    DOCIP                         SMALLINT,
    PROSPECT                      SMALLINT,
    ASSET_SIZE                    DECIMAL(15, 2),
    INCOME                        DECIMAL(15, 2),
    IND_OR_BUS_TYPE               CHAR(1)     not null,
    FEP                           SMALLINT,
    MSB                           SMALLINT,
    ON_PROBATION                  SMALLINT,
    PROBATION_START               DATE,
    PROBATION_END                 DATE,
    PROBATION_REASON              CHAR(11),
    CLOSED                        SMALLINT,
    CLOSED_DATE                   DATE,
    CLOSED_REASON                 CHAR(11),
    OPEN_DATE                     DATE        not null,
    COUNTRY_OF_RESIDENCE          INTEGER,
    COUNTRY_OF_CITIZENSHIP        INTEGER,
    NAME_PREFIX                   CHAR(25),
    FIRST_NAME                    VARCHAR(50),
    MIDDLE_NAME                   VARCHAR(50),
    LAST_NAME                     VARCHAR(50),
    NAME_SUFFIX                   CHAR(25),
    ALIAS                         VARCHAR(50),
    PLACE_OF_BIRTH                VARCHAR(50),
    MOTHERS_MAIDEN_NAME           VARCHAR(50),
    INTRODUCER                    VARCHAR(50),
    YRS_AT_CURR_ADDRESS           INTEGER,
    NO_OF_DEPENDANTS              SMALLINT,
    EMPLOYER_NAME                 VARCHAR(50),
    JOB_TITLE                     VARCHAR(50),
    JOB_TIME                      VARCHAR(50),
    LENGTH_OF_EMPL                VARCHAR(25),
    IS_ALIEN                      SMALLINT,
    COUNTRY_OF_DUAL_CITIZENSHIP   INTEGER,
    SECONDARY_EMPLOYER            VARCHAR(50),
    ORIGIN_OF_FUNDS               VARCHAR(50),
    IS_PERSONAL_RELATIONSHIP      SMALLINT,
    DATE_OF_INCEPTION             DATE,
    LEGAL_ENTITY_TYPE             VARCHAR(50),
    NO_OF_EMPLOYEES               INTEGER,
    TOTAL_ANNUAL_SALES            VARCHAR(50),
    PRODUCTS_SOLD                 VARCHAR(255),
    SERVICES_PROVIDED             VARCHAR(255),
    GEOGRAPHICAL_AREAS_SERVED     VARCHAR(255),
    PUBLICLY_TRADED               SMALLINT,
    TICKER_SYMBOL                 CHAR(10),
    EXCHANGE                      VARCHAR(50),
    IS_PENSION_FUND               SMALLINT,
    IS_ENDOWMENT_FUND             SMALLINT,
    IS_GOVERMENT_SPONSORED        SMALLINT,
    IS_SUBSIDIARY                 SMALLINT,
    IS_FOREIGN_CORR_BANK          SMALLINT,
    REQUIRE_CASH_TRANS            SMALLINT,
    REQUIRE_FOREIGN_TRANS         SMALLINT,
    REQUIRE_WIRE_TRANS            SMALLINT,
    HAS_FOREIGN_BRANCHES          SMALLINT,
    FOREIGN_BRANCH_COUNTRIES      VARCHAR(255),
    TYPE_OF_MON_INSTRUMENTS       VARCHAR(255),
    URL                           VARCHAR(255),
    HAS_PATRIOT_ACT_CERTIFICATION SMALLINT,
    PATRIOT_ACT_CERT_EXPIRY_DATE  DATE,
    MONEY_ORDERS                  SMALLINT,
    MO_REGISTRATION               CHAR(10),
    MO_REG_CONFIRMATION_NO        VARCHAR(50),
    MO_ACTING_AGENT_FOR           CHAR(20),
    MO_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    MO_MONTHLY_AMNT               DECIMAL(15, 2),
    MO_PERCENT_INCOME             CHAR(5),
    TRAVELERS_CHECK               SMALLINT,
    TC_REGISTRATION               CHAR(10),
    TC_REG_CONFIRMATION_NO        VARCHAR(50),
    TC_ACTING_AGENT_FOR           CHAR(20),
    TC_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    TC_MONTHLY_AMNT               DECIMAL(15, 2),
    TC_PERCENT_INCOME             CHAR(5),
    MONEY_TRANSMISSION            SMALLINT,
    MT_REGISTRATION               CHAR(10),
    MT_REG_CONFIRMATION_NO        VARCHAR(50),
    MT_ACTING_AGENT_FOR           CHAR(20),
    MT_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    MT_MONTHLY_AMNT               DECIMAL(15, 2),
    MT_PERCENT_INCOME             CHAR(5),
    CHECK_CACHING                 SMALLINT,
    CC_REGISTRATION               CHAR(10),
    CC_REG_CONFIRMATION_NO        VARCHAR(50),
    CC_ACTING_AGENT_FOR           CHAR(20),
    CC_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    CC_MONTHLY_AMNT               DECIMAL(15, 2),
    CC_PERCENT_INCOME             CHAR(5),
    CURRENCY_EXCHANGE             SMALLINT,
    CE_REGISTRATION               CHAR(10),
    CE_REG_CONFIRMATION_NO        VARCHAR(50),
    CE_ACTING_AGENT_FOR           CHAR(20),
    CE_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    CE_MONTHLY_AMNT               DECIMAL(15, 2),
    CE_PERCENT_INCOME             CHAR(5),
    CURRENCY_DEALING              SMALLINT,
    CD_REGISTRATION               CHAR(10),
    CD_REG_CONFIRMATION_NO        VARCHAR(50),
    CD_ACTING_AGENT_FOR           CHAR(20),
    CD_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    CD_MONTHLY_AMNT               DECIMAL(15, 2),
    CD_PERCENT_INCOME             CHAR(5),
    STORED_VALUE                  SMALLINT,
    SV_REGISTRATION               CHAR(10),
    SV_REG_CONFIRMATION_NO        VARCHAR(50),
    SV_ACTING_AGENT_FOR           CHAR(20),
    SV_MAX_DAILY_AMNT_PER_PERSON  DECIMAL(15, 2),
    SV_MONTHLY_AMNT               DECIMAL(15, 2),
    SV_PERCENT_INCOME             CHAR(5),
    CDDUSER1                      VARCHAR(40),
    CDDUSER2                      VARCHAR(40),
    CDDUSER3                      VARCHAR(40),
    CDDUSER4                      VARCHAR(40),
    CDDUSER5                      VARCHAR(40),
    CDDUSER6                      VARCHAR(40),
    CDDUSER7                      VARCHAR(40),
    CDDUSER8                      VARCHAR(40),
    CDDUSER9                      VARCHAR(40),
    CDDUSER10                     VARCHAR(40),
    CDDUSER11                     VARCHAR(40),
    CDDUSER12                     VARCHAR(40),
    CDDUSER13                     VARCHAR(40),
    CDDUSER14                     VARCHAR(40),
    CDDUSER15                     VARCHAR(40),
    CDDUSER16                     VARCHAR(40),
    CDDUSER17                     VARCHAR(40),
    CDDUSER18                     VARCHAR(40),
    CDDUSER19                     VARCHAR(40),
    CDDUSER20                     VARCHAR(40),
    CDDUSER21                     VARCHAR(40),
    CDDUSER22                     VARCHAR(40),
    CDDUSER23                     VARCHAR(40),
    CDDUSER24                     VARCHAR(40),
    CDDUSER25                     VARCHAR(40),
    CDDUSER26                     VARCHAR(40),
    CDDUSER27                     VARCHAR(40),
    CDDUSER28                     VARCHAR(40),
    CDDUSER29                     VARCHAR(40),
    CDDUSER30                     VARCHAR(40),
    CDDUSER31                     VARCHAR(100),
    CDDUSER32                     VARCHAR(100),
    CDDUSER33                     VARCHAR(100),
    CDDUSER34                     VARCHAR(100),
    CDDUSER35                     VARCHAR(100),
    CDDUSER36                     VARCHAR(100),
    CDDUSER37                     VARCHAR(100),
    CDDUSER38                     VARCHAR(100),
    CDDUSER39                     VARCHAR(100),
    CDDUSER40                     VARCHAR(100),
    RELATION_WITH_BANK_AFFILIATE  SMALLINT,
    PRIVATE_INVESTMENT_COMPANY    SMALLINT,
    NEGATIVE_PRESS_SEARCH_RESULT  VARCHAR(255),
    primary key (ID, WLT_DATE)
);

