create table QUERIES_CRITERIA
(
    ORDER_UNIT         INTEGER,
    ORDER_USR          CHAR(8),
    TMPSTAMP           TIMESTAMP(6),
    PRFT_SYSTEM        SMALLINT,
    ID_TRANSACT        INTEGER,
    CNT_4_TO           SMALLINT,
    CNT_1_TO           SMALLINT,
    CNT_3_TO           SMALLINT,
    CNT_1_FROM         SMALLINT,
    CNT_4_FROM         SMALLINT,
    CNT_2_FROM         SMALLINT,
    CNT_2_TO           SMALLINT,
    CNT_3_FROM         SMALLINT,
    YEAR_TO            SMALLINT,
    YEAR_FROM          SMALLINT,
    PRODUCT_ID_TO      INTEGER,
    PRODUCT_ID         INTEGER,
    GD_SERIAL_NUM_4    INTEGER,
    GD_SERIAL_NUM_3_TO INTEGER,
    GD_SERIAL_NUM_3_FR INTEGER,
    GD_SERIAL_NUM_2_TO INTEGER,
    GD_SERIAL_NUM_2_FR INTEGER,
    GD_SERIAL_NUM_1_TO INTEGER,
    GD_SERIAL_NUM_1_FR INTEGER,
    GD_SERIAL_NUM      INTEGER,
    TARGET_UNIT        INTEGER,
    ID_INTEREST_FL_TO  INTEGER,
    ID_INTEREST_FL_FRO INTEGER,
    ID_INTEREST_CT_TO  INTEGER,
    ID_INTEREST_CT_FRO INTEGER,
    CURRENCY_ID        INTEGER,
    CURRENCY_L_ID      INTEGER,
    TO_UNIT_1          INTEGER,
    TO_AMM_1           DECIMAL(15, 2),
    TO_AMM_2           DECIMAL(15, 2),
    TO_AMM_3           DECIMAL(15, 2),
    TO_AMM_4           DECIMAL(15, 2),
    TO_AMM_5           DECIMAL(15, 2),
    FROM_AMM_1         DECIMAL(15, 2),
    FROM_AMM_2         DECIMAL(15, 2),
    FROM_AMM_3         DECIMAL(15, 2),
    FROM_AMM_4         DECIMAL(15, 2),
    FROM_AMM_5         DECIMAL(15, 2),
    TO_DATE_5          DATE,
    FROM_DATE_6        DATE,
    FROM_DATE_5        DATE,
    FROM_DATE_4        DATE,
    FROM_DATE_3        DATE,
    FROM_DATE_2        DATE,
    TO_DATE_1          DATE,
    TO_DATE_2          DATE,
    TO_DATE_3          DATE,
    TO_DATE_4          DATE,
    PRINT_DEL_DT       DATE,
    TO_DATE_6          DATE,
    FROM_DATE_1        DATE,
    ORDER_STATUS       CHAR(1),
    LOAN_STATUS        CHAR(1),
    REQUEST_TYPE       CHAR(1),
    ACC_STATUS         CHAR(1),
    OV_EXP_EXT_FLG     CHAR(1),
    REQUEST_STS        CHAR(1),
    REQUEST_LOAN_STS   CHAR(1),
    AGR_STATUS         CHAR(1),
    TO_USR_1           CHAR(8),
    OFFICER_1_ID_FROM  CHAR(8),
    OFFICER_1_ID_TO    CHAR(8),
    OFFICER_2_ID_FROM  CHAR(8),
    FROM_USR_1         CHAR(8),
    OFFICER_2_ID_TO    CHAR(8)
);

create unique index IXU_QUE_001
    on QUERIES_CRITERIA (ORDER_UNIT, ORDER_USR, TMPSTAMP, PRFT_SYSTEM, ID_TRANSACT);

