create table R_ACCOUNT_COLLATER
(
    FK_CUSTOMERCUST_ID      INTEGER     not null,
    FK_COLLATERALFK_UN      INTEGER     not null,
    FK_COLLATERALFK_CO      INTEGER     not null,
    FK_COLLATERALCOLLA      DECIMAL(10) not null,
    PRFT_ACCOUNT            CHAR(40)    not null,
    INTERNAL_SN             SMALLINT    not null,
    PROFITS_SYSTEM          INTEGER,
    REVAL_CURR_FIX_RAT      DECIMAL(12, 6),
    REVAL_INIT_FIX_RAT      DECIMAL(12, 6),
    REVAL_INIT_SV           DECIMAL(15, 2),
    REVALUATION_CURRID      INTEGER,
    YIELD_UTILISED_AMN      DECIMAL(15, 2),
    YIELD_LIMIT_AMN         DECIMAL(15, 2),
    YIELD_PERC              DECIMAL(8, 4),
    CB_INSURANCE_AMN        DECIMAL(15, 2),
    UNIT_CODE               INTEGER,
    ISSUER_ACCOUNT          DECIMAL(13),
    BANK_CODE               SMALLINT,
    ITEMS_CNT               INTEGER,
    EST_VALUE_AMN           DECIMAL(15, 2),
    EST_INSURANCE_AMN       DECIMAL(15, 2),
    EXPIRY_DT               DATE,
    INSERTION_DT            DATE,
    TMSTAMP                 TIMESTAMP(6),
    DEP_ACC_IND             CHAR(1),
    ENTRY_STATUS            CHAR(1),
    NOTE_STATUS             CHAR(1),
    ACCOUNT_CD              SMALLINT,
    USER_CODE               CHAR(8),
    REFERENCE_NUMBER        CHAR(20),
    AFM_NO                  CHAR(20),
    FIRST_NAME              VARCHAR(20),
    ADDRESS                 VARCHAR(40),
    SURNAME                 VARCHAR(70),
    BLOCK_TRX_DATE          DATE,
    BLOCK_TRX_UNIT          INTEGER,
    BLOCK_TRX_USR           CHAR(8),
    BLOCK_TRX_USR_SN        INTEGER,
    MORTGAGE_AMN            DECIMAL(15, 2),
    MORTGAGE_CLASS          CHAR(1),
    MORTGAGE_DATE           DATE,
    PROVISIONS_CALC_DT      DATE,
    PROVISIONS_OMV          DECIMAL(15, 2),
    PROVISIONS_OMV_CURR     INTEGER,
    PROVISIONS_OMV_ACC_CURR DECIMAL(15, 2),
    PROVISIONS_FIXING       DECIMAL(8, 4),
    PROVISIONS_ACC_BAL      DECIMAL(15, 2),
    PROVISIONS_TOT_BAL      DECIMAL(15, 2),
    PROVISIONS_CALC_AMN     DECIMAL(15, 2),
    PROVISIONS_ACC_CURR     INTEGER,
    PROVISIONS_MECHANISM    SMALLINT,
    PROVISIONS_BAL_1        DECIMAL(15, 2),
    PROVISIONS_BAL_2        DECIMAL(15, 2),
    PROVISIONS_BAL_3        DECIMAL(15, 2),
    REVAL_LAST_DT           DATE
);

