create table R_AGREEMENT_GUARAN
(
    FK_AGREEMENTFK_UNI INTEGER,
    FK_AGREEMENTAGR_YE SMALLINT,
    FK_AGREEMENTAGR_SN INTEGER,
    FK_AGREEMENTAGR_ME INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    TMSTAMP            TIMESTAMP(6),
    GUARANTEE_AMOUNT   DECIMAL(15, 2),
    REMOVAL_DT         DATE,
    GUARANTOR_STATUS   CHAR(1),
    AGR_PERC_AMOUNT    DECIMAL(15, 2),
    GUARANTEE_DT       DATE,
    ADDRESS_SN         INTEGER,
    RECEIPIENT_FLAG    CHAR(1)
);

