create table R_CUST_COLL_TOTALS
(
    CUSTOMER_ID        INTEGER,
    COLLATERAL_CATEGOR CHAR(1),
    COLLATERAL_TYPE    INTEGER,
    CURRENCY           INTEGER,
    CB_INSURANCE_DB    DECIMAL(15, 2),
    CB_INSURANCE_CR    DECIMAL(15, 2),
    YIELD_UTILISED_AMN DECIMAL(15, 2),
    ESTIMATED_INSUR_CR DECIMAL(15, 2),
    ESTIMATED_INSUR_DB DECIMAL(15, 2),
    YIELD_LIMIT_AMN    DECIMAL(15, 2),
    ESTIMATED_VALUE_DB DECIMAL(15, 2),
    ESTIMATED_VALUE_CR DECIMAL(15, 2)
);

