create table R_CUSTOMER_CREDIT
(
    FK_CURRENCYID_CURR INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    TMSTAMP            TIMESTAMP(6),
    FK_UNITCODE        INTEGER,
    HISTORY_CNT        DECIMAL(10),
    CRLINE_AMOUNT      DECIMAL(15, 2),
    UTILISED_AMOUNT    DECIMAL(15, 2),
    EXPIRY_DATE        DATE,
    REEVALUATION_DT    DATE,
    EVALUATION_DT      DATE,
    ENTRY_STATUS       CHAR(1),
    INTRACOM_FLG       CHAR(1),
    FK_USRCODE         CHAR(8)
);

