create table RATE_TABLE
(
    EXCH_NOTES_FLAG    CHAR(1),
    FK_CURRENCYID_CURR INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    RATE_TABLE_NUMBER  DECIMAL(10),
    SCALE_MAX_AMOUNT   DECIMAL(15, 2),
    MIN_NEGOT_UNIT     SMALLINT,
    MULTIPLIER         INTEGER,
    BUY_RATE           DECIMAL(12, 6),
    FIXING_RATE        DECIMAL(12, 6),
    SELL_RATE          DECIMAL(12, 6),
    BUY_RATE_MT        DECIMAL(12, 6),
    ACTIVATION_DATE    DATE,
    TMSTAMP            TIMESTAMP(6),
    ACTIVATION_TIME    TIME
);

create unique index IXU_RAT_000
    on RATE_TABLE (EXCH_NOTES_FLAG, FK_CURRENCYID_CURR, FK_CUSTOMERCUST_ID, FK_GENERIC_DETAFK, FK_GENERIC_DETASER,
                   RATE_TABLE_NUMBER, SCALE_MAX_AMOUNT);

