create table RATE_TABLE_FACTORS
(
    FK_CURRENCYID_CURR INTEGER,
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    EXCH_NOTES_FLAG    CHAR(1),
    SCALE_MAX_AMOUNT   DECIMAL(15, 2),
    SELL_OFFSET        DECIMAL(7, 4),
    OPEN_MORE          DECIMAL(7, 4),
    BUY_PERCENTAGE     DECIMAL(7, 4),
    SELL_PERCENTAGE    DECIMAL(7, 4),
    BUY_OFFSET         DECIMAL(7, 4),
    OPEN_MARKET_MT     DECIMAL(7, 4),
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    USED_IN_TABLE      CHAR(1),
    BUY_PIPS           DECIMAL(7, 5) default 0,
    SELL_PIPS          DECIMAL(7, 5) default 0
);

create unique index IXU_RAT_001
    on RATE_TABLE_FACTORS (FK_CURRENCYID_CURR, FK_GENERIC_DETAFK, FK_GENERIC_DETASER, FK_CUSTOMERCUST_ID,
                           EXCH_NOTES_FLAG, SCALE_MAX_AMOUNT);

