create table REAL_ESTATE
(
    ID                     DECIMAL(10) not null
        constraint IXU_COL_036
            primary key,
    REAL_ESTATE_DESC       CHAR(40),
    REAL_ESTATE_TYPE       CHAR(2),
    OWNERSHIP_IND          CHAR(1),
    REAL_ESTATE_CAT        CHAR(254),
    MAIN_AREA              DECIMAL(18, 4),
    ADDITIONAL_AREA        DECIMAL(18, 4),
    APARTMENT_NUM          CHAR(40),
    CONSTRUCTION_YEAR      SMALLINT,
    FRONTAGE_IND           CHAR(1),
    INSURANCE_DESCR        CHAR(254),
    INSURANCE_AMN          DECIMAL(15, 2),
    INS_ORIGINAL_AMN       DECIMAL(15, 2),
    AGREEMENT_VALUE        DECIMAL(15, 2),
    ADDRESS                CHAR(80),
    ADDRESS_NUM            CHAR(10),
    ZIP_CODE               CHAR(10),
    CITY                   CHAR(50),
    REGION                 CHAR(60),
    MUNICIPALITY           CHAR(40),
    COMMERCIAL_VAL_AMN     DECIMAL(15, 2),
    EST_INSUR_AMN          DECIMAL(15, 2),
    OBJECTIVE_AMN          DECIMAL(15, 2),
    EVALLUATION_IND        CHAR(1),
    ADD_DESCR1             CHAR(80),
    ADD_DESCR2             CHAR(80),
    ADD_DESCR3             CHAR(80),
    ADD_DESCR4             CHAR(80),
    ADD_DESCR5             CHAR(80),
    TRX_UNIT               INTEGER,
    INSERTION_USR          CHAR(8),
    INSERTION_DT           DATE,
    MODIFICATION_DT        DATE,
    MODIFICATION_USR       CHAR(8),
    ENTRY_STATUS           CHAR(1),
    FK_GH_ADDDI            CHAR(5),
    FK_GD_ADDDI            INTEGER,
    FK_GH_CAT              CHAR(5),
    FK_GD_CAT              INTEGER,
    FK_GH_CAT_BANK         CHAR(5),
    FK_GD_CAT_BANK         INTEGER,
    FK_GH_COUNTRY          CHAR(5),
    FK_GD_COUNTRY          INTEGER,
    FK_GH_DESCR            CHAR(5),
    FK_GD_DESCR            INTEGER,
    FK_GH_FLOOR            CHAR(5),
    FK_GD_FLOOR            INTEGER,
    FK_GH_INS_COMP         CHAR(5),
    FK_GD_INS_COMP         INTEGER,
    FK_GH_INS_KIND         CHAR(5),
    FK_GD_INS_KIND         INTEGER,
    INSURANCE_SD           DATE,
    INSURANCE_ED           DATE,
    ANNUAL_RENT_AMN        DECIMAL(15, 2),
    BUILD_LICENCEID        CHAR(20),
    CONSTR_COST_AMN        DECIMAL(15, 2),
    FK_GD_BASAK            INTEGER,
    FK_GD_HAS_RENT_TYPE    INTEGER,
    FK_GH_BASAK            CHAR(5),
    FK_GH_HAS_RENT_TYPE    CHAR(5),
    ISSUE_YEAR             SMALLINT,
    LAND_REGIST_ID         CHAR(50),
    LEGAL_PROBLEMS         VARCHAR(500),
    MON_TOT_PARK_NUM       INTEGER,
    MON_TOT_STORE_NUM      INTEGER,
    MORTGAGE_AREA          DECIMAL(18, 4),
    OUTDOOR_ATTIC_A        DECIMAL(18, 4),
    PARKING_VAL_AMN        DECIMAL(15, 2),
    REAL_EST_VAL_AMN       DECIMAL(15, 2),
    REEVAL_FREQ            SMALLINT,
    RENTAL_DATE            DATE,
    RENTING_COMMENTS       VARCHAR(255),
    SITE_VALUE_AMN         DECIMAL(15, 2),
    STORE_ROOM_NUM         INTEGER,
    STORE_VALUE_AMN        DECIMAL(15, 2),
    TOT_PARK_AREA          DECIMAL(18, 4),
    TOT_PARK_NUM           INTEGER,
    TOT_STORE_AREA         DECIMAL(18, 4),
    TOTAL_SITE_AREA        DECIMAL(18, 4),
    TOTAL_VALUE_AMN        DECIMAL(15, 2),
    URBAN_PLAN_PRO         VARCHAR(500),
    VALUE_DATE             DATE,
    PAR_LAND_REGIST_ID     CHAR(50),
    REGISTRY               CHAR(2),
    REGISTRY_TITLE_NO      CHAR(50),
    DISTRICT_REGISTRY      CHAR(30),
    BUILDING               CHAR(100),
    UNIT_NO                CHAR(10),
    ESTATE                 CHAR(100),
    COURT                  CHAR(100),
    FK_GH_TITLE_NT         CHAR(5),
    FK_GD_TITLE_NT         INTEGER,
    TITLE_ISSUE_DT         DATE,
    TITLE_TERM             INTEGER,
    TITLE_EXPIRY_DT        DATE,
    TITLE_NATURE_TYPE      CHAR(2),
    FK_GH_TS_AREA          CHAR(5),
    FK_GD_TS_AREA          INTEGER,
    FK_GH_MN_AREA          CHAR(5),
    FK_GD_MN_AREA          INTEGER,
    FK_GH_OA_AREA          CHAR(5),
    FK_GD_OA_AREA          INTEGER,
    FK_GH_AD_AREA          CHAR(5),
    FK_GD_AD_AREA          INTEGER,
    FK_GH_MG_AREA          CHAR(5),
    FK_GD_MG_AREA          INTEGER,
    FK_GH_ST_AREA          CHAR(5),
    FK_GD_ST_AREA          INTEGER,
    FK_GH_PR_AREA          CHAR(5),
    FK_GD_PR_AREA          INTEGER,
    FOLIO                  CHAR(2),
    FK_GH_DIST             CHAR(5),
    FK_GD_DIST             INTEGER,
    FK_GH_SUBCOUNTY        CHAR(5),
    FK_GD_SUBCOUNTY        INTEGER,
    INSUR_ANNUAL_AMNT      DECIMAL(15, 2),
    PLOT_NUMBER            CHAR(10),
    BLOCK_NUMBER           CHAR(4),
    COND_PLAN_NO           CHAR(15),
    INSTRUMENT_NO          CHAR(14),
    MARKETABILITY          CHAR(2),
    GPS_COORD              CHAR(20),
    COPY_OF_TITLE          CHAR(1),
    TITLE_SUBM_DT          DATE,
    TITLE_RETURN_DT        DATE,
    FK_CUST_ADDR_PASN      INTEGER,
    FK_CUST_ADDR_PACO      CHAR(8),
    FK_TITL_ADDR_PASN      INTEGER,
    FK_TITL_ADDR_PACO      CHAR(8),
    INSUR_POLICY_NO        CHAR(40),
    BELONGS_TO_REAL_ESTATE DECIMAL(10),
    DISTRIBUTION_AGREEMENT CHAR(1),
    REAL_ESTATE_RESTRICT   CHAR(1),
    FUNDED                 CHAR(1),
    LEASED                 CHAR(1),
    TOTAL_MORTGAGED_SHARE  CHAR(20),
    TOTAL_REGISTERED_SHARE CHAR(20),
    SEGMENT                CHAR(15),
    FK_GH_IS_INSURED       CHAR(5),
    FK_GD_IS_INSURED       INTEGER,
    ADEQUATELY_INSURED     CHAR(1),
    SECTION                VARCHAR(80)
);

