create table REAL_ESTATE_CUST
(
    INTERNAL_SN        DECIMAL(10) not null,
    ENTRY_STATUS       CHAR(1),
    FK_REAL_ESTATEID   DECIMAL(10) not null,
    FK_CUSTOMERCUST_ID INTEGER,
    CONTRACT_ID        VARCHAR(255),
    FK_GD_OWNER_TYPE   INTEGER,
    FK_GH_OWNER_TYPE   CHAR(5),
    OWNERSH_PERC       DECIMAL(8, 4),
    REGIST_PROPRIETOR  CHAR(40),
    MORTGAGED_SHARE    CHAR(20),
    REGISTERED_SHARE   CHAR(20),
    constraint IXU_COL_037
        primary key (FK_REAL_ESTATEID, INTERNAL_SN)
);

