create table RECON_GENERIC_TABLE
(
    FK_TYPE               INTEGER            not null,
    FK_RECON_LOADED_FILES BIGINT             not null,
    ID                    BIGINT             not null,
    ENTRY_STATUS          SMALLINT default 0 not null,
    LAST_PROCESS_DATE     TIMESTAMP(6),
    AMOUNT_1              DECIMAL(18, 2),
    AMOUNT_2              DECIMAL(18, 2),
    AMOUNT_3              DECIMAL(18, 2),
    AMOUNT_4              DECIMAL(18, 2),
    AMOUNT_5              DECIMAL(18, 2),
    AMOUNT_6              DECIMAL(18, 2),
    AMOUNT_7              DECIMAL(18, 2),
    AMOUNT_8              DECIMAL(18, 2),
    AMOUNT_9              DECIMAL(18, 2),
    AMOUNT_10             DECIMAL(18, 2),
    AMOUNT_11             DECIMAL(18, 2),
    AMOUNT_12             DECIMAL(18, 2),
    AMOUNT_13             DECIMAL(18, 2),
    AMOUNT_14             DECIMAL(18, 2),
    AMOUNT_15             DECIMAL(18, 2),
    AMOUNT_16             DECIMAL(18, 2),
    AMOUNT_17             DECIMAL(18, 2),
    AMOUNT_18             DECIMAL(18, 2),
    AMOUNT_19             DECIMAL(18, 2),
    AMOUNT_20             DECIMAL(18, 2),
    AMOUNT_21             DECIMAL(18, 2),
    AMOUNT_22             DECIMAL(18, 2),
    AMOUNT_23             DECIMAL(18, 2),
    AMOUNT_24             DECIMAL(18, 2),
    AMOUNT_25             DECIMAL(18, 2),
    AMOUNT_26             DECIMAL(18, 2),
    AMOUNT_27             DECIMAL(18, 2),
    AMOUNT_28             DECIMAL(18, 2),
    AMOUNT_29             DECIMAL(18, 2),
    AMOUNT_30             DECIMAL(18, 2),
    TEXT_1                CHAR(100),
    TEXT_2                CHAR(100),
    TEXT_3                CHAR(100),
    TEXT_4                CHAR(100),
    TEXT_5                CHAR(100),
    TEXT_6                CHAR(100),
    TEXT_7                CHAR(100),
    TEXT_8                CHAR(100),
    TEXT_9                CHAR(100),
    TEXT_10               CHAR(100),
    TEXT_11               CHAR(100),
    TEXT_12               CHAR(100),
    TEXT_13               CHAR(100),
    TEXT_14               CHAR(100),
    TEXT_15               CHAR(100),
    TEXT_16               CHAR(100),
    TEXT_17               CHAR(100),
    TEXT_18               CHAR(100),
    TEXT_19               CHAR(100),
    TEXT_20               CHAR(100),
    DATE_1                DATE,
    DATE_2                DATE,
    DATE_3                DATE,
    DATE_4                DATE,
    DATE_5                DATE,
    DATE_6                DATE,
    DATE_7                DATE,
    DATE_8                DATE,
    DATE_9                DATE,
    DATE_10               DATE,
    DATE_11               DATE,
    DATE_12               DATE,
    DATE_13               DATE,
    DATE_14               DATE,
    DATE_15               DATE,
    DATE_16               DATE,
    DATE_17               DATE,
    DATE_18               DATE,
    DATE_19               DATE,
    DATE_20               DATE,
    LARGE_BLOB_1          BLOB(1048576),
    LARGE_BLOB_2          BLOB(1048576),
    LARGE_BLOB_3          BLOB(1048576),
    LARGE_BLOB_4          BLOB(1048576),
    LARGE_TEXT_5          BLOB(1048576),
    TIMESTAMP_1           TIMESTAMP(6),
    TIMESTAMP_2           TIMESTAMP(6),
    TIMESTAMP_3           TIMESTAMP(6),
    TIMESTAMP_4           TIMESTAMP(6),
    TIMESTAMP_5           TIMESTAMP(6),
    NUMERIC_1             BIGINT,
    NUMERIC_2             BIGINT,
    NUMERIC_3             BIGINT,
    NUMERIC_4             BIGINT,
    NUMERIC_5             BIGINT,
    NUMERIC_6             BIGINT,
    NUMERIC_7             BIGINT,
    NUMERIC_8             BIGINT,
    NUMERIC_9             BIGINT,
    NUMERIC_10            BIGINT,
    TIME_1                DATE,
    TIME_2                DATE,
    TIME_3                DATE,
    TIME_4                DATE,
    TIME_5                DATE,
    TEXT_21               CHAR(100),
    TEXT_22               CHAR(100),
    TEXT_23               CHAR(100),
    TEXT_24               CHAR(100),
    TEXT_25               CHAR(100),
    TEXT_26               CHAR(100),
    TEXT_27               CHAR(100),
    TEXT_28               CHAR(100),
    TEXT_29               CHAR(100),
    TEXT_30               CHAR(100),
    TEXT_31               CHAR(100),
    TEXT_32               CHAR(100),
    TEXT_33               CHAR(100),
    TEXT_34               CHAR(100),
    TEXT_35               CHAR(100),
    TEXT_36               CHAR(100),
    TEXT_37               CHAR(100),
    TEXT_38               CHAR(100),
    TEXT_39               CHAR(100),
    TEXT_40               CHAR(100),
    DECIMAL_1             DECIMAL(12, 6),
    DECIMAL_2             DECIMAL(12, 6),
    DECIMAL_3             DECIMAL(12, 6),
    DECIMAL_4             DECIMAL(12, 6),
    DECIMAL_5             DECIMAL(12, 6),
    COMMENTS              VARCHAR(400),
    constraint RECON_GENERIC_TABLE_PK
        primary key (FK_RECON_LOADED_FILES, ID)
);

create unique index INX_TYPE_STATUS
    on RECON_GENERIC_TABLE (FK_TYPE, ENTRY_STATUS);

