create table REG_REP_02
(
    BUSINESS_DATE  DATE,
    ROW_NO         SMALLINT,
    APPLICATION_NO DECIMAL(27, 3),
    APPROVED_NO    DECIMAL(10),
    MATURITY_AMT1  DECIMAL(27, 3),
    MATURITY_AMT2  DECIMAL(27, 3),
    MATURITY_AMT3  DECIMAL(27, 3),
    MATURITY_AMT4  DECIMAL(27, 3)
);

