create table RELATIONSHIP
(
    FKCUST_HAS_AS_FIRS INTEGER,
    FKCUST_HAS_AS_SECO INTEGER,
    FK_RELATIONSHIPTYP CHAR(12),
    EFFECTIVE_FROM     DATE,
    TMSTAMP            TIMESTAMP(6),
    EXPIRY_DATE        DATE,
    REL_COMMENTS       CHAR(100),
    PERCENTAGE         DECIMAL(5, 2)
);

create unique index IXSECO
    on RELATIONSHIP (FKCUST_HAS_AS_SECO, FK_RELATIONSHIPTYP);

create unique index IXU_REL_002
    on RELATIONSHIP (FKCUST_HAS_AS_FIRS, FKCUST_HAS_AS_SECO, FK_RELATIONSHIPTYP);

