create table RELATIONSHIP_REASO
(
    FKCUST_HAS_AS_FIRS INTEGER,
    FKCUST_HAS_AS_SECO INTEGER,
    FK_RELATIONSHIPFK  CHAR(12),
    REASON_ACCOUNT     CHAR(20),
    REASON_TYPE        CHAR(1),
    TMSTAMP            TIMESTAMP(6),
    COMMENTS_2         CHAR(80),
    COMMENTS_1         CHAR(80)
);

create unique index IXU_REL_004
    on RELATIONSHIP_REASO (FKCUST_HAS_AS_FIRS, FKCUST_HAS_AS_SECO, FK_RELATIONSHIPFK, REASON_ACCOUNT, REASON_TYPE);

