create table REP_COLLECTION_U
(
    TMPSTMP              TIMESTAMP(6) not null,
    COLLECTION_AGENCY    INTEGER      not null,
    ACC_UNIT             INTEGER      not null,
    ACC_TYPE             SMALLINT     not null,
    ACC_SN               INTEGER      not null,
    CUST_ID              INTEGER      not null,
    ACC_CD               SMALLINT,
    SEND_FLAG            CHAR(1),
    DATE_CREATE          DATE,
    DATE_SEND            DATE,
    ACC_NO               CHAR(8),
    PRODUCT_ID           INTEGER,
    PARTICIPANT_TYPE     SMALLINT,
    PRODUCT_DESCR        CHAR(40),
    CUSTOMER_NAME        CHAR(40),
    HOME_ADDRESS         CHAR(40),
    HOME_CITY            CHAR(20),
    HOME_ZIP_CODE        CHAR(7),
    BUSINESS_ADDRESS     CHAR(40),
    BUSINESS_CITY        CHAR(20),
    BUSINESS_ZIP_CODE    CHAR(7),
    HOME_PHONE           CHAR(20),
    BUSINESS_PHONE       CHAR(20),
    COMPANY_NAME         CHAR(30),
    PROF_ID              INTEGER,
    PROF_DESCRIPTION     CHAR(20),
    AFM_NO               CHAR(10),
    ID_NO                CHAR(10),
    WITHDRAWAL_CAPITAL   DECIMAL(15, 2),
    ACTIVE_CAPITAL       DECIMAL(15, 2),
    WITHDRAWAL_DATE      CHAR(8),
    ACCOUNTING_BAL       DECIMAL(15, 2),
    INSTALMENT_AMOUNT    DECIMAL(15, 2),
    UNPAID_INSTALMENT_NO SMALLINT,
    UNPAID_AMOUNT        DECIMAL(15, 2),
    LAST_PAYMENT_AMOUNT  DECIMAL(15, 2),
    LAST_PAYMENT_DT      CHAR(8),
    constraint IXU_CIU_053
        primary key (CUST_ID, ACC_SN, ACC_TYPE, ACC_UNIT, COLLECTION_AGENCY, TMPSTMP)
);

