create table REP_74760
(
    ACC_UNIT     INTEGER,
    ACC_TYPE     SMALLINT,
    ACC_SN       INTEGER,
    LOAN_STATUS  CHAR(1),
    TRX_DATE     DATE,
    TMSTAMP      TIMESTAMP(6),
    TRX_CODE     INTEGER,
    FORECAST_AMT DECIMAL(15, 2),
    TRX_USR_SN   INTEGER
);

create unique index IXU_LOA_065
    on REP_74760 (ACC_UNIT, ACC_TYPE, TMSTAMP, LOAN_STATUS, TRX_DATE, ACC_SN, TRX_USR_SN);

