create table REP_MONTH_YEAR_SPREAD
(
    CURRENCY_ID    INTEGER,
    UNIT_CODE      INTEGER,
    PRODUCT_ID     INTEGER,
    YEAR_POS_RATE  DECIMAL(11, 4),
    MONTH_POS_RATE DECIMAL(11, 4),
    MULT_YEAR_POS  DECIMAL(15, 2),
    MULT_YEAR_NEG  DECIMAL(15, 2),
    MONTH_POS_BAL  DECIMAL(15, 2),
    YEAR_NEG_BAL   DECIMAL(15, 2),
    YEAR_NEG_RATE  DECIMAL(15, 2),
    MONTH_NEG_BAL  DECIMAL(15, 2),
    MONTH_NEG_RATE DECIMAL(15, 2),
    MULT_MONTH_POS DECIMAL(15, 2),
    YEAR_POS_BAL   DECIMAL(15, 2),
    MULT_MONTH_NEG DECIMAL(15, 2),
    CURR_DESC      CHAR(5),
    PRFT_SYSTEM    VARCHAR(3),
    ACC_DAILY_TYPE VARCHAR(3),
    UNIT_NAME      VARCHAR(40)
);

