create table REP_COLLECTION
(
    CUST_ID            INTEGER,
    ACC_SN             INTEGER,
    ACC_TYPE           SMALLINT,
    ACC_UNIT           INTEGER,
    COLLECTION_AGENCY  INTEGER,
    TMPSTMP            TIMESTAMP(6),
    PARTICIPANT_TYPE   SMALLINT,
    ACC_CD             SMALLINT,
    BUCKET_ID          SMALLINT,
    UNPAID_INSTALMENT  SMALLINT,
    LEGAL_FORM         INTEGER,
    CUST_FINSORT       INTEGER,
    PROF_ID            INTEGER,
    PRODUCT_ID         INTEGER,
    LOAN_FIN_CODE      INTEGER,
    LAST_PAYMENT_AMOUN DECIMAL(15, 2),
    UNPAID_AMOUNT      DECIMAL(15, 2),
    INSTALMENT_AMOUNT  DECIMAL(15, 2),
    ACCOUNTING_BAL     DECIMAL(15, 2),
    ACTIVE_CAPITAL     DECIMAL(15, 2),
    WITHDRAWAL_CAPITAL DECIMAL(15, 2),
    DATE_SEND          DATE,
    DATE_CREATE        DATE,
    RECORD_TYPE        CHAR(1),
    SEND_FLAG          CHAR(1),
    HOME_ZIP_CODE      CHAR(7),
    BUSINESS_ZIP_CODE  CHAR(7),
    WITHDRAWAL_DATE    CHAR(8),
    LAST_PAYMENT_DT    CHAR(8),
    ACC_NO             CHAR(8),
    ID_NO              CHAR(10),
    AFM_NO             CHAR(10),
    PROF_DESCRIPTION   CHAR(20),
    HOME_PHONE         CHAR(20),
    BUSINESS_PHONE     CHAR(20),
    AGREEMENT_ID       CHAR(20),
    BUSINESS_CITY      CHAR(20),
    HOME_CITY          CHAR(20),
    COMPANY_NAME       CHAR(30),
    BUSINESS_ADDRESS   CHAR(40),
    REPRESANTATIVE     CHAR(40),
    CUSTOMER_NAME      CHAR(40),
    HOME_ADDRESS       CHAR(40),
    PRODUCT_DESCR      CHAR(40)
);

create unique index IXN_REP_001
    on REP_COLLECTION (ACC_NO, DATE_SEND, SEND_FLAG);

create unique index IXN_REP_002
    on REP_COLLECTION (ACC_UNIT, ACC_TYPE, ACC_SN, DATE_CREATE, COLLECTION_AGENCY);

create unique index IXU_REP_004
    on REP_COLLECTION (CUST_ID, ACC_SN, ACC_TYPE, ACC_UNIT, COLLECTION_AGENCY, TMPSTMP);

