create table REP_74551
(
    LOAN_ACC_NUMBER    CHAR(40) not null,
    AGREEMENT_SN       CHAR(40) not null,
    AGREEMENT_CD       SMALLINT,
    LOAN_ACC_CD        SMALLINT,
    PRODUCT_ID         INTEGER,
    SERVICE_CENTR_CODE INTEGER,
    REG_BRANCH_CODE    INTEGER,
    BRANCH_CODE        INTEGER,
    CUST_ID            INTEGER,
    AGREEMENT_LIMIT    DECIMAL(15, 2),
    ACC_LIMIT_AMN      DECIMAL(15, 2),
    ACCOUNT_EXP_DT     DATE,
    ACCOUNT_OPEN_DT    DATE,
    AGREEMENT_CURRENCY CHAR(5),
    ACCOUNT_CURRENCY   CHAR(5),
    OFFICER_ID         CHAR(8),
    CUST_NAME          CHAR(20),
    CUST_PID           CHAR(20),
    CUST_CATEGORY      CHAR(40),
    PROD_DESCRIPTION   CHAR(40),
    CUST_SURNAME       CHAR(70),
    OFFICER_SURNAME    VARCHAR(20),
    OFFICER_NAME       VARCHAR(20),
    MECHANISM          VARCHAR(153),
    constraint IXU_REP_033
        primary key (LOAN_ACC_NUMBER, AGREEMENT_SN)
);

