create table REP_74800
(
    ACCOUNT_LIMIT  CHAR(1),
    LOAN_STATUS    CHAR(1),
    PROD_CATEGORY  INTEGER,
    GL_ACCOUNT     CHAR(21),
    ACC_MOVE_CURR  INTEGER,
    ACC_UNIT       INTEGER,
    NO_OF_ACCOUNTS DECIMAL(15),
    MONTH_CREDIT   DECIMAL(15, 2),
    PREV_BAL       DECIMAL(15, 2),
    NEXT_BALANCE   DECIMAL(15, 2),
    MONTH_DEBIT    DECIMAL(15, 2)
);

create unique index IXU_REP_017
    on REP_74800 (ACCOUNT_LIMIT, LOAN_STATUS, PROD_CATEGORY, GL_ACCOUNT, ACC_MOVE_CURR, ACC_UNIT);

