create table REP_7388C
(
    ID_PRODUCT        INTEGER,
    POS_EURO_BOOK_BAL DECIMAL(15, 2),
    POS_MULT_EUR_BAL  DECIMAL(15, 2),
    NEG_MULT_EUR_BAL  DECIMAL(15, 2),
    NEG_EURO_BOOK_BAL DECIMAL(15, 2),
    CUST_TYPE         CHAR(1),
    CUST_CATEGORY     VARCHAR(15),
    PROD_DESCRIPTION  VARCHAR(40)
);

