create table REP_74210
(
    ACC_UNIT      INTEGER,
    ACC_TYPE      SMALLINT,
    ACCOUNT_ID    INTEGER,
    LOAN_STATUS   CHAR(1),
    ACC_CD        SMALLINT,
    PROD_CATEGORY INTEGER,
    ACC_MOVE_CURR INTEGER,
    PRODUCT       INTEGER,
    CUST_ID       INTEGER,
    NEXT_BALANCE  DECIMAL(15, 2),
    MONTH_CREDIT  DECIMAL(15, 2),
    PREV_BAL      DECIMAL(15, 2),
    MONTH_DEBIT   DECIMAL(15, 2),
    ACC_EXP_DT    DATE,
    FIRST_NAME    CHAR(20),
    GL_ACCOUNT    CHAR(21),
    SURNAME       CHAR(70)
);

create unique index IXU_REP_008
    on REP_74210 (ACC_UNIT, ACC_TYPE, ACCOUNT_ID, LOAN_STATUS);

