create table REPAYMENT_SCHEDULE
(
    COLLECTION_DATE    DATE        not null,
    COLLECTION_AMOUNT  DECIMAL(15, 2),
    REPAYMENT_DATE     DATE,
    PAYMENT_AMOUNT     DECIMAL(15, 2),
    FK_LOAN_ACCOUNTLOA CHAR(1)     not null,
    FK_LOAN_ACCOUNTACC DECIMAL(11) not null,
    constraint PKREPAYMENTSCHED
        primary key (FK_LOAN_ACCOUNTLOA, FK_LOAN_ACCOUNTACC, COLLECTION_DATE)
);

