create table REPORT_HDR
(
    ISGROUPED  SMALLINT,
    STATUSNO   SMALLINT,
    MINACCESS  SMALLINT,
    REPORTCAT  SMALLINT,
    REPORTNO   INTEGER,
    ACTCONTROL CHAR(8),
    HEADER     VARCHAR(50),
    COMMENTS   VARCHAR(250),
    SQLORDERBY VARCHAR(250),
    SQLSELECT  VARCHAR(1000)
);

