create table REPORT_DTL
(
    TOTAL      SMALLINT,
    STATUSNO   SMALLINT,
    QRYVALUE   SMALLINT,
    SORTCOL    SMALLINT,
    ALIGN      SMALLINT,
    DATATYPE   SMALLINT,
    CRITERION  SMALLINT,
    SERIAL     SMALLINT,
    WIDTH      INTEGER,
    REPORTNO   INTEGER,
    QRYCOLNAME VARCHAR(50),
    CALCTXT    VARCHAR(50),
    FLDNAME    VARCHAR(50)
);

