create table REVERSAL_PAYMENT
(
    LNS_ACCOUNT    VARCHAR(40),
    LNS_ACCOUNT_CD VARCHAR(2),
    PRFT_SYSTEM    INTEGER,
    CURRENCY_ID    INTEGER,
    AMOUNT         DECIMAL(15, 2),
    RQ_EXPIRE_DT   DATE,
    COMMENTS       VARCHAR(200),
    PRODUCT_ID     INTEGER,
    DESCRIPTION    VARCHAR(200),
    ACC_STATUS     CHAR(1),
    ACCOUNT_NUMBER VARCHAR(40),
    ROW_STATUS     INTEGER,
    ROW_ERR_DESC   VARCHAR(250),
    TMSTAMP        DATE
);

