create table RISK_FACTORS
(
    MLT_YPER       SMALLINT,
    CUST_DIGIT     SMALLINT,
    MLT_ENHM       SMALLINT,
    ACC_CD         SMALLINT,
    PROD_ID        INTEGER,
    CODE_BASE_RATE INTEGER,
    BANK_CODE      INTEGER,
    CUR            INTEGER,
    CODE_RATE      INTEGER,
    CUST_CODE      INTEGER,
    EFTE           DECIMAL(9, 6),
    PER_RATE       DECIMAL(12, 6),
    LIBOR          DECIMAL(12, 6),
    RATE           DECIMAL(12, 6),
    EURIBOR        DECIMAL(12, 6),
    NO_ACCRUALS    DECIMAL(15, 2),
    MKT            DECIMAL(15, 2),
    ACCRUALS       DECIMAL(15, 2),
    NO_CASH        DECIMAL(15, 2),
    CRED_BAL       DECIMAL(15, 2),
    CUR_ACC_BAL    DECIMAL(15, 2),
    NOEN_BAL       DECIMAL(15, 2),
    ACC_BAL        DECIMAL(15, 2),
    NO_MKT         DECIMAL(15, 2),
    CUR_FINAL_RATE DECIMAL(15, 2),
    FINAL_RATE     DECIMAL(15, 2),
    GROWTH         DECIMAL(15, 2),
    PER_BASE_RATE  DECIMAL(15, 2),
    EN_BAL         DECIMAL(15, 2),
    CUR_DATE       DATE,
    LOAN_STATUS    CHAR(1),
    ACC_STATUS     CHAR(1),
    CUST_NAME      CHAR(20),
    ENHM           CHAR(21),
    ENHM_CRED      CHAR(21),
    INSECURE       CHAR(21),
    FINAL_DELAY    CHAR(21),
    OVERDUE        CHAR(21),
    ACC_NUM        CHAR(40),
    CUST_SUR       CHAR(70),
    CURR_DESC      VARCHAR(3),
    CAT_CAT        VARCHAR(8),
    DESC_BASE_RATE VARCHAR(40),
    PROD_DESC      VARCHAR(40),
    DESC_RATE      VARCHAR(40),
    BANK_DESC      VARCHAR(40)
);

