create table RISK_LISTING
(
    UNIT_CODE                     INTEGER,
    UNIT_NAME                     VARCHAR(40),
    CUSTOMER_NAME                 VARCHAR(91),
    CUSTOMER_CODE                 INTEGER not null
        constraint PK_CUSTCODE
            primary key,
    RISK_CALCULATION_DATE         VARCHAR(100),
    CUSTOMER_PEP_SN               VARCHAR(100),
    CUSTOMER_PEP_DESCRIPTION      VARCHAR(100),
    ACCOUNT_RISK_SN               VARCHAR(100),
    ACCOUNT_RISK_DESCRIPTION      VARCHAR(100),
    BALANCE_LIMIT_OF_INDIVIDUAL   VARCHAR(100),
    BALANCE_LIMIT_OF_CORPORATE    VARCHAR(100),
    TOTAL_OPENING_AMOUNT          VARCHAR(100),
    AVERAGE_BOOK_BALANCE          VARCHAR(100),
    SUSPICIOUS_CUSTOMER_INDICATOR VARCHAR(100),
    ACTIVITY_SECTOR               VARCHAR(100),
    FINAL_RISK_SN                 VARCHAR(100),
    FINAL_RISK_DESCRIPTION        VARCHAR(100)
);

