create table RPT_PORTFOLIO_ANALYSIS
(
    ROW_SN    INTEGER,
    ROW_DESCR CHAR(40),
    EOM_DATE  DATE,
    OUTST_BAL DECIMAL(15, 2),
    GE_PERC   DECIMAL(8, 4),
    CASES     INTEGER,
    NRM_BAL   DECIMAL(15, 2),
    WATCH_BAL DECIMAL(15, 2),
    SUB_BAL   DECIMAL(15, 2),
    DOUBT_BAL DECIMAL(15, 2),
    LOSS_BAL  DECIMAL(15, 2),
    NP_BAL    DECIMAL(15, 2),
    NP_PERC   DECIMAL(8, 4),
    PROV_BAL  DECIMAL(15, 2)
);

