CREATE PROCEDURE RUN_FOREX_AGREEMENT
LANGUAGE SQL
BEGIN
DECLARE LSCHEDULED_DATE DATE;
DECLARE LRECEIVED_AMOUNT DECIMAL(15,2);
DECLARE LPAYED_AMOUNT DECIMAL(15,2);
DECLARE LRECEIVED_CURRENCY INTEGER;
DECLARE LPAYED_CURRENCY INTEGER;
DECLARE LGL_ACCOUNT CHAR(21);
DECLARE LLC_CURRENCY INTEGER;
DECLARE LPRFT_FX_ACCOUNT CHAR(21);
DECLARE LSHORT_DESCR CHAR(5);
DECLARE LLSHORT_DESCR CHAR(5);
DECLARE LLLSHORT_DESCR CHAR(5);

DECLARE C3 CURSOR FOR
SELECT SCHEDULED_DATE
FROM BANK_PARAMETERS;

DECLARE C1 CURSOR FOR
SELECT AMOUNT,LC_AMOUNT,RECEIVED_CURRENCY,PAYED_CURRENCY
FROM GLG_NOTANNOUNCED
WHERE TRN_DATE=LSCHEDULED_DATE;

DECLARE C2 CURSOR FOR
SELECT FK_CURRENCYID_CURR,PRFT_FX_ACCOUNT FROM GLG_ENTEP_CTL;

DECLARE C4 CURSOR FOR
SELECT SHORT_DESCR
FROM CURRENCY
WHERE ID_CURRENCY=LRECEIVED_CURRENCY;

DECLARE C40 CURSOR FOR
SELECT SHORT_DESCR
FROM CURRENCY
WHERE ID_CURRENCY=LLC_CURRENCY;

DECLARE C41 CURSOR FOR
SELECT SHORT_DESCR
FROM CURRENCY
WHERE ID_CURRENCY=LPAYED_CURRENCY;

BEGIN
OPEN C3;  FETCH C3 INTO LSCHEDULED_DATE;               CLOSE C3;
OPEN C2;  FETCH C2 INTO LLC_CURRENCY,LPRFT_FX_ACCOUNT; CLOSE C2;
OPEN C40; FETCH C40 INTO LLSHORT_DESCR;                CLOSE C40;

OPEN C1;
LOOP
FETCH C1 INTO LRECEIVED_AMOUNT,LPAYED_AMOUNT,LRECEIVED_CURRENCY,LPAYED_CURRENCY;
-- ** EXIT WHEN C1%NOTFOUND;
IF LRECEIVED_CURRENCY<>LLC_CURRENCY THEN
OPEN C4;
FETCH C4 INTO LSHORT_DESCR;
CLOSE C4;
SET LGL_ACCOUNT=REPLACE(LPRFT_FX_ACCOUNT,'XX',LPAD(LRECEIVED_CURRENCY,2,'0'));
INSERT INTO REP_74220_FOREX
	(
	PRFT_SYSTEM,
	ACC_UNIT,
	ACC_MOVE_CURR,
	GL_ACCOUNT,
	TP_GL_BALANCE,
	GL_TRN_DATE,
	TIMESTMP,
	CURR_ISO_CODE
	)
VALUES
	(
	'88',
	'107',
	LRECEIVED_CURRENCY,
	LGL_ACCOUNT,
	LRECEIVED_AMOUNT,
	LSCHEDULED_DATE,
	(SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1),
	LSHORT_DESCR
	);

INSERT INTO REP_74220_FOREX
	(
	PRFT_SYSTEM,
	ACC_UNIT,
	ACC_MOVE_CURR,
	GL_ACCOUNT,
	TP_GL_BALANCE,
	GL_TRN_DATE,
	TIMESTMP,
	CURR_ISO_CODE
	)
VALUES
	(
	'88',
	'107',
	LLC_CURRENCY,
	LGL_ACCOUNT,
	(-1)*LPAYED_AMOUNT,
	LSCHEDULED_DATE,
	(SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1),
	LLSHORT_DESCR
	);
ELSE
OPEN C41;
FETCH C41 INTO LLLSHORT_DESCR;
CLOSE C41;
SET LGL_ACCOUNT=REPLACE(LPRFT_FX_ACCOUNT,'XX',LPAD(LPAYED_CURRENCY,2,'0'));
INSERT INTO REP_74220_FOREX
	(
	PRFT_SYSTEM,
	ACC_UNIT,
	ACC_MOVE_CURR,
	GL_ACCOUNT,
	TP_GL_BALANCE,
	GL_TRN_DATE,
	TIMESTMP,
	CURR_ISO_CODE
	)
VALUES
	(
	'88',
	'107',
	LPAYED_CURRENCY,
	LGL_ACCOUNT,
	(-1)*LPAYED_AMOUNT,
	LSCHEDULED_DATE,
	(SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1),
	LLLSHORT_DESCR
	);

INSERT INTO REP_74220_FOREX
	(
	PRFT_SYSTEM,
	ACC_UNIT,
	ACC_MOVE_CURR,
	GL_ACCOUNT,
	TP_GL_BALANCE,
	GL_TRN_DATE,
	TIMESTMP,
	CURR_ISO_CODE
	)
VALUES
	(
	'88',
	'107',
	LLC_CURRENCY,
	LGL_ACCOUNT,
	LRECEIVED_AMOUNT,
	LSCHEDULED_DATE,
	(SELECT CURRENT_TIMESTAMP FROM SYSIBM.SYSDUMMY1),
	LLSHORT_DESCR
	);

END IF;
END LOOP;
CLOSE C1;
COMMIT;
END;
END;

