create table SCH_SCRIPT_RUN_PARAMETERS_BCK
(
    TIMESTAMP_BCK       TIMESTAMP(6)          not null,
    USER_BCK            VARCHAR(20)           not null,
    ID                  VARCHAR(40)           not null,
    LABEL               VARCHAR(100)          not null,
    DB_HOST             VARCHAR(50),
    DB_USER             VARCHAR(50),
    DB_PASSWORD         VARCHAR(100),
    EXE_PATH            VARCHAR(4000)         not null,
    SQL_PATH            VARCHAR(4000),
    CMD_PATH            VARCHAR(4000),
    TIMEOUT             INTEGER  default 3600 not null,
    THREAD_COUNT        SMALLINT default 1    not null,
    HOOK                SMALLINT default 0    not null,
    COMM_TYPE           SMALLINT default 0    not null,
    TELNET_HOST         VARCHAR(50),
    TELNET_USER         VARCHAR(50),
    TELNET_PASSWORD     VARCHAR(100),
    TELNET_LOGIN_SCRIPT VARCHAR(4000),
    WEB_HOST            VARCHAR(4000),
    DELETED             SMALLINT default 0    not null,
    EMAIL               VARCHAR(2000),
    WIN_DOMAIN          VARCHAR(200),
    WIN_USER            VARCHAR(200),
    WIN_PASS            VARCHAR(200),
    DB_TYPE             SMALLINT default 0,
    DB_SERVER           VARCHAR(50),
    WIN_MAP             SMALLINT default 0,
    DB_PARAMS           VARCHAR(200),
    CONNECTION_STRING   VARCHAR(500),
    DATABASE            VARCHAR(100)
);

