create table SDB_TRXJUST
(
    FK_SDB_TYPEFK_PROD INTEGER not null,
    FK_PRFT_TRANSACID  INTEGER not null,
    FK_JUSTIFICID_JUST INTEGER not null,
    FK_ACCOUNTING_RSNU SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_PARAMETRIC_RID  INTEGER,
    FK_ACCOUNTING_RID  INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    MIN_TRN_AMOUNT     DECIMAL(15, 2),
    MAX_TRN_AMOUNT     DECIMAL(15, 2),
    VALIDITY_DATE      DATE,
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    HOME_BRANCH        CHAR(1),
    FK_LNS_COMMISSION  INTEGER default 0,
    FK_LNS_TAX         INTEGER default 0,
    FK_LNS_EXPENSE     INTEGER default 0,
    constraint IXU_SDB_000
        primary key (FK_SDB_TYPEFK_PROD, FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST)
);

