create table SEC_DRILL_DETAIL
(
    MAIN_CODE       CHAR(8) not null,
    SECOND_CODE     CHAR(8) not null,
    MAIN_SYSTEM     SMALLINT,
    SECOND_SYSTEM   SMALLINT,
    USE_ORDER       INTEGER,
    USE_CUSTOMER    CHAR(1),
    USE_ACCOUNT     CHAR(1),
    USE_ACCOUNT_SYS SMALLINT,
    UPDATE_TMSTAMP  TIMESTAMP(6),
    UPDATE_USR      CHAR(8),
    UPDATE_DATE     DATE,
    UPDATE_UNIT     INTEGER,
    CREATE_TMSTAMP  TIMESTAMP(6),
    CREATE_USR      CHAR(8),
    CREATE_DATE     DATE,
    CREATE_UNIT     INTEGER,
    ENTRY_STATUS    CHAR(1),
    constraint PK_DRILLDTL
        primary key (SECOND_CODE, MAIN_CODE)
);

