create table SEC_ROLE_BAK062016
(
    CODE            INTEGER,
    FK_SEC_ROLECODE INTEGER,
    TMSTAMP         TIMESTAMP(6),
    ENTRY_STATUS    CHAR(1),
    PROOF_NEED      CHAR(1),
    DESCRIPTION     VARCHAR(50)
);

