create table SECRET_ACC
(
    ACCOUNT_CD        SMALLINT,
    PRODUCT_ID        INTEGER,
    MONOTORING_UNIT   INTEGER,
    DEP_OPEN_UNIT     INTEGER,
    CUST_ID           INTEGER,
    DEP_ACC_NUMBER    DECIMAL(11),
    FK_BANKEMPLOYEEID CHAR(8),
    FK_BANKEMPLOYEEI1 CHAR(8),
    ACCOUNT_NUMBER    CHAR(40)
);

create unique index SECR_A
    on SECRET_ACC (DEP_ACC_NUMBER, DEP_OPEN_UNIT);

