create table SECURITIES_GL
(
    FK_PRODUCTID_PRODU INTEGER,
    FKGH_GROUP_MEMBER  CHAR(5),
    FKGD_GROUP_MEMBER  INTEGER,
    FKGH_CUST_CATEGORY CHAR(5),
    FKGD_CUST_CATEGORY INTEGER,
    FK_CLEARING_SYSCOD CHAR(10),
    TMSTAMP            DATE,
    CR_CNTR_GL_ACC_LVL CHAR(1),
    DR_CNTR_GL_ACC_LVL CHAR(1),
    ENTRY_STATUS       CHAR(1),
    DR_CNTR_GL_ACC     CHAR(21),
    CR_CNTR_GL_ACC     CHAR(21),
    BANK_SECUR_ACC     CHAR(21)
);

create unique index IXU_SEC_002
    on SECURITIES_GL (FK_PRODUCTID_PRODU, FKGH_GROUP_MEMBER, FKGD_GROUP_MEMBER, FKGH_CUST_CATEGORY, FKGD_CUST_CATEGORY,
                      FK_CLEARING_SYSCOD);

