create table SECURITIES_PARAM
(
    BANK_TR_ACC_TYPE   SMALLINT,
    FORMAT_SYS         SMALLINT,
    PROXY_PLEDG_DAYS   SMALLINT,
    CUSTODY_CODE       SMALLINT,
    BANK_TRAC_UNIT_COD INTEGER,
    AKDD_MATUR_JUSTIF  INTEGER,
    REPO_PLEDG_CATEG   INTEGER,
    PROXY_PLEDG_CATEG  INTEGER,
    AKDD_PLEDG_CATEG   INTEGER,
    BANK_TRACC_ACC_SN  INTEGER,
    REPO_RND_BLCK_AMNT DECIMAL(15, 2),
    FORMAT_SEQ         CHAR(3)
);

create unique index IXP_SEC_000
    on SECURITIES_PARAM (CUSTODY_CODE);

