create table SECUR_TRXJUST
(
    FK_SECUR_PROD_ID    INTEGER,
    FK_PRFT_TRANSACID   INTEGER,
    FK_JUSTIFICID_JUST  INTEGER,
    MIN_VALUE_DAYS      SMALLINT,
    MAX_VALUE_DAYS      SMALLINT,
    FK_PARAMETRIC_RSNU2 SMALLINT,
    FK_PARAMETRIC_RSNU  SMALLINT,
    FK_ACCOUNTING_RSNU  SMALLINT,
    VALUE_DAYS          SMALLINT,
    FK_PARAMETRIC_RID2  INTEGER,
    FK_PARAMETRIC_RID   INTEGER,
    FK_CURRENCYID_CURR  INTEGER,
    FK_ACCOUNTING_RID   INTEGER,
    EXP_UP_LIMIT        DECIMAL(8, 4),
    EXP_LOW_LIMIT       DECIMAL(8, 4),
    COM_LOW_LIMIT       DECIMAL(8, 4),
    COM_UP_LIMIT        DECIMAL(8, 4),
    MIN_TRN_AMOUNT      DECIMAL(15, 2),
    MAX_TRN_AMOUNT      DECIMAL(15, 2),
    VALIDITY_DATE       DATE,
    ENTRY_STATUS        CHAR(1),
    HOME_BRANCH         CHAR(1)
);

create unique index IXU_SEC_004
    on SECUR_TRXJUST (FK_SECUR_PROD_ID, FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST);

