create table SERVICE
(
    FK_PRODUCTID_PRODU INTEGER,
    ID_PRODUCT         INTEGER,
    TMSTAMP            TIMESTAMP(6),
    VALIDITY_DATE      DATE,
    PRODUCT_TYPE       CHAR(1),
    GL_NET_ACC_LEVEL   CHAR(1),
    FOREIGN_CURRENCY   CHAR(1),
    CUSTOMER_TYPE      CHAR(1),
    ENTRY_STATUS       CHAR(1),
    GL_ACCOUNT_LEVEL   CHAR(1),
    GL_ACCOUNT_NUMBER  CHAR(21),
    NETWORK_GL_ACCOUNT CHAR(21),
    SYSTEM_TO_USE      SMALLINT,
    STATUS_1           CHAR(1),
    STATUS_2           CHAR(1),
    STATUS_3           CHAR(1),
    STATUS_4           CHAR(1),
    STATUS_5           CHAR(1),
    STATUS_6           CHAR(1),
    STATUS_7           CHAR(1),
    STATUS_8           CHAR(1),
    STATUS_9           CHAR(1),
    STATUS_10          CHAR(1),
    DESC_STATUS_1      CHAR(20),
    DESC_STATUS_2      CHAR(20),
    DESC_STATUS_3      CHAR(20),
    DESC_STATUS_4      CHAR(20),
    DESC_STATUS_5      CHAR(20),
    DESC_STATUS_6      CHAR(20),
    DESC_STATUS_7      CHAR(20),
    DESC_STATUS_8      CHAR(20),
    DESC_STATUS_9      CHAR(20),
    DESC_STATUS_10     CHAR(20),
    DESC_AMOUNT_1      CHAR(30),
    DESC_AMOUNT_2      CHAR(30),
    DESC_AMOUNT_3      CHAR(30),
    DESC_AMOUNT_4      CHAR(30),
    DESC_AMOUNT_5      CHAR(30),
    DESC_AMOUNT_6      CHAR(30),
    DESC_AMOUNT_7      CHAR(30),
    DESC_AMOUNT_8      CHAR(30),
    DESC_AMOUNT_9      CHAR(30),
    DESC_AMOUNT_10     CHAR(30)
);

create unique index IXU_SER_001
    on SERVICE (FK_PRODUCTID_PRODU);

