create table SERVICE_PRICING
(
    FK0SERVICE_TRXJFK  INTEGER,
    FK1SERVICE_TRXJFK  INTEGER,
    FK_SERVICE_TRXJFK  INTEGER,
    SNUM               SMALLINT,
    FK_PARAMETRIC_RSNU SMALLINT,
    FK_PARAMETRIC_RID  INTEGER,
    FK_CHEQ_ITEM_CHID  INTEGER,
    FK_TAXID_TAX       INTEGER,
    FK0TAXID_TAX       INTEGER,
    FK1TAXID_TAX       INTEGER,
    FK_EXPENSEID_EXPEN INTEGER,
    FK_COMMISSIONID_CO INTEGER,
    ID_PRODUCT         INTEGER,
    COM_UP_LIMIT       DECIMAL(8, 4),
    COM_LOW_LIMIT      DECIMAL(8, 4),
    CPI_LOW_LIMIT      DECIMAL(8, 4),
    EXP_UP_LIMIT       DECIMAL(8, 4),
    CPI_UP_LIMIT       DECIMAL(8, 4),
    EXP_LOW_LIMIT      DECIMAL(8, 4),
    TMSTAMP            DATE,
    TRXJUST_VALID_DATE DATE,
    VALIDITY_DATE      DATE,
    ENTRY_STATUS       CHAR(1)
);

create unique index IXU_SER_002
    on SERVICE_PRICING (FK0SERVICE_TRXJFK, FK1SERVICE_TRXJFK, FK_SERVICE_TRXJFK, SNUM);

