create table SHIP
(
    ID                 DECIMAL(10) not null
        constraint PK_SHIP
            primary key,
    SHIP_DESCRIPTION   CHAR(40),
    SHIP_NAME          CHAR(30),
    SHIP_REG_CLASS     CHAR(30),
    SHIP_REG_PORT      CHAR(30),
    SHIP_REGISTRY_NO   CHAR(20),
    SHIPPING_YEAR      SMALLINT,
    SHIPPING_PLACE     CHAR(30),
    SHIP_USAGE         CHAR(30),
    ENTRY_STATUS       CHAR(1),
    SEC_CERTIF_FLG     CHAR(1),
    LOAD_LINE_CERT_FLG CHAR(1),
    GROSS_REG_TONNAGE  DECIMAL(10, 2),
    NET_REG_TONNAGE    DECIMAL(10, 2),
    LENGTH_OVERALL     DECIMAL(6, 2),
    REG_LENGTH         DECIMAL(6, 2),
    REG_WIDTH          DECIMAL(6, 2),
    REG_DEPTH          DECIMAL(5, 2),
    ENGINE_DETAILS     CHAR(40),
    SHIP_VELOCITY      DECIMAL(5, 2),
    PASNGR_CAP_SUMMER  INTEGER,
    PASNGR_CAP_WINTER  INTEGER,
    CAR_CAPACITY       INTEGER,
    TRUCK_CAPACITY     SMALLINT,
    DISTINCT_NAME      CHAR(30),
    FLAG_REGISTRY      CHAR(20),
    INSURANCE_RISKS    CHAR(254),
    SPECIFIC_CLAUSES   CHAR(254),
    INSURANCE_AMNT     DECIMAL(15, 2),
    INSUR_START_DT     DATE,
    INSUR_END_DT       DATE,
    INS_CONTRACT_ID    CHAR(20),
    INSUR_CONTRACT_DT  DATE,
    INS_RISK_COVER_PRC DECIMAL(5, 2),
    INS_CONCESS_DTLS   CHAR(100),
    INS_COMMENTS       CHAR(254),
    LESSEE             CHAR(40),
    LEASE_START_DT     DATE,
    LEASE_END_DT       DATE,
    LEASE_ANNUAL_AMN   DECIMAL(15, 2),
    LEASE_COMMENTS     CHAR(254),
    LEGAL_PROBLEMS     CHAR(254),
    TECHNICAL_PROBLEMS CHAR(254),
    OTHER_PROBLEMS     CHAR(254),
    INSERTION_USR      CHAR(8),
    INSERTION_UNIT     INTEGER,
    INSERTION_DT       DATE,
    MODIFICATION_USR   CHAR(8),
    MODIFICATION_DT    DATE,
    FK_GH_LEASE_DESC   CHAR(5),
    FK_GD_LEASE_DESC   INTEGER,
    FK_GH_INSCO_DESC   CHAR(5),
    FK_GD_INSCO_DESC   INTEGER,
    FK_GH_SHTYPE       CHAR(5),
    FK_GD_SHTYPE       INTEGER
);

create unique index I0000893
    on SHIP (FK_GH_SHTYPE, FK_GD_SHTYPE);

create unique index I0000910
    on SHIP (FK_GH_LEASE_DESC, FK_GD_LEASE_DESC);

create unique index I0010890
    on SHIP (FK_GH_INSCO_DESC, FK_GD_INSCO_DESC);

