create table SO_SPEC_AGR_CATEG
(
    PRODUCT_ID     INTEGER,
    CUST_CATEG_SN  INTEGER,
    EFFECTIVE_DATE DATE,
    DISCOUNT_PERC  DECIMAL(8, 4),
    USR_COMM_PERC  DECIMAL(8, 4),
    USR_COMM_AMNT  DECIMAL(15, 2),
    DISCOUNT_AMNT  DECIMAL(15, 2),
    TMSTAMP        DATE
);

create unique index IXU_SO__006
    on SO_SPEC_AGR_CATEG (PRODUCT_ID, CUST_CATEG_SN, EFFECTIVE_DATE);

