create table SPECIAL_AGREEMENT
(
    COM_CHARGE_FRQ       SMALLINT,
    FK_JUSTIFICID_JUST   INTEGER,
    FK_PRFT_TRANSACID    INTEGER,
    FK_GENERIC_DETASER   INTEGER,
    FK_PRODUCTID_PRODU   INTEGER,
    FK_CUSTOMERCUST_ID   INTEGER,
    CHARGES_DISCOUNT     DECIMAL(8, 4),
    COMM_DISCOUNT        DECIMAL(8, 4),
    MIN_AMOUNT           DECIMAL(15, 2),
    TMSTAMP              TIMESTAMP(6),
    ENTRY_STATUS         CHAR(1),
    COM_CHARGE_FRQ_TYP   CHAR(1),
    FK_GENERIC_DETAFKH   CHAR(5),
    EXPIRY_DATE          DATE,
    FK_TAX_FIRST         INTEGER,
    FK_TAX_SECOND        INTEGER,
    FK_TAX_THIRD         INTEGER,
    FK_EXPENSE_FIRST     INTEGER,
    FK_EXPENSE_SECOND    INTEGER,
    FK_EXPENSE_THIRD     INTEGER,
    FK_COMMISSION_FIRST  INTEGER,
    FK_COMMISSION_SECOND INTEGER,
    FK_COMMISSION_THIRD  INTEGER
);

create unique index PKX_SPECIAL_AGREEMENT
    on SPECIAL_AGREEMENT (FK_CUSTOMERCUST_ID, FK_PRFT_TRANSACID, FK_JUSTIFICID_JUST, FK_PRODUCTID_PRODU);

