create table SPECIAL_AGREEMEN_U
(
    FK_CUSTOMERCUST_ID INTEGER      not null,
    FK_PRODUCTID_PRODU INTEGER      not null,
    FK_PRFT_TRANSACID  INTEGER      not null,
    FK_JUSTIFICID_JUST INTEGER      not null,
    FK_GENERIC_DETAFKH CHAR(5),
    FK_GENERIC_DETASER INTEGER,
    COM_CHARGE_FRQ_TYP CHAR(1),
    MIN_AMOUNT         DECIMAL(15, 2),
    COM_CHARGE_FRQ     SMALLINT,
    TMSTAMP            TIMESTAMP(6) not null,
    CHARGES_DISCOUNT   DECIMAL(8, 4),
    COMM_DISCOUNT      DECIMAL(8, 4),
    ENTRY_STATUS       CHAR(1)      not null,
    constraint IXU_CIU_055
        primary key (FK_JUSTIFICID_JUST, FK_PRFT_TRANSACID, FK_PRODUCTID_PRODU, FK_CUSTOMERCUST_ID)
);

