create table SPLIT_UP_BANKING_I
(
    FK_CUSTOMERCUST_ID INTEGER,
    FK_OTHER_BANKDISCR CHAR(15),
    FK_OTHER_BANKFK_G1 INTEGER,
    FK_OTHER_BANKFK_GE CHAR(5),
    SERIAL_NUM         SMALLINT,
    CREDIT_LIMIT       DECIMAL(15, 2),
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    BRANCH             VARCHAR(30),
    ENTRY_COMMENTS     VARCHAR(30)
);

create unique index IXU_SPL_000
    on SPLIT_UP_BANKING_I (FK_CUSTOMERCUST_ID, FK_OTHER_BANKDISCR, FK_OTHER_BANKFK_G1, FK_OTHER_BANKFK_GE, SERIAL_NUM);

