create table SQL_STAGE01
(
    VERSION             DECIMAL(15, 2),
    SIGNATURE           DECIMAL(15, 2),
    SQL_HANDLE          VARCHAR(30),
    OBJ_NAME            VARCHAR(30),
    OBJ_TYPE            VARCHAR(30),
    PLAN_ID             DECIMAL(15, 2),
    SQL_TEXT            CLOB(1048576),
    CREATOR             VARCHAR(30),
    ORIGIN              VARCHAR(30),
    DESCRIPTION         VARCHAR(500),
    DB_VERSION          VARCHAR(64),
    CREATED             TIMESTAMP(6),
    LAST_MODIFIED       TIMESTAMP(6),
    LAST_EXECUTED       TIMESTAMP(6),
    LAST_VERIFIED       TIMESTAMP(6),
    STATUS              DECIMAL(15, 2),
    OPTIMIZER_COST      DECIMAL(15, 2),
    MODULE              VARCHAR(48),
    ACTION              VARCHAR(32),
    EXECUTIONS          DECIMAL(15, 2),
    ELAPSED_TIME        DECIMAL(15, 2),
    CPU_TIME            DECIMAL(15, 2),
    BUFFER_GETS         DECIMAL(15, 2),
    DISK_READS          DECIMAL(15, 2),
    DIRECT_WRITES       DECIMAL(15, 2),
    ROWS_PROCESSED      DECIMAL(15, 2),
    FETCHES             DECIMAL(15, 2),
    END_OF_FETCH_COUNT  DECIMAL(15, 2),
    CATEGORY            VARCHAR(30),
    SQLFLAGS            DECIMAL(15, 2),
    TASK_ID             DECIMAL(15, 2),
    TASK_EXEC_NAME      VARCHAR(30),
    TASK_OBJ_ID         DECIMAL(15, 2),
    TASK_FND_ID         DECIMAL(15, 2),
    TASK_REC_ID         DECIMAL(15, 2),
    INUSE_FEATURES      DECIMAL(15, 2),
    PARSE_CPU_TIME      DECIMAL(15, 2),
    PRIORITY            DECIMAL(15, 2),
    OPTIMIZER_ENV       VARCHAR(2000),
    BIND_DATA           VARCHAR(2000),
    PARSING_SCHEMA_NAME VARCHAR(30),
    COMP_DATA           CLOB(1048576)
);

