create table SQL_BATCH_EXECUTE
(
    BATCH_ID    CHAR(5),
    TIMESTMP    TIMESTAMP(6),
    INTERNAL_SN DECIMAL(15),
    DATA_SQL    VARCHAR(4000),
    RESULT0     VARCHAR(50)
);

create unique index IXP_SQL_000
    on SQL_BATCH_EXECUTE (TIMESTMP, INTERNAL_SN, BATCH_ID);

