create table STAGE_W_FACT_CUSTOMER_CARD
(
    CARD_NO                  VARCHAR(16) not null,
    ENTRY_STATUS_IND         VARCHAR(1)  not null,
    ACCOUNT_NO               VARCHAR(20) not null,
    PRF_AC_PRFT_SYSTEM       SMALLINT    not null,
    PROFITS_ACCOUNT_NUM      VARCHAR(40) not null,
    ROW_EFFECTIVE_DATE       DATE        not null,
    ROW_EXPIRATION_DATE      DATE,
    ROW_CURRENT_FLAG         DECIMAL(15),
    ENTRY_STATUS_IND_NAME    VARCHAR(8),
    PROFITS_ACCOUNT_CD       SMALLINT,
    CARD_CUSTOMER_ID         INTEGER,
    CARD_CUSTOMER_NAME       VARCHAR(107),
    CARD_START_DATE          DATE,
    CARD_END_DATE            DATE,
    ACCT_KEY                 DECIMAL(11),
    CARD_CUSTOMER_CD         SMALLINT,
    ACCT_PRODUCT_DESCRIPTION VARCHAR(40),
    ACCT_PRODUCT_ID          INTEGER,
    MONITORING_UNIT          INTEGER,
    constraint STAGE_PK_W_FACT_CUSTOMER_CARD
        primary key (CARD_NO, ENTRY_STATUS_IND, ACCOUNT_NO, PRF_AC_PRFT_SYSTEM, PROFITS_ACCOUNT_NUM, ROW_EFFECTIVE_DATE)
);

