create table STAGE_EOM_BENEFICIARY
(
    EOM_DATE           DATE,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    BENEFICIARY_SN     SMALLINT,
    ACCT_KEY           DECIMAL(11)
);

