create table STAGE_FST_DEMAND_EXTRAIT_TMP
(
    DEP_ACC_NUMBER            DECIMAL(11) not null,
    FIRST_INSTALLMENT_DATE    DATE,
    PREVIOUS_INSTALLMENT_DATE DATE,
    INSTALLMENT_AMOUNT        DECIMAL(15)
);

