create table STAGE_W_CUSTOMER_APPLICATION
(
    UNIT_CODE         DECIMAL(5) not null,
    APPLICATION_ID    CHAR(15)   not null,
    CUST_ID           DECIMAL(7) not null,
    ACCOUNT_CD        DECIMAL(2),
    APPLICATION_TYPE  DECIMAL(5),
    INTERNAL_SN       DECIMAL(11),
    DRAWDOWN_AMN      DECIMAL(15, 2),
    REQUEST_AMN       DECIMAL(15, 2),
    REQUEST_DT        DATE,
    DRAWDOWN_DT       DATE,
    CONFIRM_DT        DATE,
    TMSTAMP           TIMESTAMP(6),
    APPLICATION_STS   CHAR(2),
    CONFIRM_USR       CHAR(8),
    INSERT_USR        CHAR(8),
    ACCOUNT_NUMERIC   CHAR(40),
    REQUEST_FORECAST  VARCHAR(200),
    CONFIRM_CMNTS     VARCHAR(250),
    INSERT_CMNTS      VARCHAR(250),
    CHANNEL_ID        DECIMAL(5),
    REFERENCE_NUMERIC CHAR(40)
);

