create table STAGE_W_EOM_LOAN_ACCOUNT
(
    EOM_DATE                      DATE                      not null,
    ACCOUNT_NUMBER                CHAR(40)                  not null,
    C_DIGIT                       SMALLINT,
    NRM_RL_URL_FLG                SMALLINT,
    OV_RL_URL_FLG                 SMALLINT,
    ACCOUNT_CD                    SMALLINT,
    PRFT_SYSTEM                   SMALLINT,
    AGREEMENT_CD                  SMALLINT,
    AGREEMENT_SYSTEM              SMALLINT,
    ACC_TYPE                      SMALLINT,
    INSTALL_FREQ                  SMALLINT,
    INSTALL_COUNT                 SMALLINT,
    LAST_NRM_TRX_CNT              SMALLINT,
    FK_BASE_RATEFK_GD             INTEGER,
    FK_UNITCODE                   INTEGER,
    LNS_OPEN_UNIT                 INTEGER,
    ID_PRODUCT                    INTEGER,
    FKCUR_IS_CHARGED              INTEGER,
    FKCUR_IS_MOVED_IN             INTEGER,
    FKCUR_USES_AS_LIM             INTEGER,
    FKGD_HAS_AS_CLASS             INTEGER,
    FKGD_HAS_AS_FINANC            INTEGER,
    FKGD_HAS_AS_LOAN_P            INTEGER,
    FKGD_CATEGORY                 INTEGER,
    FK_INTERESTID_INTE            INTEGER,
    ACC_SN                        INTEGER,
    CUST_ID                       INTEGER,
    REMAINING_DAYS                DECIMAL(10),
    REMAINING_MONTHS              DECIMAL(10),
    TOTAL_DAYS                    DECIMAL(10),
    TOTAL_MONTHS                  DECIMAL(10),
    OVERDUE_DAYS                  DECIMAL(10),
    OVERDUE_MONTHS                DECIMAL(10),
    NRM_CAP_BAL                   DECIMAL(15, 2),
    NRM_RL_INT_BAL                DECIMAL(15, 2),
    NRM_URL_INT_BAL               DECIMAL(15, 2),
    NRM_EXP_BAL                   DECIMAL(15, 2),
    NRM_COM_BAL                   DECIMAL(15, 2),
    NRM_ACR_INT_BAL               DECIMAL(15, 2),
    NRM_SUBSIDY_BAL               DECIMAL(15, 2),
    OV_CAP_BAL                    DECIMAL(15, 2),
    OV_RL_NRM_INT_BAL             DECIMAL(15, 2),
    OV_RL_PNL_INT_BAL             DECIMAL(15, 2),
    OV_URL_NRM_INT_BAL            DECIMAL(15, 2),
    OV_URL_PNL_INT_BAL            DECIMAL(15, 2),
    OV_EXP_BAL                    DECIMAL(15, 2),
    OV_COM_BAL                    DECIMAL(15, 2),
    OV_ACR_NRM_INT_BAL            DECIMAL(15, 2),
    OV_ACR_PNL_INT_BAL            DECIMAL(15, 2),
    OV_SUBSIDY_BAL                DECIMAL(15, 2),
    ACC_LIMIT_AMN                 DECIMAL(15, 2),
    POSITIVE_AMN                  DECIMAL(15, 2),
    UNCLEAR_AMN                   DECIMAL(15, 2),
    BLOCKED_AMN                   DECIMAL(15, 2),
    DORMANT_AMN                   DECIMAL(15, 2),
    INSTALL_FIXED_AMN             DECIMAL(15, 2),
    NRM_ACCRUAL_AMN               DECIMAL(15, 2),
    OV_ACCRUAL_AMN                DECIMAL(15, 2),
    LNS_UNREALIZED                DECIMAL(15, 2),
    PRFT_ACC_LMT_AMN              DECIMAL(15, 2),
    BOOK_BALANCE                  DECIMAL(15, 2),
    NRM_BALANCE                   DECIMAL(15, 2),
    OV_BALANCE                    DECIMAL(15, 2),
    OV_MKT                        DECIMAL(15, 2),
    SELECTED_BANK_RATE            DECIMAL(8, 4),
    SELECTED_NORMAL_RA            DECIMAL(8, 4),
    FINAL_INTEREST                DECIMAL(8, 4),
    BASE_SPREAD                   DECIMAL(8, 4),
    SPREAD                        DECIMAL(8, 4),
    N128                          DECIMAL(9, 6),
    BANK_SPREAD                   DECIMAL(12, 6),
    INSTALL_FIRST_DT              DATE,
    INSTALL_NEXT_DT               DATE,
    INSTALL_PREV_DT               DATE,
    ACC_EXP_DT                    DATE,
    ACC_OPEN_DT                   DATE,
    OV_EXP_DT                     DATE,
    LOAN_STATUS                   CHAR(1),
    ACC_STATUS                    CHAR(1),
    ACC_MECHANISM                 CHAR(1),
    FIRST_NAME                    CHAR(20),
    NRM_DR_CNTR_GL_ACC            CHAR(21),
    NRM_CR_CNTR_GL_ACC            CHAR(21),
    OV_DR_CNTR_GL_ACC             CHAR(21),
    DEFINATE_DELAY                CHAR(21),
    WRITE_OFF                     CHAR(21),
    AGREEMENT_NUMBER              CHAR(40),
    SURNAME                       CHAR(70),
    PAN_DUE_CAT                   VARCHAR(8),
    LNS_INTEREST_DESC             VARCHAR(40),
    DESCRIPTION                   VARCHAR(40),
    PRODUCT_DESC                  VARCHAR(40),
    UNIT_NAME                     VARCHAR(40),
    DRAWDOWN_FST_AMN              DECIMAL(15, 2),
    DRAWDOWN_FST_DT               DATE,
    INSTA_PAID                    INTEGER,
    PROVISION_AMN                 DECIMAL(15, 2),
    PROVISION_CURR_PERC           INTEGER,
    TOT_CAP_AMN                   DECIMAL(15, 2),
    TOT_COMMISSION_AMN            DECIMAL(15, 2),
    TOT_DRAWDOWN_AMN              DECIMAL(15, 2),
    TOT_EXPENSE_AMN               DECIMAL(15, 2),
    TOT_NRM_INT_AMN               DECIMAL(15, 2),
    TOT_PNL_INT_AMN               DECIMAL(15, 2),
    FKGH_CBPURP                   CHAR(5),
    FKGD_CBPURP                   INTEGER,
    FKINT_CURRENT_FIX             INTEGER,
    FKINT_AS_FLOATING             INTEGER,
    FKINT_PREV_FIXED              INTEGER,
    DEL_FKINT_HAS_OVERDUE         INTEGER,
    PENALTY_INTE_RATE             DECIMAL(8, 4),
    CUST_TYPE                     SMALLINT,
    OV_GL_ACCRUAL_ACC             CHAR(21),
    DEF_GL_ACCRUAL_ACC            CHAR(21),
    DEL_CUR_FX_INT_EXP_DT         DATE,
    DEL_CUR_FX_INT_ST_DT          DATE,
    LOAN_TYPE                     CHAR(2),
    PREV_SUB_CLASS                CHAR(1),
    CURR_SUB_CLASS                CHAR(1),
    DEL_AFM_NO                    CHAR(20),
    DEL_ID_NO                     VARCHAR(20),
    DEL_DESCRIPTION_ID            VARCHAR(40),
    PROVISION_AMOUNT              DECIMAL(15, 2),
    FKGH_HAS_AS_CLASS             CHAR(5),
    EURO_BOOK_BAL                 DECIMAL(15, 2),
    FIXING_RATE                   DECIMAL(12, 6),
    TRX_AMN_WO_WD                 DECIMAL(15, 2),
    TRX_AMN_CAP_INT               DECIMAL(15, 2),
    DISCOUNTED_VALUE              DECIMAL(15, 2),
    WRITE_OFF_PAY_AMT             DECIMAL(15, 2),
    FKGH_HAS_AS_FINANC            CHAR(5),
    FKGH_AS_CRED_LINE             CHAR(5),
    FKGD_AS_CRED_LINE             INTEGER,
    DEL_JUSTIFICATION_CODE        INTEGER,
    DEL_TRANSACTION_CODE          INTEGER,
    TRX_AMN                       DECIMAL(15, 2),
    DEL_REVERSED_FLG              CHAR(1),
    REQUEST_TYPE                  CHAR(1),
    DRAWDOWN_EXP_DT               DATE,
    DEL_HOLDR_FK_GENERIC_DETASER  INTEGER,
    HOLDR_DESCRIPTION             CHAR(20),
    FKGH_CATEGORY                 CHAR(5),
    FK_GENERIC_DETASER            INTEGER,
    FK_CATEGORYCATEGOR            CHAR(5),
    LAST_TRANSACTION_DATE         DATE,
    DEL_EMP_FIRST_NAME            VARCHAR(40),
    DEL_EMP_LAST_NAME             VARCHAR(70),
    DEL_NRM_CHRG_CNT              SMALLINT,
    DEL_NRM_INST_CNT              SMALLINT,
    DEL_NRM_INT_CNT               SMALLINT,
    DEL_NRM_LOAN_CNT              SMALLINT,
    OV_INST_CNT                   SMALLINT,
    DEL_OV_INT_CNT                SMALLINT,
    DEL_OV_LOAN_CNT               SMALLINT,
    DEL_OV_CHRG_CNT               SMALLINT,
    DEL_TRX_DATE                  DATE,
    RECYCLING_LMT_FLG             CHAR(1),
    LUMP_DRAWDOWN_FLG             CHAR(1),
    MONOTORING_UNIT               INTEGER,
    LOAN_CLASS                    CHAR(1),
    AGR_LIMIT                     DECIMAL(15, 2),
    GROSS_TOTAL                   DECIMAL(15, 2),
    LC_GROSS_TOTAL                DECIMAL(15, 2) default 0,
    INTEREST_IN_SUSPENSE          DECIMAL(15, 2) default 0,
    DEL_FINAL_CLASS               CHAR(1),
    ADJUSTED_SUB_CLASS            CHAR(1),
    ACTUAL_SUB_CLASS              CHAR(1),
    ADJUSTED_CLASS                CHAR(1),
    COLLATERAL_OM_VALUE           DECIMAL(15, 2),
    FINAL_SUB_CLASS               CHAR(1),
    ACC_DRAWDOWN_STS              CHAR(1),
    ACCT_KEY                      DECIMAL(11),
    FKGH_HAS_ADJUST               CHAR(5),
    FKGD_HAS_ADJUST               INTEGER,
    CURRENCY                      CHAR(5),
    ISS_REMAINING_AMNT            DECIMAL(15, 2),
    SERVICE_DEP_ACCT_KEY          DECIMAL(11),
    AGREEM_ACCT_KEY               DECIMAL(11),
    CLOSED_FLAG                   CHAR(3)        default 'No',
    TOT_INT_SPRD_AMN              DECIMAL(15, 2),
    TOT_SUBS_INT_AMN              DECIMAL(15, 2),
    CUSTOMER_NAME                 VARCHAR(300),
    LOAN_TYPE_NAME                VARCHAR(38),
    LAST_MONTH_INTEREST_DEBIT_AMT DECIMAL(15, 2),
    FINAL_CLASS_NAME              VARCHAR(14),
    DATE_CLASS_CHANGED            DATE,
    ACCOUNT_NO                    VARCHAR(50),
    CRM_ARREARS_DATE              DATE,
    CRM_LAND_REGISTRY_NUMBER      VARCHAR(40),
    CRM_NOTICE_ISSUE_DATE_90      DATE,
    CRM_NOTICE_MATURITY_DATE_90   DATE,
    CRM_NOTICE_ISSUE_DATE_40      DATE,
    CRM_NOTICE_MATURITY_DATE_40   DATE,
    CRM_AUCTION_DATE              DATE,
    CRM_COMMENTS                  VARCHAR(500),
    RECOVERIES_DATE               DATE,
    MONTHLY_PREMIUM               DECIMAL(15, 2) default 0,
    LEDGER_FEES                   DECIMAL(15, 2) default 0,
    DELAY_OFFICER_ID              VARCHAR(8),
    DELAY_OFFICER_NAME            VARCHAR(41),
    LOAN_STATUS_IND_NAME          VARCHAR(15),
    CLOAN_CATEGORY_DESCRIPTION    VARCHAR(40),
    AGREEMENT_NUMERIC             CHAR(40),
    CRM_LAND_REGISTRY_NUMERIC     VARCHAR(40),
    LOAN_OFFICER_ID               VARCHAR(8),
    LOAN_OFFICER_NAME             VARCHAR(41),
    INSTALLMENT_AMOUNT            DECIMAL(15, 2),
    REMAINING_CAPITAL_AMT         DECIMAL(15, 2),
    TRANSFER_WRITEOFF_DATE        DATE,
    CRM_AMOUNT_PAID               DECIMAL(15, 2),
    CRM_SALE_PRICE                DECIMAL(15, 2),
    CRM_SALE_DATE                 DATE,
    CRM_COMPLETION_DATE           DATE,
    CRM_AUCTIONEER                VARCHAR(60),
    TOTAL_CAPITAL_DEBITED         DECIMAL(15, 2),
    TOTAL_INTEREST_CREDITED       DECIMAL(15, 2),
    SO_FIRST_PRIORITY_ACCOUNT_NO  VARCHAR(50),
    SO_SECOND_PRIORITY_ACCOUNT_NO VARCHAR(50),
    FINANCIAL_SECTOR              VARCHAR(40),
    SALESPERSON                   VARCHAR(40),
    OVERDRAFT_TYPE_FLAG           VARCHAR(13),
    INSURANCES_AMOUNT             DECIMAL(15, 2),
    DAILY_DEBIT                   DECIMAL(15, 2),
    DAILY_CREDIT                  DECIMAL(15, 2),
    MONITORING_UNIT_NAME          VARCHAR(40),
    MEDIATOR_CODE                 VARCHAR(25)    default '' not null,
    MEDIATOR_DESCRIPTION          VARCHAR(25),
    DEF_DELAY_DATE                DATE,
    DEF_DELAY_AMN                 DECIMAL(15, 2),
    WRITE_OFF_DATE                DATE,
    WRITE_OFF_AMN                 DECIMAL(15, 2),
    LAST_PAYMENT_DATE             DATE,
    LAST_PAYMENT_AMN              DECIMAL(15, 2),
    ACCOUNTING_AMN                DECIMAL(15, 2),
    ADJUSTMENT_DT                 DATE,
    AGREEMENT_SIGNING_DT          DATE,
    PURCHACE_DT                   DATE,
    PURCHACE_AMN                  DECIMAL(15, 2),
    WRITE_OFF_RECOVERY_AMN        DECIMAL(15, 2),
    PRODUCT_CATEGORY              CHAR(50),
    WRITE_OFF_REASON              CHAR(50),
    DEF_DELAY_BUCKET              CHAR(50),
    DEF_DELAY_OV_DAYS             DECIMAL(10),
    constraint IXU_EOM_007
        primary key (EOM_DATE, ACCOUNT_NUMBER)
);

