create table STAGE_EOM_DEPOSITS
(
    EOM_DATE                      DATE                     not null,
    ACCOUNT_NUMBER                CHAR(40)                 not null,
    ACCOUNT_CD                    SMALLINT,
    RANKING                       DECIMAL(15, 2),
    DEP_OPEN_UNIT                 INTEGER,
    CUST_ID                       INTEGER,
    C_DIGIT                       SMALLINT,
    PRFT_SYSTEM                   SMALLINT,
    AGREEMENT_CD                  SMALLINT,
    AGREEMENT_SYSTEM              SMALLINT,
    ID_PRODUCT                    INTEGER,
    ID_CURRENCY                   INTEGER,
    DAYS_DURATION                 SMALLINT,
    REMAINING_DAYS                DECIMAL(15, 2),
    SERIAL_NUM_F                  INTEGER,
    SERIAL_NUM_P                  INTEGER,
    SERIAL_NUM_L                  INTEGER,
    RATE                          DECIMAL(8, 4),
    RENEWAL_SER_NUM               INTEGER,
    FIXING_RATE                   DECIMAL(12, 6),
    FKGD_CATEGORY                 INTEGER,
    FK2GENERIC_DETASER            INTEGER,
    FK_GENERIC_DETASER            INTEGER,
    FK_COLLABORATIOBAN            INTEGER,
    NOTIFICATION_DAYS             SMALLINT,
    LNS_UNITCODE                  INTEGER,
    LNS_ACC_TYPE                  SMALLINT,
    LNS_ACC_SN                    INTEGER,
    NORMAL_BAL                    DECIMAL(15, 2),
    OVERDUE_BAL                   DECIMAL(15, 2),
    INTEREST                      DECIMAL(15, 2),
    EURO_INTEREST                 DECIMAL(15, 2),
    AVER_INT_BAL                  DECIMAL(15, 2),
    EURO_AVER_INT_BAL             DECIMAL(15, 2),
    BOOK_BALANCE                  DECIMAL(15, 2),
    ACCOUNT_LIMIT                 DECIMAL(15, 2),
    EURO_BOOK_BAL                 DECIMAL(15, 2),
    START_DATE                    DATE,
    EXPIRY_DATE                   DATE,
    CUST_TYPE                     CHAR(1),
    NON_RESIDENT                  CHAR(1),
    EUR_IN_COUNTRY                CHAR(1),
    ENTRY_STATUS                  CHAR(1),
    ONE_ACCOUNT_FLG               CHAR(1),
    DEPOSIT_TYPE                  CHAR(1),
    FKGH_CATEGORY                 CHAR(5),
    FK2GENERIC_DETAFK             CHAR(5),
    FK_GENERIC_DETAFK             CHAR(5),
    PARAMETER_TYPE_L              CHAR(5),
    PARAMETER_TYPE_P              CHAR(5),
    PARAMETER_TYPE_F              CHAR(5),
    CR_CNTR_GL_ACC                CHAR(21),
    CR_INT_ACCR_GL_ACC            CHAR(21),
    CR_INT_GL_ACC                 CHAR(21),
    DR_CNTR_GL_ACC                CHAR(21),
    DR_INT_ACCR_GL_ACC            CHAR(21),
    DR_INT_GL_ACC                 CHAR(21),
    TD_CR_INT_ACCR_GL_ACC         CHAR(21),
    TD_CR_INT_GL_ACC              CHAR(21),
    TD_CR_INT_NOTAX_GL_AC         CHAR(21),
    TD_GL_ACCOUNT                 CHAR(21),
    TD_GL_ACCRUAL_ACC             CHAR(21),
    NRM_DR_CNTR_GL_ACC            CHAR(21),
    OV_DR_CNTR_GL_ACC             CHAR(21),
    FIRST_NAME                    CHAR(20),
    AGREEMENT_NUMBER              CHAR(40),
    SURNAME                       CHAR(70),
    UNIT_NAME                     VARCHAR(40),
    PRODUCT_DESC                  VARCHAR(40),
    FK0UNITCODE                   INTEGER,
    FK1GENERIC_DETAFK             CHAR(5),
    FK1GENERIC_DETASER            INTEGER,
    DEP_ACC_NUMBER                DECIMAL(11),
    CHECKING_ACC_TYPE             SMALLINT,
    ACCR_CR_INTEREST              DECIMAL(15, 2),
    ACCR_DB_INTEREST              DECIMAL(15, 2),
    FK1INTERESTID_INTE            INTEGER,
    FK0INTERESTID_INTE            INTEGER,
    FK_INTERESTID_INTE            INTEGER,
    UNCLEAR_BALANCE               DECIMAL(15, 2),
    IBAN                          VARCHAR(40),
    LAST_TRX_DATE                 DATE,
    OPENING_DATE                  DATE,
    AFM_NO                        CHAR(20),
    ID_NO                         VARCHAR(20),
    DEL_DESCRIPTION_ID            VARCHAR(40),
    UNUTILIZED_DAYS               DECIMAL(15, 2),
    AVAILABLE_BALANCE             DECIMAL(15, 2),
    BLOCKED_BALANCE               DECIMAL(15, 2),
    LAST_DORMANT_DATE             DATE,
    CLOSING_TOTAL                 DECIMAL(15, 2),
    EMP_FIRST_NAME                VARCHAR(40),
    EMP_LAST_NAME                 VARCHAR(70),
    LAST_TRX_AMOUNT               DECIMAL(15, 2),
    FK_BANKEMPLOYEEID             CHAR(8),
    PERIOD_INTEREST               DECIMAL(15, 2),
    PERIOD_INT_TAX                DECIMAL(15, 2),
    DEL_TAX_WITHHELD_TO_DATE_LCY  DECIMAL(15, 2),
    FINAL_WHLD_TAX_FLG            CHAR(1),
    PRODUCT_TAX_PERC              DECIMAL(8, 4),
    APPROV_CR_RATE                DECIMAL(8, 4),
    APPROV_DB_RATE                DECIMAL(8, 4),
    DURATION_UNIT                 CHAR(1),
    DURATION_VALUE                SMALLINT,
    TEMP_EXC_END_DT               DATE,
    TEMP_EXC_START_DT             DATE,
    CR_INT_PERC                   DECIMAL(9, 6),
    TRANSACTION_CODE              INTEGER,
    ACCOUNT_TYPE                  CHAR(1),
    PROD_IDLE_DURATION            SMALLINT,
    ACCR_EXCESS_INTER             DECIMAL(15, 2),
    ACCR_EXCESS_INT_LC            DECIMAL(15, 2),
    CR_PROGRESS_INTER             DECIMAL(15, 2),
    CR_PROGRESS_INT_LC            DECIMAL(15, 2),
    DB_PROGRESS_INTER             DECIMAL(15, 2),
    DB_PROGRESS_INT_LC            DECIMAL(15, 2),
    ACCR_EXC_PROGRESS             DECIMAL(15, 2),
    ACCR_EXC_PROGRE_LC            DECIMAL(15, 2),
    ACCR_CR_INTER_LC              DECIMAL(15, 2),
    ACCR_DB_INTER_LC              DECIMAL(15, 2),
    OVERDRAFT_COMMENT             CHAR(40),
    TEMPORARY_EXCESS              DECIMAL(15, 2),
    LAST_DATE_SWITCHED_2_NEGATIVE DATE,
    DEL_LAST_TUN_DATE             DATE,
    DEL_LAST_TUN_USR              CHAR(8),
    DEL_LAST_TUN_USRSN            INTEGER,
    DEL_LAST_TUN_UNIT             INTEGER,
    DEL_LAST_TUN_CODE             INTEGER,
    OVERDU_DB_ACCRUALS            DECIMAL(15, 2),
    NORMAL_DB_ACCRUALS            DECIMAL(15, 2),
    GROSS_TOTAL                   DECIMAL(15, 2),
    GROSS_TOTAL_LC                DECIMAL(15, 2),
    EXCESS_INTEREST_RATE          DECIMAL(9, 6),
    CURRENCY                      CHAR(5),
    ACCT_KEY                      DECIMAL(11)              not null,
    LOAN_ACCT_KEY                 DECIMAL(11)    default 0 not null,
    DATE_IN_EXCESS                DATE,
    CLOSING_DATE                  DATE,
    LAST_STATEMENT_NUM            INTEGER,
    CLOSING_AMT                   DECIMAL(15, 2),
    BENEFICIARIES_NAMES_STANDARD  VARCHAR(2000),
    ATM_CARD_FLAG                 VARCHAR(7),
    DEPOSIT_TYPE_IND              VARCHAR(14),
    CUSTOMER_NAME                 VARCHAR(300),
    CLOSING_FEE                   DECIMAL(15, 2),
    CLOSING_USER                  CHAR(8),
    CLOSING_UNIT                  INTEGER,
    ACCOUNT_NO                    VARCHAR(50),
    DEL_INTEREST_TO_DATE_LCY      DECIMAL(15, 2) default 0,
    STATUS_IND                    VARCHAR(15),
    DORMANT_CR_CNTR_GL_ACC        CHAR(21),
    INTEREST_TO_WITHDRAW          DECIMAL(15, 2) default 0,
    MONITORING_EMPLOYEE_NAME      VARCHAR(41),
    CLOAN_CATEGORY_DESCRIPTION    VARCHAR(40),
    DEBIT_INTEREST_RATE           DECIMAL(15, 2),
    SALESPERSON                   VARCHAR(40),
    FKGH_TYPE                     CHAR(5),
    FKGD_TYPE                     INTEGER,
    FKGH_RESIDES_IN_RE            CHAR(5),
    FKGD_RESIDES_IN_RE            INTEGER,
    CLOSED_AUTHORIZER             CHAR(8),
    I_COMMENTS                    VARCHAR(40)
);

