create table STAGE_W_EOM_ACCOUNT
(
    EOM_DATE           DATE,
    ACCT_KEY           DECIMAL(11),
    ACCOUNT_NUMBER     CHAR(40),
    PRFT_SYSTEM        SMALLINT,
    ACCOUNT_CD         SMALLINT,
    CRM_NOTES_KEY      DECIMAL(11) default 0,
    PROFILE_KEY        SMALLINT,
    AGREE_ACCT_KEY     DECIMAL(11),
    AGREE_PATHSTRING   VARCHAR(2000),
    BENEFICIARIES_NAME VARCHAR(4000),
    OPEN_DATE          DATE,
    MONITORING_UNIT    DECIMAL(5),
    CUST_ID            DECIMAL(7),
    CUST_CD            DECIMAL(1),
    ACCT_STATUS_IND    VARCHAR(10),
    PRODUCT_ID         DECIMAL(5),
    CURRENCY_CODE      VARCHAR(5),
    OPEN_USER_CODE     VARCHAR(8),
    DATE_CLOSED        DATE,
    CUSTOMER_NAME      VARCHAR(91),
    CLOSING_DATE       DATE
);

