create table STAGE_W_DIM_ACCOUNT
(
    ACCT_KEY       DECIMAL(10),
    ACCOUNT_NUMBER CHAR(40),
    PRFT_SYSTEM    SMALLINT,
    ACCOUNT_CD     SMALLINT,
    ACCOUNT_NO     VARCHAR(43),
    DEP_ACC_NUMBER DECIMAL(11),
    LNS_OPEN_UNIT  INTEGER,
    LNS_TYPE       SMALLINT,
    LNS_SN         INTEGER,
    LG_ACC_SN      DECIMAL(13)
);

