create table STAGE_W_FACT_PROFILE_SECURITY
(
    PROFILE_ID          VARCHAR(8),
    WINDOW_CODE         VARCHAR(8),
    GUI_CODE            VARCHAR(8),
    ROW_EFFECTIVE_DATE  DATE,
    ROW_EXPIRATION_DATE DATE,
    ROW_CURRENT_FLAG    DECIMAL(15) default 0,
    SYSTEM_DESCRIPTION  VARCHAR(40)
);

