create table STAGE_W_EOM_COLLATERAL
(
    EOM_DATE                 DATE,
    COMBO_KEY                CHAR(20),
    PRODUCT_CODE             INTEGER,
    UNIT_CODE                INTEGER,
    COLLATERAL_SN            DECIMAL(10),
    COL_EST_VALUE_AMN        DECIMAL(15, 2),
    COLLATERAL_STATUS        CHAR(1),
    COLLATERAL_STATUS_IND    VARCHAR(12),
    COLLATERAL_MECHANISM_IND VARCHAR(15),
    PRODUCT_DESCRIPTION      VARCHAR(40),
    CURRENCY_CODE            VARCHAR(3),
    PRODUCT_DYNAMIC_DESCR    VARCHAR(40)
);

