create table STAGE_EOM_ACCOUNT_COLLATERAL
(
    FK_CUSTOMERCUST_ID     INTEGER     not null,
    PRFT_ACCOUNT           CHAR(40)    not null,
    EOM_DATE               DATE        not null,
    FK_COLLATERALFK_UN     INTEGER     not null,
    FK_COLLATERALFK_CO     INTEGER     not null,
    FK_COLLATERALCOLLA     DECIMAL(10) not null,
    INTERNAL_SN            SMALLINT    not null,
    ACCOUNT_NUMBER         CHAR(40)    not null,
    ACCOUNT_CD             SMALLINT,
    REVAL_CURR_FIX_RAT     DECIMAL(12, 6),
    REVAL_INIT_FIX_RAT     DECIMAL(12, 6),
    REVAL_INIT_SV          DECIMAL(15, 2),
    REVALUATION_CURRID     INTEGER,
    YIELD_UTILISED_AMN     DECIMAL(15, 2),
    YIELD_LIMIT_AMN        DECIMAL(15, 2),
    YIELD_PERC             DECIMAL(8, 4),
    CB_INSURANCE_AMN       DECIMAL(15, 2),
    UNIT_CODE              INTEGER,
    ISSUER_ACCOUNT         DECIMAL(13),
    BANK_CODE              SMALLINT,
    ITEMS_CNT              INTEGER,
    PROFITS_SYSTEM         INTEGER,
    EST_VALUE_AMN          DECIMAL(15, 2),
    EST_INSURANCE_AMN      DECIMAL(15, 2),
    FK_CURRENCYID_CURR     SMALLINT,
    NRM_BALANCE            DECIMAL(15, 2),
    OV_BALANCE             DECIMAL(15, 2),
    LG_AMOUNT_BAL          DECIMAL(15, 2),
    DEFAULT_AMN            DECIMAL(15, 2),
    TOT_EST_VALUE_AMN      DECIMAL(15, 2),
    INSERTION_DT           DATE,
    EXPIRY_DT              DATE,
    TMSTAMP                TIMESTAMP(6),
    NOTE_STATUS            CHAR(1),
    ENTRY_STATUS           CHAR(1),
    DEP_ACC_IND            CHAR(1),
    USER_CODE              CHAR(8),
    AFM_NO                 CHAR(20),
    REFERENCE_NUMBER       CHAR(20),
    FIRST_NAME             VARCHAR(20),
    ADDRESS                VARCHAR(40),
    SURNAME                VARCHAR(70),
    FK_COLLATERAL_TFK      INTEGER,
    REVAL_CHRG_AMN         DECIMAL(15, 2),
    MONITORING_UNIT        INTEGER,
    COLLATERAL_SN          DECIMAL(10),
    COLLATERAL_FK_UNITCODE INTEGER,
    COLLATERAL_STATUS      CHAR(1),
    ACCT_KEY               DECIMAL(11)
);

