create table STAGE_W_LOAN_ACCOUNT
(
    ACCOUNT_INTEGER               CHAR(40) not null,
    C_DIGIT                       INTEGER,
    NRM_RL_URL_FLG                INTEGER,
    OV_RL_URL_FLG                 INTEGER,
    ACCOUNT_CD                    INTEGER,
    PRFT_SYSTEM                   INTEGER,
    AGREEMENT_CD                  INTEGER,
    AGREEMENT_SYSTEM              INTEGER,
    ACC_TYPE                      INTEGER,
    INSTALL_FREQ                  INTEGER,
    INSTALL_COUNT                 INTEGER,
    LAST_NRM_TRX_CNT              INTEGER,
    FK_BASE_RATEFK_GD             INTEGER,
    FK_UNITCODE                   INTEGER,
    LNS_OPEN_UNIT                 INTEGER,
    ID_PRODUCT                    INTEGER,
    FKCUR_IS_CHARACTERGED         INTEGER,
    FKCUR_IS_MOVED_IN             INTEGER,
    FKCUR_USES_AS_LIM             INTEGER,
    FKGD_HAS_AS_CLASS             INTEGER,
    FKGD_HAS_AS_FINANC            INTEGER,
    FKGD_HAS_AS_LOAN_P            INTEGER,
    FKGD_CATEGORY                 INTEGER,
    FK_INTERESTID_INTE            INTEGER,
    ACC_SN                        INTEGER,
    CUST_ID                       INTEGER,
    REMAINING_DAYS                INTEGER,
    REMAINING_MONTHS              INTEGER,
    TOTAL_DAYS                    INTEGER,
    TOTAL_MONTHS                  INTEGER,
    OVERDUE_DAYS                  INTEGER,
    OVERDUE_MONTHS                INTEGER,
    NRM_CAP_BAL                   DECIMAL(15, 2),
    NRM_RL_INT_BAL                DECIMAL(15, 2),
    NRM_URL_INT_BAL               DECIMAL(15, 2),
    NRM_EXP_BAL                   DECIMAL(15, 2),
    NRM_COM_BAL                   DECIMAL(15, 2),
    NRM_ACR_INT_BAL               DECIMAL(15, 2),
    NRM_SUBSIDY_BAL               DECIMAL(15, 2),
    OV_CAP_BAL                    DECIMAL(15, 2),
    OV_RL_NRM_INT_BAL             DECIMAL(15, 2),
    OV_RL_PNL_INT_BAL             DECIMAL(15, 2),
    OV_URL_NRM_INT_BAL            DECIMAL(15, 2),
    OV_URL_PNL_INT_BAL            DECIMAL(15, 2),
    OV_EXP_BAL                    DECIMAL(15, 2),
    OV_COM_BAL                    DECIMAL(15, 2),
    OV_ACR_NRM_INT_BAL            DECIMAL(15, 2),
    OV_ACR_PNL_INT_BAL            DECIMAL(15, 2),
    OV_SUBSIDY_BAL                DECIMAL(15, 2),
    ACC_LIMIT_AMN                 DECIMAL(15, 2),
    POSITIVE_AMN                  DECIMAL(15, 2),
    UNCLEAR_AMN                   DECIMAL(15, 2),
    BLOCKED_AMN                   DECIMAL(15, 2),
    DORMANT_AMN                   DECIMAL(15, 2),
    INSTALL_FIXED_AMN             DECIMAL(15, 2),
    NRM_ACCRUAL_AMN               DECIMAL(15, 2),
    OV_ACCRUAL_AMN                DECIMAL(15, 2),
    LNS_UNREALIZED                DECIMAL(15, 2),
    PRFT_ACC_LMT_AMN              DECIMAL(15, 2),
    BOOK_BALANCE                  DECIMAL(15, 2),
    NRM_BALANCE                   DECIMAL(15, 2),
    OV_BALANCE                    DECIMAL(15, 2),
    OV_MKT                        DECIMAL(15, 2),
    SELECTED_BANK_RATE            DECIMAL(8, 4),
    SELECTED_NORMAL_RA            DECIMAL(8, 4),
    FINAL_INTEREST                DECIMAL(8, 4),
    BASE_SPREAD                   DECIMAL(8, 4),
    SPREAD                        DECIMAL(8, 4),
    N128                          DECIMAL(9, 6),
    BANK_SPREAD                   DECIMAL(12, 6),
    INSTALL_FIRST_DT              DATE,
    INSTALL_NEXT_DT               DATE,
    INSTALL_PREV_DT               DATE,
    ACC_EXP_DT                    DATE,
    ACC_OPEN_DT                   DATE,
    OV_EXP_DT                     DATE,
    LOAN_STATUS                   CHAR(1),
    ACC_STATUS                    CHAR(1),
    ACC_MECHANISM                 CHAR(1),
    FIRST_NAME                    CHAR(20),
    NRM_DR_CNTR_GL_ACC            CHAR(21),
    NRM_CR_CNTR_GL_ACC            CHAR(21),
    OV_DR_CNTR_GL_ACC             CHAR(21),
    DEFINATE_DELAY                CHAR(21),
    WRITE_OFF                     CHAR(21),
    AGREEMENT_INTEGER             CHAR(40),
    SURNAME                       CHAR(70),
    PAN_DUE_CAT                   VARCHAR(8),
    LNS_INTEREST_DESC             VARCHAR(40),
    DESCRIPTION                   VARCHAR(40),
    PRODUCT_DESC                  VARCHAR(40),
    UNIT_NAME                     VARCHAR(40),
    DRAWDOWN_FST_AMN              DECIMAL(15, 2),
    DRAWDOWN_FST_DT               DATE,
    INSTA_PAID                    INTEGER,
    PROVISION_AMN                 DECIMAL(15, 2),
    PROVISION_CURR_PERC           INTEGER,
    TOT_CAP_AMN                   DECIMAL(15, 2),
    TOT_COMMISSION_AMN            DECIMAL(15, 2),
    TOT_DRAWDOWN_AMN              DECIMAL(15, 2),
    TOT_EXPENSE_AMN               DECIMAL(15, 2),
    TOT_NRM_INT_AMN               DECIMAL(15, 2),
    TOT_PNL_INT_AMN               DECIMAL(15, 2),
    FKGH_CBPURP                   CHAR(5),
    FKGD_CBPURP                   INTEGER,
    FKINT_CURRENT_FIX             INTEGER,
    FKINT_AS_FLOATING             INTEGER,
    FKINT_PREV_FIXED              INTEGER,
    PENALTY_INTE_RATE             DECIMAL(8, 4),
    CUST_TYPE                     INTEGER,
    OV_GL_ACCRUAL_ACC             CHAR(21),
    DEF_GL_ACCRUAL_ACC            CHAR(21),
    LOAN_TYPE                     CHAR(2),
    PREV_SUB_CLASS                CHAR(1),
    CURR_SUB_CLASS                CHAR(1),
    PROVISION_AMOUNT              DECIMAL(15, 2),
    FKGH_HAS_AS_CLASS             CHAR(5),
    EURO_BOOK_BAL                 DECIMAL(15, 2),
    FIXING_RATE                   DECIMAL(12, 6),
    TRX_AMN_WO_WD                 DECIMAL(15, 2),
    TRX_AMN_CAP_INT               DECIMAL(15, 2),
    DISCOUNTED_VALUE              DECIMAL(15, 2),
    WRITE_OFF_PAY_AMT             DECIMAL(15, 2),
    FKGH_HAS_AS_FINANC            CHAR(5),
    FKGH_AS_CRED_LINE             CHAR(5),
    FKGD_AS_CRED_LINE             INTEGER,
    TRX_AMN                       DECIMAL(15, 2),
    REQUEST_TYPE                  CHAR(1),
    DRAWDOWN_EXP_DT               DATE,
    HOLDR_DESCRIPTION             CHAR(20),
    FKGH_CATEGORY                 CHAR(5),
    FK_GENERIC_DETASER            INTEGER,
    FK_CATEGORYCATEGOR            CHAR(5),
    LAST_TRANSACTION_DATE         DATE,
    OV_INST_CNT                   INTEGER,
    MONOTORING_UNIT               INTEGER,
    LOAN_CLASS                    CHAR(1),
    AGR_LIMIT                     DECIMAL(15, 2),
    GROSS_TOTAL                   DECIMAL(15, 2),
    LC_GROSS_TOTAL                DECIMAL(15, 2),
    INTEREST_IN_SUSPENSE          DECIMAL(15, 2),
    ADJUSTED_SUB_CLASS            CHAR(1),
    ACTUAL_SUB_CLASS              CHAR(1),
    ADJUSTED_CLASS                CHAR(1),
    COLLATERAL_OM_VALUE           DECIMAL(15, 2),
    FINAL_SUB_CLASS               CHAR(1),
    ACC_DRAWDOWN_STS              CHAR(1),
    ACCT_KEY                      INTEGER,
    RECYCLING_LMT_FLG             CHAR(1),
    LUMP_DRAWDOWN_FLG             CHAR(1),
    FKGH_HAS_ADJUST               CHAR(5),
    FKGD_HAS_ADJUST               INTEGER,
    CURRENCY                      CHAR(5),
    ISS_REMAINING_AMNT            DECIMAL(15, 2),
    SERVICE_DEP_ACCT_KEY          INTEGER,
    AGREEM_ACCT_KEY               INTEGER,
    TOT_INT_SPRD_AMN              DECIMAL(15, 2),
    TOT_SUBS_INT_AMN              DECIMAL(15, 2),
    CLOSED_FLAG                   CHAR(3),
    CUSTOMER_NAME                 VARCHAR(300),
    LOAN_TYPE_NAME                VARCHAR(38),
    LAST_MONTH_INTEREST_DEBIT_AMT DECIMAL(15, 2),
    FINAL_CLASS_NAME              VARCHAR(14),
    DATE_CLASS_CHANGED            DATE,
    CRM_ARREARS_DATE              DATE,
    CRM_LAND_REGISTRY_INTEGER     VARCHAR(40),
    CRM_NOTICE_ISSUE_DATE_90      DATE,
    CRM_NOTICE_MATURITY_DATE_90   DATE,
    CRM_NOTICE_ISSUE_DATE_40      DATE,
    CRM_NOTICE_MATURITY_DATE_40   DATE,
    CRM_AUCTION_DATE              DATE,
    CRM_COMMENTS                  VARCHAR(500),
    ACCOUNT_NO                    VARCHAR(50),
    RECOVERIES_DATE               DATE,
    MONTHLY_PREMIUM               DECIMAL(15, 2),
    LEDGER_FEES                   DECIMAL(15, 2),
    DELAY_OFFICER_ID              VARCHAR(8),
    DELAY_OFFICER_NAME            VARCHAR(41),
    LOAN_STATUS_IND_NAME          VARCHAR(15),
    CLOAN_CATEGORY_DESCRIPTION    VARCHAR(40),
    INSTALLMENT_AMOUNT            DECIMAL(15, 2),
    LOAN_OFFICER_ID               VARCHAR(8),
    LOAN_OFFICER_NAME             VARCHAR(41),
    TRANSFER_WRITEOFF_DATE        DATE,
    REMAINING_CAPITAL_AMT         DECIMAL(15, 2),
    FINSC_DESCRIPTION             VARCHAR(40),
    FIRST_SERVICE_ACCOUNT_NO      VARCHAR(50),
    MEDIATOR_CODE                 INTEGER,
    MEDIATOR_DESCRIPTION          VARCHAR(100),
    GRACE_PERIOD_DURATION_MONTHS  INTEGER,
    OVERDRAFT_TYPE_FLAG           VARCHAR(13),
    FKGH_HAS_AS_LOAN_P            CHAR(5),
    ANNUAL_WRITE_OFF_PAYMENTS     DECIMAL(15, 2),
    ANNUAL_WRITE_OFF_DB           DECIMAL(15, 2)
);

