create table STAGE_W_EOM_LG_ACCOUNT
(
    EOM_DATE                       DATE,
    ACCT_KEY                       DECIMAL(11),
    ACCOUNT_NUMBER                 CHAR(40),
    ACCOUNT_CD                     SMALLINT,
    CUST_ID                        INTEGER,
    CUST_CD                        SMALLINT,
    CUSTOMER_NAME                  VARCHAR(107),
    PRFT_SYSTEM                    SMALLINT,
    LG_ACCOUNT_TYPE                SMALLINT,
    LG_ACCOUNT_TYPE_DESCRIPTION    VARCHAR(40),
    LG_BODY_IND                    CHAR(1),
    LG_BODY_IND_NAME               VARCHAR(16),
    OVERDUE_FLAG                   CHAR(1),
    OVERDUE_FLAG_NAME              VARCHAR(11),
    EXTENSION_FLAG                 CHAR(1),
    EXTENSION_FLAG_NAME            VARCHAR(13),
    COMM_CHARGE_FREQUENCY          SMALLINT,
    COMM_CHARGE_FREQ_TYPE_IND      CHAR(1),
    COMM_CHARGE_FREQ_TYPE_IND_NAME VARCHAR(6),
    REPLACEMENT_REASON             CHAR(40),
    ACCOUNT_STATUS_IND             CHAR(1),
    ACCOUNT_STATUS_IND_NAME        VARCHAR(9),
    OBLIGATION_STATUS_IND          CHAR(1),
    OBLIGATION_STATUS_IND_NAME     VARCHAR(24),
    ACCOUNT_OPEN_DATE              DATE,
    LANGUAGE_CODE                  INTEGER,
    LANGUAGE_DESCRIPTION           VARCHAR(40),
    EXPIRATION_TYPE_IND            CHAR(1),
    EXPIRATION_TYPE_IND_NAME       VARCHAR(8),
    EXPIRY_DATE                    DATE,
    GUARANTEE_DATE                 DATE,
    RELEASE_DATE                   DATE,
    DEFAULT_TYPE                   CHAR(1),
    DEFAULT_DATE                   DATE,
    DEFAULT_AMOUNT                 DECIMAL(15, 2),
    REQUEST_DEFAULT_TYPE           CHAR(1),
    REQUEST_DEFAULT_TYPE_NAME      VARCHAR(25),
    REQUEST_DEFAULT_DATE           DATE,
    REQUEST_DEFAULT_AMOUNT         DECIMAL(15, 2),
    NEXT_COMMISSION_DATE           DATE,
    BALANCE_AMOUNT                 DECIMAL(15, 2),
    TOLERANCE_AMOUNT               DECIMAL(8, 4),
    INITIAL_AMOUNT                 DECIMAL(15, 2),
    LIMIT_AMOUNT                   DECIMAL(15, 2),
    DEPOSIT_ACCT_KEY               DECIMAL(11),
    DEPOSIT_ACCOUNT_NUMBER         CHAR(40),
    DEPOSIT_ACCOUNT_CD             SMALLINT,
    UNREALISED_COMMISS_FLAG        CHAR(1),
    UNREALISED_COMMISS_FLAG_NAME   VARCHAR(10),
    STOP_COMMISSION_DATE           DATE,
    STOP_COMMISSION_USER_CODE      CHAR(8),
    PRODUCT_ID                     INTEGER,
    PRODUCT_DESCRIPTION            VARCHAR(40),
    BENEFICIARY_CUST_ID            INTEGER,
    BENEFICIARY_CUST_CD            SMALLINT,
    BENEFICIARY_CUST_NAME          VARCHAR(107),
    AGREEMENT_ACCT_KEY             DECIMAL(11),
    AGREEMENT_ACCOUNT_NUMBER       CHAR(40),
    AGREEMENT_ACCOUNT_CD           SMALLINT,
    UNIT_CODE                      INTEGER,
    CHARGES_CURRENCY_ID            INTEGER,
    CHARGES_CURRENCY               CHAR(5),
    ISSUE_CUSTOMER_ID              INTEGER,
    MODIFICATION_USER_CODE         CHAR(8),
    MODIFICATION_USER_NAME         VARCHAR(41),
    MOVEMENT_CURRENCY_ID           INTEGER,
    MOVEMENT_CURRENCY              CHAR(5),
    OPEN_UNIT_CODE                 INTEGER,
    OPEN_UNIT_NAME                 VARCHAR(40),
    PRINT_UNIT_CODE                INTEGER,
    PRINT_UNIT_NAME                VARCHAR(40),
    LIMITS_CURRENCY_ID             INTEGER,
    LIMITS_CURRENCY                CHAR(5),
    ISSUANCE_JUSTIFICATION         VARCHAR(400),
    GROSS_TOTAL                    DECIMAL(15, 2),
    GROSS_TOTAL_LCY                DECIMAL(15, 2),
    BALANCE_AMOUNT_LCY             DECIMAL(15, 2),
    FIXING_RATE                    DECIMAL(12, 6),
    TOT_COMMISSION_BALANCE         DECIMAL(15, 2)
);

