create table STAGE_W_EOM_DH_COLLAT_ITEM
(
    EOM_DATE              DATE,
    COLLAT_ITEM_COMBO_KEY CHAR(12),
    COLLAT_COMBO_KEY      CHAR(20)
);

create unique index STAGE_PK_W_EOM_DH_COLLAT_COLLAT_ITEM
    on STAGE_W_EOM_DH_COLLAT_ITEM (EOM_DATE, COLLAT_ITEM_COMBO_KEY, COLLAT_COMBO_KEY);

