create table STAGE_W_AGG_ACCT_USERFIELDS
(
    ACCOUNT_NUMBER           CHAR(40),
    PRFT_SYSTEM              SMALLINT,
    PROVISION_AMT            DECIMAL(15, 2),
    INTEREST_IN_SUSPENSE_AMT DECIMAL(15, 2),
    DISCOUNTED_VALUE_AMT     DECIMAL(15, 2),
    FINAL_CLASS_IND          VARCHAR(100),
    FINAL_SUB_CLASS_IND      CHAR(1),
    ADJUSTED_SUB_CLASS_IND   VARCHAR(100),
    ADJUSTED_CLASS_IND       VARCHAR(100),
    ACTUAL_SUB_CLASS_IND     VARCHAR(100),
    COLLATERAL_OM_VALUE_AMT  DECIMAL(15, 2),
    FINAL_SUB_CLASS_NAME     CHAR(11),
    FINAL_CLASS_NAME         VARCHAR(14),
    DATE_CLASS_CHANGED       DATE
);

