create table STAGE_W_EOM_LC_ACCOUNT
(
    EOM_DATE                      DATE,
    ACCT_KEY                      DECIMAL(11) not null,
    LC_ACCOUNT_CODE               CHAR(40)    not null,
    LC_ACCOUNT_CD                 SMALLINT,
    TRADE_TYPE_IND                CHAR(1),
    TRADE_TYPE_IND_NAME           VARCHAR(8),
    TF_ACCOUNT                    CHAR(40)    not null,
    TF_ACCOUNT_CD                 SMALLINT,
    REFERENCE_NO                  VARCHAR(40),
    ISSUER_NAME                   CHAR(70),
    BENEFICIARY_NAME              CHAR(70),
    LC_PRODUCT_CODE               INTEGER,
    LC_PRODUCT_DESCRIPTION        VARCHAR(40),
    OPENING_UNIT_CODE             INTEGER,
    OPENING_UNIT_NAME             VARCHAR(40),
    MONITORING_UNIT_CODE          INTEGER,
    MONITORING_UNIT_NAME          VARCHAR(40),
    JUSTIFICATION_CODE            INTEGER,
    JUSTIFICATION_DESCRIPTION     VARCHAR(40),
    LIMIT                         DECIMAL(15, 2),
    LIMIT_CURRENCY                CHAR(5),
    CURRENT_AMOUNT                DECIMAL(15, 2),
    INITIAL_AMOUNT                DECIMAL(15, 2),
    UTILIZED_AMOUNT               DECIMAL(15, 2),
    NON_UTILIZED_AMOUNT           DECIMAL(15, 2),
    CHARGES_CURRENCY              CHAR(5),
    OPENING_DATE                  DATE,
    ISSUE_DATE                    DATE,
    EXPIRATION_DATE               DATE,
    CLOSING_LOCATION              CHAR(20),
    SETTLEMENT_TYPE_IND           SMALLINT,
    SETTLEMENT_TYPE_IND_NAME      VARCHAR(16),
    DISPATCH_TYPE_IND             SMALLINT,
    DISPATCH_TYPE_IND_NAME        VARCHAR(5),
    LC_TYPE                       SMALLINT,
    LC_TYPE_NAME                  VARCHAR(19),
    TOLERANCE                     DECIMAL(7, 4),
    INVOICE_PERCENTAGE            DECIMAL(7, 4),
    CHARGING_FREQUENCY            SMALLINT,
    CHARGING_FREQUENCY_IND        CHAR(1),
    CHARGING_FREQUENCY_IND_NAME   VARCHAR(6),
    CONFIRM_FLAG                  CHAR(1),
    CONFIRM_FLAG_NAME             VARCHAR(13),
    IRREVOCABLE_FLAG              CHAR(1),
    IRREVOCABLE_FLAG_NAME         VARCHAR(17),
    PARTIAL_SHIPMENT_FLAG         CHAR(1),
    PARTIAL_SHIPMENT_FLAG_NAME    VARCHAR(20),
    TRANSHIPMENT_FLAG             CHAR(1),
    TRANSHIPMENT_FLAG_NAME        VARCHAR(16),
    ASSIGNED_OF_PROCEED_FLAG      CHAR(1),
    ASSIGNED_OF_PROCEED_FLAG_NAME VARCHAR(21),
    RED_CLAUSE_FLAG               CHAR(1),
    RED_CLAUSE_FLAG_NAME          VARCHAR(14),
    REVOLVING_FLAG                CHAR(1),
    REVOLVING_FLAG_NAME           VARCHAR(13),
    COLLECTING_BANK_BIC           CHAR(11),
    COLLECTING_BANK_NAME          VARCHAR(105),
    REMITTING_BANK_BIC            CHAR(11),
    REMITTING_BANK_NAME           VARCHAR(105),
    INVOICE_TYPE                  INTEGER,
    INVOICE_TYPE_DESCRIPTION      VARCHAR(40),
    AGREEMENT_NO                  CHAR(40),
    AGREEMENT_NO_CD               SMALLINT,
    AGREEMENT_LIMIT               DECIMAL(15, 2),
    UTILISED_LIMIT                DECIMAL(15, 2),
    NON_UTILISED_AMOUNT           DECIMAL(15, 2),
    TRANSFER_LC                   CHAR(40),
    STATUS_IND                    CHAR(1),
    STATUS_IND_NAME               VARCHAR(7),
    LOAN_ACCT_KEY                 DECIMAL(11),
    COMMISSION_AMOUNT             DECIMAL(15, 2),
    EXPENSES_AMOUNT               DECIMAL(15, 2),
    BALANCE_AMOUNT_LCY            DECIMAL(15, 2),
    FIXING_RATE                   DECIMAL(12, 6),
    PRINCIPAL_CUST_ID             INTEGER,
    PRINCIPAL_CUST_CD             SMALLINT,
    LOAN_CUST_ID                  INTEGER,
    LOAN_CUST_CD                  INTEGER,
    LOAN_CUSTOMER_NAME            VARCHAR(300),
    LOAN_OFFICER_ID               VARCHAR(8),
    LOAN_OFFICER_NAME             VARCHAR(300),
    LOAN_ACCOUNT_NO               VARCHAR(50),
    TOT_COMMISSION_BALANCE        DECIMAL(15, 2)
);

