create table STAT_CUST_PROD
(
    DEPOSIT_GROUP  SMALLINT,
    CUST_GROUP     SMALLINT,
    DAYS_DURATION  SMALLINT,
    LOW_LIMIT      DECIMAL(15, 4),
    UP_LIMIT       DECIMAL(15, 4),
    ID_CURRENCY    INTEGER,
    CUST_TYPE      CHAR(1),
    EUR_IN_COUNTRY CHAR(1),
    NON_RESIDENT   CHAR(1),
    ID_COUNTRY     INTEGER,
    BOOK_BALANCE   DECIMAL(15, 2),
    DEPOSIT_TYPE   CHAR(1),
    COUNTS         DECIMAL(10)
);

create unique index IXP_STA_000
    on STAT_CUST_PROD (DEPOSIT_GROUP, CUST_GROUP, DAYS_DURATION, LOW_LIMIT, UP_LIMIT, ID_CURRENCY, CUST_TYPE,
                       EUR_IN_COUNTRY, NON_RESIDENT);

