create table STAT_ACCOUNT_CHEQ
(
    DATE_FROM          DATE,
    DATE_TO            DATE,
    ITEM_SERIAL_NUMBER DECIMAL(10),
    ACCOUNT_NUMBER     DECIMAL(11),
    BOUNCED_CNT        SMALLINT
);

create unique index IXU_STA_006
    on STAT_ACCOUNT_CHEQ (DATE_FROM, DATE_TO, ITEM_SERIAL_NUMBER, ACCOUNT_NUMBER);

