create table STAT_ACCOUNT_BAL
(
    ACCOUNT_NUMBER      DECIMAL(11),
    DAYS_DURATION       SMALLINT,
    ID_CURRENCY         INTEGER,
    ID_PRODUCT          INTEGER,
    RENEWAL_SER_NUM     INTEGER,
    SERIAL_NUM_L        INTEGER,
    SERIAL_NUM_P        INTEGER,
    SERIAL_NUM_F        INTEGER,
    CUST_ID             INTEGER,
    RATE                DECIMAL(8, 4),
    FIXING_RATE         DECIMAL(12, 6),
    INTEREST            DECIMAL(15, 2),
    BOOK_BALANCE        DECIMAL(15, 2),
    AVER_INT_BAL        DECIMAL(15, 2),
    EURO_BOOK_BAL       DECIMAL(15, 2),
    EURO_AVER_INT_BAL   DECIMAL(15, 2),
    EURO_INTEREST       DECIMAL(15, 2),
    EUR_IN_COUNTRY      CHAR(1),
    NON_RESIDENT        CHAR(1),
    DEPOSIT_TYPE        CHAR(1),
    CUST_TYPE           CHAR(1),
    PARAMETER_TYPE_P    CHAR(5),
    PARAMETER_TYPE_L    CHAR(5),
    PARAMETER_TYPE_F    CHAR(5),
    EURO_AMOUNT_PORTION DECIMAL(15, 2),
    EURO_ACCR_CR_TAX    DECIMAL(15, 2),
    ACCR_CR_TAX         DECIMAL(15, 2),
    EURO_ACCR_DB_INTER  DECIMAL(15, 2),
    EURO_ACCR_CR_INTER  DECIMAL(15, 2),
    COBENEF_COUNT_INS   SMALLINT,
    COBENEF_COUNT       SMALLINT,
    ACCR_CR_INTEREST    DECIMAL(15, 2),
    ACCR_DB_INTEREST    DECIMAL(15, 2),
    FINAL_WHLD_TAX_FLG  CHAR(1),
    IBAN                VARCHAR(40),
    TOTAL_AMOUNT_OWED   DECIMAL(15, 2)
);

create unique index IXP_STA_003
    on STAT_ACCOUNT_BAL (ACCOUNT_NUMBER);

