create table STAT_CUST_GROUP
(
    PARAMETER_TYPE CHAR(5),
    SERIAL_NUM     INTEGER,
    CUST_GROUP     SMALLINT,
    CUST_TYPE      CHAR(1),
    CUST_GRP_DESC  CHAR(30)
);

create unique index IXP_STA_001
    on STAT_CUST_GROUP (PARAMETER_TYPE, SERIAL_NUM, CUST_GROUP);

