create table STAT_DEPOSIT_GROUP
(
    DEPOSIT_GROUP    SMALLINT,
    ID_PRODUCT       INTEGER,
    DEPOSIT_GRP_DESC CHAR(30)
);

create unique index IXP_STA_007
    on STAT_DEPOSIT_GROUP (DEPOSIT_GROUP, ID_PRODUCT);

