create table STOCK_ORDER
(
    FK_UW_TERMUW_CODE  INTEGER,
    ORDER_CODE         INTEGER,
    UNBLOCK_SN         INTEGER,
    BLOCK_SN           INTEGER,
    FK_UNITCODE        INTEGER,
    TRX_SN             INTEGER,
    CURRENCY_ID        INTEGER,
    FK_GENERIC_DETASER INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    CONFIRMATION_ITEMS INTEGER,
    ORDER_ITEMS        INTEGER,
    OLD_ORDER_ITEMS    INTEGER,
    BLOCK_ACCOUNT      DECIMAL(11),
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    ORDER_PRICE        DECIMAL(13, 5),
    BLOCK_AMOUNT       DECIMAL(15, 2),
    ORDER_AMOUNT       DECIMAL(15, 2),
    CONFIRMATION_DATE  DATE,
    TIMESTMP           DATE,
    ORDER_DATE         DATE,
    ORDER_STATUS       CHAR(1),
    ORDER_TYPE         CHAR(1),
    FK_GENERIC_DETAFK  CHAR(5),
    FK_USRCODE         CHAR(8),
    REFERENCE_NO       CHAR(20),
    COMMENTS           CHAR(40)
);

create unique index IXU_STO_003
    on STOCK_ORDER (FK_UW_TERMUW_CODE, ORDER_CODE);

