create table SUBSIDY_ORDER
(
    ID_SUBSIDY         INTEGER,
    SUBS_DURATION_PRD  SMALLINT,
    UNPAID_RQ_CNT      SMALLINT,
    FK_INTERESTID_INTE INTEGER,
    LNS_EFFECTIVE_DT   DATE,
    LNS_EXPIRY_DATE    DATE,
    TMSTAMP            TIMESTAMP(6),
    EXPIRY_DT          DATE,
    ENTRY_STATUS       CHAR(1),
    PAY_DEPEND_FLG     CHAR(1),
    DEFINITE_DELAY_IND CHAR(1),
    INTEREST_IND       CHAR(1),
    SUBSIDY_CODE       CHAR(10),
    DESCRIPTION        CHAR(40),
    SUBS_ORDER_CODE    CHAR(40),
    ENTRY_COMMENTS     CHAR(50)
);

create unique index IXU_SUB_004
    on SUBSIDY_ORDER (ID_SUBSIDY);

