create table SUP_MASTER
(
    SUPPLIER_ID               DECIMAL(18)  not null
        constraint IXU_SUPMASTER_001
            primary key,
    SURNAME                   VARCHAR(200) not null,
    LATIN_SURNAME             VARCHAR(200),
    SHORT_NAME                VARCHAR(200),
    FKGH_HAS_SUPT             CHAR(5),
    FKGD_HAS_SUPT             DECIMAL(5),
    NO_AFM                    VARCHAR(1),
    AFM_NO                    VARCHAR(20),
    FK_TAX_OFFICEID           DECIMAL(4),
    FK_CUST_ID                DECIMAL(7),
    CUST_TYPE                 CHAR(1),
    FK_GLG_ACCOUNTACCO        CHAR(21),
    TURNOVER_AMN              DECIMAL(18, 2),
    LIMIT_AMN                 DECIMAL(18, 2),
    ADDITIONAL_INFO           VARCHAR(2000),
    FKUNIT_IS_MONITORE        DECIMAL(5),
    FKCURR_CODE               DECIMAL(5),
    FK_DISTR_CHANNEID         DECIMAL(5),
    OLD_SUPPLIER_ID           DECIMAL(18),
    ENTRY_STATUS              VARCHAR(1),
    INTERNET_ADDRESS          VARCHAR(1000),
    FKGH_HAS_CATEGORY_CODE    CHAR(5),
    FKGD_HAS_CATEGORY_CODE    DECIMAL(5),
    FKGH_HAS_SUBCATEGORY_CODE CHAR(5),
    FKGD_HAS_SUBCATEGORY_CODE DECIMAL(5),
    DISCOUNT_PER              DECIMAL(3),
    ADDDISCOUNT_PER           DECIMAL(3),
    FKGH_HAS_PROFF            CHAR(5),
    FKGD_HAS_PROFF            DECIMAL(5),
    FKGH_HAS_VAT_CATEGORY     CHAR(5),
    FKGD_HAS_VAT_CATEGORY     DECIMAL(5),
    FKGH_HAS_SUP_CATEGORY     CHAR(5),
    FKGD_HAS_SUP_CATEGORY     DECIMAL(5),
    FKGH_HAS_SUPPLIER_TYPE    CHAR(5),
    FKGD_HAS_SUPPLIER_TYPE    DECIMAL(5),
    IBAN_ACCOUNT              CHAR(27),
    SWIFT_ADRESS              VARCHAR(12),
    BANK                      VARCHAR(100),
    ADDRESS                   VARCHAR(200),
    ADDRESS_NUMBER            VARCHAR(20),
    REGION                    VARCHAR(100),
    CITY                      VARCHAR(100),
    ZIP_CODE                  VARCHAR(10),
    PO_BOX                    VARCHAR(20),
    FKGH_HAS_COUNTRY          CHAR(5),
    FKGD_HAS_COUNTRY          DECIMAL(5),
    TRX_LUSR                  CHAR(8),
    TRX_USR                   CHAR(8),
    TRX_LDATE                 DATE,
    TRX_DATE                  DATE,
    CREDIT_ACCOUNT_NO         DECIMAL(11)
);

