create table SUP_DPURCHASES
(
    TRX_DATE           DATE        not null,
    TRX_UNIT           DECIMAL(5)  not null,
    TRX_USER           CHAR(8)     not null,
    TRX_USR_SN         DECIMAL(8)  not null,
    TRX_USR_INT_SN     DECIMAL(2)  not null,
    PURCHASE_SN        DECIMAL(18) not null,
    TERMINAL_NUMBER    CHAR(30),
    PRFT_SYSTEM        DECIMAL(2),
    UNIT_CODE          DECIMAL(5),
    ITEM_TYPE          DECIMAL(5),
    FK_ITEM_ID         VARCHAR(10),
    MEASURING_UNIT     DECIMAL(5),
    QUANTITY           DECIMAL(10),
    ITEM_VALUE         DECIMAL(18, 2),
    FIXING_RATE        DECIMAL(12, 6),
    FC_AMOUNT          DECIMAL(18, 2),
    DC_AMOUNT          DECIMAL(18, 2),
    DC_AMOUNT_NET      DECIMAL(18, 2),
    FC_AMOUNT_NET      DECIMAL(18, 2),
    DC_AMOUNT_DIS      DECIMAL(18, 2),
    FC_AMOUNT_DIS      DECIMAL(18, 2),
    DC_AMOUNT_EXP      DECIMAL(18, 2),
    FC_AMOUNT_EXP      DECIMAL(18, 2),
    DC_AMOUNT_FPA      DECIMAL(18, 2),
    FC_AMOUNT_FPA      DECIMAL(18, 2),
    DC_AMOUNT_TAX      DECIMAL(18, 2),
    FC_AMOUNT_TAX      DECIMAL(18, 2),
    FPA_PERCENTAGE     DECIMAL(5),
    GL_TRN_DATE        DATE,
    FPA_CONTROL_ACC    CHAR(21),
    EXP_CONTROL_ACC    CHAR(21),
    DIS_CONTROL_ACC    CHAR(21),
    ITEM_CONTROL_ACC   CHAR(21),
    ITEMPR_CONTROL_ACC CHAR(21),
    SUPPL_CONTROL_ACC  CHAR(21),
    TAX_CONTROL_ACC    CHAR(21),
    REMARKS            VARCHAR(80),
    SUPPLIER_VALUE     DECIMAL(18, 2),
    TMSTAMP            TIMESTAMP(6),
    EXP_PERCENTAGE     DECIMAL(5),
    TAX_PERCENTAGE     DECIMAL(5),
    constraint IXU_SUP_DPUR
        primary key (TRX_DATE, TRX_UNIT, TRX_USER, TRX_USR_SN, TRX_USR_INT_SN, PURCHASE_SN)
);

