create table SUP_PAYMENTS
(
    TRX_DATE                 DATE       not null,
    TRX_UNIT                 DECIMAL(5) not null,
    TRX_USER                 CHAR(8)    not null,
    TRX_USR_SN               DECIMAL(8) not null,
    TRX_USR_INT_SN           DECIMAL(2) not null,
    PAYMENT_SN               DECIMAL(2) not null,
    PAYMENT_METHOD           DECIMAL(5) not null,
    FINAL_PAYMENT_SN         DECIMAL(2) not null,
    FINAL_PAYMENT_DT         DATE,
    FINAL_FC_AMOUNT          DECIMAL(18, 2),
    FINAL_DISCOUNT_AMOUNT_FC DECIMAL(18, 2),
    FINAL_DC_AMOUNT          DECIMAL(18, 2),
    FINAL_DISCOUNT_AMOUNT_DC DECIMAL(18, 2),
    FINAL_PAYMENT_METHOD     DECIMAL(5) not null,
    DB_DEPOSIT_ACC           DECIMAL(11),
    FK0DEPOSIT_ACCOACC       DECIMAL(11),
    BANK_DRAFT_NO            CHAR(10),
    FK_DEPOSIT_ACCOACC       DECIMAL(11),
    ORDER_CODE               VARCHAR(20),
    PRFT_REF_NO              CHAR(16),
    FK_DEPOSIT_ACC           DECIMAL(11),
    STATUS                   DECIMAL(5),
    SELECTION                DECIMAL(1),
    SELECTION_SET            DECIMAL(5),
    SELECTION_SN             DECIMAL(5),
    SELECTION_UNIT           CHAR(8),
    SELECTION_USR            CHAR(8),
    SELECTION_TMSTAMP        TIMESTAMP(6),
    COMMENTS                 VARCHAR(200),
    PO_REFERENCE_NO          DECIMAL(18),
    ID_PRODUCT               DECIMAL(5),
    TRX_CODE                 DECIMAL(5),
    ID_JUSTIFIC              DECIMAL(5),
    APPROVAL_DATE            DATE,
    APPROVAL_UNIT            DECIMAL(5),
    APPROVAL_USER            CHAR(8),
    APPROVAL_TMSTAMP         TIMESTAMP(6),
    PROCESSING_DATE          DATE,
    PROCESSING_UNIT          DECIMAL(5),
    PROCESSING_USER          CHAR(8),
    PROCESSING_TMSTAMP       TIMESTAMP(6),
    CR_TRX_DATE              DATE,
    CR_TRX_UNIT              DECIMAL(5),
    CR_TRX_USER              CHAR(8),
    CR_TRX_USR_SN            DECIMAL(8),
    CR_TRX_USR_INT_SN        DECIMAL(2),
    DB_TRX_DATE              DATE,
    DB_TRX_UNIT              DECIMAL(5),
    DB_TRX_USER              CHAR(8),
    DB_TRX_USR_SN            DECIMAL(8),
    DB_TRX_USR_INT_SN        DECIMAL(2),
    constraint IXU_SUP_PAYMENTS_PK
        primary key (TRX_DATE, TRX_UNIT, TRX_USER, TRX_USR_SN, TRX_USR_INT_SN, PAYMENT_SN, FINAL_PAYMENT_SN)
);

