create table SUSPECT_CUST_STAGE
(
    TRX_DATE                      TIMESTAMP(6) not null,
    AGENCY_REFERENCE_NUMBER       CHAR(8)      not null,
    REPEAT_SN                     INTEGER      not null,
    AGENCY_DATAID                 CHAR(10),
    ENTRY_STATUS                  CHAR(1),
    CUST_TYPE                     CHAR(1),
    AGENCY_VERSIONNUM             CHAR(10),
    FIRST_NAME                    CHAR(50),
    NAMES_OR_SURNAME              CHAR(70),
    AGENCY_LIST_TYPE              CHAR(10),
    LISTED_ON                     DATE,
    GENDER_INFO                   CHAR(10),
    SUBMITTED_BY                  CHAR(20),
    AGENCY_COMMENT                VARCHAR(1400),
    DESIGNATION_OR_TITLE          VARCHAR(350),
    NATIONALITY_INFO              CHAR(80),
    ALERT_AGENCY_TYPE             CHAR(10),
    AGENCY_UPDATED_TMSTAMP        DATE,
    ALIAS_NAME                    VARCHAR(350),
    ALIAS_DATE_OF_BIRTH           CHAR(10),
    ALIAS_PLACE_OF_BIRTH_INFO     CHAR(70),
    ALIAS_NOTE                    CHAR(250),
    ADDRESS_OR_STREET             CHAR(130),
    ADDRESS_CITY                  CHAR(150),
    ADDRESS_OR_STATE_PROVINCE     CHAR(100),
    ADDRESS_ZIP_CODE              CHAR(30),
    ADDRESS_COUNTRY               CHAR(70),
    ADDRESS_NOTE                  VARCHAR(600),
    TYPE_OF_BIRTH_DATE            CHAR(13),
    BIRTH_NOTE                    CHAR(30),
    YEAR_OF_BIRTH                 CHAR(4),
    DATE_OF_BIRTH                 CHAR(10),
    BIRTH_FROM_YEAR               CHAR(4),
    BIRTH_TO_YEAR                 CHAR(4),
    PLACE_OF_BIRTH_INFO           VARCHAR(350),
    TYPE_OF_MAIN_DOCUMENT         CHAR(40),
    DOCUMENT2_TYPE_INFO           CHAR(100),
    DOCUMENT_ISSUING_COUNTRY_INFO CHAR(140),
    DOCUMENT_DATE_OF_ISSUE        CHAR(10),
    DOCUMENT_NOTES                CHAR(200),
    DOCUMENT_NUMBER               CHAR(110),
    DELISTED_ON                   DATE,
    FILENAME                      CHAR(50),
    constraint CIFSCSPK
        primary key (TRX_DATE, REPEAT_SN, AGENCY_REFERENCE_NUMBER)
);

