create table SWEEP_AGREEMENT
(
    SWEEP_TYPE         CHAR(1)     not null,
    MIN_MAX_BAL_LIMIT  DECIMAL(15, 2),
    MIN_SWEEP_AMOUNT   DECIMAL(15, 2),
    SWEEP_AGR_DATE     DATE,
    TIMESTMP           TIMESTAMP(6),
    CR_JUSTIFICATION   INTEGER,
    DR_JUSTIFICATION   INTEGER,
    LOANS_SCHEME       CHAR(1),
    FK0DEPOSIT_ACCOACC DECIMAL(11) not null,
    FK_DEPOSIT_ACCOACC DECIMAL(11) not null,
    constraint PKEY_SWEEP_AGREEMENT
        primary key (FK_DEPOSIT_ACCOACC, FK0DEPOSIT_ACCOACC, SWEEP_TYPE)
);

create unique index I0000963
    on SWEEP_AGREEMENT (FK0DEPOSIT_ACCOACC);

create unique index I0000965
    on SWEEP_AGREEMENT (FK_DEPOSIT_ACCOACC);

