create table SWIFT_SETUP_VALUES
(
    MESSAGE_TYPE       CHAR(20) not null,
    TAG                CHAR(10) not null,
    MESSAGE_SN         INTEGER  not null,
    INTERNAL_SN        INTEGER  not null,
    MSG_CATEGORY       CHAR(1)  not null,
    SUBTAG_SN          SMALLINT,
    MANIPULATE_SUBTAG  SMALLINT,
    MANIPULATE_SUBTAG2 SMALLINT,
    NUMERIC_FUNCTION   CHAR(2),
    NEEDS_TYPE         CHAR(2),
    GEN_OPTION         CHAR(5),
    MANIPULATE_TAG     CHAR(10),
    NUMERIC_RESULT     CHAR(10),
    MANIPULATE_TAG_2   CHAR(10),
    ADDITIONAL_SWIFT   CHAR(20),
    ALLOW_VALUE        CHAR(40),
    PREDEFINED_VALUES  CHAR(40),
    CHAR_TEXT          CHAR(40),
    CHAR_FUNCTION      CHAR(40),
    ENTRY_DESCR        VARCHAR(80),
    GPI_REQUIRED_FLD   CHAR(1),
    GPI_CONTROL        CHAR(1),
    SEARCH_VALUE       CHAR(1),
    VALUE_OPTIONAL     CHAR(1),
    VALUE_FUNCTION     CHAR(1),
    MX_TAG_FOR_VALUE   VARCHAR(50),
    MX_TAG_FOR_FUNCT   VARCHAR(50),
    VALID_FOR_FUNCTIO  CHAR(1),
    constraint IXU_SWI_004
        primary key (MESSAGE_TYPE, TAG, MESSAGE_SN, INTERNAL_SN, MSG_CATEGORY)
);

create unique index SWIFT_SETUP_VALUES_IND1
    on SWIFT_SETUP_VALUES (MESSAGE_TYPE, MSG_CATEGORY);

