create table SWIFT_REF_FRM_DTL
(
    FRM_DTL_SN        SMALLINT   not null,
    FK_REF_FRM_CODE   CHAR(10)   not null,
    FK_REF_FRM_CATEG  CHAR(1)    not null,
    FK_REF_FRM_ORDSN  SMALLINT   not null,
    FRM_MAX_LENGTH    SMALLINT,
    FRM_BEGIN_OR_END  VARCHAR(7) not null,
    FRM_ACTION        VARCHAR(15),
    START_AT_POS      SMALLINT,
    END_AT_LENGTH     SMALLINT,
    START_AT_LIT      VARCHAR(40),
    START_LIT_COUNT   SMALLINT,
    START_LIT_INCLUDE CHAR(1),
    START_LIT_INTO    SMALLINT,
    END_AT_LIT        VARCHAR(40),
    END_LIT_COUNT     SMALLINT,
    END_LIT_INCLUDE   CHAR(1),
    END_LIT_INTO      SMALLINT,
    STR_LIT_F_ACTION  VARCHAR(15),
    LIT_NF_ACTION     VARCHAR(15),
    PADDING_LIT       VARCHAR(40),
    PAD_FOR_LENGTH    SMALLINT,
    VAL_FOUND_ACTION  VARCHAR(15),
    VAL_NF_ACTION     VARCHAR(15),
    FK_GH_LVAL_TYPE   CHAR(5),
    constraint PK_SWT_REF_FRM_DTL
        primary key (FK_REF_FRM_CODE, FK_REF_FRM_CATEG, FK_REF_FRM_ORDSN, FRM_DTL_SN),
    foreign key (FK_REF_FRM_CODE, FK_REF_FRM_CATEG, FK_REF_FRM_ORDSN) references SWIFT_REF_FRM
        on delete cascade
);

create unique index SK_SWT_REF_FRM_DTL
    on SWIFT_REF_FRM_DTL (FK_GH_LVAL_TYPE);

