create table SWIFT_100
(
    TRX_REFERENCE_NUMB CHAR(16),
    FK_ISSUE_UNIT      INTEGER,
    FK_OUTGOING_ORDORD INTEGER,
    MSG_CONFIRM_DATE   DATE,
    MSG_SEND_TIME      TIMESTAMP(6),
    TMSTAMP            TIMESTAMP(6),
    FK_SWIFT_COUNTEDAT DATE,
    ENTRY_STATUS       CHAR(1),
    DROP_LIST1         CHAR(1),
    PRIORITY_CODE      CHAR(2),
    DETAILS_OF_CHARGES CHAR(3),
    MSG_CONFIRM_BNKUSR CHAR(8),
    MSG_SEND_BNKUSR    CHAR(8),
    SWIFT_CODE         CHAR(12),
    FK_SWMSG_PRFTREFNO CHAR(16),
    VALUE_CURRENCY_AMO CHAR(24),
    BENEF_ADDRESS_3    CHAR(35),
    BENEF_ADDRESS_2    CHAR(35),
    BENEF_ADDRESS_1    CHAR(35),
    BENEF_ACCOUNT      CHAR(35),
    ORDER_ADDRESS_3    CHAR(35),
    ORDER_ADDRESS_2    CHAR(35),
    ORDER_ADDRESS_1    CHAR(35),
    SENDERS_CORRESPOND VARCHAR(15),
    ORDERING_CUSTOMER  VARCHAR(35),
    BENEFICIARY_CUSTOM VARCHAR(35),
    DETAILS_OF_PAYMENT VARCHAR(144),
    ACCOUNT_WITH_INSTI VARCHAR(185),
    INTERMEDIARY       VARCHAR(185),
    RECEIVERS_CORRESPO VARCHAR(185),
    ORDERING_INSTITUTI VARCHAR(185),
    SENDER_TO_RECEIVER VARCHAR(216)
);

create unique index IXU_SWI_016
    on SWIFT_100 (TRX_REFERENCE_NUMB);

