create table SWIFT_210
(
    TRX_REFERENCE_NUMB CHAR(16),
    FK_ISSUE_UNIT      INTEGER,
    MSG_SEND_TIME      TIMESTAMP(6),
    MSG_CONFIRM_DATE   DATE,
    TMSTAMP            TIMESTAMP(6),
    FK_SWIFT_COUNTEDAT DATE,
    ENTRY_STATUS       CHAR(1),
    PRIORITY_CODE      CHAR(2),
    TX_VALUE_DATE      CHAR(6),
    MSG_CONFIRM_BNKUSR CHAR(8),
    MSG_SEND_BNKUSR    CHAR(8),
    SWIFT_CODE         CHAR(12),
    FK_SWMSG_PRFTREFNO CHAR(16),
    RELATED_REFERENCE  CHAR(16),
    CURRENCY_AMO       CHAR(18),
    ORDERING_CUSTOMER  CHAR(35),
    ACCT_IDENTIFIC     CHAR(35),
    INTERMEDIARY       VARCHAR(200),
    ORDERING_INSTITUTI VARCHAR(200)
);

create unique index IXU_SWI_023
    on SWIFT_210 (TRX_REFERENCE_NUMB);

