create table SWIFT_300
(
    TRX_REFERENCE_NUMB CHAR(16),
    FK_ISSUE_UNIT      INTEGER,
    TMSTAMP            TIMESTAMP(6),
    MSG_CONFIRM_DATE   DATE,
    MSG_SEND_TIME      TIMESTAMP(6),
    FK_SWIFT_COUNTEDAT DATE,
    ENTRY_STATUS       CHAR(1),
    PRIORITY_CODE      CHAR(2),
    FIN_COPY           CHAR(3),
    TYPE_OF_OPERATION  CHAR(4),
    FX_VALUE_DATE      CHAR(8),
    FX_TRADE_DATE      CHAR(8),
    MSG_SEND_BNKUSR    CHAR(8),
    MSG_CONFIRM_BNKUSR CHAR(8),
    FX_RATE            CHAR(12),
    SWIFT_CODE         CHAR(12),
    RELATED_REFERENCE  CHAR(16),
    FK_SWMSG_PRFTREFNO CHAR(16),
    CURRENCY_AMO_SELL  CHAR(18),
    CURRENCY_AMO_BUY   CHAR(18),
    RECEIVE_CORRESPOND VARCHAR(200),
    SENDERS_CORRESPOND VARCHAR(200),
    RECEIVING_INSTITUT VARCHAR(200),
    PARTY_A            VARCHAR(200),
    PARTY_B            VARCHAR(200),
    SENDER_TO_RECEIVER VARCHAR(216),
    FLD_22C            CHAR(18) default ' '
);

create unique index IXU_SWI_024
    on SWIFT_300 (TRX_REFERENCE_NUMB);

