create table SWIFT_RECORDING
(
    TRX_DATE          DATE,
    ACCOUNT_NUMBER    DECIMAL(11),
    SEQUENCE_NO       INTEGER,
    STATEMENT_NO      INTEGER,
    STATEMENT_NO_YEAR SMALLINT,
    MSG_TYPE          CHAR(5),
    TRX_REFERENCE_NUM DECIMAL(10),
    TMSTAMP           TIMESTAMP(6),
    CREATED_FLAG      CHAR(1),
    MESSAGE_TEXT      VARCHAR(2048)
);

create unique index IXP_SWI_000
    on SWIFT_RECORDING (TRX_DATE, ACCOUNT_NUMBER, SEQUENCE_NO, STATEMENT_NO, STATEMENT_NO_YEAR, MSG_TYPE);

