create table SWIFT_SETUP_DETAIL
(
    MESSAGE_TYPE            CHAR(20) not null,
    TAG                     CHAR(10) not null,
    MESSAGE_SN              INTEGER  not null,
    MSG_CATEGORY            CHAR(1)  not null,
    SUBTAG_SN               SMALLINT,
    CHECK_CURR_STAG         SMALLINT,
    REPETATIVE_REF          INTEGER,
    TAG_REPEAT_NUMBER       INTEGER,
    TAG_FIELD_LENGTH        INTEGER,
    SHOW_ORDER              INTEGER,
    FK_VALIDATE_DCD_ID      DECIMAL(12),
    SUPPRESS_IF_ZERO        CHAR(1),
    NEED_VAL_VS_VAL         CHAR(1),
    EXACT_LENGTH            CHAR(1),
    SHOW_TO_USER            CHAR(1),
    CHECK_EXT_CHAR_SET      CHAR(1),
    MUR_FIELD               CHAR(1),
    TAG_PRIORITY            CHAR(1),
    TAG_RECEIVER            CHAR(1),
    TAG_SENDER              CHAR(1),
    TAG_STP                 CHAR(1),
    PRFT_REF_NO             CHAR(1),
    NEED_MANDA_FUNC         CHAR(1),
    REF_FLD_FLAG            CHAR(1),
    PROTECTED_FLAG          CHAR(1),
    CHECK_CURR_DEC          CHAR(1),
    CHECK_EQUALITY          CHAR(1),
    TAG_VALUE_AND_DATA      CHAR(1),
    TAG_NEXT_LINE           CHAR(1),
    TAG_MANDATORY           CHAR(1),
    TAG_REPETITIVE          CHAR(1),
    TAG_VERIFICATION        CHAR(1),
    NEED_MESSAGE_TYPE       CHAR(1),
    NEED_MANDATORY          CHAR(1),
    NEED_DISABLED           CHAR(1),
    NEED_SUMS               CHAR(1),
    NEED_CHAR_CHECK         CHAR(1),
    NEED_VALUES             CHAR(1),
    NEED_VALUE_DISABLE      CHAR(1),
    TAG_SAME_LINE           CHAR(1),
    TAG_FIELD_TYPE          CHAR(2),
    CHECK_CURR_TAG          CHAR(10),
    TAG_USE_LIST            CHAR(10),
    EXCEPTION_CODE          CHAR(10),
    TAG_USE_VALIDATION      CHAR(10),
    TAG_LABEL               CHAR(40),
    TAG_FIELD_FORMAT        CHAR(40),
    TAG_DESCRIPTION         VARCHAR(500),
    GPI_REQUIRED            CHAR(1),
    FK_SETUP_TAG_SERIAL_NUM INTEGER,
    MX_TAG                  VARCHAR(50),
    FIELD_USAGE             CHAR(1),
    TAG_GENERIC             VARCHAR(50),
    TAG_ORIG_MSG            VARCHAR(50),
    constraint IXU_SWI_003
        primary key (MESSAGE_TYPE, TAG, MESSAGE_SN, MSG_CATEGORY)
);

create unique index SWIFT_SETUP_DETAIL_IND1
    on SWIFT_SETUP_DETAIL (MESSAGE_TYPE, MSG_CATEGORY);

