create table SWIFT_320
(
    TRX_REFERENCE_NUMB CHAR(16),
    FK_ISSUE_UNIT      INTEGER,
    TMSTAMP            TIMESTAMP(6),
    FK_SWIFT_COUNTEDAT DATE,
    MSG_CONFIRM_DATE   DATE,
    MSG_SEND_TIME      TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PARTY_A_ROLE       CHAR(1),
    PRIORITY_CODE      CHAR(2),
    FIN_COPY           CHAR(3),
    TYPE_OF_OPERATION  CHAR(4),
    OPERATION_SCOPE    CHAR(4),
    TYPE_OF_EVENT      CHAR(4),
    INTEREST_DAY_COUNT CHAR(7),
    DEP_MATURITY_DATE  CHAR(8),
    NEXT_INT_DUE_DATE  CHAR(8),
    DEP_TRADE_DATE     CHAR(8),
    DEP_VALUE_DATE     CHAR(8),
    MSG_CONFIRM_BNKUSR CHAR(8),
    MSG_SEND_BNKUSR    CHAR(8),
    INTEREST_RATE      CHAR(12),
    SWIFT_CODE         CHAR(12),
    FK_SWMSG_PRFTREFNO CHAR(16),
    RELATED_REFERENCE  CHAR(16),
    CURRENCY_AMO       CHAR(18),
    CURRENCY_INT_AMO   CHAR(18),
    PARTY_B            CHAR(35),
    PARTY_A            CHAR(35),
    PARTY_A_DEL_AGENT  VARCHAR(200),
    PARTY_A_REC_AGENT  VARCHAR(200),
    PARTY_B_REC_AGENT  VARCHAR(200),
    SENDER_TO_RECEIVER VARCHAR(210),
    FLD_22C            CHAR(18) default ' '
);

create unique index IXU_SWI_025
    on SWIFT_320 (TRX_REFERENCE_NUMB);

