create table SYNDICATED_PARTICIPANTS
(
    FACILITY_ID          DECIMAL(10) not null,
    CUSTOMER_ID          INTEGER     not null,
    IS_LEADER            CHAR(1),
    CUSTOMER_PERCENTAGE  DECIMAL(7, 4),
    DEP_ACCOUNT_NUMBER   CHAR(40),
    DEP_ACCOUNT_SYSTEM   SMALLINT,
    CAPITAL_INITIAL_BAL  DECIMAL(15, 2),
    CAPITAL_CURRENT_BAL  DECIMAL(15, 2),
    CAPITAL_AMOUNT_RETRN DECIMAL(15, 2),
    INTEREST_TOTAL_PAID  DECIMAL(15, 2),
    INTEREST_TOTAL_OWED  DECIMAL(15, 2),
    COMM_TOTAL_PAID      DECIMAL(15, 2),
    COMM_TOTAL_OWED      DECIMAL(15, 2),
    FK_FT_METHOD_GH      CHAR(5),
    FK_FT_METHOD_GD      INTEGER,
    ENTRY_STATUS         CHAR(1),
    TRX_USER             CHAR(8),
    TRX_DATE             DATE,
    TRX_TIMESTAMP        TIMESTAMP(6),
    EXTERNAL_ACCOUNT     CHAR(37),
    constraint ISYNDICATED_PARTICIPANTS
        primary key (FACILITY_ID, CUSTOMER_ID)
);

create unique index MSYNDICATED_PARTICIPANTS_COMNT
    on SYNDICATED_PARTICIPANTS (FK_FT_METHOD_GH, FK_FT_METHOD_GD);

