create table TBL_FOR_RISK_REP
(
    COL_SYSTEM                   SMALLINT,
    ACCOUNT_CD                   SMALLINT,
    PRFT_SYSTEM                  SMALLINT,
    ACC_TYPE                     SMALLINT,
    LNS_INSTALL_COUNT            SMALLINT,
    LNS_INSTALL_FREQ             SMALLINT,
    LOAN_INSTALL_COUNT           SMALLINT,
    OVERDUE_CLASSIFICATION       SMALLINT,
    LOAN_REQ_INSTALL_SN          SMALLINT,
    LOAN_INSTALL_REMAIN          SMALLINT,
    COL_INTERNAL_SN              SMALLINT,
    FK_AGREEMENTAGR_YE           SMALLINT,
    INT_CODE                     INTEGER,
    INT_BASE_CODE                INTEGER,
    FK_GENERIC_DETASER           INTEGER,
    CKORY                        INTEGER,
    CRRAT                        INTEGER,
    CCODE                        INTEGER,
    FINSC                        INTEGER,
    ID_CURRENCY                  INTEGER,
    ID_PRODUCT                   INTEGER,
    CUST_GROUP                   INTEGER,
    CUST_ACTIVITY                INTEGER,
    CLOAN                        INTEGER,
    FK_AGREEMENTFK_UNI           INTEGER,
    FK_AGREEMENTAGR_ME           INTEGER,
    FK_AGREEMENTAGR_SN           INTEGER,
    AGREEMENT_CURRENCY           INTEGER,
    CRLIN_CODE                   INTEGER,
    PRFT_ACC_LMT_CURR            INTEGER,
    CIS_CATEGORY                 INTEGER,
    AGR_PRODUCT                  INTEGER,
    FIXED_INT_ID                 INTEGER,
    FLOATING_INT_ID              INTEGER,
    PENALTY_INT_ID               INTEGER,
    N128_INT_ID                  INTEGER,
    ACC_UNIT                     INTEGER,
    CUST_ID                      INTEGER,
    GROUP_MAIN                   INTEGER,
    FIXING                       DECIMAL(8, 4),
    INTEREST_RATE                DECIMAL(8, 4),
    SPREAD_RATE                  DECIMAL(8, 4),
    N128_RATE                    DECIMAL(8, 4),
    PENALTY_RATE                 DECIMAL(8, 4),
    N128                         DECIMAL(9, 6),
    KEY_COLLATERAL_SN            DECIMAL(10),
    LOAN_OVERDUE_DAYS            DECIMAL(10),
    LOAN_OVERDUE_MONTHS          DECIMAL(10, 2),
    LOAN_REGULATION_DAYS         DECIMAL(10),
    INT_BASE_PERC                DECIMAL(12, 6),
    ACC_SN                       DECIMAL(13),
    PROPERTY_AGREEMENT           DECIMAL(15, 2),
    PROPERTY_ACCOUNT             DECIMAL(15, 2),
    PROPERTY_AGREEMENT_EUR       DECIMAL(15, 2),
    PROPERTY_ACCOUNT_EUR         DECIMAL(15, 2),
    PROPERTY_AGREEMENT_VAL       DECIMAL(15, 2),
    PROPERTY_ACCOUNT_VAL         DECIMAL(15, 2),
    PROPERTY_AGREEMENT_VAL_EUR   DECIMAL(15, 2),
    PROPERTY_ACCOUNT_VAL_EUR     DECIMAL(15, 2),
    ACC_BALANCE_VS_PROPERTY_PERC DECIMAL(15, 4),
    NRM_CAPITAL                  DECIMAL(15, 2),
    NRM_CAPITAL_LC               DECIMAL(15, 2),
    OV_CAPITAL                   DECIMAL(15, 2),
    OV_CAPITAL_LC                DECIMAL(15, 2),
    LNS_FIRST_DRAWDOWN_AMN       DECIMAL(15, 2),
    ACC_COL_20205                DECIMAL(15, 2),
    ACC_COL_20206                DECIMAL(15, 2),
    ACC_COL_20013                DECIMAL(15, 2),
    ACC_COL_20001                DECIMAL(15, 2),
    ACC_COL_20002                DECIMAL(15, 2),
    ACC_COL_20003                DECIMAL(15, 2),
    ACC_COL_20011                DECIMAL(15, 2),
    ACC_COL_20012                DECIMAL(15, 2),
    ACC_COL_20014                DECIMAL(15, 2),
    ACC_COL_20015                DECIMAL(15, 2),
    ACC_COL_20016                DECIMAL(15, 2),
    ACC_COL_20017                DECIMAL(15, 2),
    ACC_COL_20018                DECIMAL(15, 2),
    ACC_COL_20019                DECIMAL(15, 2),
    ACC_COL_20004                DECIMAL(15, 2),
    ACC_COL_20005                DECIMAL(15, 2),
    ACC_COL_20006                DECIMAL(15, 2),
    ACC_COL_20007                DECIMAL(15, 2),
    ACC_COL_20008                DECIMAL(15, 2),
    ACC_COL_20009                DECIMAL(15, 2),
    ACC_COL_20010                DECIMAL(15, 2),
    ACC_COL_OTHER                DECIMAL(15, 2),
    ACC_COL_AGREEMENT            DECIMAL(15, 2),
    AGR_COL_20205                DECIMAL(15, 2),
    AGR_COL_20206                DECIMAL(15, 2),
    AGR_COL_20013                DECIMAL(15, 2),
    AGR_COL_20001                DECIMAL(15, 2),
    AGR_COL_20002                DECIMAL(15, 2),
    AGR_COL_20003                DECIMAL(15, 2),
    AGR_COL_20011                DECIMAL(15, 2),
    AGR_COL_20012                DECIMAL(15, 2),
    AGR_COL_20014                DECIMAL(15, 2),
    AGR_COL_20015                DECIMAL(15, 2),
    AGR_COL_20016                DECIMAL(15, 2),
    AGR_COL_20017                DECIMAL(15, 2),
    AGR_COL_20018                DECIMAL(15, 2),
    AGR_COL_20019                DECIMAL(15, 2),
    AGR_COL_20004                DECIMAL(15, 2),
    AGR_COL_20005                DECIMAL(15, 2),
    AGR_COL_20006                DECIMAL(15, 2),
    AGR_COL_20007                DECIMAL(15, 2),
    AGR_COL_20008                DECIMAL(15, 2),
    AGR_COL_20009                DECIMAL(15, 2),
    AGR_COL_20010                DECIMAL(15, 2),
    AGR_COL_OTHER                DECIMAL(15, 2),
    ACC_COL_TOTAL                DECIMAL(15, 2),
    AGR_COL_TOTAL                DECIMAL(15, 2),
    MONTH_0_1                    DECIMAL(15, 2),
    MONTH_1_3                    DECIMAL(15, 2),
    MONTH_4_12                   DECIMAL(15, 2),
    YEAR_1_5                     DECIMAL(15, 2),
    YEAR_5                       DECIMAL(15, 2),
    LNS_POSITIVE_AMN             DECIMAL(15, 2),
    LNS_POSITIVE_AMN_EUR         DECIMAL(15, 2),
    LNS_UNREALIZED               DECIMAL(15, 2),
    LNS_UNREALIZED_EUR           DECIMAL(15, 2),
    BALANCE                      DECIMAL(15, 2),
    OVERDUE_BALANCE              DECIMAL(15, 2),
    COLLATERAL                   DECIMAL(15, 2),
    LG_BALANCE                   DECIMAL(15, 2),
    EUR_BALANCE                  DECIMAL(15, 2),
    EUR_OVERDUE                  DECIMAL(15, 2),
    EUR_LG                       DECIMAL(15, 2),
    LG_LIMIT                     DECIMAL(15, 2),
    COL_EST_VALUE_AMN            DECIMAL(15, 2),
    EUR_COLLATERAL               DECIMAL(15, 2),
    DEP_BOOK_BAL                 DECIMAL(15, 2),
    EUR_DEP_BOOK_BAL             DECIMAL(15, 2),
    LG_COLLAT_20016              DECIMAL(15, 2),
    EUR_FOR_LG_G6                DECIMAL(15, 2),
    LG_DEFAULT_OVER              DECIMAL(15, 2),
    COLLATERAL_20005             DECIMAL(15, 2),
    COLLATERAL_PROPERTY          DECIMAL(15, 2),
    COLLATERAL_PROPERTY_BAL      DECIMAL(15, 2),
    LOAN_ACC_LIMIT               DECIMAL(15, 2),
    LOAN_OVER_LMT_FOR_NORM       DECIMAL(15, 2),
    LOAN_OVER_PERC               DECIMAL(15, 2),
    LOAN_INSTALL_FIXED_AMN       DECIMAL(15, 2),
    DBASE_EUR_BALANCE            DECIMAL(15, 2),
    DBASE_EUR_OVERDUE            DECIMAL(15, 2),
    PROPERTY_VAL_UPTO_75         DECIMAL(15, 2),
    PROPERTY_VAL_OVER_75         DECIMAL(15, 2),
    EUR_BALANCE_COLUMN_2         DECIMAL(15, 2),
    EUR_BALANCE_COLUMN_2A        DECIMAL(15, 2),
    COMMERCIAL_VAL_AMN           DECIMAL(15, 2),
    DEP_ENCROACH_TOLERANCE       DECIMAL(15, 2),
    DEP_TEMPORARY_EXCESS         DECIMAL(15, 2),
    DEP_ACCOUNT_LIMIT            DECIMAL(15, 2),
    DEP_NRM_BAL                  DECIMAL(15, 2),
    DEP_OVER_DUE_BAL             DECIMAL(15, 2),
    DEP_OVER_DUE_DAY             DECIMAL(15),
    AGREEMENT_LIMIT              DECIMAL(15, 2),
    AGREEMENT_UTILIZED           DECIMAL(15, 2),
    CRLINE_AMOUNT                DECIMAL(15, 2),
    CRLINE_UTILIZED              DECIMAL(15, 2),
    PRFT_ACC_LMT_AMN             DECIMAL(15, 2),
    AGR_TOTAL_COLLATERAL         DECIMAL(15, 2),
    AGR_TOTAL_COLLATERAL_EUR     DECIMAL(15, 2),
    ACC_TOTAL_COLLATERAL         DECIMAL(15, 2),
    ACC_TOTAL_COLLATERAL_EUR     DECIMAL(15, 2),
    ACC_BALANCE_VS_COLLAT_PERC   DECIMAL(15, 4),
    NRM_CAP_BAL                  DECIMAL(15, 2),
    NRM_EXP_BAL                  DECIMAL(15, 2),
    NRM_COM_BAL                  DECIMAL(15, 2),
    NRM_RL_INT_BAL               DECIMAL(15, 2),
    NRM_URL_INT_BAL              DECIMAL(15, 2),
    OV_CAP_BAL                   DECIMAL(15, 2),
    OV_EXP_BAL                   DECIMAL(15, 2),
    OV_COM_BAL                   DECIMAL(15, 2),
    OV_RL_NRM_INT_BAL            DECIMAL(15, 2),
    OV_URL_NRM_INT_BAL           DECIMAL(15, 2),
    OV_RL_PNL_INT_BAL            DECIMAL(15, 2),
    OV_URL_PNL_INT_BAL           DECIMAL(15, 2),
    PRFT_ACC_UTILIZED            DECIMAL(15, 2),
    PRFT_ACC_AVAILABLE           DECIMAL(15, 2),
    FINAL_PERC                   DECIMAL(15, 2),
    INT_BASE_PERC2               DECIMAL(15, 2),
    SPREAD                       DECIMAL(15, 2),
    ACC_EXPIRATION_DT            DATE,
    LNS_FIRST_DRAWDOWN_DT        DATE,
    ACC_OPEN_DT                  DATE,
    OV_EXP_DT                    DATE,
    CURR_TRX_DATE                DATE,
    DEP_DATE_SINCE_OVERDRN       DATE,
    LNS_DRAWDOWN_EXP_DT          DATE,
    AGR_SIGNING_DT               DATE,
    CRLINE_EXPIRY                DATE,
    PRFT_ACC_LMT_END_DT          DATE,
    CUR_FX_INT_EXP_DT            DATE,
    LNS_LMT_RENEWAL_STAMP        TIMESTAMP(6),
    CUST_TYPE                    CHAR(1),
    LOAN_STATUS                  CHAR(1),
    LG_OBLIGATION_STS            CHAR(1),
    ACC_MECHANISM                CHAR(1),
    FK_GENERIC_DETAFK            CHAR(5),
    LOAN_ROW_SETUP               CHAR(5),
    PREV_RATE                    CHAR(10),
    CURR_RATE                    CHAR(10),
    GROUP_AFM                    CHAR(20),
    CUST_AFM                     CHAR(20),
    GL_LNS_NORMAL                CHAR(21),
    GL_LG_ACCOUNT                CHAR(21),
    GL_LNS_WRITE_OFF             CHAR(21),
    GL_LNS_DEF_DELAY             CHAR(21),
    GL_LNS_OVERDUE               CHAR(21),
    GL_LNS_CREDIT                CHAR(21),
    ACCOUNT                      CHAR(40),
    AGREEMENT_NUMBER             CHAR(40),
    COUNTRY                      VARCHAR(20),
    INT_BASE_DESC                VARCHAR(40),
    INT_CODE_DESC                VARCHAR(40),
    CRRAT_DESC                   VARCHAR(40),
    CKORY_DESC                   VARCHAR(40)
);

create unique index IX_AGREEMENT_NUMBER
    on TBL_FOR_RISK_REP (AGREEMENT_NUMBER);

create unique index PKRSKREP
    on TBL_FOR_RISK_REP (ACCOUNT, ACCOUNT_CD, PRFT_SYSTEM, ACC_TYPE, ACC_SN, CUST_ID, ID_PRODUCT, ACC_UNIT,
                         KEY_COLLATERAL_SN, COL_SYSTEM, ID_CURRENCY, ACC_OPEN_DT, OV_EXP_DT, COLLATERAL,
                         COL_EST_VALUE_AMN, EUR_COLLATERAL, COL_INTERNAL_SN);

