create table TBL_FOR_REP_ST04_CS
(
    CUST_CD              SMALLINT,
    PRFT_SYSTEM          SMALLINT,
    ACC_TYPE             SMALLINT,
    ID_CURRENCY          INTEGER,
    CUST_ACTIVITY        INTEGER,
    ACC_UNIT             INTEGER,
    CUST_GROUP           INTEGER,
    CUST_ID              INTEGER,
    GROUP_CUST_ID        INTEGER,
    GROUP_MAIN           INTEGER,
    FIXING               DECIMAL(8, 4),
    ACC_SN               DECIMAL(13),
    LNS_POSITIVE_AMN     DECIMAL(15, 2),
    LNS_POSITIVE_AMN_EUR DECIMAL(15, 2),
    SUM_EUR_BALANCE      DECIMAL(15, 2),
    PRFT_ACC_LMT_AMN     DECIMAL(15, 2),
    SUM_EUR_LG           DECIMAL(15, 2),
    SUM_EUR_OVERDUE      DECIMAL(15, 2),
    LG_BALANCE           DECIMAL(15, 2),
    LNS_UNREALIZED_EUR   DECIMAL(15, 2),
    LNS_UNREALIZED       DECIMAL(15, 2),
    EUR_OVERDUE          DECIMAL(15, 2),
    OVERDUE_BALANCE      DECIMAL(15, 2),
    EUR_BALANCE          DECIMAL(15, 2),
    BALANCE              DECIMAL(15, 2),
    DEP_BOOK_BAL         DECIMAL(15, 2),
    EUR_DEP_BOOK_BAL     DECIMAL(15, 2),
    COLLATERAL           DECIMAL(15, 2),
    EUR_COLLATERAL       DECIMAL(15, 2),
    SUM_COLLATERAL       DECIMAL(15, 2),
    EUR_LG               DECIMAL(15, 2),
    OV_EXP_DT            DATE,
    CUST_TYPE            CHAR(1),
    PRINT_FLG            CHAR(1),
    CURR_RATE            CHAR(10),
    PREV_RATE            CHAR(10),
    GROUP_AFM            CHAR(20),
    CUST_AFM             CHAR(20),
    CUST_FIRSTNAME       CHAR(20),
    CUST_GROUP_NAME      CHAR(40),
    GROUP_SURNAME        CHAR(40),
    CUST_SURNAME         CHAR(70),
    GROUP_CUST_SURNAME   CHAR(70),
    ACCOUNT_NUMBER       CHAR(40)
);

create unique index IX_CUST_ID_CS
    on TBL_FOR_REP_ST04_CS (CUST_ID);

