create table TD_INT_SPRD_DTL
(
    ID_PRODUCT        INTEGER,
    ID_INTEREST       INTEGER,
    ID_CURRENCY       INTEGER,
    DEPOS_PAYOFF      CHAR(1),
    VALIDITY_DATE     DATE,
    INSTALLMENT_COUNT SMALLINT,
    INT_SPRD_PERC     DECIMAL(8, 4),
    INT_SPRD          DECIMAL(8, 4)
);

create unique index IXU_TD__005
    on TD_INT_SPRD_DTL (ID_PRODUCT, ID_INTEREST, ID_CURRENCY, DEPOS_PAYOFF, VALIDITY_DATE, INSTALLMENT_COUNT);

