create table TD_INT_ACCR_RESLTS
(
    TRX_UNIT           INTEGER,
    TRX_DATE           DATE,
    ACCOUNT_NUMBER     DECIMAL(11),
    DURATION_VALUE     SMALLINT,
    CR_INTEREST_RATE   DECIMAL(8, 4),
    PROD_CR_INTER_RATE DECIMAL(8, 4),
    STAMP_AMOUNT_TOTAL DECIMAL(15, 2),
    NOT_ACC_INTEREST   DECIMAL(15, 2),
    RENEWAL_BALANCE    DECIMAL(15, 2),
    GROSS_INTER_AMOUNT DECIMAL(15, 2),
    EXPIRY_DATE        DATE,
    NEXT_INSTAL_DATE   DATE,
    LAST_INT_CALC_DATE DATE,
    DURATION_UNIT      CHAR(1),
    FINAL_WHLD_TAX_FLG CHAR(1),
    DEPOSIT_TYPE       CHAR(1),
    RENEWAL_FLAG       CHAR(1),
    INTER_PAY_OPTIONS  CHAR(1),
    INTEREST_PAY_IND   CHAR(1)
);

create unique index IXU_TD__001
    on TD_INT_ACCR_RESLTS (TRX_UNIT, TRX_DATE, ACCOUNT_NUMBER);

