create table TD_VALEUR_BALANCE
(
    FK_TIME_DEPOS_RREN INTEGER,
    FK_TIME_DEPOS_RFK  DECIMAL(11),
    VALUE_DATE         DATE,
    CR_INTEREST_RATE   DECIMAL(8, 4),
    VALEUR_BALANCE     DECIMAL(15, 2)
);

create unique index IXU_TD__004
    on TD_VALEUR_BALANCE (FK_TIME_DEPOS_RREN, FK_TIME_DEPOS_RFK, VALUE_DATE);

