create table TEIRESIAS_CONFIRM
(
    LINE_SN          INTEGER,
    FILE_DATE        CHAR(8),
    CONFIRM_IND      CHAR(1),
    BANK_CODE        SMALLINT,
    FK_UNITCODE      SMALLINT,
    MME_LINE_SN      INTEGER,
    RECORD_COUNT     INTEGER,
    RETURN_COUNT     CHAR(3),
    CUST_FATHER_NAME CHAR(3),
    CUST_FIRST_NAME  CHAR(7),
    OTHER_ID_NO      CHAR(9),
    AFM_NO           CHAR(9),
    LOAN_PRIMARY_KEY CHAR(16),
    CUST_SURNAME     CHAR(24),
    REJ_COMMENT_1    CHAR(100),
    REJ_COMMENT_2    CHAR(100),
    REJ_COMMENT_3    CHAR(100),
    VALIDATION_CODE  CHAR(2),
    LOAN_INDICATOR   CHAR(5),
    LOAN_TYPE        CHAR(5),
    STOP_RECYCLE_IND CHAR(5),
    INDIV_INDICAT    CHAR(1)
);

create unique index IXU_TEI_000
    on TEIRESIAS_CONFIRM (LINE_SN, FILE_DATE, CONFIRM_IND);

