create table TEIRESIAS_PARMS
(
    PROGRAM_ID        CHAR(5) not null
        constraint IXU_LOA_102
            primary key,
    INCLUDE_PRFT_CD   SMALLINT,
    TRANSF_TO_DEF_DEL SMALLINT,
    CHK_OV_EXP_DT     SMALLINT,
    CHECK_BUCKET      SMALLINT,
    LST_TRX_END_MONTH SMALLINT,
    AMOUNT_TO         DECIMAL(3, 2),
    CHK_ACC_LMT_WHOLE SMALLINT,
    CHK_LOAN_IND      SMALLINT,
    CHK_CLOSING_EXTRA SMALLINT,
    EXCLUDE_LEGAL     SMALLINT,
    EXCL_DELAY_MONTH  SMALLINT,
    OPTIONAL_CUST_ADV SMALLINT
);

