create table TEK_MONEY_MARKET
(
    FK_TRX_PRODUCT     INTEGER,
    FK_DEAL_COL_BANK   INTEGER,
    FK_SOURCE_CURRENCY INTEGER,
    DEAL_NO            INTEGER,
    FK_CORRESP_CUST    INTEGER,
    DEP_ACC_NUMBER     DECIMAL(11),
    FK_CORRESP_DEP_ACC DECIMAL(11),
    SUM_TOT_BAL_RATE   DECIMAL(15, 2),
    CURR_AMOUNT        DECIMAL(15, 2),
    PREV_ACC_BALANCE   DECIMAL(15, 2),
    FIRST_NAME         CHAR(20),
    SURNAME            CHAR(70)
);

