create table TEK_TIME_DEPOSITS
(
    ACCOUNT_CD         SMALLINT,
    ID_PRODUCT         INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    BEN_CUSTID_5       INTEGER,
    BEN_CUSTID_4       INTEGER,
    BEN_CUSTID_3       INTEGER,
    BEN_CUSTID_2       INTEGER,
    DEP_ACC_NUMBER     DECIMAL(11),
    CURR_AMOUNT        DECIMAL(15, 2),
    PREV_ACC_BALANCE   DECIMAL(15, 2),
    SUM_TOT_BAL_RATE   DECIMAL(15, 2),
    BEN_FIRST_NAME_2   CHAR(20),
    BEN_FIRST_NAME_5   CHAR(20),
    FIRST_NAME         CHAR(20),
    BEN_FIRST_NAME_4   CHAR(20),
    BEN_FIRST_NAME_3   CHAR(20),
    ACCOUNT_NUMBER     CHAR(40),
    BEN_SURNAME_5      CHAR(70),
    BEN_SURNAME_4      CHAR(70),
    SURNAME            CHAR(70),
    BEN_SURNAME_3      CHAR(70),
    BEN_SURNAME_2      CHAR(70),
    DESCRIPTION        VARCHAR(40)
);

create unique index IX_DEP_ACC_NO_TD
    on TEK_TIME_DEPOSITS (DEP_ACC_NUMBER);

