create table TEKE_S_K_E
(
    ROW_NUM        DECIMAL(15, 2),
    CUST_ID        INTEGER,
    SURNAME        VARCHAR(70),
    FIRST_NAME     VARCHAR(100),
    CUST_TYPE      VARCHAR(1),
    FATHER_NAME    VARCHAR(20),
    MOTHER_NAME    VARCHAR(20),
    ID_NO          VARCHAR(20),
    DESCRIPTION    VARCHAR(40),
    AFM_NO         VARCHAR(20),
    DATE_OF_BIRTH  VARCHAR(10),
    AMKA           VARCHAR(11),
    ADDRESS1       VARCHAR(40),
    ADDRESS2       VARCHAR(40),
    ZIP_CODE       VARCHAR(10),
    CITY           VARCHAR(30),
    TELEPHONE      VARCHAR(15),
    DESCRIPTION_SE VARCHAR(40),
    REGEXP_STS_SK  VARCHAR(5),
    REGEXP_STS_SE  VARCHAR(5),
    REGEXP_STS_NUL VARCHAR(5)
);

