create table TEMP_CDP049F9
(
    RECONCILIATION_ID   SMALLINT,
    UNIT_CODE           SMALLINT,
    CHEQUE_NUMBER       INTEGER,
    CHEQUE_AMOUNT       DECIMAL(11, 2),
    PUBLICATION_DATE    DATE,
    TRANSACTION_DATE    DATE,
    DRAFT_IN_CHQ_FLAG   CHAR(1),
    DRAFT_AMOUNT        CHAR(25),
    DRAFT_NO            CHAR(25),
    SPECIAL_CHEQUE_CHAR VARCHAR(4),
    TRANSACTION_ID      VARCHAR(8),
    FILLER              VARCHAR(10),
    PURCHASE_DATE       VARCHAR(11),
    IBAN                VARCHAR(27)
);

