create table TEMPOR_DIAS_EXP
(
    CUST_DIGIT       SMALLINT,
    DEP_ACC_CD       SMALLINT,
    ENTRY_SER_NUM    SMALLINT,
    ACC_CURR_ID      INTEGER,
    BEL_UNIT_CODE    INTEGER,
    JUSTIFIC_ID      INTEGER,
    TRANS_SER_NUM    INTEGER,
    CUST_ID          INTEGER,
    ACCOUNT_NUMBER   DECIMAL(11),
    EXPENSE_AMN      DECIMAL(15, 2),
    TRX_DATE         DATE,
    ACCOUNT_CURRENCY CHAR(5),
    CUST_NAME        CHAR(20),
    DEP_ACC_NUMBER   CHAR(40),
    CUST_SURNAME     CHAR(70),
    JUSTIFICATION    VARCHAR(40)
);

