create table TEMP_COL_EXP_REP
(
    FK_UNITCODE         INTEGER,
    FK_COLLATERAL_TFK   INTEGER,
    FK_CUSTOMERCUST_ID  INTEGER,
    COLLATERAL_SN       DECIMAL(10),
    COL_EST_INSURANCE   DECIMAL(15, 2),
    CRL_UTILISED_AMOUNT DECIMAL(15, 2),
    ACC_LIMIT_AMNT      DECIMAL(15, 2),
    COL_EST_VALUE_AMN   DECIMAL(15, 2),
    CRLINE_AMOUNT       DECIMAL(15, 2),
    ACC_UTILISED_AMNT   DECIMAL(15, 2),
    BOOK_BALANCE        DECIMAL(15, 2),
    EXPIRY_DATE         DATE,
    COL_EXPIRY_DT       DATE,
    COLLATERAL_STATUS   CHAR(1),
    FIRST_NAME          CHAR(20),
    ACCOUNT_NUMBER      CHAR(40),
    SURNAME             CHAR(70)
);

