create table TEMP_TEIRESIA_FILE
(
    FILE_DATE              CHAR(8),
    LINE_SN                INTEGER,
    INSTALL_FREQ           SMALLINT,
    DELAY_MONTH_COUNT      SMALLINT,
    BANK_CODE              SMALLINT,
    INSTALL_COUNT          SMALLINT,
    FK_UNITCODE            INTEGER,
    RECORD_COUNT           INTEGER,
    WHOLE_BALANCE          DECIMAL(15, 2),
    NORMAL_BALANCE         DECIMAL(15, 2),
    LOAN_REQUEST_AMNT      DECIMAL(15, 2),
    OVERDUE_BALANCE        DECIMAL(15, 2),
    AMOUNT_COUNT           DECIMAL(15, 2),
    ACC_LIMIT_AMN          DECIMAL(15, 2),
    TOT_DRAWDOWN_AMT       DECIMAL(15, 2),
    NEGATIVE_BALANCE       DECIMAL(15, 2),
    OPEN_INDICATOR         CHAR(1),
    TEIRESIAS_IND          CHAR(1),
    CUSTOMER_INDICATOR     CHAR(1),
    LOAN_TYPE              CHAR(1),
    CUST_SEX               CHAR(1),
    LOAN_INDICATOR         CHAR(1),
    CUST_FATHER_NAME       CHAR(3),
    CUST_ADDRESS_NO        CHAR(4),
    CUST_ZIP_CODE          CHAR(5),
    ACC_OPEN_DT            CHAR(8),
    OPEN_IND_TRX_DATE      CHAR(8),
    LOAN_IND_TRX_DATE      CHAR(8),
    LAST_TRX_DT            CHAR(8),
    TEIRESIAS_DATE         CHAR(8),
    CUST_ID_ISSUE_DATE     CHAR(8),
    AFM_NO                 CHAR(9),
    CUST_ID_NO             CHAR(9),
    LOAN_PRIMARY_KEY       CHAR(16),
    CUST_ADDRESS_1         CHAR(20),
    CUST_FIRST_NAME        CHAR(20),
    CUST_SURNAME           CHAR(24),
    OLD_ACCT_NUM           CHAR(26),
    CUST_CITY              CHAR(30),
    VALIDATION_CODE        CHAR(2),
    CLASSIFICATION_PEE     CHAR(2),
    ADJ_TYPE               CHAR(1),
    INSTITUTIONAL_FRMWORK  CHAR(1),
    ASSOCIATED_ADJ_IND     CHAR(1),
    ASSOCIATED_ADJ_CODE    CHAR(2),
    ADJ_STATUS             CHAR(1),
    ADJ_INDICATOR          CHAR(1),
    MAX_ADJ_DELAY          CHAR(1),
    GRACE_PERIOD_DUR       CHAR(3),
    GRACE_PERIOD_EXP_DT    CHAR(8),
    INT_GRACE_PERIOD       CHAR(1),
    ADJ_DT                 CHAR(8),
    DEBT_FORG_IND          CHAR(1),
    DEBT_FORG_TYPE         CHAR(1),
    DEBT_FORG_DT           CHAR(8),
    NEW_ADJ_CODE           CHAR(16),
    ADJ_REF_DT             CHAR(8),
    OTHER_DRAWDOWN_CHANNEL CHAR(3),
    LOAN_TYPE_INDV         CHAR(1)
);

create unique index IXN_TEIR_004
    on TEMP_TEIRESIA_FILE (FILE_DATE, LOAN_PRIMARY_KEY);

create unique index IXU_TEM_011
    on TEMP_TEIRESIA_FILE (FILE_DATE, LINE_SN);

