create table TEMP_FX_FT_DAY
(
    TUN_INTERNAL_SN    SMALLINT,
    TRX_UNIT           INTEGER,
    ORG_TRX_UNIT       INTEGER,
    TARGET_CURRENCY    INTEGER,
    SOURCE_CURRENCY    INTEGER,
    TRX_CODE           INTEGER,
    TRX_CUSTOMER_CODE  INTEGER,
    CONTRACT_REF_NO    INTEGER,
    OUTGOING_ORDER_NUM INTEGER,
    TRX_SN             INTEGER,
    SOURCE_U_USER_TOTA DECIMAL(15, 2),
    TARGET_U_USER_TOTA DECIMAL(15, 2),
    AVAILABILITY_DATE  DATE,
    TRX_DATE           DATE,
    CHEQUE_ISSUE_DATE1 DATE,
    TRANSACTION_STATUS CHAR(1),
    TRX_USR            CHAR(8)
);

