create table TEMP_CPD049F9
(
    RECONCILIATION_ID   SMALLINT,
    REJECTION_ID        SMALLINT,
    UNIT_CODE           SMALLINT,
    CHEQUE_NUMBER       INTEGER,
    CHEQUE_AMOUNT       DECIMAL(11, 2),
    TRANSACTION_DATE    DATE,
    PUBLICATION_DATE    DATE,
    SPECIAL_CHEQUE_CHAR VARCHAR(4),
    TRANSACTION_ID      VARCHAR(8),
    FILLER              VARCHAR(10),
    PURCHASE_DATE       VARCHAR(11),
    IBAN                VARCHAR(27)
);

