create table TEMP_POS_ENT2BEUR
(
    LINE             SMALLINT,
    VALUE_TYPE       SMALLINT,
    CURRENCY         INTEGER,
    FIX_RATE         DECIMAL(10, 6),
    NON_CUST_BUY_FC  DECIMAL(15, 2),
    NON_CUST_BUY_DC  DECIMAL(15, 2),
    NON_CUST_SELL_FC DECIMAL(15, 2),
    NON_CUST_SELL_DC DECIMAL(15, 2),
    CUST_BUY_FC      DECIMAL(15, 2),
    CUST_BUY_DC      DECIMAL(15, 2),
    CUST_SELL_FC     DECIMAL(15, 2),
    CUST_SELL_DC     DECIMAL(15, 2),
    TOTAL_BUY_DC     DECIMAL(15, 2),
    TOTAL_SELL_DC    DECIMAL(15, 2),
    IN_GR_SELL_DC    DECIMAL(15, 2),
    IN_GR_SELL_FC    DECIMAL(15, 2),
    IN_GR_BUY_DC     DECIMAL(15, 2),
    IN_GR_BUY_FC     DECIMAL(15, 2),
    IN_SELL_DC       DECIMAL(15, 2),
    IN_SELL_FC       DECIMAL(15, 2),
    IN_BUY_DC        DECIMAL(15, 2),
    IN_BUY_FC        DECIMAL(15, 2),
    TRX_DATE         DATE,
    BANK_CODE        VARCHAR(5),
    CURRENCY_SHORT   VARCHAR(5)
);

