create table TEMP_DEMAND_EXTRAIT
(
    ACCOUNT_NUMBER       DECIMAL(11) not null,
    PENDING_FLAG         CHAR(1),
    ACCOUNT_UNIT         INTEGER,
    ACCOUNT_CURRENCY     INTEGER,
    ACCOUNT_PRODUCT      INTEGER,
    CHEQUE_NUMBER        DECIMAL(10),
    CUSTOMER_NUMBER      INTEGER,
    TRANSFERED_FLG       CHAR(1),
    REVERSE_FLAG         CHAR(1),
    REVERSED_TRX_FLAG    CHAR(1),
    ID_TRANSACT          INTEGER,
    ID_JUSTIFIC          INTEGER,
    AVAILABILITY_DATE    DATE,
    VALUE_DATE           DATE,
    DEBIT_CREDIT_FLAG    CHAR(1),
    ENTRY_AMOUNT         DECIMAL(15, 2),
    ENTRY_COMMENTS       VARCHAR(40),
    CHEQUE_CD            SMALLINT,
    SN                   INTEGER     not null,
    TRX_UNIT             INTEGER,
    TRX_DATE             DATE,
    TRX_USR              CHAR(8),
    TRX_SN               INTEGER,
    OLD_PREV_ACC_BALANCE DECIMAL(15, 2),
    NEW_PREV_ACC_BALANCE DECIMAL(15, 2),
    OLD_TRANS_SER_NUM    INTEGER     not null,
    NEW_TRANS_SER_NUM    INTEGER,
    ENTRY_SER_NUM        SMALLINT,
    NOT_PRINTED_FLG      CHAR(1),
    COMMENTS1            VARCHAR(40),
    COMMENTS2            VARCHAR(40),
    COMMENTS3            VARCHAR(40),
    COMMENTS4            VARCHAR(40),
    COMMENTS5            VARCHAR(40),
    COMMENTS6            VARCHAR(40),
    COMMENTS7            VARCHAR(40),
    COMMENTS8            VARCHAR(40),
    COMMENTS9            VARCHAR(40),
    COMMENTS10           VARCHAR(40),
    COMMENTS11           VARCHAR(40),
    COMMENTS12           VARCHAR(40),
    COMMENTS13           VARCHAR(40),
    COMMENTS14           VARCHAR(40),
    COMMENTS15           VARCHAR(40),
    COMMENTS16           VARCHAR(40),
    COMMENTS17           VARCHAR(40),
    TIMESTAMP            TIMESTAMP(6),
    TUN_INTERNAL_SN      SMALLINT,
    I_TRX_DATE           DATE,
    I_TRX_UNIT           INTEGER,
    I_TRX_USR            CHAR(8),
    I_TRX_SN             INTEGER,
    constraint IXU_DEP_104
        primary key (ACCOUNT_NUMBER, SN, OLD_TRANS_SER_NUM)
);

create unique index IXU_DEP_104
    on TEMP_DEMAND_EXTRAIT (OLD_TRANS_SER_NUM, SN, ACCOUNT_NUMBER);

