create table TEMP_SWIFT_ALLNCE_BICS
(
    SWIFT_CONN_FLAG CHAR(1),
    PREFIX          CHAR(3),
    BIC             CHAR(11),
    VALUE_ADDED_1   CHAR(12),
    LOCATION        CHAR(35),
    ADDRESS_2       VARCHAR(35),
    VALUE_ADDED_2   VARCHAR(35),
    CITY            VARCHAR(35),
    ADDRESS_3       VARCHAR(35),
    ADDRESS         VARCHAR(35),
    POB             VARCHAR(35),
    SUB_INFOR       VARCHAR(52),
    BANK_DEPT       VARCHAR(70),
    COUNTRY         VARCHAR(70),
    COUNTRY_2       VARCHAR(77),
    ZIP_CODE_TOWN   VARCHAR(105),
    BANK_DESCR      VARCHAR(105),
    EXTRA_ADDR_INFO VARCHAR(105)
);

