create table TEMP_DAILY_SPREAD
(
    PRFT_SYSTEM      SMALLINT,
    DIFF_DAYS        SMALLINT,
    CURRENCY_ID      INTEGER,
    UNIT_CODE        INTEGER,
    LNS_RATE         DECIMAL(12, 6),
    DP_RATE          DECIMAL(12, 6),
    DEP_ACCRUALS     DECIMAL(15, 2),
    LNS_ACCRUALS     DECIMAL(15, 2),
    EUR_DEP_ACCRUALS DECIMAL(15, 2),
    LNS_BAL_DC_MULT  DECIMAL(15, 2),
    LNS_BAL_FC_MULT  DECIMAL(15, 2),
    DP_BAL_DC_MULT   DECIMAL(15, 2),
    DP_BAL_FC_MULT   DECIMAL(15, 2),
    LNS_BAL_DC       DECIMAL(15, 2),
    LNS_BAL_FC       DECIMAL(15, 2),
    DP_BALANCE_DC    DECIMAL(15, 2),
    DP_BALANCE_FC    DECIMAL(15, 2),
    EUR_LNS_ACCRUALS DECIMAL(15, 2),
    TRX_DATE         DATE,
    CURR_DESC        CHAR(5),
    CNTR_GL_ACC      CHAR(21)
);

