create table TEMP_TRANSFER
(
    SERIAL_NUMBER    INTEGER not null,
    OLD_UNIT         INTEGER,
    NEW_UNIT         INTEGER,
    ACCOUNT_NUMBER   DECIMAL(11),
    TP_IDENTIFIER    DECIMAL(10),
    TP_SO_IDENTIFIER DECIMAL(10),
    PROCESSED_FLAG   CHAR(1)
);

