create table TEMP_HISTORY_FD_EXTRAIT
(
    NEW_PREV_ACC_BALANCE DECIMAL(15, 2) not null,
    NEW_TRANS_SER_NUM    INTEGER        not null,
    SN                   INTEGER        not null,
    ACCOUNT_NUMBER       DECIMAL(11)    not null,
    TRX_DATE             DATE           not null,
    OLD_TRANS_SER_NUM    INTEGER        not null,
    ENTRY_SER_NUM        SMALLINT       not null,
    TRX_UNIT             INTEGER,
    TRX_USR              CHAR(8),
    TRX_SN               INTEGER,
    C_DIGIT              SMALLINT,
    ACCOUNT_UNIT         INTEGER,
    ACCOUNT_CURRENCY     INTEGER,
    ACCOUNT_PRODUCT      INTEGER,
    CHEQUE_NUMBER        DECIMAL(10),
    CUSTOMER_NUMBER      INTEGER,
    TRANSFERED_FLG       CHAR(1),
    REVERSE_FLAG         CHAR(1),
    ID_TRANSACT          INTEGER,
    ID_JUSTIFIC          INTEGER,
    AVAILABILITY_DATE    DATE,
    VALUE_DATE           DATE,
    DEBIT_CREDIT_FLAG    CHAR(1),
    ENTRY_AMOUNT         DECIMAL(15, 2),
    PARTICIP_BAL_FLAG    SMALLINT,
    OLD_PREV_ACC_BALANCE DECIMAL(15, 2),
    ENTRY_COMMENTS       VARCHAR(40),
    PRINTED_LINE_FLAG    CHAR(1),
    CHEQUE_CD            SMALLINT,
    PENDING_FLAG         CHAR(1),
    PROCESSED_FLG        CHAR(1),
    NOT_PRINTED_FLG      CHAR(1),
    CHECK_FLG            CHAR(1),
    COMMENTS1            VARCHAR(40),
    COMMENTS2            VARCHAR(40),
    COMMENTS3            VARCHAR(40),
    COMMENTS4            VARCHAR(40),
    COMMENTS5            VARCHAR(40),
    COMMENTS6            VARCHAR(40),
    COMMENTS7            VARCHAR(40),
    COMMENTS8            VARCHAR(40),
    COMMENTS9            VARCHAR(40),
    COMMENTS10           VARCHAR(40),
    COMMENTS11           VARCHAR(40),
    COMMENTS12           VARCHAR(40),
    COMMENTS13           VARCHAR(40),
    COMMENTS14           VARCHAR(40),
    COMMENTS15           VARCHAR(40),
    COMMENTS16           VARCHAR(40),
    COMMENTS17           VARCHAR(40),
    TIMESTAMP            TIMESTAMP(6),
    I_TRX_DATE           DATE,
    I_TRX_UNIT           INTEGER,
    I_TRX_USR            CHAR(8),
    I_TRX_SN             INTEGER,
    constraint IXU_DEP_077
        primary key (OLD_TRANS_SER_NUM, ACCOUNT_NUMBER, SN)
);

