create table TEMP_DAILY_SPREAD3
(
    PRFT_SYSTEM  SMALLINT,
    REP_DAYS     SMALLINT,
    UNIT_CODE    INTEGER,
    CURRENCY_ID  INTEGER,
    POS_RATE     DECIMAL(12, 6),
    NEG_RATE     DECIMAL(12, 6),
    POS_BAL      DECIMAL(15, 2),
    POS_ACCRUALS DECIMAL(15, 2),
    NEG_ACCRUALS DECIMAL(15, 2),
    NEG_BAL      DECIMAL(15, 2),
    TRX_DATE     DATE,
    CURR_DESC    CHAR(5)
);

