create table TEMP_BOP
(
    TRX_INTERNAL_SN    SMALLINT,
    TRX_UNIT           INTEGER,
    TRX_USR_SN         INTEGER,
    TRX_AMOUNT         DECIMAL(15, 2),
    EQUIVELANT         DECIMAL(15, 2),
    TRX_DATE           DATE,
    TMSTAMP            TIMESTAMP(6),
    PROCESS_FLG        CHAR(1),
    CR_DR              CHAR(2),
    TRX_CURRENCY       CHAR(3),
    NON_RES_COUNTRY_ID CHAR(3),
    INDIVIDUAL         CHAR(4),
    TRX_CATEGORY       CHAR(5),
    CARD_IND           CHAR(5),
    TRX_USER           CHAR(8),
    STATUTORY_TYPE     CHAR(10),
    BOPBC              CHAR(10),
    CRGRP              CHAR(10),
    DRGRP              CHAR(10),
    BOPEC              CHAR(10),
    BOPFC              CHAR(10),
    ISIN_CODE          CHAR(15),
    REF_NO             CHAR(20),
    NORMAL_TUN         CHAR(25),
    CORPORATE_REG_NO   CHAR(30),
    LOAN_REF_NO        CHAR(30),
    CORPORATE_PHONE    CHAR(35),
    CORPORATE_ADDRESS  CHAR(70),
    CBG_TRX3           CHAR(100),
    CBG_TRX2           CHAR(100),
    CBG_TRX1           CHAR(100),
    COPRORATE_NAME     CHAR(150)
);

