create table TEMP_COLLABORATION_BANK
(
    FK_GENERIC_DETASER INTEGER,
    BANK_ID            INTEGER,
    FK_DISTR_CHANNEID  INTEGER,
    WEIGHT_6           DECIMAL(15),
    WEIGHT_7           DECIMAL(15),
    WEIGHT_8           DECIMAL(15),
    WEIGHT_9           DECIMAL(15),
    MODULUS            DECIMAL(15),
    WEIGHT_5           DECIMAL(15),
    WEIGHT_4           DECIMAL(15),
    WEIGHT_3           DECIMAL(15),
    WEIGHT_2           DECIMAL(15),
    WEIGHT_1           DECIMAL(15),
    WEIGHT_10          DECIMAL(15),
    TMSTAMP            DATE,
    ACC_CD_ALG_USED    CHAR(1),
    CHQ_CD_ALG_USED    CHAR(1),
    COUNTRY_CODE       CHAR(1),
    NORMAL_CHEQUES     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    ACV                CHAR(1),
    DIASCHEQ_BUYERONLY CHAR(1),
    OUR_BANK_FLG       CHAR(1),
    POSTAL_DRAFT       CHAR(1),
    CNTRY_ISO_CODE     CHAR(2),
    ACH_BANK_CODE      CHAR(3),
    MCH_BANK_CODE      CHAR(3),
    DIAS_BANK_CODE     CHAR(3),
    ATM_DIAS_CODE      CHAR(3),
    FK_GENERIC_DETAFK  CHAR(5),
    BBAN_PRINT_FORMAT  CHAR(37),
    BBAN_ACCOUNT       CHAR(37),
    BBAN_UNIT          CHAR(37),
    BBAN_FOR_CD        CHAR(37),
    SWIFT_ADDRESS      VARCHAR(40),
    ENTRY_COMMENTS     VARCHAR(40),
    BANK_NAME          VARCHAR(40)
);

