create table TERM2
(
    C_DIGIT            SMALLINT,
    ACCOUNT_CD         SMALLINT,
    FKGD_CATEGORY      INTEGER,
    FK_GENERIC_DETASER INTEGER,
    MOVEMENT_CURRENCY  INTEGER,
    PRODUCT_ID         INTEGER,
    CUST_ID            INTEGER,
    DEP_ACC_NUMBER     DECIMAL(11),
    CUST_TYPE          CHAR(1),
    CR_INT_GL_ACC      CHAR(21),
    GL_ACCRUAL_ACC     CHAR(21),
    CR_CNTR_GL_ACC     CHAR(21),
    CR_INT_ACCR_GL_ACC CHAR(21),
    FK_GLG_ACCOUNTACCO CHAR(21),
    DR_CNTR_GL_ACC     CHAR(21),
    DR_INT_ACCR_GL_ACC CHAR(21),
    GL_NETWORK_ACC     CHAR(21),
    DR_INT_GL_ACC      CHAR(21),
    ACCOUNT_NUMBER     CHAR(40)
);

