create table TF_PAYMENT_SCHED
(
    FK_TFSET_TFDOCTF CHAR(40) not null,
    FK_TFSET_TFDOCLS SMALLINT not null,
    FK_TFSET_SETSN   SMALLINT not null,
    PAYMENT_SN       SMALLINT not null,
    PAYMENT_ACC_PRFS SMALLINT,
    FK_FSC_REFNO     INTEGER,
    PAYMENT_AMOUNT   DECIMAL(15, 2),
    PAYMENT_DATE     DATE,
    PAYMENT_STATUS   CHAR(1),
    PAYMENT_LC_ACC   CHAR(40),
    PAYMENT_ACC      CHAR(40),
    PAYMENT_TUN      VARCHAR(40),
    COMMENTS         VARCHAR(70),
    constraint IXU_FX_057
        primary key (FK_TFSET_TFDOCTF, FK_TFSET_TFDOCLS, FK_TFSET_SETSN, PAYMENT_SN)
);

