create table TF_SETTLEMENT
(
    FK_TFDOC_FKTFNUM CHAR(40) not null,
    FK_TFDOC_LOTSN   SMALLINT not null,
    SETTLEMENT_SN    SMALLINT not null,
    PAYMENT_MODE     SMALLINT,
    FK_REPR_IDCURR   INTEGER,
    FK_SETTL_IDCURR  INTEGER,
    FK_GDET_SNUM_IC  INTEGER,
    FK_JUST_IDJUST   INTEGER,
    FK_CUST_CUSTID   INTEGER,
    REPRES_AMN       DECIMAL(15, 2),
    SETTLEMENT_DATE  DATE,
    SETTLEMENT_STS   CHAR(1),
    FK_GDET_GHEAD_IC CHAR(5),
    CHARGES_ACCOUNT  CHAR(40),
    COMMENTS         VARCHAR(70),
    constraint IXU_FX_047
        primary key (FK_TFDOC_FKTFNUM, FK_TFDOC_LOTSN, SETTLEMENT_SN)
);

