create table TF_TRX_RECORDING
(
    TUN_UNIT               INTEGER  not null,
    TUN_DATE               DATE     not null,
    TUN_TRN_SN             INTEGER  not null,
    TUN_USER               CHAR(8)  not null,
    TUN_INTERNAL_SN        SMALLINT not null,
    O_SETTL_PAY_MODE       SMALLINT,
    P_SETTL_PAY_MODE       SMALLINT,
    P_LC_TRANSMISSION      SMALLINT,
    O_LC_TRANSMISSION      SMALLINT,
    P_LC_TYPE              SMALLINT,
    O_LC_TYPE              SMALLINT,
    P_SETTLEMENT_MODE      SMALLINT,
    O_SETTLEMENT_MODE      SMALLINT,
    TF_ACC_CD              SMALLINT,
    P_PAYM_ACC_PRFS        SMALLINT,
    O_PAYM_ACC_PRFS        SMALLINT,
    SETTLEMENT_SN          SMALLINT,
    LOT_SN                 SMALLINT,
    PAYMENT_SN             SMALLINT,
    O_LANGUAGE             INTEGER,
    P_LANGUAGE             INTEGER,
    O_SETTL_JUSTIFIC       INTEGER,
    P_SETTL_JUSTIFIC       INTEGER,
    O_SETTL_REP_AMNC       INTEGER,
    P_SETTL_REP_AMNC       INTEGER,
    O_SETTL_INCO           INTEGER,
    P_SETTL_INCO           INTEGER,
    O_SETTL_CURR_ID        INTEGER,
    P_SETTL_CURR_ID        INTEGER,
    O_AMN_TYPE             INTEGER,
    P_AMN_TYPE             INTEGER,
    O_AMN_CURR_ID          INTEGER,
    P_AMN_CURR_ID          INTEGER,
    TRX_CODE               INTEGER,
    U_USERTOT_CURRID       INTEGER,
    I_TUN_UNIT             INTEGER,
    O_JUSTIFIC             INTEGER,
    P_JUSTIFIC             INTEGER,
    O_MONIT_UNIT           INTEGER,
    P_MONIT_UNIT           INTEGER,
    O_COUNTRY              INTEGER,
    P_COUNTRY              INTEGER,
    O_CURRENCY             INTEGER,
    P_CURRENCY             INTEGER,
    O_MOVING_CURRENCY      INTEGER,
    P_MOVING_CURRENCY      INTEGER,
    O_CHARGING_CURRENCY    INTEGER,
    P_CHARGING_CURRENCY    INTEGER,
    O_CB_PROD_CODE         INTEGER,
    P_CB_PROD_CODE         INTEGER,
    TF_EXTRAIT_SN          INTEGER,
    O_PRINCIP_CUST         INTEGER,
    P_PRINCIP_CUST         INTEGER,
    O_BENEF_CUST           INTEGER,
    P_BENEF_CUST           INTEGER,
    O_CORRESP_CUST         INTEGER,
    P_CORRESP_CUST         INTEGER,
    O_INVOICE_PERC         DECIMAL(7, 4),
    P_INVOICE_PERC         DECIMAL(7, 4),
    O_DOC_TEMPLATE         INTEGER,
    P_DOC_TEMPLATE         INTEGER,
    O_SETTL_REP            INTEGER,
    P_SETTL_REP            INTEGER,
    O_PAYM_FSC_REFNO       INTEGER,
    P_PAYM_FSC_REFNO       INTEGER,
    O_COM_DISCOUNT         DECIMAL(7, 4),
    P_COM_DISCOUNT         DECIMAL(7, 4),
    FIN_SN                 INTEGER,
    FIN_TRX_USR_SN         INTEGER,
    I_TUN_TRN_SN           INTEGER,
    P_LCL_HIST_CNT         DECIMAL(10),
    O_LCL_HIST_CNT         DECIMAL(10),
    U_USERTOT_AMN          DECIMAL(15, 2),
    P_AMN_AMOUNT           DECIMAL(15, 2),
    OVERDUE_COMM_AMN       DECIMAL(15, 2),
    O_TRADE_AMOUNT         DECIMAL(15, 2),
    P_TRADE_AMOUNT         DECIMAL(15, 2),
    O_LC_FST_ISS_AMN       DECIMAL(15, 2),
    P_LC_FST_ISS_AMN       DECIMAL(15, 2),
    O_LC_TOT_ISS_AMN       DECIMAL(15, 2),
    P_LC_TOT_ISS_AMN       DECIMAL(15, 2),
    O_TF_UT_AMN            DECIMAL(15, 2),
    P_TF_UT_AMN            DECIMAL(15, 2),
    O_LCL_LIM_AMN          DECIMAL(15, 2),
    P_LCL_LIM_AMN          DECIMAL(15, 2),
    O_LCL_LC_UT_LIM        DECIMAL(15, 2),
    P_LCL_LC_UT_LIM        DECIMAL(15, 2),
    O_SETTL_REP_AMN        DECIMAL(15, 2),
    P_SETTL_REP_AMN        DECIMAL(15, 2),
    O_PAYM_AMOUNT          DECIMAL(15, 2),
    P_PAYM_AMOUNT          DECIMAL(15, 2),
    O_AMN_AMOUNT           DECIMAL(15, 2),
    COMMISSION_AMN         DECIMAL(15, 2),
    I_TUN_DATE             DATE,
    TF_OPENING_DT          DATE,
    TF_ISSUE_DT            DATE,
    TF_CONFIRM_DT          DATE,
    O_EXPIRY_DT            DATE,
    P_EXPIRY_DT            DATE,
    O_LC_ISSUE_DATE        DATE,
    P_LC_ISSUE_DATE        DATE,
    O_SETTL_DATE           DATE,
    P_SETTL_DATE           DATE,
    O_PAYM_DATE            DATE,
    P_PAYM_DATE            DATE,
    FIN_TRX_TMSTAMP        TIMESTAMP(6),
    TMPSTAMP               TIMESTAMP(6),
    O_IRREVOCABLE_FLG      CHAR(1),
    P_CONFIRM_FLG          CHAR(1),
    O_PARTIAL_SHIPMENT_FLG CHAR(1),
    P_PARTIAL_SHIPMENT_FLG CHAR(1),
    O_TRANSHIPMENT_FLG     CHAR(1),
    P_TRANSHIPMENT_FLG     CHAR(1),
    O_ASSIGN_OF_PROCEED    CHAR(1),
    P_ASSIGN_OF_PROCEED    CHAR(1),
    O_RED_CLAUSE           CHAR(1),
    P_RED_CLAUSE           CHAR(1),
    O_REVOLVING_IND        CHAR(1),
    P_REVOLVING_IND        CHAR(1),
    O_REPR_RESIDENT        CHAR(1),
    P_REPR_RESIDENT        CHAR(1),
    O_LC_STATUS            CHAR(1),
    P_LC_STATUS            CHAR(1),
    O_SETTL_STS            CHAR(1),
    P_SETTL_STS            CHAR(1),
    P_IRREVOCABLE_FLG      CHAR(1),
    O_CONFIRM_FLG          CHAR(1),
    O_PAYM_STATUS          CHAR(1),
    P_PAYM_STATUS          CHAR(1),
    TRX_STATUS             CHAR(1),
    TRN_TYPE               CHAR(1),
    REVERSAL_FLG           CHAR(1),
    I_TUN_USER             CHAR(8),
    O_REPR_ZIP_CODE        CHAR(10),
    P_REPR_ZIP_CODE        CHAR(10),
    O_ISS_BANK             CHAR(11),
    P_ISS_BANK             CHAR(11),
    O_ADV_BANK             CHAR(11),
    O_NEGOT_BANK           CHAR(11),
    P_NEGOT_BANK           CHAR(11),
    O_CONFIRM_BANK         CHAR(11),
    P_CONFIRM_BANK         CHAR(11),
    P_ADV_BANK             CHAR(11),
    O_REPR_TEL             CHAR(15),
    P_REPR_TEL             CHAR(15),
    O_EXPIRY_PLACE         CHAR(20),
    P_EXPIRY_PLACE         CHAR(20),
    P_REPR_COUNTRY         CHAR(20),
    P_REPR_REGION          CHAR(20),
    O_REPR_COUNTRY         CHAR(20),
    O_REPR_REGION          CHAR(20),
    TF_ACC_NUMBER          CHAR(40),
    P_PAYM_LC_ACC          CHAR(40),
    P_REF_NO               CHAR(40),
    O_PRINCIP_ADDRESS      CHAR(40),
    P_PRINCIP_ADDRESS      CHAR(40),
    P_BENEF_NAME           CHAR(40),
    O_BENEF_ADDRESS        CHAR(40),
    P_BENEF_ADDRESS        CHAR(40),
    O_PRINCIP_ACCOUNT      CHAR(40),
    P_PRINCIP_ACCOUNT      CHAR(40),
    O_BENEF_ACCOUNT        CHAR(40),
    P_BENEF_ACCOUNT        CHAR(40),
    O_CORRESP_ACC          CHAR(40),
    P_CORRESP_ACC          CHAR(40),
    O_AGREEMENT            CHAR(40),
    P_AGREEMENT            CHAR(40),
    O_TRANSFER_LC          CHAR(40),
    P_TRANSFER_LC          CHAR(40),
    O_REPR_ADDRESS_1       CHAR(40),
    P_REPR_ADDRESS_1       CHAR(40),
    O_REPR_ADDRESS_2       CHAR(40),
    P_REPR_ADDRESS_2       CHAR(40),
    O_SETTL_CHRG_ACC       CHAR(40),
    P_SETTL_CHRG_ACC       CHAR(40),
    O_PAYM_ACC             CHAR(40),
    P_PAYM_ACC             CHAR(40),
    O_PAYM_LC_ACC          CHAR(40),
    O_REF_NO               CHAR(40),
    O_REPR_NAME            CHAR(70),
    P_REPR_NAME            CHAR(70),
    P_PAYM_COMMENTS        CHAR(70),
    P_SETTL_COMMENTS       CHAR(70),
    O_PAYM_COMMENTS        CHAR(70),
    O_SETTL_COMMENTS       CHAR(70),
    O_PRINCIP_NAME         CHAR(90),
    P_PRINCIP_NAME         CHAR(90),
    P_CORRESP_NAME         CHAR(90),
    O_CORRESP_NAME         CHAR(90),
    O_BENEF_NAME           CHAR(90),
    COMMENTS               CHAR(100),
    constraint IXU_FX_036
        primary key (TUN_UNIT, TUN_DATE, TUN_TRN_SN, TUN_USER, TUN_INTERNAL_SN)
);

