create table TH_TRS_GENERIC_D_RELATION
(
    FK_G_H_W_TRANSACT  INTEGER,
    FK_G_H_W_JUSTIFIC  INTEGER,
    FK_G_H_W_PRODUCTID INTEGER,
    FK_G_H_W_SERIALNUM INTEGER,
    REL_NUMBER         INTEGER,
    SERIAL_NUMBER      INTEGER,
    FK_G_H_W_PRODUCTVD DATE,
    TMSTAMP            DATE,
    REL_TYPE           CHAR(2),
    DESCRIPTION        CHAR(40)
);

