create table TH_TRS_GENERIC_D_WINDOW
(
    PRFT_SYSTEM        SMALLINT,
    GENERIC_SIZE       SMALLINT,
    H_POSITION         SMALLINT,
    V_POSITION         SMALLINT,
    MODULE_NUMBER      INTEGER,
    SEC_NUMBER         INTEGER,
    SERIAL_NUMBER      INTEGER,
    FK_GWH_JUSTIFIC    INTEGER,
    FK_GWH_TRANSACTION INTEGER,
    FK_GWH_PRODUCT_ID  INTEGER,
    LANGUAGE_USED      INTEGER,
    FK_GWH_HPROD_VDATE DATE,
    TMSTAMP            DATE,
    MANDATORY          CHAR(1),
    V_DIRECTION        CHAR(1),
    H_DIRECTION        CHAR(1),
    ITEM_TYPE          CHAR(1),
    GENERIC_TYPE       CHAR(2),
    SEC_TYPE           CHAR(5),
    VAL_RULE_NAME      CHAR(20),
    VALRULE_TABLE_NAME CHAR(20),
    DESCRIPTION        CHAR(40)
);

