create table TH_TRS_GENERIC_H_WINDOW
(
    FK_PRFT_TRANSACT  INTEGER,
    FK_JUSTIFIC       INTEGER,
    FK_HPRODUCT_ID    INTEGER,
    FK_HPRODUCT_VDATE DATE,
    TMSTAMP           DATE,
    DESCRIPTION       CHAR(40)
);

