create table TIME_DEPOS_EXTRAIT
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    TRANS_SER_NUM      INTEGER,
    ENTRY_SER_NUM      SMALLINT,
    PARTICIP_BAL_FLAG  SMALLINT,
    RENEWAL_SER_NUM    INTEGER,
    TRX_UNIT           INTEGER,
    ID_JUSTIFIC        INTEGER,
    ID_TRANSACT        INTEGER,
    P_CR_INTEREST_RATE DECIMAL(8, 4),
    O_CR_INTER_RATE    DECIMAL(8, 4),
    TRX_SN             INTEGER,
    O_DR_INTEREST_RATE DECIMAL(8, 4),
    BOND_NUMBER        DECIMAL(10),
    PREV_ACC_BALANCE   DECIMAL(15, 2),
    ENTRY_AMOUNT       DECIMAL(15, 2),
    TRX_DATE           DATE,
    VALUE_DATE         DATE,
    AVAILABILITY_DATE  DATE,
    TRANSFERED_FLG     CHAR(1),
    PRINTED_LINE_FLAG  CHAR(1),
    NOT_PRINTED_FLG    CHAR(1),
    DEBIT_CREDIT_FLAG  CHAR(1),
    REVERSE_FLAG       CHAR(1),
    TRX_USR            CHAR(8),
    ENTRY_COMMENTS     VARCHAR(40),
    TIMESTAMP          TIMESTAMP(6),
    I_TRX_DATE         DATE,
    I_TRX_UNIT         INTEGER,
    I_TRX_USR          CHAR(8),
    I_TRX_SN           INTEGER
);

create unique index IXU_TIM_002
    on TIME_DEPOS_EXTRAIT (FK_DEPOSIT_ACCOACC, TRANS_SER_NUM, ENTRY_SER_NUM);

