create table TMP_DEP_BSD10
(
    ACCOUNT_NUMBER    DECIMAL(11),
    ENTRY_AMOUNT      DECIMAL(15, 2),
    NXT_ACC_BALANCE   DECIMAL(15, 2),
    PREV_ACC_BALANCE  DECIMAL(15, 2),
    TRX_DATE          DATE,
    DEBIT_CREDIT_FLAG CHAR(1)
);

