create table TMP_REFRESH_LNS_INST
(
    ACC_UNIT           INTEGER,
    ACC_TYPE           SMALLINT,
    ACC_SN             INTEGER,
    TOT_PUB_COMM_AMN   DECIMAL(15, 2),
    TOT_INT_SPRD_AMN   DECIMAL(15, 2),
    TOT_THRDPRT_AMN    DECIMAL(15, 2),
    MP_START_CAP_AMN   DECIMAL(15, 2),
    TOT_DRAWDOWN_AMN   DECIMAL(15, 2),
    TOT_PNL_INT_AMN    DECIMAL(15, 2),
    TOT_NRM_INT_AMN    DECIMAL(15, 2),
    TOT_CAP_AMN        DECIMAL(15, 2),
    TOT_COMMISSION_AMN DECIMAL(15, 2),
    LST_INT_DB_AMN     DECIMAL(15, 2)
);

