create table TMP_AVERAGE_AMT_ENTRY
(
    ENTRY_SER_NUM       SMALLINT,
    TRANS_SER_NUM       INTEGER,
    ID_PRODUCT          INTEGER,
    FK_CURRENCYID_CURR  INTEGER,
    DEP_ACC_NUMBER      DECIMAL(11),
    PREV_BOOK_BAL       DECIMAL(15, 2),
    NEW_AVERAGE_AMT_TOT DECIMAL(15, 2),
    ENTRY_AMOUNT        DECIMAL(15, 2),
    PREV_ACC_BALANCE    DECIMAL(15, 2),
    SUM_AVERAGE_AMT_TOT DECIMAL(15, 2),
    DAYS                DECIMAL(15, 2),
    TRX_DATE            DATE,
    DEBIT_CREDIT_FLAG   CHAR(1),
    FIRST_NAME          CHAR(20),
    SURNAME             CHAR(70),
    DESCRIPTION         VARCHAR(40)
);

create unique index PKTMP_AVERAGE_AMT_ENTRY
    on TMP_AVERAGE_AMT_ENTRY (DEP_ACC_NUMBER, TRANS_SER_NUM, ENTRY_SER_NUM, TRX_DATE);

