create table TMP_J2_ACCOUNTS
(
    FK_AGREEMENTFK_UNI INTEGER,
    FK_AGREEMENTAGR_YE SMALLINT,
    FK_AGREEMENTAGR_SN INTEGER,
    FK_AGREEMENTAGR_ME INTEGER,
    FK_UNITCODE        INTEGER,
    ACC_TYPE           SMALLINT,
    ACC_SN             INTEGER,
    CUST_ID            VARCHAR(4000),
    CNT                DECIMAL(15, 2),
    ACCOUNT_NUMBER     CHAR(40)
);

