create table TMP_USER_DEFINED_FLD
(
    UD_CUSTOMER_CODE  DECIMAL(10),
    UD_ACCOUNT_NUMBER CHAR(40),
    UD_PRFT_SYSTEM    SMALLINT,
    UD_RECORD_TYPE    CHAR(2),
    PFG_TAG_SET_CODE  CHAR(20),
    PFG_TAG           CHAR(10),
    PFG_SET_SN        INTEGER,
    PFG_SET_CATEGORY  CHAR(1),
    SHOW_ORDER        INTEGER,
    FIELD_LABEL       CHAR(40),
    FIELD_VALUE       VARCHAR(100),
    TMSTAMP           TIMESTAMP(6),
    TRX_USER          CHAR(8),
    UD_SN             SMALLINT
);

create unique index PK_COLLFLDTMP1
    on TMP_USER_DEFINED_FLD (UD_SN, UD_PRFT_SYSTEM, UD_ACCOUNT_NUMBER, UD_CUSTOMER_CODE, UD_RECORD_TYPE,
                             PFG_TAG_SET_CODE, PFG_TAG, PFG_SET_SN, PFG_SET_CATEGORY);

