create table TMP_SHARES_ALLOC
(
    SHARE_FROM            DECIMAL(10, 5),
    SHARE_TO              DECIMAL(10, 5),
    MEMBER_NUMBER         DECIMAL(10, 5),
    PERCENT_MEMBER_NUMBER DECIMAL(10, 5),
    PERCENT_SHARES_TOTAL  DECIMAL(10, 5),
    PERCENT_MEMBER_TOTAL  DECIMAL(10, 5),
    SHARES_NUMBER         DECIMAL(10, 5),
    PERCENT_SHARES_NUMBER DECIMAL(10, 5),
    MEMBER_TOTAL          DECIMAL(10, 5),
    SHARES_TOTAL          DECIMAL(15, 5)
);

