create table TMP_MM_1
(
    ACCOUNT_CD         SMALLINT,
    FK_DEAL_COL_BANK   INTEGER,
    FK_SOURCE_CURRENCY INTEGER,
    DEAL_NO            INTEGER,
    RATE               DECIMAL(12, 6),
    ACCRUAL_AMOUNT     DECIMAL(15, 2),
    INTEREST_AMOUNT    DECIMAL(15, 2),
    SOURCE_AMOUNT      DECIMAL(15, 2),
    TARGET_AMOUNT      DECIMAL(15, 2),
    MATURITY_DATE      DATE,
    DEAL_OPERATION     CHAR(1),
    SHORT_DESCR        CHAR(5),
    ACCOUNT_NUMBER     CHAR(40),
    GROUP_RANGE        VARCHAR(10),
    BANK_NAME          VARCHAR(40)
);

