create table TMP_FD_VALEUR_BALANCE
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    INT_CALC_PERIOD    DECIMAL(11),
    VALEUR_BALANCE     DECIMAL(15, 2),
    VALUE_DATE         DATE,
    INIT_BALANCE_FLAG  CHAR(1)
);

