create table TMP_USER_DEF_TABLE
(
    CUSTOMER_CODE  DECIMAL(10),
    ACCOUNT_NUMBER CHAR(40),
    PRFT_SYSTEM    SMALLINT,
    RECORD_TYPE    CHAR(2),
    TAG_SET_CODE   CHAR(20),
    TRX_USER       CHAR(8),
    TMSTAMP        TIMESTAMP(6),
    SN             SMALLINT
);

create unique index PK_TUS
    on TMP_USER_DEF_TABLE (SN, PRFT_SYSTEM, TAG_SET_CODE, RECORD_TYPE, ACCOUNT_NUMBER, CUSTOMER_CODE);

