create table TMP_LNS_ACC_EXCL
(
    ACCOUNT_NUMBER  VARCHAR(40),
    ACCOUNT_CD      SMALLINT,
    LNS_OPEN_UNIT   INTEGER,
    DR_CNTR_GL_ACC  VARCHAR(21),
    OV_ACC_BOOK_BAL DECIMAL(15, 2),
    FIXING          DECIMAL(8, 4),
    ID_CURRENCY     INTEGER,
    OV_ACCR_BAL     DECIMAL(15, 2)
);

