create table TMP_INSIDERS
(
    INSIDER_DESC       VARCHAR(40),
    INSIDER_NAME       VARCHAR(91),
    BORROWER_NAME      VARCHAR(4000),
    AGREEMENT_NUMBER   CHAR(40),
    ACCOUNT_NUMBER     CHAR(40),
    LOAN_CLASS         CHAR(1),
    GROSS_TOTAL        DECIMAL(15),
    FK_GENERIC_DETAFK  CHAR(5),
    FK_GENERIC_DETASER INTEGER
);

