create table TMP_GEO1
(
    EOM_DATE          DATE,
    UNIT_NAME         VARCHAR(40),
    UNIT_CODE         DECIMAL(15, 2),
    COUNTYDESCR       VARCHAR(40),
    CITY              VARCHAR(15),
    YEAR_OPEND        DATE,
    DEP_CNT_ACCOUNTS  DECIMAL(15, 2),
    DEP_TOT_AMOUNT    DECIMAL(15, 2),
    LNS0_CNT_ACCOUNTS DECIMAL(15, 2),
    LNS0_TOT_AMOUNT   DECIMAL(15, 2),
    LNS1_CNT_ACCOUNTS DECIMAL(15, 2),
    LNS1_TOT_AMOUNT   DECIMAL(15, 2)
);

