create table TMP_DEP_GL
(
    CR_TD_CNTR_GL_ACC VARCHAR(21),
    SUM_EUR_BOOKBAL   DECIMAL(15, 2),
    SUM_LEGER_BALANCE DECIMAL(15, 2),
    SUM_CR_LEGER_DIFF DECIMAL(15, 2),
    SUM_GL_BALANCE    DECIMAL(15, 2),
    SUM_CR_GL_DIFF    DECIMAL(15, 2),
    FIXING            DECIMAL(8, 4),
    ID_CURRENCY       INTEGER,
    CR_DR_FLG         CHAR(1)
);

