create table TMP_REFRESH_LNS_OV
(
    ACC_UNIT        INTEGER,
    ACC_TYPE        SMALLINT,
    ACC_SN          INTEGER,
    CAPITAL_AMN     DECIMAL(15, 2),
    EXPENSE_AMN     DECIMAL(15, 2),
    COMMISSION_AMN  DECIMAL(15, 2),
    RL_NRM_INT_AMN  DECIMAL(15, 2),
    URL_NRM_INT_AMN DECIMAL(15, 2),
    ACR_NRM_INT_AMN DECIMAL(15, 2),
    URL_PUB_INT_AMN DECIMAL(15, 2),
    ACR_PUB_INT_AMN DECIMAL(15, 2),
    SUBSIDY_AMN     DECIMAL(15, 2)
);

