create table TMP_DEP_ACC_AT_REST
(
    ACCOUNT_NUMBER    DECIMAL(15),
    ACTIVE_DB_CR_FLAG CHAR(1),
    ACTIVE_TRX_DATE   DATE,
    ACTIVE_TRX_SN     INTEGER,
    ACTIVE_TRX_UNIT   INTEGER,
    ACTIVE_TRX_USR    CHAR(10),
    AMOUNT            DECIMAL(20),
    BOOK_BALANCE      DECIMAL(20),
    ENTRY_STATUS      CHAR(1),
    REST_DATE         DATE,
    REST_DB_CR_FLAG   CHAR(1),
    REST_TRX_DATE     DATE,
    REST_TRX_SN       DECIMAL(10),
    REST_TRX_UNIT     INTEGER,
    REST_TRX_USR      CHAR(10)
);

