create table TMP_TBL_FOR_IB01
(
    ACCOUNT                      CHAR(40)       not null,
    ACCOUNT_CD                   SMALLINT       not null,
    PRFT_SYSTEM                  SMALLINT       not null,
    ACC_TYPE                     SMALLINT       not null,
    ACC_SN                       DECIMAL(13)    not null,
    CUST_ID                      INTEGER        not null,
    ID_PRODUCT                   INTEGER        not null,
    ACC_UNIT                     INTEGER        not null,
    KEY_COLLATERAL_SN            DECIMAL(10)    not null,
    COL_SYSTEM                   SMALLINT       not null,
    ID_CURRENCY                  INTEGER        not null,
    ACC_OPEN_DT                  DATE           not null,
    OV_EXP_DT                    DATE           not null,
    COLLATERAL                   DECIMAL(15, 2) not null,
    COL_EST_VALUE_AMN            DECIMAL(15, 2) not null,
    EUR_COLLATERAL               DECIMAL(15, 2) not null,
    COL_INTERNAL_SN              SMALLINT       not null,
    LOAN_INSTALL_COUNT           SMALLINT,
    LOAN_INSTALL_REMAIN          SMALLINT,
    LOAN_REQ_INSTALL_SN          SMALLINT,
    FK_AGREEMENTAGR_YE           SMALLINT,
    FINSC                        INTEGER,
    CCODE                        INTEGER,
    CLOAN                        INTEGER,
    FK_AGREEMENTAGR_SN           INTEGER,
    FK_AGREEMENTAGR_ME           INTEGER,
    FK_AGREEMENTFK_UNI           INTEGER,
    FIXING                       DECIMAL(8, 4),
    LOAN_OVERDUE_DAYS            DECIMAL(10),
    LOAN_OVERDUE_MONTHS          DECIMAL(10, 2),
    LOAN_REGULATION_DAYS         DECIMAL(10),
    BALANCE                      DECIMAL(15, 2),
    OVERDUE_BALANCE              DECIMAL(15, 2),
    LG_BALANCE                   DECIMAL(15, 2),
    EUR_BALANCE                  DECIMAL(15, 2),
    EUR_OVERDUE                  DECIMAL(15, 2),
    EUR_LG                       DECIMAL(15, 2),
    LG_LIMIT                     DECIMAL(15, 2),
    DEP_BOOK_BAL                 DECIMAL(15, 2),
    EUR_DEP_BOOK_BAL             DECIMAL(15, 2),
    LG_COLLAT_20016              DECIMAL(15, 2),
    EUR_FOR_LG_G6                DECIMAL(15, 2),
    LG_DEFAULT_OVER              DECIMAL(15, 2),
    COLLATERAL_20005             DECIMAL(15, 2),
    COLLATERAL_PROPERTY          DECIMAL(15, 2),
    COLLATERAL_PROPERTY_BAL      DECIMAL(15, 2),
    LOAN_ACC_LIMIT               DECIMAL(15, 2),
    LOAN_OVER_LMT_FOR_NORM       DECIMAL(15, 2),
    LOAN_OVER_PERC               DECIMAL(15, 2),
    LOAN_INSTALL_FIXED_AMN       DECIMAL(15, 2),
    DBASE_EUR_BALANCE            DECIMAL(15, 2),
    DBASE_EUR_OVERDUE            DECIMAL(15, 2),
    PROPERTY_VAL_UPTO_75         DECIMAL(15, 2),
    PROPERTY_VAL_OVER_75         DECIMAL(15, 2),
    EUR_BALANCE_COLUMN_2         DECIMAL(15, 2),
    EUR_BALANCE_COLUMN_2A        DECIMAL(15, 2),
    COMMERCIAL_VAL_AMN           DECIMAL(15, 2),
    PROPERTY_AGREEMENT           DECIMAL(15, 2),
    PROPERTY_ACCOUNT             DECIMAL(15, 2),
    PROPERTY_AGREEMENT_EUR       DECIMAL(15, 2),
    PROPERTY_ACCOUNT_EUR         DECIMAL(15, 2),
    PROPERTY_AGREEMENT_VAL       DECIMAL(15, 2),
    PROPERTY_ACCOUNT_VAL         DECIMAL(15, 2),
    PROPERTY_AGREEMENT_VAL_EUR   DECIMAL(15, 2),
    PROPERTY_ACCOUNT_VAL_EUR     DECIMAL(15, 2),
    ACC_BALANCE_VS_PROPERTY_PERC DECIMAL(15, 4),
    CURR_TRX_DATE                DATE,
    LOAN_STATUS                  CHAR(1),
    LG_OBLIGATION_STS            CHAR(1),
    ACC_MECHANISM                CHAR(1),
    CUST_TYPE                    CHAR(1),
    LOAN_ROW_SETUP               CHAR(5),
    AGREEMENT_NUMBER             CHAR(40),
    constraint IXU_REP_156
        primary key (ACCOUNT, ACCOUNT_CD, PRFT_SYSTEM, ACC_TYPE, ACC_SN, CUST_ID, ID_PRODUCT, ACC_UNIT,
                     KEY_COLLATERAL_SN, COL_SYSTEM, ID_CURRENCY, ACC_OPEN_DT, OV_EXP_DT, COLLATERAL, COL_EST_VALUE_AMN,
                     EUR_COLLATERAL, COL_INTERNAL_SN)
);

