create table TMP_DEP_ACC_EXCL
(
    CR_TD_CNTR_GL_ACC VARCHAR(21),
    ACCOUNT_NUMBER    VARCHAR(40),
    ACCOUNT_CD        SMALLINT,
    DEP_OPEN_UNIT     INTEGER,
    EUR_BOOKBAL       DECIMAL(15, 2),
    ACCR_CR_INTEREST  DECIMAL(15, 2),
    ACCR_DB_INTEREST  DECIMAL(15, 2),
    FIXING            DECIMAL(8, 4),
    ID_CURRENCY       INTEGER
);

