create table TMP_LNS_ACC_GL
(
    ACCOUNT_NUMBER    VARCHAR(40),
    ACCOUNT_CD        SMALLINT,
    LNS_OPEN_UNIT     INTEGER,
    OV_ACC_BOOK_BAL   DECIMAL(15, 2),
    EOM_OV_BALANCE    DECIMAL(15, 2),
    T_E_BOOK_BAL_DIFF DECIMAL(15, 2),
    OV_DR_CNTR_GL_ACC VARCHAR(21),
    LOAN_STATUS       CHAR(1),
    FIXING            DECIMAL(8, 4),
    ID_CURRENCY       INTEGER,
    OV_DR_ACCR_GL_ACC VARCHAR(21),
    OV_ACCR_BAL       DECIMAL(15, 2),
    EOM_ACCR_BALANCE  DECIMAL(15, 2),
    T_E_ACCRUAL_DIFF  DECIMAL(15, 2),
    MKT_CNTRL_GL_ACC  VARCHAR(21),
    MKT_ACCR_BAL      DECIMAL(15, 2),
    ACCOUNT_LIMIT     DECIMAL(15, 2)
);

