create table TMP_AVERAGE_AMT_MM
(
    FK_DEAL_COL_BANK   INTEGER,
    FK_TRX_PRODUCT     INTEGER,
    FK_SOURCE_CURRENCY INTEGER,
    FK_CORRESP_CUST    INTEGER,
    DEAL_NO            INTEGER,
    FK_CORRESP_DEP_ACC DECIMAL(11),
    SOURCE_AMOUNT      DECIMAL(15, 2),
    DEAL_DATE          DATE,
    MATURITY_DATE      DATE,
    DEAL_OPERATION     CHAR(1),
    STATUS             CHAR(1)
);

create unique index PKTMP_AVERAGE_AMT_MM
    on TMP_AVERAGE_AMT_MM (DEAL_NO);

