create table TMP_REFRESH_LNS_INST_1
(
    ACC_UNIT            INTEGER,
    ACC_TYPE            SMALLINT,
    ACC_SN              INTEGER,
    RL_PNL_INT_AMN      DECIMAL(15, 2),
    URL_PNL_INT_AMN     DECIMAL(15, 2),
    ACR_PNL_INT_AMN     DECIMAL(15, 2),
    TOT_EXP_IN_CC_AMN   DECIMAL(15, 2),
    TOT_COM_IN_CC_AMN   DECIMAL(15, 2),
    THRDPRT_AMN         DECIMAL(15, 2),
    TOT_SUBS_INT_AMN    DECIMAL(15, 2),
    TOT_EXPENSE_AMN     DECIMAL(15, 2),
    TOT_CONFIRM_AMN     DECIMAL(15, 2),
    POSITIVE_AMN        DECIMAL(15, 2),
    UNCLEAR_AMN         DECIMAL(15, 2),
    BLOCKED_AMN         DECIMAL(15, 2),
    DORMANT_AMN         DECIMAL(15, 2),
    LAST_NRM_TRX_CNT    DECIMAL(15, 2),
    REQUEST_SN          DECIMAL(15, 2),
    INSTALL_ROUND_AMN   DECIMAL(15, 2),
    COUNTER             DECIMAL(15, 2),
    MAX_REQ_LOAN_STATUS CHAR(1)
);

