create table TMP_SUM_TOT_BAL_RATE_MM
(
    FK_SOURCE_CURRENCY INTEGER,
    DEAL_NO            INTEGER,
    SUM_TOT_BAL_RATE   DECIMAL(15, 2),
    PREV_ACC_BALANCE   DECIMAL(15, 2),
    CURR_AMOUNT        DECIMAL(15, 2)
);

