create table TMP_TBL_FOR_N128
(
    TRX_CURR      INTEGER,
    FIXING        DECIMAL(12, 6),
    EUR_SUM_AMT   DECIMAL(15, 2),
    PROG_BAL_DAYS DECIMAL(15, 2),
    PROG_BAL      DECIMAL(15, 2),
    PREV_AMT      DECIMAL(15, 2),
    SUM_AMT       DECIMAL(15, 2),
    DAYS          INTEGER,
    TRX_DATE      DATE,
    N128_PERC     VARCHAR(10),
    PRODUCT_ID    INTEGER
);

