create table TMP_SUM_TOT_BAL_RATE
(
    FK_CURRENCYID_CURR INTEGER,
    ACCOUNT_NUMBER     DECIMAL(11),
    SUM_TOT_BAL_RATE   DECIMAL(15, 2),
    PREV_ACC_BALANCE   DECIMAL(15, 2),
    CURR_AMOUNT        DECIMAL(15, 2)
);

