create table TMP_LNS_3
(
    C_DIGIT                SMALLINT,
    ACCOUNT_CD             SMALLINT,
    LNS_INSTALL_FREQ       SMALLINT,
    LNS_INSTALL_COUNT      SMALLINT,
    FINSC                  INTEGER,
    INT_CODE               INTEGER,
    ID_PRODUCT             INTEGER,
    CUST_ID                INTEGER,
    N128                   DECIMAL(9, 6),
    PRFT_ACC_AVAILABLE     DECIMAL(15, 2),
    EUR_BALANCE            DECIMAL(15, 2),
    EUR_OVERDUE            DECIMAL(15, 2),
    LNS_FIRST_DRAWDOWN_AMN DECIMAL(15, 2),
    EXPENSES2              DECIMAL(15, 2),
    EXPENSES1              DECIMAL(15, 2),
    INT_BASE_PERC2         DECIMAL(15, 2),
    EXPENSES3              DECIMAL(15, 2),
    FINAL_PERC             DECIMAL(15, 2),
    EUR_BALANCE_OVERDUE    DECIMAL(15, 2),
    NRM_OV_CAPITAL         DECIMAL(15, 2),
    SPREAD                 DECIMAL(15, 2),
    LOAN_STATUS_ID         CHAR(1),
    ACC_MECHANISM_ID       CHAR(1),
    SHORT_DESCR            CHAR(5),
    FIRST_NAME             CHAR(20),
    GL_LNS_NORMAL          CHAR(21),
    GL_LNS_OVERDUE         CHAR(21),
    GL_LNS_DEF_DELAY       CHAR(21),
    GL_LNS_WRITE_OFF       CHAR(21),
    GL_LNS_CREDIT          CHAR(21),
    ACCOUNT                CHAR(40),
    SURNAME                CHAR(70),
    LNS_DRAWDOWN_EXP_DT    VARCHAR(10),
    ACC_EXPIRATION_DT      VARCHAR(10),
    LNS_FIRST_DRAWDOWN_DT  VARCHAR(10),
    PRFT_SYSTEM            VARCHAR(10),
    ACC_OPEN_DT            VARCHAR(10),
    COUNTRY                VARCHAR(20),
    LOAN_STATUS            VARCHAR(22),
    DESCRIPTION            VARCHAR(40),
    PROD_DESCRIPTION       VARCHAR(40),
    INT_CODE_DESC          VARCHAR(40)
);

