create table TMP_LNS_UNIT_GL
(
    LNS_OPEN_UNIT       INTEGER,
    DR_CNTR_GL_ACC      VARCHAR(21),
    SUM_OV_ACC_BOOK_BAL DECIMAL(15, 2),
    SUM_LEGER_BALANCE   DECIMAL(15, 2),
    SUM_DR_LEGER_DIFF   DECIMAL(15, 2),
    SUM_GL_BALANCE      DECIMAL(15, 2),
    SUM_DR_GL_DIFF      DECIMAL(15, 2),
    FIXING              DECIMAL(8, 4),
    ID_CURRENCY         INTEGER
);

