create table TMP_LOAN_ACCOUNT_REPORT
(
    LNS_OPEN_UNIT           INTEGER,
    UNIT_NAME               VARCHAR(40),
    ACCOUNT_NUMBER          CHAR(40),
    ACCOUNT_CD              SMALLINT,
    CUST_ID                 INTEGER,
    C_DIGIT                 SMALLINT,
    SURNAME                 CHAR(70),
    FIRST_NAME              CHAR(20),
    ID_PRODUCT              INTEGER,
    DESCRIPTION             VARCHAR(40),
    NUMBER_OVERDUE_REQUESTS DECIMAL(15, 2),
    BOOK_BALANCE            DECIMAL(15, 2),
    NORMAL_BALANCE          DECIMAL(15, 2),
    OVERDUE_BALANCE         DECIMAL(15, 2),
    NRM_RL_URL_FLG          VARCHAR(20),
    OV_RL_URL_FLG           VARCHAR(20),
    OVERDUE_DATE            DATE,
    DAYS_IN_OVERDUE         DECIMAL(15, 2),
    FINAL_NRM_INTEREST      DECIMAL(15, 2),
    FINAL_OV_INTEREST       DECIMAL(15, 2),
    INTEREST_ID             INTEGER,
    INTEREST_DESC           VARCHAR(40),
    BANK_SPREAD             DECIMAL(12, 6),
    BASE_RATE_CODE_INTEREST INTEGER,
    BASE_RATE_DESC          VARCHAR(80),
    BASE_RATE               DECIMAL(15, 2),
    SPEAD                   DECIMAL(15, 2),
    N128                    DECIMAL(9, 6),
    PENALTY_INTEREST_RATE   DECIMAL(15, 2),
    NRM_URL_INT_BAL         DECIMAL(15, 2),
    OV_URL_INT              DECIMAL(15, 2),
    CREDIT_BALANCE          DECIMAL(15, 2),
    UNCLEAR_AMN             DECIMAL(15, 2),
    NRM_ACCRUAL_AMN         DECIMAL(15, 2),
    OV_ACCRUAL_AMN          DECIMAL(15, 2),
    GL_ACCRUAL_ACC          CHAR(21),
    CR_INT_ACCR_GL_ACC      CHAR(21),
    DR_INT_ACCR_GL_ACC      CHAR(21),
    CR_INT_GL_ACC           CHAR(21),
    DR_INT_GL_ACC           CHAR(21),
    DR_CNTR_GL_ACC          CHAR(21),
    CR_CNTR_GL_ACC          CHAR(21),
    DR_CNTR_GL_ACC_1        CHAR(21),
    DR_CNTR_GL_ACC_2        CHAR(21),
    DR_CNTR_GL_ACC_3        CHAR(21),
    LOAN_STATUS             VARCHAR(14),
    ACC_STATUS              VARCHAR(15)
);

