create table TMP_BOG_REPORT11
(
    GROUP_FLG  SMALLINT,
    CUST_ID    INTEGER,
    FIXING     DECIMAL(12, 6),
    REST_AMN1  DECIMAL(15, 2),
    REST_AMN2  DECIMAL(15, 2),
    REST_AMN3  DECIMAL(15, 2),
    LOAN_AMN2  DECIMAL(15, 2),
    LOAN_AMN11 DECIMAL(15, 2),
    LOAN_AMN1  DECIMAL(15, 2),
    LG_AMN     DECIMAL(15, 2)
);

