create table TMP_MATCHINGS2
(
    ACQ_UNIT_CODE INTEGER,
    DIS_UNIT_CODE INTEGER,
    ACQ_CUST_ID   INTEGER,
    DIS_CUST_ID   INTEGER,
    ACQ_NUM       DECIMAL(10),
    DIS_APPL_ID   DECIMAL(11),
    ACQ_APPL_ID   DECIMAL(11),
    ACQ_PRICE     DECIMAL(15, 2),
    ACQ_DATE      DATE
);

