create table TMP_CMS_CARD_FILES_DATA
(
    LOADACTION                  VARCHAR(1)     not null,
    CARDPROGRAM                 VARCHAR(40),
    CARDSTATUS                  VARCHAR(1)     not null,
    CUSTOMSTATE                 VARCHAR(1)     not null,
    EXPIRYDATE                  DATE,
    HOLDRESPONSECODE            VARCHAR(2)     not null,
    TRACK2VALUE                 VARCHAR(1)     not null,
    TRACK2OFFSET                VARCHAR(1)     not null,
    SECUREPVKI                  VARCHAR(1)     not null,
    SECUREPVV                   VARCHAR(1)     not null,
    INSECUREPVV                 VARCHAR(1)     not null,
    VALIDATIONDATAQUESTION      VARCHAR(1)     not null,
    VALIDATIONDATA              VARCHAR(1)     not null,
    CARDHOLDERRESPONSEINFO      VARCHAR(1)     not null,
    MAILERDESTINATION           VARCHAR(1)     not null,
    COMPANYCARD                 VARCHAR(1)     not null,
    DISCRETIONARYDATA           VARCHAR(6)     not null,
    DATEISSUED                  VARCHAR(509)   not null,
    DATEACTIVATED               VARCHAR(1)     not null,
    ISSUERREFERENCE             VARCHAR(1)     not null,
    BRANCHCODE                  VARCHAR(11),
    INSECUREPVKI                VARCHAR(1)     not null,
    EXTENDEDFIELDS              VARCHAR(51),
    EXPIRYDAY                   VARCHAR(1)     not null,
    FROMDATE                    VARCHAR(254),
    FROMDAY                     VARCHAR(254),
    CONTACTLESSDISCRDATA        VARCHAR(1)     not null,
    DYNAMICCVVKEYINDEX          VARCHAR(1)     not null,
    BATCHNUMBER                 VARCHAR(1)     not null,
    CURRENCYCODE                VARCHAR(11)    not null,
    ACCOUNTPRODUCTID            VARCHAR(11)    not null,
    ACCOUNTPRODUCT              VARCHAR(40)    not null,
    OVERDRAFTLIMIT              DECIMAL(26, 2) not null,
    LASTUPDATEDDATE             VARCHAR(254),
    LASTUPDATEDUSR              VARCHAR(8)     not null,
    ACCOUNTID                   VARCHAR(40),
    ACCOUNTTYPENOMINATED        VARCHAR(2)     not null,
    ACCOUNTTYPEQUALIFIER        VARCHAR(1)     not null,
    ACCOUNTTYPE                 VARCHAR(2)     not null,
    PAN                         VARCHAR(40)    not null,
    PANTYPE                     VARCHAR(1)     not null,
    SEQUENCENUMBER              VARCHAR(3)     not null,
    SEQUENCENUMBER1             VARCHAR(3)     not null,
    GOODSNUMTRANLIMIT           INTEGER        not null,
    GOODSLIMIT                  INTEGER        not null,
    GOODSOFFLINELIMIT           INTEGER        not null,
    CASHNUMTRANLIMIT            INTEGER        not null,
    CASHLIMIT                   INTEGER        not null,
    CASHOFFLINELIMIT            INTEGER        not null,
    CARDNOTPRESENTLIMIT         INTEGER        not null,
    CARDNOTPRESENTOFFLIMIT      INTEGER        not null,
    DEPOSITAVAILLIMIT           DECIMAL(27, 2) not null,
    WEEKGOODSNUMTRANLIMIT       INTEGER        not null,
    WEEKGOODSLIMIT              INTEGER        not null,
    WEEKGOODSOFFLINELIMIT       INTEGER        not null,
    WEEKCASHNUMTRANLIMIT        INTEGER        not null,
    WEEKCASHLIMIT               INTEGER        not null,
    WEEKCASHOFFLINELIMIT        INTEGER        not null,
    WEEKCARDNOTPRESENTLIMIT     INTEGER        not null,
    WEEKCARDNOTPRESENTOFFLIMIT  INTEGER        not null,
    WEEKDEPOSITAVAILLIMIT       INTEGER        not null,
    MONGOODSNUMTRANLIMIT        INTEGER        not null,
    MONGOODSLIMIT               INTEGER        not null,
    MONGOODSOFFLINELIMIT        INTEGER        not null,
    MONCASHNUMTRANLIMIT         INTEGER        not null,
    MONCASHLIMIT                INTEGER        not null,
    MONCASHOFFLINELIMIT         INTEGER        not null,
    MONCARDNOTPRESENTLIMIT      INTEGER        not null,
    MONCARDNOTPRESENTOFFLIMIT   INTEGER        not null,
    MONDEPOSITAVAILLIMIT        INTEGER        not null,
    TRANSGOODSLIMIT             INTEGER        not null,
    TRANSGOODSOFFLINELIMIT      INTEGER        not null,
    TRANSCASHLIMIT              INTEGER        not null,
    TRANSCASHOFFLINELIMIT       INTEGER        not null,
    TRANSCARDNOTPRESENTLIMIT    INTEGER        not null,
    TRANSCARDNOTPRESENTOFFLIMIT INTEGER        not null,
    TRANSDEPOSITAVAILLIMIT      INTEGER        not null,
    PAYMENTNUMTRANLIMIT         INTEGER        not null,
    PAYMENTLIMIT                INTEGER        not null,
    PAYMENTOFFLINELIMIT         INTEGER        not null,
    WEEKPAYMENTNUMTRANLIMIT     INTEGER        not null,
    WEEKPAYMENTLIMIT            INTEGER        not null,
    WEEKPAYMENTOFFLINELIMIT     INTEGER        not null,
    MONTHPAYMENTNUMTRANLIMIT    INTEGER        not null,
    MONTHPAYMENTLIMIT           INTEGER        not null,
    MONTHPAYMENTOFFLIMIT        INTEGER        not null,
    TRANSPAYMENTLIMIT           INTEGER        not null,
    TRANSPAYMENTOFFLINELIMIT    INTEGER        not null,
    CUSTOMERID                  VARCHAR(11),
    NATIONALID                  VARCHAR(20)    not null,
    C1TITLE                     VARCHAR(6),
    C1FIRSTNAME                 VARCHAR(20),
    C1INITIALS                  CHAR(2),
    C1LASTNAME                  VARCHAR(70),
    C1NAMEONCARD                VARCHAR(80),
    C2TITLE                     VARCHAR(1)     not null,
    C2FIRSTNAME                 VARCHAR(1)     not null,
    C2INITIALS                  VARCHAR(1)     not null,
    C2LASTNAME                  VARCHAR(1)     not null,
    C2NAMEONCARD                VARCHAR(1)     not null,
    C3TITLE                     VARCHAR(1)     not null,
    C3FIRSTNAME                 VARCHAR(1)     not null,
    C3INITIALS                  VARCHAR(1)     not null,
    C3LASTNAME                  VARCHAR(1)     not null,
    C3NAMEONCARD                VARCHAR(1)     not null,
    TELEPHONENUMBER             VARCHAR(15),
    MOBILENUMBER                VARCHAR(15),
    FAXNUMBER                   VARCHAR(15),
    EMAILADDRESS                VARCHAR(64),
    POSTALADDRESS1              VARCHAR(40),
    POSTALADDRESS2              VARCHAR(40),
    POSTALCITY                  VARCHAR(30),
    POSTALREGION                VARCHAR(20),
    POSTALCODE                  VARCHAR(10),
    POSTALCOUNTRY               VARCHAR(10),
    OTHERADDRESS1               VARCHAR(1)     not null,
    OTHERADDRESS2               VARCHAR(1)     not null,
    OTHERCITY                   VARCHAR(1)     not null,
    OTHERREGION                 VARCHAR(1)     not null,
    OTHERPOSTALCODE             VARCHAR(1)     not null,
    OTHERCOUNTRY                VARCHAR(1)     not null,
    DATEOFBIRTH                 DATE,
    COMPANYNAME                 VARCHAR(70),
    PREFERREDLANGUAGE           VARCHAR(1)     not null,
    VIP                         VARCHAR(1)     not null,
    APPLICATIONUNIT             INTEGER        not null,
    HASCARD                     VARCHAR(1)     not null,
    VIPLAPSEDATE                VARCHAR(1)     not null,
    INCLUDEINCAF                CHAR(1),
    SECONDARY_ACC               CHAR(1)
);

