create table TOP_TEN_DEPOSITS
(
    ACCOUNT_NUMBER    VARCHAR(40) not null,
    DEPOSIT_TYPE      VARCHAR(40),
    NAME_OF_DEPOSITOR VARCHAR(91),
    BOOK_BALANCE      DECIMAL(15, 2),
    DESCRIPTION       VARCHAR(40),
    RENEWAL_SER_NUM   INTEGER,
    MATURITY_DATE     DATE,
    INTEREST_RATE     DECIMAL(8, 4)
);

