create table TPP_SECOND_DEP_ACC
(
    FK_PRIMARY_DEP_ACC DECIMAL(11),
    FK_SECOND_DEP_ACC  DECIMAL(11),
    TIMESTMP           TIMESTAMP(6),
    PRIMARY_PRFT_ACC   VARCHAR(40),
    SECOND_PRFT_ACC    VARCHAR(40)
);

create unique index IXU_TPP_001
    on TPP_SECOND_DEP_ACC (FK_PRIMARY_DEP_ACC);

