create table TPP_PARAMETERS
(
    CURRENT_YEAR       SMALLINT,
    BLOCK_JUSTIFIC     INTEGER,
    BP_ID_JUSTIFIC     INTEGER,
    BONUS_ID_JUSTIFIC  INTEGER,
    INSUFF_ID_JUSTIFIC INTEGER,
    CHRITM_ID_JUSTIFIC INTEGER,
    DOMESTIC_BANK_IND  CHAR(1)
);

create unique index IXU_TPP_000
    on TPP_PARAMETERS (CURRENT_YEAR);

