create table TPT_UNIT_TOTAL
(
    ACTUAL_YEAR   SMALLINT,
    TRX_UNIT      INTEGER,
    TP_TYPE       CHAR(5),
    TP_NUMBER     DECIMAL(15),
    TPT_TASK      CHAR(8),
    TRX_CURRENCY  INTEGER,
    ACTUAL_MONTH  SMALLINT,
    CR_TAX_AMOUNT DECIMAL(15, 2),
    CR_CHR_AMOUNT DECIMAL(15, 2),
    CR_COM_AMOUNT DECIMAL(15, 2),
    CHR_IN_DC     DECIMAL(15, 2),
    CR_NET_AMOUNT DECIMAL(15, 2),
    DB_COM_AMOUNT DECIMAL(15, 2),
    DB_TAX_AMOUNT DECIMAL(15, 2),
    PREV_BALANCE  DECIMAL(15, 2),
    DB_NET_AMOUNT DECIMAL(15, 2),
    DB_CHR_AMOUNT DECIMAL(15, 2)
);

create unique index IXU_TPT_004
    on TPT_UNIT_TOTAL (ACTUAL_YEAR, TRX_UNIT, TP_TYPE, TP_NUMBER, TPT_TASK, TRX_CURRENCY, ACTUAL_MONTH);

