create table TR_AMK_DTL
(
    FK_TRACCOUNT_UNITC INTEGER  not null,
    FK_TRACCOUNT_TYPE  SMALLINT not null,
    FK_TRACCOUNTACC_SN INTEGER  not null,
    FK_TR_AMK_HDR_CODE INTEGER  not null,
    CERTIFICATION_SN   DECIMAL(10),
    SHARES             DECIMAL(10),
    TOTAL_RIGHTS       DECIMAL(10),
    EXECUTED_RIGHTS    DECIMAL(10),
    NOT_EXECUTED_RIGHT DECIMAL(10),
    RIGHTS_BALANCE     DECIMAL(10),
    ENTRY_COMMENTS     VARCHAR(80),
    constraint IXU_DEP_175
        primary key (FK_TRACCOUNT_UNITC, FK_TRACCOUNT_TYPE, FK_TRACCOUNTACC_SN, FK_TR_AMK_HDR_CODE)
);

