create table TR_MER_DET
(
    FK_TRACCOUNT_UNITC INTEGER  not null,
    FK_TRACCOUNT_TYPE  SMALLINT not null,
    FK_TRACCOUNTACC_SN INTEGER  not null,
    FK_TR_MER_HDR_CODE INTEGER  not null,
    SHARES_SENT        DECIMAL(10),
    MERDET_SHARES      DECIMAL(10),
    SHARES_TO_SEND     DECIMAL(10),
    MERDET_AMN_SENT    DECIMAL(15, 2),
    MERDET_AMN_TO_SEND DECIMAL(15, 2),
    MERDET_WHOLE_AMNT  DECIMAL(15, 2),
    PAYMENT_DATE       DATE,
    ENTRY_COMMENTS     VARCHAR(80),
    constraint IXU_DEP_146
        primary key (FK_TRACCOUNT_UNITC, FK_TRACCOUNT_TYPE, FK_TRACCOUNTACC_SN, FK_TR_MER_HDR_CODE)
);

