create table TR_PROXY_VOTE_DT
(
    FK_TRACCOUNT_UNITC INTEGER  not null,
    FK_TRACCOUNT_TYPE  SMALLINT not null,
    FK_TRACCOUNTACC_SN INTEGER  not null,
    FK_TR_PROXYVOTECOD INTEGER  not null,
    BLOCK_CODE         INTEGER,
    PARTCIP_STOCKS     DECIMAL(10),
    PROXY_AVAIL_BAL    DECIMAL(10),
    REPRESENT_FLAG     CHAR(1),
    ENTRY_COMMENTS     VARCHAR(80),
    constraint IXU_DEP_163
        primary key (FK_TRACCOUNT_UNITC, FK_TRACCOUNT_TYPE, FK_TRACCOUNTACC_SN, FK_TR_PROXYVOTECOD)
);

