create table TR_VOTE
(
    FK_TRPROXYVOT_UNIT INTEGER  not null,
    FK_TRPROXYVOT_ACSN INTEGER  not null,
    FK_TRPROXYVOT_TYPE SMALLINT not null,
    FK_TR_PROXYVOTECOD INTEGER  not null,
    ARTICLE_NO         SMALLINT not null,
    ABSTAIN_SHARES     DECIMAL(10),
    AGAINST_SHARES     DECIMAL(10),
    FOR_SHARES         DECIMAL(10),
    constraint IXU_DEP_149
        primary key (FK_TRPROXYVOT_UNIT, FK_TRPROXYVOT_ACSN, FK_TRPROXYVOT_TYPE, FK_TR_PROXYVOTECOD, ARTICLE_NO)
);

