create table TRACCOUNT
(
    FK_UNITCODE        INTEGER,
    ACC_TYPE           SMALLINT,
    ACC_SN             INTEGER,
    SECURITIES_TYPE    SMALLINT,
    ACC_CD             SMALLINT,
    CRDR_DEP_ACC_CD    SMALLINT,
    CRDR_DEP_ACC_TYPE  SMALLINT,
    FK_CUST_ADDRESS_SN SMALLINT,
    FKGD_CUST_CATEGORY INTEGER,
    CRDR_DEP_ACC_UNIT  INTEGER,
    LAST_MODIFY_UNIT   INTEGER,
    FK_CURRENCYID_CURR INTEGER,
    CRDR_DEP_ACC_SN    INTEGER,
    FK_CUSTOMERCUST_ID INTEGER,
    FK_CUSTOMER_CUSTID INTEGER,
    TRACCOUNT_CODE     DECIMAL(10),
    EXTERNAL_CODE      DECIMAL(10),
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    LAST_MODIFY_DATE   DATE,
    TMSTAMP            TIMESTAMP(6),
    OPENING_DATE       DATE,
    ACC_KIND           CHAR(1),
    ENTRY_STATUS       CHAR(1),
    HOLDER_COMP_ACC    CHAR(1),
    FINAL_WHLD_TAX_FLG CHAR(1),
    FKGH_CUST_CATEGORY CHAR(5),
    LAST_MODIFY_USR    CHAR(8),
    INVEST_BONDCODE    CHAR(15)
);

create unique index IXU_TRA_008
    on TRACCOUNT (FK_UNITCODE, ACC_TYPE, ACC_SN);

