create table TRANSFER_CANCEL_LO
(
    FK_UNITCODE    INTEGER,
    FILE_DATE_TIME TIMESTAMP(6),
    SUBSYSTEM      CHAR(2),
    ID_TRANSFER    SMALLINT,
    RECNO          INTEGER,
    TOTAL_RECORDS  INTEGER,
    TRANSFER_DATE  DATE,
    STATUS         CHAR(1),
    FK_USRCODE     CHAR(8),
    FILE_NAME      VARCHAR(40)
);

create unique index PXFRCNLG
    on TRANSFER_CANCEL_LO (FK_UNITCODE, FILE_DATE_TIME, SUBSYSTEM, ID_TRANSFER);

