create table TRANSFER_LOG
(
    FK_UNITCODE    INTEGER,
    ID_TRANSFER    SMALLINT,
    SUBSYSTEM      CHAR(2),
    FILE_DATE_TIME TIMESTAMP(6),
    RECNO          INTEGER,
    TOTAL_RECORDS  INTEGER,
    TRANSFER_DATE  DATE,
    STATUS         CHAR(1),
    FK_USRCODE     CHAR(8),
    FILE_NAME      VARCHAR(40)
);

create unique index PKXFRLOG
    on TRANSFER_LOG (FK_UNITCODE, ID_TRANSFER, SUBSYSTEM, FILE_DATE_TIME);

