create table TRANS_PENALTY
(
    FK_DEPOSIT_ACCOACC DECIMAL(11),
    FK_CHANNELID_CHANN INTEGER,
    TRX_INTEREST_CNT   INTEGER,
    PERIOD_TRX_COUNT   INTEGER,
    TRX_PENALTY_SPREAD DECIMAL(8, 4),
    TIMESTMP           TIMESTAMP(6)
);

create unique index IXU_TRA_013
    on TRANS_PENALTY (FK_DEPOSIT_ACCOACC, FK_CHANNELID_CHANN);

