create table TRANSFER_CUST_ERR
(
    TRANSFER_DATE DATE,
    UNIT_CODE     INTEGER,
    SUBSYSTEM     CHAR(2),
    CUST_ID       INTEGER,
    ID_TRANSFER   SMALLINT
);

create unique index IXU_TRA_016
    on TRANSFER_CUST_ERR (TRANSFER_DATE, UNIT_CODE, SUBSYSTEM, CUST_ID);

