create table TRANS_CP_COMMITMEN
(
    FK_TRANS_CP_AGRCP  DECIMAL(10),
    TP_IDENTIFIER      DECIMAL(10),
    PREV_AMN_CURRENCY  INTEGER,
    ACC_CURRENCY       INTEGER,
    MAXIM_DEBIT_AMOUNT DECIMAL(15, 2),
    PREV_MAX_DEBIT_AMN DECIMAL(15, 2),
    TMSTAMP            DATE
);

create unique index IXU_TRA_012
    on TRANS_CP_COMMITMEN (FK_TRANS_CP_AGRCP, TP_IDENTIFIER);

