create table TRANS_CP_AGREEMENT
(
    CP_AGREEMENT_NO    DECIMAL(10),
    CP_AGREEMENT_CD    SMALLINT,
    TP_DEP_ACC_CURRENC INTEGER,
    PREV_AMN_CURRENCY  INTEGER,
    PREV_PEND_ITEM_TAX DECIMAL(15, 2),
    PREV_PEND_CHRG_ITM DECIMAL(15, 2),
    PREV_PEND_CHRG_TAX DECIMAL(15, 2),
    PREV_PEND_CHARGES  DECIMAL(15, 2),
    PREV_CUST_COLL_BAL DECIMAL(15, 2),
    PREV_MAX_CA_AMOUNT DECIMAL(15, 2),
    PREV_MIN_PAR_DB_AM DECIMAL(15, 2),
    CUST_COLLECT_BAL   DECIMAL(15, 2),
    PENDING_CHARG_ITEM DECIMAL(15, 2),
    PENDING_CHARGE_TAX DECIMAL(15, 2),
    PENDING_CHARGES    DECIMAL(15, 2),
    MAX_CASH_ADV_AMNT  DECIMAL(15, 2),
    MIN_PARTIAL_DB_AMN DECIMAL(15, 2),
    PENDING_ITEM_TAX   DECIMAL(15, 2),
    TMSTAMP            DATE,
    CP_AGREEMENT_DESCR VARCHAR(40)
);

create unique index IXU_TRA_011
    on TRANS_CP_AGREEMENT (CP_AGREEMENT_NO);

