create table TRAN_MONTH_PENALTY
(
    ACCOUNT_NUMBER     DECIMAL(10),
    ID_CHANNEL         INTEGER,
    TRANS_YEAR         SMALLINT,
    TRANS_MONTH        SMALLINT,
    PERIOD_TRX_COUNT   INTEGER,
    TRX_PENALTY_SPREAD DECIMAL(8, 4),
    TIMESTMP           TIMESTAMP(6)
);

create unique index IXU_TRA_010
    on TRAN_MONTH_PENALTY (ACCOUNT_NUMBER, ID_CHANNEL, TRANS_YEAR, TRANS_MONTH);

