create table TRAVELER_CHQ_DET
(
    FK_ISSUED_COL_BANK INTEGER,
    FK_BELONG_UNIT     INTEGER,
    FK_TC_CURRENCY     INTEGER,
    FK_DENOMINATIO_TC  INTEGER,
    CHEQUE_AMOUNT_LC   DECIMAL(15, 2),
    TRX_DATE           DATE,
    TIMESTMP           TIMESTAMP(6),
    STATUS             CHAR(1),
    FK_MODIFY_USR      CHAR(8),
    NUMBER0            CHAR(20)
);

create unique index IXU_TRA_018
    on TRAVELER_CHQ_DET (NUMBER0, FK_ISSUED_COL_BANK, FK_BELONG_UNIT, FK_TC_CURRENCY, FK_DENOMINATIO_TC);

