create table TRAVELER_CHQ_STOCK
(
    FK_BELONG_UNIT     INTEGER,
    FK_ISSUED_COL_BANK INTEGER,
    FK_TC_CURRENCY     INTEGER,
    DENOMINATION       INTEGER,
    QUANTITY           INTEGER
);

create unique index IXU_TRA_019
    on TRAVELER_CHQ_STOCK (FK_BELONG_UNIT, FK_ISSUED_COL_BANK, FK_TC_CURRENCY, DENOMINATION);

