create table TRBOND_COUPON
(
    FK_TRBONDBOND_CODE   CHAR(15)     not null,
    SERIAL_NUMBER        SMALLINT     not null,
    TMSTAMP              TIMESTAMP(6) not null,
    LAST_TRX_UNIT        INTEGER,
    COUPON_MATUR_INDEX   DECIMAL(8, 3),
    BOND_START_INDEX     DECIMAL(8, 3),
    TAX_PCTG_RESIDENT    DECIMAL(8, 4),
    TAX_PCTG_NON_RESID   DECIMAL(8, 4),
    BOND_INTEREST_PCTG   DECIMAL(9, 6),
    BOND_START_PERIOD    DATE,
    BOND_END_PERIOD      DATE,
    ENTRY_STATUS         CHAR(1),
    LAST_TRX_USR         CHAR(8),
    COUPON_SERIAL_NUM    DECIMAL(10),
    CAPITAL_AMOUNT       DECIMAL(15, 2),
    INTEREST_AMOUNT      DECIMAL(15, 2),
    INTERBANK_TAX_AMOUNT DECIMAL(15, 2),
    HANDLING_FEE_PCTG    DECIMAL(8, 4)  default 0,
    HANDLING_FEE_AMOUNT  DECIMAL(15, 2) default 0,
    constraint IXU_DEP_165
        primary key (FK_TRBONDBOND_CODE, SERIAL_NUMBER, TMSTAMP)
);

