create table TRIPLET_DCD
(
    FK_PRODUCTID        INTEGER,
    FK_JUSTIFICID       INTEGER,
    FK_PRFT_TRANSACID   INTEGER,
    DCD_RULE_ID         DECIMAL(12),
    DCD_PROJECT_ID      INTEGER,
    DESCRIPTION         VARCHAR(200),
    EXCLUDE_COMBINATION CHAR(1)
);

create unique index IXU_TRI_000
    on TRIPLET_DCD (FK_PRODUCTID, FK_JUSTIFICID, FK_PRFT_TRANSACID);

