create table TRS_SWIFT_202
(
    TRX_REFERENCE_NUMB CHAR(16) not null
        constraint IXU_FX_039
            primary key,
    FK_ISSUE_UNIT      INTEGER,
    FK_SWIFT_COUNTEDAT DATE,
    MSG_CONFIRM_DATE   DATE,
    MSG_SEND_TIME      TIMESTAMP(6),
    TMSTAMP            TIMESTAMP(6),
    ENTRY_STATUS       CHAR(1),
    PRIORITY_CODE      CHAR(2),
    FIN_COPY           CHAR(3),
    MSG_SEND_BNKUSR    CHAR(8),
    MSG_CONFIRM_BNKUSR CHAR(8),
    SWIFT_CODE         CHAR(12),
    RELATED_REFERENCE  CHAR(16),
    VALUE_CURRENCY_AMO CHAR(24),
    SENDERS_CORRESPOND VARCHAR(15),
    ORDERING_INSTITUTI VARCHAR(185),
    BENEFICIARY_INSTIT VARCHAR(185),
    INTERMEDIARY       VARCHAR(185),
    RECEIVERS_CORRESPO VARCHAR(185),
    ACCOUNT_WITH_INSTI VARCHAR(185),
    SENDER_TO_RECEIVER VARCHAR(216)
);

