create table TRSTOREBAL
(
    FK_TRACCOUNT_UNITC   INTEGER  not null,
    FK_TRACCOUNT_TYPE    SMALLINT not null,
    FK_TRACCOUNTACC_SN   INTEGER  not null,
    FK_TRBONDBOND_CODE   CHAR(15) not null,
    FKGH_STORE_CODE      CHAR(5)  not null,
    FKGD_STORE_CODE      INTEGER  not null,
    LAST_NRM_TRX_CNT     INTEGER,
    AVER_ACQUIS_AMOUNT   DECIMAL(15, 2),
    BOND_TRX_AMOUNT      DECIMAL(15, 2),
    BOND_FACE_VALUE      DECIMAL(15, 2),
    MATUR_BLC_INT_TAX    DECIMAL(15, 2),
    MATUR_INTER_TAX      DECIMAL(15, 2),
    MATUR_BLC_FV_INTER   DECIMAL(15, 2),
    MATURITY_INTEREST    DECIMAL(15, 2),
    MATUR_FACE_VALUE     DECIMAL(15, 3),
    MATUR_BLC_FACE_VAL   DECIMAL(15, 2),
    CR_FACE_VALUE        DECIMAL(18, 3),
    DB_FACE_VALUE        DECIMAL(18, 3),
    ACTUAL_QUANTITY      DECIMAL(18, 3),
    XXXREPOS_MAX_BALANCE DECIMAL(18, 3),
    AVAIL_FACE_VALUE     DECIMAL(18, 3),
    SYS_BLOCK_FACE_VAL   DECIMAL(18, 3),
    USR_BLOCK_FACE_VAL   DECIMAL(18, 3),
    TMSTAMP              TIMESTAMP(6),
    constraint IXU_DEP_177
        primary key (FK_TRACCOUNT_UNITC, FK_TRACCOUNT_TYPE, FK_TRACCOUNTACC_SN, FK_TRBONDBOND_CODE, FKGH_STORE_CODE,
                     FKGD_STORE_CODE)
);

