create table TUN_ACCRULE_PREDIC
(
    TRX_INTERNAL_SN SMALLINT,
    AA_ID           SMALLINT,
    TRX_UNIT        INTEGER,
    ID_TRANSACT     INTEGER,
    I_UNIT          INTEGER,
    ID_PRODUCT      INTEGER,
    ID_JUSTIFIC     INTEGER,
    GL_RULE_CODE    INTEGER,
    TRX_SN          INTEGER,
    TRX_DATE        DATE,
    SOURCE_TRN_TYPE CHAR(1),
    TARGET_TRN_TYPE CHAR(1),
    SUBSYSTEM       CHAR(2),
    I_USR           CHAR(8),
    TRX_USR         CHAR(8),
    JUSTIFIC_DESCR  VARCHAR(40),
    TRANSACT_DESCR  VARCHAR(40),
    PRODUCT_DESCR   VARCHAR(40),
    ACC_RULE_DESCR  VARCHAR(40),
    SCEN_DESC       VARCHAR(40)
);

create unique index IXU_TUN_001
    on TUN_ACCRULE_PREDIC (AA_ID, SCEN_DESC, I_USR, TRX_UNIT, TRX_DATE, TRX_USR, TRX_SN, TRX_INTERNAL_SN);

