create table UNIT_CATEGORY_PER_ROLE_AUDIT
(
    TRX_DATE        DATE,
    TRX_UNIT        INTEGER,
    TRX_USER        CHAR(8),
    TRX_USR_SN      INTEGER,
    GRP_SUBSCRIPT   INTEGER,
    TERMINAL_NUMBER VARCHAR(30),
    CODE            CHAR(8),
    OLD_PROFILE     VARCHAR(30),
    NEW_PROFILE     VARCHAR(30),
    TMSTAMP         TIMESTAMP(6)
);

create unique index PK_PROFILE_AUDIT
    on UNIT_CATEGORY_PER_ROLE_AUDIT (TRX_DATE, TRX_UNIT, TRX_USER, TRX_USR_SN, GRP_SUBSCRIPT);

