create table UNSUCCESSFUL_PWD
(
    TMSTAMP         TIMESTAMP(6),
    TERMINAL_ID     CHAR(99),
    UNITCODE        INTEGER,
    USERCODE        CHAR(8),
    ERROR_INDICATOR CHAR(1),
    MAC_ADDRESS     VARCHAR(20)
);

create unique index IXU_UNS_000
    on UNSUCCESSFUL_PWD (USERCODE, UNITCODE, TERMINAL_ID, TMSTAMP);

