create table USER_TRANSACTION_DIARY
(
    TMSTAMP             TIMESTAMP(6) not null,
    TRX_UNIT            INTEGER      not null,
    TRX_DATE            DATE         not null,
    TRX_USR             CHAR(8)      not null,
    TRX_USR_SN          INTEGER      not null,
    TUN_INTERNAL_SN     SMALLINT     not null,
    INTERNAL_SN         INTEGER      not null,
    TRX_CODE            INTEGER,
    TRX_JUSTIFIC        INTEGER,
    ID_CURRENCY         INTEGER,
    ID_CURR_TARGET      INTEGER,
    CASH_CR             DECIMAL(15, 2),
    CASH_DB             DECIMAL(15, 2),
    CASH_DIFF           DECIMAL(15, 2),
    JOURNAL_CR          DECIMAL(15, 2),
    JOURNAL_DB          DECIMAL(15, 2),
    JOURNAL_DIFF        DECIMAL(15, 2),
    CHEQUE_NO           DECIMAL(10),
    ACCOUNT_NUMBER      DECIMAL(11),
    C_DIGIT             SMALLINT,
    NON_FINANCIAL       DECIMAL(15, 2),
    FINANCIAL_IND       INTEGER,
    PRFT_ACCOUNT_NUMBER CHAR(40),
    ACCOUNT_CD          SMALLINT,
    REVERSAL_FLG        CHAR(1),
    PRFT_SYSTEM         SMALLINT,
    COMMENTS            CHAR(100),
    CUST_NAME           CHAR(95),
    ATM_USER            CHAR(1),
    VALUE_DATE          DATE,
    ACC_UNIT            INTEGER,
    ID_CHANNEL          INTEGER,
    SOURCE_TBL_STAMP    TIMESTAMP(6),
    SOURCE_TBL          VARCHAR(80),
    TRA_COUNTER         DECIMAL(15),
    TRA_TAXABLE_FLG     CHAR(1),
    TRA_RECORD_METHOD   VARCHAR(80),
    TRA_LOCAL_CURR      INTEGER,
    TRA_FIXING_RATE     DECIMAL(12, 6),
    TRA_TRX_AMN         DECIMAL(15, 2),
    TRA_TRX_AMN_DOM     DECIMAL(15, 2),
    TRA_TAX_AMN         DECIMAL(15, 2),
    TRA_TAX_AMN_DOM     DECIMAL(15, 2),
    TRA_EXP_AMN         DECIMAL(15, 2),
    TRA_EXP_AMN_DOM     DECIMAL(15, 2),
    TRA_COM_AMN         DECIMAL(15, 2),
    TRA_COM_AMN_DOM     DECIMAL(15, 2),
    TRA_TAX_UNIT        INTEGER,
    TRA_REV_TRX         CHAR(1),
    ORIG_TRX_UNIT       INTEGER,
    ORIG_TRX_USER       CHAR(8),
    ORIG_TRX_DATE       DATE,
    ORIG_TRX_SN         INTEGER,
    ORIG_TRX_INT_SN     SMALLINT,
    SERVICE_NAME        VARCHAR(80),
    DEST_ACC_NUMBER     CHAR(40),
    TRA_FEE_AMN         DECIMAL(15, 2),
    TRA_FEE_AMN_DOM     DECIMAL(15, 2),
    ORIG_TRA_COUNTER    DECIMAL(15),
    constraint IXU_USRTRXD_001
        primary key (TMSTAMP, TRX_UNIT, TRX_DATE, TRX_USR, TRX_USR_SN, TUN_INTERNAL_SN, INTERNAL_SN)
);

