create table USER_DEF_TABLE
(
    CUSTOMER_CODE  DECIMAL(10),
    ACCOUNT_NUMBER CHAR(40),
    PRFT_SYSTEM    SMALLINT,
    RECORD_TYPE    CHAR(2),
    RECORD_DESCR   CHAR(40),
    CUST_ID_1      INTEGER,
    C_DIGIT_1      SMALLINT,
    TAG_SET_CODE   CHAR(20),
    USED_UNIT      INTEGER,
    USED_REC_TYPE  INTEGER not null,
    SN             SMALLINT,
    CREATE_TMSTAMP TIMESTAMP(6),
    CREATE_DATE    DATE,
    STATUS_DESCR   CHAR(80),
    CREATE_UNIT    INTEGER,
    CREATE_USER    CHAR(8),
    UPDATE_DATE    DATE,
    UPDATE_TMSTAMP TIMESTAMP(6),
    UPDATE_UNIT    INTEGER,
    UPDATE_USER    CHAR(8)
);

create unique index PK_CTABLE
    on USER_DEF_TABLE (SN, TAG_SET_CODE, PRFT_SYSTEM, ACCOUNT_NUMBER, CUSTOMER_CODE, RECORD_TYPE);

create unique index USER_DEF_TABLE_IND2
    on USER_DEF_TABLE (TAG_SET_CODE, ACCOUNT_NUMBER);

create unique index USER_DEF_TABLE_IND3
    on USER_DEF_TABLE (TAG_SET_CODE, CUST_ID_1);

