create table USER_DEFINED_FIELDS
(
    UD_CUSTOMER_CODE  DECIMAL(10),
    UD_ACCOUNT_NUMBER CHAR(40),
    UD_PRFT_SYSTEM    SMALLINT,
    UD_RECORD_TYPE    CHAR(2),
    PFG_TAG_SET_CODE  CHAR(20),
    PFG_TAG           CHAR(10),
    PFG_SET_SN        INTEGER,
    PFG_SET_CATEGORY  CHAR(1),
    SHOW_ORDER        INTEGER,
    FIELD_LABEL       CHAR(40),
    FIELD_VALUE       VARCHAR(100),
    UD_SN             SMALLINT,
    LAST_UPD_TMSTAMP  TIMESTAMP(6),
    LAST_UPDATE_DATE  DATE
);

create unique index N3869_UDF
    on USER_DEFINED_FIELDS (PFG_TAG_SET_CODE, UD_ACCOUNT_NUMBER, UD_PRFT_SYSTEM, PFG_TAG, UD_CUSTOMER_CODE, UD_SN,
                            UD_RECORD_TYPE, PFG_SET_CATEGORY);

create unique index PK_COLLFLDUDF
    on USER_DEFINED_FIELDS (UD_SN, UD_PRFT_SYSTEM, UD_ACCOUNT_NUMBER, UD_CUSTOMER_CODE, UD_RECORD_TYPE,
                            PFG_TAG_SET_CODE, PFG_TAG, PFG_SET_SN, PFG_SET_CATEGORY);

