create table USER_TOTAL
(
    FKUNIT_REFERS_TO   INTEGER,
    PRODUCTION_DATE    DATE,
    FK_USRCODE         CHAR(8),
    FK_CURRENCYID_CURR INTEGER,
    PRFT_SYSTEM        INTEGER,
    FK_UNIT_HAS_CORRES INTEGER,
    JOURNAL_CR_DOC_NUM SMALLINT,
    COLLAT_CR_DOC_NUM  SMALLINT,
    FROM_TRX_NUM       SMALLINT,
    COLLAT_DB_DOC_NUM  SMALLINT,
    CASH_DB_DOC_NUM    SMALLINT,
    JOURNAL_DB_DOC_NUM SMALLINT,
    REVCASH_CR_DOC_NUM SMALLINT,
    MEMO_CR_DOC_NUM    SMALLINT,
    REVCASH_DB_DOC_NUM SMALLINT,
    CASH_CR_DOC_NUM    SMALLINT,
    MEMO_DB_DOC_NUM    SMALLINT,
    TOT_TRX_NUM        INTEGER,
    MEMO_CR_TOT_AMNT   DECIMAL(15, 2),
    REVCASH_DB_TOT_AMN DECIMAL(15, 2),
    MEMO_DB_TOT_AMNT   DECIMAL(15, 2),
    CASH_CR_TOT_AMNT   DECIMAL(15, 2),
    COLLAT_CR_TOT_AMNT DECIMAL(15, 2),
    COLLAT_DB_TOT_AMNT DECIMAL(15, 2),
    JOURNAL_DB_TOT_AMN DECIMAL(15, 2),
    JOURNAL_CR_TOT_AMN DECIMAL(15, 2),
    CASH_DB_TOT_AMNT   DECIMAL(15, 2),
    REVCASH_CR_TOT_AMN DECIMAL(15, 2),
    TELLER_STATUS      CHAR(1),
    PRODUCT_TYPE       CHAR(1),
    TMSTAMP            TIMESTAMP(6) default CURRENT TIMESTAMP
);

create unique index IXU_USE_000
    on USER_TOTAL (FKUNIT_REFERS_TO, PRODUCTION_DATE, FK_USRCODE, FK_CURRENCYID_CURR, PRFT_SYSTEM, FK_UNIT_HAS_CORRES);

