create table USER_DEF_FLD_HIST
(
    UD_CUSTOMER_CODE  DECIMAL(10),
    UD_ACCOUNT_NUMBER CHAR(40),
    UD_PRFT_SYSTEM    SMALLINT,
    UD_RECORD_TYPE    CHAR(2),
    PFG_TAG_SET_CODE  CHAR(20),
    PFG_TAG           CHAR(10),
    PFG_SET_SN        INTEGER,
    PFG_SET_CATEGORY  CHAR(1),
    UD_SN             SMALLINT,
    FIELD_LABEL       CHAR(40),
    P_FIELD_VALUE     VARCHAR(100),
    O_FIELD_VALUE     VARCHAR(100),
    HISTORY_SN        INTEGER,
    TRX_DATE          DATE,
    TRX_UNIT          INTEGER,
    TRX_USR           CHAR(8),
    TRX_USR_SN        INTEGER,
    TRX_CODE          INTEGER,
    TMSTAMP           TIMESTAMP(6)
);

create unique index PK_USRDEFFLDHIST
    on USER_DEF_FLD_HIST (UD_SN, UD_PRFT_SYSTEM, UD_ACCOUNT_NUMBER, UD_CUSTOMER_CODE, UD_RECORD_TYPE, PFG_TAG_SET_CODE,
                          PFG_TAG, PFG_SET_SN, PFG_SET_CATEGORY, HISTORY_SN);

