create table USR_TMP
(
    GL_LEVEL           SMALLINT,
    ACCOUNTING_ORIG    SMALLINT,
    OFFSIDE_UNIT       INTEGER,
    AK_SELLER_CODE     INTEGER,
    FK_GENERIC_DETASER INTEGER,
    FK_UNITCODE        INTEGER,
    BOUND_TO_CUST_ID   INTEGER,
    ACTIVATION_DATE    DATE,
    DEACTIVATION_DATE  DATE,
    TMSTAMP            DATE,
    VIRTUAL_USER       CHAR(1),
    ATM_USER           CHAR(1),
    NON_HOUSE_UNIT     CHAR(1),
    ENTRY_STATUS       CHAR(1),
    FK_GENERIC_DETAFK  CHAR(5),
    FKUCATEG_OWNS_AS_3 CHAR(8),
    FKUCATEG_OWNS_AS_2 CHAR(8),
    FKUCATEG_OWNS_MAIN CHAR(8),
    CODE               CHAR(8),
    FK_BANKEMPLOYEEID  CHAR(8),
    SUBSTITUTE_CODE    CHAR(8),
    PASSWORD           CHAR(26)
);

