create table USRTOT_CC_LOG
(
    TMSTAMP             TIMESTAMP(6) not null,
    TRX_UNIT            DECIMAL(5)   not null,
    TRX_DATE            DATE         not null,
    CC_TRX_USR          CHAR(8)      not null,
    REC_TRX_USR         CHAR(8)      not null,
    TRX_USR_SN          DECIMAL(8)   not null,
    TUN_INTERNAL_SN     DECIMAL(4)   not null,
    TRX_CODE            DECIMAL(5),
    TRX_JUSTIFIC        DECIMAL(5),
    ID_CURRENCY         DECIMAL(5),
    ID_CURR_TARGET      DECIMAL(5),
    CASH_CR             DECIMAL(15, 2),
    CASH_DB             DECIMAL(15, 2),
    CASH_DIFF           DECIMAL(15, 2),
    JOURNAL_CR          DECIMAL(15, 2),
    JOURNAL_DB          DECIMAL(15, 2),
    JOURNAL_DIFF        DECIMAL(15, 2),
    CHECK_NO            DECIMAL(10),
    ACCOUNT_NUMBER      DECIMAL(11),
    C_DIGIT             DECIMAL(2),
    NON_FINANCIAL       DECIMAL(15, 2),
    FINANCIAL_IND       DECIMAL(5),
    PRFT_ACCOUNT_NUMBER CHAR(40),
    ACCOUNT_CD          DECIMAL(2),
    REVERSAL_FLG        CHAR(1),
    PRFT_SYSTEM         DECIMAL(2),
    COMMENTS            CHAR(100),
    CUST_NAME           CHAR(95),
    VALUE_DATE          DATE,
    CUST_ID             DECIMAL(7),
    PROFILE_ID          CHAR(8),
    REC_TRX_USER_NAME   VARCHAR(80),
    ORDER_NUMBER        VARCHAR(20),
    constraint USRTOT_CC_LOG_PK
        primary key (TMSTAMP, TRX_UNIT, TRX_DATE, CC_TRX_USR, REC_TRX_USR, TRX_USR_SN, TUN_INTERNAL_SN)
);

