create table UW_CSD_SHAREHOLDER
(
    COMPANY_CODE    CHAR(6),
    FILE_TYPE       SMALLINT,
    PROCESS_DATE    DATE,
    RECORD_SN       INTEGER,
    RECORD_IND      CHAR(2),
    BENEFICIARY_SN  SMALLINT,
    PTS_REGISTRY_CD SMALLINT,
    PTS_ACCOUNT_CD  SMALLINT,
    ITEM_IND        SMALLINT,
    ORDER_ITEMS     DECIMAL(10),
    PTS_REGISTRY    DECIMAL(10),
    PTS_ACCOUNT     DECIMAL(11),
    PAYMENT_AMOUNT  DECIMAL(15, 2),
    ISSUE_ID_DATE   DATE,
    PAYMENT_DATE    DATE,
    ID_IND          CHAR(1),
    PAYMENT_IND     CHAR(1),
    SHAREHOLDER_IND CHAR(1),
    COUNTRY         CHAR(2),
    CITIZEN         CHAR(2),
    ISSUE_COUNTRY   CHAR(2),
    ZIP_CODE        CHAR(10),
    FATHER_NAME     CHAR(15),
    AFM_NO          CHAR(15),
    FAX_NO          CHAR(15),
    TAX_OFFICE_NO   CHAR(15),
    SAT_USER        CHAR(15),
    TELEPHONE       CHAR(15),
    SHORT_DESC      CHAR(15),
    CITY            CHAR(20),
    PROFESSION      CHAR(25),
    ID_NO           CHAR(25),
    FIRST_NAME      CHAR(30),
    ADDRESS         CHAR(40),
    ISSUE_AUTHORITY CHAR(60),
    EMAIL           CHAR(64),
    SURNAME         CHAR(200)
);

create unique index IXU_UW__007
    on UW_CSD_SHAREHOLDER (COMPANY_CODE, FILE_TYPE, PROCESS_DATE, RECORD_SN, RECORD_IND, BENEFICIARY_SN);

