create table UW_TOTALS
(
    FK_UWTOTALS_USRCO  CHAR(8),
    FK_UWTOTALS_UNITCO INTEGER,
    FK_UW_TERMUW_CODE  INTEGER,
    PRODUCTION_DATE    DATE,
    DAILY_ORDERS       INTEGER,
    DAILY_CANCEL_ORDER INTEGER,
    DAILY_CANCEL_STOCK DECIMAL(10),
    DAILY_STOCKS       DECIMAL(10)
);

create unique index IXU_UW__000
    on UW_TOTALS (FK_UWTOTALS_USRCO, FK_UWTOTALS_UNITCO, FK_UW_TERMUW_CODE, PRODUCTION_DATE);

