create table VIRTUAL_ACCOUNTS_LOADER
(
    VIRTUAL_IBAN          CHAR(100) not null,
    CUSTOMER_IDENTIFIER   CHAR(100) not null,
    ACCOUNT_TYPE          VARCHAR(100),
    CUSTOMER_ACCOUNT_NAME VARCHAR(100),
    ADDRESS_1             VARCHAR(35),
    ADDRESS_2             VARCHAR(35),
    ADDRESS_3             VARCHAR(35),
    BEN_CONTR_OWN_FIRST_1 VARCHAR(35),
    BEN_CONTR_OWN_LAST_1  VARCHAR(35),
    BEN_CONTR_OWN_FIRST_2 VARCHAR(35),
    BEN_CONTR_OWN_LAST_2  VARCHAR(35),
    BEN_CONTR_OWN_FIRST_3 VARCHAR(35),
    BEN_CONTR_OWN_LAST_3  VARCHAR(35),
    BEN_CONTR_OWN_FIRST_4 VARCHAR(35),
    BEN_CONTR_OWN_LAST_4  VARCHAR(35),
    BEN_CONTR_OWN_FIRST_5 VARCHAR(35),
    BEN_CONTR_OWN_LAST_5  VARCHAR(35),
    ROW_STATUS            INTEGER,
    ROW_ERR_DESC          VARCHAR(250),
    TMSTAMP               TIMESTAMP(6),
    constraint PK_VIRTUAL_ACCOUNT
        primary key (CUSTOMER_IDENTIFIER, VIRTUAL_IBAN)
);

