CREATE VIEW VISION_REPORTS2_VW  (     REPORT_DT,     MT_DT,     REPORT,     EXCEL_SHEET,     EXCEL_CELL,     CUST_REF,     CUST_RECDESC,     CUSTTYP,     VALUE0,     DAYS_FROM,     DAYS_TO  )  AS       SELECT t.report_dt,              t.mt_dt,              config.report,              config.excel_sheet,              config.excel_cell,              NVL (t.cust_ref, ' ') AS cust_ref,              NVL (t.cust_recdesc, ' ') AS cust_recdesc,              t.custtyp,                (CASE                    WHEN config.amount_flag = 'Y' THEN NVL (SUM (t.loc_amt), 0)                    ELSE 0                 END)              +   (CASE                      WHEN config.accruals = 'Y'                      THEN                         NVL (SUM (t.cumacrloc_amt), 0)                      ELSE                         0                   END)                * (CASE WHEN config.amount_sign = '-' THEN -1 ELSE 1 END)                 AS value0,              days_from,              days_to         FROM isn_cbk_global_trans t, profits_reports_configuration config        WHERE        -- T.REPORT_DT        = TO_DATE ('25/3/2017', 'DD/MM/YYYY')
           t    .trntyp_desc LIKE NVL (config.trn_type, '%')              AND t.hdg LIKE NVL (config.vision_hdg, '%')              AND t.finprod LIKE NVL (config.product, '%')              AND t.hdg_purposes LIKE NVL (config.purpose, '%')              AND t.ccy_loc_for LIKE NVL (config.currency, '%')              AND t.custrgn LIKE NVL (config.origin, '%')              --         AND T.CUSTRGN          = 'RESIDENT'
            --         AND T.ISS_TYP_REC      LIKE NVL (CONFIG.CATEGORY,'%')
            AND T.CUSTTYP LIKE NVL (CONFIG.CATEGORY, '%')     --    and (select TRUNC(MONTHS_BETWEEN(T.MT_DT, TO_DATE ('25/3/2017', 'DD/MM/YYYY')),0)*31 from dual) between nvl(CONFIG.DAYS_FROM,-999999999) and nvl(CONFIG.DAYS_TO,999999999)
   --             AND CONFIG.report      = 'CBK BSM'
   --             AND CONFIG.EXCEL_SHEET = 'Table G'
   --             AND CONFIG.EXCEL_CELL  = 'C9'
   GROUP BY t.report_dt,              t.mt_dt,              t.cust_ref,              t.cust_recdesc,              t.custtyp,              config.report,              config.excel_sheet,              config.excel_cell,              days_from,              days_to,              config.accruals,              config.amount_sign,              config.amount_flag,              config.average_tenor,              config.weighted_average;

