create table VOUCHER
(
    TRX_USR          CHAR(8),
    TRX_UNIT         INTEGER,
    TRX_DATE         DATE,
    TRX_USR_SN       INTEGER,
    ACC_TYPE         SMALLINT,
    ACC_CD           SMALLINT,
    TILL_NO          INTEGER,
    ADVICE_SEQ_1     SMALLINT,
    ADVICE_SEQ_2     SMALLINT,
    ADVICE_SEQ_3     SMALLINT,
    ADVICE_SEQ_4     SMALLINT,
    ADVICE_SEQ_5     SMALLINT,
    ADVICE_SEQ_6     SMALLINT,
    ADVICE_SEQ_7     SMALLINT,
    ADVICE_SEQ_8     SMALLINT,
    ADVICE_SEQ_9     SMALLINT,
    ADVICE_SEQ_10    SMALLINT,
    ADVICE_SEQ_11    SMALLINT,
    ADVICE_SEQ_12    SMALLINT,
    ADVICE_SEQ_13    SMALLINT,
    ADVICE_SEQ_14    SMALLINT,
    ADVICE_SEQ_15    SMALLINT,
    ADVICE_SEQ_16    SMALLINT,
    ADVICE_SEQ_17    SMALLINT,
    ADVICE_SEQ_18    SMALLINT,
    ADVICE_SEQ_19    SMALLINT,
    ADVICE_SEQ_20    SMALLINT,
    ADVICE_SEQ_21    SMALLINT,
    REQUEST_SN       SMALLINT,
    TRANS_CURR       INTEGER,
    EXC_FUND_ID      INTEGER,
    TRX_UNIT_2       INTEGER,
    FINAL_ID_CURR_1  INTEGER,
    FINAL_ID_CURR_2  INTEGER,
    FINAL_ID_CURR_3  INTEGER,
    FINAL_ID_CURR_4  INTEGER,
    FINAL_ID_CURR_5  INTEGER,
    FINAL_ID_CURR_6  INTEGER,
    FINAL_ID_CURR_7  INTEGER,
    FINAL_ID_CURR_8  INTEGER,
    ID_PRODUCT       INTEGER,
    ID_CURR_1        INTEGER,
    ID_CURR_2        INTEGER,
    ID_CURR_3        INTEGER,
    ID_CURR_4        INTEGER,
    ID_CURR_5        INTEGER,
    ID_CURR_6        INTEGER,
    ID_CURR_7        INTEGER,
    ID_CURR_8        INTEGER,
    ID_CURR_9        INTEGER,
    ID_CURR_10       INTEGER,
    ID_CURR_11       INTEGER,
    ID_CURR_12       INTEGER,
    ID_CURR_13       INTEGER,
    ID_CURR_14       INTEGER,
    ID_CURR_15       INTEGER,
    ID_CURR_16       INTEGER,
    ID_CURR_17       INTEGER,
    ID_CURR_18       INTEGER,
    ID_CURR_19       INTEGER,
    ID_CURR_20       INTEGER,
    ID_CURR_21       INTEGER,
    PRFT_SYSTEM      INTEGER,
    ACC_UNIT         INTEGER,
    ID_TRANSACT      INTEGER,
    ID_JUSTIFIC      INTEGER,
    ACC_SN           INTEGER,
    ADVICE_COUNTER   INTEGER,
    VOUCHER_NO       INTEGER,
    ACCNO            DECIMAL(13),
    REQUEST_NO       DECIMAL(13),
    FINAL_AMOUNT_1   DECIMAL(15, 2),
    FINAL_AMOUNT_2   DECIMAL(15, 2),
    FINAL_AMOUNT_3   DECIMAL(15, 2),
    FINAL_AMOUNT_4   DECIMAL(15, 2),
    FINAL_AMOUNT_5   DECIMAL(15, 2),
    FINAL_AMOUNT_6   DECIMAL(15, 2),
    FINAL_AMOUNT_7   DECIMAL(15, 2),
    FINAL_AMOUNT_8   DECIMAL(15, 2),
    TOT_DEB          DECIMAL(15, 2),
    TOT_CRE          DECIMAL(15, 2),
    AMOUNT_59        DECIMAL(15, 2),
    AMOUNT_58        DECIMAL(15, 2),
    AMOUNT_57        DECIMAL(15, 2),
    AMOUNT_56        DECIMAL(15, 2),
    AMOUNT_55        DECIMAL(15, 2),
    AMOUNT_54        DECIMAL(15, 2),
    AMOUNT_53        DECIMAL(15, 2),
    AMOUNT_52        DECIMAL(15, 2),
    AMOUNT_51        DECIMAL(15, 2),
    AMOUNT_50        DECIMAL(15, 2),
    AMOUNT_49        DECIMAL(15, 2),
    AMOUNT_48        DECIMAL(15, 2),
    AMOUNT_47        DECIMAL(15, 2),
    AMOUNT_46        DECIMAL(15, 2),
    AMOUNT_45        DECIMAL(15, 2),
    AMOUNT_44        DECIMAL(15, 2),
    AMOUNT_43        DECIMAL(15, 2),
    AMOUNT_42        DECIMAL(15, 2),
    AMOUNT_41        DECIMAL(15, 2),
    AMOUNT_40        DECIMAL(15, 2),
    AMOUNT_39        DECIMAL(15, 2),
    AMOUNT_38        DECIMAL(15, 2),
    AMOUNT_37        DECIMAL(15, 2),
    AMOUNT_36        DECIMAL(15, 2),
    AMOUNT_35        DECIMAL(15, 2),
    AMOUNT_34        DECIMAL(15, 2),
    AMOUNT_33        DECIMAL(15, 2),
    AMOUNT_32        DECIMAL(15, 2),
    AMOUNT_31        DECIMAL(15, 2),
    AMOUNT_30        DECIMAL(15, 2),
    AMOUNT_29        DECIMAL(15, 2),
    AMOUNT_28        DECIMAL(15, 2),
    AMOUNT_27        DECIMAL(15, 2),
    AMOUNT_26        DECIMAL(15, 2),
    AMOUNT_25        DECIMAL(15, 2),
    AMOUNT_24        DECIMAL(15, 2),
    AMOUNT_23        DECIMAL(15, 2),
    AMOUNT_22        DECIMAL(15, 2),
    AMOUNT_21        DECIMAL(15, 2),
    AMOUNT_20        DECIMAL(15, 2),
    AMOUNT_19        DECIMAL(15, 2),
    AMOUNT_18        DECIMAL(15, 2),
    AMOUNT_17        DECIMAL(15, 2),
    AMOUNT_16        DECIMAL(15, 2),
    AMOUNT_15        DECIMAL(15, 2),
    AMOUNT_14        DECIMAL(15, 2),
    AMOUNT_13        DECIMAL(15, 2),
    AMOUNT_12        DECIMAL(15, 2),
    AMOUNT_11        DECIMAL(15, 2),
    AMOUNT_10        DECIMAL(15, 2),
    AMOUNT_9         DECIMAL(15, 2),
    AMOUNT_8         DECIMAL(15, 2),
    AMOUNT_7         DECIMAL(15, 2),
    AMOUNT_6         DECIMAL(15, 2),
    AMOUNT_5         DECIMAL(15, 2),
    AMOUNT_4         DECIMAL(15, 2),
    AMOUNT_3         DECIMAL(15, 2),
    AMOUNT_2         DECIMAL(15, 2),
    AMOUNT_1         DECIMAL(15, 2),
    TRX_AMOUNT       DECIMAL(15, 2),
    AMOUNT_63        DECIMAL(15, 2),
    AMOUNT_62        DECIMAL(15, 2),
    AMOUNT_61        DECIMAL(15, 2),
    AMOUNT_60        DECIMAL(15, 2),
    RQ_EXPIRE_DT     DATE,
    DATETIMESTAMP    TIMESTAMP(6),
    VALEUR           DATE,
    DEB_CRE_1        CHAR(1),
    DEB_CRE_2        CHAR(1),
    DEB_CRE_3        CHAR(1),
    DEB_CRE_4        CHAR(1),
    DEB_CRE_5        CHAR(1),
    FINAL_CURR_1     CHAR(5),
    FINAL_CURR_2     CHAR(5),
    FINAL_CURR_3     CHAR(5),
    FINAL_CURR_4     CHAR(5),
    FINAL_CURR_5     CHAR(5),
    FINAL_CURR_6     CHAR(5),
    FINAL_CURR_7     CHAR(5),
    FINAL_CURR_8     CHAR(5),
    CURR_1           CHAR(5),
    CURR_2           CHAR(5),
    CURR_3           CHAR(5),
    CURR_4           CHAR(5),
    CURR_5           CHAR(5),
    CURR_6           CHAR(5),
    CURR_7           CHAR(5),
    CURR_8           CHAR(5),
    CURR_9           CHAR(5),
    CURR_10          CHAR(5),
    CURR_11          CHAR(5),
    CURR_12          CHAR(5),
    CURR_13          CHAR(5),
    CURR_14          CHAR(5),
    CURR_15          CHAR(5),
    CURR_16          CHAR(5),
    CURR_17          CHAR(5),
    CURR_18          CHAR(5),
    CURR_19          CHAR(5),
    CURR_20          CHAR(5),
    CURR_21          CHAR(5),
    PROFILE_1        CHAR(8),
    ACCOUNT_KIND     CHAR(8),
    TRX_USR_1        CHAR(8),
    TRX_USR_2        CHAR(8),
    REQUEST_TYPE     CHAR(10),
    LOAN_STATUS      CHAR(10),
    FILLER_3         CHAR(12),
    FILLER_4         CHAR(12),
    FILLER_5         CHAR(12),
    FILLER_6         CHAR(12),
    FILLER_7         CHAR(12),
    FILLER_8         CHAR(12),
    FILLER_9         CHAR(12),
    FILLER_10        CHAR(12),
    FILLER_11        CHAR(12),
    FILLER_12        CHAR(12),
    FILLER_13        CHAR(12),
    FILLER_14        CHAR(12),
    FILLER_15        CHAR(12),
    FILLER_16        CHAR(12),
    FILLER_17        CHAR(12),
    FILLER_18        CHAR(12),
    FILLER_19        CHAR(12),
    FILLER_20        CHAR(12),
    FILLER_21        CHAR(12),
    FILLER_1         CHAR(12),
    FILLER_2         CHAR(12),
    VOUCHER_TYPE     CHAR(30),
    JUST_PROD_DESCR  CHAR(40),
    AGREEMENT_NO     CHAR(40),
    TEXT0            CHAR(40),
    UNIT_NAME        CHAR(40),
    TRANS_DESCR      CHAR(40),
    CUSTOMER2        CHAR(80),
    TEXT5            CHAR(80),
    CUSTOMER1        CHAR(80),
    TEXT1            CHAR(80),
    TEXT2            CHAR(80),
    TEXT3            CHAR(80),
    TEXT4            CHAR(80),
    TEXT200          CHAR(200),
    PROD_DESCRIPTION VARCHAR(40)
);

create unique index IXU_VOU_000
    on VOUCHER (TRX_USR, TRX_UNIT, TRX_DATE, TRX_USR_SN);

