create table W_AGG_EOM_COLLAT_REALESTAT
(
    EOM_DATE                      DATE,
    COLLAT_PKEY                   VARCHAR(4000),
    COLLAT_ACCT_NUMBER            CHAR(40),
    COLLAT_ACCT_PROFITS_SYSTEM    INTEGER,
    COLLAT_ACCT_CUST_ID           DECIMAL(15, 2),
    ACCOUNT_NUMBER                CHAR(40),
    CUST_ID                       DECIMAL(15, 2),
    FK_COLLATERALFK_UN            INTEGER     not null,
    FK_COLLATERALFK_CO            INTEGER     not null,
    FK_COLLATERALCOLLA            DECIMAL(10) not null,
    ACCT_COLL_INTERNAL_SN         SMALLINT    not null,
    COLLATERAL_STATUS             CHAR(1),
    COLLAT_DTL_INTERNAL_SN        DECIMAL(15, 2),
    EST_VALUE_AMN                 DECIMAL(15, 2),
    REFERENCE_NUMBER              CHAR(20),
    PRENOTATION_AMN               DECIMAL(15, 2),
    RE_CUST_ID                    INTEGER,
    PROPERTYID                    DECIMAL(10),
    PLEDGE_COLLAT_DTL_INTERNAL_SN DECIMAL(15, 2),
    PROPERTY_CUST_ID              INTEGER,
    TOTALADMINISTRATIVEVALUE      DECIMAL(15, 2),
    RETYP                         VARCHAR(40),
    RE_EVALUATORS                 VARCHAR(500),
    EVALUATION_DATE               DATE,
    TOT_EST_VALUE_AMN             DECIMAL(15, 2),
    RECORD_DESCR                  CHAR(40),
    COLLAT_TYPE_DESC              VARCHAR(40),
    YIELD_LIMIT_AMN               DECIMAL(15, 2),
    COLLAT_ACCT_KEY               DECIMAL(11),
    ACCT_KEY                      DECIMAL(11)
);

