create table W_EOM_LEASING
(
    EOM_DATE                       DATE     not null,
    ACCOUNT_NUMBER_CFMS            CHAR(40) not null,
    CUSTOMER_ID_CFMS               INTEGER,
    ACCOUNT_SUBCLASS_CFMS          CHAR(2),
    ACCOUNT_FINAL_SUBCLASS_PROFITS CHAR(2),
    ACCOUNT_CLASSIFICATION_CFMS    DATE,
    FINAL_CLASSIFIC_DT_PROFITS     DATE,
    NORMAL_CAPITAL_BALANCE_CFMS    DECIMAL(15, 2),
    OVERDUE_CAPITAL_BALANCE_CFMS   DECIMAL(15, 2),
    PROVISIONS_AMOUNT_PROFITS      DECIMAL(15, 2),
    PROVISIONS_CALC_DT_PROFITS     DATE,
    constraint PK_W_EOM_LEASING
        primary key (EOM_DATE, ACCOUNT_NUMBER_CFMS)
);

