create table W_FACT_LOAN_APPLICATION
(
    APPLICATION_ID      VARCHAR(10),
    ACCT_KEY            DECIMAL(11),
    APPLICATION_TYPE    VARCHAR(100),
    APPROVAL_DATE       DATE,
    SALES_PRICE         DECIMAL(15, 2),
    RECEIVE_RENT_AMOUNT DECIMAL(15, 2),
    RESCHEDULING_FLAG   VARCHAR(16)
);

