CREATE VIEW W_GLG_ADBAL_UNPIVOT
(
   YEAR0,
   PERIOD,
   GL_ACCOUNT,
   UNIT_CODE,
   CURRENCY_ID,
   CURRENCY_CODE,
   MONTHDATE_SEQ_NO,
   DEBIT_AMOUNT,
   CREDIT_AMOUNT
)
AS
   SELECT fk_glg_periodyear year0,
          fk_glg_periodperio period,
          fk_glg_accountacco gl_account,
          fk_unitcode unit_code,
          glg_unit_adbal.fk_currencyid_curr currency_id,
          short_descr currency_code,
          monthdate_seq_no,
            flag_01 * (db_amount01)
          + flag_02 * (db_amount01 + db_amount02)
          + flag_03 * (db_amount01 + db_amount02 + db_amount03)
          + flag_04 * (db_amount01 + db_amount02 + db_amount03 + db_amount04)
          +   flag_05
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05)
          +   flag_06
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06)
          +   flag_07
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07)
          +   flag_08
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08)
          +   flag_09
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09)
          +   flag_10
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10)
          +   flag_11
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11)
          +   flag_12
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12)
          +   flag_13
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13)
          +   flag_14
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14)
          +   flag_15
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15)
          +   flag_16
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16)
          +   flag_17
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17)
          +   flag_18
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18)
          +   flag_19
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19)
          +   flag_20
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20)
          +   flag_21
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21)
          +   flag_22
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22)
          +   flag_23
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23)
          +   flag_24
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24)
          +   flag_25
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25)
          +   flag_26
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25
               + db_amount26)
          +   flag_27
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25
               + db_amount26
               + db_amount27)
          +   flag_28
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25
               + db_amount26
               + db_amount27
               + db_amount28)
          +   flag_29
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25
               + db_amount26
               + db_amount27
               + db_amount28
               + db_amount29)
          +   flag_30
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25
               + db_amount26
               + db_amount27
               + db_amount28
               + db_amount29
               + db_amount30)
          +   flag_31
            * (  db_amount01
               + db_amount02
               + db_amount03
               + db_amount04
               + db_amount05
               + db_amount06
               + db_amount07
               + db_amount08
               + db_amount09
               + db_amount10
               + db_amount11
               + db_amount12
               + db_amount13
               + db_amount14
               + db_amount15
               + db_amount16
               + db_amount17
               + db_amount18
               + db_amount19
               + db_amount20
               + db_amount21
               + db_amount22
               + db_amount23
               + db_amount24
               + db_amount25
               + db_amount26
               + db_amount27
               + db_amount28
               + db_amount29
               + db_amount30
               + db_amount31)
             debit_amount,
            flag_01 * (cr_amount01)
          + flag_02 * (cr_amount01 + cr_amount02)
          + flag_03 * (cr_amount01 + cr_amount02 + cr_amount03)
          + flag_04 * (cr_amount01 + cr_amount02 + cr_amount03 + cr_amount04)
          +   flag_05
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05)
          +   flag_06
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06)
          +   flag_07
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07)
          +   flag_08
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08)
          +   flag_09
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09)
          +   flag_10
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10)
          +   flag_11
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11)
          +   flag_12
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12)
          +   flag_13
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13)
          +   flag_14
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14)
          +   flag_15
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15)
          +   flag_16
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16)
          +   flag_17
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17)
          +   flag_18
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18)
          +   flag_19
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19)
          +   flag_20
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20)
          +   flag_21
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21)
          +   flag_22
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22)
          +   flag_23
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23)
          +   flag_24
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24)
          +   flag_25
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25)
          +   flag_26
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25
               + cr_amount26)
          +   flag_27
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25
               + cr_amount26
               + cr_amount27)
          +   flag_28
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25
               + cr_amount26
               + cr_amount27
               + cr_amount28)
          +   flag_29
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25
               + cr_amount26
               + cr_amount27
               + cr_amount28
               + cr_amount29)
          +   flag_30
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25
               + cr_amount26
               + cr_amount27
               + cr_amount28
               + cr_amount29
               + cr_amount30)
          +   flag_31
            * (  cr_amount01
               + cr_amount02
               + cr_amount03
               + cr_amount04
               + cr_amount05
               + cr_amount06
               + cr_amount07
               + cr_amount08
               + cr_amount09
               + cr_amount10
               + cr_amount11
               + cr_amount12
               + cr_amount13
               + cr_amount14
               + cr_amount15
               + cr_amount16
               + cr_amount17
               + cr_amount18
               + cr_amount19
               + cr_amount20
               + cr_amount21
               + cr_amount22
               + cr_amount23
               + cr_amount24
               + cr_amount25
               + cr_amount26
               + cr_amount27
               + cr_amount28
               + cr_amount29
               + cr_amount30
               + cr_amount31)
             credit_amount
     FROM glg_unit_adbal
          CROSS JOIN monthday_seq
          JOIN currency
             ON glg_unit_adbal.fk_currencyid_curr = currency.id_currency;

