create table W_LEASING_PORTFOLIO_ANLYSIS
(
    EOM_DATE                  DATE         not null,
    PRODUCT                   INTEGER,
    UNIT                      INTEGER,
    LOAN_STATUS               CHAR(1),
    ACC_STATUS                CHAR(1),
    BRANCH_NAME               VARCHAR(100),
    ASSET_TYPE_ID             VARCHAR(100),
    LOAN_GROUPING             VARCHAR(100),
    REPORTING_DATE            DATE,
    CREDIT_CATEGORY           VARCHAR(100),
    ACCOUNT_NUMBER            VARCHAR(100) not null,
    ACCOUNT_NAME              VARCHAR(100),
    CUSTOMER_ID               INTEGER,
    AGREEMENT_NUMBER          VARCHAR(100),
    CURRENCY_ID               INTEGER,
    FX_RATE                   VARCHAR(10),
    DISBURSMENT_AMOUNT_BASE   DECIMAL(15, 2),
    SANCTIONED_LIMIT_BASE     DECIMAL(15, 2),
    DISBURSMENT_DATE          DATE,
    EXPIRY_DATE               DATE,
    MATURITY_IN_MONTHS        INTEGER,
    PRINCIPAL_BALANCE         DECIMAL(15, 2),
    ACCRUED_INTEREST          DECIMAL(15, 2),
    CHARGES                   DECIMAL(15, 2),
    GROSS_BALANCE_P_PLUS_I    DECIMAL(15, 2),
    ARREARS_BALANCE           DECIMAL(15, 2),
    DAYS_PAST_DUE             INTEGER,
    PAYMENT_FREQ              INTEGER,
    INSTALL_NEXT_DT           DATE,
    INSTALLMENT_AMOUNT        DECIMAL(15, 2),
    INTEREST_RATE             DECIMAL(9, 6),
    RELAT_OFFICER_ID          VARCHAR(100),
    RELAT_OFFICER_NAME        VARCHAR(100),
    FIRST_PAYMENT_DT          DATE,
    NUM_OF_REMAIN_PAYMENTS    INTEGER,
    TOTAL_AMOUNT_PAID         DECIMAL(15, 2),
    SECTOR_CODE               VARCHAR(10),
    SECTOR_DESCR              VARCHAR(100),
    GENERAL_PROVISIONS        VARCHAR(100),
    SPECIFIC_PROVISIONS       VARCHAR(100),
    OPERATIVE_ACCOUNT         VARCHAR(100),
    OPERATIVE_ACCOUNT_BALANCE DECIMAL(15, 2),
    LAST_PAYMENT_AMOUNT       DECIMAL(15, 2),
    LAST_PAYMENT_DT           DATE,
    DIA_SUBCLASSIFIC          VARCHAR(100),
    DOWNGRADED_CLASSIFIC      VARCHAR(100),
    FDC_NUMBER                VARCHAR(100),
    LATE_FEES                 DECIMAL(15, 2),
    BANK_SPREAD               DECIMAL(9, 6),
    SPREAD                    DECIMAL(9, 6),
    LOAN_PURPOSE              VARCHAR(100),
    constraint W_LEASING_PORTFOLIO_ANLYSIS_PK
        primary key (EOM_DATE, ACCOUNT_NUMBER)
);

