create table W_LEASING_PORTFOLIO_PER_CUR
(
    EOM_DATE                  DATE         not null,
    PRODUCT                   INTEGER,
    UNIT                      INTEGER,
    CURRENCY_ID               INTEGER,
    LOAN_STATUS               CHAR(1),
    ACC_STATUS                CHAR(1),
    ACCOUNT_NUMBER            VARCHAR(100) not null,
    CREDIT_FACILITY_NUMBER    VARCHAR(100),
    CUSTOMER_NAME             VARCHAR(80),
    OFFICER                   VARCHAR(80),
    SUPERVISOR                VARCHAR(80),
    NET_AMN_DISBURSED         DECIMAL(15, 2),
    DEFFERED_INTEREST_FOR_WIP DECIMAL(9, 6),
    TOTAL_INTEREST            DECIMAL(9, 6),
    TAXES                     DECIMAL(15, 2),
    AMOUNT_O_STANDING         DECIMAL(15, 2),
    INPUT_VAT                 DECIMAL(15, 2),
    NOT_DUE_PRINCIPAL         DECIMAL(15, 2),
    NOT_DUE_INTEREST          DECIMAL(15, 2),
    PRINCIPAL                 DECIMAL(15, 2),
    INTEREST                  DECIMAL(15, 2),
    OVERDUE_PRINCIPAL         DECIMAL(15, 2),
    OVERDUE_INTEREST          DECIMAL(15, 2),
    OVERDUE_VAT               DECIMAL(15, 2),
    OVERDUE_OTHER             DECIMAL(15, 2),
    YEAR_TO_DATE_INT          DECIMAL(15, 2),
    INTEREST_RECEIVABLE       DECIMAL(15, 2),
    FINANCE_LEASE_FUT_RENTALS DECIMAL(15, 2),
    PROCESSING_FEES           DECIMAL(15, 2),
    PROCESSING_FEES_VAT       DECIMAL(15, 2),
    UNEARNED_PROCESSING_FEES  DECIMAL(15, 2),
    ACCURED_PROCESSING_FEES   DECIMAL(15, 2),
    REGISTRATION_FEES         DECIMAL(15, 2),
    ASSETS_AT_COST            DECIMAL(15, 2),
    DEPRECIATION_TO_DATE      DECIMAL(15, 2),
    WRITTEN_DOWN_VALUE        DECIMAL(15, 2),
    ARREARS                   INTEGER,
    DATE_OF_DISBURSTMENT      DATE,
    TERM                      INTEGER,
    SECTOR                    VARCHAR(100),
    PURPOSE_OF_LEASE          VARCHAR(100),
    DATE_OF_COMPLETION        DATE,
    INTEREST_PERCENTAGE       DECIMAL(9, 6),
    BRANCH_NAME               VARCHAR(50),
    constraint W_LEASING_PORTFOLIO_PER_CUR_PK
        primary key (EOM_DATE, ACCOUNT_NUMBER)
);

