create table W_STG_IAPPLY_LOAN_APPLICATION
(
    ACCOUNT_NUMBER             VARCHAR(40),
    APPROVAL_DATE              DATE,
    DATE_RESCHEDULING_APPROVED DATE
);

create unique index PK_W_STG_IAPPLY_LOAN_APPLIC
    on W_STG_IAPPLY_LOAN_APPLICATION (ACCOUNT_NUMBER);

