create table WFE_COLLATERAL_HDR
(
    APPLICATION_SYSTEM    SMALLINT not null,
    APPLICATION_ID        CHAR(40) not null,
    TOT_VALUE_AMN         DECIMAL(15, 2),
    TOT_INSURED_AMN       DECIMAL(15, 2),
    TOT_MOVEABLE_VALUE    DECIMAL(15, 2),
    TOT_MOVEABLE_INSURED  DECIMAL(15, 2),
    TOT_IMOVEABLE_VALUE   DECIMAL(15, 2),
    TOT_IMOVEABLE_INSURED DECIMAL(15, 2),
    TOT_CASH_VALUE        DECIMAL(15, 2),
    TOT_CASH_INSURED      DECIMAL(15, 2),
    CREATE_UNIT           INTEGER,
    CREATE_DATE           DATE,
    CREATE_USR            CHAR(8),
    CREATE_TMSTAMP        TIMESTAMP(6),
    UPDATE_UNIT           INTEGER,
    UPDATE_DATE           DATE,
    UPDATE_USR            CHAR(8),
    UPDATE_TMSTAMP        TIMESTAMP(6),
    constraint PK_WFE_COLLATERAL_HDR
        primary key (APPLICATION_SYSTEM, APPLICATION_ID)
);

