create table WFE_DETAIL
(
    WFE_DETAIL_ID     DECIMAL(12),
    EXECUTE_USER      CHAR(8),
    EXECUTE_CUSTOMER  INTEGER,
    EXECUTE_SYSTEM    SMALLINT,
    EXECUTE_ACCOUNT   CHAR(40),
    CREATE_UNIT       INTEGER,
    CREATE_DATE       DATE,
    CREATE_USR        CHAR(8),
    CREATE_TMSTAMP    TIMESTAMP(6),
    UPDATE_UNIT       INTEGER,
    UPDATE_DATE       DATE,
    UPDATE_USR        CHAR(8),
    UPDATE_TMSTAMP    TIMESTAMP(6),
    FLOW_START_STAMP  TIMESTAMP(6),
    FLOW_END_STAMP    TIMESTAMP(6),
    FLOW_START_DATE   DATE,
    FLOW_END_DATE     DATE,
    WFE_STATUS        CHAR(1),
    SENT_EMAIL        CHAR(1),
    SENT_SMS          CHAR(1),
    SENT_ALERT        CHAR(1),
    COMMENTS_DETAILED VARCHAR(2048),
    FK_WF_HEADER_ID   DECIMAL(10),
    FK_WFE_HEADER_ID  DECIMAL(12),
    FK_WFDTL_ID       DECIMAL(10),
    FK_WFDTL_WFHDR_ID DECIMAL(10),
    UPDATE_USER_SN    CHAR(8),
    WFE_DETAIL_STATUS CHAR(1)
);

create unique index PK_WFE_DTL
    on WFE_DETAIL (WFE_DETAIL_ID, FK_WF_HEADER_ID, FK_WFE_HEADER_ID, FK_WFDTL_ID, FK_WFDTL_WFHDR_ID);

