create table WFE_USERS_STATS
(
    EXECUTE_USER    CHAR(8),
    EXECUTE_UNIT    INTEGER,
    INITIATED_FLOWS DECIMAL(12),
    INITIATED_STEPS DECIMAL(12)
);

create unique index PK_WFE_STATS
    on WFE_USERS_STATS (EXECUTE_USER, EXECUTE_UNIT);

