create table WFE_COLLATERAL_DTL
(
    WFE_COLLATERALS_ID  DECIMAL(10) not null,
    APPLICATION_SYSTEM  SMALLINT    not null,
    APPLICATION_ID      CHAR(40)    not null,
    COLLATERAL_SN       DECIMAL(10) not null,
    COLLATERAL_UNIT     INTEGER,
    COLLATERAL_PRODUCT  INTEGER,
    COLLATERAL_NOTES    VARCHAR(2048),
    COLLATERAL_CURRENCY INTEGER,
    COLLTBL_CUST_ID     INTEGER,
    COLLTBL_C_DIGIT     SMALLINT,
    COLLTBL_INTERNAL_SN DECIMAL(10),
    COLLTBL_RECORD_TYPE CHAR(2),
    CREATE_UNIT         INTEGER,
    CREATE_DATE         DATE,
    CREATE_USR          CHAR(8),
    CREATE_TMSTAMP      TIMESTAMP(6),
    UPDATE_UNIT         INTEGER,
    UPDATE_DATE         DATE,
    UPDATE_USR          CHAR(8),
    UPDATE_TMSTAMP      TIMESTAMP(6),
    ENTRY_STATUS        CHAR(1),
    constraint PK_WFE_COLLATERAL_DTL
        primary key (APPLICATION_ID, APPLICATION_SYSTEM, WFE_COLLATERALS_ID)
);

