create table WFE_SCORE_DTL
(
    SCORE_DTL_SN        DECIMAL(10) not null,
    FK_WFE_CUST_ID      INTEGER     not null,
    FK_WFE_SCORECARD    DECIMAL(10) not null,
    FK_WFE_SCORE_HDR_SN DECIMAL(10) not null,
    FK_WFE_SCORE_DATE   DATE        not null,
    FK_WFS_KPI          DECIMAL(10) not null,
    APPLICATION_SYSTEM  SMALLINT,
    APPLICATION_ID      CHAR(40),
    RESULT_DATA         VARCHAR(4000),
    RESULT_SCORE        DECIMAL(5, 2),
    SCORE_MANUAL_FLG    CHAR(1),
    SCORE_COMMENTS      VARCHAR(500),
    SCORE_MANUAL_RESULT DECIMAL(5, 2),
    CREATE_UNIT         INTEGER,
    CREATE_DATE         DATE,
    CREATE_USR          CHAR(8),
    CREATE_TMSTAMP      TIMESTAMP(6),
    UPDATE_UNIT         INTEGER,
    UPDATE_DATE         DATE,
    UPDATE_USR          CHAR(8),
    UPDATE_TMSTAMP      TIMESTAMP(6),
    ENTRY_STATUS        CHAR(1),
    RESULT_SCORE_SN     DECIMAL(10),
    constraint PK_WFE_SCORE_DTL
        primary key (SCORE_DTL_SN, FK_WFE_CUST_ID, FK_WFE_SCORECARD, FK_WFE_SCORE_HDR_SN, FK_WFE_SCORE_DATE, FK_WFS_KPI)
);

