create table WFE_DTL_PREREQ
(
    FK_WFE_DETAIL_ID   DECIMAL(12),
    FK_WF_HEADER_ID    DECIMAL(10),
    FK_WFE_HEADER_ID   DECIMAL(12),
    FK_WFDTL_ID        DECIMAL(10),
    FK_WFDTL_WFHDR_ID  DECIMAL(10),
    INTERNAL_SN        SMALLINT,
    INDICATOR_SN       SMALLINT,
    PREREQ_INDICATOR   CHAR(1),
    FIELD_1_INDIC      CHAR(1),
    FIELD_1_SN         SMALLINT,
    PREREQ_FUNCTION    CHAR(5),
    FIELD_2_INDIC      CHAR(1),
    FIELD_2_SN         SMALLINT,
    PREREQ_EXEC_STATUS CHAR(1),
    FIELD1_EXEC_STATUS CHAR(1),
    FIELD2_EXEC_STATUS CHAR(1)
);

create unique index PK_WFE_PREREQ
    on WFE_DTL_PREREQ (FK_WF_HEADER_ID, FK_WFE_HEADER_ID, FK_WFE_DETAIL_ID, FK_WFDTL_ID, FK_WFDTL_WFHDR_ID,
                       INDICATOR_SN, INTERNAL_SN);

