create table WFS_DTL_PREREQ
(
    INTERNAL_SN      SMALLINT,
    FK_WF_HEADER     DECIMAL(10),
    FK_WF_DETAIL     DECIMAL(10),
    PREREQ_INDICATOR CHAR(1),
    INDICATOR_SN     SMALLINT,
    FIELD_1_INDIC    CHAR(1),
    FIELD_1_SN       SMALLINT,
    FIELD_2_INDIC    CHAR(1),
    FIELD_2_SN       SMALLINT,
    PREREQ_FUNCTION  CHAR(5),
    PREREQ_STATUS    CHAR(1),
    DESCRIPTION_1    VARCHAR(80),
    DESCRIPTION_2    VARCHAR(80)
);

create unique index PK_WFS_PREREQ
    on WFS_DTL_PREREQ (INTERNAL_SN, INDICATOR_SN, FK_WF_HEADER, FK_WF_DETAIL);

