create table WFS_DTL_PROFILES
(
    PROFILE_ID     CHAR(8),
    FK_WF_HEADER   DECIMAL(10),
    FK_WF_DETAIL   DECIMAL(10),
    PROFILE_STATUS CHAR(1)
);

create unique index PK_WFD_PROFL
    on WFS_DTL_PROFILES (PROFILE_ID, FK_WF_HEADER, FK_WF_DETAIL);

