create table WFS_SCORECARD_FLOW
(
    SCORE_FLOW_SN    DECIMAL(10) not null,
    FK_WFS_HEADER    DECIMAL(10) not null,
    FK_WFS_SCORECARD DECIMAL(10) not null,
    SCORE_FLOW_DESCR VARCHAR(80),
    CREATE_UNIT      INTEGER,
    CREATE_DATE      DATE,
    CREATE_USR       CHAR(8),
    CREATE_TMSTAMP   TIMESTAMP(6),
    UPDATE_UNIT      INTEGER,
    UPDATE_DATE      DATE,
    UPDATE_USR       CHAR(8),
    UPDATE_TMSTAMP   TIMESTAMP(6),
    ENTRY_STATUS     CHAR(1),
    constraint PK_WFS_SCORECARD_FLOW
        primary key (SCORE_FLOW_SN, FK_WFS_HEADER, FK_WFS_SCORECARD)
);

