create table WFS_HEADER
(
    WF_HDR_ID           DECIMAL(10),
    WF_DESCRIPTION      VARCHAR(80),
    WF_ANALYSIS         VARCHAR(2048),
    CREATE_UNIT         INTEGER,
    CREATE_DATE         DATE,
    CREATE_USR          CHAR(8),
    CREATE_TMSTAMP      TIMESTAMP(6),
    UPDATE_UNIT         INTEGER,
    UPDATE_DATE         DATE,
    UPDATE_USR          CHAR(8),
    UPDATE_TMSTAMP      TIMESTAMP(6),
    FLOWS_STARTED       DECIMAL(10),
    FLOWS_COMPLETED     DECIMAL(10),
    FLOWS_PENDING       DECIMAL(10),
    PRODUCTION_STATUS   CHAR(1),
    WF_STATUS           CHAR(1),
    PROD_ACTIVATE_DT    DATE,
    PROD_DEACTIVATE_DT  DATE,
    AUTHORIZE_RULE      INTEGER,
    ALL_PROFILES        CHAR(1),
    AUTO_ASSOCIATION    CHAR(1),
    MESSAGE_STEPS       CHAR(1),
    MESSAGE_FREQUENCY   CHAR(4),
    FLOW_TIME_LIMIT     CHAR(4),
    SEND_EMAIL          CHAR(1),
    SEND_SMS            CHAR(1),
    SEND_ALERT          CHAR(1),
    HOME_BRANCH         CHAR(1),
    ALL_CURRENCIES      CHAR(1),
    AUTO_USER_ASSIGN    CHAR(1),
    SYSTEM_GD           INTEGER,
    ABBREVIATION        VARCHAR(10),
    DESCRIPTION_SHORT   VARCHAR(10),
    FK_MANDATORY_FIELDS DECIMAL(5)
);

create unique index PK_WFS_HEAD
    on WFS_HEADER (WF_HDR_ID);

