create table WFS_SCORECARD_ELEMENT
(
    ELEMENT_SN       DECIMAL(10) not null,
    FK_WFS_SCORECARD DECIMAL(10) not null,
    FK_WFS_KPI       DECIMAL(10) not null,
    ELEMENT_DESCR    VARCHAR(80),
    SCORECARD_WEIGHT DECIMAL(18, 4),
    CREATE_UNIT      INTEGER,
    CREATE_DATE      DATE,
    CREATE_USR       CHAR(8),
    CREATE_TMSTAMP   TIMESTAMP(6),
    UPDATE_UNIT      INTEGER,
    UPDATE_DATE      DATE,
    UPDATE_USR       CHAR(8),
    UPDATE_TMSTAMP   TIMESTAMP(6),
    ENTRY_STATUS     CHAR(1),
    constraint PK_WFS_SCORECARD_DETAIL
        primary key (ELEMENT_SN, FK_WFS_SCORECARD, FK_WFS_KPI)
);

