create table WFS_DTL_CURRENCIES
(
    ID_CURRENCY     INTEGER,
    FK_WF_HEADER    DECIMAL(10),
    FK_WF_DETAIL    DECIMAL(10),
    CURRENCY_STATUS CHAR(1)
);

create unique index PK_WFD_CUR
    on WFS_DTL_CURRENCIES (ID_CURRENCY, FK_WF_HEADER, FK_WF_DETAIL);

