create table WLT_CUSTOMER
(
    WLT_DATE                   DATE    not null,
    CUST_ID                    INTEGER not null,
    FKUNIT_IS_MONITORE         INTEGER,
    TMSTAMP                    TIMESTAMP(6),
    DATE_OF_BIRTH              DATE,
    BIRTH_CNTRY_CODE           INTEGER,
    BIRTH_CNTRY                VARCHAR(40),
    LAST_UPDATE                DATE,
    MAIL_IND                   VARCHAR(1),
    CUST_TYPE                  CHAR(1),
    VIP_IND                    VARCHAR(1),
    CUST_STATUS                CHAR(1),
    SEX                        CHAR(1),
    NON_RESIDENT               CHAR(1),
    PENSIONER_IND              VARCHAR(1),
    TITLE                      CHAR(6),
    FK0BANKEMPLOYEEID          VARCHAR(8),
    FIRST_NAME                 CHAR(20),
    SURNAME                    CHAR(70),
    FATHER_SURNAME             CHAR(40),
    E_MAIL                     VARCHAR(64),
    LATIN_FIRSTNAME            CHAR(20),
    LATIN_SURNAME              CHAR(70),
    MOBILE_TEL                 VARCHAR(15),
    FATHER_NAME                VARCHAR(20),
    MOTHER_NAME                VARCHAR(20),
    MOTHER_SURNAME             VARCHAR(40),
    AML_STATUS                 VARCHAR(1),
    SALARY_AMN                 DECIMAL(15, 2),
    CUST_OPEN_DATE             DATE,
    NAME_STANDARD              VARCHAR(119),
    AFM_NO                     VARCHAR(20),
    AFM_EXPIRY_DATE            DATE,
    AFM_ISSUE_DATE             DATE,
    ID_NO                      VARCHAR(20),
    ID_EXPIRY_DATE             DATE,
    ID_ISSUE_DATE              DATE,
    ID_ISSUE_CNTRY_ID          INTEGER,
    ID_ISSUE_CNTRY             VARCHAR(40),
    ID_ISSUE_TYPE_ID           INTEGER,
    ID_ISSUE_TYPE              VARCHAR(40),
    ADDRESS_1                  VARCHAR(40),
    ADDRESS_2                  VARCHAR(40),
    CITY                       VARCHAR(30),
    ZIP_CODE                   VARCHAR(10),
    ADDRESS_CNTRY_CODE         INTEGER,
    ADDRESS_CNTRY              VARCHAR(40),
    INSERT_CHANNEL_USER        VARCHAR(40),
    INSERT_SOFT_ID             VARCHAR(10),
    INSERT_REFERENCE_NUMBER    VARCHAR(40),
    UPDATED_CHANNEL_USER       VARCHAR(40),
    UPDATED_SOFT_ID            VARCHAR(10),
    UPDATED_REFERENCE_NUMBER   VARCHAR(40),
    ACTIVATED_CHANNEL_USER     VARCHAR(40),
    ACTIVATED_SOFT_ID          VARCHAR(10),
    ACTIVATED_REFERENCE_NUMBER VARCHAR(40),
    COMMAND                    VARCHAR(80),
    WS_ID                      VARCHAR(20),
    TRX_DATE                   DATE,
    TRX_UNIT                   INTEGER,
    TRX_USR                    VARCHAR(8),
    TRX_USR_SN                 INTEGER,
    constraint WLT_CUSTOMER_PK
        primary key (WLT_DATE, CUST_ID)
);

