create table WLT_EFT_ORDER
(
    WLT_DATE                DATE        not null,
    ORDER_CODE              VARCHAR(20) not null,
    FK_ORDER_CODE           VARCHAR(20),
    ORDER_STATUS            CHAR(1),
    ORDER_AMOUNT            DECIMAL(15, 2),
    ORDER_TYPE              VARCHAR(3),
    ORDER_TIMESTAMP         TIMESTAMP(6),
    ISSUER_CUST_ID          INTEGER,
    BENEF_CUST_ID           INTEGER,
    CREDIT_BIC_ADDRESS      VARCHAR(40),
    CREDIT_BANK_NAME        CHAR(70),
    CREDIT_BANK_COUNTRY     CHAR(2),
    DEBIT_BIC_ADDRESS       VARCHAR(40),
    DEBIT_BANK_NAME         CHAR(70),
    DEBIT_BANK_COUNTRY      CHAR(2),
    PRFT_ACCOUNT            VARCHAR(40),
    ISSUER_IBAN_ACC         VARCHAR(37),
    BENEF_IBAN_ACC          VARCHAR(37),
    GENERIC_ACCOUNT         VARCHAR(40),
    TRX_DATE                DATE,
    REJECTION_CODE          VARCHAR(40),
    EXTERNAL_ID_REF         VARCHAR(40),
    ISSUER_FULLNAME         VARCHAR(100),
    BENEF_FULLNAME          VARCHAR(100),
    CURRENCY_DESC           CHAR(5),
    COMMENTS                VARCHAR(250),
    TRX_UNIT                INTEGER,
    ORDER_EXPENSE           DECIMAL(15, 2),
    ORDER_COMMISSION        DECIMAL(15, 2),
    COLLECTED_AMOUNT        DECIMAL(15, 2),
    SETTLEMENT_AMNT         DECIMAL(15, 2),
    PROCESS_RESULTS         VARCHAR(255),
    REMITTANCE_INFO         VARCHAR(140),
    CLEARING_SYSTEM         CHAR(35),
    CHARGE_BEARER           CHAR(4),
    ORDER_GROUP_2           CHAR(10),
    INSTRUCTION_REF_ID      VARCHAR(40),
    AML_CLEARANCE_FLG       INTEGER,
    INSERT_CHANNEL_USER     VARCHAR(40),
    INSERT_SOFT_ID          VARCHAR(10),
    INSERT_REFERENCE_NUMBER VARCHAR(40),
    WS_ID                   VARCHAR(20),
    COMMAND                 VARCHAR(80),
    BBAN                    DECIMAL(13),
    constraint IXU_CP__611
        primary key (WLT_DATE, ORDER_CODE)
);

