create table WLT_CUST_CERTIFICATES
(
    WLT_DATE                 DATE    not null,
    CUST_ID                  INTEGER not null,
    CMNT_COUNT               INTEGER not null,
    FK_GH_RQTP1              CHAR(5) not null,
    FK_GD_RQTP1              INTEGER not null,
    FK_GH_RQTP2              CHAR(5) not null,
    FK_GD_RQTP2              INTEGER not null,
    FK_GH_RQTP3              CHAR(5) not null,
    FK_GD_RQTP3              INTEGER not null,
    TRX_USER                 CHAR(8) not null,
    TRX_UNIT                 INTEGER not null,
    TRX_DATE                 DATE    not null,
    INSERT_UNIT              INTEGER,
    UPDATE_UNIT              INTEGER,
    ENTRY_STATUS             CHAR(1),
    LINKED_FILE_SN           DECIMAL(15),
    UPDATE_DATE              DATE,
    INSERT_DATE              DATE,
    TMSTAMP                  TIMESTAMP(6),
    LINKED_FILE              CHAR(1),
    SCANNED_FILE             CHAR(1),
    GIVEN_FLAG               CHAR(1),
    UPDATE_USER              CHAR(8),
    INSERT_USER              CHAR(8),
    ENTRY_COMMENTS           CHAR(254),
    EXPIRY_DATE              DATE,
    FILE_NAME                VARCHAR(40),
    FILE_EXTENSION           VARCHAR(4),
    INSERT_CHANNEL_USER      CHAR(40),
    INSERT_SOFT_ID           CHAR(10),
    INSERT_REFERENCE_NUMBER  CHAR(40),
    UPDATED_CHANNEL_USER     CHAR(40),
    UPDATED_SOFT_ID          CHAR(10),
    UPDATED_REFERENCE_NUMBER CHAR(40),
    RQTP1_DESCRIPTION        VARCHAR(40),
    RQTP2_DESCRIPTION        VARCHAR(40),
    RQTP3_DESCRIPTION        VARCHAR(40),
    WS_ID                    VARCHAR(20) default '',
    COMMAND                  VARCHAR(80) default '',
    constraint WLT_CUST_CERTIFICATES_PK
        primary key (WLT_DATE, CMNT_COUNT, CUST_ID, FK_GH_RQTP1, FK_GD_RQTP1, FK_GH_RQTP2, FK_GD_RQTP2, FK_GH_RQTP3,
                     FK_GD_RQTP3, TRX_USER, TRX_UNIT, TRX_DATE)
);

