create table WLT_DEP_TRANSACT
(
    WLT_DATE                  DATE     not null,
    ACCOUNT_NUMBER            CHAR(40) not null,
    TRANS_SER_NUM             INTEGER  not null,
    ENTRY_SER_NUM             INTEGER  not null,
    ACCOUNT_PRODUCT           INTEGER,
    PRODUCT_DESC              VARCHAR(40),
    ID_TRANSACT               INTEGER,
    TRANSACTION_DESCRIPTION   VARCHAR(40),
    ID_JUSTIFIC               INTEGER,
    JUSTIFICATION_DESCRIPTION VARCHAR(40),
    CUSTOMER_NUMBER           INTEGER,
    ACCOUNT_UNIT              INTEGER,
    TRX_UNIT                  INTEGER,
    TRX_DATE                  DATE,
    TRX_USR                   CHAR(8),
    TRX_SN                    INTEGER,
    TUN_INTERNAL_SN           INTEGER,
    ENTRY_AMOUNT              DECIMAL(15, 2),
    DEBIT_CREDIT_FLAG         CHAR(1),
    PREV_ACC_BALANCE          DECIMAL(15, 2),
    NEW_ACC_BALANCE           DECIMAL(15, 2),
    CURRENCY_DESC             CHAR(5),
    REVERSE_FLAG              CHAR(1),
    REVERSED_TRX_FLAG         CHAR(1),
    ENTRY_COMMENTS            VARCHAR(40),
    COMMENTS1                 VARCHAR(40),
    COMMENTS2                 VARCHAR(40),
    COMMENTS3                 VARCHAR(40),
    COMMENTS4                 VARCHAR(40),
    COMMENTS5                 VARCHAR(40),
    COMMENTS6                 VARCHAR(40),
    COMMENTS7                 VARCHAR(40),
    COMMENTS8                 VARCHAR(40),
    COMMENTS9                 VARCHAR(40),
    COMMENTS10                VARCHAR(40),
    COMMENTS11                VARCHAR(40),
    COMMENTS12                VARCHAR(40),
    COMMENTS13                VARCHAR(40),
    COMMENTS14                VARCHAR(40),
    COMMENTS15                VARCHAR(40),
    COMMENTS16                VARCHAR(40),
    COMMENTS17                VARCHAR(40),
    TIMESTAMP                 TIMESTAMP(6),
    I_TRX_DATE                DATE,
    I_TRX_UNIT                INTEGER,
    I_TRX_USR                 CHAR(8),
    I_TRX_SN                  INTEGER,
    MERCHANT_CITY             VARCHAR(100),
    MCC_CODE                  VARCHAR(100),
    MERCHANT_COUNTRY          VARCHAR(100),
    MERCHANT                  VARCHAR(100),
    EFT_ORDER_ID              VARCHAR(40),
    INSERT_CHANNEL_USER       VARCHAR(40),
    INSERT_SOFT_ID            VARCHAR(10),
    INSERT_REFERENCE_NUMBER   VARCHAR(40),
    WS_ID                     VARCHAR(20),
    COMMAND                   VARCHAR(80),
    FX_CCY                    CHAR(5),
    AMT_FX_CCY                DECIMAL(15, 2),
    BBAN                      DECIMAL(13),
    constraint IXU_FST_0001
        primary key (WLT_DATE, ACCOUNT_NUMBER, TRANS_SER_NUM, ENTRY_SER_NUM)
);

