create table WLT_DEP_ACCOUNT
(
    WLT_DATE                DATE     not null,
    ACCOUNT_NUMBER          CHAR(40) not null,
    IBAN                    VARCHAR(50),
    DEP_OPEN_UNIT           INTEGER,
    UNIT_NAME               VARCHAR(40),
    CUST_ID                 INTEGER,
    ID_PRODUCT              INTEGER,
    PRODUCT_DESCRIPTION     VARCHAR(40),
    CURRENCY                CHAR(5),
    BOOK_BALANCE            DECIMAL(15, 2),
    AVAILABLE_BALANCE       DECIMAL(15, 2),
    BLOCKED_BALANCE         DECIMAL(15, 2),
    ENTRY_STATUS            CHAR(1),
    LAST_TRX_DATE           DATE,
    TRANSACTION_CODE        INTEGER,
    OPENING_DATE            DATE,
    LAST_DORMANT_DATE       DATE,
    ACCOUNT_TYPE            CHAR(1),
    CLOSING_DATE            DATE,
    LST_STATEMENT_NUM       INTEGER,
    CLOSING_USER            CHAR(8),
    CLOSING_UNIT            INTEGER,
    INSERT_CHANNEL_USER     VARCHAR(40),
    INSERT_SOFT_ID          VARCHAR(10),
    INSERT_REFERENCE_NUMBER VARCHAR(40),
    WS_ID                   VARCHAR(20),
    COMMAND                 VARCHAR(80),
    TRX_DATE                DATE,
    TRX_UNIT                INTEGER,
    TRX_USR                 VARCHAR(8),
    TRX_USR_SN              INTEGER,
    TIMESTMP                TIMESTAMP(6),
    BBAN                    DECIMAL(13),
    ACCOUNT_DESCRIPTION     CHAR(60),
    constraint WLT_DEP_TRANSACT_PK
        primary key (WLT_DATE, ACCOUNT_NUMBER)
);

