create table WORD_PTJ
(
    FILE_NAME    CHAR(24),
    CODE         INTEGER,
    RULE_ID      DECIMAL(12),
    VOUCHER_FLG  SMALLINT,
    ID_PRODUCT   INTEGER,
    ID_JUSTIFIC  INTEGER,
    ID_TRANSACT  INTEGER,
    PARAMS       CHAR(15),
    INSERT_USER  CHAR(8),
    INSERT_UNIT  INTEGER,
    INSERT_DATE  DATE,
    INSERT_STAMP TIMESTAMP(6),
    UPDATE_USER  CHAR(8),
    UPDATE_UNIT  INTEGER,
    UPDATE_DATE  DATE,
    UPDATE_STAMP TIMESTAMP(6)
);

create unique index IXP_WOR_000
    on WORD_PTJ (ID_PRODUCT, ID_JUSTIFIC, ID_TRANSACT, VOUCHER_FLG);

