create table WRH_INTER_RESULTY13
(
    ACCOUNT_NUMBER    CHAR(40) not null,
    PRFT_SYSTEM       SMALLINT not null,
    NRM_YEAR_NEG_BAL  DECIMAL(15, 2),
    NRM_YEAR_NEG_STEP DECIMAL(15, 2),
    NRM_YEAR_POS_BAL  DECIMAL(15, 2),
    NRM_YEAR_POS_STEP DECIMAL(15, 2),
    OV_YEAR_TRX_BAL   DECIMAL(15, 2),
    OV_YEAR_STEP_AMN  DECIMAL(15, 2),
    CUST_ID           INTEGER,
    PRODUCT_ID        INTEGER,
    CURRENCY_ID       INTEGER,
    UNIT_CODE         INTEGER
);

