create table WRH_INTER_RESULTM13
(
    ACCOUNT_NUMBER     CHAR(40) not null,
    PRFT_SYSTEM        SMALLINT not null,
    NRM_MONTH_NEG_BAL  DECIMAL(15, 2),
    NRM_MONTH_NEG_STEP DECIMAL(15, 2),
    NRM_MONTH_POS_BAL  DECIMAL(15, 2),
    NRM_MONTH_POS_STEP DECIMAL(15, 2),
    OV_MONTH_TRX_BAL   DECIMAL(15, 2),
    OV_MONTH_STEP_AMN  DECIMAL(15, 2),
    CUST_ID            INTEGER,
    PRODUCT_ID         INTEGER,
    CURRENCY_ID        INTEGER,
    UNIT_CODE          INTEGER
);

