create table WRITE_OFF_LOANS
(
    FK_UNITCODE       INTEGER  not null,
    ACC_TYPE          SMALLINT not null,
    ACC_SN            INTEGER  not null,
    ACCOUNT_NUMBER    VARCHAR(40),
    ACCOUNT_CD        SMALLINT,
    PRFT_SYSTEM       SMALLINT,
    NAME_OF_BORROWER  VARCHAR(91),
    OPEN_DATE         DATE,
    DATE_OF_WOL       DATE,
    DEBIT_AMOUNT      DECIMAL(15, 2),
    MATURITY_DATE     DATE,
    TOTAL_NUM_OF_INST SMALLINT,
    NUM_OF_INST_PAID  SMALLINT,
    CREDIT_AMOUNT     DECIMAL(15, 2),
    SECURITY_SAVINGS  DECIMAL(15, 2),
    NUMBER_OF_DAYS_OV SMALLINT,
    CLASS             VARCHAR(40),
    PROVISIONING_RATE DECIMAL(15, 2),
    PREV_PROVISION    DECIMAL(15, 2),
    RECOVERIES_WOL    DECIMAL(15, 2)
);

