create table WSI_SYSTEM_LOG
(
    CHANNEL_EXTERNAL_ID   INTEGER     not null,
    CHANNEL_USER          VARCHAR(40) not null,
    CURR_TRX_DATE         DATE        not null,
    USER_SN               INTEGER     not null,
    CREATE_TMSTAMP        TIMESTAMP(6),
    CHANNEL_PROFITS_ID    INTEGER,
    CHANNEL_PASSWORD      VARCHAR(128),
    PROFITS_UNIQUE_ID     VARCHAR(40),
    REFERENCE_NUMBER      CHAR(40),
    SOFT_ID               VARCHAR(10),
    WS_ID                 VARCHAR(20),
    WS_COMMAND            CHAR(80),
    TIMEOUT_SECONDS       SMALLINT,
    WSI_LOG_STATUS        CHAR(2),
    TMSTAMP_1             TIMESTAMP(6),
    TMSTAMP_2             TIMESTAMP(6),
    TMSTAMP_3             TIMESTAMP(6),
    TMSTAMP_4             TIMESTAMP(6),
    TMSTAMP_C             TIMESTAMP(6),
    TMSTAMP_E             TIMESTAMP(6),
    TMSTAMP_A             TIMESTAMP(6),
    PRFT_TRX_USER         CHAR(8),
    PRFT_TRX_UNIT         INTEGER,
    PRFT_TRX_DATE         DATE,
    PRFT_TRX_USR_SN       INTEGER,
    PRFT_TRX_INTRNL_SN    SMALLINT,
    DECRYPTED_FIELD       VARCHAR(200),
    ERROR_PROFITS         VARCHAR(200),
    ERROR_WSI             VARCHAR(200),
    E0_ACCOUNT_NUMBER     CHAR(40),
    E0_ACCOUNT_CD         SMALLINT,
    E0_PRFT_SYSTEM        SMALLINT,
    E0_CUST_ID            INTEGER,
    E0_C_DIGIT            SMALLINT,
    E0_ID_JUSTIFIC        INTEGER,
    E1_ACTION_ENTRY_DESC  CHAR(20),
    E1_SRV_STATUS         CHAR(6),
    E2_CHAR_80            CHAR(80),
    E3_SRV_STATUS         CHAR(6),
    E3_ACTION_ENTRY       CHAR(2),
    E3_COMMAND            CHAR(80),
    E4_ACTUAL_MESSAGE     VARCHAR(200),
    E4_TRACE_CHAR_80      CHAR(80),
    E4_PRFT_SYSTEM        SMALLINT,
    E4_LANGUAGE           INTEGER,
    E4_TERMINATION_ACTION CHAR(2),
    E4_ROUTINE_SN         DECIMAL(12),
    E4_MESSAGE_TYPE       CHAR(2),
    E4_VALRULE_ID         DECIMAL(12),
    E4_VALRULE_SNUM       INTEGER,
    E4_ID                 DECIMAL(12),
    E_COUNT               INTEGER,
    SERVER_ERROR          VARCHAR(80),
    SERVER_ERROR_TRANS    VARCHAR(80),
    constraint PK_WSI_1003
        primary key (USER_SN, CURR_TRX_DATE, CHANNEL_USER, CHANNEL_EXTERNAL_ID)
);

