create table XXX_DIAS_INCOMING_ORD
(
    REFERENCE_NUMBER       DECIMAL(15) not null
        constraint I0010486
            primary key,
    DIAS_REFERENCE         CHAR(17),
    DIAS_VALUE_DATE        DATE,
    SEND_VALUE             DATE,
    SEND_MOVE              DATE,
    SEND_REFERENCE         CHAR(20),
    TRANS_CODE             CHAR(3),
    TRANS_AMNT             DECIMAL(15, 2),
    TRANS_COMM             DECIMAL(15, 2),
    JUSTIFIC1              CHAR(35),
    JUSTIFIC2              CHAR(35),
    JUSTIFIC3              CHAR(35),
    JUSTIFIC4              CHAR(35),
    ORDER_CUST_NAME        CHAR(35),
    ORDER_CUST_DATA1       CHAR(35),
    ORDER_CUST_DATA2       CHAR(35),
    ORDER_CUST_DATA3       CHAR(35),
    ORDER_ORIGIN           CHAR(1),
    BENEF_CUST_NAME        CHAR(35),
    BENEF_ADDRESS1         CHAR(35),
    BENEF_ADDRESS2         CHAR(24),
    BENEF_ZIP_CODE         CHAR(5),
    BENEF_CITY             CHAR(18),
    BENEF_PHONE1           CHAR(10),
    BENEF_PHONE2           CHAR(10),
    BENEF_ORIGIN           CHAR(1),
    BENEF_ID_TYPE          CHAR(1),
    BENEF_ID_NUM           CHAR(20),
    BENEF_ISSUE_AUTH       CHAR(40),
    BENEF_ACCOUNT          CHAR(27),
    INFORMATION1           CHAR(35),
    INFORMATION2           CHAR(35),
    INFORMATION3           CHAR(35),
    INFORMATION4           CHAR(35),
    INFORMATION5           CHAR(35),
    INFORMATION6           CHAR(35),
    REJECT_CODE            CHAR(3),
    LST_UPDATE_DATE        DATE,
    ENTRY_COMMENTS         CHAR(40),
    ENTRY_STATUS           CHAR(1),
    TMSTAMP                TIMESTAMP(6),
    FILE_DATE              DATE,
    FILE_NAME              CHAR(8),
    FILE_NUMBER            SMALLINT,
    SENDER_DIAS_UNIT       CHAR(4),
    FK_UNITCODE            INTEGER,
    FK0UNITCODE            INTEGER,
    FK_CURRENCYID_CURRENCY INTEGER,
    FK_PRODUCTID_PRODUCT   INTEGER,
    FK_COLLABORATIOBANK_ID INTEGER,
    FK0COLLABORATIOBANK_ID INTEGER,
    FK_CUSTOMERCUST_ID     INTEGER,
    FK0CUSTOMERCUST_ID     INTEGER
);

